### ISSUE TITLE
Error: Invalid Bitcoin Address

### ISSUE THREAD

**Issue by zophonzero** [nicehash/NiceHashMiner-Archived#1]
I'm constantly getting "Error: Invalid Bitcoin Address" as soon as I enter my own address instead of the standard one. Am I missing something? Can't start mining because of this.

**Comment by kenshirothefist** [comment]
Which Bitcoin address are you using? Please make sure you're using valid Bitcoin address here: https:\www.blockchain.info. Or else send screen shot showing this issue to support@nicehash.com.

**Comment by zophonzero** [comment]
I tried multiple addresses, for example: 3LT2jtqp7CmAGUiJF7niMM948n1U4jedVj which seems fine on blockchain.info. 
![bitcoin-error](https://cloud.githubusercontent.com/assets/1099461/10792441/fd99af4a-7d8c-11e5-9e7c-e4961ffde80a.JPG)

**Comment by kenshirothefist** [comment]
Using Multi-Sig (3xxx) addresses is currently not supported. Please use standard address (1xxx). This issue will be resolved in the future version.

**Comment by zophonzero** [comment]
ok, thanks, now it seems to work! Keep up the great work!

**Comment by bitbandi** [comment]
@kenshirothefist change the while in DecodeBase58 to this:

```
...
while (--j >= 0)
{
 ....
```

**Comment by kenshirothefist** [comment]
Resolved in 7d06e82e8af5e41011301399afe33ffe3a62cf70. Closing.
