### ISSUE TITLE
p0-state

### ISSUE THREAD

**Issue by dnev3000** [nicehash/NiceHashMiner-Archived#1000]
Hi, 

When setting p0-state to "true" in the config file it automatically resets to "false", thus not enabling p0 state on my cards. 

This is on version 2.0.0.6

Best regards
Noob

**Comment by cpshoemake** [comment]
Try making the config changes with NiceHash Miner closed. NH 2 seems to rewrite the config file when it closes.

**Comment by dnev3000** [comment]
Thanks, that worked!

**Comment by Squall-Leonhart** [comment]
you can use nvidia profile inspector to disable the cuda p2 state.

**Comment by dnev3000** [comment]
That sounds great. How do i disable it?

**Comment by Squall-Leonhart** [comment]
with this version
https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/build/artifacts

look for CUDA - Force P2 State "On"
and set it to off.
