### ISSUE TITLE
Nicehash x11gost pool problem?

### ISSUE THREAD

**Issue by crafturtoe** [nicehash/NiceHashMiner-Archived#1008]
Whenever I connect to nicehash x11gost pool either EU/US, using the NHMv1/v2 miner..It always restart...
It happens even I use other version of ccminer and connect to the pool manually

**Comment by S74nk0** [comment]
@crafturtoe All seems to work as expected. Maybe there is something specific with your setup.
This isn't related to NiceHash Miner program or source code. Please write your question to support@nicehash.com.

Closing issue not related to NiceHash Miner program or source code
