### ISSUE TITLE
Alternativement payment coin

### ISSUE THREAD

**Issue by JesusTheHun** [nicehash/NiceHashMiner-Archived#1010]
Hello,

As many of you I am worried about the future of Bitcoin. Transaction fees increased dramatically, not to mention transaction delay, but also the price in danger. We all know the building is about to collapse. We don't have to wait for it to happen to switch to another cryptocurrency.
I know the choice isn't easy since every crypto is subject to volatility, but change must happen.

Someone suggested Litecoin in #981 , it could be that, or Ethereum, a raising value we all know, which volatility goes in "good way" for now.

Please communicate on that, even to say "no" or "yes but we don't know what or how".

For an average payment of 200$ I'm taxed 4$ by BTC, this is close to NiceHash fees ! making NH system a 5% fees pool !

**Comment by Wtcheesecakes** [comment]
Ethereum would be great as it is ever going up in price so we can still make profit

**Comment by scaras** [comment]
well, litecoin has the lowest fee (btc, eth, ltc) and once they activate lightning on litecoin network it will be almost instant (few seconds) transfer and cross platform payments also will be possible with litecoin in the (near) future.

**Comment by Bill48105** [comment]
+1 for DOGE, LTC, ETH in that order but ANY alternate is better than just BTC at this point. Would love an alternate not only to reduce fees but eliminate need to trade (if we could pick one of the 4 for example) and hopefully get more frequent payouts for slower miners which can be weeks now.

**Comment by JesusTheHun** [comment]
@scaras : let's not talk about what could be, and stick with what it is.

@Bill48105 : I fully agree with that, any currency is better than Bitcoin at this point.

**Comment by Fossius** [comment]
Just not ETH, due to slowest wallet. DASH or LTC

**Comment by S74nk0** [comment]
**all** this isn't related to NiceHash Miner program or source code. Please write your question to support@nicehash.com.

Closing issue not related to NiceHash Miner program or source code
