### ISSUE TITLE
disconnecting from pool every 6 seconds

### ISSUE THREAD

**Issue by dragonshardz** [nicehash/NiceHashMiner-Archived#1012]
n/t. Every single algorithm type, without fail, six seconds after establishing a connection to the pool, the running miner disconnects.

Not sure where to start diagnosing this, as best as I can tell the router isn't blocking the stratum connections but the miners are failing to do anything but perpetually try to reconnect.

**Comment by S74nk0** [comment]
@dragonshardz If you can connect to the service and stratums (hence the issue isn't related to your network setup), please write your question to support@nicehash.com. Explain the issue in detail (send them your IP and BTC wallet address). 

Closing issue not related to NiceHash Miner program or source code
