### ISSUE TITLE
never ever had a payout

### ISSUE THREAD

**Issue by turtiustrek** [nicehash/NiceHashMiner-Archived#1016]
says it all in the title i have been mining for a month and next payout time is increasing by month 
its been 3 times it did that WHY? i am starting to think i am wasting my time to mine bitcoin because it never gives out your reward. in total it's been 2 months!

**Comment by turtiustrek** [comment]
Even worse my money rest and got no balance in my coin base wallet

**Comment by dadoremix** [comment]
what graphic card you use for mine?
balance is ?
https://www.nicehash.com/index.jsp?p=faq#faqs6

**Comment by turtiustrek** [comment]
Sorry to disturb i got the balance it was pending 
Rx 480 
$2  a day and AMD A10  w/ R7 240
