### ISSUE TITLE
not payments

### ISSUE THREAD

**Issue by atila250** [nicehash/NiceHashMiner-Archived#1018]
I would like to know, about the payment, I was scheduled for today at 7:00, but it did not happen.
Is there a problem?

tks

**Comment by augustresende** [comment]
Me too #1017

**Comment by atila250** [comment]
The deposit was made It was a time zone issue.
Now it's waiting, show up in the wallet

**Comment by S74nk0** [comment]
@atila250 this isn't related to NiceHash Miner program or source code. Please write your question to support@nicehash.com.

Closing issue not related to NiceHash Miner program or source code

**Comment by augustresende** [comment]
@S74nk0 merge my pull request and add a open source license to NHM
