### ISSUE TITLE
Still no payout day?

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#1019]
I'm looking at my stats right now, and I see that my payout day is still "N/A". I've been mining for a few days, and I still don't have a set payout day.

**Comment by dadoremix** [comment]
https://www.nicehash.com/index.jsp?p=faq#faqs6

**Comment by S74nk0** [comment]
@192uijo this isn't related to NiceHash Miner program or source code. Please write your question to support@nicehash.com.

Closing issue not related to NiceHash Miner program or source code
