### ISSUE TITLE
Benchmark terminated 1.4.0.2

### ISSUE THREAD

**Issue by justsomeguy101** [nicehash/NiceHashMiner-Archived#102]
I have two GPUs connected; a GTX 650 and GTX 750. When I try to run the benchmark for the 750 many of the algorithms fail with the word "terminated..." in the speed column.  For example both x11 and x13 fail. These same algorithms work fine for the 650.

Is there a work around for this? The latest driver is installed for both cards.

Many thanks,

**Comment by Singman33** [comment]
I use a workaround for that problem : delete "ccminer.exe" and "ccminer_neoscrypt.exe", and copy your "ccminer_sp.exe" two times, rename to deleted.
I still dont understand why NicehashMiner try to use different miner for theses two algo when SP version is at least at same speed or even faster...

**Comment by justsomeguy101** [comment]
Thanks Singman, I followed those instructions however I don't have a ccminer.exe but deleted ccminer_neoscrypt and ccminer_tpruvot . I swapped both for ccminer_sp. I can now benchmark neoscrypt but x11, x13 and x15 all get terminated on the GTX750 and also ethereum hangs up. It created the DAG on the 750 but then hangs for many hours until I have to End Task. Ethereum works on 660.

**Comment by Singman33** [comment]
Hmm, X11 and X15 are benchmarking without problem, but you could try to adjust _intensity_ in your config.json file like :
Section NVIDIA5.x, under algorithms x11 (and x13, x15)
"ExtraLaunchParameters": "--intensity=20",

Try to lower the number and find the right one

**Comment by justsomeguy101** [comment]
Singman, changing the intensity to 10 has worked and now x11, x13 and x15 are able to benchmark (very poor hash tho far worse than the 660). 

What is the default intensity for when the extalaunchparameters is blank?

**Comment by Singman33** [comment]
I think it's 31, or it's the max value. Try to increase from 20, that could work.
On a 750 Ti, I have for x11=4.932 Mh/s, x13=3.834 Mh/s, x15=3.330 Mh/s

**Comment by justsomeguy101** [comment]
I will try that, so far it seems to always terminate above 19. For my GTX750 I get less than half those values, and that's with the card overclocked and intensity=19. 

If the problem could be with ccminer_sp.exe is there another exe I could swap this for?

**Comment by leshiy-gr** [comment]
I have a similar problem with the GTX650. Benchmark hangs on algorithms whirpoolx and ethereum.
On the other system with AMD video - also hangs benchmark on the algorithm ethereum (after creating DAG) and "crashes" on the whirlpool. Now I noticed that on algorithm x11 sgminer constantly shows 0 accepted, although in the log at the bottom there accepted line. Or I must describe these cases separately?

**Comment by justsomeguy101** [comment]
Singman, are you using any custom parameters on the algorithms to get those hashrates on your 750ti.
Leshiy, I can report the same with regard to the whirlpool, I never got it to work on my 660

**Comment by Singman33** [comment]
Hi,
I'm sorry, I gave you wrong numbers, it was not the rig with 750. Here are the parameters I use in a Linux script, I've done a small bash program to find them :

```
X11, 2.898, "x11", "-i 15"
X13, 2.220, "x13", "-i 19"
Keccak, 138.230, "keccak", "-i 28"
X15, 1.907, "x15", "-i 19"
Nist5, 9.155, "nist5", "-i 24"
NeoScrypt, 0.200, "neoscrypt", "-i 15"
WhirlpoolX, 68.490, "whirlpoolx", "-i 25"
Qubit, 4.567, "qubit", "-i 20"
Quark, 6.022, "quark", "-i 24"
Lyra2REv2, 4.307, "lyra2v2", "-i 20"
Blake256r8, 902.360, "blakecoin", ""
Blake256r14,499.880, "", ""
Blake256r8vnl, 902.360, "Vanilla", ""
```

Format is Algo name, hashrate in kh/s, algo name for miner, extra parameter

**Comment by justsomeguy101** [comment]
Hi Singman, thanks for getting back to me and searching those parameters.
I notice for your x algorithms your intensity is <20, can I ask if you can replicate my problem? If you change -I to 20 on X13, does your cpminer-sp crash/terminate?
Thanks

**Comment by Singman33** [comment]
Yes, with either a "out of memory" error or just a crash.

**Comment by Singman33** [comment]
BTW, I have a 750 Ti OC with 2 Gb of VRAM. Be carefull of that.

**Comment by justsomeguy101** [comment]
Same error for me - out of memory. Helpful to know it's not my configuration/card/drivers ! Thank you

**Comment by lamerhouse** [comment]
i have this problem with 390x radeon.. Benchmark terminate all .. also ethereum is working

**Comment by justsomeguy101** [comment]
Turning down the intensity worked for me. Run the miners in the bin folder directly without the nicehash interface to see what the real error is rather than just "terminated"

**Comment by lamerhouse** [comment]
but if you do so .. the encoding gear play between various coins disappear ...

**Comment by theLosers106** [comment]
@justsomeguy101 has your problem been fixed?

**Comment by justsomeguy101** [comment]
@theLosers106 , yes - turning down intensity on algorithms that were being terminated. And for Eth the DAG is too large for 1GB card, explains why it was hanging

**Comment by Singman33** [comment]
I've created a repository for my script under Linux

https://github.com/Singman33/linux_nicehash
