### ISSUE TITLE
Payout Status Low Fee!!

### ISSUE THREAD

**Issue by Paapo** [nicehash/NiceHashMiner-Archived#1021]
Hi,
the payout from yesterday 11:59 is still showing "Low Fee" in Electrum.. What is Happening there?
The payout from  today is also still not confirmed. Do you pay no fee for you Transaction in hope they will pushed through sometimes?
Wallet: 1PUTH1BuNDs4hCE5SUpLVUfXAuhAAPAxep

Please explain soon..

Regards,
Marcus

**Comment by S74nk0** [comment]
@Paapo this isn't related to NiceHash Miner program or source code. Please write your question to support@nicehash.com.

Closing issue not related to NiceHash Miner program or source code.
