### ISSUE TITLE
New Mining

### ISSUE THREAD

**Issue by jt0909** [nicehash/NiceHashMiner-Archived#1024]
1) Just started a new day and my rig had made around £4/£5 , so do I then keep mining and after a week I get paid.?

2) Do you guys/gals think it worth running 2 gtx 970 costing around £120ea?

Im using BlockChain as a wallet.

**Comment by jt0909** [comment]
I'm using nicehash forgot to add that.

**Comment by jaretburkett** [comment]
@jt0909 this isn't really related to NiceHash Miner program or source code. Issue reporting is reserved for issues or bugs with the software itself. However, if you go to https://www.nicehash.com/index.jsp?p=miners&addr=YOUR_BTC_ADDRESS , it will give you an estimated date and estimated ammount of your next payout, based on your current hash rate.
