### ISSUE TITLE
Benchmark stuck at Ethereum

### ISSUE THREAD

**Issue by KudoJin** [nicehash/NiceHashMiner-Archived#103]
So, I'm trying to get this thing started out by running the benchmark first. However, while most of the Benchmarks work perfectly for some reason the Ethereum benchmark never ends. I have literally waited for hours for it to end, and it doesn't.

Not only that, but when it gets to that point and I hit "stop benchmark" it doesn't stop, and the only way to close the program is by using Task Manager. But if I use task manager to close it and start it up again, it no longer detects my GPU and instead only detects my CPU. Deleting and reinstalling the program doesn't fix this, the only way to fix it is by rebooting the computer.

If I reboot the computer without deleting and reinstalling, then the Ethereum mining executable crashes and I can't use the program, so I have to delete and reinstall the program.

Is there something wrong here? How can I fix this to where I can actually use the program?

**Comment by justsomeguy101** [comment]
What size of memory does your GPU have?

**Comment by theLosers106** [comment]
It seems to me that your graphics card might not be able to handle ethereum or the default parameters and that causes the GPU driver to crash.. that's why NiceHashMiner will not see the GPU unless you restart your computer.. please update us with what GPU model you are using so we can help..

Thanks,
theLosers106.

**Comment by KudoJin** [comment]
Trying it on the new version so I'll let you know how it goes on that, I'm not optimistic though since it says nothing of this issue in the changelog.

As for what GPU I'm using, a GTX 860M.

And before you say "you shouldn't mine on a laptop you'll break it", I know that but first off this thing is already breaking on me ever since my sisters cat decided the charging cable was a toy and pulled it (along with the laptop) onto the floor a few times, so I figured I might as well get a few cents out of it before it goes out completely. That and I'm not running it 24/7, rather I'm running it every so often and then giving it a (rather long) break. I have a desktop where I do 90% of my mining, but that one's having no issues.

**Comment by theLosers106** [comment]
You will have to play around with these settings to get it to work:
--cuda-grid-size 1000
--cuda-block-size 200
