### ISSUE TITLE
Question [Can I mining ETC with RX560 2GB?

### ISSUE THREAD

**Issue by kntmrkm** [nicehash/NiceHashMiner-Archived#1032]
I can't get RX560 with 4GB.

Some articles say `2GB version got error when mine ETC`.

- e.g) http://cryptomining-blog.com/tag/rx-460-ethereum-hashrate/

Now, Can I use 2GB version to mining ETC?

thanks

**Comment by lukasmagi** [comment]
Mining at 2GB VGAs is a problem ETH/ETC use same script and use DAG file, 
- my test say not use 2GB card, client crash or be unstable and some times wotnt starts
- if my tested PC have more than 8GB main memory I got little better results but still unstable...
- but mining XMR or ZCL/ZEC be still better option for you

**Comment by kntmrkm** [comment]
OK thanks for your quick response.
In japan. There are no `AMD 400 series`, `570, 580`  and `560 4GB`.

It's looks too risk to use 2GB...

thanks again.

**Comment by S74nk0** [comment]
@kntmrkm No 2GB is not enough RAM
