### ISSUE TITLE
excavator - Release v1.2.6 alpha

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner-Archived#1036]
Please include the newest excavator in the next release

https://github.com/nicehash/excavator/releases

https://github.com/nicehash/excavator/issues/8

**Comment by nicehashdev** [comment]
New Excavator uses different API approach and would require a lot of coding work in current NHM1, therefore, it will not be implemented, as NHM2 is coming out soon.

NHM2 uses new Excavator.
