### ISSUE TITLE
Ethereum not mining crashes

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#104]
So i have 2 GPUs 970 and a 960. If i reboot my win7 and start mining it works for about 3 minutes and then it crashes, it tries to reboot itself (etherminig through nice hash) but crashes at different times. Some time at a stage when it tries to get the DAG file, some times an error pops up, image attached.

I have to questions:

How can this be fixed and why does it only mine through one card?

![ethereum not mining](https://cloud.githubusercontent.com/assets/19608698/15607533/460d8b08-241c-11e6-8e2a-7e8f88d07cc0.jpg)

**Comment by theLosers106** [comment]
you will have to play around with the values for --cuda-grid-size and --cuda-block-size.. the default values for them are 8192 and 128.. I am guessing that the 960 is crashing and the 970 continues mining?

**Comment by theLosers106** [comment]
and make sure that you did not overclock you GPU as that will cause instability.. I have tried with 970 & 960 on a rig and it is working fine on ethereum..

**Comment by undefy** [comment]
What i can see is that the 960 is not recognized or is seen as 970... Is there a log file i can upload or check to see what is happening?
Some times it works fine, then after 20 minutes i get the same line 222 error. And other times the line 222 error comes up straight away.

I am not overclocking. Tried it once and it just didn't work.

"values for --cuda-grid-size and --cuda-block-size
Where are they found and/or how do i change them and to what?

**Comment by undefy** [comment]
So now i have the following errors... The only thing i did was install a 3rd car r9 380. It was working fine fo 2 days and now this... WTF?
![nh broke 2](https://cloud.githubusercontent.com/assets/19608698/15820567/fc114fec-2bf2-11e6-8367-ffe686e0fc84.jpg)
![nh broke](https://cloud.githubusercontent.com/assets/19608698/15820568/fc169bc8-2bf2-11e6-93b3-70d17d853bb3.jpg)

**Comment by nicehashdev** [comment]
Your IP has been temporarily blocked. If you still experience this issue, contact NiceHash @ support@nicehash.com

Regarding your problem; please update to latest NHM version and report back if you are still having issues.
