### ISSUE TITLE
Fail to Display Daily Earnings

### ISSUE THREAD

**Issue by psa95** [nicehash/NiceHashMiner-Archived#1044]
When I run the program with administrator privileges, the daily estimated earnings fail to show.
<img width="482" alt="e1" src="https://user-images.githubusercontent.com/20689830/27252402-d376bcb2-536e-11e7-9fe4-d81e387df846.png">

Along with this, clicking on mining details also shows no information whatsoever.
<img width="480" alt="e2" src="https://user-images.githubusercontent.com/20689830/27252403-d377a83e-536e-11e7-8e19-3db1db03d395.png">

**Comment by S74nk0** [comment]
@psa95 Please open this issue [here](https://github.com/nicehash/NiceHashMiner2/issues).
Closing ...
