### ISSUE TITLE
NHM v1.7.5.13 not detecting AMD HD7850 GPU

### ISSUE THREAD

**Issue by sebastianrothman** [nicehash/NiceHashMiner-Archived#1045]
Using miners discreetly outside of NHM pick ups the GPU fine and I am able to use it.
My CPU and nVidia cards are detected and working just fine.
I've tried various versions of drivers, from 15.12 right through to 17.5.2 with no luck.

Is there anything I am missing, or not doing right? NHM v1.7.5.12 does the same.

**Comment by S74nk0** [comment]
@sebastianrothman does [excavator](https://github.com/nicehash/excavator/releases/tag/v1.2.8a) detect your GPU?

**Comment by sebastianrothman** [comment]
Hi,
Sorry, I should have updated this already.
I re-installed the OS to Windows 10 and everything is sorted now.
I saw another thread before that also mentioned testing it in excavator, and I tried, but it didn't work either at the time.
But the issue can be closed, thank you.
