### ISSUE TITLE
Incorrect payout - Nicehash Miner 2.0.0.7 - Alpha

### ISSUE THREAD

**Issue by FramedYannick** [nicehash/NiceHashMiner-Archived#1046]
The Nicehash Miner is reporting higher speeds then shown on the website.
On the pc, it shows a steady 660-670 MH/s speed, resulting in a payment of 4.28 mBTC/day (on average 4.2 approx). However, the online site shows much lower values between 520-550 MH/s, resulting in a much lower pay (3.3mBTC/day). This is not internet related, as I have 10 ping and high bandwith atm.

1) Which payout schedule is the correct one?
2) What is causing a different payout schedule?
3) Can we do anything about it or is this software related?

Hardware:
GPU: gtx 1080 gaming x SLI
CPU: 6700k
RAM: 2400GHz 16GB
Mb: MSI Z170 Gaming M5

![image](https://user-images.githubusercontent.com/4488764/27254256-4173230c-5385-11e7-88c7-daabf9d8931e.png)

#update:
Apparently the inverse also happens (although less often) that the online page is showing a higher speed and payout rate then the Nicehash Miner.

**Comment by nerdatwork** [comment]
As you can clearly see it is in ALPHA mode. NOT FOR PUBLIC USE so many many issues will happen. I would suggest WAIT till NH devs release it publicly before you report it.

**Comment by FramedYannick** [comment]
As I'm not part of the Nicehash Mining team, I don't know the intended release schedule but the alpha version can be found on the new NH website. It must also be noted that alpha and beta releases are introduced for debugging purposes and it is therefore critical that occurring bugs are reported in the form of feedback so that the development team can address these issues when they see fit.
Having this said, the only similar issue I found on the GitHub being #934  failed to mention the hardware setup and the NH Miner version and this issue was not yet addressed by the NH team.

**Comment by nicehashdev** [comment]
1. Disable SLI. It can only cause issues when mining, but gives no additional speed.

2. You need to consider **average** speed reported online and not instant, as instant may vary up or down, depending how **lucky** your miner is.

3. NHM2 issues should be reported here: https://github.com/nicehash/NiceHashMiner2/issues
