### ISSUE TITLE
phymem.sys not Signed?  Thoughts?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#1049]
Is this a x64 x32 issue and Signing Issue? Windows 7 x64 and Windows 10 x64 Same Issues?

**Comment by Johann1982** [comment]
Windows has driver signature enforcement enabled. 
Open elevated command prompt and paste
bcdedit.exe /set nointegritychecks on

This only works on windows 7 as far as I know. I am having trouble getting it to work on windows 10. Maybe someone else knows how to sort this?

**Comment by imrecsoka** [comment]
thanks command worked - windows 7 ultimate

**Comment by Johann1982** [comment]
We still need a solution for windows 10. There should be a way of permanently disabling driver signatures.

**Comment by Johann1982** [comment]
For Windows 10 users:

Disable secure boot in bios
Open elevated command prompt and paste the following:

bcdedit /set testsigning on
bcdedit.exe /set nointegritychecks on
bcdedit.exe -set loadoptions DISABLE_INTEGRITY_CHECKS
bcdedit.exe -set TESTSIGNING ON

Press enter and reboot your pc.

**Comment by mendiolacubicle** [comment]
Johann1982's advise worked but i went down from 379 MH/s on lbry to 120 to 250 MH/s so i reverted it back and it went back to 370 to 380 MH/s.

**Comment by Johann1982** [comment]
@mendiolacubicle I have found the same issue after testing. With testing mode on profitability drops. Apparently phymem.sys is for AMD only. I have NVidia rigs, so I just ignore it. They will eventually have all drivers signed and then all will work as it should. It is still in Alpha stage.

**Comment by S74nk0** [comment]
@mendiolacubicle The issue with hashrate drops is answered [here](https://github.com/nicehash/NiceHashMiner2/issues/77). It is due to bad cleanup in **ccminer**.
@everyone The next excavator release will have a signed driver. There really isn't any need to workaround this as all enabled algorithms from NHM2 do not need the driver. 
Closing

**Comment by imrecsoka** [comment]
Hi, stupid question from a silly person, is excavator a GPU or CPU mine,r im not sure....
This was not named after the elevator action game right ?
Is this usable on AMD and called by Nicehashminer ?
Is there potential earnings using it on an RX470 card ?
Thank you for reading.
