### ISSUE TITLE
[Feature] SoloMining Support

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#105]
i would love to be able to use the nicehash soloming/lottery with the nicehashminer for some old gpu to waste some energy and maybe be lucky :D

**Comment by nicehashdev** [comment]
NHM will ever only support to mine on NiceHash and no other pool. We will never make support for any kind of solo mining. If you wish to solo mine, you will have to configure miners manually.

**Comment by felixbrucker** [comment]
i meant no other pool, just the https://solo.nicehash.com/ nicehash solo pool
