### ISSUE TITLE
Nicehashminer doesn't switch to other algos?

### ISSUE THREAD

**Issue by ultramania** [nicehash/NiceHashMiner-Archived#106]
I've been using the miner and it only mines X11 for the last month, doesn't seem to switch to etherium or other algos when they are higher. Is there a setting I need to configure for this? Thanks!

**Comment by Singman33** [comment]
Verify that everything you want to mine is checked in the "Benchmark" window, they are linked (what you choose tto bench is what you could mine).

**Comment by theLosers106** [comment]
@ultramania Can you screenshot the benchmark window so we could see if you have correctly benchmarked your card and also checked all the algo like what @Singman33 said..

**Comment by nicehashdev** [comment]
Update to latest NHM version and report back if you still have this problem.
