### ISSUE TITLE
Add support for .NET framework 4.xx

### ISSUE THREAD

**Issue by darkmorpher** [nicehash/NiceHashMiner-Archived#1063]
@nicehashdev @S74nk0

Currently highest version supported by the installer is v3.5. Please add support for .NET framework 4.xx, which is default on Win10.

Related #876, #1022 

[NiceHashMinerLegacy Fix](https://github.com/nicehash/NiceHashMinerLegacy/commit/aa9b0f02d16b0e039c88fdfd0a05962951707939)   [#157](https://github.com/nicehash/NiceHashMinerLegacy/issues/157)

**Comment by Squall-Leonhart** [comment]
That is not how things work.
