### ISSUE TITLE
Bios Corrupt, hard shutdown "Watchdog error"

### ISSUE THREAD

**Issue by dacendoran** [nicehash/NiceHashMiner-Archived#1066]
I'm on Windows 8.1. I was mining with EWBF's Zcash miner and attempted to open your Exe, when I BSODED and something said "watch dog error" And my system refused to boot, fans spinning no post etc. I had to clear the CMOS in order to get my system to boot.

**Comment by S74nk0** [comment]
We do not support **EWBF's Zcash** (this is probably from some forked NiceHashMiner project). We will also not support **EWBF's Zcash**.

Closing issue... Not related to official NiceHashMiner project

**Comment by 008** [comment]
"We do not support EWBF" why? It gives more hashes
