### ISSUE TITLE
Dual-Claymore Siacoin error response from server

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#1067]
AMD RX 480
![image](https://user-images.githubusercontent.com/24593637/27360567-8c0d6a7e-562a-11e7-9f03-18bb00760081.png)

**Comment by S74nk0** [comment]
@N8Thrasher this seems to be related to **Claymore miner**. Replace the Claymore dual miner in **bin_3rdparty\claymore_dual** with the latest Claymore dual miner it is compatible. I will update the miner binary download.
Closing...
