### ISSUE TITLE
Sia Coin stratum error

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#1071]
![sia](https://user-images.githubusercontent.com/24593637/27412854-64e4db9a-5700-11e7-9391-e4e07802d6d1.PNG)

**Comment by nicehashdev** [comment]
NiceHash uses Sia stratum protocol, which is not supported by this version of ccminer.

You may try our Excavator: https://github.com/nicehash/excavator

This is not NHM related issue. Closing.
