### ISSUE TITLE
Unable to Hide Mining Windows

### ISSUE THREAD

**Issue by Dinesh6777** [nicehash/NiceHashMiner-Archived#1074]
Unable to Hide mining windows(Screenshot Attached) even through the below option is checked it is not working.
Settings --> Hide mining Windows

Please advice, 
Thanks

![image](https://user-images.githubusercontent.com/6111150/27436490-7ff21b76-5770-11e7-8ef8-46396800cf42.png)

**Comment by S74nk0** [comment]
[ref](https://github.com/nicehash/NiceHashMiner/issues/996#issuecomment-308156470)
Closing

**Comment by Dinesh6777** [comment]
thanks for the reference....
