### ISSUE TITLE
BOUNTY HELP FOR 0.5 ZCASH: Getting 8x NVIDIA GTX 980 Ti GPU to be detected on Asus PRIME Z270-A Motherboard / Windows 10 / NiceHash Miner

### ISSUE THREAD

**Issue by tigercamefortea** [nicehash/NiceHashMiner-Archived#1076]
Hello Community,

I am a newbie and have recently aquired 8x NVIDIA GTX 980 Ti cards. My end goal is to build a rig with the cards and mine crypto.

So I have done a fair amount of research into what I needed and from my understanding I have everything I need. This is what I currently have:

8X GPU (Nvidia gtx 980 ti)
1x CPU & stock fan (intel pentium g4560 3.5ghz)
2x PSU (EVGA 1600w gold & all cables)
1x Motherboard (Asus Prime Z270-A)
2x RAM (2x4GB DDR4)
1x SSD (128GB seagate)
1x Windows 10 OS on usb stick
1x M.2. to PCIE converter (ebay)
8x Risers (version 006 from ebay with usb and molar connections)
1x Open air mountain bracket (ebay)

The first step I took was assembling all the parts with the exception of adding any of the GPU's.

Windows 10 installed fine and updated. Along with the BIOS update for the motherboard from ASUS website.

When adding the first GPU I installed the driver from nvidia and it was working fine and even tested on nicehash seemed okay!

When adding the 2nd it does work but only in certain slots and then adding 3rd or anymore than that either the rig will not turn on and display just black screen.

I am also finding that windows comes up with all kinds of repairs when rebooting after adding more cards.

Troubleshooting wise I have already tried enabling the 4G Decoding option which seems to make no difference to the amount of GPU it can detect.

I will also add that the slots which work through 1 to 7 (PCIE) seem to be random and different ones work at different times.

I have seen lots of people online achieving 8 NVIDIA GPU's so I am sure it is possible with the equipment I have purchased. 

The conclusion of my problem is that I simply cannot get more than 3 cards to show and its a struggle even getting it to that point.

Anyone willing to video skype call and assist with a solution resulting in all 8 gpu's working on this motherboard will be rewarded with 0.5 ZCASH for there time.

I can show you all my wiring and my setup on the video call and I have also ordered another new motherboard & all other new parts to be sure its not the parts which are not working.

Joey

**Comment by nicehashdev** [comment]
You may post this in our reddit or bitcointalk.

Not NHM issue, closing.

**Comment by 008** [comment]
know you problem and solution
want 0.5 ZCASH prepayd :)
