### ISSUE TITLE
NiceHash earnings gone after a computer crash :/

### ISSUE THREAD

**Issue by lnternetHero** [nicehash/NiceHashMiner-Archived#1078]
Hello,

I started using NiceHashMiner couple days ago and already earned some money,
Yesterday the computer crashed while I was mining,
When I restarded the system and started the NiceHash app it asked me to accept terms & conditions - like if I just installed the app and wanted it to run for the first time... 
All the savings is gone, it shows ZERO of evertyhing,
Also it did not synchronize with my walltet (Electrum)

Is there a way to get it back or is it gone for good?

Please help.

**Comment by pwdrhash** [comment]
You should understand that NiceHash, like any other pool, is not "putting money" on your computer in any form.  You are just a machine on their network doing work.  Whatever money you earn sits in your NiceHash account until it gets paid to your BItcoin wallet.  All you need to do is re-enter your Bitcoin wallet address under settings like you did originally.

**Comment by S74nk0** [comment]
@lnternetHero you can check your balance here _https://new.nicehash.com/miner/ **YOUR_BTC**_ replace **YOUR_BTC** with the BTC you were mining. Just paste your BTC in NiceHash Miner and it will show your current balance. 
Closing...

**Comment by lnternetHero** [comment]
Yes, I do understand that. I did re-enter my BTC receiving address and also checked the balance onilne and it is empty, with no history. 

Receiving address that I've been using:

1NwGpocDzph23jxU6UHkUZ4YyPiLfSh3Ug

And please ignore the 0.02 USD - this was earned after the system crash.
There was much more before that.

**Comment by S74nk0** [comment]
@lnternetHero issues like this should not be addressed here, open issues related only to NiceHash Miner software. For your problem please write to support@nicehash.com
