### ISSUE TITLE
This video card does not run

### ISSUE THREAD

**Issue by zhandayu** [nicehash/NiceHashMiner-Archived#1082]
![qq 20170623222506](https://user-images.githubusercontent.com/28682220/27486470-4151a53c-5863-11e7-8a60-16f4af01698e.png)

**Comment by Squall-Leonhart** [comment]
did you benchmark it?

it is just a GTX 1060 designed for mining after all....

**Comment by S74nk0** [comment]
@zhandayu Check out **tutorials** on NiceHash Miner v1. You:
  - **start**
  - type your **BTC** address
  - **benchmark**
  - **mine**

Closing issue...
