### ISSUE TITLE
NiceHashMiner is a Virus

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#1084]
**Dear Everyone,**
Please, please, please **don't** install this. **It is a Trojan.** If you don't believe me, try it yourself if you have antivirus. Proof: [https://drive.google.com/file/d/0B4oeoTYTK9UdY3RZZ0xvNXE5SVE/view?usp=sharing](https://drive.google.com/file/d/0B4oeoTYTK9UdY3RZZ0xvNXE5SVE/view?usp=sharing)

**Please don't install it,**

Allan

**Comment by jaretburkett** [comment]
A lot of the miners binaries that NHM uses are also used in viruses so the creators of the viruses can make money off of your computer power. Therefore, the miners frequently get flagged as viruses by anti virus software when they are not.
