### ISSUE TITLE
Profitability fluctuations

### ISSUE THREAD

**Issue by bodanu** [nicehash/NiceHashMiner-Archived#1086]
I have been studying the profitability chart for gtx970 for the last 30 days and i have seen some quite big fluctuations. Will it increase again to about 4$/day or is this gpu dying?

**Comment by S74nk0** [comment]
@bodanu You can check the average profitability at a given time on the stats page. BTC to FIAT fluctuations affect the FIAT ($)/day payouts, you are earning **Bitcoins** for your work the $/day payouts correlate to **BTC to USD** exchange. Your GPU is probably fine. Your question if the profitability will increase at a previous $/day is **impossible** to answer, we can only speculate, and this is related to many different factors. You are basically asking us what will the price of **Bitcoin** be in the future, what are the prices of other alt-coins going to be... In short **nobody knows**.
In the future please do not open any issues on **GitHub** that aren't related **specifically** to **NiceHash Miner software** (**bugs**, **feature requests**, **bad design**, **source code**,...).
I have taken the time to answer your question... In the future write to support, our reddit channel or bitcointalk forums. 

Closing issue not related to **NiceHash Miner software**
