### ISSUE TITLE
Windows 10 crash benchmark

### ISSUE THREAD

**Issue by lamerhouse** [nicehash/NiceHashMiner-Archived#109]
hi 

i have 2 390x and 1 980 gtx .. in computer with nvidia 980 is all OK .. but in all computer is 390x all benchmark is terminated and when it ends to calculate Eternium freezes and I have to restart the program losing all the data of the benchmark .. this always happens on most computers

version software 1.5

**Comment by theLosers106** [comment]
what graphics driver are you using?

**Comment by lamerhouse** [comment]
Radeon Software 313 MB  Crimson Edition 16.5.3 Hotfix   5/23/2016

**Comment by theLosers106** [comment]
Could you try driver ver 15.12? Some users are reporting slow and problems when mining using the latest driver..

**Comment by lamerhouse** [comment]
The problem is not the driver ... both with 290x 390x that with the problem is also the same as with previous drivers ... and anyway if I start the pool individual without this program with ether do 35 MH therefore his works and calculates well .. the problem is internal to the software settings that go into finished all .. something is not set right, benchmarks or something .. because then if i do as he always takes X11 as default and calculates 38 Mh and works .. but only the benchmark does not work ... and if it does not Too bad that no automatic exchange of currency

**Comment by theLosers106** [comment]
Could you delete log.txt file and try to run the benchmark as usual. Then send the log.txt file to nhm@nicehash.com so I could review it. Thanks.

**Comment by theLosers106** [comment]
Now I would need you to go to these two folders: sgminer-5-1-0-optimized & sgminer-5-4-0-general .. then send the dump.txt file.. thanks.. looks like the benchmark took too long and NiceHashMiner just exits without completing..

**Comment by lamerhouse** [comment]
hi

in both the folders you report there is no dump.txt file

2016-06-07 5:48 GMT+02:00 theLosers106 notifications@github.com:

**Comment by nicehashdev** [comment]
We do not recommend using Win 10 for mining as there are driver issues when mining Daggerhashimoto - you will get low speed. Rather use older OS.

**Comment by lamerhouse** [comment]
I'm sorry but it works beautifully with Windows 10 does not need to use
Windows 8 or Windows 7 ... if you use the individual software without using
the automatic .. works very well ... and calculates with a 39 MH 390x
Daggerhashimoto do exactly as with windows 7 or windows 8 ... the problem
is NICEHASHMINER with AMD graphics cards with Nvidia video cards instead
everything works ... i think you need to double check how it uses the AMD
driver through NICEHASH software ... and he who errs .. as i said using the
individual miner software also runs on AMD ... if you can fix the program
automatic movement between currencies also amd GOOD ... if you'll go on to
calculate the individual currencies in manual and change every now and then
... the problem and only manages the AMD cards if you can solve the perfect
one

2016-06-09 20:59 GMT+02:00 nicehashdev notifications@github.com:

**Comment by nicehashdev** [comment]
Windows 10 with Maxwell NVIDIA cards will produce low hashrate on daggerhashimoto. You can get high hashrate only when using Pascal cards.
