### ISSUE TITLE
not working yet

### ISSUE THREAD

**Issue by lody2mk** [nicehash/NiceHashMiner-Archived#1090]
please i have problem . Nicehash not work
![capture](https://user-images.githubusercontent.com/29691583/27517844-aa211186-5987-11e7-9be7-6fa78ad26477.PNG)
i don't install any antivirus

**Comment by bovcan** [comment]
hardware info? what cpu/gpu...

**Comment by ThisIsJustARandomGuy** [comment]
Does it work if you click "Yes"? 

If so - I had the same "problem" after switching out my mainboard / copying the pre-configured miner to different computers. In the NiceHashMiner folder there is a directory called "configs" and in there is a file called "General.json". To fix your problem you can backup this file, delete it, restart NiceHashMiner (accept TOS etc.) and close the miner again. This generates a new "General.json" file which you then open up. Look for a line that begins with "hwid". Copy said line, open your backup of the "General.json" file and replace the same line there with the one you copied. Remove the newly generated "General.json" and replace it with your updated backup.

**Comment by S74nk0** [comment]
@lody2mk In this case click Yes, Re-Enter your BTC account and resume mining. Or do what @ThisIsJustARandomGuy has suggested in case you have made major changes to the **General.json** config file.

Closing...
