### ISSUE TITLE
Detailed build instructions in the wiki

### ISSUE THREAD

**Issue by mascondante** [nicehash/NiceHashMiner-Archived#1095]
Would this be possible or is the project open source purely for educational/transparency purposes?

**Comment by llamasoft** [comment]
I'm not sure I understand.  The project comes with a Visual Studio .sln file which you can use to build the binary on your own.

**Comment by mascondante** [comment]
It was my mistake. I was using Visual Studio 2017 and tried upgrading the sln to 2017. Got some errors. Just left it as is and I was able to build zero issues. I see why you were confused. No instructions needed besides don't try to upgrade the project.
