### ISSUE TITLE
Will benchmark Lyra2REv2 but not mine GTX 960

### ISSUE THREAD

**Issue by Noobminer17** [nicehash/NiceHashMiner-Archived#1096]
### So I'm using newest nicehash miner with most recent NVIDIA drivers (on Strix GTX 960 4Gb) and all the algorythms benchark nicely but then the 2 best (Lyra2REv2 and Lbry) both on ccminer wont run. The script starts up and shuts down, The log states the following:

`[ccminer_NVIDIA-MINER_ID(9)-DEVICE_IDs(0)] Starting miner [pid(13864)|bin(bin\ccminer_nanashi\ccminer.exe)] --algo=lyra2v2 --url=stratum+tcp://lyra2rev2.usa.nicehash.com:3347 --userpass=34SveLG7dkAhDXyP98CUt7v3kWnGoi5ayR.My rig:x  --api-bind=4009  --devices  0`

`[2017-06-27 00:05:02] [INFO] [ccminer_NVIDIA-MINER_ID(9)-DEVICE_IDs(0)] [pid(13864)|bin(bin\ccminer_nanashi\ccminer.exe)] Starting cooldown checker`

`[2017-06-27 00:05:03] [INFO] [ccminer_NVIDIA-MINER_ID(9)-DEVICE_IDs(0)] [pid(13864)|bin(bin\ccminer_nanashi\ccminer.exe)] Miner_Exited Will restart in 5000 ms`

`[2017-06-27 00:05:03] [INFO] [ccminer_NVIDIA-MINER_ID(9)-DEVICE_IDs(0)] [pid(13864)|bin(bin\ccminer_nanashi\ccminer.exe)] GetAPIData reason: No connection could be made because the target machine actively refused it 127.0.0.1:4009`

`[2017-06-27 00:05:03] [INFO] [ccminer_NVIDIA-MINER_ID(9)-DEVICE_IDs(0)] [pid(13864)|bin(bin\ccminer_nanashi\ccminer.exe)] summary is null`

`[2017-06-27 00:05:03] [INFO] [ccminer_NVIDIA-MINER_ID(9)-DEVICE_IDs(0)] GetSummary returned null..`

### Thanks in advance! (best answer gets a small noob donation once I get up and running)

**Comment by kazso** [comment]
You have a space in your worker name: 

`My rig`

Maybe that's causing the issue.
I tried that on my ccminer and got the same error.

**Comment by Noobminer17** [comment]
@kazno thank you my good sir. I changed that in my last desperate attempt and it worked just a few minutes before you answered. However, seeing as it was correct and would have saved me literal sleepless nights, post that bitcoin address (can't guarantee a lot as I'm only switching from ether now, but you deserve it :3)
