### ISSUE TITLE
neoscrypt not working properly on AMD R9 380

### ISSUE THREAD

**Issue by CreamyG31337** [nicehash/NiceHashMiner-Archived#11]
hashing speed is about 130 Mh/s which is impossibly high
Nothing is accepted or rejected for hours, online stats confirm this
![nicehash error 1](https://cloud.githubusercontent.com/assets/11222932/11938173/25ecee6c-a7d6-11e5-9d52-db4447988303.png)
This problem existed in the previous release also, I just disabled it by setting the benchmark result to 0
I believe one of the other algo was intermittently doing this also but I'm not sure which one.

**Comment by kenshirothefist** [comment]
Which driver version do you have installed? Which OS?

**Comment by CreamyG31337** [comment]
win 10 x64, 15.201.1151.1008

**Comment by kenshirothefist** [comment]
What happens if you try to run runme.bat directly from the ..\bin\sgminer-5-2-1-neoscrypt folder?

**Comment by CreamyG31337** [comment]
Same thing, GPU not doing anything but showing 115 Mh/s

**Comment by kenshirothefist** [comment]
Then this is related to your AMD GPU driver version. You're obviously running a version of drivers, newer than 15.7.1. Try uninstalling your current AMD GPU driver and install version 15.7.1: http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows+7+-+64

Unfortunately NeoScrypt is not compatible with newer drivers. And unfortunately AMD is making a total mess out of their drivers ... every newer release is having incompatibility, stability or performance issues.

**Comment by kenshirothefist** [comment]
Were you able to resolve your issue by installing 15.7.1 drivers?

**Comment by CreamyG31337** [comment]
Sorry, I uninstalled that video card because I have to give it away as a Christmas present.

**Comment by kenshirothefist** [comment]
Full AMD GPU support with various Display Drivers was added in 1.2.2.0. Closing.
