### ISSUE TITLE
Ethminer: JSON-RPC problem. Probably couldn't connect

### ISSUE THREAD

**Issue by borodovich21** [nicehash/NiceHashMiner-Archived#110]
Hi everyone! 
Ether-proxy.exe: Errror while refleshing block template on Nicehash..
This issue lasts for about 20 hours. 
Everything worked before. Use an older version 1.3.0.2. Still not working with upgrade to 1.4.0.2
Did anyone had that problem? Maybe i should change smth in config.json?

**Comment by BaalMcKloud** [comment]
please upgrade to 1.5 and try again
https://github.com/nicehash/NiceHashMiner/releases

**Comment by borodovich21** [comment]
well, it's interrupted at half load. 
That not happened before

**Comment by borodovich21** [comment]
It's working. Thank's a lot!

**Comment by theLosers106** [comment]
I'll be closing this since it is solved.
