### ISSUE TITLE
how to disable dual mine?

### ISSUE THREAD

**Issue by xdxdy** [nicehash/NiceHashMiner-Archived#1102]
Dual mine can make more money, but my video card can't handle the heat, my power supply is not enough for this, either. Is there anyway to disable dual mine?

I noticed that there is a 'enable3rdpartyminers', disable it may help. But will this get worse profit than claymoreAMD's DaggerHashimoto?

Thank you very much.

**Comment by ghostRZA** [comment]
Currently having the problem with my 280x cards. They work fine mining ETH but the moment it jumps to dual mining with Decred or others it overheats and crashes.

**Comment by S74nk0** [comment]
@xdxdy @ghostRZA uncheck the dual enabled algorithms if you don't want them enabled.
Example:
![disable dual](https://user-images.githubusercontent.com/1517233/27747887-89568694-5dcd-11e7-9104-47abf0ac6216.PNG)

**Comment by xdxdy** [comment]
@S74nk0 Thank you for help.

but if I only enable one algorithm, then how could the miner  choose the most profitly algorithm? nicehash miner would lost its advantage.
