### ISSUE TITLE
Negative mining stats 

### ISSUE THREAD

**Issue by slocumjared** [nicehash/NiceHashMiner-Archived#111]
Once and awhile I am getting negative mining stats on ethereum. any Ideas on what is causing it?
<img width="960" alt="negative stats" src="https://cloud.githubusercontent.com/assets/19740276/15796739/0e102b28-29d2-11e6-9b97-8aa2027cb2f2.png">

**Comment by theLosers106** [comment]
I have not seen this error before.. could you send me you log file when it happens again? send it to nhm@nicehash.com

**Comment by nicehashdev** [comment]
No need to investigate this bug any more since we do not use ethproxy anymore.
