### ISSUE TITLE
NiceHash 1.5.0.0 Decred Benchmark show 0H/S

### ISSUE THREAD

**Issue by PauloOF** [nicehash/NiceHashMiner-Archived#112]
Hi,

Until now could not achieve more than 0MH/s with Decred. Any sugestion? Thanks.

**Comment by theLosers106** [comment]
When you upgraded to v1.5.0.0, did you did a clean upgrade or did you copy over older versions of the config file?

**Comment by nicehashdev** [comment]
Please, upgrade to latest version and report back if you still have this issue.
