### ISSUE TITLE
Nicehash 1.5 stuck at benchmark Ethereum

### ISSUE THREAD

**Issue by dualshock2** [nicehash/NiceHashMiner-Archived#113]
I have : 

**4 x 7970**: benchmark and mining fine ! 
**4 x 7950**: benchmark and mining fine !
**5 x 7950**: stuck at benchmark Ethereum. After create DAG file, its say "wait for 2 - 4 min" but I wait some hours it's still not complete. 
**5 x 270x**: stuck at benchmark Ethereum. Same above ! 

All rigs running Windows 10 x64. with 4G of Ram. No Antivirus, No software installed.
All rigs work fine with Nicehash 1.4.

pls help me !

**Comment by Singman33** [comment]
Maybe a RAM problem for supporting 5 cards. Try to remove one card from a faulty rig and bench again.

**Comment by dualshock2** [comment]
Thankyou for supporting ! 
I will try that ! 

from iOS

On Tue, Jun 7, 2016 at 2:36 AM +0700, "Singman33" notifications@github.com wrote:

Maybe a RAM problem for supporting 5 cards. Try to remove one card from a faulty rig and bench again.

**Comment by theLosers106** [comment]
Could you try the latest NiceHashMiner and report back? Thanks

**Comment by dualshock2** [comment]
I try NH miner 1.5.1 and work fine with Dagger. Thankyou ! 

from iOS

On Thu, Jun 9, 2016 at 4:47 PM +0700, "theLosers106" notifications@github.com wrote:

Could you try the latest NiceHashMiner and report back? Thanks

**Comment by theLosers106** [comment]
Will be closing this issue as it is resolved.

**Comment by dualshock2** [comment]
Thankyou for supporting !

from iOS

On Thu, Jun 9, 2016 at 7:22 PM +0700, "theLosers106" notifications@github.com wrote:

Will be closing this issue as it is resolved.
