### ISSUE TITLE
Connection to excavator failing on startup

### ISSUE THREAD

**Issue by graham-m-dunn** [nicehash/NiceHashMiner-Archived#1135]
Nicehash 2.0.0.7 windows 10 creators edition

`{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer","time":"2017-07-04T16:07:28.563Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer_CryptoNight","time":"2017-07-04T16:07:28.563Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_OCL","time":"2017-07-04T16:07:28.563Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_CUDA","time":"2017-07-04T16:07:28.563Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_sgminer","time":"2017-07-04T16:07:28.563Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreZcash","time":"2017-07-04T16:07:28.579Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreCryptoNight","time":"2017-07-04T16:07:28.579Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_OptiminerZcash","time":"2017-07-04T16:07:28.579Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_excavator","time":"2017-07-04T16:07:28.579Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreDual","time":"2017-07-04T16:07:28.579Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Initializing NiceHashMiner v2.0.0.7 - Alpha","time":"2017-07-04T16:07:28.579Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Initializing NiceHashMiner v2.0.0.7 - Alpha","time":"2017-07-04T16:07:28.579Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Initializing Languages","time":"2017-07-04T16:07:28.892Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Initializing Interfaces","time":"2017-07-04T16:07:29.198Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Starting Device Detection...","time":"2017-07-04T16:07:33.173Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Starting Device Detection...","time":"2017-07-04T16:07:33.173Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Checking CPU devices","time":"2017-07-04T16:07:33.475Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] utils\\CPUDetection.exe JSON parse error: SyntaxError: Unexpected end of JSON input","time":"2017-07-04T16:07:33.537Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] QueryCPUs START","time":"2017-07-04T16:07:33.538Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] QueryCPUs: CPUHelpers.GetCPUInfo() returned null","time":"2017-07-04T16:07:33.539Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Checking CPU devices","time":"2017-07-04T16:07:33.539Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Querying CUDA devices","time":"2017-07-04T16:07:33.539Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] QueryCudaDevices START","time":"2017-07-04T16:07:33.540Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] ---\n  msg: \"CudaDevicesDetection:\"\n  devices: []\n","time":"2017-07-04T16:07:33.721Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] QueryCudaDevices END","time":"2017-07-04T16:07:33.721Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Querying CUDA devices","time":"2017-07-04T16:07:33.721Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Querying OpenCL devices","time":"2017-07-04T16:07:33.722Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] QueryOpenCLDevices START","time":"2017-07-04T16:07:33.723Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] ---\n  msg: \"AMDOpenCLDeviceDetection:\"\n  OCL_PlatformsDevices: \n    - \n      PlatformName: \"NVIDIA CUDA\"\n      PlatformNum: 0\n      Devices: \n        - \n          DeviceID: 0\n          AMD_BUS_ID: -1\n          _CL_DEVICE_NAME: \"Quadro 600\"\n          _CL_DEVICE_TYPE: \"GPU\"\n          _CL_DEVICE_GLOBAL_MEM_SIZE: 1073741824\n          _CL_DEVICE_VENDOR: \"NVIDIA Corporation\"\n          _CL_DEVICE_VERSION: \"OpenCL 1.1 CUDA\"\n          _CL_DRIVER_VERSION: \"369.09\"\n","time":"2017-07-04T16:07:33.830Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ComputeDeviceManager.Query] QueryOpenCLDevices END","time":"2017-07-04T16:07:33.830Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Querying OpenCL devices","time":"2017-07-04T16:07:33.830Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Starting Device Detection... Done!","time":"2017-07-04T16:07:33.835Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Checking miner files","time":"2017-07-04T16:07:33.835Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Checking Exchange Rates and Updates","time":"2017-07-04T16:07:34.137Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Current Bitcoin rate: BTC = 2594.466 USD","time":"2017-07-04T16:07:34.775Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Miners setup / updates","time":"2017-07-04T16:07:34.778Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[MinerFilesController] Checking miner file downloads and settup","time":"2017-07-04T16:07:35.079Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[MinerFilesController] Initializing miner bins hashes","time":"2017-07-04T16:07:35.082Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Checking Miner hashes","time":"2017-07-04T16:07:35.082Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[MinerFilesController] Init_3 file null","time":"2017-07-04T16:07:35.383Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Getting etherchain blocks","time":"2017-07-04T16:07:35.384Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Getting NiceHash SMA","time":"2017-07-04T16:07:35.845Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Checking Balance","time":"2017-07-04T16:07:36.296Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Starting NiceHash API streams...","time":"2017-07-04T16:07:36.713Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Starting NiceHash API streams...","time":"2017-07-04T16:07:36.713Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Starting NiceHash API streams... Done!","time":"2017-07-04T16:07:37.014Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Starting Excavator Server...","time":"2017-07-04T16:07:37.014Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Starting Excavator Server...","time":"2017-07-04T16:07:37.015Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2017-07-04T16:07:40.327Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Failed for sendData: \" {\"id\":1,\"method\":\"device.list\",\"params\":[]} \"","time":"2017-07-04T16:07:40.327Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2017-07-04T16:07:41.630Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Failed for sendData: \" {\"id\":1,\"method\":\"device.list\",\"params\":[]} \"","time":"2017-07-04T16:07:41.630Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2017-07-04T16:07:42.930Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Failed for sendData: \" {\"id\":1,\"method\":\"device.list\",\"params\":[]} \"","time":"2017-07-04T16:07:42.930Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2017-07-04T16:07:44.234Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Failed for sendData: \" {\"id\":1,\"method\":\"device.list\",\"params\":[]} \"","time":"2017-07-04T16:07:44.234Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2017-07-04T16:07:45.535Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server._GetAPIRequest] Failed for sendData: \" {\"id\":1,\"method\":\"device.list\",\"params\":[]} \"","time":"2017-07-04T16:07:45.535Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[excavator_server.GetAPIRequestNTry<T>] Failed for sendData: \" {\"id\":1,\"method\":\"device.list\",\"params\":[]} \"","time":"2017-07-04T16:07:45.836Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ExcavatorServer.MapExcavatorIDs] List devices failed","time":"2017-07-04T16:07:45.836Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[[GUI] NHMMainWorker.StartDeviceDetection] Done","time":"2017-07-04T16:07:45.837Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[ELECTRON LOAD] _MainController.Init Finished","time":"2017-07-04T16:07:46.138Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] SMA get","time":"2017-07-04T16:09:37.017Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] workerName= Quadro600","time":"2017-07-04T16:09:37.017Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] SMA get","time":"2017-07-04T16:11:37.045Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] workerName= Quadro600","time":"2017-07-04T16:11:37.045Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[InternetCheckerController] HAS Intenret connection","time":"2017-07-04T16:12:28.597Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] Balance get","time":"2017-07-04T16:12:42.020Z","v":0}
{"name":"NHM","hostname":"DESKTOP-U2KH2DS","pid":7844,"level":30,"msg":"[NICEHASH] workerName=Quadro600  &&  btcAddr=[redacted]","time":"2017-07-04T16:12:42.020Z","v":0}
`

**Comment by GoldKimber-Mining** [comment]
I had a similar problem.  Finally figured out I had a space in my worker name and it was too long.  Not sure about NiceHash2, but Quadro600 exceeds the 7 character max for NiceHash1.  Try shortening the worker name and try mining again.  Let us know if that works?

**Comment by graham-m-dunn** [comment]
Yep, that was it! Thanks.
