### ISSUE TITLE
Unauthorised installation

### ISSUE THREAD

**Issue by 2mancz** [nicehash/NiceHashMiner-Archived#114]
Hey, someone illegally crossed the software nicehash miner on my server, and benefits bitcoints, can such a person punish removing BitCoins?

**Comment by kenshirothefist** [comment]
You must always keep your computer safe and only download from our official download page: https://github.com/nicehash/NiceHashMiner/releases/tag/1.5.1.0. Unfortunately we can't help you on this particular issue that you're having, since it's not directly related to NiceHash Miner.
