### ISSUE TITLE
Balance reset suddenly!

### ISSUE THREAD

**Issue by CARB0** [nicehash/NiceHashMiner-Archived#1149]
i have been mining whenever my computer is idle for a few days now (around a week) and i made about 7 dollars or less, i left the miner on and went out, when i got back home i found my balance on 0.20! i thought it was just a glitch on the app so i checked it online and it was the same! please help as soon as possible so i would know if i should continue mining or not.

here are some screenshots i took of my progress a few days ago as well as a picture of my current unpaid balance:
![unknown](https://user-images.githubusercontent.com/29990176/27979535-6be372ae-637f-11e7-8138-5313b4d7b765.png)
![image](https://user-images.githubusercontent.com/29990176/27979543-772b9d12-637f-11e7-87b7-4b8873f8881e.png)
thank you!

**Comment by mrfearless** [comment]
check your stats page online to view payouts. NiceHash has recently changed minimum threshold for paying out - I got a payment today.
