### ISSUE TITLE
Nicehash 1.5.1.0 decred benchmark - file not found

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner-Archived#116]
Perform a clean installation.

[9:16:38] [BENCHMARK] Benchmark starts
[9:16:38] [NVIDIA5.x] Starting benchmark:  --algo=decred --benchmark --time-limit 20   --devices 0
[9:16:38] [NVIDIA5.x] Benchmark Exception: Не удается найти указанный файл (File not found)

**Comment by Kayfolom** [comment]
Solution found:
Download http://cryptomining-blog.com/7718-new-ccminer-1-7-1-fork-by-alexs78-with-improved-vcash-and-decred-performance/ , rename 64-bit version to ccminer_decred.exe and place it to NiceHashMiner\bin

**Comment by theLosers106** [comment]
That error indicates that the file is not there.. so most likely your antivirus has deleted it.. if that solves your problem, then I would like to close this issue.. thanks (:

**Comment by Kayfolom** [comment]
ccminer_decred.ehe file is missing in the archive https://github.com/nicehash/NiceHashMiner/releases/download/1.5.1.0/NiceHashMiner.v1.5.1.0.zip
