### ISSUE TITLE
Add for NiceHash

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#117]
Add a setting to specify NiceHash priority processes in the system.
Also, please add a customizable delay in seconds for the start of mining after the start of the program

Now I use this startup script:
ping 127.0.0.1 -n 150
C:
cd C:\NiceHashMiner
start /low NiceHashMiner.exe

**Comment by foxwarernd** [comment]
It would also be a good idea to assign priorities to the individual preferences of mining processes on the CPU and on the GPU, so leaving one core for mining for the GPU ( GPU without losing performance of mining ) .

such as the CPU of mining low priority , and the priority of mining for the GPU below average

**Comment by nicehashdev** [comment]
CPU mining is always low priority.
GPU mining priority has no effect - priority can be assigned only to CPUs.

Explain why do you need startup delay?

**Comment by foxwarernd** [comment]
With regard to the priority : if not configured liberate one CPU core , the GPU Mining is reduced . That is a good idea to assign machine CPU usage priority for the CPU and GPU of mining processes ( I'm not talking about the priority in the GPU on the graphics subsystem ) .
Pause to start necessary in my situation when you turn off the light : the light is lost - loaded router ( rising Internet connection) , and the computer has booted up and can not see nicehash Internet - and brakes.

**Comment by Singman33** [comment]
Use the "Less threads" option (ie, put 1 to free one core).

**Comment by foxwarernd** [comment]
already I use

**Comment by Singman33** [comment]
You are asking ultra specific option for your own use, outside of the scope of NicehashMiner. You already have many solutions.
