### ISSUE TITLE
NiceHash Miner v1.7.5.13 - CudaDeviceDetection.exe Issue

### ISSUE THREAD

**Issue by Tornadocraver** [nicehash/NiceHashMiner-Archived#1174]
I recently found a Nvidia GeForce 7900 GTX (which I think is an old model). After putting it in my PC (Windows 10, 64-bit) and installing the drivers, I wanted to try mining with it using the NiceHash Miner. Initially, when I start NiceHash, it gives me a message box with this error:

![image](https://user-images.githubusercontent.com/20540006/28249614-0e8aeed0-6a27-11e7-9ab7-e4b3cc3f2737.png)

I do have the "latest" driver for my card (which is 309.08; ancient compared to newer devices):

![image](https://user-images.githubusercontent.com/20540006/28249708-fa943d30-6a28-11e7-9cf2-113b3f2e7195.png)

I've also tried to find the "nvmllnit_v2" library (with no luck), installed the CUDA SDK (as per the documentation for CudaDeviceDetection.exe), and re-installed the same version of the video driver (as a clean install). I am still getting the error. Here's the contents of the NiceHash folder:

![image](https://user-images.githubusercontent.com/20540006/28249656-e8ddcd50-6a27-11e7-831e-302dd28e63d7.png)

Here's another error that comes up when I click "OK" on the first error:

![image](https://user-images.githubusercontent.com/20540006/28249669-3cccd528-6a28-11e7-94da-36fdd3ecc08e.png)

I also have the log file contents, but don't want to upload it yet in case there's any personal information in it (I'm very new to mining). I can upload it if you can prove that it's safe to do so. Thanks for your time, and I eagerly wait for a response on the matter.

**Comment by OneOfMany07** [comment]
According to wikipedia "Release date | June 2005–2006" so yep, pretty old now.  I think it retails for $35 from at least one place on Google.  I'm guessing current NVidia software doesn't support a card that old.

At least it isn't listed on the CUDA supported page.  https://developer.nvidia.com/cuda-gpus

Think you're out of luck.  Sorry.

**Comment by Squall-Leonhart** [comment]
this gpu predates CUDA, it was still when graphics cards had seperate pixel and vertex shaders.

**Comment by Tornadocraver** [comment]
Hi guys, thank you for your responses. I had no idea that the GPU was that old, lol. Maybe I could get a few dollars for it on Ebay or something.
