### ISSUE TITLE
[feature request] CUDA Compute 6.1 for Nvidia Mining (GTX 1080/1070)

### ISSUE THREAD

**Issue by SasaharaNatsuki** [nicehash/NiceHashMiner-Archived#118]
Are you going to add a GPU Nivida6x Mining option for the new Pascal GPUs, GTX 1080/1070?

Just got a nice GTX 1080, but working out what is best to mine manually is a pain. :)

And if so, is there an eta?

Thanks

**Comment by nicehashdev** [comment]
Yes, we have plans eventually, but we need to obtain this hardware first so we can analyse it and test.

When NHM has support for it, it will be announced & released.
