### ISSUE TITLE
NVIDIA GTX 1080 not recognized

### ISSUE THREAD

**Issue by mdaria510** [nicehash/NiceHashMiner-Archived#119]
The cards mine just fine when manually launching the mining tools, but the nicehashminer doesnt recognize them at all.

**Comment by nicehashdev** [comment]
We will add support in following version but mining programs may not have been optimised for SM 6.x.

**Comment by mdaria510** [comment]
I cant speak for all of them, but Lyrarev2 is working great and pulling in
a solid $5 a day on a GTX 1080.
