### ISSUE TITLE
How to reset benchmark on nicehash miner 2.0.0.8

### ISSUE THREAD

**Issue by C1BERUS** [nicehash/NiceHashMiner-Archived#1190]
Just like a title says, can you tell me how to reset benchmark on NHM 2 ? I got very low benchmark on my 470 only got 10mh/s..... i benchmark it using the newest driver, after that i want to reset my benchmark and using the old drivers.

thanks :)

**Comment by S74nk0** [comment]
Please open nhm2 issues [here](https://github.com/nicehash/NiceHashMiner2/issues).

Closing issue as it is not related to nhmv1
