### ISSUE TITLE
[Request] Add Settings Toggle to Disable Warning for Unbenchmarked Algorithms

### ISSUE THREAD

**Issue by doug-sw** [nicehash/NiceHashMiner-Archived#1193]
There are a few algorithms that do not benchmark correctly. Coincidentally, I do not want to mine these algorithms. I have disabled them from the allowed algorithms in the settings, however I am still met with a prompt saying that there are unbenchmarked algorithms.

Would it be possible to add a toggle to the settings to skip this pop up for disabled algorithms? Thank you.

**Comment by FathomX** [comment]
This would be a great feature to add. I am having the same issue. I must initiate mining manually everytime i start my rig up.
