### ISSUE TITLE
sgminer freezes

### ISSUE THREAD

**Issue by Fossius** [nicehash/NiceHashMiner-Archived#12]
Bug: sgminer-5-1-0-optimized freezes  while x11 mining. Bug is floating, sometime after 3 hours mining, sometime after 20 minutes mining.
win7x64, 2 R9 280X, amd-catalyst-15.7.1
Please combine all algorithms with single sgminer, to provide Auto-Switching Multi-Algorithm Mining  ::)

**Comment by kenshirothefist** [comment]
sgminer-5-1-0-optimized is integrated into NiceHash Miner, when using sgminer with NiceHash Miner GUI, the NiceHash Miner applications itself provides Auto-Switching Multi-Algorithm Mining and also auto-restarts sgminer if it freezes. That said, if you use sgminer within NiceHash Miner your all good to go.

**Comment by kenshirothefist** [comment]
Explanation was given, closing.
