### ISSUE TITLE
m/BTC significant decrease.

### ISSUE THREAD

**Issue by jrousian** [nicehash/NiceHashMiner-Archived#1201]
Intel i7 5930k 6 core 15mb cache CPU
EVGA 1070 FTW edition 
Viper 32gb ddr4 ram
1000watt P/S

I was originally mining at about $4.45-$5.96 and now it's gone down to an average of $1.40-$2.08?

Any suggestions on what I may do to increase this? or resolve

**Comment by HailHEN** [comment]
I think its due to the uncertainty caused by the Fork on August 1 by Bitcoin. Its affecting all miners

**Comment by rbj325** [comment]
Because of the upcoming fork there were a few major spikes over the past week or so.  The numbers you are seeing now are more accurate to what you should see with your equipment.

https://www.nicehash.com/?p=calc

**Comment by S74nk0** [comment]
@jrousian Please post only issues related to NiceHash Miner bugs, feature requests, code,...

Closing ...
