### ISSUE TITLE
daggerhashimoto no solution on nvidia GTX660ti ?

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#121]
![dag](https://cloud.githubusercontent.com/assets/16473762/15989288/a0ad9f68-3073-11e6-9eca-379b03182060.jpg)

Daggerhashimoto doesn't get any solution on nvidia GTX660Ti
(left side of the screen, red desktop) even with the difficulty decreased
On a GTX970 it runs correctly.
(right side of the screen, green desktop)
Surprisingy, the GTX660TI is only half of the 970 power. It should work...

Analyzing the window output, have noticed
something interesting..  [A0+0:R0+0:F0] from the 660
compared to [A272+0:R0+0:F0] from the 970
could be this the bug?

**Comment by nicehashdev** [comment]
You should post this issue here: https://github.com/Genoil/cpp-ethereum

As it is related to ethminer's mining capabilities.
