### ISSUE TITLE
2.0.0.11 - Alpha

### ISSUE THREAD

**Issue by Timoulis** [nicehash/NiceHashMiner-Archived#1214]
2.0.0.11 - Alpha, opens a dead excavator window doing nothing when i start NHM. Closing it just restart the dead window.
Is this normal or what?
Win 10 64b, 2X RX 470-8Gb

Regards 
Tim

**Comment by vertexinc110** [comment]
I also face a problem in new version start button remain disable I can able to start mining.
while older version work fine.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/1208234/log.txt)

![untitled](https://user-images.githubusercontent.com/30834742/29074591-b8003ef4-7c04-11e7-8902-28cdf5bf06dd.png)

**Comment by Timoulis** [comment]
This is because this version doesn't recognize your CPU and GPU.
I also have problems with older Gpu's like my GT 740. 
2.0.0.11 - Alpha doesn't recognize it also.No broblems with the old NHM.

**Comment by S74nk0** [comment]
@Timoulis please open nhm2 related issues [here](https://github.com/nicehash/NiceHashMiner2/issues).
Closing issue not related to this project.
