### ISSUE TITLE
NiceHashMiner-1.7.5.14 issues

### ISSUE THREAD

**Issue by Swiapq** [nicehash/NiceHashMiner-Archived#1215]
Hello,

How do I open this application, where is the exe/application file?

On previous version NiceHashMiner 1.7.5.13 is was simple, it was one file "NiceHashMiner" application, but on this new version 1.7.5.14, is missing.

Thanks!

**Comment by josephx86** [comment]
I tried the new NHM 2 but it seems buggy (maybe because it's alpha?) but then I cannot find NiceHashMiner 1.7.5.14. The link is missing.

Thanks

**Comment by remzkie** [comment]
no exe file :(

**Comment by pitergui** [comment]
1.7.5.14. ????????

**Comment by Swiapq** [comment]
NiceHashMiner 1.7.5.14. you can download from here, but is missing the exe/application file to start this application:

https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.14

https://github.com/nicehash/NiceHashMiner/archive/1.7.5.14.zip

**Comment by mondial-btc** [comment]
ok ca va

**Comment by cobusg** [comment]
Surely it cant be difficulty for somebody in the know to answer the question from Swiapq, how to use version1.7.5.14.  I tried to search, but cant find the answer, where is the exe for this version?

**Comment by josephx86** [comment]
I tried the legacy miner from https://github.com/nicehash/NiceHashMinerLegacy/releases

I haven't had any issues with the latest prelease (1.8.1.0 Prerelease 4) but if you want a stable release there is 1.8.0.2, released about 2 weeks ago. 

I'm using the prerelease because it gives me higher hash rates (even though power drawn increased by about 20W... something i'll tweak when I get time).

**Comment by nicehashdev** [comment]
There is no 1.7.5.14, it is just a placeholder for you to go to page https://miner.nicehash.com

There you can choose two versions: NHMv2 or NHM Legacy.

NHMv1 has been retired and will never be updated anymore, it is time to move on, especially if you want higher speed and more profit.

**Comment by cobusg** [comment]
Thanks for the reply

**Comment by cobusg** [comment]
Thanks for the reply, appreciated

**Comment by Swiapq** [comment]
Thanks for the reply!
