### ISSUE TITLE
2.0.0.11 Alpha crashed and removed itself

### ISSUE THREAD

**Issue by vanilla-thunder** [nicehash/NiceHashMiner-Archived#1218]
Hi, 
i tried to start parallel CPU & GPU mining with NiceHash software, but it always wanted to use my GPU for mining even if it was disabled in hardware overview (at least i think, that the small gray/green switch disables/enables hardware for mining).
So i tried to start second nicehash instance for CPU mining, but after the loading screen both instances crashed and "NiceHash Miner 2.exe" disappeared.
I started the installer again, but it removed nicehash and the installer itself from my disk. There was no option to select install / repair / remove or something like that.

OS: Windows 10 Pro v.1703
AV: Avast free (no warnings with this miner version)
CPU: i7-6700K
GPU: EVGA GTX 1080 Ti

Everything works again after removing C:/program files/nicehash2/ and reinstalling miner

**Comment by S74nk0** [comment]
Please open nhm2 issues [here](https://github.com/nicehash/NiceHashMiner2/issues).

Closing issue as it is not related to nhmv1
