### ISSUE TITLE
gtx770 not showing up :(

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner-Archived#1219]
hello.  noob here

3770k (4.6ghz) in z77 sabertooth mobo with gtx 770 4gb

all my drivers are upto date. but my gpu count remains at 0.

any way to remedy this?

thanks
jim

**Comment by Timoulis** [comment]
Latest version problem.
Install previous.

**Comment by jimmyhackers** [comment]
yes it would appear the legacy edition recognises both my cpu and gpu 

great work dude thanks.
