### ISSUE TITLE
Nvidia 750TI not recognized 

### ISSUE THREAD

**Issue by SirPsychoSexy0** [nicehash/NiceHashMiner-Archived#122]
![screenshot_549](https://cloud.githubusercontent.com/assets/19897028/15995220/bd79edfc-30ed-11e6-885c-90e7376c2371.png)
The only device its showing up is my CPU, need some update on this. 

Cheers :)

**Comment by future74** [comment]
Have you updated Nvidia drivers , I have same set up and it works fine for the past 4days

**Comment by SirPsychoSexy0** [comment]
after some days battling against my drivers, i've found a version which works, thanks my friend!
