### ISSUE TITLE
sma freeze on load then says no connection and wont mine

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner-Archived#1226]
bit of a weird error here.

i accidentally turned my router off for 30 minutes or so. upon turning it back on two of my three rigs have begun mining again with no problem.

but one has developed a problem. upon loading nicehash legacy, the green bar gets stuck on the sma part. then it gives me an error about not being able to connect to the internet and i cant mine. the pc however is fully connected and i can access the regular internet as normal through the browser etc 

windows 7 error reporting sent an error report about nicehash but returned no results. annoyingly i cant find the log (might need instruction on how to find it).

ive tried the disabling ipv4 and 6 thing but neither one off or on helps.
the computer is connected to the same router by cable as my other 2 rigs which are working fine.

all i can think is the disconnect has somehow caused an error that hasnt cleared in a log somewhere.

any help would be greatly appreciated

**Comment by jimmyhackers** [comment]
update: 
i have updated from v 1.8.1.0 pre4 preview to the full blown version.....

problem is solved hopefully never to reappear.

and my dell xps 630i with a e6550 and a gtx 660 is back to normal :P (all of 20 cents a day)

thanks me ( i think )
and who ever fixed the bug in the newer version???

**Comment by darkneon2002** [comment]
![sma nicehash](https://user-images.githubusercontent.com/10987492/34908646-7c24883e-f893-11e7-8d93-c5ade8c39d8a.png)

having this issue
2.0.1.5 works flawlessly
