### ISSUE TITLE
Earnings went down just after updating to 2.0.0.12 gtx1080ti Windows

### ISSUE THREAD

**Issue by TyHuffman** [nicehash/NiceHashMiner-Archived#1230]
ASUS GTX 1080ti, Windows 10 latest update and current. My profits went from $4.47 daily to $3.67 daily right after updating from 2.0.0.11 to 2.0.0.12. I restarted due to the 1080 bios patch ( do I need to do that every time? ) I have ensured that the GPU settings are all the same Max clock, Max memory, power at +0%. (edited in) I just noticed that my mining rate on Lyra2rev2 is very similar, 74MHs versus the old rate of 75MHs. Just adding info as I come across it. When I noticed the profit drop I did go back at reconfirm the benchmarks in Standard benchmark mode, and all benchmarks were very similar to a bit better than the previous benchmark.

A bug is now my GPU temperature is not being read. No worries about overheating on my end because I keep the power setting neutral and boost up the fans a bit. But it would be nice to be able to see the temp in the future.

**Comment by user01010111** [comment]
Earnings fluctuate with market rate. May be related?

**Comment by TyHuffman** [comment]
Yep, the market was in play. I believe another person was caught off guard. It was a 20% to 25% drop in the time it took to update.

My hash rate is down but not by much but still down. Again I attempted to get a good idea of how it was performing prior to the update so I could compare.

**Comment by user01010111** [comment]
What was the BIOS patch that you applied? You could always run the old version for a bit and compare, but really unless the underlying miners changed version (e.g. Claymores updated) there should be no change in hashrate as NiceHash-Miner is really just a front end/control module for the underlying apps.
