### ISSUE TITLE
error: (403) Forbidden

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#124]
Everything worked great, than at about 3am a problem occurred. It seems Nicehash miner cannot connect, problem with internet. But internet works fine i can even ping through telenet, i can bench mark but i cannot mine.

What can be the problem?

Log file says there is an error: (403) Forbidden

Latest version of the miner windows 7

**Comment by theLosers106** [comment]
Does it still have problem connecting to the internet? If so, please contact NiceHash at support@nicehash.com as it might be either your internet connection or you might have been blocked by NiceHash server
