### ISSUE TITLE
Not credited for dual mining

### ISSUE THREAD

**Issue by jaspsev** [nicehash/NiceHashMiner-Archived#1242]
Hi,

I am new so sorry if this is a repeat.

I started mining a few days ago (mostly on Lyra2REv2 and on Equi/Lbry) and noticed that the web stats is not crediting me for the Equi/Lbry. 

Web: https://new.nicehash.com/miner/17mJ5w8djBZPjT7ypLwpLKKWuVzjr3oiz1
![screenshot 2017-08-24 08 49 45](https://user-images.githubusercontent.com/31302650/29651579-156e8b70-88aa-11e7-9817-40f4b567381a.png)
![screenshot 2017-08-24 08 50 00](https://user-images.githubusercontent.com/31302650/29651580-156ef8bc-88aa-11e7-8a29-507598f6c9b4.png)

Am I doing something wrong? Thanks.

**Comment by HailHEN** [comment]
It is crediting you, it just fluctuates frequently.

**Comment by S74nk0** [comment]
This is a fixed bug. Closing
