### ISSUE TITLE
NiceHashMiner 2 stuck at "Starting Excavator Server"

### ISSUE THREAD

**Issue by ckhung5** [nicehash/NiceHashMiner-Archived#1245]
Hi, I just updated to v2.0.1.0 version and it got stuck at  "Starting Excavator Server".

Any Idea?

**Comment by ckhung5** [comment]
It took longer load.. Everything is good

**Comment by Pititul** [comment]
Mine does work. It asks to benchmark again.

**Comment by Pititul** [comment]
Mine doesn't work. Sorry. Any idea why it keeps asking mento benchmark again and again.

**Comment by RBTData** [comment]
Mine wont benchmark after waiting 15 min fot excavator to finish its thing.
