### ISSUE TITLE
Balance displayed wrong

### ISSUE THREAD

**Issue by aronpc** [nicehash/NiceHashMiner-Archived#125]
He jumps decimal places to the left

My Balance: 0.09999999
Displays : 9.99999900

v1.5.1.0

**Comment by tonyrayo** [comment]
The balance is shown in mBTC, it looks like the top is BTC and the bottom mBTC however I'm not sure (I'm having to use an old version due to issues).

**Comment by theLosers106** [comment]
Could you provide a screenshot of both balances so it is easier to understand? Thanks
