### ISSUE TITLE
Click "yes" to P0 state automatically

### ISSUE THREAD

**Issue by leftishness** [nicehash/NiceHashMiner-Archived#1255]
I have my rigs set to restart every so often and, when they restart, P0 is supposed to be set in the config. However, Windows always asks to authenticate when NH attempts to set P0. If I don't manually click 'yes' every time my rigs reset, it never begins mining. I need a way to have the miner start mining after a restart without any interaction (which should really be a priority since anyone with lots of miners won't want to interact with each of them at every restart). In other words, how do I set P0 without Windows authenticating?

**Comment by C1BERUS** [comment]
dont use P0 on nicehash, use NVIDIA inspector instead to set your card always on P0.

**Comment by S74nk0** [comment]
@UnderwearWarrior NVIDIA P0 requires admin privileges so if you log in as an administrator user there will be no prompt. This is a how Windows user permissions work, this cannot be changed. If you run the program as Administrator there will be no prompt.
