### ISSUE TITLE
Whirlpool X on GTX 760 not working

### ISSUE THREAD

**Issue by Kickbub** [nicehash/NiceHashMiner-Archived#126]
I tried bench marking on my GTX 760 and the program always gets stuck on Whirlpool X. I checked that the ccminer-tpruvot process is running, but ASUS GPU Tweak says that the GPU usage is at 0%.

**Comment by theLosers106** [comment]
I have had the same problem before.. Will be fixed in the next release.. Thanks (:

**Comment by tonyrayo** [comment]
Same with 660 Ti so glad a fix is coming :+1: 

**Updated**
Fixed in beta release - https://github.com/nicehash/NiceHashMiner/commit/6c79bfb14367dc62b2dae7b8dec3618a0b3cbb90

**Comment by Kickbub** [comment]
This seems to be a problem for the Nvidia3.x devices. My friend has a Nvidia5.x device and the benchmark works perfectly.

**Comment by theLosers106** [comment]
Have you tried the latest NiceHashMiner.. it should be fixed.. Thanks
