### ISSUE TITLE
DaggerHashimoto benchmark issue

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#127]
NHM 1.5.1.0. A week ago all works fine. Today tried to benchmark daggerhashimoto algo again to measure speed with last size of dag-file. But benchmark starts, "Creating DAG" (10-20 min) and nothing... My GPU's don't loaded and in process list there is no ethminer.exe.
In the log.txt:
"[INFO] [AMD_OpenCL] Exception: System.Exception: GetCurrentBlock returns null..
   в NiceHashMiner.Ethereum.CreateDAGFile(Boolean HideWindow, String worker)"

Mining runs normal. Problem is only with benchmark...

**Comment by theLosers106** [comment]
This will be improved in the next release.. Stay tuned.. Thanks (:

**Comment by UnclWish** [comment]
Thanks to you. )))) I just want to improve program and remove all bugs. NHM is amazing software...

**Comment by nicehashdev** [comment]
In next version, DAG will be generated on GPU so you shall not have such issues anymore. Closing this.
