### ISSUE TITLE
NVIDIA GeForce GT 630M not detected

### ISSUE THREAD

**Issue by helymia** [nicehash/NiceHashMiner-Archived#1272]
I am using NiceHash Miner 2.0.1.1 - Beta and my GPU (GeForce GT 630M) is not detected in available hardware menu.

I uninstalled and installed Nvidia driver but it still doesn't see my GPU.

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner2/wiki/Supported-Hardware#nvidia
