### ISSUE TITLE
GeForce GT650M Not detected - Nicehash 2.0.1.1

### ISSUE THREAD

**Issue by applebus1** [nicehash/NiceHashMiner-Archived#1273]
Nicehash 2.0.1.1 cannot detect my GPU.

This is the experiment I tried.
I updated the version of Nvidia and run the program. The program then froze and showed

> The 'Nvidia GeForce GT 650M' device is not removable and cannt be ejected or unplugged

I was forced to do a hard restart after Nvidia updated but this seemed like Nicehash was able to detect my GPU. 

Now I had no choice but to reinstall the old version of Nvidia and Nicehash 2.0.1.1 cannot detect my GPU. At this point, I think the problem is the version of the program are not compatible. I really want to try the older version of Nicehash. If anyone has a link, please help me.

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner2/wiki/Supported-Hardware#nvidia
