### ISSUE TITLE
DaggerHashimoto new ethminer

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#130]
Hi!
This is not a issue just a quastion: why ethminer.exe starts always with singlekeep option of dag-load-mode?
It uses large amount of RAM with this option. Why don't use the parallel mode?

**Comment by nicehashdev** [comment]
This mode allows quick algorithm switching, because DAG is kept in host memory. Otherwise, with each switch, DAG would have to be regenerated and miners loosing important time.

**Comment by UnclWish** [comment]
I see - when NHM switch to other algo, ethiminer is paused.
But i think it must be an option in settings, that will allow to change modes for ethminer. F.e. i want to try ethminer in parrallel mode.

**Comment by UnclWish** [comment]
Updated me previous post...

**Comment by nicehashdev** [comment]
We believe that any decent mining machine already has enough ram to keep DAG in memory.

Setting additional parameters, you can reconfigure DAG generating, but we do not recommend this, because you will be earning less.
