### ISSUE TITLE
[BUG] Out of Range Exception with daggerhashimoto & GTX960

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#131]
![zzz](https://cloud.githubusercontent.com/assets/16473762/16257352/4a0752f2-3858-11e6-9a42-7dbbc3928821.jpg)
I tried also with a GTX970 but I got same error.

**Comment by theLosers106** [comment]
Did by any chance you copied any part of the config file from older NiceHashMiner?

**Comment by apprehensivemom** [comment]
![cas](https://cloud.githubusercontent.com/assets/16473762/16264315/234a16a6-3879-11e6-90bb-88d48f44a220.jpg)
no. Clean config fille.
The bug is triggered only when daggerhashimoto is running, BUT NOT IN THE BENCHMARK.
daggerhashimoto benchmark runs ok  (8829 MH/s with GTX960)

**Comment by theLosers106** [comment]
Can you try this fix please.. https://drive.google.com/open?id=0B6kB9L8GNvQwbE9KZldobGJiUVU
Thanks.

**Comment by miji** [comment]
The fix worked on 970 and 980ti. However, it is not working (neither benchmark nor mine) on 1080 (Win7 x64)

**Comment by apprehensivemom** [comment]
![senza titolo-1](https://cloud.githubusercontent.com/assets/16473762/16267210/d13cb6b0-3888-11e6-9ab5-ee8f5cbb3cff.jpg)
The fix worked on GTX 960 but it keeps closing and reopening the upper left window and no result at all.
(image taken 1 second before restart)

**Comment by miji** [comment]
Same issue here with GTX 1080

**Comment by theLosers106** [comment]
try this.. https://drive.google.com/open?id=0B6kB9L8GNvQwalhEa1pka3BiWXM and if it still fails.. just increase the MinerAPIGraceSeconds to like 60 or 120.. I have had this happened to me but sometimes it works fine.. sorry for the trouble..

**Comment by apprehensivemom** [comment]
it works for me now. (gtx 960)
Thanks.

**Comment by miji** [comment]
![capture](https://cloud.githubusercontent.com/assets/5583549/16271596/f5f1cd30-389a-11e6-8026-3415033b248a.PNG)
No luck here...

**Comment by theLosers106** [comment]
daggerhashimoto/ethereum is a know problem on GTX1080/GTX1070.. I am not sure why it got detected on NiceHashMiner though but you should disable that algo manually.. When a fix is available, we will include it in future release.. Thanks..
