### ISSUE TITLE
this software is useless

### ISSUE THREAD

**Issue by plifter** [nicehash/NiceHashMiner-Archived#132]
this version crashes my graphics on everthing execpt x11 and eth. nothing else works. last version I had terminations on  x15, x13 and a couple of others but never this. please fix so it no longer crashes

**Comment by theLosers106** [comment]
You would need to explain more on your situation.. what GPU and OS are you using?

**Comment by plifter** [comment]
I am using xfx amd r9 390x and win 10

**Comment by plifter** [comment]
now is no longer getting profitbility anymore

**Comment by theLosers106** [comment]
1. What driver version are you using for nVidia and AMD?
2. Try this (https://drive.google.com/open?id=0B6kB9L8GNvQwMlIxZU9LTjNzbGs) and if it still crashes then please paste the log file here.. Thanks

**Comment by plifter** [comment]
crimson driver 16.5.3

**Comment by plifter** [comment]
I downloaded it but just says nicehashminer stopped working. getting a freeze

**Comment by theLosers106** [comment]
I would recommend using driver v15.11.1 as earlier than that has produced unexpected behavior..

**Comment by plifter** [comment]
change over to that driver not having as many problems with the new version but getting poor speeds. tried to mine dagger directly. having connection problems libcur 52

**Comment by nicehashdev** [comment]
If you still have issues with latest version, please, reopen this.
