### ISSUE TITLE
Balance and daily estimated earnings is 0

### ISSUE THREAD

**Issue by Inside99** [nicehash/NiceHashMiner-Archived#1328]
Hello,

Today I change the wallet adress, and Balance and daily estimated earnings is 0, my PC is working.

Balance grows every minute. I also checked the wallet address and is ok.

What can it be?

Nicehash version is : 2.0.1.3, but the issue is also the same with the new version 2.0.1.4.
I also attached here  a printscreen.

![daily-estimated-earnings-not show](https://user-images.githubusercontent.com/33549765/32665147-06ca0052-c63c-11e7-9898-cfe1c70d7bf8.jpg)

**Comment by Inside99** [comment]
Solved, was a issues from Nicehash.

**Comment by SebastienOuellet** [comment]
I get the same issue today, What have you done ? close-open the app ?
