### ISSUE TITLE
1.6.0 dagger-hash crashes

### ISSUE THREAD

**Issue by crysishc4l** [nicehash/NiceHashMiner-Archived#134]
Hey, i just updated to 1.6.0 but as soon as my GTX 650 TI BOOSTED starts mining with the dagger hash , it crashes with a unhandled exception 
![image](https://cloud.githubusercontent.com/assets/16018466/16266290/5a2680dc-3884-11e6-88be-a4f6689c572d.png) , it did work without a crash on the 1.5.1 for me

**Comment by theLosers106** [comment]
Can you try this fix please.. https://drive.google.com/open?id=0B6kB9L8GNvQwbE9KZldobGJiUVU
Thanks.

**Comment by crysishc4l** [comment]
That did the trick, awesome fast response thank you verry much!!

**Comment by crysishc4l** [comment]
i did found a new problem, eth miner keeps restarting before it is even able to finish the new DAG file, so its start recreating the dag file, but around 50 - 80% it restarts (only got dagger hash selected to mine at this moment got a solusion for this as well?)   , i assume this is becuase of the way you create a DAG file now and nolonger save it on the hdd?

**Comment by theLosers106** [comment]
try this.. https://drive.google.com/open?id=0B6kB9L8GNvQwalhEa1pka3BiWXM and if it still fails.. just increase the MinerAPIGraceSeconds to like 60 or 120.. I have had this happened to me but sometimes it works fine.. sorry for the trouble..

**Comment by crysishc4l** [comment]
thanks that worked great, no problem bugs happon ;D, thanks for the good support there m8

**Comment by theLosers106** [comment]
You are welcome.. Will release this bug fix soon if you want to get the "official" build of NiceHashMiner even though I am the one that compiles it anyways.. =P
