### ISSUE TITLE
NeoScrypt benchmark never ends

### ISSUE THREAD

**Issue by b-f-** [nicehash/NiceHashMiner-Archived#1346]
After auto-update to 2.0.1.5-beta and Start button click, NeoScrypt benchmark is auto-started and gets stuck at 50%. After stopping benchmark manually, mining details are unavailable.

GPU: MSI gtx 1050ti
Console output:
Excavator v1.3.6a_nvidia GPU Miner for NiceHash.
Build number: 99
[0x00002fcc][info] core | Preparing benchmark for MSI GeForce GTX 1050 Ti - NeoScrypt
--------- Benchmark never completes (> 4min).

Issue fixed by machine reboot.

**Comment by hulk500** [comment]
hey
