### ISSUE TITLE
ethminer crashes on version v1.6.0.0

### ISSUE THREAD

**Issue by FishEagle** [nicehash/NiceHashMiner-Archived#135]
NiceHashMiner_v1.5.1.0 works fine, but on the new version ethminer crashes

I'm running Win 7 64 bit with a GTX 970 and a R9 290x

**Comment by theLosers106** [comment]
Try this (https://drive.google.com/open?id=0B6kB9L8GNvQwMlIxZU9LTjNzbGs) and if it still crashes then could you post the log file of the crash? Thanks.

**Comment by FishEagle** [comment]
It still crashed with that version. I checked a bit further and found that the AMD card still did daggerhashimoto, it was just the NVIDIA card that crashed.

Upgrading my NVIDIA driver fixed the crash, only problem is that now daggerhashimoto is Disabled for the NVIDIA card in NichHashMiner. Hopefully a newer driver or ethminer will be available in future that allows for better mining.
