### ISSUE TITLE
ethminer crashes on version v1.6.0.0 with minimumProfit

### ISSUE THREAD

**Issue by PauloOF** [nicehash/NiceHashMiner-Archived#136]
Hi,

After install V1.6.0.0, NiceMiner crashes opening a error box dialog, case I set the parameter MinimumProfit ($/day) different from 0. With 0 works fine.

I have testing in 4 miner machines with different HW (GPUs R390X, R290X, R280, etc. and windows 10) and always got the same issue. In the previous NiceHash Miner version is working fine with same set of parameters.

Thanks.
Paulo
PS. Case it helps the msgs at error window:

System.IndexOutOfRangeException: Índice fora dos limites da matriz.
   em NiceHashMiner.Miner.AlgoNameIs(String algoname)
   em NiceHashMiner.Miner.GetSummary()
   em NiceHashMiner.Form1.MinerStatsCheck_Tick(Object sender, EventArgs e)
   em System.Windows.Forms.Timer.OnTick(EventArgs e)
   em System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by theLosers106** [comment]
try this.. https://drive.google.com/open?id=0B6kB9L8GNvQwalhEa1pka3BiWXM

**Comment by PauloOF** [comment]
Solved with V1.6.0.1!

Thanks.
