### ISSUE TITLE
Workers are going OFFLINE again!

### ISSUE THREAD

**Issue by AlexVirlan** [nicehash/NiceHashMiner-Archived#1360]
Hello there!
Since last night, I keep getting this errors:
"**SOCKET ERROR - RECEIVE error: socket closed**" - on NiceHashMiner v.2.0.1.5 Beta
"**cryptonight.eu.nicehash.com:3355 - connection reset by peer**" - on NiceHashMinerLegacy v.1.8.2.0-Pre2

Sometimes they connect. Work for a couple of minutes, then error again. I googled around and I haven't found any explanations.
How can we fix this? Please help!
Thank you.

------------------------------------------------------------------------------------------------------

UPDATE (at 09:56)
I saw that **NH is in maintenance mode**. I changed the servers to US. A slight improvement.

UPDATE 2 (at 10:35)
The **balance doesn't get updated**, even if my hashes are accepted...

UPDATE 3 (at 10:50)
**USA and INDIA servers are now giving errors** too...

**Comment by cipriz** [comment]
Looks like cryptonight got some serius issues, the legacy mimer 1.8.1.5 shows it mines 1.5-2.5$/day but my balance remain the same, only on cryptonight. Eight now the servers are on metenance and can't check it away. Hope they are fixing crypronight

**Comment by AlexVirlan** [comment]
Now, I get this:
**SOCKET ERROR - CONNECT error: No connection could be made because the target machine actively refused it.**
And this:
**[cryptonight.eu.nicehash.com:3355] connect error: "connection refused"**

**Comment by cipriz** [comment]
Maybe becouse nicehash is under metenance

**Comment by AlexVirlan** [comment]
@cipriz Yeah, I believe that is the problem.
**They've just changed the website to Maintenance mode.**

**Comment by Alandlau** [comment]
still error right now . .

**Comment by GITAHUB4U** [comment]
Website continues to be in Maintenance mode.

**Comment by interbiznw** [comment]
They were hacked and lost ~$60M.
https://www.reddit.com/r/NiceHash/comments/7i0s6o/official_press_release_statement_by_nicehash/

**Comment by AlexVirlan** [comment]
@interbiznw I just saw the press release this morning (it's 08:23 AM for me now).
I can't imagine the damage for some big miners. Also I really want to know about that security breach.
I hope they will fix it soon.

Here is the hacker BTC address https://bitinfocharts.com/bitcoin/address/1EnJHhq8Jq8vDuZA5ahVh6H4t6jh1mB4rq
Balance: 4,736.42811232 BTC = 68,094,502.5 USD
:|

UPDATE:
This two comments sounds interesting...
https://www.reddit.com/r/NiceHash/comments/7i0s6o/official_press_release_statement_by_nicehash/dqv8kiv/
https://www.reddit.com/r/NiceHash/comments/7i0s6o/official_press_release_statement_by_nicehash/dqvbynh/

**Comment by cipriz** [comment]
@AAv-Soft i know... it could be if you think it about it

**Comment by sgtlove** [comment]
Good day to you.

My name is Sgt.Leigh A. Hester,i will like to be your friend ,if you care please reply me back in my private email ( Hester.Ann.leigh87@gmail.com ) So that i will tell you more about my self .

**Comment by AlexVirlan** [comment]
NH still down. Those 24 hours passed long time ago.
BTC's value jumped so high these past days. $17K was the highest value. 
Maybe because of NiceHash's "maintenance"...? Hmm.
Now the hacker's BTC address is at ~80M$
