### ISSUE TITLE
1.6.0.0 Ethminer crashes, Lyra2v2 hangs, neoscrypt returns 0 in benchmark

### ISSUE THREAD

**Issue by lincolnjohnson** [nicehash/NiceHashMiner-Archived#137]
I'm probably not the usual hardware case here, but I figured I'd mention some issues with the new release anyways.
- Ethminer crashes on NHM load, fixed by copying relevant ethminer files from 1.5.1.0
- Lyra2v2 benchmark hangs with no result and no stop. Had to quit benchmark. Not fixed by replacing miner with 1.5.1.0 file. No relevant info in log other than benchmark started, quit by user 5 minutes later.
- Neoscrypt returns 0 in benchmark, same problem in 1.5.1.0

System spec:
Windows server 2012 R2 x64
Dual Xeon E5-2690
Tesla M60 Card w/ Cuda 7.5, 354.92 driver (newest available for M60)

Same ethminer problem with my GTX 960 box, fixed by using 1.5.1.0 ethminer files.

**Comment by lincolnjohnson** [comment]
Output from ccminer_nanashi_lyra2rev2.exe:

```
C:\...\NiceHashMiner_v1.6.0.0\bin>ccminer_nanashi_lyra2rev2.exe
*** ccminer 1.7.6 for nVidia GPUs by tpruvot@github ***
    Built with VC++ 2013 and nVidia CUDA SDK 8.0

  Originally based on Christian Buchner and Christian H. project
  Include some of the work of djm34, sp, tsiv and klausT.

BTC donation address: 1AJdfCpLWPNoAMDfHF1wD5y8VgKSSTHxPo (tpruvot)

[2016-06-22 16:46:03] Unable to query number of CUDA devices! Is an nVidia driver installed?
```

No relevant output on neoscrypt run.

**Comment by theLosers106** [comment]
Could you run this command inside the bin directory and show me the result:

`ccminer_tpruvot.exe --ndevs`

Thanks.

**Comment by lincolnjohnson** [comment]
On the tesla box:

```
GPU #0: SM 5.2 Tesla M60
GPU #1: SM 5.2 Tesla M60
```

On the GTX 960 box:

```
GPU #0: SM 5.2 EVGA GTX 960
```

**Comment by theLosers106** [comment]
For the Tesla M60, I do not have access to one so that would be a bit hard to help. The GTX960 should run perfectly as I have test on more than one system that has a single and also multiple 960s.. What driver version are you running for the 960? I am running 368.39 for all the testing..

**Comment by lincolnjohnson** [comment]
I'm also using 368.39 for the 960. I've done some digging on my own and haven't been able to figure out the Tesla problem either. I mean, it still works fine with 1.5.1.0 so I don't have a a problem running that one.

**Comment by nicehashdev** [comment]
If you still have these issues with latest version, reopen this.
