### ISSUE TITLE
Request miner addition

### ISSUE THREAD

**Issue by mavericknoob** [nicehash/NiceHashMiner-Archived#1377]
Please add xmr-stack (https://github.com/fireice-uk/xmr-stak) as GPU miner. 
Please see my thread on NiceHash Legacy issues page for details. https://github.com/nicehash/NiceHashMinerLegacy/issues/750

**Comment by Cryptominer937** [comment]
This miner is no longer maintained head over to either the legacy miner at
https://github.com/nicehash/NiceHashMinerLegacy
or version 2 of the miner at
https://miner.nicehash.com/
