### ISSUE TITLE
[FEATURE] Start mining after benchmark

### ISSUE THREAD

**Issue by vince120** [nicehash/NiceHashMiner-Archived#138]
Considering that benchmarking all algorithms take a while, it should be interesant to add a checkbox to ask NiceHashMiner to automatically start mining just after benchmark ending.

Thanks for your work

**Comment by theLosers106** [comment]
This should make it to the next major release.. Thanks for the suggestion (:

**Comment by Nickfost** [comment]
:+1:

**Comment by ghost** [comment]
If you have unbenchmarked algos then clicking Start brings up a popup asking if you want benchmarks to run before starting. If you accept it'll run benchmarks and then start mining, unless a benchmark fails and then it stops at a popup asking if you want to Try Again. In 1.7.9 this alternative does not work.

**Comment by Nickfost** [comment]
It asks me each time and then it fails each time. But it says it's "done" not that it had any issues.

Nick Foster
-----------------
me@nickfost.com

**Comment by S74nk0** [comment]
@thaistar `In 1.7.9 this alternative does not work.` this will be fixed/restored as it was in previous versions. This feature will be added in the next release.

**Comment by S74nk0** [comment]
[7484aa8](https://github.com/nicehash/NiceHashMiner/commit/7484aa818581c6e52d9bfec7f907437d0f885256) includes suggested feature.
Closing issue...
