### ISSUE TITLE
Cannot establish SSL/TLS connection - CryptoNight

### ISSUE THREAD

**Issue by electro1776** [nicehash/NiceHashMiner-Archived#1385]
So I started mining with nicehash on my Radeon HD 7700, which works with zcash standalone claymore miner just fine.

I started mining yesterday and everything was working fine, and suddenly it encountered this error:

(I've already combed through google and nobody seems to have had this issue before[or if they did they didn't report it], the closest I can find is something to the effect of "cannot validate trust relationship" or something similar regarding its inability to ssl/tls connect....) 

heres what it says in console:
Cannot establish SSL/TLS connection
Stratum - Cannot connect  to cryptonight.usa.nicehash.com port 33355
DevFee:  Stratum - Failed to connect, retry in 20 sec...
Cannot establish SSL/TLS connection
Stratum - Cannot connect  to cryptonight.usa.nicehash.com port 33355
 Stratum - Failed to connect, retry in 20 sec...

It just keeps repeating that over and over, I left it running all night to see if it would correct itself, but no such luck. it was suggested for another issue so I thought I would give it a try, but definately didn't work.

I'm using legacy, my card is an AMD.

Any ideas as to why this is happening?
Cheers mates!

![image](https://user-images.githubusercontent.com/34798733/34322211-a3e5c932-e7ef-11e7-8628-d346317a1051.png)

**Comment by electro1776** [comment]
UPDATE.
I fixed this by disabling this particular miner and using another, The profitablity is the same, but for whatever reason claymore's miner doesn't work properly right now. 
Hope this helps somebody :)

**Comment by midozido** [comment]
how did u disable it I am trying to stp sgminer cryptonight but in vain.
