### ISSUE TITLE
NHM 1.6 Random Crash // System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by morgll** [nicehash/NiceHashMiner-Archived#139]
First of all thx for your work! 
Running GTX970 I5 6600K on Windows 8.1 64bit and randomly getting this Exception error

`************\* Texte de l'exception **************
System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   à NiceHashMiner.Miner.EnabledDevicePerAlgoCount(Int32 algoIndex)
   à NiceHashMiner.ccminer.Start(Int32 nhalgo, String url, String username)
   à NiceHashMiner.Form1.SMAMinerCheck_Tick(Object sender, EventArgs e)
   à System.Windows.Forms.Timer.OnTick(EventArgs e)
   à System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by theLosers106** [comment]
try this.. https://drive.google.com/open?id=0B6kB9L8GNvQwalhEa1pka3BiWXM

**Comment by morgll** [comment]
Fixed! ... Thx
