### ISSUE TITLE
.NET Framework error with 1.2.2.0

### ISSUE THREAD

**Issue by forumaster** [nicehash/NiceHashMiner-Archived#14]
I get this error when i start the new version of nicehash miner during the check of AMD OpenCL devices, i don't have this bug in the 1.2.1.0, i cannot use 1.2.2.0 because the AMD OpenCL check is neverending....
I have an ACER ASPIRE 5755G with windows 7
sorry for my english
![jhiaole](https://cloud.githubusercontent.com/assets/16463429/12018989/db9fa454-ad6a-11e5-8f81-223744bb2b9e.png)

the text is this:
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

*************\* Testo dell'eccezione **************
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in NiceHashMiner.sgminer.QueryCDevs()
   in NiceHashMiner.sgminer..ctor()
   in NiceHashMiner.Form1.StartupTimer_Tick(Object sender, EventArgs e)
   in System.Windows.Forms.Timer.OnTick(EventArgs e)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Assembly caricati **************
mscorlib
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

NiceHashMiner
    Versione assembly: 1.2.2.0
    Versione Win32: 1.2.2.0
##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/NiceHashMiner.exe

System.Windows.Forms
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5492 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll

Newtonsoft.Json
    Versione assembly: 7.0.0.0
    Versione Win32: 7.0.1.18622
##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/Newtonsoft.Json.DLL

mscorlib.resources
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

log4net
    Versione assembly: 1.2.15.0
    Versione Win32: 1.2.15.0
##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/log4net.DLL

System.Configuration
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Windows.Forms.resources
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Debug JIT **************
Per attivare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
attivato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è attivato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by theLosers106** [comment]
Hi, have you tried running it as administrator (Right-click -> Run as administrator)?

Thanks.

**Comment by forumaster** [comment]
yes, same results

**Comment by kenshirothefist** [comment]
Can you please try this: https://drive.google.com/file/d/0B6kB9L8GNvQwYWp2TW4yZVBPOWc/view?usp=drive_web

Just replace NiceHashMiner.exe in your existing folder NiceHashMiner_1.2.2.0 with exe from link above.

**Comment by forumaster** [comment]
![screenshot_11](https://cloud.githubusercontent.com/assets/16463429/12027093/0ca4e026-adc2-11e5-8037-8c6d83904d32.png)

**Comment by theLosers106** [comment]
Could you post the details? Or is it the same as previous?

**Comment by forumaster** [comment]
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

*************\* Testo dell'eccezione **************
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in NiceHashMiner.sgminer.QueryCDevs()
   in NiceHashMiner.sgminer..ctor()
   in NiceHashMiner.Form1.StartupTimer_Tick(Object sender, EventArgs e)
   in System.Windows.Forms.Timer.OnTick(EventArgs e)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Assembly caricati **************
mscorlib
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

NiceHashMiner
    Versione assembly: 1.2.2.1
    Versione Win32: 1.2.2.1

##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/NiceHashMiner.exe

System.Windows.Forms
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5491 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5492 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5483 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll

Newtonsoft.Json
    Versione assembly: 7.0.0.0
    Versione Win32: 7.0.1.18622

##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/Newtonsoft.Json.DLL

mscorlib.resources
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

log4net
    Versione assembly: 1.2.15.0
    Versione Win32: 1.2.15.0

##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/log4net.DLL

System.Configuration
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5483 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Windows.Forms.resources
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5420 (Win7SP1.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Debug JIT **************
Per attivare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
attivato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è attivato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by mendoza1468** [comment]
Hi, im getting the same issue. Version 1.2.1.0 work well. But version 1.2.2.0 crash at startup

![capture](https://cloud.githubusercontent.com/assets/16471209/12029287/3f54e348-adb5-11e5-956f-f3073064b8dd.JPG)

It crash when he look for Querying AMD OpenCL devices. (I use Nvidia) maybe it can help you to find the source of the problem

IF I REPLACE THE NICEHASHMINER.EXE YOU SEND ABOVE IT WORKS WITH THE VERSION 1.2.2.0.

Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

*************\* Texte de l'exception **************
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à NiceHashMiner.sgminer.QueryCDevs()
   à NiceHashMiner.sgminer..ctor()
   à NiceHashMiner.Form1.StartupTimer_Tick(Object sender, EventArgs e)
   à System.Windows.Forms.Timer.OnTick(EventArgs e)
   à System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Assemblys chargés **************
mscorlib
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

NiceHashMiner
    Version de l'assembly : 1.2.2.0
    Version Win32 : 1.2.2.0

##     CodeBase : file:///E:/MINER/CCMINER/NiceHashMiner_v1.2.2.0/NiceHashMiner.exe

System.Windows.Forms
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/WINDOWS/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll

Newtonsoft.Json
    Version de l'assembly : 7.0.0.0
    Version Win32 : 7.0.1.18622

##     CodeBase : file:///E:/MINER/CCMINER/NiceHashMiner_v1.2.2.0/Newtonsoft.Json.DLL

mscorlib.resources
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

log4net
    Version de l'assembly : 1.2.15.0
    Version Win32 : 1.2.15.0

##     CodeBase : file:///E:/MINER/CCMINER/NiceHashMiner_v1.2.2.0/log4net.DLL

System.Configuration
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Windows.Forms.resources
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase : file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

**Comment by theLosers106** [comment]
@albysprx did you copy this NiceHashMiner.exe (link removed) to the appropriate folder? It should solve that bug.
@mendoza1468 so basically what you are saying is that the patch work right?

**Comment by mendoza1468** [comment]
Yes exactly, i copy this Nicehashminer.exe
(https://drive.google.com/file/d/0B6kB9L8GNvQwYWp2TW4yZVBPOWc/view?usp=drive_web) 
 and it solve the problem

**Comment by mendoza1468** [comment]
If there is update from the ccminer of sp, is it possible to put the new version inside with the same name to make it works?

**Comment by apprehensivemom** [comment]
For me it still doesn't work  when using NVIDIA GTX760,
even with the patched Nicehashminer v1221
Unhandled exception in the application. Click Continue to ignore the error and try to continue . Click Exit to stop the application immediately
System.NullReferenceException : Object reference not set to an instance of an object .
   in NiceHashMiner.sgminer.QueryCDevs()
   in NiceHashMiner.sgminer..ctor()
   in NiceHashMiner.Form1.StartupTimer_Tick(Object sender, EventArgs e)
   in System.Windows.Forms.Timer.OnTick(EventArgs e)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

If I switch the graphic card to a NVIDIA GTX960 Nicehashminer works even with version 1220

**Comment by forumaster** [comment]
yes, i copied it, in the screenshot you can see 1.2.2.1

**Comment by dontshootitsme** [comment]
I encountered this issue, too. I have 3 GTX960 Rigs.
#1: Resolved after upgrading to 1.2.2.1
#2: 1.2.2.1 don't work either. But 1.2.1.0 works fine.
#3: 1.2.x.x versions don't work. 1.1.0.5 workes fine.

**Comment by forumaster** [comment]
i have a nvidia geforce gt540m in my laptop

**Comment by tonyrayo** [comment]
Same issue here (freezing with .NET error when it goes to look for AMD cards).  I tried replacing the exe that @kenshirothefist provided (running Windows 7 Pro SP1 - ugh I know I will need to upgrade to Windows 10 soon but I'm not digging the "wall of boxes" :100: ).  I'm reinstalling VS 2003 Pro to see if I can help debug the issue.

P.S. - The previous official release - fd534ed3b710479116d6dad5931a3734a05baa48 - works and I was hoping to use that configuration file as a drop-in but the program scans for new hardware upon launch (as a dirty/quick fix, is there a flag that can disable either checking for AMD cards or checking for new hardware upon launch?)

Edit: I have yet to get home (extended family staying... extendedly :family: ), however I think this may be a Windows 7 issue.  Even though I believe I have all needed frameworks installed, I will test this tomorrow and try to find a fix.

**Comment by apprehensivemom** [comment]
Now something has changed. This is very strange:
Windows 10 Pro(64bit)             32GB RAM GTX960 intel 6700K ----> v 1.2.2.0 works ok
Windows 7 ultimate(64bit)        16GB RAM  GTX760 intel 4770K ----->v 1.2.2.0 works ok
Windows 7 ultimate(64bit)        16GB RAM  GTX760 intel 3770K ----->v 1.2.2.0 / v 1.2.2.1 don't start

## Here are the logs:

THIS ONE WORKS:
[2016-01-05 09:48:39] [INFO] [NICEHASH] Starting up
[2016-01-05 09:48:39] [INFO] [NICEHASH] Total RAM: 16322MB
[2016-01-05 09:48:39] [INFO] [NICEHASH] Page File Size: 2046MB
[2016-01-05 09:48:39] [INFO] [NVIDIA5.x] Detected: GPU #0: SM 3.0 GeForce GTX 760
[2016-01-05 09:48:40] [INFO] [NVIDIA3.x] Detected: GPU #0: SM 3.0 ASUS GTX 760
[2016-01-05 09:48:40] [INFO] [NVIDIA3.x] Added: ASUS GTX 760
[2016-01-05 09:48:41] [INFO] [NVIDIA2.1] Detected: GPU #0: SM 3.0 ASUS GTX 760
[2016-01-05 09:48:41] [INFO] [AMD_OpenCL] Platform Devices: 1
[2016-01-05 09:48:41] [INFO] [AMD_OpenCL] One of the GPUs detected is not Tahiti, Hawaii or Pitcaird. Optimized version is disabled!
[2016-01-05 09:48:41] [INFO] [AMD_OpenCL] GPU Name (Driver Ver): NVIDIA GeForce GTX 760 (10.18.13.6143)
[2016-01-05 09:48:41] [INFO] [AMD_OpenCL] One of the GPUs detected is not Tahiti (GeForce GTX 760). Changing default gpu-threads to 2
[2016-01-05 09:48:41] [INFO] [NICEHASH] Version get
[2016-01-05 09:48:42] [INFO] [NICEHASH] SMA get
[2016-01-05 09:48:42] [INFO] [COINBASE] Bitcoin rate get
[2016-01-05 09:48:42] [INFO] [COINBASE] Current Bitcoin rate: 433.47
[2016-01-05 09:48:42] [INFO] [NICEHASH] Balance get

## [2016-01-05 09:48:43] [INFO] [NICEHASH] Setting environment variables

THIS ONE DOES NOT:
[2016-01-05 10:15:01] [INFO] [NICEHASH] Starting up
[2016-01-05 10:15:01] [INFO] [NICEHASH] Total RAM: 16327MB
[2016-01-05 10:15:01] [INFO] [NICEHASH] Page File Size: 2046MB
[2016-01-05 10:15:03] [INFO] [NVIDIA5.x] Detected: GPU #0: SM 3.0 GeForce GTX 760
[2016-01-05 10:15:04] [INFO] [NVIDIA3.x] Detected: GPU #0: SM 3.0 ASUS GTX 760
[2016-01-05 10:15:04] [INFO] [NVIDIA3.x] Added: ASUS GTX 760
[2016-01-05 10:15:05] [INFO] [NVIDIA2.1] Detected: GPU #0: SM 3.0 ASUS GTX 760

## [2016-01-05 10:15:07] [INFO] [AMD_OpenCL] GPU Name (Driver Ver): NVIDIA GeForce GTX 760 (10.18.13.6143)

I hope this helps

**Comment by theLosers106** [comment]
Can anyone try this build. Just replace NiceHashMiner.exe in your existing folder NiceHashMiner_1.2.2.0 with exe from the link. (link removed)

**Comment by theLosers106** [comment]
@apprehensivemom thanks a lot. helped me narrow down the problem. hopefully with the new exe I just posted it will fix the problem.

**Comment by forumaster** [comment]
This isn't solve the problem for me...
![screenshot_12](https://cloud.githubusercontent.com/assets/16463429/12116383/c00b2196-b3b9-11e5-984b-9c34588ea3d1.png)
but now it's not Form3 it's Microsoft .NET Framework, here is the log:

Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

*************\* Testo dell'eccezione **************
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in NiceHashMiner.sgminer.QueryCDevs()
   in NiceHashMiner.sgminer..ctor()
   in NiceHashMiner.Form1.StartupTimer_Tick(Object sender, EventArgs e)
   in System.Windows.Forms.Timer.OnTick(EventArgs e)
   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Assembly caricati **************
mscorlib
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

NiceHashMiner
    Versione assembly: 1.2.2.2
    Versione Win32: 1.2.2.2

##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/NiceHashMiner.exe

System.Windows.Forms
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5491 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5492 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5483 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll

Newtonsoft.Json
    Versione assembly: 7.0.0.0
    Versione Win32: 7.0.1.18622

##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/Newtonsoft.Json.DLL

mscorlib.resources
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

log4net
    Versione assembly: 1.2.15.0
    Versione Win32: 1.2.15.0

##     Base di codice: file:///C:/Users/Acer/Desktop/NiceHashMiner_v1.2.2.0/log4net.DLL

System.Configuration
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5483 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5485 (Win7SP1GDR.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Windows.Forms.resources
    Versione assembly: 2.0.0.0
    Versione Win32: 2.0.50727.5420 (Win7SP1.050727-5400)

##     Base di codice: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Debug JIT **************
Per attivare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
attivato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è attivato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by theLosers106** [comment]
@albysprx could you post the log instead? the debug message isn't helping =/

**Comment by tonyrayo** [comment]
@theLosers106 Thanks for posting an updated build; there is a clear change in the approach the application is using as evident by what the log is showing now compared to what it was before, however the exception is still being thrown.  Here is my log (if it helps, I'm running Windows 7 Pro x64 SP1, with a 3770S CPU and a EVGA nVidia 660 Ti gfx card).

https://gist.github.com/tonyrayo/404424f9e5f985b05a7a

I am typing this from my phone, however when I am home I will continue to look through the code and try to compile a working exe (it kind of helps if you are able to recreate the problem directly :cake: ).

**Comment by forumaster** [comment]
[2016-01-05 18:48:47] [INFO] [NICEHASH] Starting up
[2016-01-05 18:48:47] [INFO] [NICEHASH] Total RAM: 3947MB
[2016-01-05 18:48:47] [INFO] [NICEHASH] Page File Size: 3946MB
[2016-01-05 18:48:50] [INFO] [NVIDIA5.x] Detected: GPU #0: SM 2.1 GeForce GT 540M
[2016-01-05 18:48:51] [INFO] [NVIDIA3.x] Detected: GPU #0: SM 2.1 GeForce GT 540M
[2016-01-05 18:48:53] [INFO] [NVIDIA2.1] Detected: GPU #0: SM 2.1 GeForce GT 540M
[2016-01-05 18:48:53] [INFO] [NVIDIA2.1] Added: GeForce GT 540M
[2016-01-05 18:48:55] [INFO] [DEBUG] [18:48:55] CL Platform vendor: Intel(R) Corporation
[2016-01-05 18:48:55] [INFO] [DEBUG] [18:48:55] CL Platform name: Intel(R) OpenCL
[2016-01-05 18:48:55] [INFO] [DEBUG] [18:48:55] CL Platform version: OpenCL 1.1 
[2016-01-05 18:48:55] [INFO] [DEBUG] [18:48:55] Error -1: Getting Device IDs (num)
[2016-01-05 18:48:55] [INFO] [DEBUG] [18:48:55] clDevicesNum returned error, no GPUs usable
[2016-01-05 18:48:55] [INFO] [DEBUG] [18:48:55] 0 GPU devices max detected
[2016-01-05 18:48:55] [INFO] [AMD_OpenCL] GPU Name (Driver Ver): NVIDIA GeForce GT 540M            (10.18.13.6143)
[2016-01-05 18:48:55] [INFO] [AMD_OpenCL] GPU Name (Driver Ver): Intel(R) HD Graphics 3000 (9.17.10.4229)

**Comment by theLosers106** [comment]
@albysprx @tonyrayo @apprehensivemom this build should hopefully help you guys (link removed) .. please report back your findings so I could release an update to the code as I can't reproduce the error.. thanks (:

**Comment by forumaster** [comment]
@theLosers106 problems solved! thanks

**Comment by apprehensivemom** [comment]
Problem solved with the new exe thanks.

The only issue I had is this:
in the beginning I had to disable avast in order to stop it from deleting the exe

then avast somehow accepted it, but the exe crashed in the very beginning
(NiceHasMiner has stopped working) during the avast 15 seconds test run.
Luckily, the normal run that follows the test phase had no problems

Now after some runs, avast somehow trusts this program and
doesn't switch to the 15 seconds test phase anymore,
therefore program runs normally.

My opinion is that in the test run avast doesn't give access to some resources and the
program uses them without checking for their availability

**Comment by tonyrayo** [comment]
@theLosers106 Perfection! I think this will allow NiceHash Miner to have zero open issues on GitHub (still waiting to hear back from that last person but I think you've done it).  As I'm _finally_ getting around to learning C# (I dismissed it when it was introduced as a "Microsoft controlled" language - which I guess it technically still is but even before Linux and Mac received official support in April of last year, there were some great 3rd party .NET libraries, i.e. Mono) I'll be looking forward to comparing the initialization code on the next git pull. :+1:

**Comment by kenshirothefist** [comment]
Resolved in v1.2.2.2.
