### ISSUE TITLE
ethminer thinks it's not running

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#140]
ethminer starts, seems to begin running fine, after a moment, a second ethminer window opens, starts loading, the first window closes, the second progresses and gets to beginning to run fine, and the cycle repeats.  

version 1.6.0.1, installed yesterday. 
Not sure what to try next. 

Turned on debug console, and it shows a more complicated version of the same: 

[2:08:11 PM] [AMD_OpenCL] ethminer is not running.. restarting..
[2:08:11 PM] [AMD_OpenCL] Shutting down miner
[2:08:11 PM] [AMD_OpenCL] Starting miner (bin\ethminer.exe):  --opencl --opencl-
platform 0   -S daggerhashimoto.usa.nicehash.com:3353 -O 16HqUTTyDToEP4yN4gf8Afs
51et35adqPD.worker1:x --api-port 34562 --opencl-devices 0 1  --dag-load-mode sin
glekeep 0
[2:08:11 PM] [NICEHASH] Balance get
[2:08:31 PM] [AMD_OpenCL] ethminer is not running.. restarting..
[2:08:31 PM] [AMD_OpenCL] Shutting down miner
[2:08:31 PM] [AMD_OpenCL] Starting miner (bin\ethminer.exe):  --opencl --opencl-
platform 0   -S daggerhashimoto.usa.nicehash.com:3353 -O 16HqUTTyDToEP4yN4gf8Afs
51et35adqPD.worker1:x --api-port 34562 --opencl-devices 0 1  --dag-load-mode sin
glekeep 0
[2:09:04 PM] [AMD_OpenCL] ethminer is not running.. restarting..
[2:09:04 PM] [AMD_OpenCL] Shutting down miner
[2:09:04 PM] [AMD_OpenCL] Starting miner (bin\ethminer.exe):  --opencl --opencl-
platform 0   -S daggerhashimoto.usa.nicehash.com:3353 -O 16HqUTTyDToEP4yN4gf8Afs
51et35adqPD.worker1:x --api-port 34562 --opencl-devices 0 1  --dag-load-mode sin
glekeep 0

**Comment by foxwarernd** [comment]
Maybe it is hanging one copy ethminer, and the second does not start? View in taskmanager , or simply reboot . And in extreme cases, check availability ethminer.exe files in the bin folder (or siphon all 1.6.0.1 in a new folder )

**Comment by theLosers106** [comment]
What GPU are you using? If nVidia, then I would suggest to try this beta version (https://drive.google.com/open?id=0B6kB9L8GNvQwMlIxZU9LTjNzbGs).. if not, then try to increase the MinerAPIGraceSeconds to like 60 or 120 or higher (personally I would go up to like 120 only)..

**Comment by ghost** [comment]
Using 7970 gpus. changed as suggested to 120s grace. No improvement

**Comment by theLosers106** [comment]
Hurmm.. I can't replicate the problem.. What CPU are you using?

**Comment by ghost** [comment]
AMD FX9370 8 core, 20g ram, win7-64 ult.
Started up this morning and it ran with no issue for about 30 min, then i
decided to upgrade nicehash miner, and now i'm waiting for the benchmarks.

On Sun, Jun 26, 2016 at 12:17 PM, theLosers106 notifications@github.com
wrote:

> Hurmm.. I can't replicate the problem.. What CPU are you using?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nicehash/NiceHashMiner/issues/140#issuecomment-228611718,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASvWuCfzccNgQHUrybzDTveik1Xk4RSeks5qPrQWgaJpZM4I-C1Z
> .

## 

_KG5JVF_
Byron Morgan
Ecru, Mississippi, EM54li
https://www.qrz.com/db/KG5JVF
100WaW #935
NAQCC #8330
Flying Pigs #3741
DMC#08297

**Comment by nicehashdev** [comment]
I believe this bug has been fixed.
