### ISSUE TITLE
Why am I seeing a tiny monitor icon next to one of my graphics cards?

### ISSUE THREAD

**Issue by Sawtaytoes** [nicehash/NiceHashMiner-Archived#1404]
My third GPU is showing a tiny monitor icon next to the card, and it's performing at less than a fourth of the hash rate of the other two cards. What's causing this icon to show up and how might I fix it?

**Comment by Sawtaytoes** [comment]
A UEFI update corrected the issue; although, I'd still like to know the reason that icon shows up.

**Comment by ghost** [comment]
You see that icon cause you're giving your monitor connection on that GPU thatzat mate. İt's not a prob :)

**Comment by Sawtaytoes** [comment]
I was remoted in at the time and no monitor was connected, so that's strange. Thanks for your help!
