### ISSUE TITLE
NHM stops working after short period! 2 weird o_O

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#1417]
Hey there. I got 8x you rig working perfectly. Zero problem. When I add 9. GPU, it stops working after real short period. ( I'm using another 750 watt Corsair psu for that GPU btw) last night I've tried that also another 3 new GPU and with 11 GPU I got same problem there. NHM reinstalled, all benchmark done  from zero and nope.. it sometimes working for 10 mins, sometimes 10 seconds. Then cmd screen disappears and showing up again and rig starts working from zero.. dunno what to do... I'm goin with 8 GPU ATM cause can't use more GPU on it.. specs here : 1x 970, 7x 1060 6gb. This works perfectly anyways. When I try add even 1 GPU (1060 6gb) doomsday start showing up.. any pro here about that case??

**Comment by russalex83** [comment]
Hi there! I had exactly the same problem. NH Miner CANNOT handle 10 GPUs simultaneously (at least in my experience, maybe it works for someone), No matter what I did, under clocking, adding more PSUs, reinstalling stuff, ect - wasted hours. But STUPID NH Excavator kept restarting, dropping my profits. I just gave up on them... I solved it here: https://github.com/nicehash/NiceHashMiner/issues/1407,  with help from tomcleaver user, been running for a few hours and no issues so far:
https://github.com/nicehash/NiceHashMiner/issues/1407

**Comment by ghost** [comment]
Anything that I can do about it? I think I need help tho :/

**Comment by russalex83** [comment]
Just follow this link: https://github.com/nicehash/NiceHashMiner/issues/1407

**Comment by ghost** [comment]
Okay mate I'll give try thx a lot..

**Comment by russalex83** [comment]
No problem
