### ISSUE TITLE
Ethminer submitting stales and crashing

### ISSUE THREAD

**Issue by uvxcoin** [nicehash/NiceHashMiner-Archived#142]
Last good working version was and is 1.5.1.0
Latest version starts up, Ethminer runs a minute or so and then submits a bunch of stales and crashes. It does not restart. it is left in memory.
Also ver 1.6.0.0 and 1.6.0.1 crash on Dagger benchmarking. Says 2-4 mins. I waited 2 hours. Nada.
4X R9 270x
Win 7 X64
Catalyst driver 15.7.1

V1.5.1.0 works fantastic and I average 50 MH/s.

**Comment by theLosers106** [comment]
Could you post the log file when the crash happened? Thanks

**Comment by nicehashdev** [comment]
Same issue here: https://github.com/nicehash/NiceHashMiner/issues/165
