### ISSUE TITLE
GTX 960 DaggerHashimoto Bench Disabled

### ISSUE THREAD

**Issue by HeckuvaTester** [nicehash/NiceHashMiner-Archived#143]
When benchmarking my GTX 960, every option under NVIDIA5.x is checked and benchmarks fine, but when it reaches DaggerHashimoto, it skips it and put "Disabled" in the speed column. Why does it skip DaggerHashimoto?

**Comment by nicehashdev** [comment]
This is a known bug in 1.6.0.1 and will be fixed with next release.
