### ISSUE TITLE
1.6.0.1 - Nvidia GPU not present in list

### ISSUE THREAD

**Issue by vvzar** [nicehash/NiceHashMiner-Archived#144]
IT was present, but then disappeared. How can I check what vga card components are need to be present so nicehashminer able to detect GPU? 
CUDA  - installed, physx - installed, driver version installed - 341.95. (In GPU-Z: CUDA checked, Physx - unchecked)

**Comment by theLosers106** [comment]
You driver might have crashed and that is why it is not seen by NiceHashMiner.. You could try to run any of the ccminer with --ndevs and see what the output says

**Comment by vvzar** [comment]
it says:  Unable to query number of CUDA devices! Is an nVidia driver installed?

**Comment by theLosers106** [comment]
That means the driver has crashed and usually you would need to restart the computer.. If you overclock your GPU, then you should dial down the OC..

**Comment by vvzar** [comment]
thanks, I have restarted my PC many times but it does not help, it not overclocked. May be an older driver would help?

**Comment by foxwarernd** [comment]
1 ) Write some video cards are connected
2 ) What is the established OS , which bit OS
3 ) 341.95 is not the latest driver nvidia - try to put the latest Nvidia's site

**Comment by Amorf** [comment]
Same problem on GTX 570 (GF110), OS Windows 7 x64, latest driver installed and no overclock GPU....

**Comment by theLosers106** [comment]
@Amorf I am affraid that your GPU is not supported as it is Compute 2.0. You need at least Compute 2.1 to mine using ccminer.

**Comment by Lbniese** [comment]
You can use this link to check whether your GPU is supported or not.

http://cryptomining-blog.com/4950-what-version-of-ccminer-to-use-with-your-nvidia-gpu/
