### ISSUE TITLE
Missing Miner Files

### ISSUE THREAD

**Issue by leogloballife** [nicehash/NiceHashMiner-Archived#1465]
Hi, Im installing nice hash 2 for the first time. Im getting Missing miner files, excavator_server_91.. I disabled windows defender and firewall also. im using windows 10 build 1709(anniversary edition).. No bin folder in Roaming folder. So i created bin and excavator_server folder and inserted excavator in it. I tried my level best, but still no luck. Could anyone help me please..  im struggling with this issue from last 3 days..

**Comment by duub** [comment]
same problem windows 10 and nvidia drivers 390.77

**Comment by duub** [comment]
try installing a vpn as commented here: https://github.com/nicehash/NiceHashMiner/issues/1460#issuecomment-362128167

**Comment by leogloballife** [comment]
Yes my issue get resolved after installing VPN.. Thanks a lot :)
