### ISSUE TITLE
1.6.1.0 no daggerhashimoto for gtx1080

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#148]
![aa](https://cloud.githubusercontent.com/assets/16473762/16514300/42853e26-3f6b-11e6-9ba7-d2b953305247.jpg)
THIS IS A GTX960 (everything works)

![cc](https://cloud.githubusercontent.com/assets/16473762/16514590/0959db28-3f6d-11e6-988d-d6e19b56ecb6.jpg)
THIS IS A GTX1080 (only daggerhashimoto doesn't work)

**Comment by theLosers106** [comment]
Sorry but ethminer does not work for nVidia 10 series GPUs on Windows. That is why NiceHashMiner disabled that algorithm. I'll be closing this issue and when it works we'll be releasing a new NiceHashMiner.
