### ISSUE TITLE
1.6.1.0 Same issues. Stales and crashes - Log attached

### ISSUE THREAD

**Issue by uvxcoin** [nicehash/NiceHashMiner-Archived#149]
Last good working version was and is 1.5.1.0
Latest version starts up, Ethminer runs a minute or so and then submits a bunch of stales and crashes. It does not restart. it is left in memory.
4X R9 270x
Win 7 X64
Catalyst driver 15.7.1

Log attached (I removed my BTC address)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/344119/log.txt)

**Comment by nicehashdev** [comment]
Same issue: https://github.com/nicehash/NiceHashMiner/issues/165
