### ISSUE TITLE
GPU'S NOT DETECTED BY NICEHASH

### ISSUE THREAD

**Issue by Umair-khalidkhan** [nicehash/NiceHashMiner-Archived#1520]
Hi!
I URGENTLY REQUEST HELP AND I AM STUCK FOR SO MANY HOURS. Ok so I got to know about the latest compute mode of and gpus. So to bring that and told me to update bios and amd drivers first I updated the bios and then check (at this time the gpus were fine on nicehash) then I updated to the latest block chain crimson beta drivers(which I first already had downloaded and were running fine, ran DDU to delete them). Then when I opened nicehash it did NOT detect any gpu( 3 RX 570s) only the cpu. Now I have literally done everything in my power. I used DDU and 're installed drivers multiple times, completed uninstalled the device and tried from scratch. Deleted NICEHASH several times and tried again but nothing. Downloaded the latest .5 version of legacy still no use.

Please help. I will remember you for like if you do so.

**Comment by killdog99x** [comment]
try running DDU and removing drivers and shutting down, then change the order witch the cards are connected to the motherbord. (e.g. move card 1 to pcie 2, move card 2 to pcie 1, etc...) then reinstall all the stuff sometimes that works.

**Comment by Umair-khalidkhan** [comment]
I'll try but I am very sceptical as when already I change my slots I get no display. Even when it was working fine.

**Comment by Umair-khalidkhan** [comment]
Hey I just did a recovery of the windows and 're installed it and the drivers and this time it worked.
