### ISSUE TITLE
No p0 state for 2.13

### ISSUE THREAD

**Issue by Kyetchup** [nicehash/NiceHashMiner-Archived#1522]
I want to force p0 state for my mining... 

I am using Nvidia Profile Inspector 2.13

I am trying to find a version where the option still exists, it's been some hour already.

Hopefully, I can find answers here. Thanks in advance!

**Comment by foxwarernd** [comment]
http://www.softpedia.com/get/System/System-Info/NVIDIA-Inspector.shtml

**Comment by Kyetchup** [comment]
Hey, anyone here?
