### ISSUE TITLE
NiceHash Miner Bug Not Detecting Nvidia GTX 550 ti

### ISSUE THREAD

**Issue by maxlopez123** [nicehash/NiceHashMiner-Archived#156]
Windows 7 ultimate 64 bit
Core i3 - 2100 cpu @ 3.10ghz
Ram 6gb
Hdd: 500gb
Gpu model: Nvidia GeForce gtx 550 ti
Driver version: 332.21

Everything is install right I'm not sure why it's not detecting the gpu only detecting the cpu cores, before i reformated my pc is working fine.

**Comment by Lbniese** [comment]
Sure your GPU is supported?

http://cryptomining-blog.com/4950-what-version-of-ccminer-to-use-with-your-nvidia-gpu/

**Comment by maxlopez123** [comment]
Hey thanks for your reply yes its in the list my gpu is suppoted its under nvidia2.1, infact previously its working just fine then recently i reformated my pc and the new updates of nicehash miner comes along and it just does`t seem to detect anymore. I have the latest version for my graphic driver but still for some reason its not detecting it. Any idea or help is much appericated. Thanks.

**Comment by maxlopez123** [comment]
![spec](https://cloud.githubusercontent.com/assets/20420316/17049321/3760fa8e-501f-11e6-85c1-aa77cc9e5bc6.png)

**Comment by Lbniese** [comment]
Do you have the latest version of the Cuda Driver installed?

https://developer.nvidia.com/cuda-downloads

**Comment by maxlopez123** [comment]
Omg thanks my friend it did not release that cuda driver was not install i only install the normal driver. You have solve my issue for that im really greaful to you. Was having a hard time figuring it out for couple of weeks. lol. Thanks man.

**Comment by maxlopez123** [comment]
I will close this issue now.

**Comment by jaggedsoft** [comment]
For me the solution was to disable SLI mode from the NVIDIA Control Panel.
I have 2x GeForce 670
