### ISSUE TITLE
[Feature] add cpuminer-opt and all supported algos to the CPU mining list

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#159]
it would be awesome if you could package cpuminer-opt (https://bitcointalk.org/index.php?topic=1326803.0) with the NHM and allow the CPU to mine any algo supported by nicehash in general (not just some 3 or 4).

cheers

**Comment by nicehashdev** [comment]
Hello. This is something we will not do. Some algorithms are a waste to mine with CPU and in most cases only botnet owners use them.

However, we will continue to add promising CPU minable algorithms to NHM with future versions.
