### ISSUE TITLE
NiceHashMiner.exe got "no responding" every few seconds when there's no direct internet connection

### ISSUE THREAD

**Issue by kuntan2237** [nicehash/NiceHashMiner-Archived#161]
Hi,

I'm using a proxy connecting to internet on the mining system, the mining software (like cpuminer_x64_SE2.exe) works fine with proxy (with "--proxy" option).
However, I didn't find any proxy options for NiceHashMiner.exe itself, and it will get "no responding" every few seconds.

Is there any fix/workaround for this?

Thanks.

**Comment by kuntan2237** [comment]
There's a workaround that use Proxifier to force NiceHashMiner.exe use proxy.

**Comment by nicehashdev** [comment]
We will add support for proxy in one of the future versions.

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.
