### ISSUE TITLE
[FEATURE] Mining When Idle Ignores Gaming with Controller

### ISSUE THREAD

**Issue by HeckuvaTester** [nicehash/NiceHashMiner-Archived#163]
I occasionally game with a controller on my PC. When I set it to mine while idle, it seems that it interprets no mouse movement while playing with a controller as 'idle.' This means that if I want to use my controller, I can't set it to mine while idle, but i rather have to tell it to start each time.

**Comment by nicehashdev** [comment]
We will take a look into this issue and try to find possible solution in one of following versions.

**Comment by jmv1** [comment]
This would actually be very useful. Maybe even add an option to mine always unless controller input (not keyboard or mouse) is detected. So when I'm gaming with controller it would stop mining and keep on mining with normal desktop usage.

**Comment by S74nk0** [comment]
Closing issue. Opened a new issue related to **Mining when Idle Feature update** that coveres this issue as well. Post all new suggestions or related problems to the new opened issue here #398
