### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#164]
Everytime that I try to start NiceHash Miner it's showed: 
![untitled](https://cloud.githubusercontent.com/assets/20497699/16898797/d8117d14-4bbf-11e6-9bf8-3d5f824b39c9.png)

My internet it's just fine, already did this steps: https://github.com/nicehash/NiceHashMiner/issues/59#issuecomment-201658134 and sent an e-mail. What can I do to solve this?

**Comment by kenshirothefist** [comment]
Can you post what are your ping results to each location? Check here: https://www.nicehash.com/index.jsp?p=faq#faqs13

**Comment by ghost** [comment]
EU Server: 

> Pinging speedtest.ams01.softlayer.com [159.253.132.18] with 128 bytes of data:
> Reply from 159.253.132.18: bytes=128 time=247ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=247ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=248ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=248ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=253ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=248ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=249ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=249ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=248ms TTL=46
> Reply from 159.253.132.18: bytes=128 time=252ms TTL=46
> Ping statistics for 159.253.132.18:
> Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
> Approximate round trip times in milli-seconds:
> Minimum = 247ms, Maximum = 253ms, Average = 248ms

USA server:

> Pinging speedtest.sjc01.softlayer.com [50.23.64.58] with 128 bytes of data:
> Reply from 50.23.64.58: bytes=128 time=256ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=256ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=255ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=256ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=255ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=256ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=256ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=462ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=256ms TTL=49
> Reply from 50.23.64.58: bytes=128 time=256ms TTL=49
> Ping statistics for 50.23.64.58:
> Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
> Approximate round trip times in milli-seconds:
> Minimum = 255ms, Maximum = 462ms, Average = 276ms`

HK Server:

> Pinging speedtest.hkg02.softlayer.com [119.81.130.170] with 128 bytes of data:
> Reply from 119.81.130.170: bytes=128 time=403ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=402ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=402ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=403ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=402ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=404ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=403ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=402ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=402ms TTL=48
> Reply from 119.81.130.170: bytes=128 time=403ms TTL=48
> Ping statistics for 119.81.130.170:
> Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
> Approximate round trip times in milli-seconds:
> Minimum = 402ms, Maximum = 404ms, Average = 402ms

JP Server:

> Pinging speedtest.tok02.softlayer.com [161.202.125.20] with 128 bytes of data:
> Reply from 161.202.125.20: bytes=128 time=358ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=357ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=349ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=350ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=350ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=351ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=350ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=349ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=360ms TTL=48
> Reply from 161.202.125.20: bytes=128 time=350ms TTL=48
> Ping statistics for 161.202.125.20:
> Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
> Approximate round trip times in milli-seconds:
> Minimum = 349ms, Maximum = 360ms, Average = 352ms

I don't think that is the server, just the NiceHash Miner don't connect on the internet. I try to use the minerD to connect with NiceHash server and it's fine. Just the NiceHash Miner program don't connect. I want to use this software. =('

**Comment by nicehashdev** [comment]
Can you visit website www.nicehash.com normally? What about if you open this in your browser: https://www.nicehash.com/api?method=simplemultialgo.info ?

**Comment by jonesskill01** [comment]
same problem here , it seems that I and BahiaAlves are from Brazil and we could not use the NiceHasminer

**Comment by jonesskill01** [comment]
#nicehashdev, 
yes I can open this page shows where the algorithms and prices

**Comment by felixbrucker** [comment]
i have the same issue on one of my rigs currently (usually fine), log says something about ssl/tls (german):
"[NICEHASH] Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine Vertrauensstellung hergestellt werden.."

google translate: "The underlying connection was closed : for the SSL / TLS secure channel trust relationship could not be established"

**Comment by felixbrucker** [comment]
i solved my problem by syncing the clock (was out of sync)

**Comment by enahmad** [comment]
I'm having the same issue too, nicehash did not detect my internet connection. Any way to solve this issue?

**Comment by nicehashdev** [comment]
If you still have this issue, you may have to contact Cloudflare and ask if they have blacklisted your IP.

**Comment by enahmad** [comment]
It seems working ok now.

Thank you.

**Comment by NogaAllTK** [comment]
I have the same problem you did nothing seems to help.

**Comment by NaitorStudios** [comment]
Here's how to fix it:
I've found out that NiceHash Miner (and some other programs) can't detect internet connection when IPv4 and IPv6 are enabled at the same time.
Disable one of them and the problem should go away. I think IPv6 is better, so I let it enabled and disabled IPv4, but I don't know if there's any drawbacks.

To disable just right click the network tray icon, then click Open Network and Sharing Center.
In the window that show up, look for "Connections: " right below HomeGroup, then click whats on the right side (should be your network name).
New window, Properties, you will see a list, check or uncheck IPv6 or IPv4, you must let at least one checked.

For the developers:
NiceHash Miner can't determine with IP version to use when both are enabled, hope in a future update it get fixed so we can use both at same time and people won't freak out with this issue.

**Comment by Igloczek** [comment]
@nicehashdev could you make this just a warning instead of alert with required action? IMO miner should try to restart mining automatically after failure, instead of waiting for user action, b/c at all "no" will probably close miner, so choosing "yes" is the only reasonable option.

**Comment by aqarooni02** [comment]
@nicehashdev i cant connnect to the website
