### ISSUE TITLE
1.6.1.2 Same issues / 1 Issue resolved

### ISSUE THREAD

**Issue by uvxcoin** [nicehash/NiceHashMiner-Archived#165]
First off the one issue resolved was in the previous version when Ethminer crashed Sgminer relaunched.
Now when Ethminer crashes, Ethminer relaunches...and crashes...and relaunches...and crashes...etc

As with ALL versions after 1.5.1 Ethminer is submitting stales and crashing.

Keep trying... You will get it eventually

4X R9 270x
Win 7 X64
Catalyst driver 15.7.1

**Comment by uvxdev** [comment]
I am happy to announce I am now mining with latest version. I upgraded my crimson drivers to 16.3.2 and all is well. I suggest editing your help files to reflect the new miner is working great with 16.3.2 with no speed loss at all.
Thanks Dev you can close this issue.

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.
