### ISSUE TITLE
question:  USD or $ ??

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#166]
Why when I select USD in the main window appears the symbol $
and when I select EUR doesn't appear the € euro symbol but EUR ?
and when I select GBP doesn't appear the £ pound symbol but GBP ?
and when I select JPY doesnt appear the ¥ yen symbol but JPY?
...and so on...
the 3 letters is more precise (both USD and canada CAD have $)
but of course $ is quick and universal.. 
should the choice to be left to the user? symbols or 3 letters?

**Comment by nicehashdev** [comment]
We will fix to USD in future version.
