### ISSUE TITLE
Nvidia 3 and 5 mutation

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#167]
![nicehash1](https://cloud.githubusercontent.com/assets/19608698/17082790/81865856-5192-11e6-8dcd-215ba5e8c805.jpg)
![nicehash2](https://cloud.githubusercontent.com/assets/19608698/17082789/8184a830-5192-11e6-9605-1a2947e32185.jpg)

When I mine with them simultaneously,  ether gets mined at same speed of n3 for both n3 and n5. My n5 speed should be 22 and instead it is registering as 9 (speed of n3). Why is that?

**Comment by nicehashdev** [comment]
With future version, there will be only one ethminer for all NVIDIA cards.

**Comment by S74nk0** [comment]
This is now fixed with the current [NiceHashMiner v1.7.0.3-BETA](https://github.com/nicehash/NiceHashMiner/releases/tag/v1.7.0.3-BETA) and new upcoming releases. I will close this issue.
