### ISSUE TITLE
A lots of things broken on a fresh install

### ISSUE THREAD

**Issue by Singman33** [nicehash/NiceHashMiner-Archived#169]
I'm using NicehashMiner since start, and upgraded up to 1.6.1.2, but I've modified a lot your miners binary by replacing with mine. Today, I tried a fresh install and I was very surprised to see that nearly everything is broken. I got error on many algorithms, even the basic ones (X, Quark, Neoscrypt). I should even stop the benchmark because Lyra2v2 hang.  What have you done to this program ? You are getting it worse everydays !

Log file attached.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/380963/log.txt)

**Comment by nicehashdev** [comment]
Looks like you are getting CUDA errors:

Benchmark Exception: CUDA error

Do you have proper NVIDIA drivers installed?

**Comment by Singman33** [comment]
You are right ! I was using dev drivers with CUDA 8 disabled (the toolikt will be out only on August) to compile some miners and forgot to switch them back. Look like benchmark is back to normal, with others problems (I will open a new issue).
