### ISSUE TITLE
No install - no .exe?

### ISSUE THREAD

**Issue by justsomeguyinfl** [nicehash/NiceHashMiner-Archived#17]
Download binaries from here: https://github.com/nicehash/NiceHashMiner/releases
Extract zip archive
Run NiceHashMiner.exe

NiceHashMiner.exe doesn't exist
there is a publish.bat file the appears to copy it...

@echo off
IF [%1]==[] goto exit_param
IF [%2]==[] goto exit_param
IF [%3]==[] goto exit_param
set PATH=%PATH%;C:\Program Files (x86)\Windows Kits\8.1\bin\x86
mkdir NiceHashMiner_v%1
cd NiceHashMiner_v%1
copy ..\NiceHashMiner.exe NiceHashMiner.exe
SignTool sign /f %2 /p %3 /t 

When run:
>publish.bat
Usage: [version] [cert_location] [cert_pw]

??

**Comment by tonyrayo** [comment]
Looks like a script someone would run to get the program ready to publish.  If you download now, all relevant files are there.

**Comment by justsomeguyinfl** [comment]
Again...

When run:

> publish.bat
> Usage: [version] [cert_location] [cert_pw]

it doesn't do anything except state:

Usage: [version] [cert_location] [cert_pw]

What arguments are required to get this to run and complete? Doesn't say anything in the readme except to run nicehash.exe - which, again, does not exist

**Comment by kenshirothefist** [comment]
You do **not** need run publish.bat, this is internal tool to sign the .exe binaries. All you have to do is run NiceHashMiner.exe. Please re-download it, extract the zip file and you'll find NiceHashMiner.exe in the extracted folder.

**Comment by tonyrayo** [comment]
Oh, I see the problem. You need to download builds from the release page - https://github.com/nicehash/NiceHashMiner/releases - otherwise you are downloading the source code.

**Comment by justsomeguyinfl** [comment]
Gotcha, followed the link from the NiceHash pool website. Thanks!
