### ISSUE TITLE
GTX 960 with X13 and Neoscrypt

### ISSUE THREAD

**Issue by Singman33** [nicehash/NiceHashMiner-Archived#170]
Fresh install of 1.6.1.2 and brand new drivers from NVidia 368.81.
When benchmarking, I got errors for x13 and neoscrypt algorithms (not enough memory from CUDA).
- You are using sp-hash ccminer I think for x13 (https://github.com/sp-hash/ccminer), it work perfectly on a GTX 750 Ti, but I need to add "--intensity=20" parameter to make it working on GTX 960. Do you have the lastest version ?
- I can't determine what kind of ccminer you are using for Neoscrypt, but again it need a "--intensity=15" to work on my card. SP-hash dont need that parameter but my version gave me inferior hashrates than your (crippled ?) version. Can you tell me what kind of miner you are using for Neoscrypt ?

**Comment by nicehashdev** [comment]
We will run some tests and see if we have the same issue with this card.

Meanwhile, it seems to me as if something is using a lot of memory on your card. Check with GPU-Z to see current memory usage. It should not be more than 500 MB in idle state (that is what WDDM takes up).

Also, what is your OS? Windows 10 maybe?

**Comment by Singman33** [comment]
OS is Windows 10, and I have 200 Mb used.

**Comment by nicehashdev** [comment]
Will try to test on Windows 10 and see what happens...

**Comment by S74nk0** [comment]
Hi @Singman33. Does this problem persist on newer NVIDIA drivers? We have tested GTX 960 and GTX 750 Ti under Windows 10 and could not reproduce the problem.
