### ISSUE TITLE
multiple GTX 1070 - unspecified launch failure after some time

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#171]
mining lyra2rev2 with multiple GTX 1070 (tested with 3 and 2) works for some time (5 minute-ish) and then fails with "unspecified launch failure" and displays very high hashrate

see screen for reference
![gtx-1070-unspecified-launch-failure](https://cloud.githubusercontent.com/assets/5189997/17120593/908fe18c-52cd-11e6-8dff-3c3a9222f3b0.PNG)

with only 1 GTX 1070 mining seemed to work fine overnight

**Comment by felixbrucker** [comment]
_not removing this issue for future google searches, might be useful_

The issue is not NHM related, but to the ordering of the PCIe connectors on the Mainboard (in my case a MSI Z170-A PRO).
I had to connect the two of my currently 3 cards to all 2 full width x16 connectors (via x1-x16 risers) and it worked like a charm even with multiple GPU.

**Comment by felixbrucker** [comment]
Sadly that did not work, i was just lucky it ran some time longer

Issue still persists

**Comment by nicehashdev** [comment]
This is ccminer specific issue. You may search ccminer bitcointalk threads, see if anyone came up with a solution.

**Comment by felixbrucker** [comment]
searching for this exact error reveals nothing related to ccminer (and only very view results in general), experimenting with cli and windows updates now, will post results (had base 8.1 x64 install without updates)

**Comment by felixbrucker** [comment]
running ccminer directly from cli works for a longer time but those errors are more sporadic
i ran it for 32 minutes and then connected via teamviewer to check cli output and was shown the errors (might be triggered?) 
a second run directly from cli is now running since 50 minutes fine, even after connecting with teamviewer multiple times

very strange

will test latest 1.8 ccminer from tpruvot now as it supports pascal

update: ccminer 1.8 (tpruvot) has the same issue

**Comment by felixbrucker** [comment]
as a first conclusion i can say: ccminer started via cli two times (the first instance generates only half the hashes per second for some reason and in return gets killed by my script after 20 sec) produces a stable hashrate and does not crash. i have not attempted to connect via teamviewer in this case and its been running for over 90 minutes now (as per NH web ui)

**Comment by felixbrucker** [comment]
switched to win 10 and no problems since, NHM works fine with multiple gtx 1070

might be due to increased chunk sizes in win 10 compared to win7/8, at least thats the only reference to "unspecified launch failed" i found (https://bitcointalk.org/index.php?topic=826901.msg15524494#msg15524494)

**Comment by felixbrucker** [comment]
aaaaaand still in win10, too

will wait for a fix from ccminer devs

**Comment by felixbrucker** [comment]
finally found the cause: the mainboard itself, z170 chipsets tend to have an unstable pcie bus and cant handle multiple pcie cards well
(https://forum.ethereum.org/discussion/comment/23808 , https://forum.ethereum.org/discussion/comment/24847 and https://forum.ethereum.org/discussion/5787/3-way-mining-rig-nvidia-vs-amd)

**Comment by AndrewDonelson** [comment]
This issue still exist. I have Asus B250 Mining Expert board with 6 MSI GTX1080ti 11G, and 2 MSI GTX 1070. 32GB Ram and 32GB dedicated SWAP.

I get this same error on Lyra2Rev2, and Lybry. Overlocked, Factory Default, Drop power to 75%. Nothing works. Other Algorithms on ccminer work perfect. Hard to believe this issue is still around over a year later. 

Anyone figure it out?

**Comment by jstevenson81** [comment]
So I had the exact same issue and had almost given up when I realized there is a switch you can pass into ccminer that may solve my issue.  My problem was I would set the power level of each card in msi afterburner and then start mining.  

I would watch the power level of the card CLIMB past the setting in Afterburner.  If it stayed past that level, I would get the "unspecified launch error".  So, I googled and found nothing, and almost gave up when I checked the ccminer readme.  

There's a setting in there call --plimit, and it defaults to 150%.  So, I watched again, and sure enough, my power level would spike up to the max my card would allow (my 1060's only allow 117% and my 1080 ti's only allow 120%).  So, because I have 6 cards, I did this in my config

`--plimit=70,70,70,70,70,70` (replace 70 with whatever power level you want ccminer to respect)

And now I'm stable and my power limits on each card are respected.  I hope this helps you.  It was EXTREMELY frustrating for many days and nights trying to figure out why this error would randomly show up.

**Comment by Kugell** [comment]
@jstevenson81 
Thank you for taking the time to post your solution. I am unable to locate the --plimit setting. In which config file did you place the --plimit setting in and what directory is the file located in?  

Thanks!

**Comment by jstevenson81** [comment]
Not in the config file. It’s a switch in the batch file you use to run ccminer.

Thanks,
Jonathan Stevenson
Chief Information Officer
Intelligent Retinal Imaging Systems
(504) 430-0812
jstevenson@retinalscreenings.com<mailto:jstevenson@retinalscreenings.com>

On Nov 8, 2017, at 01:37, Kugell <notifications@github.com<mailto:notifications@github.com>> wrote:


@jstevenson81<https://github.com/jstevenson81>
Thank you for taking the time to post your solution. I am unable to locate the --plimit setting. In which config file did you place the --plimit setting in and what directory is the file located in?

Thanks!

**Comment by epb5119** [comment]
The setting is in the batch file. Here's my example.
ccminer -a lyra2v2 -o stratum+tcp://hub.miningpoolhub.com:20593 -u "your logon id.worker" -p "worker password" --intensity=20 --plimit=77,77,77,77,77,77
You may need a lower intensity and or power level to stop the unspecified launch failure. regards
Ernie

**Comment by alexrancel** [comment]
Thank you so much for this valuable help!!!!

**Comment by Fyril** [comment]
How to you put that in to Nicehash?  The miners in the bin folder does not have that bat file?

**Comment by winnal** [comment]
I am getting “unspecified launch error” on excavator.

**Comment by BrianRamsay** [comment]
When I try using --plimit it says I have insufficient permissions. But when I try to run the batch file as an administrator, it immediately closes.

**Comment by jbrady89** [comment]
@BrianRamsay I am getting this as well. Were you able to solve it?

**Comment by epb5119** [comment]
different mining software can use various file type to manage the miner parameters. Some programs use BAT files, others use CONF files and others use JSON files. It is best for you to join the Discord or Slack communications media used for the coin u are mining. In those social media channels u can get very good support from fellow miners that match the coin/miner/GPU u are using..

**Comment by cholakovdev** [comment]
I just disabled the GPUs in windows and then enabled and now works fine.

**Comment by yelgaoual** [comment]
increasing the size of the virtual memory solved my problem

**Comment by BelgianBoy** [comment]
> I just disabled the GPUs in windows and then enabled and now works fine.

This sorted my problem, thank you! I also made my virtual memmory bigger to 35000mb on one rig and other to 40000mb.

This regedit i did also for a problem with nicehash.

https://www.kapilarya.com/display-driver-stopped-responding-and-has-recovered-windows-10

But the easiest one (yours) fixed it i think honestly, cheers!
