### ISSUE TITLE
NVidia multiple card detection

### ISSUE THREAD

**Issue by trinitrate** [nicehash/NiceHashMiner-Archived#173]
I have two 1070's running on a Win10 platform.   Everything works as expected during initial boot up, NH detects both cards and begins mining just fine. 

If I stop mining using the 'stop' button, and then start again, NH will only show one GPU and will only mine at 1/2 speed.    Nvidia GeForce Experience and FireStorm both see and can interact with the second card. 

A reboot always fixes the issue.

**Comment by nicehashdev** [comment]
Does the second card suddenly disappear from the list of devices?

**Comment by trinitrate** [comment]
The card remains on the list, but the miner won't launch properly after that, indicating non existent card. (See screenshot). I guess that would point to my machine being the issue, but interestingly other Nvidia tools can interact with both of the cards. 

If I quit NH and re-launch it, it only shows one card, but will mine off of that one card just fine. I am using RDP to control the miner if that matters. 

![untitled](https://cloud.githubusercontent.com/assets/20744943/17279989/fb4a2298-5738-11e6-986f-090d3013bb2e.png)

**Comment by nicehashdev** [comment]
Could you clear your log file, invoke bug again and then attach log here?

**Comment by felixbrucker** [comment]
during my short time with win10 i had not encountered this error, while waiting you could try if this also happens if not using rdp (which is known for breaking gpu detections) and try with teamviewer or direct console via VGA/DVI etc

**Comment by Singman33** [comment]
to take control of rigs, never use RDP, the best solution is VNC (all flavors).

**Comment by trinitrate** [comment]
I retested from the console, and couldn't reproduce the issue.  You can probably drop this one and dismiss it as an RDP issue.  I saw the note on RDP on the site, but it only mentioned issues with AMD cards.

**Comment by nicehashdev** [comment]
Ok, looks like NVIDIA cards have issues with RDP as well.
