### ISSUE TITLE
[FYI] new optimized hodl-miner by Optiminer

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#174]
not tested as of now if it generates valid shares, but you might want to keep track of https://github.com/Optiminer/hodlminer-wolf (https://bitcointalk.org/index.php?topic=1317918.msg15768475#msg15768475)

performance improvements are impressive and could be included/merged into the hodlminer you ship

br

**Comment by nicehashdev** [comment]
We will take a look into it. But currently, HODL is having some issues and we do not expect it to have good profitability for a while, so this is not a priority for us.

**Comment by felixbrucker** [comment]
yes, its only fyi :D

might be useful for hodl based coins like ERC
