### ISSUE TITLE
Disappears address btc ( not important)

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#175]
During the initial setup ( for example, put the new version nicehash ) if you first set up the address and autostart of mining btc , apply settings ( nicehash restart say ) - then when you restart nicehash says you must do the testing speeds and at this moment I see that the entered address btc disappeared.

This is a bug or a feature ?

**Comment by trinitrate** [comment]
I noticed that if you dont launch NH as an administrator. You need to be able to write to the config file that is stored with the EXE.   If you place NH in program files for example, your regular user account doesnt have write permissions into that folder to save the address (and default server location).
