### ISSUE TITLE
Tesla M60 Lyra2 problems

### ISSUE THREAD

**Issue by lincolnjohnson** [nicehash/NiceHashMiner-Archived#176]
Issue still exists. Appears to be a conflict with the nanashi miner only, and I think I've narrowed it down to it being built with Cuda 8.0 - the existing drivers only support up to 7.5.

I managed to compile a version that works by compiling it with Cuda SDK 7.5.

**Comment by nicehashdev** [comment]
Tesla cards are not officially supported by NiceHash Miner. If we decide to add support, we will take a look into this issue as well.

**Comment by kenshirothefist** [comment]
@lincolnjohnson we are now testing Nvidia M60. What kind of speed were you able to get on Lyra2re and Lyra2rev2? Which OS did you use?

**Comment by lincolnjohnson** [comment]
Windows server 2012 R2, lyra2v2 ~43.88 MH/s

**Comment by kenshirothefist** [comment]
OK, we tested Nvidia M60 with latest drivers and CUDA 8 mining software builds - all works fine. Anyway, any Tesla or Quadro card, which is based on Maxwell architecture should work just fine with NiceHash Miner.
