### ISSUE TITLE
Error Benchmark on lyra2re for Nvidia gtx 550 ti, it just stuck there for hours and hours any idea why?

### ISSUE THREAD

**Issue by maxlopez123** [nicehash/NiceHashMiner-Archived#177]
Error Benchmark for lyra2re for Nvidia gtx 550 ti, it just stuck there for hours and hours any idea why?

**Comment by Lbniese** [comment]
Have you made sure that you have the latest version of both NiceHash Miner and your GPU driver?

**Comment by felixbrucker** [comment]
my gtx 550ti is working fine (win8.1 x64, v1.6.1.4)

**Comment by DrRobotto** [comment]
I have the same problem on a GTX 970 with lyra2re, lyra2rev2 and daggerhashimoto. Drivers are up to date and the ccminer-1-8-tpruvot-windows is working with 20.50MH/s

**Comment by S74nk0** [comment]
lyra2re benchmark error will be fixed in the future release. @DrRobotto daggerhashimoto should work. Can you please give more information about daggerhashimoto problem?

**Comment by DrRobotto** [comment]
@S74nk0 when I press the benchmark button, I immediately get 0.000 MH/s and nothing else happens.

**Comment by S74nk0** [comment]
@DrRobotto please post the log file and we'll inspect this problem. Also what Nvidia drivers are installed on your machine?

**Comment by DrRobotto** [comment]
@S74nk0 Hm, I tried to reproduce the error, but after the installation of the newest NVidia driver (372.54) everything seems to work.  Even lyra2re, lyra2rev2 and daggerhashimoto . Thx for your help!
