### ISSUE TITLE
Default intensity crashes lyra2rev2 on 7970

### ISSUE THREAD

**Issue by mky300** [nicehash/NiceHashMiner-Archived#178]
xintensity is too high by default on this card

--keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --xintensity 160  --thread-concurrency 0 --worksize 64 --gpu-threads 1

works (was default string in previous versions)

**Comment by nicehashdev** [comment]
You can modify or disable these parameters in latest version.

**Comment by mky300** [comment]
Would be nice if the default settings were appropriate for most cards, or you logged common settings used on that particular model card that could be automatically retrieved from an API on your website. Have to change this every time I upgrade to a new version - most users would have no idea what to change it to, to make it work.
