### ISSUE TITLE
1.6.1 all revs are reporting incorrect hash to NiceHash.com

### ISSUE THREAD

**Issue by uvxcoin** [nicehash/NiceHashMiner-Archived#179]
I have never this happen with 1.5.1.0
All revs of 1.6.1 are, after a few hours of mining, reporting very low Dagger hashrate to NiceHash.com and thats what we are getting paid on.

I have monitored my rig very closely during these incorrect reporting times and have never seen even remotely close to the low hash reported to nicehash.com

As I write this nicehash.com is showing (paying) DaggerHashimo at a speed of about 19 MH/s but my rig has never dipped under 45 MH/s and averages 50 MH/s. 

My rig is 4X AMD sapphire 270X
Windows 7 X64
Latest Crimson drivers (I changed from Crimson 15.7.1 to latest as no version after 15.1.0 would run ETHminer on old drivers)

As I finish writing this issue I have checked again and Nicehash is showing a speed of 19.45 MH/s Dagger and the Miner on the rig is showing average of 50 MH/s

I don't care if speed is reported wrong but I sure don't want to paid wrong for it.

I am switching back to 1.5.1.0 which IMO is by far the best version of the minor to date.

**Comment by nicehashdev** [comment]
Is your ethminer reporting speed of 50 mhs or less?

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.
