### ISSUE TITLE
NiceHashMiner does not save the currency I selected.

### ISSUE THREAD

**Issue by CharlesDeep** [nicehash/NiceHashMiner-Archived#181]
-The currency selector to show you balance does not save the currency you selected.
<img width="123" alt="58031c5377d6b5e31db07745a0d27599" src="https://cloud.githubusercontent.com/assets/18505627/17644863/92ad24e6-6193-11e6-9b0e-7b53bed6acfd.png">

**Comment by nicehashdev** [comment]
Use latest version and reopen if issue persists.
