### ISSUE TITLE
Wont Mine Daggerhashimoto on Benchmark R9 380 - 4GB

### ISSUE THREAD

**Issue by Sifontes** [nicehash/NiceHashMiner-Archived#184]
Hello guys,

i have several rigs mining but when trying to benchmark or mine the daggerhashimoto coin with my R9 380, the card simply wont even try the benchmark, any advices?

thanks!

**Comment by S74nk0** [comment]
@Sifontes can you post the log file so we can see what is wrong?

**Comment by Sifontes** [comment]
I got it fixed!!

Had to do with an AMD SEMPRON APU that was interfering with the
daggerhashimoto mine.

Thanks for your reply!!
