### ISSUE TITLE
No graphics cards???

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#185]
No graphics cards show up in the list. I have 2 HD7950 installed in the system and they show up in device manager as working properly.

**Comment by S74nk0** [comment]
@xadonxander please post the log file so we can inspect this issue.

**Comment by xadonxander** [comment]
Solved it. Apparently only the primary graphics card will show up if connected via remote desktop. When the Radeon cards were installed it selected the intel graphics so nothing showed up in the list. I switched the cards for nvidia and then only one card would show over remote connection. I restarted with and used local keyboard and mouse All the cards show up. However with 2 HD7950 and a R9 270 I am only getting 15khs so It looks like only 1 card is being used for eth. Nvidia cards are working great!

**Comment by malagent** [comment]
This is indeed an issue with Microsoft's RDC. It has long implemented a generic video driver over RDC, in lieu of a the CUDA or OpenCL driver(s). This is an issue I encountered in 2007, which still persists today.
Some other remote applications do correctly show the hardware such as GPUs. TeamViewer for example.
