### ISSUE TITLE
Could no longer open nicehash

### ISSUE THREAD

**Issue by ledj1996** [nicehash/NiceHashMiner-Archived#186]
I just started mining a week ago, for me this is the easiest way for me to mine. 
Yesterday the program just wont open. I tried downloading a new 1.6.1.4 it opened but after i choose my language it closes. I tried turning off windows defender yet it still closes after choosing a language.

**Comment by S74nk0** [comment]
Hello @ledj1996. Can you please post the log file?

**Comment by ledj1996** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/432024/log.txt)

**Comment by ledj1996** [comment]
sorry this is the log file when it first happened 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/432028/log.txt)

**Comment by ledj1996** [comment]
My windows was on maintenance that time, im not sure if it changed something on my computer stopping nicehash from running

**Comment by S74nk0** [comment]
Hi @ledj1996. Try running [NiceHashMiner v1.7.0.3-BETA](https://github.com/nicehash/NiceHashMiner/releases/tag/v1.7.0.3-BETA) and report if the problem persists.

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.
