### ISSUE TITLE
Daggehashimoto ethminer --dag-load-mode singlekeep

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#189]
Please add possibility to change --dag-load-mode during minig daggerhashimoto
Even if choosen one GPU and only one algo dagger ethminer.exe uses 1,6Gb RAM. Why keep dag in RAM if 1 choose only 1 algo?
I tried to add --dag-load-mode single in config, but it nothing changes.

**Comment by S74nk0** [comment]
Hello @UnclWish. We will add this feature in the future release. Thanks for the suggestion.
