### ISSUE TITLE
[Feature] 1.7.0.0 to display bench speed while/after benchmark

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#190]
while 1.7.0.0 is in active development the first thing i missed was the display of the benchmarked speed for the current/last algorithm while the others are still running, as the overview over the speeds is now moved to another form

cheers

edit: one can move the forms so he can observe the stored values of the benchmarks but the last/current bench speed displayed in the benchmark form would definitely be great

**Comment by S74nk0** [comment]
Hi @felixbrucker. We will fix this problem. The UX will probably change significantly. Thanks for your reply.
