### ISSUE TITLE
[Bug][1.7.0.1 BETA]Downloading miners every time

### ISSUE THREAD

**Issue by blockbasti** [nicehash/NiceHashMiner-Archived#192]
Everytime I run NHM, it downloads all the miners, even when it just downloaded them seconds ago. I don't have an Antivirus so they don't get deleted by that.

**Comment by S74nk0** [comment]
Hi @blockbasti. We cannot reproduce this error. Can you give us more information (log file, OS)?

**Comment by Kayfolom** [comment]
I confirm that an error appeared in the windows 7 prof x64. After installation vcredist_x64.exe and
vcredist_x86.exe, the problem is resolved. Although previous versions worked fine.
