### ISSUE TITLE
[BUG] [1.7.0.1] GTX 1060's create 5.x device group with older GPU names

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#194]
upon starting mining daggerhashimoto with 6x 1060's the device group 5.x appears and displays older GPUs

see screen for clarification:
![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18143624/3ee3b97c-6fc3-11e6-8d26-9942d2c051c0.PNG)
the speed is not picked up and stays at zero kh/s

after some time the miner disconnects from nicehash and displays the correct string and speed
![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18145043/ce5d69d0-6fc9-11e6-848a-ea4075f2282e.PNG)

upon switching to another algo because it is more profitable ethminer.exe stays open ("Cant't submit solution: not connected")

**Comment by S74nk0** [comment]
Hi. Can you please post the log file so we can inspect this?

**Comment by felixbrucker** [comment]
sure: 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/448349/log.txt)

**Comment by S74nk0** [comment]
Thanks.

**Comment by felixbrucker** [comment]
a similar problem occurred on my gtx 1070 rig with daggerhashimoto, the miner stopped working because it  could not connect to nicehash (network connectivity was fine)

upon restarting the miner (by clicking stop, then start) it was able to continue working

screen and log appended below

![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18160204/966adcd4-702c-11e6-845d-39ff39808c2a.PNG)

[log.txt](https://github.com/nicehash/NiceHashMiner/files/449099/log.txt)

**Comment by felixbrucker** [comment]
if in the case above the NHM switches algorithms two miner are open (ethminer starts hashing again after some time)

**Comment by felixbrucker** [comment]
the original issue seems resolved in 1.7.0.2, the other issue persists, will create another issue for this
