### ISSUE TITLE
[Feature] [1.7.0.1] Autostart Mining on Open

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#195]
im missing the option to autostart mining upon opening the miner (was present in earlier versions < 1.7.x.x)

cheers

**Comment by Kayfolom** [comment]
+1

**Comment by nicehashdev** [comment]
We probably will not be using this feature anymore, because some people were installing NiceHashMiner on botnets.

**Comment by Kayfolom** [comment]
Then disable "Start Mining When Idle" and button "Start" - to accurately villains could not use the app

**Comment by felixbrucker** [comment]
So what will be the preferred way of starting the miner on a dedicated rig with no monitor connected? Should i always need to connect via teamviewer and start the mining manually? This seems rather inefficient and poorly designed.

I get that you want to counter bot nets, but this is not the right way

**Comment by felixbrucker** [comment]
in the meantime i have created this autoit script to enable startup after 20 sec:

```
Run("NiceHashMiner.exe")
Sleep(20000)
Opt("WinTitleMatchMode", 4)
WinActivate("[REGEXPTITLE:NiceHash Miner*]")
Sleep(200)
Send("{TAB}{TAB}{TAB}{TAB}{TAB}{ENTER}")
```

though this quick and dirty hack should definitely not be needed in the final release :/
