### ISSUE TITLE
[BUG] [1.7.0.1] cryptonight benchmark fails on GTX 1070

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#196]
the cryptonight benchmark fails on my 6x GTX 1070 rig (runs fine on 6x GTX 1060)

the actual mining works fine (via cmd and when starting via the NHM)

**Comment by S74nk0** [comment]
What NVIDIA driver version is installed? Also log file could help.

**Comment by felixbrucker** [comment]
sure:
[log.txt](https://github.com/nicehash/NiceHashMiner/files/448354/log.txt)

driver version 372.54

**Comment by S74nk0** [comment]
@felixbrucker thanks for your feedback this issue will be resolved in the future release.

**Comment by JRDAVIS1** [comment]
It is certainly resolved in 1.7.0.2. That algo works fine on my 1070 (and 1080 and 980 ti)
