### ISSUE TITLE
Unable to set Japan as the default location

### ISSUE THREAD

**Issue by Torsdan** [nicehash/NiceHashMiner-Archived#2]
I would assume Location 3 would be Japan, but setting it to that resets to 0 thus back to Europe, unless I'm missing something.
Also is there options to run and auto-hide the main window to tray?

**Comment by Torsdan** [comment]
Found the issue with Location. Changed Form1 line 59 from:
if (Config.ConfigData.Location >= 0 && Config.ConfigData.Location < 3)
to:
if (Config.ConfigData.Location >= 0 && Config.ConfigData.Location <= 3)

**Comment by kenshirothefist** [comment]
Resolved in 7d06e82e8af5e41011301399afe33ffe3a62cf70. Closing.
