### ISSUE TITLE
NiceHashMiner 1.7.0.1-beta does not load binaries

### ISSUE THREAD

**Issue by JRDAVIS1** [nicehash/NiceHashMiner-Archived#200]
After starting the beta I'm advised that a required path name cannot be found (...bib/...). I press 'continue' and it says it is loading, but after 15 minutes it is clear that no downloads are actually happening.

**Comment by S74nk0** [comment]
Hi @JRDAVIS1. We have discontinued NiceHashMiner 1.7.0.1-BETA (I suspect you have AMD cards and are experiencing this error). Please try [NiceHashMiner 1.7.0.2-BETA](https://github.com/nicehash/NiceHashMiner/releases/tag/v1.7.0.2-BETA). This version should fix the problem. I will close this issue. If you are experiencing this issue with NiceHashMiner 1.7.0.2-BETA please reopen it.
