### ISSUE TITLE
[BUG] GPU #0: result for 00000000 does not validate on CPU! Asus GTX 650

### ISSUE THREAD

**Issue by hadeshuynh** [nicehash/NiceHashMiner-Archived#201]
hey guys i just learn about mining and have error in this step when i star the CPU and GPU it always has a terminal with these command

GPU #0: ASUS GTX 650, 20.41 GH/s
GPU #0: unspecified launch failure
GPU #0: result for 00000000 does not validate on CPU!
 GPU #0: result for 00000000 does not validate on CPU!

anyone can help me please ???

**Comment by S74nk0** [comment]
Hi @hadeshuynh. You must be using NiceHashMiner 1.6.1.4. Unfortunately most cards below SM5.x don't work good for Lyra2RE and Lyra2REv2 algorithms. You could disable these two algorithms and resume mining or you can try our [BETA](https://github.com/nicehash/NiceHashMiner/releases/tag/v1.7.0.2-BETA)

**Comment by hadeshuynh** [comment]
many thanks
