### ISSUE TITLE
[Feature] Ability to select "LessThreads" for individual CPU algos

### ISSUE THREAD

**Issue by fuzzfuzz** [nicehash/NiceHashMiner-Archived#204]
Hi,
I run NiceHashMiner across a variety of CPU.
With new CryptoNight, it is much more profitable at the moment, so most of farm is on this. As it requires ~2MB of fast cache, it makes sense to run miner with less threads on most CPU as it is more efficient.
e.g. a Sandy Bridge Xeon 8 core (10 meg cache) I run with 4 cores as it is much faster than with 8 cores.
Issue is though - at some point CryptoNight will be not as profitable and e.g. CPUs will crunch hodl or lyra, but with less threads as Miner is specified to use only 4 of 8 threads. Unless I manually monitor this constantly lyra or hodl will not be as efficient as could be.
It would be nice to see ability to set individual thread number per algo on CPU.

Worth noting I'm only seeing the need to drop thread count on CPU with AVX. Older CPU with SSE2 don't seem to benefit from reduced core.

Thanks and keep up excellent work! Randall.

**Comment by S74nk0** [comment]
Hi @fuzzfuzz. We will make this feature available in the next release.
