### ISSUE TITLE
Miner windows close immediately after hitting start/Unhandled exception when starting CPU mining

### ISSUE THREAD

**Issue by duel007** [nicehash/NiceHashMiner-Archived#205]
Currently having two possibly related issues. I benchmarked both GPU's (GTX 780) and CPU (i5-6600k) just fine but when I start the CPU miner only, I get an unhandled exception (Logs below)

When starting the two GPUs, the window opens, and makes it as far as "stratum detected a new block" and then the window closes. No stats ever appear in the nicehash window so it's not running in the background.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at NiceHashMiner.Miner.UpdateBindPortCommand_ccminer_cpuminer(Int32 oldPort, Int32 newPort)
   at NiceHashMiner.Miners.cpuminer.UpdateBindPortCommand(Int32 oldPort, Int32 newPort)
   at NiceHashMiner.Miner.ChangeToNextAvaliablePort()
   at NiceHashMiner.Miner.Stop_cpu_ccminer_sgminer(Boolean willswitch)
   at NiceHashMiner.Miners.cpuminer._Stop(Boolean willswitch)
   at NiceHashMiner.Miner.Stop(Boolean willswitch)
   at NiceHashMiner.Miners.MinersManager.GroupMiners.End()
   at NiceHashMiner.Miners.MinersManager.StopAllMiners()
   at NiceHashMiner.Form_Main.buttonStopMining_Click(Object sender, EventArgs e)
   at NiceHashMiner.Form_Main.IdleCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

NiceHashMiner
    Assembly Version: 1.7.0.2
    Win32 Version: 1.7.0.2
##     CodeBase: file:///D:/Downloads/nicehash/NiceHashMiner_v1.7.0.2-BETA/NiceHashMiner.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
##     CodeBase: file:///D:/Downloads/nicehash/NiceHashMiner_v1.7.0.2-BETA/Newtonsoft.Json.DLL

System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
##     CodeBase: file:///D:/Downloads/nicehash/NiceHashMiner_v1.7.0.2-BETA/log4net.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/Downloads/nicehash/NiceHashMiner_v1.7.0.2-BETA/MessageBoxManager.DLL

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by S74nk0** [comment]
Hi @duel007. Can you post the log file (log.txt or logs\log.txt)?

**Comment by duel007** [comment]
Sure, here @S74nk0 

http://pastebin.com/bPL6Gv5B

**Comment by duel007** [comment]
This is on the latest beta, FYI. I don't see the option to select the version I'm running.

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.
