### ISSUE TITLE
[BUG] [1.7.0.3] benchmark

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#208]
current behavior: i have 6 identical GPUs enabled, in benchmark mode it shows "Bechmark step (1/96)"

expected behavior: benchmark all enabled devices at once if the same device or only benchmark one device and multiply the results (option switch or something to choose)

not exactly a bug, might be intended. but its odd

**Comment by S74nk0** [comment]
Hi @felixbrucker. Yes the previous version had worked as you described. I suggest that you benchmark only one card and then right click on the others and copy benchmarks from the benchmarked card. We will make this feature more streamlined/smarter in the future so users will not have to do this manually.

**Comment by felixbrucker** [comment]
ok thanks for clarifying
