### ISSUE TITLE
[BUG] [1.7.0.3] resize NHM

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#209]
i noticed one can now resize the window, but its not working (at least for me on win 8.1 x64)

![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18322917/6aabb2cc-7535-11e6-8669-e64beb7f85b7.PNG)

**Comment by S74nk0** [comment]
This was a BETA BUG, resizing is not available/enabled (as of the time of writing). I will close this issue.
