### ISSUE TITLE
doest mine

### ISSUE THREAD

**Issue by amfofo** [nicehash/NiceHashMiner-Archived#21]
running windows 10 64bit. 
benchmark result is terminated
![capture](https://cloud.githubusercontent.com/assets/16478762/12515407/3b4d6a60-c163-11e5-8d21-70805fa3d2a8.PNG)
this is what i got when starting the miner
![capture](https://cloud.githubusercontent.com/assets/16478762/12515436/5fc24456-c163-11e5-8c5b-e8080bfa0d5f.PNG)

**Comment by theLosers106** [comment]
Have you tried running the runme.bat? Does it run normally?

**Comment by felixbrucker** [comment]
i noticed a similar result with plain sgminer after a recent windows 10 update, it could not find/register/use the opencl device, haven't fixed it yet.

**Comment by transcats** [comment]
Same issue (w7 64). Tried running latest sgminer afterwards and none of the servers are responding. Wireshark shows servers are closing the connection immediately.

It's as if running the benchmark causes the servers to blacklist your IP.

**Comment by theLosers106** [comment]
@felixbrucker have you tried --gpu-platform ? sometimes the integrated GPUs or NVidia GPUs can cause problem. you just need to find the right --gpu-platform number.

**Comment by theLosers106** [comment]
@transcats you will have to contact nicehash about that.. email them your ip address to support@nicehash.com

**Comment by felixbrucker** [comment]
it seems to be related to the amd driver as a complete reinstall of a different OS but with the same current amd drivers resulted in the same problem, will try 15.7 when i have time

@theLosers106 it's not related to some igpu or something

**Comment by d57heinz** [comment]
ive got it working but for whatever reason it will not take any gpu clock settings.. Always puts my hd7970 to 925 mhz gpu and 1375 mem clock.. Not sure whats going on but when i tried to go back to 1.2.2.2 which let me set whatever clock .. seems to do the same thing now as well.. Maybe was a windows update.. ill keep tweaking with things see if i can get it rolling again... win 10 64 bit pro xfx hd7970 3gb ram 15.7.1  hate to try crimson again that was a nightmare... dont like the lack of functionality crimson had vs catalyst..

**Comment by amfofo** [comment]
Reinstalled everything and its working.
When running benchmark Some algo from 1.2.2 is not working in 1.2.3.0. I dont know why

**Comment by d57heinz** [comment]
I also have figured out what i think happen with mine..
when i ran the new version the config still had the autogpu flag in there. I think that caused some kind of glitch.. I shut down computer.. reloaded the miner with no config.json. Then once it created the new one i shutdown the nicehashminer.. Then i edited the file by removing all the lines of auto-gpu.. then i also put --gpu-engine=1040 in the global extraparameters.. All seem to work great now. And my overclock settings are staying where i want them.. Getting 3.3 mhs on x15.. not sure if that good for a hd7970 or not>> Its mostly mining x11 lyra and quark anyway.. Thanks again for the feedback everyone..Best regards Doug

**Comment by amfofo** [comment]
Nice. I'll try to check my config later

**Comment by felixbrucker** [comment]
without doing anything besides updating windows server2012r2 its working now (using crimson 16.1), and the optimized sgminer is doing great (15.25Mh/s on a 290x) :D

**Comment by kenshirothefist** [comment]
Glad to see it's working. Latest AMD drivers are a bit clumsy for mining, unfortunately, especially on Windows 10. In general the best results for mining are achieved with Windows 7 and 15.7.1 drivers. Will be closing now this Issue.
