### ISSUE TITLE
[BUG] [1.7.0.3] ethminer not getting restarted when failed

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#210]
sadly this issue still persists with 1.7.0.3 and my gtx 1060s rig only:

ethminer stops working randomly, but NHM does not stop/restart it even though it detects 0.000 GH/s speed:

![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18336880/74cf0dc0-758b-11e6-87bd-0f1147bf8d98.PNG)

logs:

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/460831/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/460832/log.txt)

**Comment by S74nk0** [comment]
Hi @felixbrucker. We have located the issue and have been testing the fix. It should be working in the next release. We will keep this issue open for now, until the new release is out.

**Comment by pflip3** [comment]
Hi,

for what its worth, I have a similar issue with the current version (7.1.3).  I noticed that if the video driver fails (overheat or other issues) the miner will never get reset and the Hashrate goes down to 0 or little more.

I tried with the  windows reporting on or off still no resolution.

This behavior started to appear with the 7.x.x version branch.

I have to manually reset the video driver and then the miner goes back to normal operation and speed. ( I have an AMD r9280x with win7 64b, latest amd drivers, doing about 16 Mhs).

**Comment by felixbrucker** [comment]
using the latest 1.7.1.3, for what its worth i had not had such an issue the last days, but i also had not had any driver crash in the last days too. will check if it persists over the next few days.

sidenote: when my nvidia driver crashed it restarted the system (BSOD i guess)

**Comment by felixbrucker** [comment]
fix is working fine :)
