### ISSUE TITLE
Miner DL window remains above everything else

### ISSUE THREAD

**Issue by malagent** [nicehash/NiceHashMiner-Archived#212]
A very miner issue to be sure, but was a little annoying when dealing with other system functions.

On first launch with 1.7.0.3B, the miner DL status window/progress bar remained above everything else when I switched away from NH miner.  Additionally, when I clicked in a web browser window (and other apps such as control panel, over where the NH application window is under the apps I get an error sound and the mouse click is not registered in the correct application. I had to move said application's window to correctly register such actions.
![dl window remains on top everything](https://cloud.githubusercontent.com/assets/17844295/18360091/468b4e1a-75c2-11e6-9340-06103bd5c0e8.PNG)

Testing system details:
- OS Name: Microsoft Windows 10 Enterprise
  - Version  10.0.10240 Build 10240
- System Model: MS-7865
  - Processor: AMD Athlon(tm) 5350 APU with Radeon(tm) R3, 2100 Mhz, 4 Core(s)
  - Adapter Type: AMD Radeon Graphics Processor (0x6610), Advanced Micro Devices, Inc. compatible
  - Adapter Description: AMD Radeon R7 200 Series [XFX R7 250; 2GB]

**Comment by S74nk0** [comment]
This will be fixed this in the upcoming release.
