### ISSUE TITLE
Can't access Config window in NiceHashMiner 1.7.0.3 BETA

### ISSUE THREAD

**Issue by CharlesDeep** [nicehash/NiceHashMiner-Archived#213]
<img width="424" alt="23d94ac301f7706099b3872b7c1498a5" src="https://cloud.githubusercontent.com/assets/18505627/18362475/1d3d64be-7606-11e6-91b7-209ba075f217.png">
When I try to open the Config window, the program thrown me an exception.
My PC:
Windows, 10, build 10586
16 GB Ram

**Comment by CharlesDeep** [comment]
(en (spanish) = in (english))
*************\* Texto de la excepción (EXCEPTION TEXT) **************
System.Collections.Generic.KeyNotFoundException: La clave proporcionada no se encontró en el diccionario.
   en System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   en NiceHashMiner.Forms.FormSettings.InitializeGeneralTabFieldValuesReferences()
   en NiceHashMiner.Forms.FormSettings.InitializeGeneralTab()
   en NiceHashMiner.Forms.FormSettings..ctor()
   en NiceHashMiner.Form_Main.buttonSettings_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by S74nk0** [comment]
Hi @CharlesDeep. Did this error occurred on previous BETA-s? Did you added an additional language file?

**Comment by CharlesDeep** [comment]
No, I haven't used any language file.
And no, there wasn't this error in the 1.7.0.2 BETA.

Also, can I start translating the program as I did in the 1.6 version?

**Comment by S74nk0** [comment]
That is strange.  You have unzipped the bin and started and crashed after clicking settings as I understand correctly? Can you please post the log file (it might help even though I doubt it)?

No not yet, there will probably be more GUI changes.

**Comment by CharlesDeep** [comment]
I´ve deleted the langs file and restarted NiceHashMiner.. Before that I looked in the langs folder and there was only en.lang.

Then the lang folder was redownloaded  and the Settings window worked.

Conclusion: The lang file could be corrupted.

**Comment by S74nk0** [comment]
I am not sure what could be the cause of this BUG. Have tested NHM 1.7.0.3 on several machines and didn't encounter this problem. What is your Windows Locale? If you have the deleted en.lang file your trash that was/is corrupted can you post it here? I am really not sure what could be causing the problem. Bad unzip? Ram issues? Disk issue?

**Comment by CharlesDeep** [comment]
[en.lang.txt](https://github.com/nicehash/NiceHashMiner/files/462566/en.lang.txt)
(The file ends with .txt because Github does not allow .lang in here)

I have compared the "corrupted" one with the good file and there is no difference. So this must be a temporal error caused by something that alredy passed.
