### ISSUE TITLE
[1.7.0.3 BETA] Can't find Nvidia Tesla cards since the driver version is too low

### ISSUE THREAD

**Issue by kuntan2237** [nicehash/NiceHashMiner-Archived#215]
Hi NHM developpers,
I'm using Tesla K80 and the driver has been updated to the latest 354.99
But when I started NHM 1.7.0.3 BETA, there's message -
"We have detected that your system has Nvidia GPUs, but your driver is older than 362.61. In order for Nicehash Miner to work correctly you should upgrade your drivers to recommended 372.54 or newer"

Could you help?

**Comment by S74nk0** [comment]
Hi @kuntan2237. Can you please post the log file?

**Comment by kuntan2237** [comment]
This is another system with Nvidia GRID K2 cards.
There's some font issue but I think it might be worth to have a check.
I'm using Tesla driver 354.92 and it was working fine with NHM 1.6.0.0 before.

The failure happened here
**[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] CudaDevicesDetection found no devices. CudaDevicesDetection returned: CUDA error in func 'CudaDetection::QueryDevices' at line 15 : CUDA driver version is insufficient for CUDA runtime version.**

```
[2016-09-09 16:26:20] [INFO] [NICEHASH] Starting up NiceHashMiner v1.7.0.3
[2016-09-09 16:26:20] [INFO] [NICEHASH] Selected language: English
[2016-09-09 16:26:20] [INFO] [NICEHASH] Total RAM: 98038MB
[2016-09-09 16:26:20] [INFO] [NICEHASH] Page File Size: 12737MB
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] 
QueryVideoControllers: 
    GPU Name (Driver Ver): NVIDIA GRID K2 (10.18.13.5492)
    GPU Name (Driver Ver): NVIDIA GRID K2 (10.18.13.5492)
    GPU Name (Driver Ver): NVIDIA GRID K2 (10.18.13.5492)
    GPU Name (Driver Ver): Microsoft ?W,g>f:y?M?hV(NOR???s) (10.0.10240.16384)
    GPU Name (Driver Ver): NVIDIA GRID K2 (10.18.13.5492)

[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] CudaDevicesDetection found no devices. CudaDevicesDetection returned: CUDA error in func 'CudaDetection::QueryDevices' at line 15 : CUDA driver version is insufficient for CUDA runtime version.
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] 
OpenCLDeviceDetection found devices success:
    Found devices for platform: NVIDIA CUDA
        Device:
            Device ID 0
            Device NAME GRID K2
            Device TYPE GPU
        Device:
            Device ID 1
            Device NAME GRID K2
            Device TYPE GPU
        Device:
            Device ID 2
            Device NAME GRID K2
            Device TYPE GPU
        Device:
            Device ID 3
            Device NAME GRID K2
            Device TYPE GPU

[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): NVIDIA GRID K2 (10.18.13.5492)
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): NVIDIA GRID K2 (10.18.13.5492)
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): NVIDIA GRID K2 (10.18.13.5492)
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): Microsoft ?W,g>f:y?M?hV(NOR???s) (10.0.10240.16384)
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): NVIDIA GRID K2 (10.18.13.5492)
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] Cuda NVIDIA/CUDA device count BAD!!!
[2016-09-09 16:26:21] [INFO] [ComputeDeviceQueryManager] AMD GPU device count GOOD
[2016-09-09 16:26:25] [INFO] [NICEHASH] Version get
[2016-09-09 16:26:27] [INFO] [NICEHASH] ܏
N?S(u0?V??: (503)                        z
[2016-09-09 16:26:27] [INFO] [NICEHASH] SMA get
[2016-09-09 16:26:27] [INFO] [NICEHASH] ܏
N?S(u0?V??: (503)                        z
[2016-09-09 16:26:27] [INFO] [NICEHASH] SMA get failed .. retrying
[2016-09-09 16:26:29] [INFO] [NICEHASH] ܏
N?S(u0?V??: (503)                        z
[2016-09-09 16:26:29] [INFO] [NICEHASH] SMA get failed .. retrying
[2016-09-09 16:26:30] [INFO] [NICEHASH] ܏
N?S(u0?V??: (503)                        z
[2016-09-09 16:26:30] [INFO] [NICEHASH] SMA get failed .. retrying
[2016-09-09 16:26:32] [INFO] [NICEHASH] ܏
N?S(u0?V??: (503)                        z
[2016-09-09 16:26:33] [INFO] [COINBASE] Bitcoin rate get
[2016-09-09 16:26:34] [INFO] [COINBASE] Current Bitcoin rate: 622.74
[2016-09-09 16:26:34] [INFO] [NICEHASH] Balance get
[2016-09-09 16:26:35] [INFO] [NICEHASH] ܏
N?S(u0?V??: (503)                        z
[2016-09-09 16:26:35] [INFO] [NICEHASH] Setting environment variables
[2016-09-09 16:26:35] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
[2016-09-09 16:26:35] [INFO] [NICEHASH] Current DontShowUI value: 0
[2016-09-09 16:26:35] [INFO] [NICEHASH] Setting register value to 1.
```

**Comment by S74nk0** [comment]
Yes I see. We will have to make CUDA device detection work with older drivers then, we will make this available in the future release. What is your Windows Locale settings?

**Comment by kuntan2237** [comment]
The font in mining system? It's setting to Chinese.
I'm using telnet to assess those logs so it doesn't print the character correctly.

**Comment by S74nk0** [comment]
@kuntan2237 thanks for clarifying

**Comment by kuntan2237** [comment]
@S74nk0 Thanks for your quick response.

**Comment by S74nk0** [comment]
Hi @kuntan2237. In the next release CudaDevice detection will be able to work with NVIDIA drivers from 353.54 and newer, so cards in your rig will be detected. If you want I can upload a [link](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/CudaDeviceDetection_SDK_6.5.zip) for unofficial fix or you can wait for the next official release. If you choose the unofficial fix link just copy all the files to NHM 1.7.0.3 BETA and replace with the current ones. If this fixes the problem we will close this issue.

**Comment by kuntan2237** [comment]
Hi @S74nk0 Tesla can be detected now, but there are some GPU and CPU algo benchmark failed.
More details here -
1. The pop-up warning for GPU driver version is still shown up, but this doesn't effect mining.
2. CPU bench mark doesn't work (lyra2re/hodl/cryptonight), while official 1.7.0.3-BETA does work. It looks like new patch skipped CPU benchmarks.
3. GPU daggerhashimoto and cryptonight skipped, the other algo work fine

Logs -

> [2016-09-12 11:48:49] [INFO] [NICEHASH] Starting up NiceHashMiner v1.7.0.3
> [2016-09-12 11:48:49] [INFO] [NICEHASH] Selected language: English
> [2016-09-12 11:48:49] [INFO] [NICEHASH] Total RAM: 12157MB
> [2016-09-12 11:48:49] [INFO] [NICEHASH] Page File Size: 1856MB
> [2016-09-12 11:48:50] [INFO] [ComputeDeviceQueryManager] 
> QueryVideoControllers: 
>   GPU Name (Driver Ver): NVIDIA Tesla K10 (10.18.13.5492)
>   GPU Name (Driver Ver): NVIDIA Tesla K20m (10.18.13.5492)
>   GPU Name (Driver Ver): Microsoft \u57fa\u672c\u663e\u793a\u9002\u914d\u5668(\u4f4e\u5206\u8fa8\u7387) (10.0.10240.16384)
>   GPU Name (Driver Ver): NVIDIA Tesla K10 (10.18.13.5492)
> 
> [2016-09-12 11:48:50] [INFO] [ComputeDeviceQueryManager] 
> CudaDevicesDetection:
>   ADDED device:
>       ID: 0
>       NAME: NVIDIA Tesla K20m
>       VENDOR: NVIDIA
>       UUID: GPU-ed1be628-21ec-fd7d-ade0-2d2874bed19d
>       SM: 3.5
>       MEMORY: 5032968192
>       ETHEREUM: YES
>   ADDED device:
>       ID: 1
>       NAME: NVIDIA Tesla K10.G2.8GB
>       VENDOR: NVIDIA
>       UUID: GPU-ee84802e-2cbb-074f-176c-cecb4565e620
>       SM: 3.0
>       MEMORY: 3757899776
>       ETHEREUM: YES
>   ADDED device:
>       ID: 2
>       NAME: NVIDIA Tesla K10.G2.8GB
>       VENDOR: NVIDIA
>       UUID: GPU-79086769-69bf-af7d-e429-4f6974d989aa
>       SM: 3.0
>       MEMORY: 3757899776
>       ETHEREUM: YES
> 
> [2016-09-12 11:48:51] [INFO] [ComputeDeviceQueryManager] 
> OpenCLDeviceDetection found devices success:
>   Found devices for platform: NVIDIA CUDA
>       Device:
>           Device ID 0
>           Device NAME Tesla K20m
>           Device TYPE GPU
>       Device:
>           Device ID 1
>           Device NAME Tesla K10.G2.8GB
>           Device TYPE GPU
>       Device:
>           Device ID 2
>           Device NAME Tesla K10.G2.8GB
>           Device TYPE GPU
> 
> [2016-09-12 11:48:51] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): NVIDIA Tesla K10 (10.18.13.5492)
> [2016-09-12 11:48:51] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): NVIDIA Tesla K20m (10.18.13.5492)
> [2016-09-12 11:48:51] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): Microsoft \u57fa\u672c\u663e\u793a\u9002\u914d\u5668(\u4f4e\u5206\u8fa8\u7387) (10.0.10240.16384)
> [2016-09-12 11:48:51] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): NVIDIA Tesla K10 (10.18.13.5492)
> [2016-09-12 11:48:51] [INFO] [ComputeDeviceQueryManager] Cuda NVIDIA/CUDA device count GOOD
> [2016-09-12 11:48:51] [INFO] [ComputeDeviceQueryManager] AMD GPU device count GOOD
> [2016-09-12 11:48:54] [INFO] [NICEHASH] Version get
> [2016-09-12 11:48:56] [INFO] [NICEHASH] SMA get
> [2016-09-12 11:48:56] [INFO] [COINBASE] Bitcoin rate get
> [2016-09-12 11:48:58] [INFO] [COINBASE] Current Bitcoin rate: 608.63
> [2016-09-12 11:48:58] [INFO] [NICEHASH] Balance get
> [2016-09-12 11:48:59] [INFO] [NICEHASH] Setting environment variables
> [2016-09-12 11:48:59] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
> [2016-09-12 11:48:59] [INFO] [NICEHASH] Current DontShowUI value: 1
> [2016-09-12 11:49:14] [INFO] [MinersManager] CreateMiner Creating MinerEtherumCUDA instance
> [2016-09-12 11:49:16] [INFO] [BENCHMARK] Benchmark starts
> [2016-09-12 11:49:16] [INFO] [MinerEtherumCUDA] Starting benchmark:  --benchmark-warmup 40 --benchmark-trial 20  --cuda --cuda-devices  0 --dag-load-mode singlekeep 0 --benchmark 2243543
> [2016-09-12 11:49:16] [INFO] [MinerEtherumCUDA] Using miner: bin\ethminer.exe
> [2016-09-12 11:49:19] [INFO] [BENCHMARK] Final Speed: 0.000 H/s 
> [2016-09-12 11:49:19] [INFO] [BENCHMARK] Benchmark ends
> [2016-09-12 11:49:20] [INFO] [BENCHMARK] Benchmark starts
> [2016-09-12 11:49:20] [INFO] [NVIDIA3.x] Starting benchmark:  --algo=cryptonight --benchmark  --devices  0
> [2016-09-12 11:49:20] [INFO] [NVIDIA3.x] Using miner: bin\ccminer_cryptonight.exe
> [2016-09-12 11:49:20] [INFO] [BENCHMARK] Final Speed: 0.000 H/s 
> [2016-09-12 11:49:20] [INFO] [BENCHMARK] Benchmark ends
> [2016-09-12 11:49:20] [INFO] [MinersManager] Reseting MinerEtherumCUDA instance, with new devices
> [2016-09-12 11:49:21] [INFO] [BENCHMARK] Benchmark starts
> [2016-09-12 11:49:21] [INFO] [MinerEtherumCUDA] Starting benchmark:  --benchmark-warmup 40 --benchmark-trial 20  --cuda --cuda-devices  1 --dag-load-mode singlekeep 1 --benchmark 2243543
> [2016-09-12 11:49:21] [INFO] [MinerEtherumCUDA] Using miner: bin\ethminer.exe
> [2016-09-12 11:49:26] [INFO] [BENCHMARK] Final Speed: 0.000 H/s 
> [2016-09-12 11:49:26] [INFO] [BENCHMARK] Benchmark ends
> [2016-09-12 11:49:27] [INFO] [BENCHMARK] Benchmark starts
> [2016-09-12 11:49:27] [INFO] [NVIDIA3.x] Starting benchmark:  --algo=cryptonight --benchmark  --devices  1
> [2016-09-12 11:49:27] [INFO] [NVIDIA3.x] Using miner: bin\ccminer_cryptonight.exe
> [2016-09-12 11:49:27] [INFO] [BENCHMARK] Final Speed: 0.000 H/s 
> [2016-09-12 11:49:27] [INFO] [BENCHMARK] Benchmark ends
> [2016-09-12 11:49:27] [INFO] [MinersManager] Reseting MinerEtherumCUDA instance, with new devices
> [2016-09-12 11:49:28] [INFO] [BENCHMARK] Benchmark starts
> [2016-09-12 11:49:28] [INFO] [MinerEtherumCUDA] Starting benchmark:  --benchmark-warmup 40 --benchmark-trial 20  --cuda --cuda-devices  2 --dag-load-mode singlekeep 2 --benchmark 2243543
> [2016-09-12 11:49:28] [INFO] [MinerEtherumCUDA] Using miner: bin\ethminer.exe
> [2016-09-12 11:49:30] [INFO] [BENCHMARK] Final Speed: 0.000 H/s 
> [2016-09-12 11:49:30] [INFO] [BENCHMARK] Benchmark ends
> [2016-09-12 11:49:31] [INFO] [BENCHMARK] Benchmark starts
> [2016-09-12 11:49:31] [INFO] [NVIDIA3.x] Starting benchmark:  --algo=cryptonight --benchmark  --devices  2
> [2016-09-12 11:49:31] [INFO] [NVIDIA3.x] Using miner: bin\ccminer_cryptonight.exe
> [2016-09-12 11:49:31] [INFO] [BENCHMARK] Final Speed: 0.000 H/s 
> [2016-09-12 11:49:31] [INFO] [BENCHMARK] Benchmark ends
> [2016-09-12 11:49:31] [INFO] [FormBenchmark] EndBenchmark() benchmark routine finished
> [2016-09-12 11:49:59] [INFO] [NICEHASH] Balance get
> [2016-09-12 11:51:00] [INFO] [NICEHASH] Balance get

**Comment by nicehashdev** [comment]
NiceHash Miner is not supported to work only on desktop and mobile video cards. Implementation of miners are not optimized for running on any other types of cards (industry, pro etc), thus you would get very weak performance.

Because we only support desktop video cards, we consider this issue as irrelevant.
