### ISSUE TITLE
Mining daggerhashimoto without internet connection

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#216]
Today my inernet connection was broken during mining dagger through NHM.
Miner cointinues minig about 5 hours without internet. My GPU's all 5 hours work hard without any profit... Ethereum proxy don't says to ethminer that it's no internet connection - stop mining.
It's neccesary to add check of existance of internet during minig daggerhashimoto.

**Comment by S74nk0** [comment]
Hi @UnclWish. What NHM version are you using? Can you post the log.txt?

**Comment by UnclWish** [comment]
NHM 1.6.1.4.
[log.2.txt](https://github.com/nicehash/NiceHashMiner/files/464454/log.2.txt)

**Comment by UnclWish** [comment]
What about this bug? Das it fixed in NHM 1.7+?

**Comment by nicehashdev** [comment]
This is addressed in upcoming new version.
