### ISSUE TITLE
Cannot run benchmarks on AMD cards (finnish Windows 10)

### ISSUE THREAD

**Issue by spegelius** [nicehash/NiceHashMiner-Archived#217]
Two Radeon 7850, they work fine when I start sgminer manually with minimal cmdline. When I try to run benchmarks, GPU utilization stays at ~0% and every result is 0MH/s (except daggerhashimoto).

I tried running the benchmark cmdline on command prompt and this is what i got: [18:26:19] sgminer.exe: --sched-stop: Invalid time set, should be HH:MM. The cmdline was sgminer.exe  --gpu-platform 0 -k x11 --url=stratum+tcp://x11.eu.nicehash.com:3336 --userpass=xxxxxxxxxxxxxxxxxxxxxxxxxx.worker1:x --sched-stop 17.23 -T --log 10 --log-file dump.txt  --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --xintensity 1024 --thread-concurrency 0 --worksize 64 --gpu-threads 1 --device 0,1 --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu && del dump.txt".

So is this somehow an issue with my localisation (finnish)?

**Comment by S74nk0** [comment]
Hi @spegelius. What NHM version are you using? Can you post the log file?

**Comment by spegelius** [comment]
NHM 1.6.14. I switched my region format to English (UK) and now benchmarking produses results. Not all algos, but most. Log here: http://pastebin.com/tfWBiq9j
There's multiple runs on the log

**Comment by S74nk0** [comment]
If some algorithms fail to benchmark then this is a driver issue (I presume based on your driver that WhirlpoolX and Quark, if you want to mine those two try using 15.7.1 driver).  Locale issues should be resolved in the newer releases.
