### ISSUE TITLE
[FEATURE] Please add CryptoNight GPU Miner for AMD Card.

### ISSUE THREAD

**Issue by xiaolin1579** [nicehash/NiceHashMiner-Archived#218]
https://github.com/wolf9466/wolf-xmr-miner
Please use the program to develop the miner to add to the Nicehash Miner.

**Comment by xadonxander** [comment]
+1

**Comment by S74nk0** [comment]
Next release will have **CryptoNight ** with added Claymore's miner ([commit](https://github.com/nicehash/NiceHashMiner/commit/91acd373d5b9af5f32ec21e566318d35cc351d89)).
Closing issue.
