### ISSUE TITLE
No Autostart mining option?

### ISSUE THREAD

**Issue by BogBeast** [nicehash/NiceHashMiner-Archived#224]
Seems to be no option to Autostart mining under settings? I rely on this to restart automatically if (when) my machine crashes. Is this by design?

**Comment by nicehashdev** [comment]
Check here: https://github.com/nicehash/NiceHashMiner/issues/223

**Comment by BogBeast** [comment]
Ok, I can see why. I will see if I can Autoit instead

Could you not re-enable autorun put a warning windows up for say 60 sec at start? saying something to the effect  of "Your computer is running a resource intensive mining application  if this is not what you want, please exit the application from the system tray"  

Maybe disable the option to minimise the app too.

**Comment by felixbrucker** [comment]
#195

**Comment by felixbrucker** [comment]
also it seems 1.7.1.3 supports autostart

**Comment by BogBeast** [comment]
Ah - Ok - thanks Felix
