### ISSUE TITLE
1.7.1.1 > Never successfully completes benchmarking

### ISSUE THREAD

**Issue by FoxyBit** [nicehash/NiceHashMiner-Archived#225]
When I try and benchmark on 1.7.1.1, it will benchmark a few different coins but skip over most of them including one's that I have previously earned on - neoscrypt, as an example. When it gets to the end of the list, a window says that it has not successfully completed the benchmarking. I have run it again but the same thing keeps happening. I've had to go back to a previous version to be able to mine. I've attached the log file if that's any help.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/475056/log.txt)

**Comment by aaronsace** [comment]
1.7.x is utter trash. Just pull the release until fixed. Can't get most of the benchmarks to even run without BSOD.

**Comment by S74nk0** [comment]
Hi @FoxyBit. There was an issue with default parameters for AMD cards in **v1.7.1.1** you can check out the new version or wait for a new release (we will be releasing it tomorrow). The **v1.7.1.3** has **lbry** support that is the only advantage for now in the new release for AMD cards. If you are using **v1.7.1.3** with AMD rigs do not copy configs and start a new and everything should work. 

@aaronsace I suspect that you have AMD cards. Yes we have made major changes and included new sgminer. If you are using **v1.7.1.3** with a clean config and getting BSOD for every benchmark please tell us what cards are you using and what drivers.

**Comment by FoxyBit** [comment]
@S74nk0 Thanks. I have been using the newest version without any problems and have lbry currently mining :)
