### ISSUE TITLE
V1.7.1.1 missing start auto mining 

### ISSUE THREAD

**Issue by DrJackDaniel** [nicehash/NiceHashMiner-Archived#228]
I really want this feature in case of power loss when i'm away from my miners. Will this be added in future updates?

**Comment by nicehashdev** [comment]
Read here: https://github.com/nicehash/NiceHashMiner/issues/223

**Comment by felixbrucker** [comment]
#195

**Comment by felixbrucker** [comment]
also it seems 1.7.1.3 supports autostart
