### ISSUE TITLE
bugs - ver. driver and videocard

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#229]
I use NiceHashMiner 1.7.1.2. 

I have installed programs RealVNC remote access - for its work , it installs a virtual video driver  (VNC Mirror Driver):

![8](https://cloud.githubusercontent.com/assets/19841581/18592988/181c898c-7c42-11e6-9592-fc3b819803c8.jpg)

This error pops up when you start:

![5](https://cloud.githubusercontent.com/assets/19841581/18593057/5954615e-7c42-11e6-80c8-8f5bc1b83a64.jpg)

also in the program settings , I put not warn the driver version:

![7](https://cloud.githubusercontent.com/assets/19841581/18593112/97603a68-7c42-11e6-9ee2-c84f9d8e9e88.jpg)

but , when you start still pops up warning:

![6](https://cloud.githubusercontent.com/assets/19841581/18593145/bcb85ee4-7c42-11e6-90a5-ce1f53535652.jpg)

all with cars run the miner expects to press the OK button . That is, if the computer is rebooted autostart option is useless . In version 1.6.1.4 there were no errors .

Be the option - disable all the warnings ? Well, except for the initial

**Comment by S74nk0** [comment]
Hi @foxwarernd. We will fix this in the future release to disable all warnings.

**Comment by foxwarernd** [comment]
Thanks
