### ISSUE TITLE
NiceHashMiner_v1.2.3.0

### ISSUE THREAD

**Issue by mendoza1468** [nicehash/NiceHashMiner-Archived#23]
Slower Quark 700 K/hs with new version (Strange coz it look like it doesn't touch SP .exe file
Neoscrypt don't work in benchmark (Terminated)

If i download the new version NiceHashMiner_v1.2.3.0 quark is slower, but if i keep the last one and updated the .exe and bin its getting slower

**Comment by mendoza1468** [comment]
Im getting better hashrate from updating NiceHashMiner_v1.2.3.0 exe file on (Quark 32.780 mh/s from new version) and with update (exe file) it's almost like the previous version 33.65 mh/s

**Comment by theLosers106** [comment]
@mendoza1468 what Windows version are you using with what GPU? there should be no speed difference between the 2 releases except Neoscrypt on Maxwell GPUs. Could you run again the benchmark using NiceHashMiner v1.2.2.2 to confirm the speed as it might be because of something else.

**Comment by d57heinz** [comment]
some notable things i seen are..  New version doesn't take settings used from old config file. Sets my gpu back to stock settings when mining begins/benchmarks.  For whatever reason when i load the 1.2.3 the benchmark results for lyra2re disappear.. If i load the 1.2.2.2 the stats reappear in the benchmark without re running it.(maybe is not reading the config file correctly?). using 15.7.1 catalyst xfx hd7970 3 gb vid ram. 8gb system 4 core 2.8 ghz intel

**Comment by theLosers106** [comment]
@d57heinz yes.. the newer version has x15 algo included which will make the config file a bit different so the easiest solution would be to run the benchmark again..

**Comment by d57heinz** [comment]
@theLosers106 I have tried running the benchmark again.. When it gets to x15 the computer hangs and goes to the dreaded bsod.. And i get this error..   video_tdr_error  in atimpag.sys  then it gathers some info and reboots the pc  Ill have some time in about an hour.. ill try to delete the config and let it start fresh.. maybe that is the problem:)  Will get back asap

**Comment by theLosers106** [comment]
@d57heinz ok sure.. one more thing to try is running it directly from the command prompt and not by using the NiceHashMiner.. if that crashes too then I would recommend asking on the sgminer thread..

**Comment by d57heinz** [comment]
@theLosers106 Problem fixed on x15.. all i had to do was delete the config file and let the new version 1.2.3.0 make a new one as my old didnt have any config for x15.. may want to add that to the home page on the upgrade instructions.  one thing im still working on is i could globally set the gpu speed and by removing -auto gpu under the algos.. Not working this time.. will try to set gpu speed per amd algo and see if that will let me keep my gpu settings.  Would be nice if i could set the gpu and mem clock in external program and nicehash miner not override them. Best Regards Doug   Keep up the great work guys!

**Comment by d57heinz** [comment]
one more thing. does anyone have nist 5 working on amd hd7970. (hasnt worked yet for me since first release of nicehashminer)  Maybe isnt supported or is it my config error?

Best Regards
d57heinz

**Comment by theLosers106** [comment]
@d57heinz the reason it is not "working" is because unlike ccminer and cpuminer, sgminer does not have a benchmark option so it is actually mining on Nicehash with each algo and since Nist5 does not have any orders at the time of benchmarking then it will terminate the benchmark. This can be seen here (https://www.nicehash.com/index.jsp?p=stats&a=7&l=1)

**Comment by d57heinz** [comment]
@theLosers106 Thanks for all your help.. I appreciate it.. 
Best Regards 
Doug
