### ISSUE TITLE
Check profitability

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#233]
Check profitability in settings-devices/algorithms uploads a number way too high for lbra. I think the decimal is in the wrong place.

**Comment by S74nk0** [comment]
Hi @xadonxander. Lbry had around 17.3256 Paying rate at the time you opened this issue. Although post the log file if you can.

**Comment by xadonxander** [comment]
![nicehash](https://cloud.githubusercontent.com/assets/2667712/18615767/beb8e438-7d74-11e6-8a03-e48de897fe0e.jpg)

**Comment by xadonxander** [comment]
I know my 980ti's are good but they can't do the impossible. Somehow .184 GH/s + .184 GH/s = 367.17 GH/s. Looks like it is multiplied by 1000. I wish this computer would pay +113.43724531 BTC (+69457.63 USD) I would build a few more.

**Comment by S74nk0** [comment]
@xadonxander. You are right. This is a bug. We will fix it.
