### ISSUE TITLE
Been trying to download bin.zip for two days. 

### ISSUE THREAD

**Issue by Nickfost** [nicehash/NiceHashMiner-Archived#236]
So i have bad internet, I understand that. but there needs to be some resumable downloads here, whether you use IPFS or BT it doesnt matter. If we are going to have this program download it's binarys it's going to need to actually finished them. I let this thing sit at 70% complete downloading for a day. After that i restarted it hung at 30% all afternoon. 

I understand i'm not the majority here but it's irresponsible to make things that only work on really fast connections especially when it's not required.  

Try something like ipfs, I've got that server in my closet so every machine in my house can pull it from there once it gets it down once. 

Meanwhile i'm grabbing bin_1_7_1_0.ZIP hoping it hasnt been changed since then.

**Comment by Nickfost** [comment]
Of course 
![image](https://cloud.githubusercontent.com/assets/1572453/18612923/f561b626-7d2f-11e6-93f1-c522688a2051.png)

**Comment by Abdulsyukur** [comment]
Tidak bisa withdraw.. scam 

```
Pada Minggu, 18 September 2016 11:39, Nick Foster <notifications@github.com> menulis:
```

 Of course

**Comment by Nickfost** [comment]
![image](https://cloud.githubusercontent.com/assets/1572453/18618749/84092058-7db2-11e6-9bfc-a6e14099cdcc.png)
Stuck on this when i got up this afternoon

**Comment by S74nk0** [comment]
Hello @Nickfost. If you are having issues with internet speed. Try downloading [bin.zip](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/bin_1_7_1_3.zip) for the current latest release **v1.7.1.3**, if you are using Firefox you can try this plugin [DownThemAll!](https://addons.mozilla.org/en-US/firefox/addon/downthemall/). We will not be adding resume download feature for the next release but will probably fix it in the new upcoming releases. This workaround will be a viable solution for now. We are currently making major changes and at the moment this feature is not a high priority. Sorry for your inconvenience.
