### ISSUE TITLE
NiceHashMiner_v1.7.1.3 Can,t mine with the following algorithm,lyra2re,lyra2rev2.

### ISSUE THREAD

**Issue by Anonymous3556** [nicehash/NiceHashMiner-Archived#237]
Windows 10 x64
NET Framework 4.6.1 or a later update is already installed
Microsoft Visual C++ Redistributable 2013 x64  V12.030501 

Gtx 950 2G driver Version 372.70 

930M driver version 372.70

Algorithm,lyra2re,lyra2rev2 is working fine on NiceHashMiner_v1.6.1.4 ,1.7.1.1 ,1.7.1.2

**Comment by foxwarernd** [comment]
Most likely you will be asked to put the program log

**Comment by Anonymous3556** [comment]
sorry I have log and log.1 which one should i put here?

**Comment by Anonymous3556** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/478869/log.txt)

**Comment by Anonymous3556** [comment]
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/478871/log.1.txt)

**Comment by Anonymous3556** [comment]
these log file and log.1 are the graphics card MSI gtx 950 gaming 2g

**Comment by aaronsace** [comment]
AMD R9 290 and AMD RX 480 are also not working. DaggerHashimoto and Decred are the only GPU miners that work on 1.7.x. (1.6.x works perfectly)

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.
