### ISSUE TITLE
interface has broken

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#238]
Software version NiceHashMiner 1.7.1.3

Interface is working properly When you run the program . But after an hour or two it becomes somehow reduced : 

![12](https://cloud.githubusercontent.com/assets/19841581/18617632/c89bcc14-7ddc-11e6-8721-e1bb8b0a755f.jpg)

Perhaps matters - working with a PC is not directly but through RealVNC remote access program

**Comment by S74nk0** [comment]
This is fixed in the new release
