### ISSUE TITLE
Interface issue unable to view algorithms

### ISSUE THREAD

**Issue by nhm-gh-report** [nicehash/NiceHashMiner-Archived#239]
Unable to see algorithms in interface or select for that matter as they cant be seen. the program does seem to run and did add algorithm and when checking configs in file you can see the benchmark values it just is not visible in interface. Operating system is windows 10 
nicehashminer 1.7.1.3

![image](https://cloud.githubusercontent.com/assets/22282246/18619492/c92d4ae2-7db2-11e6-80ab-b3363a74db83.png)

**Comment by S74nk0** [comment]
Hi @nhm-gh-report. This is a major BUG that we are unable to reproduce on our testing machines (some setups work while others don't). We are working on a fix and if you would like to help us solve this problem I will post a patched version in this post. It would be helpful to get user feedback since we haven't found a way to reproduce this BUG.

**Comment by nhm-gh-report** [comment]
When a patch is available will test.

**Comment by S74nk0** [comment]
@nhm-gh-report here are patched versions. Try and report what patch fixed the problem. To try them just copy them in the NiceHashMiner v1.7.1.3 folder and run the .exe files. Thanks!
[NiceHashMiner_ALV_patched.zip](https://github.com/nicehash/NiceHashMiner/files/483651/NiceHashMiner_ALV_patched.zip)

**Comment by nhm-gh-report** [comment]
Interesting all three patches have worked and they all display same result. The default values shown are for the CPU and is not highlighted. If you highlight AMD OpenCL for graphics card I am able to see benchmark values.
Initial load Device Algorithm defaults to CPU (but CPU is not highlighted) 
![image](https://cloud.githubusercontent.com/assets/22282246/18740302/ef328736-805d-11e6-82d3-03e2172fb0bb.png)
Select Graphics Card AMD OpenCl Device
![image](https://cloud.githubusercontent.com/assets/22282246/18740361/324724b4-805e-11e6-91ba-bc5f4be17288.png)

Highlight CPU and goes back to CPU benchmark values with CPU highlighted.

... I then went back to original version and determined that the same will work if you highligt each of the device the algorithm and benchmark values will appear.

So in this case it seems that the initial load on the unpatched 1.7.1.3 is that the inital loading of graphical interface for algo is not populating so user does not think to highlight the device they wish to see the value for. 

Hope this helps. let me know if you need more details its late and had long day at work

**Comment by S74nk0** [comment]
Hi @nhm-gh-report. Your feedback was helpful. Thanks!
