### ISSUE TITLE
WhirlpoolX 4000-8000 MH/s o.O

### ISSUE THREAD

**Issue by forumaster** [nicehash/NiceHashMiner-Archived#24]
i have a strange bug with the new 1.2.3.0
here is screenshots:
![screenshot_17](https://cloud.githubusercontent.com/assets/16463429/12593935/dc57c776-c473-11e5-8811-f73783575361.png)
![screenshot_18](https://cloud.githubusercontent.com/assets/16463429/12593936/dc58f010-c473-11e5-95a8-72d817bc359f.png)
i have an acer aspire 5755G with a nvidia geforce gt 540m with windows 7

**Comment by theLosers106** [comment]
@albysprx did you removed the old config file first? this have solved some user's problem with the newer version. there should not be any difference between the new version and the old one AFAIK.

**Comment by forumaster** [comment]
yes, because benchmark was mixed so i deleted the old one and downloaded the full new version

**Comment by theLosers106** [comment]
@albysprx so I'm assuming that did not fix the problem?

**Comment by forumaster** [comment]
yes, but i don't have whirlpoolx in 1.2.2.2, maybe it's doing this because it's not supported for SM2.1?

**Comment by kenshirothefist** [comment]
True, whirlpoolx is not supported on SM2.1, therefore this algo has now been removed for SM2.1 devices in NHM. Fixed in the 1.2.3.1 release.
