### ISSUE TITLE
Possible feature

### ISSUE THREAD

**Issue by fefsf** [nicehash/NiceHashMiner-Archived#240]
Hello,

Would it be possible to add some kind of GPU crash detection within Nicehash Miner? Im always worried about one of my GPUs crashing for whatever reason and that one GPU bringing the while mining operation down with it (so im constantly checking up on my machines).  If the crash could be detected and the mining stop and auto started again that would be amazing

**Comment by S74nk0** [comment]
Hi @fefsf. This feature is currently implemented. If the miner is unresponsive for some reason NHM will detect it and restart the faulting miner. However there still can be rare cases where NHM will not be able to do this, for example less popular GPUs driver crashes (by user reports AMD GPUs are more likely to have problems), where there could be system crashes. We are of course looking for those solutions as well. I will close this issue. If you have any problems with Nicehash Miner let us know. Open a new issue and we will take it into account (**and fix it**).
