### ISSUE TITLE
v1.7.1.3 dont detect driver version correctly

### ISSUE THREAD

**Issue by Singman33** [nicehash/NiceHashMiner-Archived#242]
I've réinstalled my NVidia driver to fix the display of algorithms, that worked but when I rebooted, NicehashMiner tell me I dont have a driver version  > 36x.x while I have last one (372.70).

Log file : 

> [2016-09-20 07:32:00] [INFO] [NICEHASH] Starting up NiceHashMiner v1.7.1.3
> [2016-09-20 07:32:00] [INFO] [NICEHASH] Selected language: English
> [2016-09-20 07:32:01] [INFO] [NICEHASH] Total RAM: 8136MB
> [2016-09-20 07:32:01] [INFO] [NICEHASH] Page File Size: 32768MB
> [2016-09-20 07:32:03] [INFO] [ComputeDeviceQueryManager] 
> QueryVideoControllers: 
>     Win32_VideoController detected:
>         Name NVIDIA GeForce GTX 960
>         Description NVIDIA GeForce GTX 960
>         PNPDeviceID PCI\VEN_10DE&DEV_1401&SUBSYS_29623842&REV_A1\4&15E11016&0&0011
>         DriverVersion 21.21.13.7270
>         Status OK
> [2016-09-20 07:32:03] [INFO] [MinersManager] Creating MinerPathChecker miners
> [2016-09-20 07:32:03] [INFO] [AMD_OpenCL-MINER_ID(0)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 07:32:03] [INFO] [NVIDIA2.1-MINER_ID(1)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 07:32:03] [INFO] [NVIDIA3.x-MINER_ID(2)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 07:32:04] [INFO] [NVIDIA5.x-MINER_ID(3)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 07:32:04] [INFO] [NVIDIA6.x-MINER_ID(4)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 07:32:04] [INFO] [CPU0-MINER_ID(5)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 07:32:09] [INFO] [ComputeDeviceQueryManager] CudaDevicesDetection found no devices. CudaDevicesDetection returned: 
> [2016-09-20 07:32:14] [INFO] [ComputeDeviceQueryManager] 
> AMDOpenCLDeviceDetection found devices success:
> [2016-09-20 07:32:14] [INFO] [ComputeDeviceQueryManager] Skipping AMD device detection, settings set to disabled
> [2016-09-20 07:32:14] [INFO] [ComputeDeviceQueryManager] Cuda NVIDIA/CUDA device count BAD!!!
> [2016-09-20 07:32:14] [INFO] [ComputeDeviceQueryManager] AMD GPU device count GOOD
> [2016-09-20 07:32:50] [INFO] [NICEHASH] Version get
> [2016-09-20 07:32:51] [INFO] [NICEHASH] SMA get
> [2016-09-20 07:32:51] [INFO] [COINBASE] Bitcoin rate get
> [2016-09-20 07:32:52] [INFO] [COINBASE] Current Bitcoin rate: 609.10
> [2016-09-20 07:32:52] [INFO] [NICEHASH] Balance get
> [2016-09-20 07:32:52] [INFO] [NICEHASH] Setting environment variables
> [2016-09-20 07:32:52] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
> [2016-09-20 07:32:52] [INFO] [NICEHASH] Current DontShowUI value: 1
> [2016-09-20 07:32:55] [INFO] [NICEHASH] nvidiasetp0state all OK
> [2016-09-20 07:33:51] [INFO] [NICEHASH] SMA get
> [2016-09-20 07:33:53] [INFO] [NICEHASH] Balance get

**Comment by Singman33** [comment]
Close the NicehashMiner application, relaunch and everything is fine...
Really, that v1.7.1.3 introduced many many bugs, you should work more carefully with that application and raise the level of you QC.

Log.txt :

> [2016-09-20 10:38:21] [INFO] [NICEHASH] Starting up NiceHashMiner v1.7.1.3
> [2016-09-20 10:38:21] [INFO] [NICEHASH] Selected language: English
> [2016-09-20 10:38:21] [INFO] [NICEHASH] Total RAM: 8136MB
> [2016-09-20 10:38:21] [INFO] [NICEHASH] Page File Size: 32768MB
> [2016-09-20 10:38:21] [INFO] [ComputeDeviceQueryManager] 
> QueryVideoControllers: 
>     Win32_VideoController detected:
>         Name NVIDIA GeForce GTX 960
>         Description NVIDIA GeForce GTX 960
>         PNPDeviceID PCI\VEN_10DE&DEV_1401&SUBSYS_29623842&REV_A1\4&15E11016&0&0011
>         DriverVersion 21.21.13.7270
>         Status OK
> [2016-09-20 10:38:21] [INFO] [MinersManager] Creating MinerPathChecker miners
> [2016-09-20 10:38:21] [INFO] [AMD_OpenCL-MINER_ID(0)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 10:38:21] [INFO] [NVIDIA2.1-MINER_ID(1)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 10:38:21] [INFO] [NVIDIA3.x-MINER_ID(2)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 10:38:21] [INFO] [NVIDIA5.x-MINER_ID(3)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 10:38:21] [INFO] [NVIDIA6.x-MINER_ID(4)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 10:38:21] [INFO] [CPU0-MINER_ID(5)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
> [2016-09-20 10:38:23] [INFO] [ComputeDeviceQueryManager] 
> CudaDevicesDetection:
>     ADDED device:
>         ID: 0
>         NAME: EVGA GeForce GTX 960
>         VENDOR: EVGA
>         UUID: GPU-184cff4c-7dfe-6517-a0da-a85546240d35
>         SM: 5.2
>         MEMORY: 2147483648
>         ETHEREUM: YES
> [2016-09-20 10:38:23] [INFO] [ComputeDeviceQueryManager] 
> AMDOpenCLDeviceDetection found devices success:
>     Found devices for platform: NVIDIA CUDA
>         Device:
>             Device ID 0
>             Device NAME GeForce GTX 960
>             Device TYPE GPU
> [2016-09-20 10:38:23] [INFO] [ComputeDeviceQueryManager] Skipping AMD device detection, settings set to disabled
> [2016-09-20 10:38:23] [INFO] [ComputeDeviceQueryManager] Cuda NVIDIA/CUDA device count GOOD
> [2016-09-20 10:38:23] [INFO] [ComputeDeviceQueryManager] AMD GPU device count GOOD
> [2016-09-20 10:38:23] [INFO] [NICEHASH] Version get
> [2016-09-20 10:38:24] [INFO] [NICEHASH] SMA get
> [2016-09-20 10:38:24] [INFO] [COINBASE] Bitcoin rate get
> [2016-09-20 10:38:24] [INFO] [COINBASE] Current Bitcoin rate: 609.63
> [2016-09-20 10:38:24] [INFO] [NICEHASH] Balance get
> [2016-09-20 10:38:24] [INFO] [NICEHASH] Setting environment variables
> [2016-09-20 10:38:24] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
> [2016-09-20 10:38:24] [INFO] [NICEHASH] Current DontShowUI value: 1
> [2016-09-20 10:38:26] [INFO] [NICEHASH] nvidiasetp0state all OK
> [2016-09-20 10:39:20] [INFO] [NICEHASH] Entering idling state

**Comment by ODIN27** [comment]
Скачал программу,распаковал,при установлении пишет старые драйвера.У меня установлена новая Windows 10,скачал с сайта обновление драйверов.Программа всё равно пишет у вас старые драйвера,что делать?

**Comment by Singman33** [comment]
Everyone should speak russian now ? Back to '80s ?

**Comment by ODIN27** [comment]
?????

**Comment by Singman33** [comment]
Ok, I found a workaround. I'm using a program to delay the launch of NicehashMiner when booting the computer. With that delay, the program detect the correct driver version.
That bug should should only appear when the boot process is long and with many programs to launch, or maybe did you put a timeout when asking the version ?

**Comment by S74nk0** [comment]
@Singman33. In the new version you can disable showing this warning altogether with disabling **Show Driver Version Warning** from **v1.7.1.4**. If you are experiencing this issue only at system boot startups and driver re installations, then this issue is most likely related to NVIDIA OpenCL driver loading (we will test this with system boot up to reproduce the issue).
