### ISSUE TITLE
cryptonight 980ti SLI

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#244]
I had to disable cryptonight gpu mining due to driver crashing (Driver 21.21.13.7270) Windows 10 64 Pro. If I don't disable it, eventually windows blue screens and reboots.

**Comment by S74nk0** [comment]
If this is only a NVIDIA rig try disabling default optimizations or remove cryptonight ExtraLaunchParameters for all NVIDIA cards. cryptonight  with default optimizations can be problematic for some setups and cards. Have you added ExtraLaunchParameters  yourself maybe?

**Comment by S74nk0** [comment]
Hi @xadonxander. Did disabling default optimizations fixed the problem?

**Comment by xadonxander** [comment]
Yes, it was already done but the config was not saved.  I started a new topic about the config issue.
