### ISSUE TITLE
nicehash 1.7.1.4 config

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#245]
Initial setup is not saved. Every time the program is run I have to run benchmarks and input my bitcoin address. If I copy in the config folder from previous install the config is not changed when the program is restarted.

**Comment by S74nk0** [comment]
Hi @xadonxander. We haven't had any such issues with our testing machines. Have you ran NHM as Administrator user? If so it could be a permissions issue with file owners if the configs are owned by the Administrator user.

**Comment by xadonxander** [comment]
I first ran it without copying the configs into the folder and had to setup every time. Even with the config folder deleted nothing is being saved.

Apparently it doesn't like being run from the desktop any longer. I put it in in the root folder of my hard drive and it saves now.
