### ISSUE TITLE
ccminer_cryptonight crashing the Nvidia driver

### ISSUE THREAD

**Issue by SearchAndDestroy** [nicehash/NiceHashMiner-Archived#247]
I have an EVGA GeForce GTX 980 Ti and the ccminer_cryptonight is crashing the driver.
I tried the command line without the --bfactor=0 and it works fine.
I have attached the system info from the nvidia control panel

PS: Retested with the miner instead of a command line and it works when changing the ExtraLaunchParameters for CryptoNight for the card to --bfactor=6 instead of --bfactor=0
Removing the --bfactor=0 defaults to 0 (for Linux) instead of 6 for Windows

[NVIDIA System Information 09-22-2016 17-16-48.txt](https://github.com/nicehash/NiceHashMiner/files/487645/NVIDIA.System.Information.09-22-2016.17-16-48.txt)

**Comment by S74nk0** [comment]
The default optimization for this card is causing this issues. Removing the extra launch parameters will resolve this problem. In the future release NHM will not be setting optimizations for this card or other Ti SM5+ cards, since many users reported having this issue with this model.
