### ISSUE TITLE
ethminer.exe continues to mining w/out internet connection

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#249]
What about problem with ethminer working withoit internet connection too long? During this periodes of time on the wallet nothing to add. Therefore ethminer.exe must stops to mine when it's no internet connection.

**Comment by S74nk0** [comment]
No this has not been resolved yet. We will be speeding up ethminer for the future release. As for proxy checking we will have to check how to implement it in ethminer or NHM. We will try to fix this asap, probably with the next release

**Comment by UnclWish** [comment]
Thanks. I'am understand this. Will wait.

**Comment by nicehashdev** [comment]
Will be fixed with additional checks and options in next version that is coming out soon.
