### ISSUE TITLE
[BUG] [1.7.1.4] Intensity Setting gone, LessThreads everywhere

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#250]
after the upgrade from 1.7.1.3->1.7.1.4 the Setting for Intensity for GPUs is gone and is instead replaced by a greyed out "LessThreads", usually only visible in CPU section.

have set intensity for lyra2re for my nvidias with extralaunch for now (-i 18)

**Comment by S74nk0** [comment]
Hi @felixbrucker. We removed intensity parameters from settings and made a new per device **ExtraLaunchParameters** settings logic (not sure how to call it), instructions are [here](https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/README_ExtraLaunchParameters%20.md). All shorthand instruction flags are supported even though they are not listed at the moment (will update the wiki). So now the correct way to add extra options is like you already added, but keep in mind it is per device and not global as it used to be (pre v1.7.x) and pre v1.7.1.4 ran multiple miners if the settings were different (the new way fixes this). We will make sure to handle old settings correctly.

**Comment by felixbrucker** [comment]
ok thanks
