### ISSUE TITLE
v1.7.1.4: Radeon HD6570 not detected

### ISSUE THREAD

**Issue by kazso** [nicehash/NiceHashMiner-Archived#251]
Since version 1.7 my AMD Radeon HD6570 isn't detected anymore, I use Catalyst driver version 15.7.1 and Windows 7. Nicehashminer v1.6.1.4 still works fine with this card.
Is this card not supported anymore in the new Nicehasminer? Or is this only a bug?

[log.txt](https://github.com/nicehash/NiceHashMiner/files/488347/log.txt)

**Comment by S74nk0** [comment]
Hi @kazso. We will take a look into this. We will not be supporting non gaming NVIDIA cards. But this is a BUG, we have not intended to disable support for any AMD OpenCL cards at the moment.

**Comment by kazso** [comment]
I was able to fix this issue by changing the **ComputeDeviceQueryManager.cs** file in the source, and building the project.
In line 728 i had to change the wait time:
from: `const int waitTime = 5 * 1000; // 5seconds`
to: `const int waitTime = 6 * 1000; // 6seconds`

With 6 seconds my card is detected every time i start Nicehashminer.

**Comment by S74nk0** [comment]
@kazso thanks for reporting this. We will increase wait time in the next release.
