### ISSUE TITLE
nicehash give error check internet connection, and not responding 

### ISSUE THREAD

**Issue by piplhemant** [nicehash/NiceHashMiner-Archived#253]
first time i start mining in nicehash 20 days and suddenly show error not responding after that v again reinstall window 10 then run only 1 day again check internet connection and not responding 
i try all version of nicehash 
firewall disabled 
no antivirus
check server as mailed recd fr nicehash

Program Version: 1.7.1.4
OS Version: Windows 10 Enterprise build 10240
**Note**: My Internet connection is IPv6

**Comment by DaniellPlasmmer** [comment]
Did you try Windows 7?
Disabling uneeded services and Aero can give smoother mining than the current OS version.

**Comment by DaniellPlasmmer** [comment]
I have another idea: upgrade Windows 10 to its latest version.

**Comment by piplhemant** [comment]
no v dont try in window 7

already upgrade window 10 

can this need to upgrade ?

**Comment by DaniellPlasmmer** [comment]
Yes, the current version is 10240.
You have Threshold 2 and Redstones updates available.

**Comment by piplhemant** [comment]
Says "Downloading updates" and 0% status. My connection is 300KBps.
<img src="http://i.imgur.com/3zEck0I.png"/>

**Comment by DaniellPlasmmer** [comment]
As I see, the problems is in the OS instalation side. I suggest a new formatation with a new OS version. Windows 7 can be a good choice.

**Comment by S74nk0** [comment]
Hi @piplhemant. If I understand correctly you were already mining and now you can't because of connection problems? If the automatic miner download doesn't work you can download the miners manually (download link is provided in the release description). If you can send us the log file to see what could be the problem.

**Comment by NaitorStudios** [comment]
Here's how to fix it:
I've found out that NiceHash Miner (and some other programs) can't detect internet connection when IPv4 and IPv6 are enabled at the same time.
Disable one of them and the problem should go away. I think IPv6 is better, so I let it enabled and disabled IPv4, but I don't know if there's any drawbacks.

To disable just right click the network tray icon, then click Open Network and Sharing Center.
In the window that show up, look for "Connections: " right below HomeGroup, then click whats on the right side (should be your network name).
New window, Properties, you will see a list, check or uncheck IPv6 or IPv4, you must let at least one checked.

If this helped you, you may consider a donation, here's my Bitcoin Address:
1KZZX3xfo3PoavhWvVZJPjETTbCprwqBQa

I've recorded an improvised how to video:
https://www.youtube.com/watch?v=fnZ-eoGWt74

For the developers:
NiceHash Miner can't determine with IP version to use when both are enabled, hope in a future update it get fixed so we can use both at same time and people won't freak out with this issue.

**Comment by S74nk0** [comment]
Opened a new issue that references this and other related issues (#397).
