### ISSUE TITLE
benchmarck closes in the process

### ISSUE THREAD

**Issue by nandopais** [nicehash/NiceHashMiner-Archived#255]
hello I'm having trouble with "benchmarck" when I start it checks all the coins and the last he simply closes.

I have a core i3 3.20
4gb ddr3
1 x gygabite R9 380 4gb
1 x Sapphire R9 380 4gb
1 x powercolor r7 265 2gb

everything always worked perfectly in verssao 1.6.1.3, so I was moving to the 1.7.1.4 version that has given me such problems.

ok 
ok

**Comment by S74nk0** [comment]
Hello @nandopais. Please try the following and report if everything works or where do things brake:
- Try running **\bin\sgminer-5-5-0-general\runme.bat** manually from NHM v1.7.1.4 and report if there is any crash
- Try **disabling default optimizations** in NHM and try benchmarking
- Copy over the older [sgminer](https://github.com/nicehash/sgminer/releases/download/5.4.0/sgminer-5.4.0-nicehash-39-windows-amd64.zip) to **\bin\sgminer-5-5-0-general\** (this will not have **lbry** support) and report if benchmarking works.

Some AMD users are experiencing issues other are not. Your feedback would be helpful to resolve this issue.

You can also post the log file that might help.

**Comment by mirzagee** [comment]
I am facing same Issue on MSI R9 390x with NHM v.1.7.1.4 , tried all above methods but not working :(

**Comment by S74nk0** [comment]
Hi @mirzagee. Please try [NHM v1.6.1.4](https://github.com/nicehash/NiceHashMiner/releases/tag/1.6.1.4) and report if there is any issue with that version.

**Comment by mirzagee** [comment]
hello @S74nk0  just got it working , 
1.Copied old sgminer ( Previously it was not working in 1st attempt)
2.Benchmark only one GPU at Draganhashi
3.Rest of GPU's automatically get the 1st benchmark 
Started Mining and it is working from last 10 minutes without crash , i'll update you after crash interval

i am using windows 10 x64 Enterprise

**Comment by S74nk0** [comment]
Hi @mirzagee.

So old **sgminer** is working with **NHM v.1.7.1.4**? Or are you talking about **NHM v.1.6.1.4**?

**Comment by mirzagee** [comment]
@S74nk0  yes bro it is working with NHM v.1.7.1.4 , with the things ive mentioned above ,
for addition i don't have any problem on my RX 480 RiG with NHM v.1.7.1.4 (just few crash intervals )

**Comment by S74nk0** [comment]
@mirzagee Thank you very much for this response. Your feedback has been very helpful.

**Comment by mirzagee** [comment]
@S74nk0 thank you for giving me such easy miner :) i am totally new and just started throttle 20 days back :)

**Comment by nandopais** [comment]
S74nk0

I performed the test and gave me all worked. I deactivated standard optimizations and managed to make benchmarck.
now it's all ok.
I would like to give an opnion. if possible create a protection, so that it turn off when the plates have very high temperatures, or even an rpm control for cooler

I did some tests yesterday and realized that the temperature of my r9 290x reached 95graus
luckily I was close because it could have burned.
I'm turning off amd temperature control with it enabled my cooler so reach 30%

I used the MSI Afterburner 100% rpm cooler to lower the temperature a little of vga however not help much

**Comment by S74nk0** [comment]
Hi @nandopais. What Algorithm/coin were you mining? The AMD temperature control (sgminer) works for all algorithms except DaggerHashimoto (ethminer). More on this can be read [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters). We will try to add temperature protection but I am not sure in what version.

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
