### ISSUE TITLE
windows of nicehashminer little and blocked

### ISSUE THREAD

**Issue by laurence0000** [nicehash/NiceHashMiner-Archived#257]
windows of nicehashminer little and blocked . unable to resize the windows, impossible run the program.....
I ve tried with check compatibility of windows but no worked.

**Comment by laurence0000** [comment]
I used : Resize program: http://www.pcastuces.com/pratique/astuces/2793.htm  and its worked with this système

**Comment by nicehashdev** [comment]
We are aware of this issue; it will be fixed in next version.
