### ISSUE TITLE
benchmarks fail

### ISSUE THREAD

**Issue by Jyle1** [nicehash/NiceHashMiner-Archived#26]
Everytime I try to do a benchmark with my GPU (r9 390 Nitro), the tests are terminated one by one. I have no clue what to do to fix this. Plz help.

**Comment by theLosers106** [comment]
Have you tried running directly the runme.bat file in sgminer-general folder and see if that works ok?

**Comment by Jyle1** [comment]
This is what it did when I ran it:

http://i63.tinypic.com/mawk8n.jpg

**Comment by kenshirothefist** [comment]
Please try to set your own Bitcoin address instead of using the default one (https://www.nicehash.com/index.jsp?p=faq#faqs15) and then try again running the benchmark. Should work.

**Comment by Jyle1** [comment]
Oops. Well, I fixed that, and it still isn't working. Tests still get terminated. 

Here's a screeny: http://i66.tinypic.com/2cepykj.png

**Comment by kenshirothefist** [comment]
Try this:
- go to bin/sgminer-5.2.1-general
- delete **all** .bin files
- edit sgminer-fixed.conf file and replace the bitcoin address with your in the whole file (search&replace), then save and close the file
- now run runme.bat from the same directory

Post your results again. Thanks!

**Comment by Jyle1** [comment]
Here are the results: http://tinypic.com/r/2qb5d6w/9

**Comment by kenshirothefist** [comment]
Well, it seems that your computer is unable to connect to the mining pool. Try selecting different locations (Europe, USA) in the GUI and try run benchmark for X11 algorithm only.

Also, what is the result of this command:

telnet x11.eu.nicehash.com 3336

telnet x11.usa.nicehash.com 3336

**Comment by kenshirothefist** [comment]
This issue has been addressed in the latest Release 1.2.3.2 https://github.com/nicehash/NiceHashMiner/releases/tag/1.2.3.2

Please try this release and report if it works for you.

Thank you!
