### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by fryman91** [nicehash/NiceHashMiner-Archived#262]
Hi

There is a bug with UI, when CPU mine lyra2, there is wrong rate BTC/day showing in main window, while in "Benchmark" window everything is OK(look at screenshot)

![nicebug](https://cloud.githubusercontent.com/assets/22659603/19151930/78514eac-8be0-11e6-9bfd-0de75246a71c.jpg)

**Comment by S74nk0** [comment]
Hi @fryman91. We will take a look into this issue. Tell us are the stats **check my stats online!** reporting correct hash rate?

**Comment by fryman91** [comment]
Hi @S74nk0. Yeah, it's reporting 1.28 MH/s in average.

**Comment by S74nk0** [comment]
Closing issue. This is fixed in the new release.
