### ISSUE TITLE
Incorrectly Displays GPU Manufacturer

### ISSUE THREAD

**Issue by HeckuvaTester** [nicehash/NiceHashMiner-Archived#263]
At the home page of the miner, it incorrectly matches the manufacturers with the different GPUs. While the EVGA GTX 960 is correct, my 980Ti is from Gigabyte, while my other GTX 960 is from MSI.
![capture](https://cloud.githubusercontent.com/assets/16405027/19215182/8f595d42-8d5c-11e6-960b-99d135300423.PNG)

**Comment by S74nk0** [comment]
Hi @HeckuvaTester. This is highly unlikely to be the case, but just to be sure I would ask you to do the following:
- open **cmd (Command Prompt)** and "**cd NHM_PATH**" to the directory where NiceHash Miner is located (replace NHM_PATH with actual path/location)
- run the following command "**.\CudaDeviceDetection.exe > cudeDevsDump.txt**", this will create a **cudeDevsDump.txt** file
- send us **cudeDevsDump.txt** file so we can see if VendorIDs/ManufacturerIDs are mapped correctly.

**Comment by HeckuvaTester** [comment]
[cudaDevsDump.txt](https://github.com/nicehash/NiceHashMiner/files/518365/cudaDevsDump.txt)

**Comment by HeckuvaTester** [comment]
So you know, I have my MSI 960 in the top PCIe slot, then my EVGA 960 in the middle PCIe slot, the my Gigabyte 980Ti in the bottom slot. However, I use the 980Ti as my primary display device. When I run the versions of ccminer that support the "-n" option to list CUDA devices, my 980Ti is always listed as GPU #0, then my two 960's. In the dump file, it similarly lists the 980Ti as the first card, but the manufacturer names of the cards are in the order that they are in my computer, from top to bottom. I seems to me that while it ranks the GPU's with the primary display driver first, then ranking by order in the system, the manufacturers are associated with the GPU number solely by order.

**Comment by S74nk0** [comment]
Hi @HeckuvaTester. There is indeed a BUG in our CudaDeviceDetection. Cuda and Nvlm indexes order differ and this is causing the problem. Thanks for pointing this out as it isn't a minor issue. We will fix this in the upcoming release.

**Comment by S74nk0** [comment]
This bug is now fixed with the latest release.
