### ISSUE TITLE
[FEATURE] Disable Primary GPU when in use

### ISSUE THREAD

**Issue by fefsf** [nicehash/NiceHashMiner-Archived#264]
Hello,

Would it be possible to have nicehash stop mining on the Primary GPU when the PC is in use instead of disabling all of them?

**Comment by S74nk0** [comment]
Hi @fefsf. Can you give us some more detail? You want NHM to disable the primary GPU when other programs are using it?

**Comment by fefsf** [comment]
Lets say a PC has 3 GPU's. The top slot GPU is used for everything, meaning its used to displays the operating system and play games ect. So I would call this the primary GPU.  Now, I think it would be a nice feature if NHM only stops mining on this GPU when the PC is in use, instead of how it is now where NHM will stop mining on all GPUs. There really is no reason to stop mining on the non-primary GPU's since the user doesn't interact with them.  If a user wanted to stop all they could also click stop in the main window.

**Comment by Nickfost** [comment]
Great idea!

**Comment by aaronsace** [comment]
This is the exact annoyance I have. I stop it, untick the primary GPU and CPU then start it. Once finished with the PC, I have to remember to enable them all again.

**Comment by S74nk0** [comment]
Closing issue. Opened a new issue related to **Mining when Idle Feature update** that coveres this issue as well. Post all new suggestions or related problems to the new opened issue here #398
