### ISSUE TITLE
NiceHash attempting to mine 2x GPU's with multiple algorithms concurrently

### ISSUE THREAD

**Issue by jimmyweee** [nicehash/NiceHashMiner-Archived#265]
When mining with two GPU's (nVidia GTX 1070) and CPU, NiceHash will attempt to open a third mining window while mining DaggerHashimoto in addition to another algorithm (i.e. one window mining Lbry using both GPU, second window mining DaggerHashimoto with one or two GPU). Two GPU windows will conflict and attempt to share GPU resources, significantly reducing output. Temporary fix is to disable DaggerHashimoto.

**Comment by S74nk0** [comment]
Hi @jimmyweee. When NHM is mining DaggerHashimoto and switches to another coin/Algorithm it keeps the miner (ethminer process) still opened so when DaggerHashimoto is most profitable again it skips generating DAG. There are 4 options for generating DAG (Dag Load Mode in Settings/Advanced), singlekeep is the default and optimizes DAG generation (and keeps DAG in memory). 
Now if both miner windows are mining at the same time (ethminer.exe - DaggerHashimoto and ccminer_tpruvot.exe - Lbry) then this is clearly a BUG. If you can please send the log files under the **logs** folder (don't paste the logs send the files), to see what is going on. If there are two miner windows opened and only one is mining then this is not a BUG. To clear GPU resources you can change Dag Load Mode in settings.

`significantly reducing output`
By how much does the hash-rate drop?

**Comment by jimmyweee** [comment]
Hello @S74nk0! I've attached the log in use when I noticed the phenomenon. I've resumed mining DaggerHashimoto in an attempt to replicate what I saw yesterday; at the moment, each GPU is mining separately without issue.

When ccminer_tpruvot.exe was mining Lbry at the same time as ethminer was mining DaggerHashimoto, Lbry hash rates fell from ~280MH to a number I can't quite recall, but was in the KH range.

[log.-.Copy.txt](https://github.com/nicehash/NiceHashMiner/files/518279/log.-.Copy.txt)

**Comment by jimmyweee** [comment]
The phenomenon occurred again, this time leaving two stale windows mining Lbry on the same GPU; both had to be forced closed, "Stop" from within NiceHash did not work. Log and screenshot attached.

[log - Copy.txt](https://github.com/nicehash/NiceHashMiner/files/525852/log.-.Copy.txt)
![overlap](https://cloud.githubusercontent.com/assets/22719645/19331868/352475d0-90b5-11e6-9e45-129192e7aa1d.png)

**Comment by technyne** [comment]
I am having the same issue.  Im running 6 x GTX1070's and everything will start up as it should and then over time when I check on it it will be mining 3 algos at once with a significant decrease in performance (obviously) over all the algos as well as the obvious drop in profitability.  It eventually leads to a crash of the whole rig after a few hours. I don't have a screenshot as when i logged in to get one NHM had crashed.

**Comment by S74nk0** [comment]
Hi all! As a temporary workaround I would suggest to do the following. In the benchmarks or settings form right click on the GPU and a context menu will appear with **Copy Settings From (Benchmarks, algorithm parameters)** from here on you will be able to copy settings from one card to another. This makes sense to do with same GPU models as the performance/profit differences are negligible and mining will be more stable (we will add this to make an average of benchmarks with the same GPUs, this used to be the case but was removed). This should be a temporary fix. Here is a screenshot how the menu looks:
![copy benchmarks](https://cloud.githubusercontent.com/assets/1517233/19649365/d678bd7a-9a05-11e6-9640-628793087bd0.PNG)

@technyne please post the log file to see what miners were called at the same time (was ethminer mining?).

**Comment by technyne** [comment]
I have set all my GPUs to copy settings from GPU1 per your instructions, it appears that due to the fact that I have multiple brands of 1070's that didn't auto apply for all of them. It did seem to have auto copied settings between the same brand cards which is nice.  I will post the log but what I assume was happening was it was trying to mine what was most profitable for each individual card causing the LBRY, Lyra2REv2, and dagger-hashimoto miners to be opened over time.  I will test and let you know if anything changes.  Thanks for the help.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/548729/log.txt)

**Comment by jimmyweee** [comment]
Running 1.7.3.3 and the problem hasn't resurfaced. My two GPU's have individual benchmarks (I have not copied results from one to the other as you suggested) and has been running fine for a few days now. Thanks @S74nk0 for looking into it.

**Comment by zoogaezee** [comment]
My GPU's are both using DaggerHashimoto-  Ethminer , I have a GTX 1070 and GTX 1080 (2 cards total)
Now.. when I mine Ethminer both GPU's - MHash/s are added together and displayed as one reading. Is there any way to separate the Hash-rate reading on Ethminer/ GPU cards so I can see the hash-rate of both of the cards instead of one hashrate added together. I want to be able to see the ETHminer hash-rate of each card individually. Please let me know thanks.

**Comment by Kacktusjack** [comment]
I'm running a 6 card rig with GTX1080's. I'm coming across the same thing with Nicehash running 2 algo's at the same time. This is my fist set up and some friends are suggesting that running 2 algorithms isn't normal.. Secondly, I cant seem to get much more then about 24hrs of solid mining without some sort of crash or freeze in the system.. I'v stopped Windows from updating and have stock clocks on my cards so I'm at a loss as to what's causing the issue. Here is the latest log file. 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/1671831/log.txt)

**Comment by Kacktusjack** [comment]
Here is an example of multi algorithms being hashed. I also seem to have issues getting my NMH to display the current algorithm or algorithms its hashing. My wallet is receiving funds but hard to keep track of what's happening with no information being displayed. 
[Doc1.docx](https://github.com/nicehash/NiceHashMiner/files/1671842/Doc1.docx)
