### ISSUE TITLE
[Feature Request] Autoscale BTC reward indicators

### ISSUE THREAD

**Issue by EdoaLive** [nicehash/NiceHashMiner-Archived#27]
Hello,
As per title, it would be nice if the reward in BTC would auto-scale to mBTC to be more readable for everyone.
(Who the hell have a reward of more than 1BTC per day??)

Thanks
P.S. If I have time, I'd like to try to fork and do this myself, but I don't know when. In the meantime, this is my suggestion.

**Comment by theLosers106** [comment]
@Edoa That is a nice feature to have.. will consider it.. thanks (:

**Comment by apprehensivemom** [comment]
well... would be also nice to set an option to have the reward unit in BTC, mBTC, uBTC, and let the user choose which one to use (like Bitcoin CORE)

**Comment by kenshirothefist** [comment]
Version 1.3.0.0 brings autoscaling of reward indicators.
