### ISSUE TITLE
Sapphire RX 480 nitro+ 8giga OC :work fine :-) 

### ISSUE THREAD

**Issue by laurence0000** [nicehash/NiceHashMiner-Archived#270]
Just for says that my sapphire radeon rx480 8g nitro+ oc work now fine in nicehashminer.

Thanks for the job!!

I ll do a little donation for that.

**Comment by PhoenixAdageyudi** [comment]
What kind of.hash rate your.pulling with that thing? .. My 2 480 gbget around 19-21mhs ethereum dagger

**Comment by laurence0000** [comment]
With one rx480nitro+ 8gigaoc i have 23.75mh/s on etherminer dagger
![capture4](https://cloud.githubusercontent.com/assets/22505851/19305791/e39e26c6-9072-11e6-8672-7352206c2d1c.PNG)

**Comment by aaronsace** [comment]
Use Claymore's Dual Ethereum+Decred Miner. I get 26-27mh/s Ethereum plus a bonus 700-800hm/s Decred.
