### ISSUE TITLE
multiple  gpu  3 nvidia gtx 970 4giga. Possible?

### ISSUE THREAD

**Issue by laurence0000** [nicehash/NiceHashMiner-Archived#271]
i have a question: we can mine with nicehashminer with 3 multiple gpu nvidia gtx970 4giga as a rig? With my computer with riser and pcie 1X connection?

Nicehashminer will concentrate the power of calcul of the 3 cards? or it's as miner with 3 gpu séparate as 3 computer? Excuse my english is bad . Do you understand?
Nicehash will do the same work than a rig with only sgminer, ethminer an other programme.?
If yes where find the documentation for configurate this?
Thanks.

**Comment by nicehashdev** [comment]
Yes, NiceHash Miner supports multiple GPUs, different vendors, models, you can even mix NVIDIA and AMD together and it will properly detect everything and launch best possible mining combination that earns the most.
