### ISSUE TITLE
[UPSTREAM BUG] ccminer neoscrypt on multiple GPUs

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#272]
this issue is not directly NHM related but regarding the ccminer neoscrypt miner bundled, in previous versions (iirc 1.6. something) neoscrypt would more or less perform equal, independent of the GPU count. I just (by accident) noticed the benchmarked 800-900kh/s on a single card turn into 630kh/s when using multiple GPUs. This does not occur on other algos like lbry or lyra2rev2, anybody noticed the same or knows a fix?

**Comment by phieti** [comment]
Try delist CPU from mining, i noticed poor neoscrypt perfomance when CPU loaded

**Comment by felixbrucker** [comment]
im running my cpu mining externally with only one core used (dual core celeron) so i suppose there is no easy way of automating the stopping of cpu mining when neoscrypt is run 

stopping the cpuminer indeed fixed it, and thats because the neoscrypt miner takes 25% cpu, while "system" process increases to 45%, msi afterburner also increases to 10%, total cpu load is 86%

now each gpu gives 950 kh/s, is there some bugfix upstream that might fix this high sytsem load when mining ?

**Comment by S74nk0** [comment]
Closing issue...

**Comment by felixbrucker** [comment]
so i suppose this bug didnt get fixed upstream

**Comment by S74nk0** [comment]
@felixbrucker no the upstream is not fixed. We can make a workaround in NHM though to disable CPU when mining **neoscrypt**. I suppose that this would fix the problem?

**Comment by felixbrucker** [comment]
no need, its not worth your time, additionally im cpu mining externally (not with NHM) so this wouldnt work for me

**Comment by S74nk0** [comment]
@felixbrucker ok thanks for the feedback. So far your feedback was always helpful :).
Closing issue...
