### ISSUE TITLE
Sapphire nitro+ rx 470 4gb

### ISSUE THREAD

**Issue by bhanu545** [nicehash/NiceHashMiner-Archived#273]
System crashes as soon as i start the benchmark. If i open the latest NHM it says to enable atleast 1 miner.
I followed the posts of https://github.com/nicehash/NiceHashMiner/issues/258 as it seems very same like mine but never worked out for me.

**Comment by bhanu545** [comment]
I replaced the atikmpag.sys file and i could benchmark 1 gpu only for dagger hashimoto and could mine in demo mode. do you think i am all set now?
I had my system crashing for 15-20 times and i was very frustrated to use nicehashminer again.

**Comment by bhanu545** [comment]
so i was able to test all my miners in Daggerhashimoto only disabling all other algorithms after replacing with the patch given by https://github.com/S74nk0.
I enabled scrypt mode to see benchmark and again whole system crash. whats wrong with this NHM?

**Comment by S74nk0** [comment]
Hi @bhanu545. If you are using 1.7.2.0 version there is no need to use any patches as they are included in this release. There were many users that are reporting problems with AMD Sapphire vendor GPUs. We are still working out what could be the problem. For now DaggerHashimoto should work without problems, so use only that until we find a solution. This could be a driver related problem, new sgminer problem, NHM problem or some combination that only occurs on AMD Sapphire cards.

**Comment by dakky221** [comment]
I'm using XFX RX 480 RS 8GB (Samsung memory) with latest 1.7.2.0 and latest Crimson 16.9.2 and benchmarking restarts the PC. DaggerHashimoto works fine. So it affects XFX as well, not only Sapphire.

**Comment by wikako** [comment]
After installation and starting the benchmark fans got stuck on 20%. 

Cant get them to go at anything else apart from 20% speed now. GPU will clock down when reaching maximum temperature instead of raising fanspeeds. I even tried updating drivers, nothing works. 

What happend?

2x RX480

**Comment by S74nk0** [comment]
Hi all! Please try this [potential fix](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/NiceHashMiner_v1.7.2.0_Potential_AMD_Fix.zip).

**Comment by dakky221** [comment]
Nope, the "potential" fix doesn't work... just by clicking Start on benchmark with standard settings, the computer freezes.... or restarts... Stanko I've tried to reach you via FB, I can give you teamviewer access to my rig so please answer there as well. We can speed up the process that way.

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
