### ISSUE TITLE
bin\ccminer_nanashi.exe unspecified launch failure

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner-Archived#276]
on error miners bin\ccminer_nanashi.exe, NiceHashMiner not restart it, and a miner working indefinitely or switch algorithms

Console log on bin\ccminer_nanashi.exe : 
`[2016-10-22 10:10:15] GPU #0: unspecified launch failure
[2016-10-22 10:10:15] GPU #0: Gigabyte GTX 1070, 30.54 GH/s
[2016-10-22 10:10:15] GPU #0: unspecified launch failure
[2016-10-22 10:10:15] GPU #1: Gigabyte GTX 1070, 25.28 GH/s
[2016-10-22 10:10:15] GPU #1: unspecified launch failure
[2016-10-22 10:10:15] GPU #1: Gigabyte GTX 1070, 43.12 GH/s
[2016-10-22 10:10:15] GPU #0: Gigabyte GTX 1070, 36.65 GH/s
[2016-10-22 10:10:15] GPU #0: unspecified launch failure
[2016-10-22 10:10:15] GPU #1: unspecified launch failure
[2016-10-22 10:10:15] GPU #1: Gigabyte GTX 1070, 43.12 GH/s
[2016-10-22 10:10:15] GPU #1: unspecified launch failure
[2016-10-22 10:10:15] GPU #0: Gigabyte GTX 1070, 37.91 GH/s
[2016-10-22 10:10:15] GPU #0: unspecified launch failure
[2016-10-22 10:10:15] GPU #1: Gigabyte GTX 1070, 42.29 GH/s
[2016-10-22 10:10:15] GPU #1: unspecified launch failure
[2016-10-22 10:10:15] GPU #0: Gigabyte GTX 1070, 39.98 GH/s
[2016-10-22 10:10:15] GPU #0: unspecified launch failure
[2016-10-22 10:10:15] GPU #1: Gigabyte GTX 1070, 44.88 GH/s
[2016-10-22 10:10:16] GPU #1: unspecified launch failure
[2016-10-22 10:10:16] GPU #0: Gigabyte GTX 1070, 37.91 GH/s
[2016-10-22 10:10:16] GPU #0: unspecified launch failure
[2016-10-22 10:10:16] GPU #0: Gigabyte GTX 1070, 47.81 GH/s
[2016-10-22 10:10:16] GPU #0: unspecified launch failure
[2016-10-22 10:10:16] GPU #1: Gigabyte GTX 1070, 34.36 GH/s
[2016-10-22 10:10:16] GPU #1: unspecified launch failure
[2016-10-22 10:10:16] GPU #1: Gigabyte GTX 1070, 9214.22 MH/s
[2016-10-22 10:10:16] GPU #1: unspecified launch failure
[2016-10-22 10:10:16] GPU #0: Gigabyte GTX 1070, 39.27 GH/s
`

Log NiceHashMiner : 
`[2016-10-22 10:09:53] [INFO] [NICEHASH] SMA get
[2016-10-22 10:10:48] [INFO] [NICEHASH] Balance get
[2016-10-22 10:10:53] [INFO] [NICEHASH] SMA get
[2016-10-22 10:11:02] [INFO] [MinersManager] Current device profits:
    Profits for GPU-a51bfb34-0859-650f-8f87-ff16e93c819a (Gigabyte GeForce GTX 1070 #1):
        x13             :   PROFIT = 0.000149998560  (DISABLED, SPEED =   -10960000.000, NHSMA = 0.013686000000)
        keccak          :   PROFIT = 0.001611080800  (DISABLED, SPEED =  -788200000.000, NHSMA = 0.002044000000)
        x15             :   PROFIT = 0.000138599538  (DISABLED, SPEED =    -9628980.000, NHSMA = 0.014394000000)
        nist5           :   PROFIT = 0.001315880750  (DISABLED, SPEED =   -45730000.000, NHSMA = 0.028775000000)
        neoscrypt       :   PROFIT = 0.001153058376  (DISABLED, SPEED =     -821000.000, NHSMA = 1.404456000000)
        whirlpoolx      :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -352990000.000, NHSMA = 0.000000000000)
        qubit           :   PROFIT = 0.000299866800  (DISABLED, SPEED =   -22640000.000, NHSMA = 0.013245000000)
        quark           :   PROFIT = 0.000496222240  (DISABLED, SPEED =   -28690000.000, NHSMA = 0.017296000000)
        lyra2re         :   PROFIT = 0.001270668172  (DISABLED, SPEED =    -5505280.000, NHSMA = 0.230809000000)
        lyra2rev2       :   PROFIT = 0.002195336250  (ENABLED , SPEED =    39150000.000, NHSMA = 0.056075000000)
        blake256r8      :   PROFIT = 0.000000883686  (DISABLED, SPEED =  -4418430000.000, NHSMA = 0.000000200000)
        blake256r14     :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -2646760000.000, NHSMA = 0.000000000000)
        blake256r8vnl   :   PROFIT = 0.001462884114  (DISABLED, SPEED =  -4571370000.000, NHSMA = 0.000320010000)
        daggerhashimoto     :   PROFIT = 0.002037600311  (DISABLED, SPEED =   -28101731.000, NHSMA = 0.072508000000)
        decred          :   PROFIT = 0.001228780854  (DISABLED, SPEED =  -2783700000.000, NHSMA = 0.000441420000)
        cryptonight     :   PROFIT = 0.001343235407  (DISABLED, SPEED =        -595.500, NHSMA = 2255.643000000000)
        lbry            :   PROFIT = 0.002255227488  (DISABLED, SPEED =  -297800000.000, NHSMA = 0.007572960000)
        MOST PROFITABLE (ENABLED) ALGO: lyra2rev2, PROFIT: 0.002195336250

```
Profits for GPU-69cc43d0-8db6-a104-c05c-ca2a23415e01 (Gigabyte GeForce GTX 1070 #2):
    x13             :   PROFIT = 0.000149998560  (DISABLED, SPEED =   -10960000.000, NHSMA = 0.013686000000)
    keccak          :   PROFIT = 0.001611080800  (DISABLED, SPEED =  -788200000.000, NHSMA = 0.002044000000)
    x15             :   PROFIT = 0.000138599538  (DISABLED, SPEED =    -9628980.000, NHSMA = 0.014394000000)
    nist5           :   PROFIT = 0.001315880750  (DISABLED, SPEED =   -45730000.000, NHSMA = 0.028775000000)
    neoscrypt       :   PROFIT = 0.001153058376  (DISABLED, SPEED =     -821000.000, NHSMA = 1.404456000000)
    whirlpoolx      :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -352990000.000, NHSMA = 0.000000000000)
    qubit           :   PROFIT = 0.000299866800  (DISABLED, SPEED =   -22640000.000, NHSMA = 0.013245000000)
    quark           :   PROFIT = 0.000496222240  (DISABLED, SPEED =   -28690000.000, NHSMA = 0.017296000000)
    lyra2re         :   PROFIT = 0.001270668172  (DISABLED, SPEED =    -5505280.000, NHSMA = 0.230809000000)
    lyra2rev2       :   PROFIT = 0.002195336250  (ENABLED , SPEED =    39150000.000, NHSMA = 0.056075000000)
    blake256r8      :   PROFIT = 0.000000883686  (DISABLED, SPEED =  -4418430000.000, NHSMA = 0.000000200000)
    blake256r14     :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -2646760000.000, NHSMA = 0.000000000000)
    blake256r8vnl   :   PROFIT = 0.001462884114  (DISABLED, SPEED =  -4571370000.000, NHSMA = 0.000320010000)
    daggerhashimoto     :   PROFIT = 0.002037600311  (DISABLED, SPEED =   -28101731.000, NHSMA = 0.072508000000)
    decred          :   PROFIT = 0.001228780854  (DISABLED, SPEED =  -2783700000.000, NHSMA = 0.000441420000)
    cryptonight     :   PROFIT = 0.001343235407  (DISABLED, SPEED =        -595.500, NHSMA = 2255.643000000000)
    lbry            :   PROFIT = 0.002255227488  (DISABLED, SPEED =  -297800000.000, NHSMA = 0.007572960000)
    MOST PROFITABLE (ENABLED) ALGO: lyra2rev2, PROFIT: 0.002195336250
```

[2016-10-22 10:11:02] [INFO] [MinersManager] Current Global profit: 2.77231452 USD/Day
[2016-10-22 10:11:02] [INFO] [MinersManager] Current Global profit: IS PROFITABLE MinProfit mine always regardless of profit
[2016-10-22 10:11:49] [INFO] [NICEHASH] Balance get
[2016-10-22 10:11:53] [INFO] [NICEHASH] SMA get
[2016-10-22 10:12:44] [INFO] [MinersManager] Current device profits:
    Profits for GPU-a51bfb34-0859-650f-8f87-ff16e93c819a (Gigabyte GeForce GTX 1070 #1):
        x13             :   PROFIT = 0.000152453600  (DISABLED, SPEED =   -10960000.000, NHSMA = 0.013910000000)
        keccak          :   PROFIT = 0.001610292600  (DISABLED, SPEED =  -788200000.000, NHSMA = 0.002043000000)
        x15             :   PROFIT = 0.000138792118  (DISABLED, SPEED =    -9628980.000, NHSMA = 0.014414000000)
        nist5           :   PROFIT = 0.001326673030  (DISABLED, SPEED =   -45730000.000, NHSMA = 0.029011000000)
        neoscrypt       :   PROFIT = 0.001165446445  (DISABLED, SPEED =     -821000.000, NHSMA = 1.419545000000)
        whirlpoolx      :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -352990000.000, NHSMA = 0.000000000000)
        qubit           :   PROFIT = 0.000326808400  (DISABLED, SPEED =   -22640000.000, NHSMA = 0.014435000000)
        quark           :   PROFIT = 0.000494845120  (DISABLED, SPEED =   -28690000.000, NHSMA = 0.017248000000)
        lyra2re         :   PROFIT = 0.001270525034  (DISABLED, SPEED =    -5505280.000, NHSMA = 0.230783000000)
        lyra2rev2       :   PROFIT = 0.002189542050  (ENABLED , SPEED =    39150000.000, NHSMA = 0.055927000000)
        blake256r8      :   PROFIT = 0.000000883686  (DISABLED, SPEED =  -4418430000.000, NHSMA = 0.000000200000)
        blake256r14     :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -2646760000.000, NHSMA = 0.000000000000)
        blake256r8vnl   :   PROFIT = 0.001462884114  (DISABLED, SPEED =  -4571370000.000, NHSMA = 0.000320010000)
        daggerhashimoto     :   PROFIT = 0.002039342619  (DISABLED, SPEED =   -28101731.000, NHSMA = 0.072570000000)
        decred          :   PROFIT = 0.001230311889  (DISABLED, SPEED =  -2783700000.000, NHSMA = 0.000441970000)
        cryptonight     :   PROFIT = 0.001343029364  (DISABLED, SPEED =        -595.500, NHSMA = 2255.297000000000)
        lbry            :   PROFIT = 0.002243124896  (DISABLED, SPEED =  -297800000.000, NHSMA = 0.007532320000)
        MOST PROFITABLE (ENABLED) ALGO: lyra2rev2, PROFIT: 0.002189542050

```
Profits for GPU-69cc43d0-8db6-a104-c05c-ca2a23415e01 (Gigabyte GeForce GTX 1070 #2):
    x13             :   PROFIT = 0.000152453600  (DISABLED, SPEED =   -10960000.000, NHSMA = 0.013910000000)
    keccak          :   PROFIT = 0.001610292600  (DISABLED, SPEED =  -788200000.000, NHSMA = 0.002043000000)
    x15             :   PROFIT = 0.000138792118  (DISABLED, SPEED =    -9628980.000, NHSMA = 0.014414000000)
    nist5           :   PROFIT = 0.001326673030  (DISABLED, SPEED =   -45730000.000, NHSMA = 0.029011000000)
    neoscrypt       :   PROFIT = 0.001165446445  (DISABLED, SPEED =     -821000.000, NHSMA = 1.419545000000)
    whirlpoolx      :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -352990000.000, NHSMA = 0.000000000000)
    qubit           :   PROFIT = 0.000326808400  (DISABLED, SPEED =   -22640000.000, NHSMA = 0.014435000000)
    quark           :   PROFIT = 0.000494845120  (DISABLED, SPEED =   -28690000.000, NHSMA = 0.017248000000)
    lyra2re         :   PROFIT = 0.001270525034  (DISABLED, SPEED =    -5505280.000, NHSMA = 0.230783000000)
    lyra2rev2       :   PROFIT = 0.002189542050  (ENABLED , SPEED =    39150000.000, NHSMA = 0.055927000000)
    blake256r8      :   PROFIT = 0.000000883686  (DISABLED, SPEED =  -4418430000.000, NHSMA = 0.000000200000)
    blake256r14     :   PROFIT = 0.000000000000  (DISABLED, SPEED =  -2646760000.000, NHSMA = 0.000000000000)
    blake256r8vnl   :   PROFIT = 0.001462884114  (DISABLED, SPEED =  -4571370000.000, NHSMA = 0.000320010000)
    daggerhashimoto     :   PROFIT = 0.002039342619  (DISABLED, SPEED =   -28101731.000, NHSMA = 0.072570000000)
    decred          :   PROFIT = 0.001230311889  (DISABLED, SPEED =  -2783700000.000, NHSMA = 0.000441970000)
    cryptonight     :   PROFIT = 0.001343029364  (DISABLED, SPEED =        -595.500, NHSMA = 2255.297000000000)
    lbry            :   PROFIT = 0.002243124896  (DISABLED, SPEED =  -297800000.000, NHSMA = 0.007532320000)
    MOST PROFITABLE (ENABLED) ALGO: lyra2rev2, PROFIT: 0.002189542050
```

[2016-10-22 10:12:44] [INFO] [MinersManager] Current Global profit: 2.76499749 USD/Day
[2016-10-22 10:12:44] [INFO] [MinersManager] Current Global profit: IS PROFITABLE MinProfit mine always regardless of profit
[2016-10-22 10:12:50] [INFO] [NICEHASH] Balance get
[2016-10-22 10:12:53] [INFO] [NICEHASH] SMA get
[2016-10-22 10:13:51] [INFO] [NICEHASH] Balance get
[2016-10-22 10:13:53] [INFO] [NICEHASH] SMA get
`

**Comment by felixbrucker** [comment]
is your mainboard chipset a z170 series?

**Comment by Kayfolom** [comment]
No, Gigabyte 970A-DS3

**Comment by S74nk0** [comment]
@Kayfolom try lowering the intensity (I am not sure if this is related to intensity but give it a try, instructions can be found [here](https://github.com/nicehash/NiceHashMiner/issues/284#issuecomment-263567845) as it seems to be a similar problem). If lowering the intensity fixes the problem then close this issue.

**Comment by S74nk0** [comment]
Closing issue... Please reopen the issue if the previous suggestion for lowering intensity did not fix the problem.
