### ISSUE TITLE
[BUG] CudaDeviceDetection.exe failure

### ISSUE THREAD

**Issue by jarredwalton** [nicehash/NiceHashMiner-Archived#277]
I'm not sure what's going wrong with this PC, but I recently uninstalled all Nvidia and AMD drivers and then did a clean install of the new 373.57 Nvidia drivers. Now, CudaDeviceDetection.exe fails to work properly -- it uses a full CPU core and never completes scanning. NiceHashMiner also fails to work with the Nvidia GPUs because it expects some information back from CudaDeviceDetection.exe.

Any input / help would be welcome. I may see about installing the previous 373.06 drivers, and if that works, then I'll upgrade to 373.57 and see if things continue to work or not.

**Comment by xKumatora** [comment]
Started happening to me after updating drivers recently too, although I'm not sure the last driver version it was working on. Tried downgrading from latest to 373.06 and I have the same issue, except now along with CudaDeviceDetection (which doesn't max out my CPU btw, only goes from around 8% to 10%, although it constantly fluctuates) I now have Nvidia-SMI 373.06 which is constantly using the same amount of CPU as CudaDeviceDetection.

**Comment by kenshirothefist** [comment]
This should be fixed in recent versions, make sure to use up-to-date release of NiceHash Miner.
