### ISSUE TITLE
No way! Miner do not work! Impossible to get GPU benchmark and/or profitability

### ISSUE THREAD

**Issue by demo-mvp** [nicehash/NiceHashMiner-Archived#280]
Hello,
As mentioned in title, I can't get the miner to work.
I think I've done almost everything I've seen here and there but nothing solved the problem.
In fact I've get it mine a few hours one day and after an electrical blackout, I never could get it run back again .
I'm on win7 64bits and run one GPU R9 270x, nicehah miner 1.7.2.0, AMD driver V.15.7.1, I use DDU to switch from one driver install to another
Here is what I've try step by step:

1.suppress all .bin files from .\NiceHashMiner_v1.7.2.0\bin\sgminer-5-5-0-general 
No works!

2.change in sgminer-fixed.conf file located in .\NiceHashMiner_v1.7.2.0\bin\sgminer-5-5-0-general all bitcoin adresses by yours.
No works!

3.Try running \bin\sgminer-5-5-0-general\runme.bat manually from NHM v1.7.2.0 and report if there is any crash
 No works! sgminer will close 6 secondes after launch by itself

4.Try disabling default optimizations in NHM and try benchmarking
 No works!

5.Copy over the older sgminer (sgminer-5.4.0-nicehash-39-windows-amd64) to \bin\sgminer-5-5-0-general\ (this will not have lbry support) and report if benchmarking works.
No works!

6.try NHM v1.6.1.4 and report if there is any issue with that version.
No works!

7.try this patched version and report if the problem still exists. Copy it in 1.7.1.4 folder and run the binary.
No works! gpu not view! slow down computer!

8.In the settings under Devices/Algorithms select a sgminer algorithm (any algorithm except ethereum/DaggerHashimoto) and set Benchmark speed (H/s) manually (any value bigger than 0).
No works! I Have set the real value that I've got from previous working mining with v.1.7.2, but no work because can't get profitability !

9.Disable ethereum/DaggerHashimoto for that AMD GPU.
Save and Close settings and Start mining.
No work! unable to get nicehash profitability! if you're connected...

10.have you tried --gpu-platform ? sometimes the integrated GPUs or NVidia GPUs can cause problem. you just need to find the right --gpu-platform number
Yes! runme.bat work!

I mean, it's crazy!
Here is the screenshot of my errors:
(internet connection) http://screencast.com/t/U4x3hLr0AtM
I just click yes and the setting continue.
(unable to get profitability) http://screencast.com/t/rq74ydoQ

I have also attach my 1st log (log1.txt) and last log file (log.txt)

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/552015/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/552017/log.txt)

Sorry for the longest post but I think that way everybody has a good understanding of what's going on and will not ask questions that are already here.

Thanks all for your help.

**Comment by demo-mvp** [comment]
I just retry with all algo desactivated except Draganhashi and I succeed to have Draganhashi only benchmark, but no profitabillity so I can't mine. :-(

Help Please !!!

**Comment by aaronsace** [comment]
Every algo blue screens AMD cards except for DaggerHashimoto and Equihash.

**Comment by S74nk0** [comment]
@demo-mvp No need to apologize your long descriptions are very welcome as this problem is present for some time now, more info we get the better. This seems to be related with AMD drivers, but we are really not sure as we cannot reproduce this issue ourselves. If someone with this issue could try running benchmarks from the **Command Prompt** and report if it BSODs that would also be helpful as mining seems to work but benchmarking doesn't.

**Comment by demo-mvp** [comment]
I do not experience blue screen but the soft will just not benchmark GPU and shut down by itself.
I have tested the new version 1.7.3 and it's still the same.

**Comment by spectre110** [comment]
Here is the screenshot of my errors:
(internet connection) http://screencast.com/t/U4x3hLr0AtM
I just click yes and the setting continue.
(unable to get profitability) http://screencast.com/t/rq74ydoQ

The same mistakes
win 10 64, i5, gtx970
[log.txt](https://github.com/nicehash/NiceHashMiner/files/560413/log.txt)

**Comment by spectre110** [comment]
decision - vpn service
because my ip adress in spam bases. provider offers Internet access through NAT

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).

**Comment by NaitorStudios** [comment]
Here's how to fix it:
I've found out that NiceHash Miner (and some other programs) can't detect internet connection when IPv4 and IPv6 are enabled at the same time.
Disable one of them and the problem should go away. I think IPv6 is better, so I let it enabled and disabled IPv4, but I don't know if there's any drawbacks.

To disable just right click the network tray icon, then click Open Network and Sharing Center.
In the window that show up, look for "Connections: " right below HomeGroup, then click whats on the right side (should be your network name).
New window, Properties, you will see a list, check or uncheck IPv6 or IPv4, you must let at least one checked.

For the developers:
NiceHash Miner can't determine with IP version to use when both are enabled, hope in a future update it get fixed so we can use both at same time and people won't freak out with this issue.

**Comment by addictedindian** [comment]
please solve this error 
this programme cant start because api-ms-win-crt--runtime-[1-1-0.dll is missing from your computer
uploading image

![log](https://cloud.githubusercontent.com/assets/26764336/24448737/b1d72594-1492-11e7-937b-afa42e369893.jpg)

**Comment by aaronsace** [comment]
Post your own issue. 
It's related to your install of Microsoft Redistributable Package.
