### ISSUE TITLE
1.7x can't run on w7x64

### ISSUE THREAD

**Issue by segurah** [nicehash/NiceHashMiner-Archived#281]
Version 1.6.14 runs ok, but 1.7.x do nothing, no errors, no GUI.

I checked .NET 4.5, download it and says that have a most recent version running.

**Comment by foxwarernd** [comment]
screenshots, logs need

**Comment by S74nk0** [comment]
@segurah Closing issue. In order to help us solve potential issues we need more information (logs, OS version, screenshots,...). Please give us a more detailed description.
