### ISSUE TITLE
half the payouts

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#285]
Is it just me or did something happen to nicehash? I was getting $14 per day and now 30 days later I am getting between $7-$9 per day. Going to rollback upgrades and see if it makes a difference.

**Comment by d57heinz** [comment]
Price of eth stagnated and Difficulty has gone sky high. Almost doubling in two months. That's prolly the reason. Stay tuned for z cash mining may give us miners a bump in our income. 

Best Regards
d57heinz

**Comment by xadonxander** [comment]
I doubt that is the issue for me. I am running mostly nvidia cards, mining lyra2re2,

**Comment by fefsf** [comment]
The profit has been  decline for a few weeks now. I was making 15/day now I'm lucky my to get 9

**Comment by aaronsace** [comment]
The new equihash is sky high!

**Comment by S74nk0** [comment]
This is really not related to NHM issues so will close this. As you probably already know v1.7.3.x has equihash support.
