### ISSUE TITLE
BSOD in ATIKMDAG.SYS 

### ISSUE THREAD

**Issue by V1irus** [nicehash/NiceHashMiner-Archived#286]
Hi, just downloaded Nicehashminer and tried to banchmark 
immediately i get a BSOD with ATIKMDAG.sys... it's like 1 sec... i got the 16.10 driver on Win 10

GPU: R9 290
CPU: I5 6600K
OS: Win 10

**Comment by aaronsace** [comment]
Seriously, they not fixed this yet!?!? All you can do for now is disable all the algorithms on AMD graphics cards except for DaggerHashimoto and Equihash.

**Comment by V1irus** [comment]
Hmm okay now i can benshmark but if i try to bench Daggerhashimoto i dont get any reaction and nothing is happening

**Comment by V1irus** [comment]
hmm. okay now it's working but not ideal... i wish we can use some more algorithms

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
