### ISSUE TITLE
1.7.3.0 EquiHash mining continuously restarting

### ISSUE THREAD

**Issue by wheunis** [nicehash/NiceHashMiner-Archived#287]
Using 1.7.3.0, with i5 6600k and GTX1070.
Benchmarking works fine.
Mining starts and works fine.

For reasons unknown (no error, nothing), every 60-90 seconds, miner will simply restart for no reason.
Miner window closes and immediately pops up a new instance.

This occurs when mining only CPU, only GPU, or both combined (same results mining both in same app instance, or in separate instances).

Based on my basic reading of logfile, it looks like the miner keeps changing it's ports for some reason...

Please advise if further data is needed.
Attached logfile:
[log.txt](https://github.com/nicehash/NiceHashMiner/files/559695/log.txt)

**Comment by wheunis** [comment]
Just to add:
This does not happen when running the nheqminer manually via cmd-line, .bat file, or shortcuts.
Only happens from the NiceHash mining app.

**Comment by gennadiv** [comment]
та-же проблема и нет x11 алгоритма

**Comment by lxga** [comment]
I have the same problem with amd rx470

**Comment by allacc** [comment]
Me too!

For reasons unknown (no error, nothing), every 60-90 seconds, miner will simply restart for no reason.
... !!!???

Win10 x64 Pro / Nicehash 1.7.3.0
Rx480, Rx470 MSI / 16.8.2
R9 380 MSI and Asus / 16.6
R9 280x, 280 MSI and Asus / 16.6

**Comment by degriz** [comment]
Settings---->advanced--->Switch Time. Put a really high number in there.

**Comment by wheunis** [comment]
> Settings---->advanced--->Switch Time. Put a really high number in there

As band-aid solutions go, I guess this will do (very temporarily).
I don't actually hold very many high hopes that the price of ZCash will remain this high for very long.
Would be nice to have the autoswitch function back to normal as intended,

Anyway, thanks all the same!

**Comment by S74nk0** [comment]
This will be fixed in the next version (soon).

**Comment by S74nk0** [comment]
New release is out with a fix. Will close this issue.

**Comment by wheunis** [comment]
Confirmed fixed.
Thanks plenty!
