### ISSUE TITLE
1.7.3.0 eqhash not allowing for less threads or -t n in extra parameters

### ISSUE THREAD

**Issue by ferdjones** [nicehash/NiceHashMiner-Archived#288]
Running Win10 x64 on a 6900k and NVIDIA 1080.

No matter if I set less threads or if I add "-t 12" (for example), eqhash starts running with all 16 cores.  If I open a command prompt and start eqhash w/ "-t 12", it will only start 12 threads (or 6 if I say that, etc).

Same goes for cpu only and cpu + gpu.

Running latest windows updates and nvidia drivers.

Let me know if you need any more info.

**Comment by nicehashdev** [comment]
Aware of this bug and will be fixed in next version.

**Comment by S74nk0** [comment]
New release is out with a fix. Will close this issue.
