### ISSUE TITLE
Wont run at all on one machine.

### ISSUE THREAD

**Issue by savantguarde** [nicehash/NiceHashMiner-Archived#29]
I have a weird problem where the miner wont run on the one machine I want it to! (the high performance one )  I click on the exe and it just informs me that "nicehash miner has stopped working"  I dont get to the app at all.  I have a few other machines and it all works fine on them.  Its not specific to this version its a general problem that I have reached the end of my rope on!
Compiling the project on this machine (VS2013) , everything builds fine.   when I excecute I get an unhandled exception of type "System.Management.ManagementException" Additional info: Invalid Class.  Breaking into line 61 of form 1 .cs  
PUZZLED!

**Comment by theLosers106** [comment]
@savantguarde can you try running it with Administrator permission? right click on NiceHashMiner.exe and click "Run as administrator".

**Comment by savantguarde** [comment]
yeah same thing.  Stopped working. I dont understand it.  I have another machine here which runs it fine on which I have no administrator priveledges at all!

**Comment by theLosers106** [comment]
What Windows are you using?

**Comment by savantguarde** [comment]
Windows 7 Pro:  Version 6.1  Build 7601: service Pack 1.  same as on a machine I have it working on here.  I thought maybe I was missing a redistributable or something but that doesnt seem to be it. It should just work...

**Comment by theLosers106** [comment]
Hi,

Do you still have the same problem? Could you try out the new NiceHashMiner v1.3.0.0 yet?

Thanks.
