### ISSUE TITLE
[BUG] Main window not resize-able

### ISSUE THREAD

**Issue by jsmcconn** [nicehash/NiceHashMiner-Archived#297]
v1.7.3.1
The main window FormBorderStyle is set to FixedDialog, which results in a window that cannot be resized.  

This breaks the UI when there is more than 1 Device Group:
- When there are 2 groups: The status bar (global rate) is obscured.
- When there are 3+ groups: the 3rd and higher groups are not visible.

**Comment by jsmcconn** [comment]
Add image of issue, this is on a 4k monitor with hidpi enabled.
![nhminer](https://cloud.githubusercontent.com/assets/6070986/19857988/5dc3c074-9f45-11e6-83fc-77b359b55de8.png)

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).
The height calculation is different. Reopen this if it is not fixed.

Closing issue as it is related to an older version of NiceHash Miner.
