### ISSUE TITLE
Reconnecting in 3 seconds

### ISSUE THREAD

**Issue by ChaoticBrady** [nicehash/NiceHashMiner-Archived#298]
I decided to give bitcoin mining a shot. I configure it, benchmark and press start. It opens up cmd looking prompt and says lots of stuff like
Connected:
read_until:end of file
Reconnecting in 3 seconds.
This bug/glitch has had me puzzled all day. What exactly do I do?

**Comment by anonymous890890543** [comment]
Nicehash Miner v1.7.3.1 same problem here, Algo equihash.
windows 10 64
Graphic card gtx 950
Working great on Cpu mining

**Comment by S74nk0** [comment]
@ChaoticBrady, @anonymous890890543 does it loop reconnecting? Try changing location closest to you [Europe, USA, Japan, China]

**Comment by ChaoticBrady** [comment]
@S74nk0 Well I have tried that a lot but it never works.

**Comment by nerdatwork** [comment]
It is in loop reconnecting and if I start NH again it shows "Nicehash miner needs to connect to internet..."

**Comment by Khairan** [comment]
I have the same problem. Strange that yesterday all worked with the same settings, but today "Reconnecting in 3 seconds..." in loop

**Comment by EVGENY1777** [comment]
periodic rebooting NiceHashMiner 1
![untitled1](https://cloud.githubusercontent.com/assets/23138776/20009671/6dbe5204-a2b6-11e6-94be-4d509f379ba4.jpg)
.7.3.2
[log.txt](https://github.com/nicehash/NiceHashMiner/files/571785/log.txt)
[General.json.txt](https://github.com/nicehash/NiceHashMiner/files/571798/General.json.txt)

**Comment by EVGENY1777** [comment]
the problem is solved new reset miner. server eu too works

**Comment by Khairan** [comment]
@EVGENY1777 what is "new reset miner"?

**Comment by EVGENY1777** [comment]
Set in new Folder

**Comment by S74nk0** [comment]
Closing issue as it seems to be related to NiceHash service downtime and not NiceHash Miner.

**Comment by lutsifer** [comment]
It seems this service is down all the time...
