### ISSUE TITLE
benchmark on amd

### ISSUE THREAD

**Issue by Xerxes1000** [nicehash/NiceHashMiner-Archived#299]
NH 1.7.3 on Windows 10
it runs the benchmark and at the end the crashes and the benchmark results are gone.
I had the same issue with a previous version and got a version call
..._exitpatch that fixed it.

**Comment by S74nk0** [comment]
`_exitpatch that fixed it` this is included in NHM 1.7.3. so you are saying that the patch works but the official release does not?

**Comment by Xerxes1000** [comment]
Exactly. I was running the exit_patch and it was working fine. Then I installed 1.7.3 and I had the old problem again

Von: Stanko Krstić [mailto:notifications@github.com] 
Gesendet: Mittwoch, 2. November 2016 14:43
An: nicehash/NiceHashMiner NiceHashMiner@noreply.github.com
Cc: Xerxes1000 yorckleschber@t-online.de; Author author@noreply.github.com
Betreff: Re: [nicehash/NiceHashMiner] benchmark on amd (#299)

_exitpatch that fixed it this is included in NHM 1.7.3. so you are saying that the patch works but the official release does not?

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
