### ISSUE TITLE
Will not run 2x R9 380x

### ISSUE THREAD

**Issue by steinhammer** [nicehash/NiceHashMiner-Archived#30]
Just put my new miner together with two saphire R9 380x. Nicehash starts ok and finds the cpu and gpu:s. When I try to run benchmark cpu works fine but OpenCL say Please wait... (gpu is not doing anything) and after a long time it changes to Terminated and moves on the same way on all Algorithm. If I press Start i get a window with "Started sgminer 5.2.1" and "using Jansson 2.7" (gpu doing nothing) and nothing more.

**Comment by maciozo** [comment]
I have the same issue with an ASUS R9 290X.

**Comment by theLosers106** [comment]
Hi,

Have you tried running the runme.bat and see if it runs OK?

Thanks.
