### ISSUE TITLE
Benchmark - System Service Exception ATIKADMG.SYS

### ISSUE THREAD

**Issue by Swimmer63** [nicehash/NiceHashMiner-Archived#302]
I have one R9 290X and one RX 480 - Attempting to benchmark with both or either individually crashes PC.  System Service Exception, failing file is atikadmg.sys  WIN10, Intel Celeron CPU G1840.

**Comment by Swimmer63** [comment]
Using NiceHash Miner v1.7.3.1

**Comment by S74nk0** [comment]
This issue has been long present since v1.7 and sgminer update. Check AMD issues someone has posted a way to fix it, some had issues with voltage. We ourselves did not encountered problems with our AMD testing rigs so we are still unsure what is causing this issue.

**Comment by Swimmer63** [comment]
OK - I'll look.  Thanks!

Thanks!
Mike

**Comment by Livienspark** [comment]
https://github.com/nicehash/NiceHashMiner/issues/340

**Comment by Smokeyw** [comment]
same problem here with all the versions of nicehash and any driver for the rx 480
this realy sucks and no that fix dont work at all

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
