### ISSUE TITLE
multiple instances of nheqminer are started on some machines

### ISSUE THREAD

**Issue by CreamyG31337** [nicehash/NiceHashMiner-Archived#305]
nicehash keeps spawning extra nheqminer processes on some of my computers. The original process keeps running, and the extra processes create a lot of lag and rejected shares. 3/7 of my computers never have this problem. The other 4 it just keeps getting worse until I kill the processes manually. I have to do this every few hours.

**Comment by CreamyG31337** [comment]
I disabled the video card from 'helping' on those machines and it seems to have fixed it. Plus, it's faster. I also disabled the 'hide mining windows' on a few of the machines. Not sure if that helped too.

**Comment by S74nk0** [comment]
Try the new release. The problem might have been related to using to many CPU threads (it always used all unless setting it to use less in the settings). This has been changed to free threads for additional mining devices such as GPUs.

**Comment by leshiy-gr** [comment]
I have the same problem. In the last version is not yet know if any additional processes are created, but if the video card is enabled - the speed of processing of mining falls markedly. 1.7.3.2, 1.7.3.3
I disabled this algorithm on the video card - the processor is faster, a little bit + graphics card adds a different algorithm

**Comment by technyne** [comment]
Same issue here, I have noticed that if I have DaggerHashimoto selcted this will happen until I force the miner to quit, if I deselect DaggerHashimoto it will mine Equihash no problem, Still does it with the update, doesnt make a difference if my CPU is mining or not.  GPUs are R9 380's

**Comment by S74nk0** [comment]
This issue is related to an older NHM version. Try using the latest version and open a new issue if this issue is present or if you encounter a new issue.
