### ISSUE TITLE
benchmark ok  then it wont  mine.  HELP please

### ISSUE THREAD

**Issue by desade9** [nicehash/NiceHashMiner-Archived#307]
![nicehash 2016-11-03 19_23_44-](https://cloud.githubusercontent.com/assets/23244524/19979559/2dea4e1e-a1fb-11e6-8a39-d2f73f6f023e.png)

P

**Comment by foxwarernd** [comment]
input your btc addr and mine

**Comment by S74nk0** [comment]
Like @foxwarernd said you are missing a BTC address. If unsure what is your BTC address click on **Help me choose my Bitcoin wallet**

**Comment by desade9** [comment]
I had BTC addres when tried to mine, I just deleted when makeing
screenshot. I installed older version and is working now, so i still dont
know what is the problem, if there are any ideas, please.

On Nov 4, 2016 02:46, "Stanko Krstić" notifications@github.com wrote:

Like @foxwarernd https://github.com/foxwarernd said you are missing a BTC
address. If unsure what is your BTC address click on _Help me choose my
Bitcoin wallet_

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/nicehash/NiceHashMiner/issues/307#issuecomment-258324636,
or mute the thread
