### ISSUE TITLE
Old little interface glitch

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#31]
Not really a big issue,....but anyways
in the LOADING phase, the borderless window  with Loading doesn't stick to the program
but gets highest focus... (you can notice it putting another window close to it).
If the loading window should stay on on the top, maybe it should be better to draw it as a popup window

https://cloud.githubusercontent.com/assets/16473762/13172005/90a78580-d6fe-11e5-9e3c-5ffb9621f4d6.jpg

**Comment by theLosers106** [comment]
Noted.. Will investigate it..

Thanks (:

**Comment by theLosers106** [comment]
@apprehensivemom Great news.. this will be fixed in the next release..

**Comment by theLosers106** [comment]
This issue has been addressed in the latest Release 1.3.0.1
https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.1
