### ISSUE TITLE
RX 470 issue

### ISSUE THREAD

**Issue by VORNEua** [nicehash/NiceHashMiner-Archived#313]
If run 1 gpu all ok, but if run 2 or more то такая фигня
clSetKernelArg (-48)
clSetKernelArg (-48)
clEnqueueNDRangeKernel (-36)
clSetKernelArg (-48)
clSetKernelArg (-48)
clSetKernelArg (-48)
clEnqueueNDRangeKernel (-36)
clSetKernelArg (-48)
clSetKernelArg (-48)
clSetKernelArg (-48)
clSetKernelArg (-48)
clEnqueueNDRangeKernel (-36)
clSetKernelArg (-48)

**Comment by S74nk0** [comment]
@VORNEua I will update the bin files. Delete **OpenCL.dll** under \bin\nheqminer_v0.4a. Report if it fixes

**Comment by VORNEua** [comment]
yes, thx. working...

**Comment by S74nk0** [comment]
We are uploading the new binaries package. After that a clean install will work.

**Comment by S74nk0** [comment]
Ok let this issue be open for a while because more people might have this problem

**Comment by S74nk0** [comment]
New version out. Closing issue
