### ISSUE TITLE
Multiple Benchmark Fails (GTX 670, GTX 650, Radeon HD 6850)

### ISSUE THREAD

**Issue by babytechno** [nicehash/NiceHashMiner-Archived#320]
I am unable to benchmark the following cards. I know they are old, but I was able to run at least the Nvidia cards with 0.3a on nhminer 1.7.3.1 using the modified trump files in the previous thread.

Will there be support for older cards like these, or am I stuck?

Using the most recent Nvidia drivers, and the 15.7.1 AMD drivers.

Thank you.

**Comment by S74nk0** [comment]
Hi @babytechno. These cards are older yes and the new **eqm** and its predecessor **nheqminer** have incompatible CUDA kernel code (it became incompatible with optimization updates). This my change in the future but it is very low priority for older hardware. Closing issue.
