### ISSUE TITLE
1.7.3.3 Hash drop in random time until Equihash miner is manually restarted.

### ISSUE THREAD

**Issue by pbuva** [nicehash/NiceHashMiner-Archived#321]
Sometimes my Sols/s drop from cca 78 to 40, until Equihash miner is manually restarted. It looks like it stopped running one GPU, But because it appears as a group, do not know that, and if so, which. In 1.7.3 and maybe 1.7.3.1 was not problem.

3x RX 480 8GB
Win 10 x64
Last AMD driver

**Comment by pbuva** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/572591/log.txt)

**Comment by Dabus-777** [comment]
I have the same problem with my 5 x rx 480. In next 10 mins after the system start system one or two cards goes to standby mode with normal temperature ~40C and do nothing. Maybe they overheat? 
Is there any options for limit/control temperature of the cards?

**Comment by pbuva** [comment]
Fans got up to 2X percent, can not be overheated.

**Comment by pbuva** [comment]
Dagger-Hashimoto - stable. 
Problem  is only with equihash.

**Comment by S74nk0** [comment]
@pbuva `maybe 1.7.3.1 was not problem` can you confirm this? If you can replace the **nheqminer_v0.4b** with the older [nheqminer_v0.4a](https://github.com/nicehash/nheqminer/releases/download/0.4a/nheqminer_v0.4a.zip) please report if this also happens. **nheqminer_v0.4a** and **nheqminer_v0.4b** are exactly the same performance wise so you will not lose any performance

**Comment by S74nk0** [comment]
This issue is related to older NiceHash Miner version. Closing issue. If the issue is still present in the new version reopen this issue.
