### ISSUE TITLE
nheqminer.exe - system error - no OpenCL.dll

### ISSUE THREAD

**Issue by leshiy-gr** [nicehash/NiceHashMiner-Archived#323]
But on this system i have no amd\ati videocards. AMD detection and AMD temperature control are off in settings. 
On other computer, after manually added that library, I got an error - something like the entry point in the procedure could not be found, **clReleaseDevice**. AMD cpu but no AMD gpu.

**Comment by wyh136** [comment]
copy opencl.dll from bin directory to nheqminer.exe's dir

**Comment by leshiy-gr** [comment]
Thanks. I did not think that the necessary libraries are in the kit. In order to remove all error messages, including at startup, i also copy it to Nicehashminer dir
