### ISSUE TITLE
URL for API to check Multi Algo Stats is getting a 403 error on my machine

### ISSUE THREAD

**Issue by BorsalinoK** [nicehash/NiceHashMiner-Archived#327]
URL for API to check Multi Algo Stats is getting a 403 error on my machine

URL is linked here on this code file: https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Links.cs#L22

I also noticed that If I accessed that API via my browser I get a  form asking me for captcha verification
See in image attached:
![capture](https://cloud.githubusercontent.com/assets/23262040/20029559/f9bc5fde-a389-11e6-988a-34ece4a6df87.PNG)

Also Added the Error Log for the miner:
![capture2](https://cloud.githubusercontent.com/assets/23262040/20029560/f9be7292-a389-11e6-8a96-f198899e61ca.PNG)

**Comment by mxaddict** [comment]
I get this same issue when using my 3G connection, Any way to have the NiceHash miner forward the Captcha request so that I can fill it out? and the miner can continue as per usual...

**Comment by BorsalinoK** [comment]
Now that you mention it, I also am on a LTE connection

**Comment by S74nk0** [comment]
Opened a new issue that references this and other related issues (#397).
