### ISSUE TITLE
1.7.3.3 NVidia & CPU issues

### ISSUE THREAD

**Issue by ferdjones** [nicehash/NiceHashMiner-Archived#328]
Just installed 1.7.3.3, and it's now calling my CPU (i7 6900k) "1 * GTX970, 1 * GTX990" and there are no hashes happening.

When I try to run JUST the GPU, it seems to work fine (at least for lyra2rev2), but add the CPU, and it'll list the GPU doing something (l2rev2 so far) and the 2 above listed gpus (that I don't have) and zero hashes.

**Comment by dingmel** [comment]
ditto. 
having a similar problem. 

my 5930K and 1080gtx is acting weird. 

The cpu runs equihash just fine, but the 1080, gives out zero hashes and a false hashrate when running cryptonight. Trying to switch to lyra2rev2 just lists  "1 \* GTX970, 1 \* GTX990" and there are no hashes happening as well.

**Comment by ghost** [comment]
Yeah, I used 2 different cpus and got the same names

**Comment by dingmel** [comment]
I sorted it out on my end. Turns out some AV's flag some of the miners as malware, and restrict/remove them subtly. In my case, was KIS. Added an exclusion and sorted out my problem. Hope this helps!

**Comment by ferdjones** [comment]
That seemed to work for me too.  Weird thing is is that I could run nheqminer for the cpu manually with no problems, but when I tried w/ the nicehash miner program, it gave me the initial problem.

It was Windows Defender here that gave me the problem, so I just added the whole folder to the exclusions list.  As a side note, I had WD flag a .log file a few weeks ago as malware.

Side note #2:  The nheqminer now does follow the less threads option, BUT, even when I tell it to use 6 less threads (and it seems to follow it via the output in the miner window), it still uses a good portion of the 16 available threads according to task manager.  10 threads are pegged at 100%, while the other 6 sit near 90-95%, which means that video watching/gaming runs like crap.

**Comment by cryptonit** [comment]
i would love ability to choose launch nicehashminer and all its started mining processes at below normal process priority for now i always have to go manual towards taskmanager and change priority and once miner restarts it forget the reduced priority again

**Comment by S74nk0** [comment]
The original issue is related to an older version of NiceHash Miner and it should work in the new version. All other issues that are not related to the original problem please open a separate issue.
Closing...
