### ISSUE TITLE
GPU1 not running

### ISSUE THREAD

**Issue by gaby64** [nicehash/NiceHashMiner-Archived#329]
I have 2 R9 290, selecting only GPU1 it doesnt run, selecting both, only GPU2 runs
this is for both daggerhashimo and equihash

**Comment by Bige086** [comment]
Im having the same issue with 2 rx 480s.

**Comment by S74nk0** [comment]
Hi all! Post the logs. If NHM is not passing OpenCL indexes to these miners than NHM has to be fixed if it does than the problem might be in the miners. Some logs for now would help

**Comment by S74nk0** [comment]
Closing this issue. [New issue](https://github.com/nicehash/NiceHashMiner/issues/393) will be opened until we push out a new release. The fix will be most likely available with the new upcoming release.
