### ISSUE TITLE
[Feature Request] Separate OpenCL miners

### ISSUE THREAD

**Issue by EdoaLive** [nicehash/NiceHashMiner-Archived#33]
Hi all,
I have a Radeon R9-290 and a R7 series integrated in my A10-7850K.
I have this issue:
When I disable the integrated GPU, everything run smooth, NiceHashMiner use the optimized miner and I have a good hashing rate.
When I enable the integrated card, NiceHashMiner runs a single sgminer(?) process for both cads, and I get a terrible hashing rate (worse than the single R9). 
I think there are 2 causes for this:
1. NiceHashMiner don't recognize the R9 290 device name and don't use the optimized sgminer
2. sgminer use a single memory buffer for both devices, causing a bottleneck for memory transfer between the 2 GPUs.

This happens also if I select only the R9-290, because of a bug (that I'll fill separately) that reverse the device names and the OpenCL id.

I think the best solution is to launch many separate sgminer processes for every ("different"?) GPU, or at least add an option to select "separate OpenCL processes" mode.

Thank you!

**Comment by PhoenixAdageyudi** [comment]
SAME PROBLEM WITH ETHEREUM. I HAVE. 295x and 270x I STARTED USING THE 270X AFTER ALL WAS WELL WITH THE 295X THEN WTF 1$ A DAY FROM 10!?!?!?!?!   

PLEASE FIX.  

PLEASE FIX.  

hope you heard me

**Comment by kenshirothefist** [comment]
The idea or running separate mining processes for different GPUs is not bad, but it also requires more main RAM memory (especially in Ethereum case). We will consider this upgrade as an optional setting in a future release.

**Comment by EdoaLive** [comment]
Is there some news about this?
Thanks

**Comment by nicehashdev** [comment]
We have plans to group devices per separate device profitability. The feature is planned for next release.

**Comment by nicehashdev** [comment]
Already implemented.
