### ISSUE TITLE
Radeon xfx hd 6950 1gb

### ISSUE THREAD

**Issue by HenningTT** [nicehash/NiceHashMiner-Archived#334]
only find the amd 8350 8 core cpu.
my gpu card  radeon hd 6950 1gb by xfx do not get detected.
i tryed all driver.  any support for that card any time soon?

**Comment by ArtAnts1986** [comment]
> hd 6950 1gb by xfx  

you need to install the driver AMD 14.2

**Comment by S74nk0** [comment]
Closing this issue. [New issue](https://github.com/nicehash/NiceHashMiner/issues/393) will be opened until we push out a new release. The fix will be most likely available with the new upcoming release.
