### ISSUE TITLE
Help with AMDOpenCLDeviceDetection

### ISSUE THREAD

**Issue by cryptoanarchism** [nicehash/NiceHashMiner-Archived#337]
Can anyone direct me to a link or explain to me how setup my AMD GPU to work on NiceHashMiner. I was looking at the README didn't quiet understand what it meant by "Make sure that the binary can link to OpenCL.dll". I did download AMD APP SDK 3.0 however.

**Comment by semisane** [comment]
For systems that don't have Intel integrated graphics I've used the Intel OpenCL CPU drivers, for computers that had an Intel 3xxx integrated GPU I successfully used the AMD SDK to get rid of that message.

What GPU and driver version are you using?

**Comment by cryptoanarchism** [comment]
GPU = rx480
Driver Version = 21.19.160.512
Radeon Software Version = 16.11.2
OpenCl Version = 21.19.160.512

**Comment by semisane** [comment]
So what error are you receiving?

**Comment by cryptoanarchism** [comment]
stop code = SYSTEM SERVICE EXCEPTION
what failed = atikmdag.sys

**Comment by semisane** [comment]
There's another issue opened up with the same problem. It seems that if they use the onboard graphics and then mine they don't have the BSOD. Can you see if you can try that?

**Comment by cryptoanarchism** [comment]
Got it too work. thanks man
