### ISSUE TITLE
[BUG] OpenCL GPUs id/name being mixed up

### ISSUE THREAD

**Issue by EdoaLive** [nicehash/NiceHashMiner-Archived#34]
Hi all,
I have a Radeon R9-290 and a R7 series integrated in my A10-7850K.
My monitor is connected to the R9 (if the issue is here).

If I enable the integrated GPU, I see both in NiceHashMiner, the but if I select the R7, I see high GPU usage on the R9 and vice versa.

**Comment by theLosers106** [comment]
Hi,

Could you post a screenshot of the NiceHashMiner and also run this command in the sgminer folder:

> `sgminer -n`

or if you need to specify which OpenCL platform then:

> `sgminer --gpu-platform X -n`

*Replace X with the appropriate GPU platform

Thanks.

**Comment by theLosers106** [comment]
I'll be closing this for now as there is no follow up for a while now..

**Comment by richardxtc** [comment]
Im currently expericing thia issue. Nice hash version 17.2.13

Not aure how to upload a screen shot?
