### ISSUE TITLE
A way to fix SYSTEM_SERVICE_EXCEPTION on AMD cards.

### ISSUE THREAD

**Issue by Livienspark** [nicehash/NiceHashMiner-Archived#340]
I have a RX 470 GPU. It fails to do some algorythms on sgminer resulting in BSOD SYSTEM_SERVICE_EXCEPTION. So cause of crash is definitely sgminer.
I tried to move my display cable from card to motherboard and then it worked nice without any BSOD. Please, check this if you can make it work with display attached to card.

P.S. Radeon HD 7770 has same problem on sgminer. This fix works on that card too.
P.P.S. Display uses VGA cable. RX 470 connecting through HDMI->VGA converter.

//Sorry for bad english.

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
