### ISSUE TITLE
Extra Launch Parameters not working?

### ISSUE THREAD

**Issue by freedomtacos** [nicehash/NiceHashMiner-Archived#341]
I tried using the intensity parameter -i like in the old builds but it's not working so it's always using 100% of my GPU. Is there a new way to lower the intensity that I can't seem to figure out? Or is this just a bug? 

What exactly would I have to type here: http://i.imgur.com/3NqEf5E.png

**Comment by S74nk0** [comment]
Hi @freedomtacos there is no **--intensity** or **-i** for **DaggerHashimoto**, [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#nvidia-ethminer-daggerhashimoto) are the parameters that can lower your intensity. Tweaking these two you can achieve lower intensity.
