### ISSUE TITLE
Ati XFX 7850 and Xeon 5440 nicehash 1.7.3.3. not working

### ISSUE THREAD

**Issue by dadoremix** [nicehash/NiceHashMiner-Archived#342]
Hi 
problem with nheqminer_v0.4b on 1.7.3.3 version

pc is rebooting.. 
i see in miner when starting.. hash pool 1744 MB will use
then crash ati drivers and whole system reboot
win 10 pro in use

1.7.3.1 working good with nheqminer_v0.3a

try to replace V0.3a to 1.7.7.3 bin .. but then no valid adress to miner

**Comment by dadoremix** [comment]
anyone ?

**Comment by S74nk0** [comment]
@dadoremix using nheqminer with GPUs with less than 2GB RAM will not work. The new version gives the user a choice to use 3rd party claymore miner (with users agreement, as it is a 3rd party closed source miner). So for now our open source nheqminer can be used only with AMD GPUs with 2GB RAM or more. 
Closing issue...
