### ISSUE TITLE
[feature request] checkbox for multiple instances

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#343]
somebody likes multiple instances, for me is not good because I often forget to quit another
instance of the program hidden somewhere in my desktop.
I think it would be nice to add a checkbox in the options windows with
"Allow multiple instances? [yes][no]

The code could be like this:
if((FindWindow(0,"NiceHashMiner v1.7.3.3"))!=NULL  &&  checkboxsingle==TRUE ) { exit(0); } 

// If it's found another window named "NiceHashMiner v1.7.3.3" AND you selected
// single instance, then we are the unwantend instance and we will quit.

**Comment by installer1983** [comment]
1000000

**Comment by S74nk0** [comment]
We will add this on one of the newer releases

**Comment by S74nk0** [comment]
Feature request is covered with this [commit](https://github.com/nicehash/NiceHashMiner/commit/eb44530547b08bcacc9bd859d762a25738b9fb82). Feature will be included in the next release of NiceHash Miner.
Closing issue.
