### ISSUE TITLE
[bug] Sometimes currency resets from EUR back to USD

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#344]
1.7.3.3 and previous
I've found that when I start the program,  sometimes the currency is reset from EUR to USD
Not a big problem, I can change it again to EUR in the setting window,
but maybe you can fix it

**Comment by S74nk0** [comment]
This [commit](https://github.com/nicehash/NiceHashMiner/commit/e2062d36d960716be9ad5ca5dc2ec8a6d63c69a1) fixes this issue. It will only fallback to **USD** when the currency converter API is inaccessible. Closing issue as it will be fixed in the future release.
