### ISSUE TITLE
[Request] Start mining when idle AND start manually

### ISSUE THREAD

**Issue by justsomedudeonthenet** [nicehash/NiceHashMiner-Archived#345]
I would love to be able to leave "Start Mining When Idle" turned on all the time, but still be able to manually start the miner when I am using the computer for low intensity stuff mining won't affect.

When manually started with the Start button, it should keep running until I hit the Stop button.
When mining automatically on idle, it should stop once activity is detected.

Right now clicking Start makes it start mining for a second, then realize there is activity and stop.

**Comment by S74nk0** [comment]
@justsomedudeonthenet we will fix this in one of the newer releases.

**Comment by S74nk0** [comment]
This commit [4e46902](https://github.com/nicehash/NiceHashMiner/commit/4e469020dd30f3fb932de810b3df02e6f9c2b066) fixes this issue. It will be included in the future NHM release. Closing issue.
