### ISSUE TITLE
[Feature] filter stdout

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#346]
i noticed somewhere in the src there is already basic stdout filtering to restart (?) in case of cuda error and stuff, it would be great to get some nheqminer related stuff there too, as it sometimes crashes with multiple error messages (its somehow related to core oc).

in my own miner wrapper im currently filtering:

CUDA error
eq_cuda_context

**Comment by S74nk0** [comment]
Hi @felixbrucker. Are you referring to this in case of failure to restart the miner? If so this is covered with the new **eqm** miner inside **eqm** miner itself. Please confirm if I have understood you correctly.

**Comment by felixbrucker** [comment]
Yes that is correct, with the latest eqm version this error doesnt happen though it seems (eqm doesnt even need to restart).
