### ISSUE TITLE
Claymore Nicehash Zcash

### ISSUE THREAD

**Issue by PauloOF** [nicehash/NiceHashMiner-Archived#347]
I would prefer to use Claymore integrated into Nicehash GUI. Any plans to do it?

Claymore its faster than nheqminer_v0.4b working at nicehash Equihash pool (about 4 times faster).

**Comment by instahater407** [comment]
Same

**Comment by allacc** [comment]
SILENTARMY

Official site: https://github.com/mbevand/silentarmy

Performance

115 sol/s with one R9 Nano
75 sol/s with one RX 480 8GB
70 sol/s with one GTX 1070

**Comment by Singman33** [comment]
Why do you want Claymore to be included in NicehashMiner, while that program get a dev fee of 2.5% and is closed source ? If Nicehash should get a better miner, the real candidate is SilentArmy, an open source program.

**Comment by PauloOF** [comment]
Just because with Claymore I have 144 sol/s stable (138 to 150) for each MSI R9 390X @ Windows 10.

**Comment by Singman33** [comment]
So, you want to use a program that ask a dev fee (2.5%) to mine on a pool that already get some fees (nicehash) ? Are you crazy ? If you want to use Claymore, do it on your wallet, you dont need Nicehash for that !

**Comment by PauloOF** [comment]
180H/s on stock 390X
