### ISSUE TITLE
opencl.dll not installed on your system.

### ISSUE THREAD

**Issue by unipsycho** [nicehash/NiceHashMiner-Archived#348]
OK, I have a second machine with no GPU, so I'm trying to just do CPU mining.  Got this working on other machines all fine (newer OS with graphics cards) and the second machine is windows7 but no go.  If I run nicehash, the benchmarks all fail saying "missing opencl.dll".  If I copy the opencl.dll from the bin folder to root executable and the nheqminer folder, the error goes away, but then the benchmarks all return 0 rate, and when I start the nicehashminer it just says no devices enabled for mining, with the CPU miner checked.  Any help in getting the openCL to properly run and the benchmarks so the miner will run??

**Comment by swtrse** [comment]
Just copy a openCL.dll file from one of your other PCs to the nicehash bin/nheqminer_v0.4b directory. Because that's the miner that has problems. And the benchmark will work.

**Comment by leshiy-gr** [comment]
you can copy it from /bin dir to nicehash bin/nheqminer_v0.4b directory and to nicehash directory

**Comment by unipsycho** [comment]
Well, I think I've tried every combination of directories to have the openCL.dll.  As per your comments, the same as my original issue, it runs and does not complain about the openCL.dll missing anymore, but the benchmark is still failing, so can't activate the CPU device.  Here is the screen shot of what it does after benchmarking everytime.
[niceminer-error.jpg](https://postimg.org/image/k7ov9byr3/)

**Comment by unipsycho** [comment]
And if I run the nheqminer manually in a prompt, which works on other computes using:
nheqminer -t 6 -l equihash.usa.nicehash.com:3357 -u 19fnXp4cdPXEoPo8pp6And35tZQFRvYwnB.worker1

It runs for about 20 seconds and just returns to the prompt:
`C:\Users\Mike\Desktop\NiceHash Miner>nheqminer -t 6 -l equihash.usa.nicehash.com
:3357 -u 19fnXp4cdPXEoPo8pp6And35tZQFRvYwnB.worker1

```
    ==================== www.nicehash.com ====================
            Equihash CPU&GPU Miner for NiceHash v0.4b
    Thanks to Zcash developers for providing base of the code.
           Special thanks to tromp, xenoncat, mbevand
                 and eXtremal-ik7 for providing
          optimized CPU, CUDA and AMD equihash solvers.
    ==================== www.nicehash.com ====================
```

Setting log level to 2
[16:33:28][0x00000e2c] Using SSE2: YES
[16:33:28][0x00000e2c] Using AVX: YES
[16:33:28][0x00000e2c] Using AVX2: NO
[16:33:28][0x000012bc] stratum | Starting miner
[16:33:28][0x00000a8c] miner#0 | Starting thread #0 (CPU-XENONCAT-AVX)
[16:33:28][0x00001350] miner#1 | Starting thread #1 (CPU-XENONCAT-AVX)
[16:33:28][0x00000338] miner#2 | Starting thread #2 (CPU-XENONCAT-AVX)
[16:33:28][0x000013e4] miner#3 | Starting thread #3 (CPU-XENONCAT-AVX)
[16:33:28][0x00001388] miner#4 | Starting thread #4 (CPU-XENONCAT-AVX)
[16:33:28][0x000012bc] stratum | Connecting to stratum server equihash.usa.niceh
ash.com:3357
[16:33:28][0x0000048c] miner#5 | Starting thread #5 (CPU-XENONCAT-AVX)
[16:33:28][0x000012bc] stratum | Connected!
[16:33:29][0x000012bc] stratum | Subscribed to stratum server
[16:33:29][0x000012bc] miner | Extranonce is 242bfd1f00000000000000001ffd2b236c
[16:33:29][0x000012bc] stratum | Authorized worker 19fnXp4cdPXEoPo8pp6And35tZQFR
vYwnB.worker1
[16:33:29][0x000012bc] stratum | Target set to 01e1e1e1e000000000000000000000000
0000000000000000000000000000000
[16:33:29][0x000012bc] stratum | Received new job #00000002210f7937

C:\Users\Mike\Desktop\NiceHash Miner>`

**Comment by kazso** [comment]
You can install the OpenCL Runtime for Intel Core and Xeon processors (if you have an Intel CPU): [https://software.intel.com/en-us/articles/opencl-drivers](https://software.intel.com/en-us/articles/opencl-drivers) (scroll down until you find OpenCL™ Runtime for Intel® Core™ and Intel® Xeon® Processors)

**Comment by dtawom** [comment]
You can also install the AMD open CL 3.0 SDK regardless of whether you have an AMD card or not:  http://developer.amd.com/amd-license-agreement-appsdk/

**Comment by unipsycho** [comment]
Thanks guys, even with openCL installed for some reason the miner launches and runs the text I pasted above, but just ends a few seconds later after it received the new job numbers and it returns to the command prompt, no longer running anything.  I don't get it, I can run this on all my other computers, in VMs even without that happening.  Nothing unique about this install, just a standard win7 machine I use for rendering animation work so was hoping to mine when it not in use.  I guess not.

**Comment by S74nk0** [comment]
This issue is related to an older version of NiceHash Miner. Try using the new version (it has a new **eqm** miner included used with AVX/AVX2 capable CPUs).
Closing issue.
