### ISSUE TITLE
[FEATURE] Mine during time periods

### ISSUE THREAD

**Issue by mattjohnpowell** [nicehash/NiceHashMiner-Archived#349]
Is there a way to mine during certain periods during the day? 
i.e. Electricity is cheaper at night so being able to mine during these hours would help with profitability

**Comment by S74nk0** [comment]
@mattjohnpowell we will consider this request. It is a good suggestion.

**Comment by S74nk0** [comment]
Closing issue. Opened a new issue related to **Mining when Idle Feature update** that coveres this issue as well. Post all new suggestions or related problems to the new opened issue here #398
