### ISSUE TITLE
[1.7.3.4] mixed nvidia+amd on daggerhashimoto crash the miner

### ISSUE THREAD

**Issue by can99** [nicehash/NiceHashMiner-Archived#351]
1. running mixed card on daggerhashimo algorithm crashed the miner
2. it works fine on single card run
3.  running mixed card on different algorithm works fine(ex: daggerhashimoto(nvidia)+equihash(amd), equihash(nvidia)+daggerhashimoto(amd), equihash+equihash)

1.7.3.4
![image](https://cloud.githubusercontent.com/assets/20637900/20401842/0115dd80-ad2d-11e6-9a9d-4cca62a5c136.png)

1.7.3.3
![image](https://cloud.githubusercontent.com/assets/20637900/20401904/243b2c5c-ad2d-11e6-9532-f0a80bd57b21.png)

**Comment by S74nk0** [comment]
[this](https://github.com/nicehash/NiceHashMiner/commit/40c983d001348bcd47165736f9d9ebe54ce48a2b) commit fixes this issue. Keep the issue open until the new official release.

**Comment by S74nk0** [comment]
New [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.3.5) fixes this issue.
