### ISSUE TITLE
Lyra2re and daggerhashimoto on gtx950

### ISSUE THREAD

**Issue by Blackwing215** [nicehash/NiceHashMiner-Archived#355]
MSI gtx950 gaming, latest drivers (375.86), nicehash version 1.7.3.5, lyra2re works like that + daggerhashimoto doesn't work at all (but in version 1.7.3.3 it was working)

![benchscreen](https://cloud.githubusercontent.com/assets/18266311/20435646/ef7b55b4-adbd-11e6-8caa-cd0fc3c6f4e5.png)
![lyra2refail](https://cloud.githubusercontent.com/assets/18266311/20435647/ef7bec22-adbd-11e6-8a05-ef16da143c6e.jpg)

**Comment by cainzjuss** [comment]
Perhaps try the latest driver. That fixed some forgotten issue for me some time ago. 375.95 should be out.

**Comment by Blackwing215** [comment]
drivers 375.95, problem is still there(
and sometimes miner can't see videocard

**Comment by Blackwing215** [comment]
hmmm, okay, it looks like it is because of OC
