### ISSUE TITLE
1.7.3.4/5 equihash benchmark failed on GTX 1080

### ISSUE THREAD

**Issue by esensio** [nicehash/NiceHashMiner-Archived#356]
Just to let you know that 1.7.3.4 & 1.7.3.5 versions of nicehash can't run equihash on GTX 1080.
There is no problem with eqm_v.1.0.0b

**Comment by esensio** [comment]
Tested on
Asus STRIX GTX 1080-A8G 8GB
Z97X and H81, G1840, 8GB RAM
Win7-64, 16GB swap
nvidia drivers 370.90 (Z97X) & 373.06 (H81)

[log.txt](https://github.com/nicehash/NiceHashMiner/files/600506/log.txt)

Tried to set extra launch parameters without success.

**Comment by esensio** [comment]
Tried manually with eqm 1.0.1b - ~90+ sol/s

**Comment by CreamyG31337** [comment]
375.86 works fine on my STRIX-GTX1080-8G-GAMING on the lastest nicehash
updated to 375.95, still works fine for me.

**Comment by esensio** [comment]
Probably the new drivers will fix the issue. I will try later and post the result.

Anyway, equihash is not profitable enough with this solrate (~90sol/s) on 1080, so it's not a big deal.

**Comment by esensio** [comment]
Thank you CreamyG31337 for sharing the info.

**Comment by CreamyG31337** [comment]
yeah my 1080 gets the same hash rate as my old 970 :(
maybe nicehash is confused because of your many video cards. if you uncheck/disable some maybe that will help the developers find the problem? Try to reboot after you update the driver too -- my video card was stuck at a slower clock speed until I rebooted. Good luck!

**Comment by esensio** [comment]
Yes, exactly the same sols on 970 - I have three of them. I have separate rig only with 1080 - it is the same as the mixed one with 1070's. Nevermind, I can use the manual 1.0.1b if the price of ZEC start to raise, which is very unlikely to happen ;)

What GPU/MEM clocks you're running on your 1080? I have stable 2030/5100 on ETH.

**Comment by CreamyG31337** [comment]
My first 1080 burned out while playing Deus Ex, it took about a month to get the replacement. I have been a bit worried to overclock it since then, just running it stock. I'll try something slightly less than what you've posted, I think I just had bad luck before.

**Comment by fefsf** [comment]
I get a lil over 90SOL on my 1080 on latest version

**Comment by S74nk0** [comment]
New vesrion has updated **eqm** miner. Try new version. If you encounter problems open a new issue.
