### ISSUE TITLE
eqm 1.0.1b is working for few minutes and then crash

### ISSUE THREAD

**Issue by ansemz** [nicehash/NiceHashMiner-Archived#357]
nicehash 1.7.3.5
[error]  miner#2 | CUDA error 'unspecified launch failure' in func 'eq_cuda_context::~eq_cuda_context' line 1667
 Thread detected runtime error, restarting in 5 seconds...

**Comment by abhi1693** [comment]
Even I'm getting the same error!

**Comment by EugW** [comment]
me too

**Comment by EugW** [comment]
I have a temporary solution to this problem. You need check P0 State in settings. I then became normal work

**Comment by nicehashdev** [comment]
Make sure your overclocks are stable (fully). A single corrupted memory transaction will cause this. We will release more robust version of eqm in following days.

**Comment by abhi1693** [comment]
Mine is stable! But, it still crashes..

**Comment by EugW** [comment]
I have notebook Asus n550jk with Nvidia 850m 4GB VRAM. Overclock on notebook is almost impossible

**Comment by ansemz** [comment]
I mining on laptop too. Can not OC.

**Comment by ansemz** [comment]
when do you resolve it? thx

**Comment by ansemz** [comment]
resolved when i update to 1.0.1c.

**Comment by auroracoin** [comment]
Thank you  It's working great.  One thing please.. is it possible for you to do 1 build for my vista windows computer nivida 750ti. mcvs 2015 is missing I can't fix it and i cant compile. Just one build to take me out of 11 s/s. My 750ti's on w 8.1 are doing 60 s/s.  Thank you  ps just one time.
