### ISSUE TITLE
v1.7.3.5 Locks system up when benchmarking

### ISSUE THREAD

**Issue by Ancorale** [nicehash/NiceHashMiner-Archived#358]
I have an AMD Radeon HD 5450 that when the NiceHash Miner attempts to benchmark completely locks up the entire system. The last version did so, also. Thank you.

**Comment by dtawom** [comment]
I have dual R9 Furys and have the same issue.  The system always locks on the equihash benchmark.

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
