### ISSUE TITLE
crashing with certain algorithms

### ISSUE THREAD

**Issue by cainzjuss** [nicehash/NiceHashMiner-Archived#359]
This issue diddent happen last month but recently when mining lyra2re, lyra2rev2 and lbry for an hour or so the PC crashes (poweroff , no errors). I have updated drivers, tried the older, Tried last 5 versions of nicehash. All the other algorithms work fine.

GPU: GTX 1080 Zotac AMP Extreme
OS: Win10 64bit

**Comment by cainzjuss** [comment]
Update: Left it running all night today. No crashes. Thay seem to appear most when i do something at the same time... like browse the internet.

**Comment by cainzjuss** [comment]
Update2: Left it running all night and the crash happened.

**Comment by S74nk0** [comment]
This issue is related to an older NHM version. Try using the latest version and open a new issue if this issue is present or if you encounter a new issue.
