### ISSUE TITLE
what are u doing Developer of nicehash

### ISSUE THREAD

**Issue by dexametazon** [nicehash/NiceHashMiner-Archived#360]
Did you guys know how to make a program ? 
full of shit new version of nicehash and keep continue ..
![motherfuckerbug](https://cloud.githubusercontent.com/assets/23564495/20451202/1581c59c-ae0c-11e6-8432-b567f2a0b93e.JPG)

look at .. 
i think go on with MinerGate !

**Comment by CreamyG31337** [comment]
that seems extreme but i do have 1-2 extra copies of the cpuminer on most of my machines today after updating.

**Comment by S74nk0** [comment]
This is a serious issue. Please post the logs so we can see what is causing this.

**Comment by foxwarernd** [comment]
I have on different computers have the same problems with 1.7.3.5
I can see that normally can not be closed processes miners

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/601621/log.1.txt)

**Comment by S74nk0** [comment]
New release fixes this issue
