### ISSUE TITLE
[BUG] Pressing STOP -> Display driver stopped responding and has recovered

### ISSUE THREAD

**Issue by Emma-Walker** [nicehash/NiceHashMiner-Archived#362]
Nearly always when I press STOP (to stop mining) the Display Driver crashes:

Screen goes blank for 5 seconds and my Windows 7 reappears with "Display driver stopped responding and has recovered".

I tried out the two newest drivers for my NVidia KFA2 GTX 1070 (driver v375.70 and v375.95).

It does not happen always. It has never happened during an automatic algo switch. It has never happened with benchmarking, only with mining+stopping.

I use NiceHashMiner since version 1.7.3.3. But the bug exists in 1.7.3.4 and 1.7.3.5

**Comment by CreamyG31337** [comment]
any chance the card is bad or you're overclocking too much? My friend's work computer has dual video cards and one video card gets artifacts and the display driver crashes at least once a day. I don't know why but stopping nicehash causes the driver to crash quite often too, like 25% of the time maybe.

**Comment by Emma-Walker** [comment]
I didn't overclock the card. It's like bought from the shop. Moreover it happens when I press STOP, not when the algo starts or changes.

**Comment by nerdatwork** [comment]
I am facing same issue but my display driver crashes in the middle of mining. I tried everything from using so called stable version 15.7.1 to using latest driver, same issue. The only way to fix it is to use onboard agp connection for display. Use VGA to see your screen and hopefully you wont get that error. There is absolutely no help whatsoever for this error though. I have tried searching everywhere.

**Comment by Emma-Walker** [comment]
Now it crashed when I auto-switched from daggerhashimoto to another algo :(

**Comment by Emma-Walker** [comment]
Still crashes. I come back after a few hours and it's 0,0USD/day and my GPU monitor reports "Connection to GPU 1 lost".

**Comment by S74nk0** [comment]
@Emma-Walker we are still resolving this issue. It will most likely be resolved in one of the next releases. Do the machines where the drivers are crashing have only dedicated GPUs?

**Comment by kenshirothefist** [comment]
This has now been added to our internal to-do. Thank you for your feedback!

**Comment by Endacy** [comment]
I am having the same issues currently:
NiceHash Miner: v1.7.5.12
GFX card: MSI 1080 ti Gaming X
Driver version: 382.33 (and tried 382.05)
OS: Windows 7

When auto-switching algo's or when pressing stop, screen goes blank and windows shows "Display driver stopped responding and has recovered", and sometimes when it crashes the connection to the GPU is lost as well, the only way I can get it to pick up my graphics card again is by re-installing the driver and restarting NHM
