### ISSUE TITLE
[Feature] Intensity/Aggression/Aggressiveness

### ISSUE THREAD

**Issue by Emma-Walker** [nicehash/NiceHashMiner-Archived#363]
I request the ability to adjust aggression manually or automatically, so that computers with NiceHashMiner running stay usable.

**Comment by S74nk0** [comment]
Hi @Emma-Walker. [Here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters) is the wiki how to achieve what you want. If some feature is missing reopen this issue and state what feature is needed and it will be considered.
