### ISSUE TITLE
NiceHash Miner requires internet connection to run - bug

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#364]
Many times on different PCs when I try to launch NHM I get a popup saying that I do not have an internet connection. I do have an internet connection (see screenshot below) and FAH is running fine and anything else that needs the internet. If I put the shortcut to NHM in my Start folder it will not launch at boot because it hangs on this error. TIA
![nhm internet bug](https://cloud.githubusercontent.com/assets/7033982/20456176/39bd6764-ae24-11e6-87d3-e705a258f023.jpg)

**Comment by S74nk0** [comment]
@thaistar make sure that you have access to NH service locations. This pop up dialog is shown if NHM cannot access NH service.

**Comment by foxwarernd** [comment]
Check your system time. If not correct time not access to site with ssl and this error. May be add in Nhm check system time?

**Comment by ghost** [comment]
My system time is correct and synced to NIST & has never been the issue. 
"make sure that you have access to NH service locations." This comment makes no sense if you actually read what I wrote and lookd at the screenshot. I have 11 mining rigs and have no problem accessing NH. The problem is a bug in the NHM code. I've also tried checking the Settings/General/"Continue mining if no internet access" box and it still happens randomly.

**Comment by NaitorStudios** [comment]
Here's how to fix it:
I've found out that NiceHash Miner (and some other programs) can't detect internet connection when IPv4 and IPv6 are enabled at the same time.
Disable one of them and the problem should go away. I think IPv6 is better, so I let it enabled and disabled IPv4, but I don't know if there's any drawbacks.

To disable just right click the network tray icon, then click Open Network and Sharing Center.
In the window that show up, look for "Connections: " right below HomeGroup, then click whats on the right side (should be your network name).
New window, Properties, you will see a list, check or uncheck IPv6 or IPv4, you must let at least one checked.

If this helped you, you may consider a donation, here's my Bitcoin Address:
1KZZX3xfo3PoavhWvVZJPjETTbCprwqBQa

I've recorded an improvised how to video:
https://www.youtube.com/watch?v=fnZ-eoGWt74

For the developers:
NiceHash Miner can't determine with IP version to use when both are enabled, hope in a future update it get fixed so we can use both at same time and people won't freak out with this issue.

**Comment by S74nk0** [comment]
@FuurioBR thanks for pointing out the issue. This will be fixed in one of the future releases. 
Opened a new issue that references this and other related issues (#397).
