### ISSUE TITLE
Nicehash not detecting RX480 only CPU

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#365]
I cannot get Nicehash to see my GPU, can anyone help?

**Comment by S74nk0** [comment]
Hi @Johann1982. Please post the log file to see what is going on. Thanks!

**Comment by Johann1982** [comment]
Hi S74nk0

See attached log

[log.txt](https://github.com/nicehash/NiceHashMiner/files/601605/log.txt)

**Comment by mohnori** [comment]
its happen here , the miner can't detect MSI RX480.

**Comment by Johann1982** [comment]
Hi, I have managed to get it to work, but can only mine Dagerhashimo and Equihash. Just trying to benchmark the others crashes my pc. I see others are also having that issue. Maybe they will fix with next update. I ordered 2x GTX960 in the meantime, hope they work better.

**Comment by nerdatwork** [comment]
As of now only dagger is profitable for GPU. Uncheck all other algorithms and check only dagger then run the benchmark.
