### ISSUE TITLE
EQM opens mining window

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#367]
Even when Hide Mining Windows is checked in Settings eqm spawns a mining window.

**Comment by BogBeast** [comment]
Yep - I have this issue as well

**Comment by ansemz** [comment]
please read release note.

> eqm miner when Hide Mining Windows enabled ignored (will not mine if no console is shown)

**Comment by S74nk0** [comment]
**eqm** will not mine if the miner console window is hidden.

**Comment by ghost** [comment]
When I mouseover I see that. Sure would be nice to be able to hide eqm window to use NHM in background to not annoy PC users.
![image](https://cloud.githubusercontent.com/assets/7033982/20641134/68c4c53e-b3a6-11e6-9e2c-4aa28fb2ccb1.png)
