### ISSUE TITLE
Look at this problem 

### ISSUE THREAD

**Issue by dexametazon** [nicehash/NiceHashMiner-Archived#368]
![motherfuckerbug2](https://cloud.githubusercontent.com/assets/23564495/20464144/867cfd92-af57-11e6-8a5a-316e1a58400d.jpg)
after 3 or 4 hour work nicehash on the cryptonight crashed and open a lot of miner 
this server must gave me 0.10 USD/DAY but with this problem give me 0.01 USD\DAY 
and use all of the CPU 
:-1:

**Comment by fuzzfuzz** [comment]
Can confirm I'm seeing this issue as well - this morning when I arrived at work, my single miner i've upgraded to 1.7.3.5 had 6 running cpuminer windows.
It required closing each manually after terminating Nicehash.

**Comment by S74nk0** [comment]
New release fixes this issue
