### ISSUE TITLE
Benchmark problem with gtx760

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#369]
PROBLEM: nicehash offers to redo some benchmark, after I already did all of them (also cpu)
every time I start nicehash.
_________________________________________________________________________________________________________
![z01](https://cloud.githubusercontent.com/assets/16473762/20478105/63dd18d2-afe1-11e6-9e2f-36cb8d82f05e.jpg)
This image before starting program (all benchmarks done)
_________________________________________________________________________________________________________
![z02](https://cloud.githubusercontent.com/assets/16473762/20478136/7e1ef346-afe1-11e6-801f-4a09d3db88af.jpg)
This image after pushing start button. It looks benchmarks are not done. I press YES to start benchmark
_________________________________________________________________________________________________________

![z03](https://cloud.githubusercontent.com/assets/16473762/20478183/b38d9438-afe1-11e6-8c29-738cb0f161a8.jpg)
Quickly this message appears... no benchmark was actually run, but it looks that now benckmarks were completed successfully!!!
Dismissing the "Benchmark finished report" window by pushing OK button, program starts normally
_________________________________________________________________________________________________________

This happens every time I start Nicehash.
and yes, I already tried to delete the folder and restart from scratch.  Any hint? thanks

**Comment by S74nk0** [comment]
This is a very strange issue. Can you please post the log file?

**Comment by S74nk0** [comment]
@apprehensivemom According to the picture the GPU#1 is highlighted blue, that means that one of the algorithms has returned benchmark speed 0. Disable that algorithm and the benchmark loop will disappear.
Closing issue.
