### ISSUE TITLE
Suddenly 1.3.0.0 won't run any more

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#37]
![image](https://cloud.githubusercontent.com/assets/7033982/13571090/72c2f226-e427-11e5-8662-70ad1d6da255.png)

**Comment by ghost** [comment]
It will run if I display the Debug Console and Mining windows. It did not need that yesterday.

**Comment by theLosers106** [comment]
Hi,

Could you make sure you have done this: https://github.com/nicehash/NiceHashMiner/issues/36#issuecomment-193125381

If the problem still persist, please send you log.txt file to nhm@nicehash.com.

Thanks.

**Comment by ghost** [comment]
Have done what??? It's not blocked if that's what you mean.

**Comment by theLosers106** [comment]
Ohh ok.. could you post a screenshot of the details of the error.. thanks.

**Comment by Kekkonshiki** [comment]
Check your settings first for Ethereum algo: APIBindPortEthereumFrontEnd & APIBindPortEthereumProxy.
2developers: i suggest to set a default value for these parameters :-)

**Comment by theLosers106** [comment]
@thaistar this should be fixed in this dev build if you would like to test it out: https://github.com/nicehash/NiceHashMiner/issues/36#issuecomment-193622587

@SiegHeil  There is already a default set.. (:
https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Config.cs#L98

**Comment by theLosers106** [comment]
This issue has been addressed in the latest Release 1.3.0.1
https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.1
