### ISSUE TITLE
Benchmark runs all night

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#370]
I installed 1.7.3.5 on a new PC and daggerhashimoto ran all night with completing a benchmark. Also, equihash will not benchmark and times out repeatedly.

**Comment by Johann1982** [comment]
System specs?

**Comment by Johann1982** [comment]
I have noticed that benchmark takes forever when using anything less than 4GB ram. Also, win7 has some issues with benchmark. I spent the whole weekend with 4 different pc's. Figured out you need atleast 4gb ram, win 8.1 or 10.

**Comment by S74nk0** [comment]
@thaistar specify your **System specs** OS version, hardware used... without this information we cannot help.

**Comment by ghost** [comment]
Problem seems to have gone away with 1.7.3.6. I unchecked most algos since they're unprofitable anyway.
Win7 64, AMD R9 200s, FX-8350.

**Comment by S74nk0** [comment]
`Problem seems to have gone away with 1.7.3.6. I unchecked most algos since they're unprofitable anyway.
Win7 64, AMD R9 200s, FX-8350.` => Closing issue
