### ISSUE TITLE
Blocked as malicious by Chrome

### ISSUE THREAD

**Issue by alexellis** [nicehash/NiceHashMiner-Archived#373]

**Comment by S74nk0** [comment]
What version? This is a false positive.

**Comment by alexellis** [comment]
Hi - it's the release v1.7.3.5 because v1.7.3.4 was not flagged.

**Comment by Nickfost** [comment]
Eset hates every version

**Comment by S74nk0** [comment]
This issue is related to false positive AV flagging. Closing issue.
