### ISSUE TITLE
[FEATURE] Failover servers

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner-Archived#377]
It may be to make automatic switching between servers eu, usa, hk, jp, when one of them is not available? For failover...

**Comment by foxwarernd** [comment]
+++++

**Comment by ghost** [comment]
And switch back to closest server when it came back online. +++++++++++

**Comment by nicehashdev** [comment]
We will not implement this.

Our backend service is very reliable. There are some outages here and there, but these happen due to update of our systems and at the same time everywhere (so, both marketplaces are down at the same time - failover would not help).

**Comment by phrostb** [comment]
your daggerhashimoto and lyra2rev2 US servers are down
