### ISSUE TITLE
AMD RX480 unable to benchmark all algorithms

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#378]
Has the RX480 issue with benchmarking been resolved yet? The benchmark will either run forever or completely crash the computer.

**Comment by foxwarernd** [comment]
Any logs?

**Comment by Johann1982** [comment]
I'll wait till I get my other 2x RX470 cards and 1200w psu. Will re test then and see.

**Comment by batosun** [comment]
Hello. I have the same issue with benchmarking RX480 :(
[log.txt](https://github.com/nicehash/NiceHashMiner/files/613950/log.txt)

**Comment by nerdatwork** [comment]
We all face the same issue. The trick is to uncheck all algos and keep only dagger and equihash checked, run the benchmark. Since only these 2 are profitable it will work smoothly. If you want to mine a particular algo without worrying about profitability then I suggest mining it in the old fashioned console and bat file way.

**Comment by Gamingpro2006** [comment]
The unchecking benchmarks has the same effect on my miner, no matter which algos it benchmarks it crashes, then restarts the system. I cant have them sitting idle for obvious reasons, so I reverted back to 6.1.1.1 which is now the only version I can get to work as _**_you can skip the benchmarking process and start mining automatically._** 👍

**Comment by blue-yu** [comment]
Try to disable temperature control. It helped me, and now it's working like a charm...

**Comment by S74nk0** [comment]
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).
