### ISSUE TITLE
ccminer_cryptonight times out after 2 minutes

### ISSUE THREAD

**Issue by malafaya** [nicehash/NiceHashMiner-Archived#383]
Every time there is no feedback from stratum for 2 minutes, ccminer_cryptonight detects a connection timeout. This does not happen with the CPU miner which doesn't lose connection when ccminer_cryptonight does.

**Comment by S74nk0** [comment]
@malafaya we will be dropping **ccminer_cryptonight** support in the next release due to miner instability and user complaints.
