### ISSUE TITLE
Won't mine

### ISSUE THREAD

**Issue by jesdh** [nicehash/NiceHashMiner-Archived#384]
It has been running for 1 hour and it  is still at 0.00 USD/Day Do i have to do a bechmark because i didnt do 1

**Comment by nerdatwork** [comment]
Are you GPU or CPU mining ? Try to benchmark first.

**Comment by S74nk0** [comment]
@Lion048 `Do i have to do a bechmark because i didnt do 1` yes benchmark all the algorithms that you want to mine and then NHM will switch most profitable based on the hardware benchmark speeds.
Closing issue as it is not relevant to NiceHash Miner software issues.
