### ISSUE TITLE
Not mining profitabaly at ALL!!

### ISSUE THREAD

**Issue by Decimate1405** [nicehash/NiceHashMiner-Archived#385]
I'm using a gtx 1080 but still the max is 2.5USD/Day . please fix this and bring equihash back as that was more profitable for me!

**Comment by nerdatwork** [comment]
prices go up and down, you cant bring back anything like the way you want. You can mine specifically on zcash by using the console parameters shown on many youtube videos. Besides NHM works on switching profitability.

**Comment by S74nk0** [comment]
@Decimate1405 NiceHash Miner mines the most profitable algorithm based on the hardware benchmark scores and current paying rates. **equihash** is included, we are using an optimized CUDA **eqm** miner and **eqm** miner performance is improving with new releases. As for the daily profits this is not software related. It is related to current BTC to USD exchange rates and alt-coin prices (as @nerdatwork said `prices go up and down`).
Closing issue as it is not relevant to NiceHash Miner software issues.
