### ISSUE TITLE
NiceHashMiner stopped working

### ISSUE THREAD

**Issue by theeye23** [nicehash/NiceHashMiner-Archived#386]
I upgraded to 1.7.3.7 and while downloading the 3rd party binaries, the miner suddenly crashes.

![capture](https://cloud.githubusercontent.com/assets/24218732/20658580/ed8ed2fe-b578-11e6-8e3c-85ca49739218.PNG)

Do you have a separate download for the 3rd party binaries?

Thanks!

**Comment by nerdatwork** [comment]
https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/bin_1_7_3_6.zip maybe this will help

**Comment by S74nk0** [comment]
@theeye23 `Do you have a separate download for the 3rd party binaries?` yes we do they can be downloaded [here](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/bin_3rdparty_1_7_3_6.zip) (we will update release notes on this). Do you have anti virus software installed? It looks like that the AV software is flagging **claymore miner** and this is resulting in a crash. Download the 3rd party miners bins and white-list **claymore miner**. You can also download claymore miner from the links on [this thread](https://bitcointalk.org/index.php?topic=1670733.0) and unpack it into **\\bin_3rdparty\\claymore_zcash\\** under NHM folder. Closing issue reopen if the issue related to something else than AV flagging.
