### ISSUE TITLE
[BUG] AMD running/benchmarking certain algorithms (sgminer related)

### ISSUE THREAD

**Issue by S74nk0** [nicehash/NiceHashMiner-Archived#389]
Opening a new issue to reference common opened issues related to **AMD GPUs** and **sgminer** (they will be closed and referenced to this new issue to easily keep track).

### Description:
Many AMD users are reporting issues with **_most algorithms_** (all are related to **sgminer**) when bench-marking or running resulting in a **BSOD**. Most users reporting the issue seem to be using **AMD RXxxx (AMD Polaris) GPUs (RX480, RX470, etc..)**, there are also some users with older GPUs.

### Potential solutions (may not apply with all users):
  - Disabling Default optimizations. To do this go to **Settings > General > Disable Default Optimizations** and check option.
  - Disabling AMD Temperature Control. To do this go to **Settings > General > Disable AMD Temperature Control** and check option.
  - Try bench-marking/running **only** the following algorithms (Disabling **Default optimizations** and **AMD Temperature Control**, will increase stability):
    - NeoScrypt* **(will not work on Ellesmere/Polaris GPUs and will most likely BSOD with AMD Temperature Control enabled, so don't benchmark/use this one if your GPU is Ellesmere/Polaris)**
    - Lyra2REv2
    - DaggerHashimoto
    - Decred
    - Lbry
    - Equihash

### Referenced issues (closed, all new related issues should be closed and reference to this issue):
  - #246 
  - #254
  - #255
  - #258
  - #269
  - #273
  - #280
  - #286
  - #299
  - #300
  - #302
  - #340
  - #358
  - #378
  - #388
  - #303
  - #429
  - #413

**Comment by kenshirothefist** [comment]
Closing this since we made several changes with algorithms selection in latest releases.

Also, sgminer-gm issues should be [discussed here](https://github.com/nicehash/sgminer-gm/issues)

sgminer (common version) issues should be [discussed here](https://github.com/nicehash/sgminer/issues)

**Comment by jhulianni** [comment]
Nada de eso sirvió. No puedo minar con mis MSI RX570 y RX470. Cual es la solucion de NiceHash???
