### ISSUE TITLE
1.3.0.0 don't use extralaunch parametres for ethereum

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#39]
Any arguments in config for extralaunch parameters for ethereum didn't used by program when starting ethereum mining. Even parameters by default "--cl-global-work 16384 --cl-local-work 128".
In log: "[2016-03-08 01:50:48] [INFO] [AMD_OpenCL] Starting miner:  --opencl --opencl-platform 0  -F http://127.0.0.1:4052/miner/10/AMD_OpenCL --dag-dir data\AMD_OpenCL"

**Comment by theLosers106** [comment]
@UnclWish Thanks for finding that bug.. will be fixed in the next build..

**Comment by UnclWish** [comment]
Maybe temporary way to fix it or patch?

**Comment by theLosers106** [comment]
Use this if you want as it is fixed in this dev build: https://github.com/nicehash/NiceHashMiner/issues/36#issuecomment-193622587

**Comment by UnclWish** [comment]
Thanx, in this dev build bug fixed.
One more thing: pressing "Check my stats online!" during mining process opens page with stats on current mining algo. During ethereum mining it's opens not page with ethereum, but page with 1st algo Scrypt.

**Comment by Kekkonshiki** [comment]
@UnclWish #41

**Comment by theLosers106** [comment]
This issue has been addressed in the latest Release 1.3.0.1
https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.1
