### ISSUE TITLE
[FEATURE] NH thinks I'm idle when watching a movie

### ISSUE THREAD

**Issue by p1r473** [nicehash/NiceHashMiner-Archived#392]
Hi,
Can we get better idle detection for when we are watching a movie?
I was using both the VLC app, and Netflix app, and NiceHash kicked in because it thought I was idle. I had to go into settings, disable idle detection, then I was able to continue my movie. When NiceHash runs, the movie is unwatchable due to frame drops.

Maybe it can detect certain apps (VLC/Netflix) or full screen mode detection?

**Comment by auroracoin** [comment]
Yes please Nicehash .. I believe it's called intensity setting -i then I could hash with my other card.

**Comment by semisane** [comment]
Is it possible to just disable the CPU mining while using these apps?

**Comment by p1r473** [comment]
Well I am using gpu mining only and it was still choppy for me while watching 
Its not that I want to lower the intensity when watching a movie, I want it disabled. Idle detection isn't working
Maybe have an option to mine only when windows is locked?

**Comment by S74nk0** [comment]
@p1r473 this feature request has been taken into consideration. We are evaluation how to achieve this.

**Comment by S74nk0** [comment]
Closing issue. Opened a new issue related to **Mining when Idle Feature update** that coveres this issue as well. Post all new suggestions or related problems to the new opened issue here #398
