### ISSUE TITLE
Lower intensity on 3rd party miner

### ISSUE THREAD

**Issue by semisane** [nicehash/NiceHashMiner-Archived#395]
The intensity setting on Claymore miner @ 4 is causing a lot of rejected sol/s - around 200.

Running 4x 480's. When mining just on Claymore it's easy to set -i 2 but I don't see this option in NHM

Any help would be appreciated!

**Comment by tmslacker** [comment]
I'm running 3 system with 2x video cards each.  I have 2x system running 2x AMD 480 Each.  I've noticed the drop.  They start at 360+ Sol/s and slowly drop!  I need to restart about once an hour!!!! 

I'm going from almost $12 a day to $7!  or 1200 Sol/s to 800 Sol/s.

**Comment by semisane** [comment]
I'm also having the same thing. When I run Claymore by itself I can set the intensity to 2 which is great. I need to know how to do this within NHM

**Comment by S74nk0** [comment]
@semisane, @tmslacker this can be achieved. [Here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters) is an overview what flags are supported from NHM and [here are claymore's settings](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#amd-claymorezcash-equihash). If you have multiple GPUs make sure to input the settings for every GPU you are using, if you have multiple identical GPUs you can configure only one and copy the settings to the rest (right click on a device and a context menu should appear). 
[Here](https://github.com/nicehash/NiceHashMiner/issues/284#issuecomment-263567845) is an example how to set Extra launch parameters (this one is for NVIDIA ccminer). 
The instructions provided should solve the intensity setting problem.
Closing issue.
