### ISSUE TITLE
Profitability Chart; Sucks! 

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#396]
I have a 1080, 980 Ti and 4x 480 seem off!  Like Sol/s 0? for EquiHash!

**Comment by semisane** [comment]
What are the logs saying?

**Comment by tmslacker** [comment]
https://www.nicehash.com/index.jsp?p=calc

When I check out 1080 or 980 TI; it show 0 Sol/s
or
When I check out 480; it shows 35 Sol/s

Mining and Hashing is really easy, but getting started is hard.  

This isn't the right forum, but I don't know how to remove my post.

Sorry.

**Comment by semisane** [comment]
Oh! Gotcha, you're using the calculator. I don't think it's actually updated for equihash but I could be wrong.
My 1080/980Ti/980/970 are having better profit with Lyra2Rev2 
and my 4x 480's are mining zcash and daggerhashimoto. 

I do find that after benchmarking in NHM the profitability is much more accurate.

**Comment by S74nk0** [comment]
The profitability calculator data is old and in some cases outdated (**nheqminer** gives 35 Sols/s). You can benchmark your hardware from NHM and submit it to check profits based on your specific hardware setup and specific benchmarks.
Closing issue.
