### ISSUE TITLE
[FEATURE UPDATE] - Mining when Idle

### ISSUE THREAD

**Issue by S74nk0** [nicehash/NiceHashMiner-Archived#398]
Opening a new issue to reference common opened issues related to **Mining when Idle Feature** (they will be closed and referenced to this new issue to easily keep track).

### Description:
A feature upgrade based on user suggestions. Update idle checking logic to detect **Gaming controller** (#163) usage and **Full screen media application** activity (#392). Update Idle mining policy to disable only primary GPU (#264) or only the [CPU](https://github.com/nicehash/NiceHashMiner/issues/392#issuecomment-264105176). To achieve this it would be best to add an option to choose **Idle mining policy** keep the current **default** one and add a **new custom** policy where the user would specify which CPUs/GPUs to disable when idle mining is resumed (similar to enabling/disabling devices), and which to continue mining. Related features to this would be to add **Mine during time periods** (#349) and **cooldown** intervals (this suggestion comes from social channels).

### Solution:
Create a new Mining policy (maybe some different name) setting to NiceHash Miner based on the description. **User suggestions/constructive criticism are also welcomed**.

### Referenced issues (closed, all new related issues should be closed and reference to this issue):
  - #392
  - #163
  - #264
  - #349

**Comment by jmv1** [comment]
One nice feature related to this would be that you could define list of applications and if NiceHashMiner detects one of those running it would stop mining.

**Comment by kenshirothefist** [comment]
This has now been added to our internal to-do. Thank you for your feedback!

**Comment by nathanielcwm** [comment]
would like an eta on how far you guys are going with this. tho im pretty sure you already have a lot of work on your hands with the fact that you guys got hacked and stuff

**Comment by jpmckearin** [comment]
So this was moved internally, hasn’t been implemented, and all of the issues concerning it are closed?
