### ISSUE TITLE
1.3.0.X & Ethereum - current balance isn't calculated

### ISSUE THREAD

**Issue by Kekkonshiki** [nicehash/NiceHashMiner-Archived#40]
in JSON balance for Ethereum in the value "**balance_confirmed**"
`{"balance_unexchanged":"0.00000000","rejected_speed":"0.00000000","balance_immature":"0.000000000","algo":999,"accepted_speed":"0.00000000","balance_confirmed":"0.00000000"}`

**Comment by cgladue** [comment]
i know nicehash treats etherium seperatly (seperate payout) so maybe that has something to do with it

**Comment by theLosers106** [comment]
@SiegHeil : Yes I have found where this bug is located and will be fixed in the next release.. thanks for reporting it.. (:

@cgladue : Made a mistake while parsing the json data that's all..

**Comment by theLosers106** [comment]
This issue has been addressed in the latest Release 1.3.0.1
https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.1
