### ISSUE TITLE
After Selecting P0 and saving/restarting.  Doesn't save?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#400]

**Comment by S74nk0** [comment]
@tmslacker what does not get saved exactly? The NiceHash Miner settings or P0 state doesn't get set?

**Comment by casparov-man** [comment]
Hi, im having same problem on 2 different machines, but without the NVIDIA P0 setting evolved. The program after being closed, and then re-opened, restarts has if it was the first time, asking for the language, third party miners acceptance, but does not download the miners again, and doesn´t save settings.

**Comment by tmslacker** [comment]
What he said,

**Comment by happyartifact** [comment]
Looks to me like it's not either creating or modifying the configs folder.

**Comment by p1r473** [comment]
Did you run the program as admin?

**Comment by tmslacker** [comment]
didn't help

**Comment by tmslacker** [comment]
it not saving any settings.

**Comment by nicehashdev** [comment]
This is a bug and will be fixed with new version tomorrow morning CET time.

**Comment by tmslacker** [comment]
I fixed it by just creating a configs folder.

**Comment by S74nk0** [comment]
New [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.3.9) has been pushed to fix this critical issue.
