### ISSUE TITLE
mines all the time

### ISSUE THREAD

**Issue by easye35** [nicehash/NiceHashMiner-Archived#403]
even though I have selected mine when idle, it's mining constantly.  worked great before the update

**Comment by S74nk0** [comment]
@easye35 have you started the miner manually? Due to user request this was added #345. If you started the miner manually then it will ignore resuming from idle mode unless stopping it manually.

**Comment by easye35** [comment]
So how do I load this then. I want it to only mine when idle? Do I click
the start button?

**Comment by S74nk0** [comment]
Set the Minimun Idle time. Go to Settings > Advanced > Minimum Idle and set the time. After that time elapses it is considered that the machine is in idle mode an will start mining.
Closing issue

**Comment by easye35** [comment]
It says 60 there already

**Comment by S74nk0** [comment]
That means that after 1 minute if there aren't any mouse or keyboard interactions it will start mining

**Comment by easye35** [comment]
I understand that, then why is it mining before the 60 secs? That's the
whole problem, it isn't stopping mining when I start to use computer

**Comment by easye35** [comment]
Deleting and reinstalling. See if that fixes it
