### ISSUE TITLE
Latest Version doesn't do anything when I hit "start"

### ISSUE THREAD

**Issue by stealthmachines** [nicehash/NiceHashMiner-Archived#405]
Gigabyte RX 480 8gb x 4, CPU miner disabled, MSI Z97 Gaming5 mobo.  Version x.x.x.7 worked great!

**Comment by S74nk0** [comment]
@stealthmachines Make sure that there are bench-marked algorithms or at least one enabled Algorithm per device. The log file would also help.

**Comment by stealthmachines** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/628563/log.txt)

Tried benchmarking and running again with only equihash on only one 480, same result.

**Comment by S74nk0** [comment]
From the logs
`Disabled Devices:
	DISABLED: CPU#1 Intel(R) Celeron(R) CPU G1840 @ 2.80GHz
	No Enabled Algorithms: GPU#1 Radeon (TM) RX 480 Graphics
	No Enabled Algorithms: GPU#2 Radeon (TM) RX 480 Graphics
	No Enabled Algorithms: GPU#3 Radeon (TM) RX 480 Graphics
	No Enabled Algorithms: GPU#4 Radeon (TM) RX 480 Graphics`

CPU is disabled but looks like that no algorithm is enabled or that there aren't any benchmarks done. Look at the benchmarks or settings and confirm if there are enabled algorithms.

**Comment by huidoo** [comment]
need benchmark before start

**Comment by S74nk0** [comment]
The reason for the confusion is that the notification for a needed benchmark or enabled algorithms is broken in 1.7.3.9. [7484aa8](https://github.com/nicehash/NiceHashMiner/commit/7484aa818581c6e52d9bfec7f907437d0f885256) fixes the UX issue.
Closing issue...
