### ISSUE TITLE
[BUG] EQM can't hide itself while mining

### ISSUE THREAD

**Issue by NaitorStudios** [nicehash/NiceHashMiner-Archived#408]
Basically, the option to hide mining windows is not working for eqm.

**Comment by nicehashdev** [comment]
And it never will. It is part of the anti-botnet protection.

**Comment by FuurioBR** [comment]
Question: If doesn't work if hidden?
Because I've made an small program to hide it.

**Comment by FuurioBR** [comment]
Can I share it?
![image](https://cloud.githubusercontent.com/assets/12569002/20862520/4bc1c858-b994-11e6-9b2d-7758e4d6f2b0.png)

**Comment by NaitorStudios** [comment]
I get it, you mean that people could try to hide it on someones pcs, right?
Is it what anti-botnet protection is trying to prevent?
Ok then.

**Comment by NaitorStudios** [comment]
I have a better way to prevent botnet and add these features for people that has no bad intentions though.
