### ISSUE TITLE
1.3.0.X & Ethereum - "Check my stats online!"

### ISSUE THREAD

**Issue by Kekkonshiki** [nicehash/NiceHashMiner-Archived#41]
browser opens URL, where the parameter "&a = 19", but for Ethereum "&a = 999"

**Comment by theLosers106** [comment]
This will be fixed in the next release.. thanks for reporting it.. (:

**Comment by theLosers106** [comment]
This issue has been addressed in the latest Release 1.3.0.1
https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.1
