### ISSUE TITLE
[FEATURE] Please add IPFS hashes to the download links.

### ISSUE THREAD

**Issue by Nickfost** [nicehash/NiceHashMiner-Archived#410]
Please add IPFS hashes to the download links. The download usually times out and cancels.

**Comment by NaitorStudios** [comment]
When downloading miners or when checking profitability?
It doesn't say "NiceHash Miner requires internet connection to run.", right?

**Comment by Nickfost** [comment]
In the release notes. If ipfs functionality could be added to the miner application that would be great! i have internet. i don't have fast internet and GH times you out after 10 mins or so.

**Comment by NaitorStudios** [comment]
I see, I just mentioned because usually NiceHash Miner can't detect internet with both IPv4 and IPv6 enabled, but it only fails on profitability and other data, not downloading miners.
You could try though.

**Comment by Nickfost** [comment]
Not talking about the program at all. i'm talking about where the zip of miner files is hosted. It would be nice if it were hosted on the IPFS network rather than GH servers and served over HTTP

**Comment by Nickfost** [comment]
EX: instead of http://GH/files.zip use IPFS://Blob.zip
![image](https://cloud.githubusercontent.com/assets/1572453/20862587/8c7e7604-b974-11e6-9f74-b5d9ee167523.png)

**Comment by NaitorStudios** [comment]
Oh, never heard of IPFS, but sounds appropriate.
Mine couldn't download the miners the first time with the newest version, closing it and relaunching fixed.
Bigger timeout limit or even an option to choose it would be nice.

**Comment by Nickfost** [comment]
IPFS is a protocol aimed at becoming a standard. if we could just use the existing network protocols in our programs we can have much more resilient network connections capable of resuming during errors. I don't know C. My main language is PHP. but if I could do this I would. as a community of developers, we MUST stop assuming everyone has a perfect network connection. everything must be resumable and redundant. if IPFS goes mainstream it will put CDNs out of business. for now, we can use it in our applications to make them more reliable with a flakey network and all network situations

**Comment by Nickfost** [comment]
> Bigger timeout limit or even an option to choose it would be nice.
 @FuurioBR 

This is set by GH's HTTP servers. Eliminating HTTP with IPFS fixes this at the root of the problem by removing a centralized service with any say in how we obtain the file.

**Comment by NaitorStudios** [comment]
Got it, so they must fix this as soon as possible I think.

**Comment by Nickfost** [comment]
I'm unsure if there is a public LIB for IPFS-c so maybe the best they could do right now is at least provide us a blob with the hash so we can go retrieve it ourselves. if a LIB is avail it would be trivial i would imagine.

**Comment by Nickfost** [comment]
Related #236

**Comment by kenshirothefist** [comment]
This has now been added to our internal to-do. Thank you for your feedback!
