### ISSUE TITLE
Reset error

### ISSUE THREAD

**Issue by cenkut** [nicehash/NiceHashMiner-Archived#411]
06:24:12:114	15c4	watchdog - thread 0, hb time 15
06:24:12:114	15c4	watchdog - thread 1, hb time 47
06:24:12:114	15c4	watchdog - thread 2, hb time 140
06:24:12:129	15c4	watchdog - thread 3, hb time 93
06:24:12:129	15c4	watchdog - thread 4, hb time 76937
06:24:12:129	15c4	WATCHDOG: GPU 1 hangs in OpenCL call, exit
06:24:12:129	15c4	watchdog - thread 5, hb time 77078
06:24:12:145	15c4	WATCHDOG: GPU 1 hangs in OpenCL call, exit
06:24:12:145	15c4	watchdog - thread 6, hb time 77109
06:24:12:145	15c4	WATCHDOG: GPU 1 hangs in OpenCL call, exit
06:24:12:160	15c4	watchdog - thread 7, hb time 77031
06:24:12:160	15c4	WATCHDOG: GPU 1 hangs in OpenCL call, exit
06:24:13:192	15c4	Restarting failed: error 87

i use NiceHashMiner_v1.7.3.7 , NiceHashMiner_v1.7.3.8 and NiceHashMiner_v1.7.3.9 but "Restarting failed: error 87" this error not fixed. RX 480 x2 and PowerSupply 600W 80+Thermalte

**Comment by ghost** [comment]
Do you have the latest driver installed???
non-whql-win7-64bit-radeon-software-crimson-16.11.5-nov25.exe

**Comment by S74nk0** [comment]
@cenkut this looks like an error in the 3rdparty closed source miner. There is a **Readme!!!.txt** file under **bin_3rdparty\claymore_zcash** check if you have the minimum requirements and recommended setup. The RX 480 cards surely must work with this miner as it was tested. As for the restarting error this should be addressed to the developer [Claymore](https://bitcointalk.org/index.php?action=profile;u=306958) as this is related to his closed source miner that we cannot change/improve/fix.
Closing issue...

**Comment by Norlpz** [comment]
I am having the same problem. con rx570

**Comment by Norlpz** [comment]
@cenkut Could you solve  it?

**Comment by Norlpz** [comment]
![333](https://user-images.githubusercontent.com/35514163/35080965-67ce1524-fbe7-11e7-88fe-243d684b1596.png)
