### ISSUE TITLE
Brake gen hwid

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#412]
I downloaded Nhm 1.7.3.9 on the same computer, open it (in the folder "configs" appeared files - including General.json) and copied to other PCs. And now, every time you run prompts for confirmation run on this PC. It helps remove General.json file. Please fix

**Comment by ghost** [comment]
I delete the entire folder C:\NiceHashMiner_v1.7.3.9\configs. I then copy the entire folder C:\NiceHashMiner_v1.7.3.8\configs and paste it into C:\NiceHashMiner_v1.7.3.9.
Not the contents of the folder but right-click on the folder itself.

**Comment by foxwarernd** [comment]
Super. And what I wrote) to version 1.7.3.7 Previously there were no problems in the same situation. And here there is a problem

**Comment by S74nk0** [comment]
This error is fixed and will not happen with the future releases.
