### ISSUE TITLE
Nicehash Miner v1.7.3.9 Gtx 950/750 TI problem with cryptonight algo

### ISSUE THREAD

**Issue by anonymous890890543** [nicehash/NiceHashMiner-Archived#415]
Windows 10 64bit
Last nvidia driver updated 

cryptonight, start mining but its weird, it give me 37249.79 EUR of profit

**Comment by enavarrocu** [comment]
I have the same problem with cryptonight algo. Your other issue is not related to the NiceHash miner itself.

**Comment by anonymous890890543** [comment]
enavarroucu,lyra2rev2 its working for you?
What is your Service location?
Do you have gtx 950 ?

**Comment by enavarrocu** [comment]
Yes lyra2rev2 is working. I have a 750 TI giving the same issue with the hash rate.

**Comment by anonymous890890543** [comment]
ok thanks it was my firewall its working now

**Comment by S74nk0** [comment]
When getting very high hash rates (and profits) with NVIDIA **CryptoNight** disable it for that GPU as it is not mining correctly. 
Closing issue...
