### ISSUE TITLE
GPU not mining, but CPU is

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#418]
So I just installed Nicehash, and I tried to start mining with my GTX 970. It didn't start, nothing happened. My CPU however did start mining. Both the CPU and GPU is detected, the GPU drivers are up to date, I even reinstalled them.

**Comment by S74nk0** [comment]
@192uijo Please provide the log files it would helpto see what is the issue. Most likely the GPU doesn't have any algorithms enabled or they aren't benchmarked.

**Comment by 192uijo** [comment]
Alright, I actually just benchmarked it and enabled some algorithms. It works now, thanks.

**Comment by S74nk0** [comment]
The reason for the confusion is that the notification for a needed benchmark or enabled algorithms is broken in 1.7.3.9. [7484aa8](https://github.com/nicehash/NiceHashMiner/commit/7484aa818581c6e52d9bfec7f907437d0f885256) fixes the UX issue.
Closing issue
