### ISSUE TITLE
1.7.3.9 switch algorithm ethminer didn't close properly, hide mining windows didn't work with eqm

### ISSUE THREAD

**Issue by can99** [nicehash/NiceHashMiner-Archived#419]
gpu: amd rx 470 4gb
when switching algorithm, ethminer window didn't close properly
![image](https://cloud.githubusercontent.com/assets/20637900/20864902/187a93e8-ba35-11e6-8d35-9a65df1e4b78.png)

gpu:nvidia gtx1060
eqm windows shown even when hide mining windows is checked on option
![image](https://cloud.githubusercontent.com/assets/20637900/20864911/c968c2d8-ba35-11e6-96be-802e4331361e.png)
![image](https://cloud.githubusercontent.com/assets/20637900/20864910/c372e778-ba35-11e6-85e9-d89936721fbf.png)

**Comment by S74nk0** [comment]
Regarding ethminer issue read here https://github.com/nicehash/NiceHashMiner/issues/420#issuecomment-264725505. As for eqm not hiding this is intentional because **eqm** will not mine when the console window is hidden.
Closing issue...
