### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by JPBoggis** [nicehash/NiceHashMiner-Archived#42]
I have been using NIceHashMiner for a while and find it a great way of making the best of the hardware in my gaming PC when it's not in use to earn Bitcoin.

I have a few suggestions for some improvements/fixes:

Could NiceHashMiner be updated to take the current average rate for the algorithm currently being mined (As shown on GUI) into account when deciding to switch? (After 1 minute or so to allow the rate to settle.)  So if the rate drops below the calibrated value, it can switch to a different algorithm.

Currently NiceHashMiner uses the calibrated values to decide which algorithm to mine and when to switch to a different (More profitable) algorithm.  However, I have found that for some algorithms the calculated value can be inaccurate and the actual rate when mining can vary.

In particular, the calibrated values for Neoscript and the new Etherium for my system are twice the actual average I get once it settles down (After a few minutes of mining).  In both cases, when mining it will start off at a higher rate and then gradually settle down to a lower average (Usually half the initial rate.)  Quark also sometimes (But not always) halves in rate after 5-10 minutes of minutes.

In all these cases, it will keep mining without switching because it assumes it's still getting the calibrated rate when it could switch to a more profitable algorithm.  As a work around, I currently have to manually edit the values to half after calibration and use a scheduled task to kill the miner every 15 mins to work around the Quark problem.

If it took the current rate for the active algorithm into account, these problems would be avoided.  It would also be useful if it could update the calibrated value with the actual average it gets when mining which in time would allow it to work with more accurate/realistic figures and take into account changes in system performance automatically.

Also, could there be an option added to mine at a reduced intensity when the PC is in use (Detected by mouse and keyboard activity)?  This would allow mining to continue in the background at a reduced rate when the PC is in use with less effect on the user.  Currently most of the algorithms make the PC very laggy to use (E.g:  For web browsing) and in the case of Etherium it's unusable.

**Comment by cgladue** [comment]
i kinda like the idea of having an auto benchmark ... so if the benchmark values are reset to zero then use the actual mining rate over a peroid of some time to set the benchmark value, or do the benchmark so it gets a rough idea of how your setup performs, but then adjust that over time as the client runs, as i too have had to go and manually raise or lower the benchmark value to the actual performance of my rig so i dont switch when i dont think i should.

**Comment by kenshirothefist** [comment]
Any kind of automation can only be done up to a particular level. We've spent significant effort to make benchmarking as good as possible, but it can't be made ideal. First of all, make sure to run Precise benchmark if Standard benchmark is not giving you satisfactory results. If you still see a deviation of actual mining speed from the one, calculated from benchmark, then you should manually enter these observed speed numbers from actual mining into config.json file or set them via the "Settings" button.

**Comment by kenshirothefist** [comment]
I'll be closing this issue, see my previous reply for workarounds, but we'll take the proposals into account for the future releases. Thanks for the feedback!
