### ISSUE TITLE
Seems ethminer doesnt stop

### ISSUE THREAD

**Issue by Nickfost** [nicehash/NiceHashMiner-Archived#420]
![image](https://cloud.githubusercontent.com/assets/1572453/20865445/b8ac1ec6-b9d7-11e6-858d-9ce2562fedcd.png)

**Comment by S74nk0** [comment]
If ethminer stays opened and does not continue mining than this is expected, the reason ethminer window stays open is to keep the DAG data in memory so when it resumes mining it doesn't need to generate it again saving time and continues mining right away. Looking at the provided picture everything seems to be in order (ethminer window message **An established connection was aborted by ...**), ethminer is paused and eqm is mining. If ethminer is giving hashes and/or you see a significant hash drop from the other active miner **eqm** in this case than there is a problem here.
Looking at the provided picture everything seems to be in order. 
Closing issue... reopen if ethminer is giving hashes and/or you see a significant hash drop from the other active miner.
