### ISSUE TITLE
Missing algorithms for gpu in 1.7.3.8/1.7.3.9

### ISSUE THREAD

**Issue by bovcan** [nicehash/NiceHashMiner-Archived#421]
In version 1.7.3.7 I have this algos under gpu
![fee2e850be536edf216ce05191d50b5d](https://cloud.githubusercontent.com/assets/23615538/20866853/82233a1e-ba37-11e6-8ac2-6d5b3eb6a188.png)

but in 1.7.3.8/9 only this one
![1ea7d899413ffee7bdabe4ca7b100947](https://cloud.githubusercontent.com/assets/23615538/20866868/b028929c-ba37-11e6-8e20-0ee298737d74.png)

Do I miss something, or this algos were removed?

**Comment by S74nk0** [comment]
The missing algorithms are removed because there are not profitable as the other ones. This is intentional [commit](https://github.com/nicehash/NiceHashMiner/commit/363be687a6b1943e1781d931a8097142aa9d2204)

**Comment by bovcan** [comment]
ok.. but I had better profitability with keccak.

**Comment by Dave-MNC** [comment]
Sorry to comment on a closed case, but I would like to see the LyraRE algorithm back for NVidia cards.
There have been a number of times where the LyraRE smashes the profitability of LyraRE2.
