### ISSUE TITLE
Which Address? (Using Coinbase)

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#422]
I've been mining for a bit now. I just started to wonder if I'm using the correct "Bitcoin Address". When I went to **Coinbase**, my balance was still zero cents and zero dollars. I wasn't sure if I was actually using the correct address so I started worrying.

The address that I copied and paste was the address under the "tools" tab. It just said the address name and how long ago was it created. Now I looked at the "accounts" tab and saw _"BTC Wallet", "ETH Wallet", and "BTC Vault"_. I assumed I just used the wrong address so I took the "BTC Vault" address and pasted it into the miner. I'm still not sure if that's the right address, which one is it?

**Comment by NaitorStudios** [comment]
It doesn't mine directly to your wallet, it mines the most profitable algorithm / coin, then it convert to bitcoin and then it send to your wallet.

You can see your progress and when you'll receive your bitcoins through this link, you need to add your wallet address in front of it:
https://www.nicehash.com/index.jsp?p=miners&addr=

**Comment by NaitorStudios** [comment]
Oh, and the right one is BTC Wallet in this case.
You must avoid changing wallet address whenever possible, since you lose track of your stats and may also lose progress.

**Comment by S74nk0** [comment]
@192uijo you need a BTC address put that in benchmark all your devices and you are ready to mine. 
Closing issue...
