### ISSUE TITLE
Unable to connect to stratum server

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#423]
Hi

I have been having issues connecting to stratum servers for the last 40mins. I have 2x pc's running nicehash mining equihash. When pc 1 is running pc2 won't connect. If I stop pc1, pc2 connects. I cannot get both to run.
![ip and port](https://cloud.githubusercontent.com/assets/23583570/20894535/86815c0c-bb1e-11e6-8538-25f93dc80ff9.jpg)

Can anyone assist?

**Comment by S74nk0** [comment]
The issue was opened then closed. What was the issue and what was the fix?

**Comment by Johann1982** [comment]
Hi, issue was fixed. Had my ISP route my other pc onto a different public
ip.
