### ISSUE TITLE
Not honoring StartMiningWhenIdle - v1.7.3.9

### ISSUE THREAD

**Issue by BogBeast** [nicehash/NiceHashMiner-Archived#424]
Hi,

Kept my configs folder when upgrading to v1.7.3.9

I use the  Start Mining when idle option, but now each time it starts  it commences mining equihash straightaway 

  "ConfigFileVersion": {
    "Major": 1,
    "Minor": 7,
    "Build": 3,
    "Revision": 9,
    "MajorRevision": 0,
    "MinorRevision": 9
  },
  "Language": 0,
  "DisplayCurrency": "GBP",
  "DebugConsole": false,
  "BitcoinAddress": "",
  "WorkerName": "PC",
  "ServiceLocation": 0,
  "AutoStartMining": true,
  "HideMiningWindows": true,
  "MinimizeToTray": true,
  "ForceCPUExtension": 0,
  "SwitchMinSecondsFixed": 90,
  "SwitchMinSecondsDynamic": 30,
  "SwitchMinSecondsAMD": 90,
  "MinerAPIQueryInterval": 5,
  "MinerRestartDelayMS": 500,
  "BenchmarkTimeLimits": {
    "CPU": [
      10,
      20,
      60
    ],
    "NVIDIA": [
      10,
      20,
      60
    ],
    "AMD": [
      120,
      180,
      240
    ]
  },
  "DeviceDetection": {
    "DisableDetectionAMD": true,
    "DisableDetectionNVIDIA": false
  },
  "DisableAMDTempControl": false,
  "DisableDefaultOptimizations": false,
  "AutoScaleBTCValues": true,
  "StartMiningWhenIdle": true,
  "MinIdleSeconds": 90,
  "LogToFile": true,
  "LogMaxFileSize": 1048576,
  "ShowDriverVersionWarning": true,
  "DisableWindowsErrorReporting": true,
  "NVIDIAP0State": true,
  "ethminerDefaultBlockHeight": 2000000,
  "EthminerDagGenerationType": 0,
  "ApiBindPortPoolStart": 4000,
  "MinimumProfit": 0.0,
  "ContinueMiningIfNoInternetAccess": false,
  "DownloadInit": true,
  "Use3rdPartyMiners": 2,
  "DownloadInit3rdParty": true,
  "AllowMultipleInstances": false,
  "LastDevicesSettup":

Is in the JSON 

Is there anythingthat needs tweaking ?

**Comment by BogBeast** [comment]
Just seen duplicate - sorry

**Comment by S74nk0** [comment]
@BogBeast no problem. Look [here](https://github.com/nicehash/NiceHashMiner/issues/404) it is just a change of logic,
