### ISSUE TITLE
[BUG] Nvidia Driver comparison not handled correctly 

### ISSUE THREAD

**Issue by NaitorStudios** [nicehash/NiceHashMiner-Archived#425]
It still says "We have detected that your Nvidia Driver is older than 372.54 (current 376.19). We recommend you to update to 372.54 or newer." though.

**Comment by S74nk0** [comment]
@FuurioBR this is clearly a BUG with comparing NVIDIA driver versions. It will be fixed in a future release. Thanks for pointing it out.

**Comment by Nickfost** [comment]
![image](https://cloud.githubusercontent.com/assets/1572453/20915304/b47821d2-bb4a-11e6-8f96-d560f2b34d66.png)

10 / 10

**Comment by S74nk0** [comment]
[commit](https://github.com/nicehash/NiceHashMiner/commit/9e61ee5e93f673aa8ab89f497360222dfba71246) fixes the issue. It will be included with the new NHM release
