### ISSUE TITLE
Miner problem since 1.7.3.6 and above

### ISSUE THREAD

**Issue by nightmaker** [nicehash/NiceHashMiner-Archived#427]
Since v1.7.3.5, I couldn't upgrade to latter version of miner.
Most stable and high hashrate for my rig for now is v1.7.3.3.

MY rig has 2X CPU (Intel Xeon X5675) and 1 GPU (NVIDIA Quadro 6000).

Problem I faced according to version:-

v1.7.3.5:
- all CPU working good
- GPU on cryptonight has lower hashrate compared to v1.7.3.3

![1735](https://cloud.githubusercontent.com/assets/23731947/20914313/c54b70ee-bbb9-11e6-994e-e8e4ac0301e8.PNG)

v1.7.3.7:
- miner (cryptonight) only mine on 1 CPU even after I tried to benchmark several times, and carefully check that both CPU is selected for mining.
- GPU on cryptonight is OK

![1737](https://cloud.githubusercontent.com/assets/23731947/20914314/c54dbef8-bbb9-11e6-8bbf-1c8b5cede79f.PNG)

v1.7.3.9
- CPU mining is OK for both CPU
- GPU mining cannot select cryptonight on benchmark and settings

![1739](https://cloud.githubusercontent.com/assets/23731947/20914315/c57256d2-bbb9-11e6-9ea8-e073dec7cf1f.PNG)

**Comment by S74nk0** [comment]
@nightmaker cryptonight was removed for NVIDIA SM2.1 because it has proven to be very unstable. The printing BUG was not present for a while now, can this be reproduced on earlier versions (did this happen after some driver install)?

**Comment by nightmaker** [comment]
No I did not install any new driver.
So I guess the new version did not have any problem running on my rig.
Except of lack of cryptonight.

Looking forward for new version with cryptonight for NVIDIA cards.. Cheers.
Thanks!

**Comment by S74nk0** [comment]
@nightmaker I understand now. We might reintroduce it back for NVIDIA SM2.1. But it has been very unstable altogether.
Closing issue...
