### ISSUE TITLE
Sapphire Radeon  RX470 BSOD  system service error  ATIKMDAG

### ISSUE THREAD

**Issue by soldier3** [nicehash/NiceHashMiner-Archived#429]
Whan i runing  Benchmark in NiceHash Miner v1.7.3.9  (v1.7.3.8 v1.7.3.7)
Sapphire Radeon  RX470 nitro 4GB . Windows 10 x 64 
I get BSOD  system service error  ATIKMDAG
I tray:
- reinstall Windows 10 x 64 
-  driver install form Windows update or Amd.com 
 - different system on CPU  AMD (Athlon 3x ) and INTEL (Core i3-4xxx )
Video card work only with MSI B150 pro-hdv  + Core i5 6600, Windows 10 x 64

**Comment by S74nk0** [comment]
@soldier3 Disable all algorithms except **DaggerHashimoto** and **Equihash**. **sgminer** is failing with AMD **Polaris** GPUs. Also refer to [this issue](https://github.com/nicehash/NiceHashMiner/issues/389)
