### ISSUE TITLE
EthMiner Doesn't work on any of my machines

### ISSUE THREAD

**Issue by swagkiller69** [nicehash/NiceHashMiner-Archived#43]
When trying to run the eth miner, one way or another I get given this error
Sometimes I see a little black cmd box appear and dissapear very quickly.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at NiceHashMiner.Miner._Start()
   at NiceHashMiner.Miner.Restart()
   at NiceHashMiner.Form1.MinerStatsCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

NiceHashMiner
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
##     CodeBase: file:///C:/Users/_/_/*/NiceHashMiner.exe

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5495 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll

Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
##     CodeBase: file:///C:/Users/_/_/*/Newtonsoft.Json.DLL

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5494 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll

log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
##     CodeBase: file:///C:/Users/_/_/*/log4net.DLL

System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

`
That's on my GTX 970M
On my GTX 970 Desktop, it asks for permission to run the eth-proxy and the other exe, they flash up for under a second and i get the same issue
This is happening to my friend also

**Comment by Kekkonshiki** [comment]
try that #37

**Comment by swagkiller69** [comment]
Setting a dir for the DAG file seems to have fixed the issue.

**Comment by swagkiller69** [comment]
The DAG finished being created and now when I try to mine I get a connection error (to the proxy)

**Comment by Kekkonshiki** [comment]
@swagkiller69 check settings in config.json: APIBindPortEthereumFrontEnd & APIBindPortEthereumProxy
https://github.com/nicehash/NiceHashMiner/issues/37#issuecomment-193644576

**Comment by theLosers106** [comment]
@swagkiller69 What do you mean by:

> Setting a dir for the DAG file seems to have fixed the issue.

Is it empty in the config.json file?

**Comment by theLosers106** [comment]
@swagkiller69 is your problem solved yet?

**Comment by swagkiller69** [comment]
Fixed it myself
