### ISSUE TITLE
[FEATURE] add 3rd party cryptonight miner for AMD 

### ISSUE THREAD

**Issue by BobDoe** [nicehash/NiceHashMiner-Archived#430]
adding claymores zec miner was great idea could you also add claymores cryptonight miner

**Comment by BobDoe** [comment]
also upgrade to V 9 of zec miner

**Comment by S74nk0** [comment]
@BobDoe we will consider adding claymores cryptonight miner. As for the V 9 of zec miner upgrade of course we will do this. Although you probably don't have to wait for the next release of NHM, you can just replace the contents of the current folder (**bin_3rdparty\claymore_zcash**) with V 9 of zec miner and it will work (drop in replacement).

**Comment by BobDoe** [comment]
Thanks I will drop in V9 ZEC.  Any reliable and fast Cryptonight miner for AMD Cards will do. You know better than I what would be BEST. Thanks for all your hard work, top hat :)

**Comment by Johann1982** [comment]
Hi, Just out of curiosity.. Where can I download V9 Zec?

**Comment by S74nk0** [comment]
@Johann1982 read [here](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.3.9)

**Comment by Johann1982** [comment]
Thanks S74nk0, got it.

**Comment by Johann1982** [comment]
wow, it actually make a big difference. 15 to 20% increase.

**Comment by S74nk0** [comment]
Next release will have this miner ([commit](https://github.com/nicehash/NiceHashMiner/commit/91acd373d5b9af5f32ec21e566318d35cc351d89)).
Closing issue.
