### ISSUE TITLE
Showing wrong status

### ISSUE THREAD

**Issue by Decimate1405** [nicehash/NiceHashMiner-Archived#431]
please fix this problem as soon as possible
![nm](https://cloud.githubusercontent.com/assets/24218060/20936666/83d81186-bbf4-11e6-96cf-df99466ec3df.PNG)

**Comment by S74nk0** [comment]
Your GPU (looks like a mobile/laptop GPU) is not working correctly with this miner. Disable **CryptoNight** for this GPU. [ccminer-cryptonight](https://github.com/nicehash/ccminer-cryptonight) does not work correctly with all GPUs and we are planing to remove it all-together.
Closing issue...
