### ISSUE TITLE
GPU slows down.

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#432]
Since 1.7.3.9 one of my graphics cards slows down from 1500mhz to 405mhz after running for a few minutes. The second card slows down too but they do it at different times. The card that slows down tends to be random. P0 state is active on both of the 980TI's. It requires a restart of the computer to get them both working again. Running the most current driver 21.21.13.7619. It is in performance power mode and all power saving features have been disabled. Any ideas what could be causing it.

**Comment by S74nk0** [comment]
@xadonxander The miner software didn't change except for updated **eqm** miner.  Are you experiencing this when mining Equihash?

**Comment by xadonxander** [comment]
I guess it could have been within the last 3 versions. They came out within a few days and I may not have noticed. Yes, equihash

**Comment by xadonxander** [comment]
My second graphics card is reverting to p2 when eth miner restarts or the algo changes.


==============NVSMI LOG==============

Timestamp                           : Thu Dec 08 12:28:37 2016
Driver Version                      : 376.19

Attached GPUs                       : 2
GPU 0000:01:00.0
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        Unknown                     : Not Active

GPU 0000:02:00.0
    Performance State               : P2
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        Unknown                     : Not Active

**Comment by snowcrawl** [comment]
Not sure if it has been brought up before, but Nicehash miner seems to be more optimized to work under Windows 10.   I just upgraded on one machine that had Windows 7 on it.    I am getting a 20 percent boost in performance from my RX 480 card on the claymore zcash miner.  Smoother, more effecient switching between algorithms.  Plus no freezing anymore, which I was occasionally getting with the claymore 3rd party software when running under Windows 7.

**Comment by xadonxander** [comment]
from what I see it's a problem with the p0 in settings. I turned it off and
have had no further issues.

**Comment by S74nk0** [comment]
@xadonxander I am not entirely sure but I think that the newer GPUs have overclocking disabled (the state doesn't persist it falls back to P2). I think this only happens with **Pascal** (I have seen this with **Pascal**) GPUs but it could happen with **Maxwell** (just guessing). So you have 2 GPUs both 980TI's?

**UPDATE:** this is only with newer CUDA-8 drivers I think.

**Comment by xadonxander** [comment]
I have 2, 980ti's. Since I disabled p0 everything is working fine.

**Comment by S74nk0** [comment]
I believe the overclocking issue is due to NVIDIA drivers. Also **eqm** sometimes might not work with overclocked GPUs if that was also the issue. 
Closing issue... 
Reopen if it is not resolved
