### ISSUE TITLE
New AMD Graphic's Driver - Issues - Help

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#433]
Unsure what to ask but don't seem to work with the latest's setup?

**Comment by S74nk0** [comment]
@tmslacker please be more specific.

**Comment by tmslacker** [comment]
I installed the new relive drivers and they are 2x the size of the driver pack.  I'm running 4x 480 and 2x per system.

**Comment by tmslacker** [comment]
Clean install of the drivers; fixed the issue!
