### ISSUE TITLE
nicehashminer v.1.7.3.9  want be start  

### ISSUE THREAD

**Issue by almoharebh** [nicehash/NiceHashMiner-Archived#435]
nicehashminer  v.1.7.3.9 want be start . 
he loop close every time I start miner . I don't know how to start

**Comment by S74nk0** [comment]
@almoharebh this is a **BUG in v.1.7.3.9** it should have prompt a notice that a benchmark is needed. You need to go to benchmarks and benchmark the devices (GPUs/CPUs) that you want to mine on, after that NHM will be able to mine

**Comment by S74nk0** [comment]
There is already a fix [commit](https://github.com/nicehash/NiceHashMiner/commit/7484aa818581c6e52d9bfec7f907437d0f885256), and it will be included in the next release.

**Comment by almoharebh** [comment]
i don't understand how add this file . i press benchmark i press start nothing do not start i cant press any thing can you learn me how to add

**Comment by almoharebh** [comment]
Yes ; it is work now . Thank You

**Comment by S74nk0** [comment]
[new version](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.3.10) is out and has this issue fixed.
Closing issue...
