### ISSUE TITLE
Attached Photoshot

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#436]
https://s28.postimg.org/630vw45rh/8e0e5f38_bef7_11e6_80b0_990070316388.jpg

Can anyone Help!...

**Comment by tmslacker** [comment]
Did you extract the folder from the zip file?

**Comment by ghost** [comment]
Didn't you look at the pic ?... it shows it in the main folder, unzipped.

**Comment by tmslacker** [comment]
Mine doesn't double folder it when I extract it.  Anti virus and malware can flag the program.  I was just trying to help.

**Comment by ghost** [comment]
Thanks, i am not sure what/why this happen on this computer because everything went fine on my other pc (desktop) have it running ok, i just unzipped it, clicked on application and it is fine. Come to this pc (laptop) and get this error...i am still working on it, try to get NiceHash.com support next.

https://s30.postimg.org/aon12zbu9/2016_12_11_at_05_23_55pm.jpg

**Comment by S74nk0** [comment]
This seems to be an issue related to Windows file read/write permissions and not NHM itself. Is that from a removable media storage like **USB**?

**Comment by Sweetasdad** [comment]
Hi, 
Thanks for the input, and i am now happy to say, (and with help from Windows Support) it is now producing the goods and i will be waiting with patience for Payday!... Thanks again.
![2016-12-13 at 07 06 39pm](https://cloud.githubusercontent.com/assets/17826004/21129769/ca620516-c168-11e6-87d2-5ee0bdab1bf0.jpg)

**Comment by ghost** [comment]
Hi, 
Thanks for the input, and i am now happy to say, (and with help from Windows Support) it is now producing the goods and i will be waiting with patience for Payday!... Cause of problem, Anti Virus/Malware software (@tmslacker) and Nvidia Card compatible. 
Thanks again. 
![2016-12-13 at 07 06 39pm](https://cloud.githubusercontent.com/assets/17826004/21129769/ca620516-c168-11e6-87d2-5ee0bdab1bf0.jpg)
