### ISSUE TITLE
Are payouts now only going to occur once a week?

### ISSUE THREAD

**Issue by snowcrawl** [nicehash/NiceHashMiner-Archived#437]
I am not sure if it just a temporary clitch, but on the Nicehash stats page for my Nicehash miner farm it is now displaying my next payout as occurring exactly one week from today.   I realize that there are occasionally glitches like this where it might say that a payout will be posponed, only for the payout to end up going through anyways.   I just wanted to know if there was some kind of change happening to the payout system.

**Comment by fefsf** [comment]
https://www.nicehash.com/index.jsp?p=news&id=122

**Comment by S74nk0** [comment]
Closing issue... not relevant to NiceHash Miner
