### ISSUE TITLE
Error Messages 

### ISSUE THREAD

**Issue by almoharebh** [nicehash/NiceHashMiner-Archived#438]
@S74nk0
i receive this error messages when i start mining  the application was unable to start correctly (0xc000007b).click ok to close the applecation

**Comment by S74nk0** [comment]
Where does this happen? Please give more info regarding this error.

**Comment by almoharebh** [comment]
when I start mining with nicehash

**Comment by S74nk0** [comment]
The new version is out with many BUG fixes. Please try that and report if it fixes your issue. Also in the future please provide logs and detailed information (What GPUs/CPUs are you using, how much RAM does the system have, GPU RAM), motherboard, Operating System version and architecture...
All future issues without detailed information will be closed.

**Comment by Edubrakata** [comment]
Mine is having the same problem I have tried downloading everything necessary help please
