### ISSUE TITLE
Nicehash  and cpu usage amd radeon

### ISSUE THREAD

**Issue by palmiris** [nicehash/NiceHashMiner-Archived#44]
I am running nicehashminer with amd radeon card 7750 HD. I am getting very good performance with blake256r8vnl. Nicehash is using sgminer.exe which is utilizing 50% of the processor power.

I have run the benchmarks as recommended.

Why am I seeing high cpu usage?? OpenCL GPU should not consume any cpu load. I have not selected CPU usage with AMD openCL mining. Is sgminer.exe a virus causing high cpu usage??? I don't want to use any CPU power since it destroys the purpose of efficiency and minimal power usage.

Also when doing the performance tests the last one runs for ever and I don't get a hash score (ethereum). I have to end task.

Please can anyone suggest a correction? Thanks

**Comment by kenshirothefist** [comment]
Blake256 implementation in Windows is unfortunately very CPU intensive. We can't do anything about this, it's the way the algorithm was built.

**Comment by theLosers106** [comment]
@palmiris about your ethereum problem.. could you try running it manually? what CPU do you have? sometimes slower CPU takes longer to benchmark

**Comment by palmiris** [comment]
Hello,
I am not testing a cpu. I am testing AMD Radeon 77XX Graphics Card. 
1. Why do I get 50% CPU usage with blake?? just using AMD_OpenCL with cpu0 disabled.
2. Why does ethereum benchmark test never ends???? (not cpu0 but AMD_OpenCL test) It runs when manually selected but too slow. Still CPU usage 50%
3. I will try to use Keccak to see if the cpu usage stops. Checked and crushed my drivers. Not stable.
4. PC is mini-itx with P9600 mobile intel core 2 duo 2666MHz, operating system win 10 x64, Memory 2x4GB.

Guys openCL means that only GPU should work thus CPU usage should be near zero similar to guiminer openCL where I get 130MH/s without problems on Amd radeon 7750 using the AMD overdrive settings.

**Comment by theLosers106** [comment]
1. Yes.. I know it is not mining on the CPU.. but the CPU is used to precalculate some of the hash and that is what's causing the high CPU usage..
2. How long does never end is? Slower CPU such as yours might take longer to benchmark as ethminer needs to prepare and warm up the GPU before finally getting the speed.. that's just how the ethminer is.. ethminer does use some CPU during mining and the reason I "THINK" is because it is precomputing the next dag file..

and yes again.. OpenCL should use the GPU instead of the CPU but then again if the miner software wants to precaculate stuff on the CPU then it will be using the CPU..

**Comment by palmiris** [comment]
that is why it is acting like a Trojan.

**Comment by kenshirothefist** [comment]
@palmiris NiceHash Miner is using mining software (cgminer/sgminer, ccminer, cpu_miner) which are based on community driven development. Blake256vnl algorithm implementation in sgminer is probably not optimized enough for OpenCL and is thus also using CPU. I suggest you ask Blake256vnl implementation authors about this issue: https://v.cash/forum/forums/tools-tutorials-projects.12/

**Comment by palmiris** [comment]
If you are interested in improving the nicehashminer app, then the way forward is to implement OpenCL support fully. I have the same problem with Keccak so it is not just black256vnl. Probably it is an sgminer/nicehashminer app bug. 
I have tested just now the bfgminer you are referring with my GPU card, and I have no problems what so ever with the CPU usage. How do you justify this??? 
I used auto setting. Intensity 14 and I get 112 MH/S ( kernel phatk). It is using again OCL, though gpu temperature a bit higher than guiminer.
1. CGMiner, the version I am using does not support the GPUs. Only my U2 usb antminer.
2. BFGMiner supports both usb antminer U2 and GPU openCL. CPU usage 2-6%. GPU Temperature 50
3. Guiminer supports only my GPU using openCL. CPU usage 2-4% GPU Temperature 44.  130MH/S
4. SGminer app cpu usage 50% through the nicehashminer app. Does not support usb antminer 

So to cut the long story short, 
a. I am using the same worker name, cgminer app with U2 antminer, and guiminer app with AMD Radeon graphics card and I get the best result with low CPU usage.

b) or as an alternative I can use the bfgminer app for both GPU and U2 antminer with similar results.

How does nicehashminer app combine the use of both gpu and antminer U2 U3 etc????? If it was made as an alternative to the guiminer, then it failsssssssssssssss since 50% cpu usage is not allowed. The purpose of GPU openCL is to use OpenCL of GPU and not CPU.

**Comment by UnclWish** [comment]
I found a new issue with ethereum miner. When run the benchmark, it don't use extralaunch parameters or parameters by nicehashminer for mining etherium. When you mine ethereum it creates dag files in subfolder data in NHM folder, when you run benchmark - ethminer creates dag files in AppData folder.
1st benchmark run ethminer creates dag files in my ssd about 5 minutes size 3Gb. I think because my videocard has 4Gb RAM. On hdd it can take some more time up to 10-15 min. Dag files created in user's Appdata folder,
After benchmark when run ethereum mining ethminer creates dag files again, becuase NHM runs it for mining with parameter --dag-dir data\AMD_OpenCL.

Creating dag files process uses much CPU time. During mining CPU usage is low. But many RAM needed for minng - i think size of dag files is amount of RAM needed for miner.

sgminer 5.3.0 use about 25% of my 8 cores AMD CPU during ANY mining algorythm.
NHM runs sgminer 5.3.0 for my Radeon R9 270X in any algorythm besides X11 - it runs on sgminer 5.1.1.
sgminer 5.2.1 and 5.1.1 use 1-3% od CPU.

**Comment by palmiris** [comment]
When the problems are fixed please let me know. I am not using it until then. Let me scan your pc, create 3gb or more data and then upload that to the internet??? Far fetched but suspicious to me. Or is it downloading malicious programs???? The thought scares me.
Regards

**Comment by UnclWish** [comment]
Ethminer is not upload data to internet. Dag files creates by ether-proxy.exe and makes us possible to mine ethereum into btc directly. We are recieve btc for this work. And if you affraid something don't use it - it's your business.

**Comment by palmiris** [comment]
ok thanks for pointing that out that it is safe. I wish the cpu usage can be fixed. and crushes with the drivers/instability. Regards and good luck.

**Comment by UnclWish** [comment]
In mining ethereum once creating dag files miner not uses CPU (very low CPU usage).
I repeat high CPU usage is only during creating DAG files (1st launch) and during working sgminer 5.3.0.

**Comment by palmiris** [comment]
I do have high cpu usage in general using you app. Ethereum gives me very low score anyhow, I don't remember what was the cpu usage when using ethereum logarithm, and I don't want to check again.

**Comment by UnclWish** [comment]
I was wrong - ethereum miner so as sgminer 5.3.0 uses about 20-25% of CPU power during mining process. It's sad (((. Can anyone else confirm this?

EDIT: No. it was temporary - i deleted dag files, ethminer creates new dag files about 5 min, during this CPU usage was high - about 50-75%. After finishing creating dag files ethminer starts to mine - GPU usage became 100%, but for some time (about 5-10 min) CPU usage was 25% and disk I/O about 1,5Mb/s. I think ethminer can start to mine when it's possible, and continues to finishing creating dag files.
Now ethminer uses 100% GPU and about 1-2% CPU.

**Comment by theLosers106** [comment]
Yes.. it will use a substantial amount of CPU during mining so it can precompute the next DAG file.. it should be every now and then only..

**Comment by palmiris** [comment]
and where does it not use high CPU usage any logarithm you propose?????

**Comment by theLosers106** [comment]
I'm not sure which miner you are talking about.. I was referring to ethminer..

**Comment by palmiris** [comment]
ok I never used it so my mistake. Probably gpu mining through scrypt is memory cpu intensive. Is ethminer using scrypt like lightcoins????

**Comment by theLosers106** [comment]
That I have no clue.. what I know is that it uses the CPU only when it needs to create the DAG file.. so sometimes it happens during the start of the miner and sometimes during mining if the option (--no-precompute) is not used..

**Comment by palmiris** [comment]
:) thanks for the pointer. If I use ethminer, maybe it is worth it with my low hash rate, then I will use this command option. Are you mining with AMD GPU? Can I use ethminer with antminer usb hardware too?

**Comment by theLosers106** [comment]
It is actually not recommended to not use that command option.. I am not sure to what will happen.. maybe you could ask it here for further info (https://forum.ethereum.org/discussion/2227/cuda-miner/p1).. Ethminer is AFAIK can only mine using GPUs and not ASICs.. (:

**Comment by palmiris** [comment]
A lot of info:) When I have time, I am trying to finish a webpage following an online course, I will look into that. Thanks

**Comment by theLosers106** [comment]
Reduced CPU usage of sgminer for blake algos by about 43%.. will be closing this for now..

**Comment by UnclWish** [comment]
sgminer updates exe? Were it can be downloaded?
