### ISSUE TITLE
NiceHashMiner v1.7.3.10 problem with Intel Pentium CPU G4400 3.30 mining cryptonight algo

### ISSUE THREAD

**Issue by anonymous890890543** [nicehash/NiceHashMiner-Archived#442]
win 8.1 64bit  full updated

Start mining but, it is mining with only cpu0.
Working ok on v1.7.3.9 

It is working ok on intel core duo E8400 3.00 in both v1.7.3.9 and v1.7.3.10

**Comment by Alchemist80** [comment]
The new version nicehash v1.7.3.10 is HS on all CPU's
2CPU.I7 4790K ?

**Comment by mmliar** [comment]
Please check if you have `less thread` set to 1 in "Settings" --> Devices/Algos". If so, set it to 0 and you should see both cores are running.

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
