### ISSUE TITLE
RX480 Zcash Miner loses connection to server then crashes windows ( V1.7.3.10 update )

### ISSUE THREAD

**Issue by Gamingpro2006** [nicehash/NiceHashMiner-Archived#443]
windows 10 reports hardware has been blocked from being accessed by zecminer64 exe. as it crashes.
adding to exceptions yielded the same result.

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
