### ISSUE TITLE
Payout Day

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#444]
So today is pay out day for me. The 12th. Now, I just went ahead to Coinbase to check my wallet, but it's still empty. I've already made sure the wallet address is the same on in the Nicehash miner to go into it. My friend told me that if is it the unpaid balance (it is) it will take a while. 

But I'm not sure according to those stats online. My estimated payout day balance is different from my unpaid balance and I'm not sure which one am I getting.

**Comment by fefsf** [comment]
This has nothing to do with the Nicehash Miner.  

The payout dates have been changed. Click the link below

https://www.nicehash.com/index.jsp?p=news&id=122

**Comment by keztheminer** [comment]
yeah pretty shitty they done it the day b4 normal payout with no notice

**Comment by 192uijo** [comment]
Oh... well, that's unfortunate...
