### ISSUE TITLE
Extra Launch Param doesn't work for NVIDIA ccminer CryptoNight

### ISSUE THREAD

**Issue by mmliar** [nicehash/NiceHashMiner-Archived#446]
When putting param in the "Extra Launch Parameters" for cryptonight for NVIDIA GPU, it won't be applied when actually running the miner. 
In my case, I put "--launch=15x45" in it and the nicehash miner will just run the ccminer without adding this param. Nothing related (extra param info / ignored notice) showed up in the log file and debug console. 
Tried running ccminer using "ccminer_cryptonight.exe  --url=stratum+tcp://cryptonight.usa.nicehash.com:3355 --userpass=*.*:x  --devices  0  --launch=15x45" directly and it works well.

**Comment by mmliar** [comment]
Here is the log. 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/650137/log.txt)

And here is the set up of my extra param.
![image](https://cloud.githubusercontent.com/assets/15837487/21159336/afbb72ac-c135-11e6-8862-fc8a55af6b22.png)

**Comment by S74nk0** [comment]
NVIDIA ccminer CryptoNight is very faulty miner. All GPUs that are lower than Maxwell (lower than SM50), have these settings disabled (only for **ccminer CryptoNight**)

**Comment by S74nk0** [comment]
@mmliar  this has been fixed ([read](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#how-to-add-missing-miner-flag)). [Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.4)
