### ISSUE TITLE
miners at idle 1.7.3.10

### ISSUE THREAD

**Issue by hazer1** [nicehash/NiceHashMiner-Archived#447]
Hello
I have to start 1.7.3.10 is not working miners at idle. Instead, always works when you click Start. I tried to turn off the option to save the settings, ran, tried to include the option retained, ran. The result is included immediately after pressing start and shut down automatically during operation. In previous releases, it worked.

**Comment by mmliar** [comment]
Are you talking about the "Start mining when idle" option? If so, you don't need to click on the "start" button at all. 
As long as you keep the NiceHash Miner opened and do not use your computer (no interact through any input) for the minimum idle time, the miners will start automatically. The miners will always start immediately when you explicitly click on "Start".

**Comment by hazer1** [comment]
Hello.Yes, I'm talking about this setting.Earlier, I pressed start, the miner is started and immediately closed. And after the time specified in the settings, it start and run if the computer is idle.This version starts immediately after pressing the start button and stops at my actions.I checked your advice. Indeed, if you do not press the start button, it runs through the allotted time and off with my actions.Thank you. The question can be closed. Alexandermob.: +7 (903) 641-77-63   13.12.2016, 08:11, "mmliar" <notifications@github.com>:Are you talking about the "Start mining when idle" option? If so, you don't need to click on the "start" button at all.As long As you keep the NiceHash Miner opened and do not use your computer (no interact through any input) for the minimum idle time, the miners will start automatically. The miners will always start immediately when you explicitly click on "Start".—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by p1r473** [comment]
For me, I set idle to 5 seconds, I sit back and watch, and it won't idle. I am not doing anything! Not moving mouse or typing on keyboard.
idle detection hasn't worked in the last 2 versions for me. I have the option checked to mine when idle, but it won't start!

**Comment by S74nk0** [comment]
@p1r473 what are your settings? I was unable to reproduce the error, so maybe some combination doesn't work correctly.

**Comment by S74nk0** [comment]
@hazer1 if you start it manually it ignores idle settings.

**Comment by p1r473** [comment]
![image](https://cloud.githubusercontent.com/assets/9235633/21134973/0cf4f3f0-c0ee-11e6-8c63-a3dedb39f500.png)

**Comment by S74nk0** [comment]
@p1r473 I have tested with the settings you have provided with idle timeout 5 seconds. But still the Idle setting is working. I cannot reproduce the issue. The log file will show what is going on here. The only notable change with Idle mining is that when starting **manually** or when auto-starting the Idle setting is then ignored (also when manually stopping then Idle setting still works as expected).

**Comment by p1r473** [comment]
here is the log
https://www.sendspace.com/file/mttupk

I have it set for 60, I left to run some chores, come back, nothing!

**Comment by mmliar** [comment]
@p1r473 Line 849 indicates that your miner was running. The reason why you think it is not working might be that you enabled "Minimize To Tray" and you cannot see the running miners. Also, for the "Start Mining When Idle" option, if you have any keyboard or mouse input after the miners start running, the software will not consider you computer is idle anymore therefore closes all your miners.

**Comment by p1r473** [comment]
I have been monitoring GPU usage using an LCD screen. When it is supposed to be running, my usage is at 0%. As well, I have had it open for days, and I haven't earned a single cent

Also usually I can tell its running because the main NiceHash UI screen shows how much I am earning per day at the bottom, but it is just showing 0

Here is a screenshot I took after 60 seconds. I can tell based on the USD/Day that it isn't doing anything, and also group/device rates usually has text in it when the miner is running.

![image](https://cloud.githubusercontent.com/assets/9235633/21161965/041f4972-c159-11e6-92a6-8399f02dc8cc.png)

**Comment by p1r473** [comment]
Here is a fresh/clean log after I have deleted the old log, opened the app, and stepped away for 5 minutes:
https://www.sendspace.com/file/slagqf

**Comment by p1r473** [comment]
@S74nk0 Can you please take a look?
Thanks!

**Comment by p1r473** [comment]
Seems to be working now... Will update if it breaks again

**Comment by p1r473** [comment]
@nicehashdev Still not running for me when idle

**Comment by p1r473** [comment]
OK I am going to open my own issue instead of piggybacking on this closed one
