### ISSUE TITLE
1.7.3.10 reset CPU Less Threads after the benchmark

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/NiceHashMiner-Archived#448]
1.7.3.10 reset to 0 CPU Less Threads after the benchmark

**Comment by billmcilhargey** [comment]
On this note: 1.7.3.11
I noticed after benchmark my CPU threads went from 4 to 3.  Any reason it would run one CPU thread less than what's installed?

**Comment by S74nk0** [comment]
When setting number of threads through parameter **-t 4** LessThreads will not change. The changing is due multiple benchmark tests when benchmarking CryptoNight to find the best setting.

Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).
Closing issue as it is related to an older version of NiceHash Miner.
