### ISSUE TITLE
1.7.3.10 - R9 380 and daggerhashimoto algo ?

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#449]
in version 1.7.3.10 on R9 380 missing daggerhashimoto algorithm. it was beneficial for me this gpu. It is possible to return? Or it does not make sense?

**Comment by S74nk0** [comment]
This is probably a 2GB RAM GPU right? If so then this is the reason. The DAG is over 2GB and that is the reason it is not listed anymore. 
Reopen if the GPU is over 2GB RAM

**Comment by foxwarernd** [comment]
manual start and goes running

**Comment by S74nk0** [comment]
You can use the previous version until the DAG will over cap the GPUs RAM. It will work for a short while. But keep an eye on those rigs as they will not be capable of holding the DAG file in the near future.

**Comment by S74nk0** [comment]
Also the if you are using the new claymore zcash miner you can copy the newest version over and older NHM will work. So there aren't any performance fallbacks

**Comment by foxwarernd** [comment]
thanks
