### ISSUE TITLE
etherrium for 3.x 

### ISSUE THREAD

**Issue by crysishc4l** [nicehash/NiceHashMiner-Archived#45]
Heey,

i have been switching from eth miner to nicehash miner since it didn't have eth, now it does but you guys dont support the 3.x cuda miner and i still cant mine eth with nicehash are you going to add this as well?

with regards
crysishc4l

**Comment by theLosers106** [comment]
Hopefully Genoil can get Compute 3.0 Cards to work using CUDA. https://forum.ethereum.org/discussion/comment/21836/#Comment_21836

Anyways, testing ethming using OpenCL on a GTX 650Ti, it is hashing really really slow (4-6MH/s). I wonder how much other more powerful Compute 3.0 cards running using OpenCL are doing..

**Comment by Kekkonshiki** [comment]
manual update ethminer from [Genoil](https://github.com/Genoil/cpp-ethereum/tree/master/releases)

**Comment by theLosers106** [comment]
Will be closing this issue as it has been resolved in NiceHashMiner v1.4.0.0 release..
