### ISSUE TITLE
16.12.1

### ISSUE THREAD

**Issue by keztheminer** [nicehash/NiceHashMiner-Archived#450]
its mining but not submitting no shares for daggerhasimoto, i've run it for 3 days with no earnings using r9 390

**Comment by S74nk0** [comment]
@kezdarkriser what is the GPU RAM size?

**Comment by CAVACO-PT** [comment]
Same here , i had to put old drivers to get it back to work , 16.12.1 doesnt submit shares with daggerhasimoto , only when we put driver 16.11.1 back , diferent cards used , 290x,   480 ,  same result

**Comment by keztheminer** [comment]
8gb  ram
xfx r9 390 8gb

**Comment by S74nk0** [comment]
@kezdarkriser this seems to be related to new drivers. Fallback on previous working driver until these issues with newer drivers aren't resolved.

**Comment by kezdarkriser** [comment]
been 2 weeks and no earnings and i will not ever revert to old drivers as system is used for gaming 50% of the time ,plus with the payments changing it's not worth me using no more not been paid now for like forever . the miner wont even tick over to a new algo

**Comment by kezdarkriser** [comment]
running 17.1.1 now , been nearly 2 months and only earnt 500k satoshi instead of 1 mill plus weekly,i'm done now was a nice ride while it lasted/worked

**Comment by S74nk0** [comment]
**AMD ethminer is discontinued** 

Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
