### ISSUE TITLE
10-15% rejected

### ISSUE THREAD

**Issue by semisane** [nicehash/NiceHashMiner-Archived#455]
Running 4 x AMD 480 8GB cards. Constantly see rejection rates around 14%.

Have seen this issue on all versions of NHM. Using latest & Claymore.

I get zero rejections using 4 x 980/970/1080/980Ti

Any hints?

**Comment by semisane** [comment]
I'm also constantly mining at 780-800 sol/s according to NHM but the web interface never peaks over 650 sol/s
![image](https://cloud.githubusercontent.com/assets/18557237/21204525/c34cc712-c20c-11e6-88df-5bfd711f50e4.png)

**Comment by Johann1982** [comment]
I also get a lot of stale/rejected hashes. 2x RX480 and 2x RX470

**Comment by S74nk0** [comment]
There were issues with our provider [check here](https://twitter.com/NiceHashMining). Things should be now running as expected.

**Comment by S74nk0** [comment]
If you are getting rejects with claymore's miner it might be producing stale results.
Try lowering the intensity value for your GPUs. Here is a the [wiki](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#amd-claymorezcash-equihash).
Please report back if this fixes the issue

**Comment by semisane** [comment]
With the dramatic drop in equihash value & re-benchmarking my cards daggerhash is more profitable.

This can be closed for now. I'm sure a new claymore miner & NHM will be released shortly anyway.

Thanks!

**Comment by S74nk0** [comment]
@semisane all right. Please reopen this issue if it persist in future releases.
Closing issue...
