### ISSUE TITLE
Profitability down

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#456]
Is is just me or is the profitability down quite a bit the last week or so? It seems to be dropping everyday. Using NHM mining Equihash.

**Comment by tmslacker** [comment]
I'm running: 1080 GTX, 980 Ti and 5x 480's.  It's been kinda painful as of late.

**Comment by S74nk0** [comment]
There were issues with our provider [check here](https://twitter.com/NiceHashMining). Things should be now running as expected.

**Comment by tmslacker** [comment]
We are not talking about the site issue.  With 5x - 10x increase in hashing power!  We are making less each day or close to it.
