### ISSUE TITLE
10% - 15% rejects

### ISSUE THREAD

**Issue by semisane** [nicehash/NiceHashMiner-Archived#458]
*EDIT* This has been happening for at least a month!
Notice that I have zero rejections on nVidia cards...
This is only happening on AMD cards

Please help!

Running 4 x AMD 480 8GB cards. Constantly see rejection rates around 14%.

Have seen this issue on all versions of NHM. Using latest & Claymore.

I get zero rejections using 4 x 980/970/1080/980Ti

Any hints?

**Comment by S74nk0** [comment]
Related [issue](https://github.com/nicehash/NiceHashMiner/issues/455).
