### ISSUE TITLE
[Feature request] Automatic benchmark updates while mining.

### ISSUE THREAD

**Issue by lightning200mph** [nicehash/NiceHashMiner-Archived#46]
Automatic benchmark update on last "x" time interval.
I have noticed that the precise benchmark is normally off a little from what it is actually mining at, would be nice to have it update while running for accurate most profitable switching.

**Comment by kenshirothefist** [comment]
Any kind of automation can only be done up to a particular level. We've spent significant effort to make benchmarking as good as possible, but it can't be made ideal. First of all, make sure to run Precise benchmark if Standard benchmark is not giving you satisfactory results. If you still see a deviation of actual mining speed from the one, calculated from benchmark, then you should manually enter these observed speed numbers from actual mining into config.json file or set them via the "Settings" button.

**Comment by kenshirothefist** [comment]
I'll be closing this issue, see my previous reply for workarounds, but we'll take the proposal into account for the future releases. Thanks for the feedback!
