### ISSUE TITLE
Can't mine/benchmark Lyra2rev2

### ISSUE THREAD

**Issue by djbert-01** [nicehash/NiceHashMiner-Archived#461]
Hello,

I can't mine/benchmark lyra2Rev2 at all. When I benchmark it on my AMD GPUs, it just stalls and displays dots in the speed column for hours. I have attached the my log to this request. Almost all other crypto coin mining works with my NiceHashMiner. I am using version 1.7.3.10, but I have had this issue with all versions I have used in the past. Thank you. 

[log.txt](https://github.com/nicehash/NiceHashMiner/files/658765/log.txt)

**Comment by BARUCHER777** [comment]
/// .... There is the same problem on graphics cards Fury and Radeon R 390....
P.S    Been used: --- NiceHash Miner v1.7.3.12 and Crimson ReLive Edition 16.12.2

**Comment by djbert-01** [comment]
Thank you for the info. I gave up on it for now.

Sent from my iPhone

On Jan 8, 2017, at 6:22 PM, BARUCHER777 <notifications@github.com<mailto:notifications@github.com>> wrote:


/// .... There is the same problem on graphics cards Fury and Radeon R 390

-

**Comment by S74nk0** [comment]
@djbert-01 @BARUCHER777 this is driver related. On 16.11.4 **NeoScrypt** and **Lyra2REv2** will not work. Older drivers will work with these algorithms.
