### ISSUE TITLE
about daggerhashimoto

### ISSUE THREAD

**Issue by huidoo** [nicehash/NiceHashMiner-Archived#463]
AMD rx 470 daggerhashimoto 
the nicehashminer soft show is worked but my online stats is 0 or none

**Comment by kezdarkriser** [comment]
my guess would be that your using the new driver 16.12.1, it shows as mining but if u watch doesn't actually submit any shares

**Comment by huidoo** [comment]
I can see the online state instead of using EthDcrMiner64.exe alone.

**Comment by S74nk0** [comment]
@huidoo are you running Windows 10? How many GPUs do you have?

**Comment by huidoo** [comment]
@S74nk0 2008system 1GPu

**Comment by wtc2** [comment]
I am having the same issue.  Win 10 2-rx470 and 1-gtx970.

**Comment by wtc2** [comment]
Most recent 12/23 AMD drivers fail. rolled back and all is well again.

**Comment by N8Thrasher** [comment]
same problem with my RX480, GTX 780 showing on Nicehash but RX480 is 0.00h/s
![nicehasj](https://cloud.githubusercontent.com/assets/24593637/21544887/0960bbfe-cde4-11e6-857f-34ae5f2daaab.JPG)

**Comment by cryptoanarchism** [comment]
I'm having the same issue. Until someone figures out the problem I am just going to use equihash for now

**Comment by PauloOF** [comment]
Same problem on Windows 10, AMD 390X rigs and several others (290X, 390). Will stop Nicehash miner until bug is solved.

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/503).
Closing issue...
