### ISSUE TITLE
Poor Cryptonight Performance i7-6700k - v1.7.3.10

### ISSUE THREAD

**Issue by Eyedol-X** [nicehash/NiceHashMiner-Archived#464]
With my i7-6700K CPU's I get around 108-115 h/s with the cryptonight miner.

This is around half the performance of Claymore's CPU Miner 3.5

Please update the cryptonight miners for both CPU and GPU.

**Comment by xadonxander** [comment]
I get 130h/s with mine

**Comment by S74nk0** [comment]
@Eyedol-X this will be considered.

**Comment by bpvarsity** [comment]
This would be nice. I only get 120 h/s with nicehash miner and i get 220 h/s with claymore.

**Comment by mmliar** [comment]
Set `less thread` to 1 will potentially enhance the performance. 

For example, I'm using i5-4460, 4 cores @3.20GHz. If I set `less thread` to 0, even though all four cores are mining, the speed will be like 100 H/s; however, with `less thread` set to 1 and my speed will be stabled at 115 H/s.

**Comment by coladudetje** [comment]
i6@3.2GHz 101 H/s

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
