### ISSUE TITLE
R7 370 missing dagger in version 1.7.3.10

### ISSUE THREAD

**Issue by Treebeardz** [nicehash/NiceHashMiner-Archived#465]
I am missing dagger in my list of possible algorithms. If I download version 1.7.3.9 it seems to work just fine any reason for this?

**Comment by I-play-farruca** [comment]
I am also missing dagger in my list of possible algorithms in 1.7.3.10. If I too download version 1.7.3.9 it seems to work just fine. All other algos are good inc, 3rd pty Zec.  Windows 7 / AMD HD7870 (latest drivers)

**Comment by S74nk0** [comment]
This issue is [related](https://github.com/nicehash/NiceHashMiner/issues/449). If your GPU is 2GB RAM or less dagger is disabled in **v1.7.3.10**
