### ISSUE TITLE
Amd miner crash

### ISSUE THREAD

**Issue by unf0rg0tt3n** [nicehash/NiceHashMiner-Archived#467]
Hi, whenever I want to use my 2 amd gpu's I get BSOD's everytime again. I can't skip the benchmark but whenever I want to benchmark I get a BSOD. Please help!

**Comment by S74nk0** [comment]
What GPUs do you have? What NHM version are you running? Also please check this [issue](https://github.com/nicehash/NiceHashMiner/issues/389) and try one of the following, it seems to me that your issue is related.

**Comment by unf0rg0tt3n** [comment]
Hi I got a amd r7 370 and a amd rx470. I tried to follow the attached guide from the wiki; but I can't find where the settings are. Disable default optimization for example, where to find that? Is that a windows setting or inside AMD? And the fan controller from AMD, there are several of those but none apply to the ones described.

**Comment by S74nk0** [comment]
Here are pictures:
![amd_1](https://cloud.githubusercontent.com/assets/1517233/21370516/51f75780-c70c-11e6-9a71-364043bc52fc.PNG)
![amd_2](https://cloud.githubusercontent.com/assets/1517233/21370519/54ffe848-c70c-11e6-8565-c90a799c7e9a.PNG)
