### ISSUE TITLE
Cannot set extra launch parameters for CryptoNight on NVIDIA

### ISSUE THREAD

**Issue by KexyBiscuit** [nicehash/NiceHashMiner-Archived#469]
Though I set it in settings, the miner just doesn't obey it. Debug window shows NHM doesn't pass it at all.

My parameters: `-l 32x14`

**Comment by mmliar** [comment]
I have submit the same issue 12 days ago ( #446 ) and got no answer back yet. You can always override this manually by using CMD / shell. Just replace the settings accordingly.
`[(Nicehash miner folder)]\bin\ccminer_cryptonight.exe --launch=[15]x[45] --url=stratum+tcp://cryptonight.usa.nicehash.com:3355 --userpass=[(bitcoin address)].[(worker)]:x --timeout=30`

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/469)
Closing issue...
