### ISSUE TITLE
1.3.0.0 showing $5 a day mining Etherum but no increase on bitcoin balance or USD balance.

### ISSUE THREAD

**Issue by ElectricInferno** [nicehash/NiceHashMiner-Archived#47]
Is this a bug? NiceHashMiner says my GPU will earn me $5-6 a day, but nothing is being added .Is this a separate payment? If so, will this go in my Coinbase account, or will I have to make an Etherum wallet?

**Comment by Kekkonshiki** [comment]
see #40 & #41

**Comment by ElectricInferno** [comment]
Sorry, I may be a bit thick, but what do those issues have to do with my issue? 41 says that the URL needs to be &a=999, but that doesn't change anything (my balance is still the same) and 40 I don't really understand except for the fact that it counts them separately. Is there another place I find them? I noticed that there are a lot of unexchanged and immature on my graph for etherum, could that be the problem?

**Comment by Kekkonshiki** [comment]
40 - explains the reason why the program doesn't show the current balance
41 - link for check balance
after the exchange (occurs automatically upon reaching a certain balance) will change indicator "Unpaid balance".

**Comment by theLosers106** [comment]
This issue has been addressed in the latest Release 1.3.0.1
https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.1
