### ISSUE TITLE
Why I am gitting small profit on NiceHashMiner_v1.7.3.10 

### ISSUE THREAD

**Issue by almoharebh** [nicehash/NiceHashMiner-Archived#471]
cryptonight stop mining lyra2re small amount off profit .
and when the profit send to my bitcoin wallet 
and nicehashminer not detect my NVidia graphics card  . and not mining with graphics cards mining with CPU only .

**Comment by S74nk0** [comment]
@almoharebh please be specific what NVIDIA GPU model is on your machine. The profit is changing with market [prices](https://www.nicehash.com/).

**Comment by S74nk0** [comment]
If your NVIDIA GPU is not Fermi SM 2.1 and above keep this issue closed as those GPUs aren't supported. Here are [unsupported](https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Devices/CUDA_Unsupported.cs) devices.
