### ISSUE TITLE
clReleaseDevice could not be located in dynamic link library 

### ISSUE THREAD

**Issue by almoharebh** [nicehash/NiceHashMiner-Archived#472]
clReleaseDevice could not be located in dynamic link library

**Comment by S74nk0** [comment]
@almoharebh post more information about your setup. What CPU/GPU motherboard vendors/models, amount of RAM do you have... 
vague descriptions will be closed immediately. Reopen this issue and be as specific about the hardware, driver versions, what algorithms are causing problems... 
Closing issue as description is vague...

**Comment by almoharebh** [comment]
CPU/GPU motherboard NVidia GeForce 210 RAM 4GB motherboard gigabyte CPU: Intel(R) Pentium(R) Dual  CPU  E2200  @ 2.20GHz dual core  that's accrued when I start mining nice hash

**Comment by S74nk0** [comment]
@almoharebh The GPU is too old. Also the CPU will not yield any significant profit as it is also an older CPU it cannot compete with today's CPUs and not to mention GPUs hash-rates. The hardware is too old. There is nothing we can do to make it work better on older hardware as that is impossible.
