### ISSUE TITLE
stratum+ssl

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner-Archived#473]
Hello , maybe im doing something wrong , can i get some help ,

This pool (stratum+ssl) does not support ZCash addresses as login (or requires worker name in "Login.Worker" format) and cannot be used for devfee mining, therefore it is not supported.
14:22:48:213	e80	However, you can mine on this pool if you specify "-allpools 1" option, default pools (different from this pool) will be used for devfee.
14:22:48:214	e80	Please read "Readme" file for details.
14:22:48:214	e80	This pool (stratum+ssl) does not support ZCash addresses as login (or requires worker name in "Login.Worker" format) and cannot be used for devfee mining, therefore it is not supported.
14:22:48:215	e80	However, you can mine on this pool if you specify "-allpools 1" option, default pools (different from this pool) will be used for devfee.
14:22:48:216	e80	Please read "Readme" file for details.
14:22:48:216	e80	Pool stratum+ssl removed from the list
14:22:48:217	e80	ZEC: 1 pool is specified

args: -logfile cl_log_noappend.txt -di 0 -mport -4000 -zpool stratum+ssl://equihash.eu.nicehash.com:33357 -zwal xxxxxxxxxxxxxxxxxxxxx.xxxxx 

What do i need to change ?

**Comment by CAVACO-PT** [comment]
if i dont specify a pool in epools.txt it doesnt mine equishash  keeps displaying that message

**Comment by UnclWish** [comment]
You must use btc-wallet adress in -zwal parametr.

**Comment by CAVACO-PT** [comment]
amd grafics cards , give that error , and even if i choose a pool in the epool.txt , are not submiting shares with equishash to the pool , the website doesnt apear the computers iv upgrades to new version of nice hash , something is not working for amd cards

**Comment by CAVACO-PT** [comment]
Downgraded to 1.7.3.10 , the error is gone , and the pcs are apearing in the web site as submiting shares

**Comment by CAVACO-PT** [comment]
had 1 computer that was connected fine , copied the folder to the others , and they now connect fine with ssl , and they apear in the pool as working , maybe the download of the miners when u open the new version didnt go well , dont know why

**Comment by S74nk0** [comment]
@MACE-Zer0  What service location are you using? Oh `ZCash addresses as login` you need a BTC addresses as login.
