### ISSUE TITLE
Only one server working at a time

### ISSUE THREAD

**Issue by steinhammer** [nicehash/NiceHashMiner-Archived#474]
Updated my five servers to version .11 and now only one server at a time show as "speed accepted" on stats page. 
The others show as "0". If I turn of the working server then another takes over and speed is accepted for that one. Now I run four servers with .10 version and one with .11 and now speed is showing on stats page again for all servers.
On the local nicehash miner all looks normal and basicly the same, some beter hashrate on .11 ofc.

**Comment by steinhammer** [comment]
Looks to be same problem as #475

**Comment by kenshirothefist** [comment]
Old issue, closing this now.
