### ISSUE TITLE
Stopped working in .11

### ISSUE THREAD

**Issue by Daltonganger** [nicehash/NiceHashMiner-Archived#475]
Dear Nicehash,

If you're mining on 2 computers with both .11 version. And 1 had Nvidia cards and the other one has AMD cards. The Nvidia (Not SSL) doesnt get counted to the account on NiceHash.

Do it's showing me a great score, with new EQM. But like to get the BTC for the mining!

Great thx

**Comment by Daltonganger** [comment]
See screen:

<img width="892" alt="schermafdruk 2016-12-25 17 01 07" src="https://cloud.githubusercontent.com/assets/17501732/21471922/cf62a8ea-cac3-11e6-80d3-142fbcb3731c.png">

**Comment by CAVACO-PT** [comment]
i had to downgrade to .10, because with amd cards , didnt even apear in the site

**Comment by tmslacker** [comment]
Same problem with my 1080 and 980 Ti

**Comment by tmslacker** [comment]
NVIDIA cards are not being counted for equihash.  SSL problem.

**Comment by NaitorStudios** [comment]
Unckeck "Hide mining windows", it's hiding EQM console window and it not suppose to, that's what cause the issue.

**Comment by S74nk0** [comment]
NVIDIA issue wasn't SSL related. [commit](https://github.com/nicehash/NiceHashMiner/commit/ecc1145362f52cc2a966628bd8d364041d15fd90) fixes NVIDIA issue.
