### ISSUE TITLE
[BUG] v1.7.3.11 - EQM 0.00 Sol/s

### ISSUE THREAD

**Issue by NaitorStudios** [nicehash/NiceHashMiner-Archived#476]
EQM mining on the software, showing Speed and USD/day normally, but on the NiceHash web page it show the miner as 0.00 Sol/s and make no money at all.
This is a really serious bug, must be fixed as soon as possible.

My GPU is a GTX 1080.

**Comment by fefsf** [comment]
Works fine on my 1080. Im sure youre going to have to post your log file for anyone to know whats going on with your setup

**Comment by NaitorStudios** [comment]
This seen to only happen when "hide mining windows" are checked, which also seen to hide EQM console window but I believe it not suppose to.

**Comment by S74nk0** [comment]
@FuurioBR this is indeed a BUG. This [commit](https://github.com/nicehash/NiceHashMiner/commit/ecc1145362f52cc2a966628bd8d364041d15fd90) fixes it. Keep issue opened until new release.
