### ISSUE TITLE
1.7.3.11 - AMD GPU not detected (RX480)

### ISSUE THREAD

**Issue by RazerMantis** [nicehash/NiceHashMiner-Archived#479]
Hi, got some little problem after update.
It just dont want to see the gpu. I have tried to reinstall drivers, latest or downgrade and as a result - nothing. 
So switched back to 1.7.3.10 and tooked the BIN folder from the 1.7.3.11

**Comment by RazerMantis** [comment]
Here is a log file and screenie.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/672951/log.txt)
![nicehash](https://cloud.githubusercontent.com/assets/24776171/21481858/78d64a9c-cb75-11e6-8315-466425c170b4.png)

**Comment by foxwarernd** [comment]
У Вас в логе пишет что обнаружил карту. Зайдите в настройки и проверьте что не стоит галочка на - "Откл. определение AMD".

![111](https://cloud.githubusercontent.com/assets/19841581/21483732/79fa378a-cb98-11e6-9b3b-aefc56a04966.jpg)

**Comment by RazerMantis** [comment]
@foxwarernd

Those setings doesnt change anything. Problem is not solved. 
It seems like it looses the card after launching AMDOpenCLDeviceDetection.exe or something like that.

Эти параметры ничего не меняют, что с галочкой , что без. Проблема осталась. 
Похоже что карта после обнаружения AMDOpenCLDeviceDetection.exe теряется или что то в этом роде.

**Comment by foxwarernd** [comment]
Попробуйте проверить карту какой нибудь нагрузкой, например furmark.
У меня есть подобные карты - проблем с обнаружением и с работой нет

**Comment by foxwarernd** [comment]
могу еще предложить скопировать файл opencl.dll к nicehash.exe

**Comment by RazerMantis** [comment]
@foxwarernd 

Карта то работает с версией 1.7.3.10 допустим тот же equihash и версии которые были до этого тоже работали , а вот самая последняя не видит.

![zcash](https://cloud.githubusercontent.com/assets/24776171/21484045/1182dc64-cb95-11e6-9daa-1d353c169041.png)


вот что показывает GPU-Z 
![stable](https://cloud.githubusercontent.com/assets/24776171/21484256/3c6bf836-cb98-11e6-9450-7745b018e1f6.png)

**Comment by S74nk0** [comment]
@RazerMantis did this issue happened after a driver update or just with NHM version update?

**Comment by RazerMantis** [comment]
@S74nk0  it happened only with new NHM, previous one works fine.

**Comment by RazerMantis** [comment]
@S74nk0 
log from 1.7.3.10
[log.txt](https://github.com/nicehash/NiceHashMiner/files/673247/log.txt)

log from 1.7.3.11
  [log.txt](https://github.com/nicehash/NiceHashMiner/files/673248/log.txt)

**Comment by RazerMantis** [comment]
I think i will try to reinstall OS.

**Comment by RazerMantis** [comment]
Strange, but after reinstall problem is gone. (Runing 1.7.3.11 , latest drivers "Crimson ReLive Edition 16.12.2 ", win 7 x64)
Thank you all for your replies.
Issue is closed =)
