### ISSUE TITLE
upgraded miner v1.7.3.11 (CPU Less threads)

### ISSUE THREAD

**Issue by realcotter** [nicehash/NiceHashMiner-Archived#480]
Hey great software, thank you...

when i upgraded to nicehashminer v1.7.3.11 the sofware only reported it using the 2 of the 4 cores on the cpu. When using v1.7.3.10 it was using all 4. the same problem happened on my test pc, when upgraded it only using 1 of the cores on cpu when previous version was using all 2. I downgraded back to 1.7.3.10 but problem persisted. I used a separate pc (3rd) and installed v1.7.3.11 with no problems using all available cores. 

is there a file i need to clear or use command line options?

**Comment by S74nk0** [comment]
@realcotter is this related to **CPU mining CryptoNight** or **CPU mining in general**?

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to older version.
