### ISSUE TITLE
NiceHash Miner 1.7.3.11 | 940M GPU | Cryptonight mining BUG

### ISSUE THREAD

**Issue by ShippyG** [nicehash/NiceHashMiner-Archived#481]
When i start mining it tells that my cryptonight mining speed is 34.454 MH/s :D

Screenshot: https://gyazo.com/c9d0f2a321f738c2c89c05d6bbce86fd

**Comment by fefsf** [comment]
Its not a bug, you're just becoming a millionaire :)

**Comment by S74nk0** [comment]
This is a known bug. Please follow [these](https://github.com/nicehash/NiceHashMiner/issues/500#issuecomment-271076255) instructions and report back on this [issue thread](https://github.com/nicehash/NiceHashMiner/issues/500). closing [duplicate](https://github.com/nicehash/NiceHashMiner/issues/500)
