### ISSUE TITLE
Duel Mining With Claymore

### ISSUE THREAD

**Issue by scrunchds** [nicehash/NiceHashMiner-Archived#482]
Please enable automatic duel mining option with 3rd party miner.

**Comment by tmslacker** [comment]
So many people using this app and not a single comment!  I think we need better communication!

**Comment by dogfried** [comment]
Is there an How to for doing this?

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre). Dual mining feature is not available ATM.
