### ISSUE TITLE
Why is information so out of date or hard to find!  I thought you wanted use to do well?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#484]
AMD & Nvidia.  2x companies and handful of cards and branches?  

Bragging $$$ aside?  Let's puts some real and solid information togeather!

$1ish a day for card 200ish $  is the system that fucked?  overhead and power?

We Can Do Better?  This kinda feels like trying to reading in the dark without a book sometimes!

**Comment by PhoenixAdageyudi** [comment]
Respectfully my good sir or madam but..
What the hell are you talking about
