### ISSUE TITLE
Anyone else having issues? 

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#487]
Dagger isn't being reported.  I can't download v.10.

**Comment by yetanotherjson** [comment]
Yes same here everytime I mine with daggerhashimoto the client reports that I am mining however when I check the site for reporting, it shows 0.0h/s for my miner.  Had the same issue since 1.7.3.10 and persists now in 1.7.3.11.

**Comment by yetanotherjson** [comment]
Also mining values seems to be reporting incorrectly for equihash also.  For example nicehash miner client reports 485sol/s however reporting usually reports roughly 200.  Didnt have this problem with 9, seems to persist with 10 and 11 only.

**Comment by slangza** [comment]
I have a similar issue.

Have 2 workers, only the one worker's hashrate is being recorded/displayed on the stats page. the other's hashrate stays on 0.00mh/s and is not being counted towards the Estimated incomes on the right side

**Comment by coladudetje** [comment]
Same problem no report of dagger i asked on facebook but i thought it was me provider but its since .10 
I using windows 10 with amd R9 390 card.

**Comment by semisane** [comment]
Has anyone found a solution yet?

**Comment by keztheminer** [comment]
solution is to find somewhere else to mine as nvidia nicehashminer works fine, but amd badhash miner  is screwed

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/496)
