### ISSUE TITLE
Not Recieving payments

### ISSUE THREAD

**Issue by protossdisaster** [nicehash/NiceHashMiner-Archived#489]
2nd payout I have not received from nicehash. My bitcoin wallet address matchs. Whats going on

**Comment by ShippyG** [comment]
How much is your unpaid balance?

**Comment by ShippyG** [comment]
This is what i found about nicehash payments.

3 (or 4) times a day if your balance is 4 million+ satoshis (0.04 BTC = 44.0 mBTC) in your balance
1 times a day (every fourth payment) if your balance is 400,000+ satoshis (0.004 BTC = 4.0 mBTC )
Every Sunday if you have 10,000+ satoshis (0.0001 BTC =0.1 mBTC)

**Comment by nicehashdev** [comment]
https://www.nicehash.com/?p=faq#faqs6
