### ISSUE TITLE
Request new option - Minimize Mining Windows

### ISSUE THREAD

**Issue by jsmcconn** [nicehash/NiceHashMiner-Archived#490]
As eqm doesn't work with hidden windows, it would be nice to have an option to minimize/not activate mining windows on start.

I find these settings to be best:

```
sflags = CREATE_NEW_CONSOLE;
sInfo.dwFlags = STARTF_USESHOWWINDOW;
sInfo.wShowWindow = SW_SHOWMINNOACTIVE;
```

**Comment by nicehashdev** [comment]
We want EQM to be visible to the user. Botnet owners often abuse our software if it can easily be hidden. From this point on, we will be working to make everything MORE visible and not less.
