### ISSUE TITLE
Why don't I see CryptoNight as a choice for AMD GPU's?

### ISSUE THREAD

**Issue by uvxdev** [nicehash/NiceHashMiner-Archived#494]
Running a Windows 10 rig with 4X R9 390's
NH does't show CryptoNight (Note) as a choice for mining at all under GPU.
I do see it under the CPU.
Really want NH to have this algo for 3rd party Claymore.
Please add ASAP.
Thanks

**Comment by S74nk0** [comment]
It will be added in the near future.

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/430)
