### ISSUE TITLE
Added a new (old) GPU and now NHM doesn't detect my 290x

### ISSUE THREAD

**Issue by flyize** [nicehash/NiceHashMiner-Archived#495]
I recently added an old x300 video card to push an extra monitor I have.  Since adding that card, NHM refuses to see any of my AMD GPUs.  Log file attached...
[log.txt](https://github.com/nicehash/NiceHashMiner/files/685951/log.txt)

**Comment by S74nk0** [comment]
@flyize I'll post a patched version for dev detection... it will generate a log and we can see what is the problem

**Comment by flyize** [comment]
That would be awesome.  Thanks

**Comment by flyize** [comment]
@S74nk0 Any updates on this?

**Comment by S74nk0** [comment]
Hi @flyize. Sorry for the late reply. 
[AMDOpenCLDeviceDetection.zip](https://github.com/nicehash/NiceHashMiner/files/693939/AMDOpenCLDeviceDetection.zip) unzip this somewhere and run **runAMD_log.bat**. This will generate a text file called **AMD_Detection_LOG.txt**. Send back that file. The AMD detection program is modified. I will try to prepare a new detection program (that is in the making) as soon as possible. Sorry for waiting.

**Comment by flyize** [comment]
@S74nk0 That returns a blank log file.  I ran it as administrator as well, just in case.

**Comment by S74nk0** [comment]
That being blank is probably the error. But it should not be blank, some error should have been logged. What does the **Event Viewer** show after running this program?

**Comment by flyize** [comment]
Okay, I'm embarrassed that I didn't try this first, but I have resolved the issue.

After that exe didn't work, I figured maybe the driver somehow got hosed when I installed this old ass x300.  I removed all drivers with DDU, then reinstalled the x300 driver, then the R9 driver.  After a reboot, everything works again.

**Comment by S74nk0** [comment]
@flyize no need to be embarrassed :). If you can remember what were the old driver we can add a check that will prompt the user to install a newer version.

**Comment by flyize** [comment]
I installed the same drivers again, so I'm really not sure what the issue was.  But burning everything down with DDU and starting over seems to have fixed it.
