### ISSUE TITLE
daggerhashimoto still isn't reporting and I've had to turn it off!!!

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#496]
ON MY AMD 480 CARDS!  I see higher payout and then nothing on the stats site!!!  Not my first post for this problem!

**Comment by S74nk0** [comment]
Are you running Windows 7?

**Comment by tokkenno** [comment]
Same problem here.

Windows 7 x64 SP1
Nicehash 1.7.3.12
Saphire rx480 8Gb

**Comment by tmslacker** [comment]
8.1 and 10 x64
same version

**Comment by kezdarkriser** [comment]
I got used to mining with this but gonna have to start looking elsewhere again now as since amd messed up a month ago struggling to earn 30k satoshi no matter what now , not even a third of my electric  covered

**Comment by semisane** [comment]
Ugh. Same here. NHM showing stats fine. Just not getting paid for it. 
Awesome.
Win10
4x480 8GB

**Comment by semisane** [comment]
I'm going to be doing a clean install of Win10 + drivers - I think they got updated.
Will follow up.
What drivers is everyone running?

**Comment by septk** [comment]
Hi, 

I've rx480, when I start bench, daggerhashimoto still run but not complete the work for start to mine.

What can I do?

**Comment by semisane** [comment]
septk - put in 23MH/s for Dagger. Don't benchmark it.

**Comment by septk** [comment]
ethminer.exe it run, but when receive new job mining was 0.00MH/s.

I've setup that @semisane says :), this is problem of nicehash?

thanks

**Comment by tmslacker** [comment]
They are the best and I respect the work they do!  I want to thank the people working hard on GetHub.  This problem has only really been an issue for 3 weeks and has been reported 5+ times.  I'm sure they have way bigger issues than helping the small guy or gal trying to show their support!  It's not like down time really affects the smaller miner that are trying to cover or break even.

**Comment by tmslacker** [comment]
I respect the work you do(S74nk0)!  I would like to be part of the solution.  Privet contact?

**Comment by S74nk0** [comment]
This issue seems to be **driver related**. Revert to **v16.10.3** and report if shares are getting accepted (check stats should show accepted shares for worker).

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/503)
