### ISSUE TITLE
version 1.7.3.12 "hide Mining Window" no longer respects setting

### ISSUE THREAD

**Issue by DaaBoss** [nicehash/NiceHashMiner-Archived#497]
Last version, (11), did respect this setting, 12 doesn't.  I started mining GPU GTX-980M / equihash (runs at 180 Sols consistently, BTW), and noticed that it pops up a CMD window every time I start.  Rechecked settings in both v11 and v12, both are set to "not open the mining window", and only v11 skips opening the window.  I had to run with this setting, since it got annoying to have it change algorithms often, and then while I am working, bring up a new CMD into the foreground every time it changes.  Losing focus of MY work is annoying.  

Granted, this is a minor annoyance, but....  This is the only setting change, other than setting a minimum profitability setting in both versions.

**Comment by S74nk0** [comment]
[related](https://github.com/nicehash/NiceHashMiner/issues/476). **equihash** is an exception and it will be shown no matter the setting.
