### ISSUE TITLE
u2 ant miner

### ISSUE THREAD

**Issue by protossdisaster** [nicehash/NiceHashMiner-Archived#498]
Are you guys going to incorporate the ant miners sticks? I'm running mine on a different company because your pools are dead and useless. There has to be a way to plug and play the ant miners

**Comment by felixbrucker** [comment]
as its a bitcoin (sha256d) mining asic it can only use this algorithm so you can just point your mining software for this asic to the nicehash sha256(d) stratum server(s)

running it in nicehashminer is pointless as it cant switch to another algorithm
