### ISSUE TITLE
[FEATURE] on same devices link config/benchmarks

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#499]
Currently if one has a rig with same cards and benchmarks only one GPU (GPU0) the values are getting changed in the corresponding other GPUs if they are set to use the config of GPU0.

Now if i change some values manually, they are not copied over to the other cards.

It would be great if all "linked" cards would also get the changed values copied over if i change something manually.

**Comment by S74nk0** [comment]
this feature will probably be included in one of the newer releases.

**Comment by kenshirothefist** [comment]
This is now in our internal to-do. Thanks for feedback!
