### ISSUE TITLE
[BUG] neoscrypt benchmark and other little problems

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#50]
**BUG:**
NVIDIA GTX 960  (NVIDIA5.x) neoscrypt completes the benchmark (is the result 0.340 MH/s ok?)
NVIDIA GTX 760  (NVIDIA3.x) neoscrypt does not complete the benchmark at all.(the result is 0)
The bug is present not only in 1.3.0.1 but also  in older releases, for example 1.2.3.2

![problems](https://cloud.githubusercontent.com/assets/16473762/13732394/7ed27f24-e98a-11e5-838a-cff4330f4655.png)

**INTERFACE:**
Resize window doesn't work in Windows 10  (Benchmark window / Config window)
I have to click in the title bar and then resize in order to resize.
Using Windows 7 it works, dragging the lower right corner, as should be.
Maybe you need to add an explicit resize box or change window style.

**DISPLAY**
Ethminer shows a strange seedhash the first 8 are hex, then the last 3 are printed incorrectly
Maybe the printf doesnt' have the right format for very large numbers?
It also should be nice to give a clue to the user of how much time to wait, or a countdown.

**FEATURE REQUEST:**
During benchmark, It should be nice to check for existence of the executable
and display "Can't find exe" if benchmark cannot find the executable
and not "Terminated" to give a better clue to the user of what happened.
(if some antivirus program deletes it)

**Comment by mendoza1468** [comment]
Hi, if you have upgraded to the last nvidia driver who is 364.51, those are the worst driver since alot of time from nvidia. Try go back to 362.00, maybe it should repair your problem. I lost 5 mh/s with 364.51 drivers on gtx 970 for quark. For your other problem idk !

**Comment by mendoza1468** [comment]
![capture - copie](https://cloud.githubusercontent.com/assets/16471209/13756173/0946dda2-e9f5-11e5-8c70-64aaf95fec49.JPG)

I'm getting 2 kind of error on this version with Neoscrypt

**Comment by CreamyG31337** [comment]
I agree -- please detect missing exe and give a warning (not a stack of 200 message-boxes please) and continue to the next most profitable algorithm.

**Comment by Singman33** [comment]
I got a bug while mining neoscrypt on GTX 960, the program want to launch ccminer_neoscrypt.exe but that program doesn't work. I copied the ccminer_sp.exe over it because this miner is working, and everything is fine.
Not sure why NicehashMiner want to launch a specific miner for Neoscrypt, hashrate is very similar.

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.
