### ISSUE TITLE
Cryptonight issue

### ISSUE THREAD

**Issue by TheButtShark** [nicehash/NiceHashMiner-Archived#500]
I'm kinda new for this Bitcoin mining thing and I have a problem with cryptonight: when benchmarking GPU my cryptonight speed is 22. 867 MH/s, ratio is about 1680... and BTC/day is 38! I'm using standart gaming computer. Also my NVIDIA drivers crash when starting mining and when benchmarking cryptonight. Thank You.

**Comment by p1r473** [comment]
I also get crashing when benchmarking it

And I am also making a ton of money (but not really)
![image](https://cloud.githubusercontent.com/assets/9235633/21738403/3fd6d8ca-d452-11e6-9d82-c6ef1672d158.png)

**Comment by S74nk0** [comment]
@TheButtShark & @p1r473  we will be changing the CryptoNight miner. Please try the current miner with the [new](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/ccminer_cryptonight_new.zip) one, just copy over the original under **bin** folder. The miner is faster and hopefully more stable. Please report back if it fixes the issue with huge hash rate reports (**a known BUG**).
Thanks!

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
