### ISSUE TITLE
message "Too many resources requested for launch" on nvidia card gforce 540m on dell laptop

### ISSUE THREAD

**Issue by karboxifene** [nicehash/NiceHashMiner-Archived#501]
hi all

when i try to run mining with CPU anf GPU or only GPU i have this message 
"too many resources requested for launch"
on Del laptop with gforce 540m 

what sould i do?

thanks

**Comment by karboxifene** [comment]
nobody can help me?

**Comment by S74nk0** [comment]
@karboxifene I would advise you NOT to use a laptop/ mobile CPU/GPUs, you will not earn as much.
