### ISSUE TITLE
Mining stats not showing correctly on Web 

### ISSUE THREAD

**Issue by rnahlawi** [nicehash/NiceHashMiner-Archived#502]
Hi,
Since NiceHash 1.7.3.10 and my Daggerhashimo mining is not showing on nicehash website. 
Currently have 1.7.3.12 and mining with 4x 480s. Other workers for different protocols are showing correct.

**Comment by PauloOF** [comment]
Same problem with 1.7.3.12 with several R390X Rigs when mining Daggerhashimo.
 
Workername appears at "Active workers" list, however the "Speed (accepted)" is always zero as well as the revenue.

**Comment by semisane** [comment]
I think this is a driver issue. I had 4x 480's and had to clean install windows and use older drivers.

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/503)
