### ISSUE TITLE
[BUG] DaggerHashimoto new Driver issue

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#503]
Good day, dear developers,
I have a problem with DaggerHashimoto, have the following graphics cards: - ADR Fury Strix, Radeon 480 2 pieces and Radeon 390, the problem is that your miner produces only the tasks running, but Reshin are not very long time, ran the same bunch video card on the miner from Claymore version 7.4 ...... everything is working fine and no problems with your miner and DaggerHashimoto permanent problems occur when working with a bunch of my cards!
DEAR DEVELOPERS Please solve the problem at least in some way!
Доброго времени суток, уважаемые разработчики,
у меня возникла проблема с ДаггерХашимото, есть следующие видеокарты: -- АСУС  ФЬЮРИ СТРИКс, Радеон 480 2 штуки и радеон 390, проблема в том, что ваш майнер выдает только задания на выполнение, но решиния не находятся очень долго время, запускал ту же связку видеокарт на майнере от Клеймора версии 7.4 ......всё работает нормально и без проблем, с вашим майнером и ДаггерХашимото постоянно проблемы возникают, при работе с моей связкой видеокарт! 
Пожалуйста УВАЖАЕМЫЕ РАЗРАБОТЧИКИ решите проблему хоть каким-то образом!

**Comment by septk** [comment]
same problem here @BARUCHER777

**Comment by protossdisaster** [comment]
All my work is being done and everything looks fine I never receive my payouts,

**Comment by S74nk0** [comment]
This issue has been present after new **AMD drivers** have been released. We are working on a fix. You can try installing **driver version 16.11.1** or lower, if driver downgrade doesn't get accepted shares then disable Dagger for the time being. When changing drivers make sure to check online stats and see if there are any accepted shares (NHM will be fixed to notify if there is local activity and no online activity **valid shares**)

**Comment by S74nk0** [comment]
This issue seems to be **driver related**. Revert to **v16.10.3** and report if shares are getting accepted (check stats should show accepted shares for worker).

**Comment by tokkenno** [comment]
@S74nk0 yes, downgrade to v16.10.3 apparently solve the bug. Thanks!!

**Comment by S74nk0** [comment]
**AMD ethminer is discontinued**
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
