### ISSUE TITLE
 GekkoScience Compac BM1384 Stickminer algorythm for nicehash ?

### ISSUE THREAD

**Issue by karboxifene** [nicehash/NiceHashMiner-Archived#504]
hi,

there is a way to use  GekkoScience Compac BM1384 Stickminer  for mining in nicehash ?

thanks for your information

**Comment by felixbrucker** [comment]
as its a bitcoin (sha256d) mining asic it can only use this algorithm so you can just point your mining software for this asic to the nicehash sha256(d) stratum server(s)

running it in nicehashminer is pointless as it cant switch to another algorithm

**Comment by karboxifene** [comment]
Thank felixbrucker, but if i try to use bfgminer, i don't detect my bm1384 and i i use cgminer, i don't accept adress#xnsub..... 

there is a special version of bfgminer or cgminer ?

i try all from this page https://www.nicehash.com/?p=news&id=49 but nothing work

**Comment by felixbrucker** [comment]
i suggest you read https://bitcointalk.org/index.php?topic=1173963.0

there is a bfgminer commandline example listed, be sure to use the correct hex for clocks

you might not have used the correct bfgminer version, 5.3.0 added support

**Comment by karboxifene** [comment]
I already read this page :( and i have 5.4.9 version of bfgminer.
i use too zadig for install good usb driver, if i use cgminer for pool eu.stratum.bitcoin.cz it work fine but if i use cgminer for nicehash with #xnsub parameter then it don't work, it detect correctly the BM1384 usb stick

**Comment by felixbrucker** [comment]
i dont own one so i cant help you further, might be an option to raise this question in the mentioned support thread (regarding bfgminer and why it might not work)

**Comment by karboxifene** [comment]
ok, thanks a lot for your time for your help felixbrucker

**Comment by Kamnoie541** [comment]
where is the  bfgminer 5.3.0 for download. PLEAS

**Comment by denics** [comment]
Hi @karboxifene you can find here https://github.com/denics/cgminer.git a version of cgminer tricked to work with #xnsub . use the xnsub branch. I'm using it without issue but no new luck yet :D
