### ISSUE TITLE
GTX 1060 3GB Mini

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#505]
I was just wondering what the difference in hash rate would be between a 6GB GTX 1060 and a Zotac 3GB GTX 1060 Mini? I see on the profitability chart 280mh/s equihash on GTX 1060. Not sure how much ram that one has.. Can anyone elaborate please?
I am planning on buying 6x GTX 1060 Mini cards for mining.

**Comment by Johann1982** [comment]
The Zotac also uses the pascal chip, so not sure if that will make any improvement over previous maxwell versions.

**Comment by Johann1982** [comment]
Does anyone have the stats of GTX 1080 and Titan cards?

**Comment by GIRTAB1** [comment]
Yes, I have 2 EVGA GTX 1080 8GB FTW.  Benchmarking at 49MH's/Lyra2rv2 and 428H/s/Equihash each.

**Comment by Johann1982** [comment]
@GIRTAB1 Thanks Girtab, appreciate the feedback.
Then I am buying a couple of GTX 1070. They are a bit more profitable.
