### ISSUE TITLE
750ti/cryptonight hash drops in half on win10.

### ISSUE THREAD

**Issue by zhulick** [nicehash/NiceHashMiner-Archived#506]
well, almost half...

same card, same version of drivers (376.33), with proper version installed for each system.  win7, full speed ahead at 240-250h.  win10 tops out at 140, so almost half.

tried two separate win7 systems, and two separate win10 systems - problem is replicated on both win10 boxes.  zero issues on win7 boxes.

**Comment by blue-yu** [comment]
I am having the same problem. Already reported it, but no solution so far :( I was even asked to send log to developer, but nothing :( To bad, since 750ti is great for cryptonight at the moment...

Ajde Stanko, sredi vise taj problem :)

**Comment by S74nk0** [comment]
@zhulick This problem can be easily fixed. There were changes with the miner binary.
Check out [this](https://github.com/nicehash/NiceHashMiner/issues/658). Best to use [pre-release](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.2-pre/NiceHashMiner_v1.7.5.2_PreRelease_2.zip)

Sorry for the inconvenience
