### ISSUE TITLE
RX 470 low benchmarking

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#507]
My RX 470 starts up getting around 23 MH/s but then settles down around 8 MH/s. What's going on here?

**Comment by S74nk0** [comment]
@BurntOrange what algorithm?

**Comment by ghost** [comment]
@S74nk0 Sorry about that - dagger hashimoto

**Comment by S74nk0** [comment]
try this [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.2) it has a new miner. Report your speeds.

**Comment by ghost** [comment]
Hi,

I'm now getting around 21 MH/s but not the 24-25 MH/s on daggerhashimoto that I'm seeing reported by others. Not sure what I should change.

**Comment by S74nk0** [comment]
Try https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre.

This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
