### ISSUE TITLE
CPU Benchmark & mining not working

### ISSUE THREAD

**Issue by Freshbrewed** [nicehash/NiceHashMiner-Archived#509]
I have 2 computers using both different CPUs, i5-3570K and i7-4770K. Both setups have 1x GTX 970 which is benchmarking and mining fine. 

Problem is, when setting up benchmark for the CPU, it skips all the tests and writes speed as "none". When I start any of the mining algorithms, it just closes the miner. If I turn off the CPU mining, miners don't crash and GPU will mine normally. Been trying to run manually eqm zcash miner with CPU thread parameters but it crashes the miner. No error messages in the miners displayed whatsoever.

This happens in both setups. What do ?

**Comment by S74nk0** [comment]
@Freshbrewed check if the **Anti Virus (AV)** software isn't flagging the miners. These CPU miners have been bundled inside malware and are flagged and/or deleted by **AV software**. The CPU miners are harmless the AV detection jumps because they were bundled inside malware (the miners are open source).

**Comment by Freshbrewed** [comment]
The  folder I keep all the miners and NiceHash contents are excluded from Antivirus scan.


EDIT: When I start mining with any mining software, it finds the allocated threads within the miner, from 1 to 8 (4770K) and from 1 to 4 (3570K) as it does for the GPUs. But as soon as it lists the threads, the miner crashes.

**Comment by S74nk0** [comment]
@Freshbrewed Does this issue only happen with **eqm** Equihash on CPU? Other CPU algorithms are running fine?

**Comment by Freshbrewed** [comment]
As stated in the first post, none of the miners provided by the NiceHash are benchmarking and mining with my CPUs.

**Comment by S74nk0** [comment]
@Freshbrewed try running **eqm** manually with the following command: **eqm.exe -p 1 -t 4 -a 4001 -l eu -w test01 -u 34HKWdzLxWBduUfJE9JxaFhoXnfC6gmePG -f 0**. It should generate a folder (**archived_logs**) with the logs inside. You can change the -t parameter to number of threads of you CPU and the BTC addr to your own. If it generates a folder **archived_logs** zip it and post it here. Also if you can check the **Event Viewer** there will be some more useful information that can help us find the problem.

**Comment by Freshbrewed** [comment]
Here's the log file when running CPU with 4 threads:

[log_2017-01-11_13-49-04.000.txt](https://github.com/nicehash/NiceHashMiner/files/698707/log_2017-01-11_13-49-04.000.txt)


Locked pages should not be an issue here.

**Comment by S74nk0** [comment]
I think you are correct about **Locked pages** this is not an issue here. But the miner is crashing after getting work. It would be very helpful if you could provide information from the **Event Viewer**.

**Comment by Freshbrewed** [comment]
Here are some of the errors listed in the Event Viewer.
[error.txt](https://github.com/nicehash/NiceHashMiner/files/698727/error.txt)
[information.txt](https://github.com/nicehash/NiceHashMiner/files/698728/information.txt)
[error2.txt](https://github.com/nicehash/NiceHashMiner/files/698729/error2.txt)


EDIT: Those are the Event Viewer logs generated while running eqm manually. I'll try to run NiceHash GUI and see if it generates different kind of logs.

**Comment by S74nk0** [comment]
@Freshbrewed thanks. We will take a look into it.

**Comment by Freshbrewed** [comment]
Here are the Event Viewer logs regarding to NiceHash GUI. There were alot more from a single running instance, but the logs were just repeating itself. Couldn't post here as a ZIP file so I'll stack em up..













[error1.txt](https://github.com/nicehash/NiceHashMiner/files/698761/error1.txt)
[error2.txt](https://github.com/nicehash/NiceHashMiner/files/698759/error2.txt)
[error3.txt](https://github.com/nicehash/NiceHashMiner/files/698758/error3.txt)
[error4.txt](https://github.com/nicehash/NiceHashMiner/files/698757/error4.txt)
[error5.txt](https://github.com/nicehash/NiceHashMiner/files/698762/error5.txt)
[error6.txt](https://github.com/nicehash/NiceHashMiner/files/698760/error6.txt)
[error7.txt](https://github.com/nicehash/NiceHashMiner/files/698764/error7.txt)
[error8.txt](https://github.com/nicehash/NiceHashMiner/files/698763/error8.txt)
[error9.txt](https://github.com/nicehash/NiceHashMiner/files/698766/error9.txt)
[error10.txt](https://github.com/nicehash/NiceHashMiner/files/698768/error10.txt)
[information.txt](https://github.com/nicehash/NiceHashMiner/files/698765/information.txt)
[information2.txt](https://github.com/nicehash/NiceHashMiner/files/698767/information2.txt)
[information3.txt](https://github.com/nicehash/NiceHashMiner/files/698769/information3.txt)
[information4.txt](https://github.com/nicehash/NiceHashMiner/files/698770/information4.txt)







EDIT: One more final note. I made a fresh Windows 7 install on both of the PCs yesterday. The old setup worked fine (3570K) mining any of the algorithms before the fresh install. Now after fresh install, both of the setups just won't mine.

**Comment by Johann1982** [comment]
@Freshbrewed Hi

Have you tried using an older version of NHM to test? Maybe it is a bug in the latest version?

**Comment by Freshbrewed** [comment]
Yes, I've tried using these versions:

1.7.3.1
1.7.3.3
1.7.3.5
1.7.3.10
1.7.3.12


Also the title of this thread is incorrect - it's not only 1 algorithm that is not working **but all of the NiceHash CPU mining algorithms.** None of them benchmarks and mines.

**Comment by Johann1982** [comment]
@Freshbrewed Ok, if your setup worked before formatting and re-loading I can only think that it is driver related. Try updating your chipset drivers of your mainboard and see if that makes a difference. What mainboard are you using?

**Comment by Freshbrewed** [comment]
I have thought the same, it cannot be coincidence that both of the rigs can't mine after fresh install.
1st rig: Asus Maximus Gene VI Z87 + 4770K
2nd rig: Gigabyte z77-UD3H + 3570K


I'll try to fetch some updates.

**Comment by Johann1982** [comment]
@Freshbrewed You can also try a different version of windows to test. If you have a spare hdd, install win 10 on it and give it a test. You don't need a license to install the trial. I had issues with win 7 x64 on one of my machines, after installing 8.1 x64 it worked perfectly.

**Comment by Freshbrewed** [comment]
If Windows 7 have worked perfectly fine, I don't see why I would change whole operating system only to resolve this issue.


EDIT:  I've just updated all my system device drivers, chipset drivers and everything worth updating. Restarted computer and ran benchamark - same issue. No benchmarking, CPU can't mine. Odd.

**Comment by Johann1982** [comment]
@Freshbrewed it is only to test that it is not hardware related. Could be that you have damaged hardware that can also cause this issue. Blown capacitors in the psu or on the mainboard etc. Just part of the troubleshooting process in case the chipset drivers doesn't work. I personally hate win 10.

**Comment by Freshbrewed** [comment]
I highly doubt that it is hardware related problem. Stresstests run fine, I don't see any corruptions or system unstability. No blue screens, no lag, no jamming. Motherboards are in excellent condition, I build computers as a hobby.

PSUs are also not defective. They are high quality and fairly new, Evga Supernova G2 750W & SuperFlower 550W Platinum.

**Comment by Johann1982** [comment]
@Freshbrewed Ok, then it is probably software.

**Comment by Pizzaguy1234** [comment]
OK had this happen to me but figured it out. During the benchmarks, only benchmark one device. Use the Start Button, not the Benchmark button, click yes! I don't know why. You should have started running program as admin. Instead of a (none field )you should see dot dot dot....on the first algorithm if not then restart. On or about the next to the last stage of equihash last algorithm - 2 dialogs will pop up from windows firewall watch for them, check both boxes and click allow. Repeat for each device if needed for Miner v1.7.4.2 and Miner v1.7.4.1 Windows 10 x64. If this didn't work you might need to restore defaults on windows firewall and try again.

**Comment by Freshbrewed** [comment]
Tried, nothing works. Every CPU miner crashes following a popup window telling me "thisminer.exe has stopped working". Here's a pic: 
![untitled](https://cloud.githubusercontent.com/assets/25055044/22331697/898c9198-e3d5-11e6-97ad-3527f740ecaa.png)

**Comment by someguy736** [comment]
Out of curiosity, could you open an **elevated** task manager, sorted by image name and with NiceHashMiner.exe highlighed, and then try to benchmark and screenshot when the error happens?

**Comment by Johann1982** [comment]
Try uninstalling avast

**Comment by Freshbrewed** [comment]
@someguy736 here's the pic: 
![untitled](https://cloud.githubusercontent.com/assets/25055044/22334906/23c4d55e-e3e5-11e6-8566-168598713547.png)

There's like 10 "program has stopped working" popups I must close during benchmark until it's done.

@Johann1982  I'll try that as a next step.
EDIT: Uninstalling Avast didn't solve the problem.

**Comment by Johann1982** [comment]
What type of windows 7 installation do you use? Is it an original disk or a modified one with extra drivers and programs inserted into the installation media? Try doing a fresh installation with drivers only. Install nhm and see if it works.

**Comment by Freshbrewed** [comment]
@Johann1982 At the moment I cannot fresh install Windows again. Running retail Win 7 with ultimate license.

Can anyone come up with any critical driver I could forgot to install ?

**Comment by someguy736** [comment]
If the program can start you have the correct drivers, and if the program can run for any length of time you have the correct software installed. Looking at the error logs it appears something in the NHM code is trying to access the other mining programs twice and when it can't hook it the second time, because it's still being used, it crashes.

Without any coherent debug information it's impossible to say for sure, but I've seen this kind of thing in C# programs I've made myself. At this point it appears to be an issue with NHM and there's nothing to do but wait until someone figures out what that problem is.

**Comment by Freshbrewed** [comment]
@someguy736 How come none of the older versions work with my setups then ? Problem ain't in the software only, quess my setups have problems also.

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.

**Comment by Freshbrewed** [comment]
@S74nk0 

It is still not benchmarking with the Pre-Release version.
![untitled](https://cloud.githubusercontent.com/assets/25055044/23587118/05feeba4-01ae-11e7-98a3-eeadb341e9bd.png)

**Comment by addictedindian** [comment]
@Freshbrewed  @S74nk0  same problem is happening here

![log](https://cloud.githubusercontent.com/assets/26764336/24449069/dbfe2cfe-1493-11e7-8846-0ab0055df8e0.jpg)

**Comment by TheFreak000** [comment]
I have the same issue with the runtime popup, using win 7 64bit intel 4690k. Anyone found a solution yet?

**Comment by guyviner** [comment]
disable your antivirus for 15 minutes and try again. .worked for me to detect and benchmark my CPU.
