### ISSUE TITLE
Slower Neoscrypt and eth problem

### ISSUE THREAD

**Issue by mendoza1468** [nicehash/NiceHashMiner-Archived#51]
I get slower Neoscrypt with this version - 125 mh/s , problem solved if i copy the ccminer_neoscrypt from 1.2.3.2 to 1.3.0.1. (same nvidia drivers)

Still get same problem on eth with 2 gtx 970 win 10, 30 mh/s benchmark but after 5 min run 5 mh/s.

**Comment by theLosers106** [comment]
AFAIK the ccminer_neoscrypt did not change from the previous version.. maybe a fluke while benchmarking? have you tried it a few times? about the eth.. it is a known problem where Windows 10 will produce higher benchmark but real mining really sucks.. not sure why though..Genoil or someone else might have a better idea than me.. not really a NiceHashMiner problem though =/

**Comment by mendoza1468** [comment]
I've tried 3 bench, all same result

**Comment by mendoza1468** [comment]
Thanks for the info. You can closed the thread if its a known bug for Eth.

**Comment by theLosers106** [comment]
Alright.. You are welcome.. (:
