### ISSUE TITLE
[FEATURE] OC/UC/TDP per algorithm

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#511]
I dont know if there is any existing tool for this purpose, but it would be great if we could set Overclocks, Underclocks and Powerlimits per algorithm.
This allows for precise tuning of the cards for specific demands by the algorithm currently being mined.

As of now one as to use "generic" settings that work on most algos best, but are not optimal for others.

I suspect this to be a major piece of work if there is no easy to use app that handles amd and nvidia correctly and is accessible via easy cli/api commands.

For generic purposes i used Afterburner, but im not sure it has an api/cli interface.

**Comment by fefsf** [comment]
This would be insanely awesome if implemented but its doubtful.

**Comment by S74nk0** [comment]
I believe this is considered but it will not land soon.

**Comment by felixbrucker** [comment]
i already guessed it, not a biggie

its also obviously not for beginners which this software is originally intended for

will maybe have a look at this in a few months, maybe i can write a simple parser to enable this (like your nvidia/amd detection exe)

**Comment by nicehashdev** [comment]
We have this planned for our own backend C++ miner. Closing.

**Comment by felixbrucker** [comment]
@nicehashdev by backend c++ miner you mean excavator?

**Comment by nicehashdev** [comment]
Yes.
