### ISSUE TITLE
[request] AMD cryptonight miner

### ISSUE THREAD

**Issue by happyartifact** [nicehash/NiceHashMiner-Archived#512]
Would there be the possibility of adding Claymore's Cryptonight miner to 3rd party miners to allow for this mining on AMD cards?  Right now I'm starting them manually, which doesn't allow for profit switching.

**Comment by S74nk0** [comment]
Yes. Next release will have this ([commit](https://github.com/nicehash/NiceHashMiner/commit/91acd373d5b9af5f32ec21e566318d35cc351d89))

**Comment by happyartifact** [comment]
Thank you!  (Missed that commit.)  Brilliant work on NHM.

**Comment by SanekXXX4** [comment]
how to prevent Miner fan speed control, it puts me 100%, although the msi afterberner value is 60%, claymore criptonote)

**Comment by S74nk0** [comment]
@SanekXXX4 read [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters). When starting the new [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.4) there will be an internals folder created ([read](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#how-to-add-missing-miner-flag)).

Closing issue as AMD cryptonight is available with sgminer and claymore miners.
