### ISSUE TITLE
Question: Minimum NVIDIA Driver

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#513]
What is the least driver version needed for NHM to work?

I'm having BSOD on new drivers.

**Comment by S74nk0** [comment]
@N8Thrasher **372.54** is recommended (lastly fully tested). **eqm** was frequently being changed over time (and didn't exist at the time when **372.54** were latest drivers). 
Does it BSODs on every algorithm/miner? What is your setup?

**Comment by N8Thrasher** [comment]
Im running Win 7-64bit, 8GB RAM, i7-4790, GTX 460, GTX 780Ti, GTX 780.
BSOD appears on new install of NHM during benchmarking.

Anyway I solve it, I reformat and fresh install of Windows 7 64bit. everything's working fine so far. Maybe there's some conflict on software somewhere before.

Although it doesnt solve the issue on my other post, Still have that issue on my other post regarding the GPU (780/780Ti) not benchmarking and hashing on Equihash.

**Comment by S74nk0** [comment]
GPU (780/780Ti) Equihash is broken and there aren't plans to fix it.

Closing...
