### ISSUE TITLE
Mined DEC 31 to Jan 14, Did not recieve payout today, 

### ISSUE THREAD

**Issue by AlaskaHobbyMiner** [nicehash/NiceHashMiner-Archived#514]
Hello, 
I have been mining on Nicehash with 2 RX480's since late October,
Until today I have always received payment at the time indicated on the profitability calculator, .

However, Today I did not receive payment for mining from Dec 31 to Jan 14th,
My payout amount reset to zero this morning, 
but I did not receive my payment, which should have been around $25 - $27

I have been mining on v1.7.3.12 since it was released
My bitcoin address is correct

Can anyone tell me what happened, and where is my BTC?
please & Thank you
 -Chris

**Comment by nerdatwork** [comment]
I am wondering the same thing. Where is my payment ?

**Comment by AlaskaHobbyMiner** [comment]
I didn't recieve payment on the 7th either.

I switched to the new version right before the scheduled payment on the 7th,
and the estimated payment date changed to the 14th on the new version.

I was assuming that payment for the 7th was going to be added to the payment scheduled for the 14th, but it never showed up

**Comment by evtnlife** [comment]
i am start mining today and i am afraid about that.

**Comment by AlaskaHobbyMiner** [comment]
Ok I assume they're sorting this out,
 I just recieved payment for my mining on the current version. 
  Have not yet for my mining on the previous version, but i'm guessing that will arrive this evening, at the old 0800 payout time?

**Comment by nerdatwork** [comment]
received payment but the timing is 4 hours late

**Comment by AlaskaHobbyMiner** [comment]
Yep, mods please move this to solved.
I realize the payout time is estimated.
And I got paid for my current mining, 

I opened v1.7.3.11 and realized i had less than .01 btc mined before switching to v1.7.3.12,
So it's not going to pay that out until the 28th on the monthly payout for lower amounts.
So I'm good to go, 
Thanks!
