### ISSUE TITLE
Not really an issue, but more of a request

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#517]
How about creating a linux based Mining O/S that we can just run off a live cd that can start mining without much setup?

**Comment by S74nk0** [comment]
@Johann1982  This is in the works. Hopefully it will come out very soon.

**Comment by Johann1982** [comment]
That will be awesome. Thanks S74nk0

**Comment by S74nk0** [comment]
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
