### ISSUE TITLE
[FEATURE] API with current miner and ports running

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#518]
it would be super great if the NicehashMiner had some kind of a (JSON) API where i would get the current running miners and their API ports if available / or some general NHM API for this miner without the ports

Templates could look like this:

{
  "result":true,
  "miner":[
    {"type":"ccminer","port":4096},
    {"type":"claymore-zec","port":4097},
    ...
  ]
}

or in case of generalized NHM API:

{
  "result":true,
  "miner":[
    {"type":"ccminer","hashrate":1234,"suffix":"MH/s","algo":"lbry", ...},
    {"type":"claymore-zec","hashrate":456,"suffix":"Sol/s","algo":"equihash", ...},
    ...
  ]
}

the first case can probably be implemented easily as its just passing through the ports, whereas the second option would require the parsing of the already collected stats data for the running miners to be made available via api

The reason for all this is to enable 3rd party monitoring software for the miners stats

Sadly im not that experienced with C#, else i could help with this in terms of PR

**Comment by S74nk0** [comment]
@felixbrucker this will be included in one of the future releases (not the next upcoming version v1.7.4.0).

**Comment by felixbrucker** [comment]
thats awesome!

looking forward to it

**Comment by S74nk0** [comment]
@felixbrucker this will probably still be implemented but the desired effect to reserve certain API ports can be achieved now (read [here](https://github.com/nicehash/NiceHashMiner/wiki/Reserving-API-bind-ports-(Advanced)))

**Comment by felixbrucker** [comment]
thanks, i will have a look

**Comment by felixbrucker** [comment]
i will probably wait for the integration though as this does not show the currently running one and thus i would have to monitor all ports

**Comment by nicehashdev** [comment]
This will maybe be available in NHM 2.0.
