### ISSUE TITLE
Ether mining

### ISSUE THREAD

**Issue by swagkiller69** [nicehash/NiceHashMiner-Archived#52]
I'm mining ETH on my GTX 970m @ 9.9MH/s
2 questions
Why is this so slow, also, why does the nicehash debug console keep saying:
[20:36:01] [NVIDIA5.x] Ethminer WARNING!
[20:36:06] [NVIDIA5.x] Ethminer WARNING!
[20:36:11] [NVIDIA5.x] Ethminer WARNING!
[20:36:16] [NVIDIA5.x] Ethminer WARNING!
[20:36:21] [NVIDIA5.x] Ethminer WARNING!
[20:36:26] [NVIDIA5.x] Ethminer WARNING!
[20:36:31] [NVIDIA5.x] Ethminer WARNING!
[20:36:36] [NVIDIA5.x] Ethminer WARNING!
[20:36:41] [NVIDIA5.x] Ethminer WARNING!
[20:36:46] [NVIDIA5.x] Ethminer WARNING!
[20:36:51] [NVIDIA5.x] Ethminer WARNING!
Apart from the slow speed, Ethminer is working fine and receiving shares and I'm being paid for them
Thanks

**Comment by bpvarsity** [comment]
Try version 1.3.0.0 and see what you get. Nvidia cards are not good at mining ETH so dont expect anything over 10 especially with a mobile version of the 970.

**Comment by swagkiller69** [comment]
1.3.0.0 hasn't solved anything... but that's not a big issue, it's mining fine and temps are 58 degrees with my cooling setup...

Unrelated from nicehashminer but related to mining, I'm trying to get ETHminer working on my 770M
I got ethminer running. It mines and is getting hashes and doing work. http://puu.sh/nHrpc/ed81bc0fd4.png
I've tried starting it with different values which im told is diff, ranging from 7 to 4 and the proxy hasn't shown a single share in over an hour
whats the deal with this and can anyone help me?

**Comment by theLosers106** [comment]
@swagkiller69 Go to the bin -> ethereum folder.. edit the config.json file and change "clientTimeout" to something larger like "10m" .. *don't forget the double quotes

**Comment by swagkiller69** [comment]
But I'm not timing out? It's mining and my gpu is getting warm so it's
definitely working it's just not getting a single share.. But I'll try that
anyways, who knows it might work :P
Thanks

**Comment by theLosers106** [comment]
@swagkiller69 if that's the case I would try running using OpenCL instead of CUDA:

`ethminer.exe -G -F http://ethereum.LOCATION.nicehash.com:3500/n1c3-YOUR-BITCOIN-ADDRESS.WORKER-NAME/WORKER-SPEED`

**Comment by swagkiller69** [comment]
@theLosers106 Thanks for your quick reply.
It tries to run using my integrated graphics, instead of my GPU, on CGminer the fix for this was --gpu-platform 1; how do i resolve this on ethminer?

**Comment by swagkiller69** [comment]
Found the command. Here it is for anyone who needs it also: 
"--opencl-platform 1 --opencl-device 1"
Thanks for all your help, I'll update if/when I get a share :D

EDIT: I got a share! Thanks for all your help @theLosers106 ; if you post your btc address i'll send you my profits from this ETH from today :+1:

**Comment by theLosers106** [comment]
@swagkiller69 Genoil's latest ethminer has fixed Compute 3.0 that should enable you to run it on ur 770m.. will hopefully be in the next major NiceHashMiner release.. if you want to donate then head on to my bct link in my profile and thanks.. (:
