### ISSUE TITLE
v1.7.4.0 flagged as malicious by Chrome and Windows SmartScreen

### ISSUE THREAD

**Issue by nchangfong** [nicehash/NiceHashMiner-Archived#520]
As title suggests, file is automatically blocked after download completes. After bypassing and trying to run NiceHashMiner.exe, SmartScreen on Windows 10 also blocks execution.

**Comment by Johann1982** [comment]
Turn off smartScreen filter, use internet explorer to download

**Comment by nchangfong** [comment]
I'm not looking for a workaround and don't think your suggestion is really a solution but thanks anyway. I opened the issue to make developers' aware and in case others are experiencing similar issues.

**Comment by Johann1982** [comment]
The reason chrome, smartscreen and av programs flags NHM as malicious is because some of the miners were bundled in spyware and trojans. There isn't much that can be done about this as it is open source.
I think this is a duplicate post also as this has been gone over before.

**Comment by nchangfong** [comment]
Ah good point and I did see that there was one for Chrome (#373) I should have linked earlier but for a previous version (v1.7.3.5) with almost no information.

**Comment by aaronsace** [comment]
Different miners get blocked all the time; nothing can be done. Just allow it. 

https://github.com/nicehash/NiceHashMiner
> My anti-virus is blocking the application
> Some anti-virus software might block NiceHash Miner as well as supporting back-end programs (cpuminer, ccminer, sgminer) due to false-positive matches. All software, included into NiceHash Miner has been verified and checked by our team and is absolutely virus/trojan free. Our service is well established and trusted among users, therefore you can fully trust software releases that are downloaded from our GitHub repository: https://github.com/nicehash/NiceHashMiner/releases. However, make sure you never download and run any files from other unknown sources! If you downloaded the software package from our GitHub repository you can simply resolve the issues with false-positives by adding the files sgminer.exe, ccminer_sp.exe, ccminer_tpruvot.exe, cpuminer_x64_AVX.exe, cpuminer_x64_AVX2.exe and cpuminer_x64_SSE2.exe to anti-virus exception list.
