### ISSUE TITLE
[BUG] Warning! Algorithm cryptonight is reporting 0 shares accepted. NHM 1.7.4.x

### ISSUE THREAD

**Issue by ShippyG** [nicehash/NiceHashMiner-Archived#522]
After update i started getting this warning:
https://gyazo.com/153df519e8f236298dcd2c4af0ee3f15

Nicehash miner version: 1.7.4.0

**Comment by S74nk0** [comment]
@ShippyG Yes this is a BUG just fixed... In about 5 minutes expect a new version **1.7.4.1**

**Comment by S74nk0** [comment]
critical issue fixed...  [new release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.1)
Closing...

**Comment by SanekXXX4** [comment]
Still having 0 shares warning on cryptonight on NHM 1.7.4.1

**Comment by S74nk0** [comment]
@ShippyG @SanekXXX4. On what hardware are you mining cryptonight?

check if your worker is listed here:

https://www.nicehash.com/api?method=stats.provider.workers&addr=BTC_ADDR&algo=PROBLEMATIC_ALGO_ID

Change BTC_ADDR with yours and PROBLEMATIC_ALGO_ID with the id. 22 = CryptoNight.

Keep the miner running and check the url periodically every 5 minutes and report when/if it is showing in the list.

**Comment by SanekXXX4** [comment]
R9380X
RX480
i5-4440
https://www.nicehash.com/api?method=stats.provider.workers&addr=1MuvUhvjEsakZZQ8yTPLe2vFrf5K5GPguR&algo=22

**Comment by S74nk0** [comment]
@SanekXXX4 the stats are on. After the first warning do you keep getting new warning (if you leave it mining you shouldn't be getting another warning)?

**Comment by SanekXXX4** [comment]
Yes, there was only one warning)

**Comment by S74nk0** [comment]
Please try this patch [NiceHashMinerv1.7.4.x_patch.zip](https://github.com/nicehash/NiceHashMiner/files/713848/NiceHashMinerv1.7.4.x_patch.zip). This issue seems to be currently happening only with cryptonight. The patched version should give it more time to pass the accept.

**Comment by ShippyG** [comment]
@S74nk0 I get same warning also with equihash and every time i select "OK" it takes about 30 minutes and same warning comes again.

Also i get this: {"result":{"addr":"1EqQg73Yz1WHdhP765ZNXZckxYQu2YSwBK","workers":[["worker1",{"a":"0.03"},39,1,"10000",0]],"algo":22},"method":"stats.provider.workers"}

My current rig:
i7-6700K
Asus Strix GTX 970 4GB OC
8GB DDR4 2133MHz

**Comment by N8Thrasher** [comment]
on my rig as of the warning appeared while on CPU/Cryptonight  but sometimes shares are showing on the Nicehash Web, sometimes not.

**Comment by SanekXXX4** [comment]
@S74nk0  all was solved with this patch, thanks)

**Comment by ShippyG** [comment]
Also @S74nk0 when i try running your NiceHashMiner_patch file, nothing happens.

**Comment by S74nk0** [comment]
@ShippyG did you copy the patch in the NHM folder?

**Comment by ShippyG** [comment]
@S74nk0 Yes, it took about minute to open for some reason.

**Comment by S74nk0** [comment]
@ShippyG @SanekXXX4 @N8Thrasher please replace the patched version. Keep it running and report back if this issue is repeating.

**Comment by ShippyG** [comment]
@S74nk0 After using your NiceHashMiner_patch.exe my cryptonight mining does not work anymore.

**Comment by N8Thrasher** [comment]
patch worked so far, patching other miners. Thanks

**Comment by ShippyG** [comment]
@S74nk0 Now it finaly got 1 accepted.

**Comment by ShippyG** [comment]
@S74nk0 Also speed is only 90 H/s cryptonight and before it was 150 H/s cryptonight.

**Comment by S74nk0** [comment]
@ShippyG the miner files are the same... if you have hidden windows make sure to shutdown all other instances of ccminer_cryptonight (you might be running multiple instances and it can be the reason for slower speeds).

**Comment by ShippyG** [comment]
@S74nk0 There was no duplications. I will let it run for 60 minutes and i will report results.

**Comment by N8Thrasher** [comment]
Patch dont work.
![image](https://cloud.githubusercontent.com/assets/24593637/22065976/be7e917a-dd9b-11e6-992a-561ea0d3c6c5.png)

**Comment by ShippyG** [comment]
@S74nk0 After running miner for about 40 minutes my system did crash for some reason. I started miner again and i will report you my results after 60 mins. I will also tell if my system crashes again.

**Comment by S74nk0** [comment]
@ShippyG @SanekXXX4 @N8Thrasher disregard the previous patch (I have deleted the post). 
https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.1 this release was re-updated. You can download the new NHM or replace with this [patch](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.4.1/NiceHashMiner_v1.7.4.x_patch.zip). Now it shouldn't strike warnings at first 0 accepted shares API call. If this still continues we will have to check the back end.

**Comment by braintm** [comment]
![1344](https://cloud.githubusercontent.com/assets/25203438/22070160/f8f96e1c-ddd5-11e6-8600-b9f7eb575ca6.jpg)
another bug
rx470

**Comment by N8Thrasher** [comment]
It appears again.
![image](https://cloud.githubusercontent.com/assets/24593637/22075395/e8b9a6de-ddbc-11e6-9a3b-bc5674fb6a32.png)

**Comment by KanoSet** [comment]
same happened with me but with algorithm equihash
gpu is sapphire r9 390

**Comment by Timoulis** [comment]
Same here with Daggerhashimoto and 2x RX470

**Comment by S74nk0** [comment]
This feature has been dropped. Please re-download the new current version it has been updated. https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.1.
Closing issue...
