### ISSUE TITLE
Too many rejected shares for Cryptonight NHM 1.7.4.0

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner-Archived#523]
Shares accepted: 151 rejected: 74 for Crytonight
50% shares rejected :-1: 

Windows 7 64 bit
NHM 1.7.4.0
Driver 17.1.1

What could be the reason ?

**Comment by S74nk0** [comment]
@nerdatwork What is your service location? US?

**Comment by snowcrawl** [comment]
I am encountering significant problems with the new Claymore Cryptonight miner, causing my computer to crash and reboot.   It appears that the 1.7.4.1 version is more stable on my system than the previous  1.7.4.0 
For the time being I am disabling Cryptonight for my AMD cards.

**Comment by nerdatwork** [comment]
@S74nk0 Its EU.

**Comment by snowcrawl** [comment]
I found updating my AMD driver has helped Cryptonight performance..  I am getting Claymore Cryptonight miner working now for the first time since the update.

**Comment by nerdatwork** [comment]
@snowcrawl Which version did you install ? As you can see I have the latest version installed

**Comment by snowcrawl** [comment]
I updated from 16.12.1   to 16.12.2.   It listed the 17.1.1 version as optional at this point on my Radeon control panel .

**Comment by snowcrawl** [comment]
Update.   It looks like I am not out of the woods yet.   Returned to my PC and realized that it had recovered from an unexpected  shut down.  Tried again with Cryptonight disabled.    Same result.   So for now I have gone back to using v.1.7.3.12

**Comment by nerdatwork** [comment]
@S74nk0 I tried all locations and result is same. I am getting 50% or more rejected shares. Have stopped Cryptonight and sticking with Ethereum for now.

**Comment by nerdatwork** [comment]
The latest version is mining with less hashrate for ethereum. Reverted back to 1.7.3.12.

**Comment by S74nk0** [comment]
We had issues on the backend with cryptonight . They should be resolved now.
