### ISSUE TITLE
Still having 0 shares warning on cryptonight on NHM 1.7.4.1

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#524]
Same issue even on 1.7.4.1

[https://github.com/nicehash/NiceHashMiner/issues/522](https://github.com/nicehash/NiceHashMiner/issues/522)

**Comment by S74nk0** [comment]
@N8Thrasher does the miner have a worker name assign to it? Also check if that worker is getting any accepted shares. Please reply

**Comment by S74nk0** [comment]
@N8Thrasher check if your worker is listed here:

https://www.nicehash.com/api?method=stats.provider.workers&addr=BTC_ADDR&algo=PROBLEMATIC_ALGO_ID

Change BTC_ADDR with yours and PROBLEMATIC_ALGO_ID with the [id](https://www.nicehash.com/?p=api). 22 = CryptoNight

**Comment by S74nk0** [comment]
@N8Thrasher also please report what is mining cryptonight (GPU/CPU version)?

**Comment by S74nk0** [comment]
Closing [duplicate](https://github.com/nicehash/NiceHashMiner/issues/522)
