### ISSUE TITLE
algorithem lyre2ra is reporting 0 shared accepte.  please disable this algorithem in setting and  report bug to suppor@.nicehash.com 

### ISSUE THREAD

**Issue by almoharebh** [nicehash/NiceHashMiner-Archived#526]
algorithem lyre2ra is reporting 0 shared accepte.  please disable this algorithem in setting and  report bug to suppor@.nicehash.com

**Comment by S74nk0** [comment]
@almoharebh Is this on CPU?

**Comment by almoharebh** [comment]
yes

**Comment by S74nk0** [comment]
This feature has been dropped. Please re-download the new current version it has been updated. https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.1.
Closing issue...
