### ISSUE TITLE
[log error] [default] [argument index out of range] with optiminer.

### ISSUE THREAD

**Issue by KanoSet** [nicehash/NiceHashMiner-Archived#527]
i'm totally new to this
but sometimes when i run gpu mining i get this message and the numbers in nicehash "usd\day" is stuck at 0 even tho the mining is still going
a pic to show better : http://puu.sh/traIo.png
also when it runs correctly that 6500+ number is usaully much lower
pic: http://puu.sh/trb6c.png

**Comment by Johann1982** [comment]
I am having the same issue with optiminer.

**Comment by Johann1982** [comment]
I think its a bug. I changed config.json back to "AMD_Equihash_3rdParty": 0

**Comment by S74nk0** [comment]
@KanoSet @Johann1982 if you could reproduce the issue and send the logs it would be easier to determine what is causing this issue. I thinks this is an issue on NHM parsing the API data from the miner, but this is just a guess.

**Comment by S74nk0** [comment]
The new [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.2) fixes this. 
Closing issue...
