### ISSUE TITLE
NiceHash Miner v1.7.4.1 Warning

### ISSUE THREAD

**Issue by JohPePe** [nicehash/NiceHashMiner-Archived#528]
I keep getting these Warning messages that are empty, what can one do to fix it?

/J
![2017-01-19](https://cloud.githubusercontent.com/assets/25219053/22097973/326fb928-de24-11e6-80e8-f5a69a0179c0.png)

**Comment by S74nk0** [comment]
You are probably missing the language package. Re download https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.1
