### ISSUE TITLE
Change opencl-platform in ethminer?

### ISSUE THREAD

**Issue by HadronicDiviner** [nicehash/NiceHashMiner-Archived#53]
Hello,

Is there an option to change the opencl-platform in the NiceHash miner?

I've been mining previously with ethminer and geth, and I needed to do this in order to use my rig.

Thanks!
Sean

**Comment by theLosers106** [comment]
Are you mining with AMD or nVidia GPU? If it is an AMD.. NiceHashMiner should automatically detect which platform it needs to run correctly..

**Comment by theLosers106** [comment]
I'll be closing this for now as there is no follow up for a while now..
