### ISSUE TITLE
0 cryptonight shares warnig on 1.7.4.1

### ISSUE THREAD

**Issue by ghostfaceuk** [nicehash/NiceHashMiner-Archived#530]
I am receiving the pop up window every so often telling me 0 shares for cryptonight and I should disable it in the miner.

This is being mined with the CPU.

I have checked on the both the miner and the stats page and they seem to show shares and a BTC a day rate.

if I go to https://www.nicehash.com/api?method=stats.provider.workers&addr=BTC_ADDR&algo=PROBLEMATIC_ALGO_ID I get this

{"result":{"addr":"129K64keaARnNL98ETMXZZm6Z5VaeDf8X2","workers":[["worker1",{"a":"0.1"},132,1,"15000",0]],"algo":22},"method":"stats.provider.workers"}

**Comment by S74nk0** [comment]
Hi @ghostfaceuk. This is a new feature that is not working well (it is a **BUG**). We have disabled this in the patched and standard download. NHM v1.7.4.1 has been updated to a later commit removing this **BUG**. Just re-download the whole package or just use the path to replace the current NHM. https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.1.
Closing issue...
