### ISSUE TITLE
Not valid BTC address!

### ISSUE THREAD

**Issue by navarrotarro** [nicehash/NiceHashMiner-Archived#531]
it says that when i click "check my stats online". i've reserched a bit and i found a post where it says it is because my wallet starts with a 3....but i'm new at this so i don't understand how to contact them to tell them that is a valid adddress. what should i do?
pd: is a bit go wallet

**Comment by S74nk0** [comment]
@navarrotarro please write to support@nicehash.com. Write your BTC address and describe your issue. 

**UPDATE:**
You can also write the address here, but also write to support@nicehash.com

**Comment by navarrotarro** [comment]
ohh thank you!
 my address is 
37F7pn19if7G4v34GiJpZgXxuTqaYbXnaz

**Comment by navarrotarro** [comment]
@S74nk0 do they take long to answer? :(

**Comment by S74nk0** [comment]
The validator has been fixed. Please reopen this if you are still having issues.
