### ISSUE TITLE
[FEATURE] restart nvidia DisplayDriver if it crashes

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#532]
Hi,

i have not been able to fully understand what exactly causes this issue, one of my rigs with 6 gtx 1070s somewhat crashes from time to time. At this point the miner force closes instantly as one of the 6 GPUs is not recognized anymore from the miner (still displayed in Device manager). A system restart fixes the problem, and it runs for another 3 days or so till it crashes again. I suspect a weak 5V line from the PSU, load is usually fine (max 1100W from a 1200W PSU)

i have not tested if it works, but im sure it will:
"nvidiaInspector -restartDisplayDriver" might be able to fix this problem without restarting the whole system (and it can be used from nicehashminer)

i will test this as soon as the rig crashes again, might this be possible to implement (using a filter for stdout to get the error message from ccminer and the like, and just executing the tool with the parameter)?

else i will have to find a way to detect the failed miner startup somehow and execute the cmdline

**Comment by felixbrucker** [comment]
edit: i have solved it with my home automation system (openhab2) and a simple rule to power cycle the rig after 15 minutes of low power draw (to allow for maintenance)

**Comment by S74nk0** [comment]
@felixbrucker the idea to power cycle the system is not bad. This will be considered.

**Comment by felixbrucker** [comment]
Actually the better approach would be the execution of this software (driver reset) as it doesnt lose that much time on rebooting and *should* work as well. Also it could and should be done directly from within the NHM at the exact time it happened. My solution is completely external to NHM and the whole system, and a powercycle certainly is not the best approach, but for my limited timeframe of operation of this rig (only the next few months till it gets hotter) it suffices.

**Comment by S74nk0** [comment]
@felixbrucker you are correct. We'll have to see how would this work in practice. For NVIDIA it would probably work fine. AMD on the other hand has proven to be very problematic and in that case the only way to workaround the driver hang is a power-cycle. We'll take it into account and test it when time allows it

**Comment by felixbrucker** [comment]
thanks

yes for amd im not sure

**Comment by kenshirothefist** [comment]
This idea of restarting device driver and detecting failed devices has now been added to our internal to-do. It is however planned for the far-future releases, so do not expect this to be implemented soon. Thank you for your feedback!
