### ISSUE TITLE
zcash 1.40

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#533]
?.  Details

**Comment by nerdatwork** [comment]
Could you use more syllables to help everybody reading your post understand what you are trying to say ?

**Comment by tmslacker** [comment]
What is this new miner option and what are the  benefits of using it?

**Comment by S74nk0** [comment]
@tmslacker This option allows you to use [OptiminerZcash](https://github.com/Optiminer/OptiminerZcash). Instructions are on the [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.1) page (you need to edit the configs file with a text editor)

**Comment by S74nk0** [comment]
[OptiminerZcash](https://github.com/Optiminer/OptiminerZcash) Is faster on some GPUs.

**Comment by tmslacker** [comment]
I have the 480, 980ti and 1080.  Any advantage?
