### ISSUE TITLE
Absent of ssl connection for cryptonight

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#536]
Claymore add an ssl connection for Cryptonight AMD GPU Miner in version 9.7 with only 2% fee.
Please, add an ssl connection for nicehash cryptonight pools.

**Comment by nerdatwork** [comment]
I second that also need a fix for 50% rejection rate on rx 480

**Comment by S74nk0** [comment]
We had issues on the backend with cryptonight . They should be resolved now. As for SSL I believe it will be included (I am not 100% sure).

**Comment by UnclWish** [comment]
Yesterday I try to connect through ssl to cryptonight.eu.nicehash.com:33355 and it works!
Today no connection to this port (((.
Will it work stable?

EDIT: I try again and connection established. Thanks for adding ssl for cryptonight.

**Comment by S74nk0** [comment]
[Added](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.4)
