### ISSUE TITLE
Dagger issue R9 380X 4GB Windows 7 x64

### ISSUE THREAD

**Issue by Treebeardz** [nicehash/NiceHashMiner-Archived#538]
I've tried the latest version and the patch and I get the same issue. I will benchmark Dagger get around 19 MH/s. Then after restarting nice hash Dagger disappears from the possible list. However not only Dagger is removed from the Algorithm list lbry, lyra2rev2, and neoscrypt are also removed from the list. Not sure why this is or how to resolve it.

Was this a driver issue? I updated to the latest AMD driver "Driver Packaging Version
16.50.2611-170113a-310468E". I can downgrade and report back if need, just wondering if this is a known issue.

**Comment by nerdatwork** [comment]
I too am using AMD and  only see cryptonight, dagger and equihash in the list. I think the unnecessary NON profitable algos are removed since you would be wasting time mining them hence they dont show up in the list.

**Comment by Treebeardz** [comment]
I just wanted to report back after looking through some other somewhat related issues but not the same behavior as mine it was suggested to down grade to driver 16.10.3. I have done that and all is working fine now it seems. 

Side Note: Overclocking with Afterburner does not seem to effect equihash at all.

**Comment by S74nk0** [comment]
@Treebeardz if you had algorithms disappear after driver upgrade this was due to miner being very unstable on 16.x (I am not sure right now the exact version). NeoScrypt and Lyra2REv2 should be missing from the list as these two algorithms were problematic.

**Comment by S74nk0** [comment]
new [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.2) is out that should also fix some Dagger issues related to ethminer. Close if this has answered your concerns.

**Comment by Treebeardz** [comment]
I replaced my AMD 380X with a GTX 980 I would test and confirm the new version resolved the issue however I am unable. All I can tell you is that using driver 16.10.3 seems to stop the issue.
