### ISSUE TITLE
Poor performance in the miner on your algorithm DagerHashimoto just 23-24 MH\s for AMD graphics cards (ATI) Radeon R9 Fury ASUS PCI-E

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#539]
Poor performance in the miner on your algorithm DagerHashimoto just 23-24 MH \ s for AMD graphics cards (ATI) Radeon R9 Fury ASUS PCI-E 4096Mb (STRIX-R9FURY-DC3-4G-GAMING) on the miner from Claymore produces 29-30 MH please add a miner from Claymore, or work better on her!
Drivers version: --- radeon-crimson-16.3.2

**Comment by nerdatwork** [comment]
I was thinking the exact thing. Need secure connection to get lower fees. NHM connects unsecured.

**Comment by Timoulis** [comment]
I don't think it has something to do with NHM. I use RX 470 from Sapphire ( Nitro + ) with 40+ MH.
Driver version is 16.11.3

**Comment by nerdatwork** [comment]
@Timoulis How do you get that many hashes ?

**Comment by Timoulis** [comment]
I don't do nothing. Nitros are factory overclocked with 1260 Mhz core clock. Maybe that is doing the trick.

**Comment by nerdatwork** [comment]
That is odd I got MSI Gaming X 8 gb Base Clock 1303, Memory at 2225 Mhz ....yet I am stuck at 24/25

**Comment by S74nk0** [comment]
@BARUCHER777 try using [v1.7.4.2](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.2) it uses sgminer by default. It should be more stable and faster. For the accurate miner benchmarking speeds set the benchmark times to be higher than the default or use precise speeds when benchmarking. Benchmarks on standard can report lower speeds but when mining the speeds should be the same as ethminer or faster.

**Comment by killmetohell** [comment]
I don't know i have 1.7.4.2 and shows poor performance on my as well my video card is RX 480 and i used have lot more better performance then had beforce unfortunly i don't know my old perm due i benchmarked due to i was wondering why wasn't doing well :P.

**Comment by Timoulis** [comment]
After installation of new version i have 23-24 mh/s too. Low mining is back again.

**Comment by BARUCHER777** [comment]
@S74nk0 
Thank You to respected, with the new version everything was better and now produces from 29 to 31, MH, but of course a long wait for these speeds!
At the miner by Claymore all of instantly the total rate of in just a a minute or two!

**Comment by killmetohell** [comment]
Sorry i think i might be putting what said in wrong topic my problem was my mining speed was 23603445 in my old benchmark looked my configs when down to 0.551 MH/s or 551100 if that helps i'm thinking putting new issue later.

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
