### ISSUE TITLE
only one cpu core working

### ISSUE THREAD

**Issue by nekajcasa** [nicehash/NiceHashMiner-Archived#540]
Hi, 
recently I have updated to latest version, I have noticed that only one CPU core is doing work (in last version) two cores were working... How do I set miner so that I will mine with all 4 cores?

**Comment by S74nk0** [comment]
@nekajcasa [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters) are the supported flags for available miners (in your case we are interested in **CPU** settings). For setting all threads (physical cores or virtual cores) use the **-t** flag and set it for the desired algorithm.
Image for illustration (Settings > tab **Devices/Algorithms**):
![all threads example](https://cloud.githubusercontent.com/assets/1517233/22194834/fe1177f6-e144-11e6-85e0-98dcf21de5d3.PNG)

In the image I am setting that cryptonight uses all 8 cores (**virtual cores** in my case)

I believe this answers your question. 
Closing issue... 
Reopen or just ask in this thread if I was unclear.
