### ISSUE TITLE
code":23,"message":"Shareabovetarget.

### ISSUE THREAD

**Issue by bobiksamara** [nicehash/NiceHashMiner-Archived#541]
Claymore's CryptoNote GPU Miner 
{"jsonrpc":"2.0","id":4,"error":{"code":23,"message":"Shareabovetarget."}}

msi amd hd 6870 TWIN FROZR
driver Catalyst 15.7.1

**Comment by bobiksamara** [comment]
Help please

**Comment by S74nk0** [comment]
try using new [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.2) with sgminer-gm (instructions on release page)

**Comment by bobiksamara** [comment]
it claymore

**Comment by S74nk0** [comment]
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.

**Comment by JBSpice** [comment]
Try the beta version of Crimson for the hd 5000 series and up, should work, think there is problems with the Catalyst 15.7.1 driver.
