### ISSUE TITLE
[Feature] Make it colorful

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner-Archived#542]
Why not make the share accepted text YELLOW and number of shares accepted GREEN and rejected share text RED. Would add more life to the whole mining experience.

**Comment by S74nk0** [comment]
@nerdatwork this will be considered (it is mostly a question if all miners can support this). There will be major UX changes to NHM in the near future so this might get in.

**Comment by felixbrucker** [comment]
not related to this issue but to your statement about UX change @S74nk0: is this related to the upcoming linux NHM?

**Comment by nicehashdev** [comment]
This is not feature for NHM, but feature for backend miners NHM is using. Closing.
