### ISSUE TITLE
Different divider between algo and hashrate

### ISSUE THREAD

**Issue by Singman33** [nicehash/NiceHashMiner-Archived#543]
Hi,
When using the API page (https://www.nicehash.com/api?method=simplemultialgo.info), I can get what Nicehash will pay for the algo, in BTC/GHash/Day. But if you write your hashrates and the result of what nicehash program is logging, you get some difference, not always related to units of hashrate. IE :

- Neoscrypt, hashrate in Mh, divider is 1000 (for converting Mh -> Gh)
- Lyra2rev2, hashrate in Mh, divider is 10000 (why ?)
- Decred, hashrate in Gh, divider is 100 (??)
- Equihash, hashare in H/s, divider is 1000000000

Can you provide a clear explanation for that divider ? it's not always related to hashrate units.

**Comment by S74nk0** [comment]
@Singman33 that API always returns GH/s. What NHM **MH/s** or **GH/s** is showing for different algorithms is just [cosmetic](https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Helpers.cs#L127) (NHM's UX is not that good it squeezes space, this will change) it doesn't have any affect with the program logic. Does this answer the question?

**Comment by Singman33** [comment]
I will test with your suggestion and report here.
