### ISSUE TITLE
AMD Driver Question

### ISSUE THREAD

**Issue by semisane** [nicehash/NiceHashMiner-Archived#546]
Has the latest AMD driver issue been resolved? I'm still running 16.11.1 and wanted to know if I can upgrade.

Anyone using anything newer with success running Dag or Equihash?

**Comment by CAVACO-PT** [comment]
nop  iv tested with 16.12.2 , still doesnt not submit shares ... still using 16.11.4 , dont bother to upgrade .. only if u use sgminer ... but even that for me gives less performance than ethminer ... #552

**Comment by kezdarkriser** [comment]
after nearly 2 months of these issues i've decided after testing that it's a ploy to make you use claymore 3rd party crapware

**Comment by semisane** [comment]
Are you having success with claymore with AMD products? I get a lot of rejected shares.

**Comment by kezdarkriser** [comment]
you will be stuck running those drivers forever , just give up already loads have

**Comment by S74nk0** [comment]
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
