### ISSUE TITLE
[Feature] Can we get Claymore's Ethereum Miner too?

### ISSUE THREAD

**Issue by DillonN** [nicehash/NiceHashMiner-Archived#547]
With all the third party miner support now I think it would be decent to have Claymore's eth miner in there as well. Especially helpful for those of us reliant on RDP who can't use sgminer, since Claymore is about 10-15% faster than ethminer. 

Even without the dual decred/eth feature it would still be a welcome addition.

**Comment by Fossius** [comment]
Yes, please add Claymore's Ethereum Miner

**Comment by S74nk0** [comment]
Added.
Closing...
