### ISSUE TITLE
sgminer-gm gives error when starting up cryptonight

### ISSUE THREAD

**Issue by dandrea2** [nicehash/NiceHashMiner-Archived#548]
sgminer-gm gives an error that only can be seen if benchmark values are entered for Cryptonight and it is set not to hide windows.  Benchmark just sits there with the GPU doing nothing for a while, with sgminer.exe left in task manager, even after stopping the benchmark and exiting NiceHashMiner.

The error appears to be a OpenCL compile error, or series of them.  Here's a copy of what got put in the console when it started:
`"C:\Users\xxx\AppData\Local\Temp\jh.cl", line 110: error: function call is not
          allowed in a constant expression
    C64e(0x0a2c813937aa7850), C64e(0x3f1abfd2410091d3),
    ^

"C:\Users\xxx\AppData\Local\Temp\jh.cl", line 110: error: function call is not
          allowed in a constant expression
    C64e(0x0a2c813937aa7850), C64e(0x3f1abfd2410091d3),
                              ^

"C:\Users\xxx\AppData\Local\Temp\jh.cl", line 111: error: function call is not
          allowed in a constant ex[19:24:43] Failed to init GPU thread 0, disabling device 0
[19:24:43] Restarting the GPU from the menu will not fix this.
[19:24:43] Re-check your configuration and try restarting.
Press enter to continue:`

I opened the jh.cl file in the sgminer-gm folder, and lines 110 and 111 are not at all like what it's complaining about.

3rd-party miners work fine

GPU is MSI Radeon HD 7770
AMD 16.11.2 driver

**Comment by dandrea2** [comment]
So, any ideas?  I'd hoped someone might have commented by now, maybe with some idea to try and get this to work.

If it's driver related, I can't switch versions.  Other versions cause stability issues for some of the games I play on this same PC (like 2016 version of DOOM), so I need to stick with this one since it was the most stable for the games.

**Comment by S74nk0** [comment]
@dandrea2 this is probably due to the default optimizations used (they might be a little too much for your GPU).
This is the default: **"--rawintensity 512 -w 4 -g 2"** try reducing the values in half (some tweaking trial and error would be needed here), best to remove all flags and try without optimization flags to see if it works and then you can experiment with values. Report back what settings work for you.

**Comment by dandrea2** [comment]
I'm pretty sure I tried at least once with optimizations disabled and also with the additional parameters field blank.  Thing is I've seen these kinds of errors before on other programs not for mining (like the distributed.net client).  Looks  to me like the error happened while sgminer and/or the GPU driver was trying to compile the CL code to a binary and never completed it to even run on the GPU.  When I looked in the sgminer-gm folder, I don't see any BIN files, either before or after running it.

I can try with the suggestion (entering and cutting in half the values), but I don't think it will work to help the CL code compile in the driver.  Right now I'm at work, so it will have to wait til I get home tonight to try it.

**Comment by dandrea2** [comment]
As I thought, made no difference.  Put "--rawintensity 256 -w 2 -g 1" in the extra launch parameters for Cryptonight on the GPU, but it does exactly the same thing.

Still think this is some kind of OpenCL compile error related to the driver, maybe.

**Comment by AngryOverlord** [comment]
I'm getting the same exact error.

**Comment by dandrea2** [comment]
Still get the same error on HNM 1.7.4.3

I'll download and install AMD 16.11.5 driver and try that.

**Comment by dandrea2** [comment]
FYI, even on NHM 1.7.4.4 and AMD 16.11.5 driver, it still does the same exact thing as in the first note.

**Comment by kenshirothefist** [comment]
Since this is a sgminer-gm issue and not directly related to NiceHash Miner, we welcome you to discuss these kind of issues here: https://github.com/nicehash/sgminer-gm/issues
