### ISSUE TITLE
"Hide mining windows" should work for benchmark as well as regular mining

### ISSUE THREAD

**Issue by dandrea2** [nicehash/NiceHashMiner-Archived#549]
After submitting the other issue, I realized it would have been easier to spot if benchmarking in NHM respected the "Hide mining windows" setting.  Right now, it doesn't matter what it's set to, it always hides the windows when benchmarking.  It would be nice if the windows would show for benchmarking when the setting is not checked so that finding errors like my earlier ticket would be easier.

**Comment by nerdatwork** [comment]
As I remember hiding windows was not working for zcash since there were reports of people using NHM on machines they were not authorized to use. This way the owner of the pc knows what was happening.

**Comment by dandrea2** [comment]
I could understand that reasoning, except it's actually been like this since before the third-party miners were added.  Just never had a reason to report it till now.

**Comment by nerdatwork** [comment]
https://github.com/nicehash/NiceHashMiner/issues/367#issuecomment-262816634

Hope this helps

**Comment by dandrea2** [comment]
I see this was linked to that older issue, but I'm not sure it should have been.

The issue I'm reporting is (and I'm not using the EQM miner anyway) that benchmark totally ignores the setting and hides the windows anyway for the miners I'm using.  Even the CPU miner windows get hidden when benchmarking the standard non-third party algos, regardless of the "Hide miner windows" setting.  If it had shown the windows when the setting is not checked, I could have found the error I reported on the first benchmark run, not a half hour later after fiddling with settings trying to find out why it kept hanging on the cryptonight GPU benchmark.

**Comment by nicehashdev** [comment]
We will add logging to benchmarking in next release.
