### ISSUE TITLE
NHM stats not matching web stats

### ISSUE THREAD

**Issue by semisane** [nicehash/NiceHashMiner-Archived#551]
Have been mining dagger consistently at 102+MH/s according to NHM.

Web interface is consistenly at 75-85MH/s

Win10
4x RX480 8GB
16.11.1

**Comment by nerdatwork** [comment]
Speed and amount are not matching since a few weeks :(

**Comment by semisane** [comment]
So far my best solution has been doing a clean install of NHM, disabling all sgminer miners, and doing benchmarks for one card and then copying them across.
Running 16.11..4

**Comment by UnclWish** [comment]
You must remember that NHM shows actual mining speed reported by current miner(s). But on statistics on site it shows only recieved mining speed reduced on 2% - the fee of the nicehash pool.

**Comment by semisane** [comment]
I'm seeing - 28% difference

**Comment by UnclWish** [comment]
I understand. This looking as 26% goes to not your address...

**Comment by semisane** [comment]
K

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
