### ISSUE TITLE
Various issues with 1.7.4.2 and SGMINER

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner-Archived#552]
Hello all , since i update to new version a few issues have been up since tried to use sgmine : 

Varios computers and configurations , from  290x , 390x and 480 cards , have showed low speed when using sgminer , it cant reach the benchmarked speeeds that it has bencharmarked the card with , iv tried this with diferent drivers problem still the same , but when i revert back to ethminer speeds are normal again , so problem seems to bee with sgminer , 

The other problem is the same as the other issue bellow #550  , when doing a clean install , or trying to benchmark with sgminer , the computer and niceminer crashes , sometimes gives bluescreen , this happen with diferent computers with 480 cards , the only way i can benchmark after a clean install is to revert back to ethminer so it does the benchmark instead of sgminer ...

Have been using in all computers and cards the old drivers 16.11.4 , because the new ones still dont submit shares with ehtminer , but tried with sgminer and the new drivers work ... but the speed of sgminer is bellow always what the benchmarks say the card can reach ... so prefer to use eth miner to have more performance and $

if you need another thing to help please let me know 

thanks

**Comment by allacc** [comment]
Me too :( 
Same here ....

**Comment by semisane** [comment]
Was having the same problems with sgminer. Thanks for the workaround so I'm not losing money.
Appreciate it!

**Comment by semisane** [comment]
So far my best solution has been doing a clean install of NHM, disabling all sgminer miners, and doing benchmarks for one card and then copying them across.
Running 16.11..4

**Comment by CAVACO-PT** [comment]
yes ... thats is what i did , clean install on all , disabled sgminer , and did benchmarks on the cards

**Comment by snowcrawl** [comment]
Just noticed this problem now since I haven't done any Ethereum mining in a while.  I was having issues just starting a few days ago of my computer freezing randomly while I was away, so losing many hours of mining this week.   But I believe the main problem was with an older Radeon HD7770 card that I was running off the same power supply cable as another NVIDIA card.   After removing that card from the rig, no more bluescreen/reboot problems (so far).  The Nicehash miner console was indicating that my 480 was running 23 MH/s, meanwhile the Check My Stats page was only indicating that I was getting about 5 MH/s.   So I have disabled Dagger (sgminer) once again.

**Comment by Eyedol-X** [comment]
Same issue here with RX480s, either crashes or horrible speeds. I went back to 1.7.4.1 and disabled eth for now

I really wish they would just add the Claymore Eth miner as a 3rd party option

**Comment by Pizzaguy1234** [comment]
Check virtual memory in the system applet is not system managed and has the required 8GB hard set and only mine with the Equihash algo worked for me. Something is seriously wrong with AMD and NHM for the other algo's.  My crashes stopped and my speed went back up.

**Comment by Eyedol-X** [comment]
Still having issues in 1.7.4.4 even with 16.11.5 Drivers. Been sitting on Cryptonight Sgminer benchmark now for 10 minutes...

Edit; After 20 minutes, I gave up waiting. So much for 1.7.4.4....

![image](https://cloud.githubusercontent.com/assets/22627805/22629703/eaf4f906-ebb0-11e6-8330-dad8c648d4cc.png)

**Comment by snowcrawl** [comment]
I had to skip that benchmark.

**Comment by CreamyG31337** [comment]
I was wondering when the sgminer cryptonight was gonna be fixed for my 470, but it looks like you guys haven't even posted a log?? This one is from the benchmark. There's 8MB of OpenCL compile errors, I just left the first few as I doubt the other 8000 errors matter at that point. This is using latest AMD drivers, I don't really feel like messing with drivers right now if that's the solution.

[dump.txt](https://github.com/nicehash/NiceHashMiner/files/775743/dump.txt)

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
