### ISSUE TITLE
NeoScript and Lyra2REv2 for AMD graphics cards!?!?!

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#554]
Algorithms do not pass the benchmark, and do not work !!!
Dear developers when you finally repair the algorithms: NeoScript and Lyra2REv2 for AMD graphics cards!?!?!
Алгоритмы не проходят бенчмарк, и не работают!!!
Уважаемые разработчики когда же вы наконец то почините алгоритмы: НеоСкрипт и  Lyra2REv2 для видеокарт АМД!?!?!

**Comment by Singman33** [comment]
You can make them working by fine tuning parameters.  To do that, you should launch the miner in command line prompt and see the error.

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
