### ISSUE TITLE
Extra Launch Parameters doesn't work with Claymore's Cryptonight miner

### ISSUE THREAD

**Issue by Fossius** [nicehash/NiceHashMiner-Archived#555]
tried to set -h 512, but no result..

**Comment by S74nk0** [comment]
[fixed](https://github.com/nicehash/NiceHashMiner/commit/e4d012a5bdb5ba3a2577e57a5ee5df3f30b9ec31). New version will have this included.

**Comment by S74nk0** [comment]
New release includes fix...
Closing...
