### ISSUE TITLE
Claymore Cryptonight w/ RX 470

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#557]
I'm receiving a lot of new jobs but not finding many shares. Is this an issue or to be expected?

**Comment by S74nk0** [comment]
You can try changing the service location. But frequent switching shouldn't be common.

This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
