### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#558]
I was wondering If you could add a select all/select none options to the benchmark window in both these parts.  Simply uncheck all devices and/or uncheck all algorithm.  The second one is more important for me.  I remote into all my system from a smart phone and when I change something and want re-bench.  It a big pain unchecking everything I don't want to test.

**Comment by S74nk0** [comment]
@tmslacker  this can be done for algorithms listview with right click. 
![disable all example](https://cloud.githubusercontent.com/assets/1517233/22388769/8c52ecfc-e4e2-11e6-8e80-04dcf77456a1.jpg)
