### ISSUE TITLE
[FEATURE] [QUESTION] websocket push on significant profitability change

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#559]
afaik right now NHM as well as all other services using nicehash query the api every X minutes to get the latest stats and choose the correct algo

This also is a question: does a single websocket (eg) connection per miner add more load on the api servers as a http call every 1 minute, or every 30 sec etc?

if its less load it could be used to push significant changes to the miner and swap immediately (or swap back immediately when the high priced order gets removed after like 20 sec).
it could be used to reduce load as well as lowering the switching time.

What do you think?

**Comment by Singman33** [comment]
If you are polling the server every minute (or worse, every 30 seconds) then you missed something in the API docs. Read it carefully.

**Comment by felixbrucker** [comment]
I just reread them, but i cant seem to find the passage you are referring to, care to share?

**Comment by nicehashdev** [comment]
We may solve this issue in near future; but currently, even our internal backend has 1 minute interval, so doing queries more often than 1 minute gives you no benefit. Closing this.

**Comment by felixbrucker** [comment]
well worst case is i just checked it before the api got internally updated, best case is i just checked it after it got updated, so my external interval does change matters, but also adds load

will watch this (hope you post updates here)

i use my own "proxy" for your api so i only call it once every x minutes/seconds, every device (besides NHM) just checks the proxy to get stats, so no exponential overhead in reducing the interval
