### ISSUE TITLE
 Error -4: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel) on X11

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#56]
This bug is persistent on 1.2.3.2 also (not sure about previous versions):

specs: 
1x amd 7970
1x amd 290x
amd driver 16.1
windows 7 x64

the error happens on the 290x, the 7970 is hashing fine

i just recently added this 290x to this rig, previously it was the only card in another pc and hashing X11 was fine, no problems whatsoever, so i guess its related to two different cards in one rig (while a 7870 and a 7970 in another rig do fine on X11).

cheers

**Comment by felixbrucker** [comment]
to give a short update: i was able to workaround this by setting xintensity to 320 instead of 640, so this might be useful for dev's

**Comment by theLosers106** [comment]
could you run it with the default values but with only 290x or 7970 selected.. might be one of those that is causing it.. thanks for the feedback.. (:

**Comment by felixbrucker** [comment]
Tried that already, no success, the 7970 works fine, the 290x gives the enqueue error

**Comment by felixbrucker** [comment]
short update: due to a new cooler the 7970 was temporarily not installed, and the single 290x worked fine with xi 640, so having those two inserted somehow gives the error

**Comment by theLosers106** [comment]
How much RAM do you have? Some have this problem and increasing the amount of RAM or Pagefile solves it.. mind giving it a try?

**Comment by felixbrucker** [comment]
i had 2GB, already ordered 4GB as the ethereum miner started to crash windows with the increasing dag :D 
will report back in a few days (maybe even just after the weekend)

**Comment by felixbrucker** [comment]
works fine with 4gb
