### ISSUE TITLE
[Nvidia GTX1070] issue with video driver nvlddmkm

### ISSUE THREAD

**Issue by Skymax7** [nicehash/NiceHashMiner-Archived#560]
Sometimes driver nvlddmkm crashed and has been recovered, sometimes card stuck and the program looping with start/end mining window. I think this happen when change algo.

**Comment by Johann1982** [comment]
What O/S are you running? Please supply more specs.

**Comment by Skymax7** [comment]
Win7 64bit - drivers ver. 378.49 (same crash with ver. 376.33)

**Comment by snowcrawl** [comment]
I'm not sure what it is like now, but a couple months ago I upgraded from Win7 to Windows 10 and found Nicehash miner ran better afterwards.

**Comment by Johann1982** [comment]
What Antivirus are you using?

**Comment by Skymax7** [comment]
nothing, light OS/machine only for mining

**Comment by Skymax7** [comment]
o well, I see when driver video crash...  exactly when sw change algo: previous dos window "stuck" and the nicehash try to open next dos session with other algo but... crash also nicehash sw with a looping of open/close dos window session...  I solve this with reset of cards with nvidia inspector and restart nicehash sw.

**Comment by Skymax7** [comment]
In system log I get these errors when driver video crash..  
Graphics Exception: ESR 0x404600=0x80000001
Graphics Exception:  EXTRA_INLINE_DATA

**Comment by nicehashdev** [comment]
Make sure your card isn't overclocked too much. Crashing drivers will always have some negative effects on other applications. Closing.

**Comment by Skymax7** [comment]
well, my cards aren't overclocked, these working on normal clock and normal burst. When I use ccminer only never crash, however I change time of change algo and it seems more stable... now happen so less than before.
