### ISSUE TITLE
AMD 470 vs 480 Ether SGminer problem

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#561]
So i have 2 asus 470 4gb and 2 Nitro+ 480 4gb cards. Windows 10 latest NHM and latest amd drivers as suggested by ZEC miner for optimal performance. Here is my problem:

I can benchmark ehter on 480 no problem, however 470 just crashes. With 16.11.4 AMD drivers both crash during benchmark. Why is that? I also have one 7950 and that cannot bench mark ether at all.

When i mine ether through sgminer with 480s it displays a speed of about 21mhs per card however only about 19 mhs per card is registering... why is that? 

Let me know of any extra info is required.

**Comment by Pizzaguy1234** [comment]
Double check virtual mem has to be 8Gb or greater on multiple Gpu's. I have rx470's and can only run equihash. Just waiting for the next version of NHM.

**Comment by undefy** [comment]
Maybe a silly question but how do I check vmem and can I modify it? Dxdiag?

**Comment by CAVACO-PT** [comment]
Already reported the crash and poor performance with sg miner in #552 , 

Disable sgminer and switch to eth miner , and dont use the latest drivers , they not compatible still with NHM , use 16.11.4 , but with sgminer off .. eht miner will do benchmark just fine , and work with DH

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
