### ISSUE TITLE
PLEASE ADD miner for PASCALCOIN

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#563]
Dear developers, please add a miner for more profit coins PASCAL !!

**Comment by blue-yu** [comment]
I see some good profit with this coin. Please add it...

**Comment by Eyedol-X** [comment]
This would be really cool to see but I suspect someone out there is going to have to create a 3rd party pascal miner before this is possible.

**Comment by felixbrucker** [comment]
additionally pools with stratum support (suprnova) will have to emerge too

**Comment by UnclWish** [comment]
Here is miner for PascalCoin: https://bitcointalk.org/index.php?topic=1583719.msg17574340#msg17574340

**Comment by blue-yu** [comment]
First Pascal pool: https://pasc.nanopool.org/

**Comment by felixbrucker** [comment]
@UnclWish thats the solo mining miner for the wallet, not at all stratum compatible

@blue-yu thats a custom pool with a custom protocol based on the rpc miner for the wallet which has been modified, no way this can be used through nicehash as of now

you can however mine it directly on the pool/wallet with your rigs

**Comment by blue-yu** [comment]
But Nicehash can do the same thing as nanopool did. Am i right?

**Comment by felixbrucker** [comment]
@blue-yu nicehash is not a pool, its a proxy

nicehash connects to *real* pool via stratum and you connect via stratum to nicehash, buyer and seller exchange BTC for your shares submitted to nicehash (which are getting redirected to the pool)

nicehash once had a real pool (zcash) but it died quickly, i dont think they will operate another one soon

on the other hand suprnova pool will soon be ready (tm), and its very likely it will support stratum at some point
if this happens nicehash can "easily" implement a pasc stratum proxy and you will be able to sell and buy pasc hashing power through nicehash

**Comment by blue-yu** [comment]
Thanks for the explaining...

**Comment by Singman33** [comment]
BTW, Pascalcoin is an ephemeral hype, mostly a coin for speculation on an exchange. Let's wait a week or two and let's see what profit this coin could bring (ie, my own opinion, less than ETH or ZEC).

**Comment by felixbrucker** [comment]
there it happend: https://pasc.suprnova.cc

**Comment by BARUCHER777** [comment]
Dear developers to quickly add Mining for Pascal coins already using modified miners in some pools, with the option of using your code and third-party!

**Comment by AngryOverlord** [comment]
Looks like NiceHash is adding Pascal algo to their sgminer, can probably expect it to be added sometime soon:

https://github.com/nicehash/sgminer/commit/fb181f5e8803c7e5c7894814daf4e5cc04f46508

**Comment by S74nk0** [comment]
[Added](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.4).
