### ISSUE TITLE
RX 480 - White or Orange Screen Problem

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#564]
I have a new RX 480 8GB. Just installed newest drivers (17.1.1) and downloaded newest version of Nicehash. I benchmarked Crypto and Equihash. They all worked execpt for Daggerhash. When I benchmarked Dagger, the screen goes white or orange, nothing to do but restart the PC.

I unchecked Daggerhash and went with the rest. When I started mining, after a few minutes, the screen will go white or orange. The two algorithims used are Cryyptohash and Equihash. I am only mining with my GPU, no CPU involved.

**Comment by BARUCHER777** [comment]
Probably at you very powerful overclocking or malfunction video RAM!

**Comment by 192uijo** [comment]
Well I didn't overclock the video card at all.

**Comment by BARUCHER777** [comment]
It means try to run testing is video memory probably the beaten you have! Benchmarks try! MSI AFTERBURNER OR 3D MARK! .... check whether present artifacts are!

**Comment by 192uijo** [comment]
Ok, I'll try 3D Mark

**Comment by 192uijo** [comment]
Well I already played a few games. I found no artifacts at all and everything was stable.

**Comment by 192uijo** [comment]
Anything else?

**Comment by nerdatwork** [comment]
@192uijo Use driver version 16.9.xx or 16.11.xx and try to mine. Remember to have a clean install of drivers by using the "amdcleanuputility.exe" utility. You can google it.

**Comment by 192uijo** [comment]
@nerdatwork I've heard somewhere else that I needed 16.9 or .11, but I only saw 16.12 unless this is it: http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-Edition-16.11.5-Release-Notes.aspx

Unfortunately, I returned the card this morning and planned on getting another one ordered instead thinking that the constant crashing in most games and regular usage was a big problem. I forgot about trying different drivers actually... oops..

I was going to get R9 390 (https://www.newegg.com/Product/Product.aspx?Item=N82E16814131672&cm_re=r9_390-_-14-131-672-_-Product) this time unless you'd like to stop me and suggest something else (sub $200).

**Comment by S74nk0** [comment]
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
