### ISSUE TITLE
Nicehash EQM Zcash frequently reporting zero shares for periods of time

### ISSUE THREAD

**Issue by snowcrawl** [nicehash/NiceHashMiner-Archived#565]
I have noticed this several times today.   When my GTX 1060 GPUs switch to EQM they sometimes are showing no shares accepted for a certain period of time.   It is not constant, only shows up occasionally.  
![screen shot 01-28-17 at 06 39 pm](https://cloud.githubusercontent.com/assets/22260316/22400687/ff0a42ca-e589-11e6-9702-c3eabcfd7cde.PNG)

**Comment by magnoman** [comment]
I'm having the same issue with my rigs.  I've got a blend of a PC with a GTX 1080, a mixed 1070 and 1060 rig and a rig with just 1060.  All 3 of them are having the same issue.  It doesn't seem to matter what service location I try.  USA or Europe.  When switching from a different algorithm to EQM many times it can go minutes before it receives a job.  Looking at the job board there are plenty to be had so there's no job shortage.

![eqm_no_job_issue](https://cloud.githubusercontent.com/assets/25410005/22400986/be34275e-e591-11e6-8eec-daf1f2ee5c82.png)

**Comment by snowcrawl** [comment]
This has been the first week that I've been having any significant switching of algorithms, also since I have finally gotten around to doing benchmarks on all of the different algorithms on all devices starting with the release of v.1.7.4.2.  So the profit switching process is being put to the test a little more than in the past, whereas it tended to stick with equihash all of the time previously.

**Comment by Meteorite777** [comment]
Did you ever have trouble benchmarking with multiple cards? Since adding a 1060 I can't get anything other than equihash to benchmark on the 980Ti.

**Comment by snowcrawl** [comment]
I did notice that there are now fewer benchmarking options for AMD Radeon 380.   Dagger is no longer listed.

**Comment by nicehashdev** [comment]
This issue should have been fixed.
