### ISSUE TITLE
Daggerhash with SGminer disabled does not show up on web interface.

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#566]
I was having issues when benchmarking daggerhash. After disabling sgminer it managed to finish benchmarking. It is currently mining, but it is not showing any info on the web interface. If I switch it to equihash it shows up.

**Comment by nerdatwork** [comment]
Is the miner showing you shares for dagger ?

**Comment by Johann1982** [comment]
Yes, on nhm it shows shares, running at 80mh/s

**Comment by nerdatwork** [comment]
I too face issue with mismatch with hashrate on miner Vs on the web but as long as payments match I think we are good. There are delays from what I last read in one of the replies.

**Comment by Johann1982** [comment]
It isn't showing anything on the web. 0 on daggerhash. I let it run for 30mins just to make sure.

**Comment by nerdatwork** [comment]
Do the BTC and USD amount match on web ?

**Comment by Johann1982** [comment]
Yes, but it isn't increasing from mining daggerhash. Only when switching to equihash

**Comment by CAVACO-PT** [comment]
what drivers do u have .. 16.12 do not submit shares ... if you have them downgrade to 16.11.5

**Comment by Johann1982** [comment]
Will 16.11.5 work on win 10?

**Comment by CAVACO-PT** [comment]
yes it will i have machines runing with windows 10

**Comment by CAVACO-PT** [comment]
the problem is that the 16.12 drivers i could not roll them back properly ... have a lot of problems i had to reinstall the machine to properly take them out ... if you cant rollback u know what i have to do ...

**Comment by Johann1982** [comment]
Thanks, I will see if I can roll back. Will update once I have done so

**Comment by Johann1982** [comment]
Seems to be working after clean install of NHM and 16.11.5 drivers. Thanks!
