### ISSUE TITLE
bug: Stuck on "Checking AMD OpenCL GPUs"

### ISSUE THREAD

**Issue by ark02** [nicehash/NiceHashMiner-Archived#569]
Latest release works on system with 8 GPUs 
switched to system with 16GPUs, all NVIDIA. Program freezes on loading, "Checking AMD OpenCL GPUs" 

Tried reverting versions, 16GPU works fine on 1.7.2.0. Could not get it to work for anything after that. Any ideas?

**Comment by Johann1982** [comment]
What system are you running that supports 16GPU's? Do you use PCI-E cluster?

**Comment by ark02** [comment]
It's an amazon aws instance. Tested still happening on 1.7.4.3
Log:
[2017-01-30 15:27:37] [INFO] [NICEHASH] Starting up NiceHashMiner v1.7.4.3
[2017-01-30 15:27:37] [INFO] [NICEHASH] No config file found. Running NiceHash Miner for the first time. Choosing a default language.
[2017-01-30 15:27:37] [INFO] [NICEHASH] Found language: English
[2017-01-30 15:27:37] [INFO] [NICEHASH] Found language: Русский
[2017-01-30 15:27:39] [INFO] [NICEHASH] Selected language: English
[2017-01-30 15:27:39] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2017-01-30 15:27:39] [INFO] [NICEHASH] Total RAM: 749567MB
[2017-01-30 15:27:39] [INFO] [NICEHASH] Page File Size: 3840MB
[2017-01-30 15:27:39] [INFO] [NICEHASH] Balance get
[2017-01-30 15:27:41] [INFO] [ComputeDeviceManager.Query] 
QueryVideoControllers: 
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&78
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&80
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&88
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&90
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&98
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&A0
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&A8
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&B0
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&B8
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&C0
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&C8
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&D0
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&D8
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&E0
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&E8
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name NVIDIA Tesla K80
		Description NVIDIA Tesla K80
		PNPDeviceID PCI\VEN_10DE&DEV_102D&SUBSYS_106C10DE&REV_A1\3&267A616A&1&F0
		DriverVersion 21.21.13.7633
		Status OK
		InfSection Section044
		AdapterRAM 0
	Win32_VideoController detected:
		Name Microsoft Basic Display Adapter
		Description Microsoft Basic Display Adapter
		PNPDeviceID PCI\VEN_1013&DEV_00B8&SUBSYS_00015853&REV_00\3&267A616A&1&10
		DriverVersion 10.0.14393.0
		Status OK
		InfSection MSBDA
		AdapterRAM 0

[2017-01-30 15:27:41] [INFO] [ComputeDeviceManager.Query] QueryCPUs START
[2017-01-30 15:27:41] [INFO] [ComputeDeviceManager.Query] QueryCPUs END
[2017-01-30 15:27:41] [INFO] [ComputeDeviceManager.Query] QueryCudaDevices START
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] 
CudaDevicesDetection:
	ADDED device:
		ID: 0
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-f07c82f3-9f45-181c-e3cf-816eb593927e
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 1
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-bed15819-7d77-6034-06cc-96a9897b54bc
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 2
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-85084655-4466-7a94-ba4a-948991297f33
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 3
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-6b8377a5-21c7-b263-5e77-ee9795fe15d1
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 4
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-77b4c2e9-de0a-d3b6-46ec-28fe67a38352
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 5
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-3d020386-59a2-b17f-aca2-4be5152f7d26
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 6
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-0de51d81-2a3a-9e90-37a2-f914f17fd25c
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 7
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-3b46392d-5782-9c87-b081-f634a531f281
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 8
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-79cbf718-89ea-38f3-9956-a8ca6afff2b9
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 9
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-5f0f62f6-9ca0-d399-8fa1-e7f23a291f85
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 10
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-5eb46554-edcc-605c-bfd8-2acbe45abe73
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 11
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-c1d672a7-8444-7a6e-0cdb-6035d25aba45
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 12
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-83016ffe-e588-4f2c-65bb-c640e66666e1
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 13
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-c429fbb6-4fa0-da66-5042-fa1a7ce0f539
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 14
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-97503f75-be5c-16e3-452f-0474f1fccd86
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES
	ADDED device:
		ID: 15
		NAME: NVIDIA Tesla K80
		VENDOR: NVIDIA
		UUID: GPU-95214887-472e-740d-fd4e-17889990c7cf
		SM: 3.7
		MEMORY: 12003115008
		ETHEREUM: YES

[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] QueryCudaDevices END
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] QueryOpenCLDevices START
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] 
AMDOpenCLDeviceDetection found devices success:
	Found devices for platform: NVIDIA CUDA
		Device:
			Device ID 0
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 1
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 2
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 3
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 4
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 5
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 6
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 7
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 8
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 9
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 10
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 11
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 12
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 13
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 14
			Device NAME Tesla K80
			Device TYPE GPU
		Device:
			Device ID 15
			Device NAME Tesla K80
			Device TYPE GPU

[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] QueryOpenCLDevices END
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] QueryAMD START
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): NVIDIA Tesla K80 (21.21.13.7633)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): Microsoft Basic Display Adapter (10.0.14393.0)
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] QueryAMD END
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] Cuda NVIDIA/CUDA device count GOOD
[2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] AMD GPU device count GOOD


On windows server 2016
was able to recreate on fresh install, after installing latest NVIDIA drivers

**Comment by ark02** [comment]
It seems to be a problem with whatever comes after the OpenCL device detection. When I set `"DisableDetectionAMD": true,` it gets stuck on "Skipping AMD OpenCL Device check"

**Comment by S74nk0** [comment]
@ark02 

>  it gets stuck on "Skipping AMD OpenCL Device check"

This seems to me to be related to something else than AMD detection... 

> [2017-01-30 15:27:44] [INFO] [ComputeDeviceManager.Query] AMD GPU device count GOOD

After this line there is nothing else logged?

**Comment by Johann1982** [comment]
@ark02 What kind of speed did you get on those K80's? Are they worth using for mining?

**Comment by S74nk0** [comment]
@ark02  Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

**Comment by vinsilsim** [comment]
@S74nk0 this release work with Tesla K80 ?

**Comment by S74nk0** [comment]
@vinsilsim non gaming GPUs aren't officially supported. They might work but if the drivers do not support CUDA 8 than miners that require CUDA 8 will not work properly.

**Comment by vinsilsim** [comment]
@S74nk0 I'm with 8 tesla k80 and I want to mine with them, any idea how to do it?

**Comment by S74nk0** [comment]
@vinsilsim You can try [v1.6.1.4](https://github.com/nicehash/NiceHashMiner/releases/tag/1.6.1.4) (old version). Versions from v1.7.x.x can only support NVIDIA GPUs with **Driver Version 362.61** (minimal driver version).

**Comment by Incarnation** [comment]
I have this issues, anyone able to solve it?

**Comment by batishchevv** [comment]
I have the same issue. Using NiceHashMinerLegacy 1.8.2.0

When i start rig with 11 NVidia GPU - it starts and works fine. But when i add one more 12 GPU. No matter which one - loading stuck on "Skipping AMD OpenCL Device check".

I think that the problem is on step "virtual memory size", because there is no this line in log file.

I have set 60 Gb Virtual memory. Is it not enough?

**Comment by SicnessPrime** [comment]
I found a fix try to locate your Nvidia install folder usually at C:\Program Files\NVIDIA Corporation. Then look for a folder named NVSMI then move that folder or rename it. Try to run Nicehash Legacy again.

**Comment by Incarnation** [comment]
@SicnessPrime move that folder to where? or what should I rename the folder to? thanks

**Comment by batishchevv** [comment]
Yes it helps! Thanks. I've just removed NVSMI folder form C:\Program Files\NVIDIA Corporation

PS How you could get this fix?

**Comment by catapara89** [comment]
@SicnessPrime  

I have a system with 13 gpu and I had this problem with Nicehash too. I rename the folder and now it's working. 
How did you manage to find such a fix?? Big up!

**Comment by kuanos1** [comment]
Thank you for the help! very helpful!
