### ISSUE TITLE
Win32/Pellate.A!cl 

### ISSUE THREAD

**Issue by azizhamad04** [nicehash/NiceHashMiner-Archived#571]
Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:C:\Users\my computer\Downloads\NiceHashMiner_v1.7.4.3\NiceHashMiner_v1.7.4.3\bin_3rdparty\claymore_cryptonight\NsGpuCNMiner.exe

**Comment by slangza** [comment]
Make an exclusion for that folder, and restore the file from your antivirus vault/quarantine
