### ISSUE TITLE
RX 480 8GB or 4GB? 

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#572]
I was looking at two Sapphire GPUs on Newegg after returning my current 480. I originally planned on the 8GB variant but then I thought about the 4GB one. I'm not sure how much of a difference will there be, but I've heard that the 480 4GB can perform the same with overclocking memory, but I don't plan on overclocking since I really don't want to increase power draw (unless it's not a large increase).

Sapphire 480 8GB: $230 USD right now on Newegg (sale, probably not going to last any longer.)
Sapphire 480 4GB: $190 USD right now on Newegg.

If you have something other than these to suggest, please tell me. I'd love to hear it.

**Comment by TVilaboa** [comment]
The 8GB variant will probably last longer if u plan to mine Eth due to DAG size increase.

**Comment by 192uijo** [comment]
@TVilaboa 

How significantly longer will it last? My friend just told me 4GB and 8GB VRAM won't really make a difference in mining Eth. Now I'm not saying he's right or wrong, but I'm not sure which is true.

**Comment by TVilaboa** [comment]
It won't make a difference in how fast you can mine until DAG size reachs 4GB. If you believe you will sell the card before that or the switch to PoS, its up to you.

http://ethereum.stackexchange.com/questions/426/what-is-the-current-dag-size-when-do-we-expect-to-hit-gpu-limits

> The DAG started at 1 GB at the time of the Frontier launch, and increases by approximately 0.73x per year. That puts the current size at roughly 1.35 GB as of mid-January 2016 (feel free to comment with an exact link if anyone has one).

Following the same crude approximation:

The 2GB limit will be hit around mid-December 2016
The 3GB limit will be hit around mid-April 2018
The 4GB limit will be hit around mid-September 2019
However, it's likely that the switch to PoS will occur long before then.

For what it's worth, certain GPUs require the DAG to be uploaded in chunks. You should search on the forums with the name of your card to find if this solution has worked for other users running the same hardware.

**Comment by S74nk0** [comment]
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
