### ISSUE TITLE
1.7.4.3 clean install cant benchmark crytonight on GTX 750

### ISSUE THREAD

**Issue by b080180d** [nicehash/NiceHashMiner-Archived#573]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/740829/log.txt)
last working miner is 1.7.4.0

pls see log file. assistance is needed. appreciate and thanks.

**Comment by foxwarernd** [comment]
for cryptonight wrong params -   --launch=8x40
works fine and more hash rate with -   --launch=8x20
nicehash devs what?

**Comment by b080180d** [comment]
how do i open the nicehash with launch=8x20 ?
pls advice. :)

added - i found this "AlgorithmSettings\Algorithm\ExtraLaunchParameters	text	Additional launch parameters when launching miner and this algorithm." in the main page.

works now.. thanks foxwarernd

**Comment by nicehashdev** [comment]
Cryptonight miner for NVIDIA cards is somewhat broken. In near future, we will bring you better miner for NVIDIA cards.
