### ISSUE TITLE
GTX 760 Ti Equihash issue

### ISSUE THREAD

**Issue by Treebeardz** [nicehash/NiceHashMiner-Archived#576]
Its listed but when a benchmark is attempted the benchmark ends and gives no score. If its the only algorithm selected NichHash will report there are none selected. Running on Windows XP with 2Gb or RAM latest Nvidia drivers 378.49.

Totally meant windows 7 lol

**Comment by nerdatwork** [comment]
Did you check your profitability here ? https://www.nicehash.com/index.jsp?p=calc

**Comment by Treebeardz** [comment]
I am not quite sure what you're asking? The GTX 760 Ti is not listed in the profitability list. All I am saying is that it wont run or benchmark at all.

**Comment by nerdatwork** [comment]
My logic was to select a particular algo based on the above mentioned page and see if it works.

**Comment by nicehashdev** [comment]
NHM is not officially supported to run on Windows XP. Please install Windows 7, 8.1 or 10.
