### ISSUE TITLE
Nicehash Ethereum (Linux)

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#578]
So I wanted to try installing the Nicehash Ethereum miner on my Linux system (Zorin). I wondering how will it work. Is it similar to the Nicehash miner to where it converts to Bitcoin? What kind of performance difference will there be?

**Comment by nicehashdev** [comment]
NiceHash Miner for Linux is coming soon. Your question has nothing to do with current NHM. Closing.
