### ISSUE TITLE
CPU miner - cryptonight

### ISSUE THREAD

**Issue by Jchan161** [nicehash/NiceHashMiner-Archived#579]
![image](https://cloud.githubusercontent.com/assets/9319636/22618258/57e8ee0c-eb23-11e6-9c8e-5da27f5cdb50.png)

Recently my cpu is giving me this error when mining cryptonight. How to I fix this? Im relatively new to mining in general.

**Comment by nerdatwork** [comment]
Try changing server location to NON europe ;)

**Comment by Jchan161** [comment]
Yeah I did that and it couldn't even connect for the GPU. Anyway I tried again a few hours later and it worked.
