### ISSUE TITLE
Ethereum - error allocate the DAG

### ISSUE THREAD

**Issue by Kekkonshiki** [nicehash/NiceHashMiner-Archived#58]
![dag_error](https://cloud.githubusercontent.com/assets/12028666/13980433/85ab3714-f119-11e5-8d6d-430317a50820.PNG)
to resolve the problem, need set the variable "GPU_SINGLE_ALLOC_PERCENT"

**Comment by theLosers106** [comment]
Will be in the next release..

**Comment by felixbrucker** [comment]
nice, just wanted to create a feature request for env variables for that :D

**Comment by malagent** [comment]
Where/how do I set this magical variable in lieu of awaiting the next release?
I was having no problems at all with ethereum, made no changes and it just stopped working a couple of days ago giving this exact error. Of course the nicehash software wont move on, so my GPU just keeps retrying and failing and I earn nothing with it. i have to manual set the config file to skip this algo so it will not get stuck in an infinite loop of not paying me. =(

**Comment by Kekkonshiki** [comment]
I'm manually start it (whithout NHMiner).
I've checked NHMiner now and it ran as is O_o. May be trouble with creating DAG

**Comment by felixbrucker** [comment]
For me the error persists, starting my own copy of ethminer with the env variables set before works (which is what im using right now)
it seems to be related to the driver and gpu bios settings in regards to the maximum allowed single allocation which depends upon the various gpu models
for me the 290x and 7970 work fine, the 7870 gives the error

**Comment by Kekkonshiki** [comment]
270x 2GB without error now... and i don't know what i did for

**Comment by Kekkonshiki** [comment]
for temporary resolve the problem you need set the variable (once run from bat-file):
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
[var.zip](https://github.com/nicehash/NiceHashMiner/files/195300/var.zip)

**Comment by felixbrucker** [comment]
in addition to the setx commands i have put:

START C:\Users\miningrig\Desktop\NiceHashMiner.lnk

below, to get my autostart on system bootup working again

**Comment by malagent** [comment]
thank you both, I will give it a try today and see how it work. =) I'm letting it chug away for now whilst I finish building another rig and setting up some antminers.

**Comment by theLosers106** [comment]
Resolved in https://github.com/nicehash/NiceHashMiner/commit/000f86321d13a7271382fd0f212f4b123d011bb2.
