### ISSUE TITLE
Getting Less Hashes Than Profitability Calculator shows

### ISSUE THREAD

**Issue by vanni2121** [nicehash/NiceHashMiner-Archived#580]
I am getting less hashes per card than shown on nicehash's profitability calculator:
I Have 
2x GTX 1070 showing 360-370 Sol/s each, (Prof Calc - 431 Sol/s ea)
2x GTX 1060 6 GB showing 250-260 Sol/s (Prof Calc - 281 Sol/s ea)
1x GTX 970 Hybrid OC showing 240 Sol/s (Prof Calc - 291 Sol/s)
1x GTX 960 OC showing 110 (Prof Calc - 141 Sol/)

I am using the latest Nvidia Drivers (378.49), and the latest Nicehash Miner v1.7.4.3, windows 7 64 bit (updated) 16 GB Ram and an AMD Phenom CPU 8Core. I have also slightly under clocked the cards (using ASUS GPU Tweak 2 power slider NOT voltage) in an attempt to keep them cooler, but this has not made a difference even if the card are normally clocked.

Any Ideas? or is the above what I should be getting?
Cheers!

**Comment by BaalMcKloud** [comment]
Keep in mind that Nvidia cards are reference cards.
Asus and other vendors changing the reference cards to there own with clock speeds etc etc..and bringing more than 1 model from it.
Asus has 5 on there page from the GTX 1070 card.
every GTX 1070 card has his own speed.

other than that..maybe a hardware or driver problem.
are you using all in one PC?!

**Comment by nicehashdev** [comment]
Just increase memory speed on these cards. If you have samsung memory, you can overclock +500 or more. Speed increase will be visible.

If you are unlucky with micron memory, search for BIOS updates. Then you can overclock almost as good as samsung memory.

**Comment by vanni2121** [comment]
Thank You So Much For your replies!
I'll Give it a crack in overclocking memory! I'm Using mainly Asus and Gigabyte Cards.

**Comment by vanni2121** [comment]
Totally Worked! I'm Getting over 250 Sol/s More over all with Increase in memory clock speed!
I've also installed MSI Afterburner to replace ASUS GPU Tweak 2. Seems easier to use with more results!
Thanks again!!
