### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#581]

**Comment by nerdatwork** [comment]
Yes you can haha

**Comment by tmslacker** [comment]
This wasn't the intended post, but I have a few question.  I have few question about gibhub and good information would go a long way!  I'm trying to understand a few things and good information would go a long way.  I'm new to the scene and would like to give better feed back!

**Comment by nerdatwork** [comment]
Ask awayyyyyyyy

**Comment by tmslacker** [comment]
I'm good with windows systems.  I can handle my own when it come to unix and linux, but I'm not a programmer.  Im not sure where to start?

**Comment by tmslacker** [comment]
I can read code.

**Comment by nerdatwork** [comment]
Well close this thread and I will help you out in the other thread you have on :)
