### ISSUE TITLE
Sgminer 5.5.0 and 5.6.0 low hashrates for AMD R9 290x

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner-Archived#583]
Hello,

Sgminer 5.5.0 and 5.6.0 both give very low hashrates when mining daggerhashimoto or pascal.
DH - 8 MH/s instead of 27
Pascal - 15 MH/s instead of 650

Reason - it doesn't use whole engine clock, keeps running on average 430 MHz instead of factory 1040 MHz.

Tried changing this by overclocking from Radeon Settings app as well as from sgminer itself (by setting clock manually in GPU settings)

No luck.

**Comment by AngryOverlord** [comment]
This is also happening when attempting to benchmark on an AMD R9 390x, the GPU usage has spikes that never stay at 100% usage and the clock speed floats ~450 MHz. It seems the new sgminer or the default parameters for it do not work well with AMD cards. It is working fine with sgminer 5.5.0 though, it's only on the new 5.6.0 that I am having issues.

Here is the dump.txt from the sgminer 5.6.0 runs that never completed benchmarking with the above issues.
[dump.txt](https://github.com/nicehash/NiceHashMiner/files/753301/dump.txt)

**Comment by giosal** [comment]
may this be caused by Radeon ReLive version of driver?
there was a note in release description about using non ReLive version...

**Comment by AngryOverlord** [comment]
Not for me, I'm currently using Radeon Software Version 16.11.1 (Pre ReLive) unless it needs to be exactly driver version 16.11.5?

**Comment by giosal** [comment]
I don't know, I'm currently updating to 17.1.2 as it popped up for me.
if not working, will check with 16.11.5
But I suppose you have first to remove the newer version

**Comment by AngryOverlord** [comment]
After updating to 16.11.5 lbry is running perfectly fine using sgminer 5.6.0. The benchmark algo order did shift around, and it appears that neoscrypt is now missing from the list which was causing the errors before.

**Comment by giosal** [comment]
actually, installing 16.11.5 did solve the probliem
