### ISSUE TITLE
stratum read_until: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by Junior88** [nicehash/NiceHashMiner-Archived#584]
ethminer.exe will start running for about 5-10mins and then stops. 
![ethminer exe-error1](https://cloud.githubusercontent.com/assets/7053340/22628121/1b0bff9e-eb94-11e6-9209-f440170c9378.png)

**Comment by AngryOverlord** [comment]
This looks like it is caused by another algorithm being better profitability. NiceHashMiner doesn't close the ethminer window due to needing to load the DAG every time it starts it up, instead it will close the connecting and stop mining with it until it is the most profitable again.

**Comment by Junior88** [comment]
Thanks! I will just leave the ethminer window open.
