### ISSUE TITLE
ZecMiner takes a really long time to connect now with SSL enabled

### ISSUE THREAD

**Issue by dandrea2** [nicehash/NiceHashMiner-Archived#586]
Whenever the algo switches in NHM to Claymore's Equihash miner, it takes a good minute for it to actually start mining.  With the windows not hidden I see it gives an error that it cannot connect to the pool, then about 30 to 45 seconds later it connects and starts mining.  Before the update for SSL, it would start almost immediately.

Obviously this needs fixed.  Or if it can't be, maybe a way to force it not to use SSL?

**Comment by dandrea2** [comment]
I tried setting the command line option "-retrydelay 5" in the settings, but it's not being passed to ZecMiner when it start.

**Comment by S74nk0** [comment]
ZecMiner uses SSL for a while now... does changing service location help?
As for the missing parameter it is not added by default but it can be added in the internals settings. I'll post what you need to update

**Comment by S74nk0** [comment]
If you replace [MinerOptionPackage_ClaymoreZcash.zip](https://github.com/nicehash/NiceHashMiner/files/753416/MinerOptionPackage_ClaymoreZcash.zip) with the existing file under internals folder you will be able to use retrydelay flag. This file has an added parameter feature 

> {
      "Type": "ClaymoreZcash_retrydelay",
      "ShortName": "-retrydelay",
      "LongName": "-retrydelay",
      "Default": "20",
      "FlagType": 1,
      "Separator": ""
    }

Under **GeneralOptions** (more info [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#how-to-add-missing-miner-flag))

**UPDATE!!: after changing these files you have to restart NHM (best to change it while NHM is not running)**

**Comment by dandrea2** [comment]
On NHM 1.7.4.3, I noticed in the window when it was shown that it was connecting without SSL and wasn't even trying it from what I could see.  With 1.7.4.4, it's trying with SSL from the start.  That's what made me think it was just added.

I'm trying it with the updated file above to see if that gets the delay shorter at least.

I haven't tried it with a different service location yet, been using USA since that is where I'm located.  I'll give that a try if the retrydelay option doesn't help.

**Comment by dandrea2** [comment]
Hmm, this is weird.  This time it connected on the first try....

**Comment by dandrea2** [comment]
Well, maybe adding the parameter did something, maybe not.  Now it connects on first try every time, whether I'm on USA or Europe location.
