### ISSUE TITLE
Low rate on new versions NHM + bag with bench

### ISSUE THREAD

**Issue by leshiy-gr** [nicehash/NiceHashMiner-Archived#587]
Performance of new versions dropped !!! Similarly, I can not say which version it started about 1.7.3.4-1.7.3.8 initially fell slightly and then more. Now the same computer with the version 1.7.3.1 provides much more than the last versions. I'm surprised I did not find similar problems described here. Noticeably less hashrate not only on the video card (I have it is very weak), but also on the processor. I'm surprised that this is no one else noticed? After changing the version I re-did benchmarks.

The second problem is noticed with the benchmarks. After passing the test, the value remains zero probably because of low productivity. But after saving the test results and re-run each time need to pass this test! And again it goes very quickly. And so every time you start. Of course, I can simply disable this algorithm.

**Comment by S74nk0** [comment]
@leshiy-gr What hardware are you using. With new versions there are new miner updates and in your case some of them might be performing lower then the old ones. Give some more info.

**Comment by leshiy-gr** [comment]
CPU Intel i5-3570K
GPU GeForce GTX650, GT630
Now i testing last version

**Comment by nicehashdev** [comment]
Try latest version. Closing.

**Comment by leshiy-gr** [comment]
1.7.4.5 - same problem. Latest version not work on cpu - see #621
