### ISSUE TITLE
Excavator missing .dll error on v1.7.4.4

### ISSUE THREAD

**Issue by magnoman** [nicehash/NiceHashMiner-Archived#588]
Excavator is looking for a missing .dll during benchmarking.  This also happened last night when I downloaded the stand-alone client.  If I manually change the name of cudart64_80.dll to cudart64_65.dll it works fine.  fyi.

Anyone else having this issue?

![excavator_error](https://cloud.githubusercontent.com/assets/25410005/22632821/7aeabd1e-ebea-11e6-81e7-5525073a18c5.jpg)

**Comment by ChinnChilla84** [comment]
Same here with GTX 980 @ 375.70 driver on W10 x64

**Comment by S74nk0** [comment]
[new version](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.5) should have this fixed.
Reopen if the issue is still pressent
