### ISSUE TITLE
pls internet connection problem

### ISSUE THREAD

**Issue by masoodrana007** [nicehash/NiceHashMiner-Archived#59]
i have mning for 2 days and it says this massage..can nit mine...
![capture 3](https://cloud.githubusercontent.com/assets/18024787/14006173/cf514350-f127-11e5-8155-6340028d2c81.PNG)

**Comment by theLosers106** [comment]
It will give that if it cannot connect to NiceHash server.. make sure your internet connection is stable..

**Comment by masoodrana007** [comment]
but how can i solve it pls help me

**Comment by theLosers106** [comment]
Refer here: https://www.nicehash.com/?p=faq#faqs13
Check to make sure you can ping and telnet to the NiceHash Server you are using (in your case Europe)..

**Comment by masoodrana007** [comment]
give me the step properly...
pls....i dont understand
i am running windows 10 64 bit pls

**Comment by theLosers106** [comment]
First, try running it again now and see if it works.. if not, then do this:
1. Press WinKey and type cmd
2. Then, right click on Command Prompt and choose Run as administrator
3. Type, pkgmgr /iu:"TelnetClient" and press enter
4. Type, telnet x11.eu.nicehash.com 3336
5. If successful, the command line should show a blank screen.

**Comment by masoodrana007** [comment]
it successfull but this happen pls help me...

**Comment by theLosers106** [comment]
Please send your public IP address (http://www.whatismypublicip.com/) to support@nicehash.com to make sure that your IP address is not blocked..

**Comment by masoodrana007** [comment]
ok

**Comment by theLosers106** [comment]
@masoodrana007 Have you solved your problem yet?

**Comment by masoodrana007** [comment]
no same problem again no solution i follow your order but no solution...

**Comment by theLosers106** [comment]
Have you checked your firewall?

**Comment by masoodrana007** [comment]
fire wall off

no solution this problem

**Comment by aear** [comment]
Strangely, the act of pinging the server solved the problem for me. Just thought I'd mention the oddity as Nicehash said no internet before I pinged the EU server. Works the second I ping it?

**Comment by malagent** [comment]
ok so for what it's worth all was fine, then sometime yesterday no connections to NiceHash work  (for mining anyway).
It's not the firewall, it's on all rigs and all algorithms. I can ping just fine, just cannot mine. So for now I've had to manually switch everything over to something else.
![fail 0](https://cloud.githubusercontent.com/assets/17844295/14609338/02d3d7b6-054f-11e6-99c4-0e0814c44756.PNG)
![fail 1](https://cloud.githubusercontent.com/assets/17844295/14609340/02d71f70-054f-11e6-80dc-2a0a36ec4514.PNG)
![fail 2](https://cloud.githubusercontent.com/assets/17844295/14609339/02d59330-054f-11e6-9afa-aabf1c34d2be.PNG)

**Comment by malagent** [comment]
OK now suddenly it just works. I dunno, but spiffy that it's back to hashing!

**Comment by theLosers106** [comment]
Can I close this issue? It seems to be your internet connection that is at fault and not the NiceHashMiner itself.. =/

**Comment by malagent** [comment]
@theLosers106 It wasn't anything in my network I can attest to that. I could ping and connect to NH through anything but the applications themselves. I was even able to connect through (third party) mining binaries themselves.
However, it was only temporary and I have no idea where the problem really was. But for now it seems the NH miner without modification or update is functioning correctly—at least for me.

**Comment by theLosers106** [comment]
Will be closing this issue now..

**Comment by masoodrana007** [comment]
But it is not solved yet

**Comment by theLosers106** [comment]
do you have any antivirus running on your computer?

**Comment by masoodrana007** [comment]
No ..i have set it many times but no solution..:(

**Comment by theLosers106** [comment]
what do you mean by "set it many times"?

**Comment by masoodrana007** [comment]
I setup my windows but no solution

**Comment by NaitorStudios** [comment]
Here's how to fix it:
I've found out that NiceHash Miner (and some other programs) can't detect internet connection when IPv4 and IPv6 are enabled at the same time.
Disable one of them and the problem should go away. I think IPv6 is better, so I let it enabled and disabled IPv4, but I don't know if there's any drawbacks.

To disable just right click the network tray icon, then click Open Network and Sharing Center.
In the window that show up, look for "Connections: " right below HomeGroup, then click whats on the right side (should be your network name).
New window, Properties, you will see a list, check or uncheck IPv6 or IPv4, you must let at least one checked.

If this helped you, you may consider a donation, here's my Bitcoin Address:
1KZZX3xfo3PoavhWvVZJPjETTbCprwqBQa

I've recorded an improvised how to video:
https://www.youtube.com/watch?v=fnZ-eoGWt74

For the developers:
NiceHash Miner can't determine with IP version to use when both are enabled, hope in a future update it get fixed so we can use both at same time and people won't freak out with this issue.
