### ISSUE TITLE
Optminer no such host is known

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner-Archived#591]
See Issue name.
Firewall allows the connection.
Optminer can't connect and restarts indefinitely

**Comment by bpvarsity** [comment]
I have this issue as well. AMD 290 with 15.12 drives. 

Optiminer just restarts indefinitely and says no such host is known. 

Only have this issue in 1.7.4.4 nicehash.

**Comment by Sammael** [comment]
![error](https://cloud.githubusercontent.com/assets/6249562/22666087/5c3c4624-ecc8-11e6-86ad-e271783256ea.png)
same problem, win10x64, firewall disabled, actual for all locations

**Comment by semisane** [comment]
Same exact problem.
4x RX480
Win10
Firewall disabled.
16.11.5

**Comment by JesterBaze** [comment]
Same issue here trying to use any Equihash miner option available. Also running Windows 10 x64 with the firewall disabled. Running a GeForce R9 290. Are the Equihash servers down, or is this a software bug?

**Comment by bpvarsity** [comment]
@JesterBaze its a software bug with the new version of NiceHashMiner. Optiminer works fine in previous versions of NHM.

**Comment by JesterBaze** [comment]
I noticed the CPU miner for Equihash (eqm) is connecting to private.equihash.usa.nicehash.com:3329, I'm going to try pointing my optiminer at this server and see if I have any luck. I will edit in a few with my results =)
-----------
Just attempted using private.equihash.usa.nicehash.com:3329 using the batch file located at:
C:\Path\To\NiceHashMiner_v1.7.4.4\bin_3rdparty\optiminer_zcash_win\start.bat   (Edit using notepad)

Changed the file to the following:
---------------
```
ECHO "Change the user and password in start.bat to yours!"

REM For nicehash uncomment following (uses bitcoin address as user):
SET POOL=private.equihash.usa.nicehash.com:3357
SET USER=1GWnaZ9AQFxRw82iDjhRz3qGw7WqBAmefn
SET PASSWORD=x

SET GPU_FORCE_64BIT_PTR=1

optiminer -s %POOL% -u %USER% -p %PASSWORD% -m 8080

pause
```
---------------   Don't include these dashes =)

Everything connected and is mining, I'm going to look and see how I can point Nicehash to run these parameters by default when using the GUI.

**Comment by semisane** [comment]
If it does work can you post a walk through. Thanks in advance!

**Comment by bpvarsity** [comment]
Easier to just switch back to 1.7.4.2 or 1.7.4.3

**Comment by semisane** [comment]
@JesterBaze how did you get it to use more than one GPU?

**Comment by JesterBaze** [comment]
@semisane I didn't =(  I'm only using one GPU. 

Try changing this:
`optiminer -s %POOL% -u %USER% -p %PASSWORD% -m 8080 `
to this 
`optiminer -s %POOL% -u %USER% -p %PASSWORD% -m 8080 -i 0`

**Comment by JesterBaze** [comment]
Also looks like I would have to build from source to compile a working version of the GUI for equihash. There is no easy "Text editor -> solution" way to fix where the miner points that I can see.

**Comment by semisane** [comment]
@JesterBaze still only running on 1 GPU - GPU0

**Comment by JesterBaze** [comment]
@semisane Try running optiminer.exe from the cmd line and run the following:
`Optiminer.exe --list-devices`
and let me know what you get, it should be showing each graphics card you have, and _should_ be running all of them by default.

**Comment by semisane** [comment]
[2017-02-06 17:39:55.819] [info] Optiminer/Zcash 1.5.0 (C) Optiminer 2017
Platform (-c) 0, Device (-d) 0:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.14 (VM)
  Address bits: 64
  Available memory: 8589934592
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 0, Device (-d) 1:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.14 (VM)
  Address bits: 64
  Available memory: 8589934592
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 0, Device (-d) 2:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.14 (VM)
  Address bits: 64
  Available memory: 8589934592
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 0, Device (-d) 3:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.14 (VM)
  Address bits: 64
  Available memory: 8589934592
  GCN Support: Gen 4
  Has device specific faster kernel: Yes

**Comment by semisane** [comment]
There has to be a way to set the devices in the bat file - i'm just having a problem finding out the command

**Comment by JesterBaze** [comment]
Maybe try using multiple iterations of the "-i 0" flag. One for each card so:
`optiminer -s %POOL% -u %USER% -p %PASSWORD% -m 8080 -i 0 -i 0 -i 0 -i 0`
Maybe this will trick it into auto setting the intensity on each card forcing them to run?

**Comment by semisane** [comment]
*sigh* no dice. Even better - the one GPU is showing no stats on NH website.

Going to revert back to genoil. These 4 cards are finnicky as all get out.

**Comment by JesterBaze** [comment]
@semisane Those are some nice cards, good luck on the mining. You could always try reverting back to a previous Nicehash version to get everything running smoothly. If you don't mind me asking what is your typical Equihash hashing speed using those? My R9 290 is running ~280 sol/s. +/- 15 sol/s

**Comment by semisane** [comment]
I haven't found a stable equihash miner. When they do work it's around 1300 sol/s for all 4 cards with a little overclocking. Any suggestions on what to use other NHM?

**Comment by semisane** [comment]
I also might switch to powered risers. not sure if that will make a difference

**Comment by JesterBaze** [comment]
@semisane I have tried [Minergate](https://minergate.com/a/4a49d5d0ea666b9774f299a8) before, however the speed vs. profit I was seeing wasn't close to NHM, it was ~10% under NHM, and I honestly can't remember if the payout was all in BTC. I'm pretty sure you had to run through changelly to convert your mining rewards (don't quote me on this). I haven't really found any truly comparable programs to NHM yet. 

*However...* If NHM isn't working why not give it a try, at worst you may waste a few minutes of time.

**Comment by JesterBaze** [comment]
@semisane Btw just after doing some quick reading I would [*strongly* recommend using powered risers](https://forum.ethereum.org/discussion/4980/powered-risers-vs-ribbon-does-it-have-a-significant-impact-how), otherwise you run the risk of popping capacitors on your motherboard. I have no experience on the subject however, this might also be a load of bull haha.

**Comment by semisane** [comment]
Yeah, I'm looking them up on amazon right now. Can't hurt - right?

**Comment by bpvarsity** [comment]
There is no reason to change software. Either download optiminer and run it manually outside nicehash miner or download NHM 1.7.4.2 or 1.7.4.3. The issue is not present in those versions from my testing with my 290's. 

You can download and run optiminer and point it to nicehash pool as well.

**Comment by semisane** [comment]
Do you have a bat file for optiminer running on NH? @bpvarsity

**Comment by bpvarsity** [comment]
Sure one moment

**Comment by bpvarsity** [comment]
REM For nicehash uncomment following (uses bitcoin address as user):
SET POOL=equihash.usa.nicehash.com:3357
SET USER=YOURBITCOINADDRRESSHERE
SET PASSWORD=x
SET GPU_FORCE_64BIT_PTR=1

optiminer  -s %POOL% -u %USER% -p %PASSWORD% -m 8080

pause

**Comment by semisane** [comment]
Well, it sees all 4 cards which is nice. But I'm getting a lot of "found solution index out of range" @bpvarsity

**Comment by bpvarsity** [comment]
What version of Optiminer and what amd drivers?

**Comment by semisane** [comment]
OM - 1.6.1
AMD - 16.11.5

**Comment by bpvarsity** [comment]
Ah sorry I didnt see that you have 4xx cards. I don't recommened optiminer for windows with 4xx cards. Neither does optiminer creator.

Have you tried Claymore? I know its slower but may work better for you.

**Comment by semisane** [comment]
I have not tried Claymore - there are so many versions I wouldn't know where to start.

**Comment by bpvarsity** [comment]
Ill grab you a link

**Comment by semisane** [comment]
Does it need a batch file as well?

**Comment by bpvarsity** [comment]
https://drive.google.com/open?id=0B69wv2iqszefeEc1dkkzWkUyZ0U
Batch file is included in the above link. You do have to add your info in the config.txt file so that the batch file know that pool and btc address to use.

**Comment by bpvarsity** [comment]
Read the readme.txt and it will help you.

**Comment by semisane** [comment]
So far so good. One weird quirk is that one of the 4 cards will hang. First it was GPU1, did a restart, now it's GPU3

**Comment by bpvarsity** [comment]
Try lowering your clocks. I don't use claymore so I wont be to much help but he does have a forum you can post on for more help. Probably best not to do it in this issue as the issue is with optiminer and the new NHM version 1.7.4.4.

**Comment by semisane** [comment]
I appreciate all the help from @bpvarsity and @JesterBaze 
I ordered the powered risers so they should be here soon. Maybe they'll help.

In the meantime I'm using genoil on NHM as that seems to be the most stable with minor overclocks. And it always sees the 4 cards with the average being about 25MH/s per card.

I've been using MSI's afterburner so if anyone has suggestions on stable overclocks let me know. Currently running +20 power, 1350 Core clock, 2125 mem.

**Comment by giosal** [comment]
Update:
NHM v.1.7.4.5 and optminer 1.5.0 still same problem

**Comment by S74nk0** [comment]
this [commit](https://github.com/nicehash/NiceHashMiner/commit/37f376a0e0402c039583ac8624a60957517b1e59) fixes the issue.

**Comment by S74nk0** [comment]
Use this [patch](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.4.5/NiceHashMiner_v1.7.4.5_patch_1.zip). It will fix the issue.
Closing

**Comment by platinum4** [comment]
Now Optiminer just closes after 5 seconds after saying GPU0 is waiting for work from pool.  It says it's connected but it never mines (with patch copied over)

**Comment by tcgirl** [comment]
Error: 

[11:14:50] [OptiminerZcashMiner-MINER_ID(3)-DEVICE_IDs(2)] Starting miner [pid(2780)|bin(bin_3rdparty\optiminer_zcash_win\Optiminer.exe)]   -c 0 -d 2   -m 4003 -s equihash.usa.nicehash.com:3357 -u xxxxxxxxxxxxxxxxxxxxx.worker1 -p x
[11:14:50] [OptiminerZcashMiner-MINER_ID(3)-DEVICE_IDs(2)] [pid(2780)|bin(bin_3rdparty\optiminer_zcash_win\Optiminer.exe)] Starting cooldown checker
[11:14:51] [ClaymoreZcashMiner-MINER_ID(2)-DEVICE_IDs(0,1)] GetSummary exception: No connection could be made because the target machine actively refused it 127.0.0.1:4002
[11:14:52] [OptiminerZcashMiner-MINER_ID(3)-DEVICE_IDs(2)] [pid(2780)|bin(bin_3rdparty\optiminer_zcash_win\Optiminer.exe)] GetAPIData reason: An existing connection was forcibly closed by the remote host
[11:14:52 AM] [OptiminerZcashMiner-MINER_ID(3)-DEVICE_IDs(2)] [pid(2780)|bin(bin_3rdparty\optiminer_zcash_win\Optiminer.exe)] Miner_Exited Will restart in 5000 ms

Device 2 is a r9 380 2GB.  Checked the firewall and it is allowed. Tried the patch as well and it didn't work.

**Comment by Eyedol-X** [comment]
Yup not fixed, straight crashes on the 4x R9 390 rig I have. Claymore works fine, disabled optiminer.
