### ISSUE TITLE
CryptoNight - sgminer issue - Nicehash 1.7.4.4

### ISSUE THREAD

**Issue by bpvarsity** [nicehash/NiceHashMiner-Archived#592]
Benchmark for GPU CryptoNight (**sgminer**) does not work. 

When I force the program to mine it I get the following error

"C:\Users\user~1\AppData\Local\Temp\OCL13360T0.cl", line 457: error: work
          group size exceeds the maximum default value for the selected device
  __attribute__((reqd_work_group_size(WORKSIZE, 8, 1)))
                 ^

2 errors detected in the compilation of "C:\Users\user~1\AppData\Local\Temp\OC
L13360T0.cl".
Frontend phase failed compilation.

[12:46:05] Failed to init GPU thread 0, disabling device 0
[12:46:05] Restarting the GPU from the menu will not fix this.
[12:46:05] Re-check your configuration and try restarting.
Press enter to continue:

**All other benchmarks and miners work perfectly.**

**Comment by bpvarsity** [comment]
I have a AMD 290 with 15.12 driver.

**Comment by abjugard** [comment]
I also ran into issues with 1.7.4.4 and an R9 290 running 15.12 driver. Had to revert to 1.7.4.3 for benchmarks to even run.

**Comment by S74nk0** [comment]
This is an error with extra launch parameters (it will be fixed in new version). But to make it work you need to change the current parameters to this `--rawintensity 512 -w 4 -g 2`. It will solve the issue. Do this in the **Settings**
