### ISSUE TITLE
NHM hangs when launches Optminer

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner-Archived#596]
NiceHashMiner hangs (stops responding) after having launched Optminer and stops switching algorithms.

Same config:
GPU: R9 290x
Driver: .16.11.5
NHM: 1.7.4.5 with patch 1
Optminer: 1.5.0

UPDATE: although, clicking on Try to restore program actually does restore it

**Comment by S74nk0** [comment]
@giosal Does the issue happen if with a newer version of **Optminer**? If you copy over the [latest](https://github.com/Optiminer/OptiminerZcash) to **bin_3rdparty\optiminer_zcash_win** folder?

**Comment by giosal** [comment]
@S74nk0 yes, issue is still there, Optminer v1.6.1
Although, obviously it is faster, by about 10-15%, instead 280 Sol/s my 290x is mining at 320 Sol/s

**Comment by S74nk0** [comment]
@giosal Ok thanks for the feedback. Then the issue is in NHM somewhere.

**Comment by giosal** [comment]
also, there is a small issue with optminer - both optminer and NHM are showing 320 Sol/s but NHM miner details webpage shows around 270 Sol/s consistently (not like usually, when it goes +-30%, but average rate is correct)

**Comment by giosal** [comment]
@S74nk0 after update of NHM 1.7.5.0 issue is still here

**Comment by kenshirothefist** [comment]
Unfortunately the Optiminer software is not very stable under windows. The main focus of Optiminer developer is Linux, and Windows version is unstable. We leave it in mainly for a choice - for users who would not like to use Claymore Equihash miner. However, if Optiminer is not working for you, you should simply enable Claymore Equihash miner (which is also faster in the Windows version).
