### ISSUE TITLE
1.7.4.4 Slower Cryptonight algorithm

### ISSUE THREAD

**Issue by R0x0r97** [nicehash/NiceHashMiner-Archived#597]
On 1.7.4.2 I used to have 270 H/s, I skipped 1.7.4.3 and now on 1.7.4.4 and even on 1.7.4.5 I get only 213 H/s. Every version was fresh install. Did you change the miner or some settings?
The gpu is an Nvidia 860M 4GB.

**Comment by S74nk0** [comment]
The miner was changed. Copy over the old miner to the new one (the old one is faster for your GPU) and you will have better speeds.

**Comment by R0x0r97** [comment]
What should I copy? Just the ccminer_cryptonight.exe file?

**Comment by S74nk0** [comment]
> What should I copy? Just the ccminer_cryptonight.exe file?

Yes just that file.

**Comment by R0x0r97** [comment]
Nothing changed... But I just noticed something. The difference between the two versions and starting the miner is that the newer version says "using 20 blocks of 8 threads" and the older one says 40 blocks.

**Comment by S74nk0** [comment]
@R0x0r97 check your previous settings (Extra launch parameters for your GPU) that could be the reason you aren't getting full speed.

**Comment by R0x0r97** [comment]
Same settings, everything is the same... Well, Ill stick with the older one for now.

**Comment by S74nk0** [comment]
@R0x0r97 driver updates can also reduce miner speeds. Keep an eye if the older NHM gives slower speeds as well and give feedback if it does or doesn't

**Comment by R0x0r97** [comment]
Im using the same driver since 1.7.4.0 came out, 369.30 so its not about that.
The older version still gives higher speeds.

**Comment by S74nk0** [comment]
@R0x0r97 do a re-bench with the older version. And report if there is any speed change (**ccminer_cryptonight** doesn't have API reading support so the speed estimation is from the benchmark, that is the reason for the two stars at the end to note an exception).

**Comment by R0x0r97** [comment]
I did re-bench like 5 times, but nothing changes. The older version still gets more.

**Comment by S74nk0** [comment]
@R0x0r97 Are you checking the NHM numbers or the ones in the miner window?

**Comment by R0x0r97** [comment]
both

**Comment by blue-yu** [comment]
Stanko, I think that R0x0r97 is having same problem as me. Solution is described in another topic.

**Comment by R0x0r97** [comment]
Which topic? Can you tell me please?

**Comment by blue-yu** [comment]
#589 is the topic

**Comment by R0x0r97** [comment]
Thank you. It worked.

**Comment by S74nk0** [comment]
@R0x0r97 it seems the problem was the incorrect default ignored values, thanks @blue-yu for helping. New releases will not have this issue anymore ([commit](https://github.com/nicehash/NiceHashMiner/commit/f1a368eec41cbb5dbe2ac502ce5771fe4f51fbc3))
