### ISSUE TITLE
NiceHashMiner is crashing

### ISSUE THREAD

**Issue by nickdf** [nicehash/NiceHashMiner-Archived#598]
When I start newest version NiceHashMiner is crashing I have 
Here i have RX 470

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nikol_000\Desktop\NiceHashMiner_v1.7.1.1\NiceHashMiner_v1.7.4.5\bin\sgminer-5-6-0-general\kernel'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path)
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.AMD.QueryAMD()
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.QueryDevices(IMessageNotifier messageNotifier)
   at NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
NiceHashMiner
    Assembly Version: 1.7.4.5
    Win32 Version: 1.7.4.5
    CodeBase: file:///C:/Users/nikol_000/Desktop/NiceHashMiner_v1.7.1.1/NiceHashMiner_v1.7.4.5/NiceHashMiner.exe
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/nikol_000/Desktop/NiceHashMiner_v1.7.1.1/NiceHashMiner_v1.7.4.5/Newtonsoft.Json.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8015 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8019 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Management
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8018 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Users/nikol_000/Desktop/NiceHashMiner_v1.7.1.1/NiceHashMiner_v1.7.4.5/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nikol_000/Desktop/NiceHashMiner_v1.7.1.1/NiceHashMiner_v1.7.4.5/MessageBoxManager.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

![image](https://cloud.githubusercontent.com/assets/25613597/22695613/9ab69868-ed4b-11e6-9594-bec7f0440ec4.png)

**Comment by nickdf** [comment]
Can anyone help?

**Comment by S74nk0** [comment]
@nickdf this is a BUG in NHM with new sgminer change. To workaround it create a **kernel** folder in **sgminer-5-6-0-general**. Please report back if it helps

**Comment by S74nk0** [comment]
@nickdf the download package has been updated. You can do a clean install and it will download the new package with the missing folder. Please give feedback if it fixes the issue.

**Comment by nickdf** [comment]
@S74nk0 I redownload all again program start. When I close I get same error

![image](https://cloud.githubusercontent.com/assets/25613597/22697689/8e6b8d50-ed52-11e6-8244-b359e077e4a3.png)

**Comment by S74nk0** [comment]
@nickdf Is this with a clean install? No old configs and/or bins folders/files?

**Comment by nickdf** [comment]
@S74nk0 Yes this is with clean install. Today I add RX470, before I mine only with CPU I7 4790K

**Comment by S74nk0** [comment]
@nickdf I can send you a version that doesn't check this [NiceHashMiner_sgminer_no_copy.zip](https://github.com/nicehash/NiceHashMiner/files/758187/NiceHashMiner_sgminer_no_copy.zip). But it would be great to solve the issue in general (with your help). If unzip the package to the **C:\** root and run it from there does the same error appear?

**Comment by nickdf** [comment]
@S74nk0 Yes it works now. Works in folder on my desktop too.

**Comment by nickdf** [comment]
@S74nk0 but sgminer take too long to benchmark I think it is not working

**Comment by nickdf** [comment]
Stucked more than 5 minutes there

![image](https://cloud.githubusercontent.com/assets/25613597/22699479/dcdd7354-ed57-11e6-9056-b5b2826cae9f.png)

**Comment by S74nk0** [comment]
@nickdf post the log file

**Comment by nickdf** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/758259/log.txt)
@S74nk0 

this is the log from my desktop 
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/758287/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/758288/log.txt)

**Comment by nickdf** [comment]
@S74nk0 I can do clean Install and sent you a log with error message if you need,

**Comment by S74nk0** [comment]
@nickdf That would be helpful. Also the posted logs are helpful. 

I see this `No connection could be made because the target machine actively refused it 127.0.0.1:4001`

It could be that Windows defender or some other AV program is blocking sgminer from running.

**Comment by nickdf** [comment]
@S74nk0 Kapesky is found as virus, but I exclude that folder to not touch. I will disable firewall to and make new fresh installation.

**Comment by nickdf** [comment]
@S74nk0 Disabled AV, disabled windows Firewall, Disabled my router firewall DD-WRT

It stoped here 
![image](https://cloud.githubusercontent.com/assets/25613597/22701854/2aa4f736-ed5f-11e6-8417-4c5f1f15a4c4.png)


[log.txt](https://github.com/nicehash/NiceHashMiner/files/758416/log.txt)
Here is the log

**Comment by nickdf** [comment]
@S74nk0 Pascal (sgminer) I get BSOD

**Comment by S74nk0** [comment]
Please try [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre)
