### ISSUE TITLE
Last 4 updates, No ALGS will benchmark

### ISSUE THREAD

**Issue by protossdisaster** [nicehash/NiceHashMiner-Archived#600]
Having a lot of issues trying to benchmark algorithms, looks like a sgminer issue

**Comment by protossdisaster** [comment]
Still having issues A lot of the algorithms are not working correctly.... been a problem for the last couple updates.....

**Comment by keztheminer** [comment]
clearly no amd  support anymore  ongoing for 3 months

**Comment by protossdisaster** [comment]
Still no AMD support 4th update, and I'm not even mining on my GPU anymore. This is getting Ridiculous

**Comment by keztheminer** [comment]
yep very clear they don't want amd miners no more

**Comment by protossdisaster** [comment]
Yep pretty sad I can mine with my AMD cpu though! Ive tried changing my drivers, reintializing nicehash, nothing.... All the ALG's just hang while my GPU idles. I left my computer on all night to Benchmark nothing. Disable certain ALGS nothing.

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.
