### ISSUE TITLE
Optiminer: "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by cesarreynab** [nicehash/NiceHashMiner-Archived#601]
When I try to use Optiminer I get the following error:
_GetAPIData reason: An existing connection was forcibly closed by the remote host
Miner_Exited Will restart in 5000 ms
GetAPIData reason: No connection could be made because the target machine actively refused it 127.0.0.1:4001
Shutting down miner_

I have disabled Firewall with no luck. Claymore Zcash Miner works fine.

Any help would be greatly appreciated. I am using Windows 10 x64 and six R9 390.

**Comment by snowcrawl** [comment]
Same issue with me as well, the new version (v.1.7.4.5)  did not help solve the problem.

**Comment by protossdisaster** [comment]
Same issues here with certain Alg's, I legit have to x out most of the ALG's just to run NiceHash, lets not even get into that you cant even successfully benchmark.

**Comment by tcgirl** [comment]
Same problem with R9 380 on Windows 10 x64.

**Comment by Eyedol-X** [comment]
Same here with R9 390s -- crashes and restarts over and over.

**Comment by nicehashdev** [comment]
Should be fixed in latest version.

**Comment by christophedemey** [comment]
I also have this issue, latest version, on 2 PC's.
