### ISSUE TITLE
Help with a 3x gtx 1070 build

### ISSUE THREAD

**Issue by dogfried** [nicehash/NiceHashMiner-Archived#602]
Hi all,
I have just finished building a new mining rig (specs to follow) and i can only get it to mine on 2 cards.When i try to connect the 3rd card the rig wont boot,it just hangs on the press f2 for bios screen.pressing f2 does nothing and as i say it just hangs on that screen.I have also tryed switching the cards and risers and they all work fine alone or in pairs.I would be thankful if someone would check the specs for to ensure i have made no mistakes in that area.

Build:
3x EGVG gtx 1070's Black ed 8gb
asus N3150M-E motherboard with integrated N3150 intel celeron
4 GB kingston RAM (i have tried an 8gb)
120GB kingston ssd 
Xpredator 1000GM psu by Aero cool

**Comment by dogfried** [comment]
I missed out the operating system.windows 8.1

**Comment by snowcrawl** [comment]
I would try to make sure that the connectors are firmly in place in the PCI-e 1X slots for example.   Maybe try different combinations of the 2 GPU configuration to see if there might be a specific PCI-e slot that isn't cooperating.   I generally go with 16 GB with 3 or more cards on a machine., although I see that this motherboard has a max of 8 GB.   Certain motherboards have limitations.  I just accept it and buy extra machines.  For example I had to accept that I could not connect NVIDIA cards to my motherboard using a PCI-e 1X to 3 PCI-e  1X hub, it only seems to work with AMD cards.

**Comment by dogfried** [comment]
Thank you,I will give it a try

Sent from Yahoo Mail on Android 
 
  On Thu, 9 Feb 2017 at 1:12, snowcrawl<notifications@github.com> wrote:   
I would try to make sure that the connectors are firmly in place in the PCI-e 1X slots for example. Maybe try different combinations of the 2 GPU configuration to see if there might be a specific PCI-e slot that isn't cooperating. I generally go with 16 GB with 3 or more cards on a machine.

**Comment by snowcrawl** [comment]
If you consider the price of those cards, it is definitely putting the cart before the horse, trying to demand the very best performance from a computer that is worth less money than only one of these graphics cards.  I just ordered a refurbished HP desktop to get some extra processing capability for mining, and it is worth less than a single GTX 1060 card.

**Comment by dogfried** [comment]
I was led to belive that the only hardware that made a difference was the cards.i see what you are saying though.thankyou a giant for your input.

Sent from Yahoo Mail on Android 
 
  On Thu, 9 Feb 2017 at 14:52, snowcrawl<notifications@github.com> wrote:   
If you consider the price of those cards, it is definitely putting the cart before the horse, trying to demand the very best performance from a computer that is worth less money than only one of these graphics cards. I just ordered a refurbished HP desktop to get some extra processing capability for mining, and it is worth less than a single GTX 1060 card.

**Comment by nicehashdev** [comment]
Not related to NHM, closing.
