### ISSUE TITLE
No Gpu is showing up

### ISSUE THREAD

**Issue by sebi12391** [nicehash/NiceHashMiner-Archived#603]
I actually have no idea because I have open cl installed but my gpu is not showing up in the device selection menu

I have a Windows 10 Pro x64 with a intel core i7 2600 and a amd readion 6770

Log file here [log.txt](https://github.com/nicehash/NiceHashMiner/files/762443/log.txt)

**Comment by S74nk0** [comment]
The reason for the GPU not being shown is usually related to driver version (to old) or that the GPU is too old itself. Looking from the log **AMDOpenCLDeviceDetection** returns an empty list.
