### ISSUE TITLE
NHM not switching from Pasc to Dagger

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner-Archived#607]
NHM 1.7.4.5 pascal and dagger are enabled but it will not switch from pascal to dagger even when dagger's rate is higher.

Win 7 64bit

**Comment by S74nk0** [comment]
Is Dagger profitability higher then the min profit threshold? If you post the log it will be clear if it is not switching because of that.

**Comment by S74nk0** [comment]
This is probably related to **min profit threshold**. If this issue persist when **min profit threshold** is 0 reopen issue.
