### ISSUE TITLE
Pascalcoin constantly shows "Found block..."

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner-Archived#609]
Constantly getting "Found block for pascal.eu.nicehash.com!" instead of accepted share message.

NHM 1.7.4.5
Win 7 ulti 64 bit
![image](https://cloud.githubusercontent.com/assets/15882196/22860364/93160bf0-f121-11e6-863f-9fb6128336b3.png)

**Comment by nicehashdev** [comment]
This is normal behaviour, sgminer informs you when high enough share diff is found. Nothing abnormal.
