### ISSUE TITLE
Nvidia Quadro 4000 not detectet

### ISSUE THREAD

**Issue by dontspammexyz** [nicehash/NiceHashMiner-Archived#61]
Hello, my Video Card is not detected. Newest Driver for Windows 10 x64 are installed. What to do to bring it up?
![nicehashminer quadro](https://cloud.githubusercontent.com/assets/18090919/14067540/084c6648-f467-11e5-9f53-04bfda9d4bc1.png)

**Comment by theLosers106** [comment]
Could you show me the log file contents.. one more thing.. run the ccminer manually (ccminer_tpruvot) with --ndevs and post it here too..

**Comment by sunscreen** [comment]
I know this is old but if you look the straight quadro 4000 only has 2.0 Compute support so I doubt its going to fly first thing I learned in my miner experience was that all cards need to support compute 2.1 minimum for Nvidia stuff

**Comment by theLosers106** [comment]
Thanks @sunscreen for noticing that details.. so I'll be closing this as this is not a device NiceHashMiner supports..
