### ISSUE TITLE
Miner restarting and freezing Windows

### ISSUE THREAD

**Issue by Yehti** [nicehash/NiceHashMiner-Archived#610]
ok idk whats happening but my miner works fine but after awhile while mining equihash it reopens a new terminal and it will freeze windows  this morning when i woke the main mining window was there but it had opened i think 7 other windows I'm forced to do a manually shutdown  i will take a screenshot the next time it happens  sometimes it mines for a hour or 5 any help is appreciated  thanks

**Comment by vanni2121** [comment]
Hi Yehti, I had the same problem and I found a way around it.
When I Introduced the 5th GPU the miner became way more unstable and the last slot was not producing enough solutions. at first i thought it was the GFX, but when I tried it on another PC it works fine. It all comes down to how many lanes the CPU has and if the board you are using has Gen3 PCIE or Gen2. Gen2 is usually more stable. 
So to my problem i configured my miner to mine only equihash without switching to any other algorhythm from the nicehash settings. This has reduced possibly my profitability from other algos, but my miner has been operating without problems for the past 3 days, no restarts and no crashes, and the way I saw it it actually generated more money than when i was restarting the miner all the time.
I Hope this helps.

**Comment by Yehti** [comment]
Thanks for the info  I guess it would of been easier to help if you knew what I was working with.   

Mobo-H110M-A  3 cards.  I have used all 3 for weeks. This all just started  happening 
Intel i3 6100 
8gb ddr4
1  sapphire 7970
1 Asus R9 280x 
1 XFX R9 290x    ... Other rig has 1 7950 just thought I share 

Power supply's.    1 650w corsair 
                               1 350w idk. 
The 650 runs the board and 2 cards and the 350 runs the other card    Do I have enough power like I said I mined this way for weeks 

I have been able to get a screen shot.  Today I reloade Windows again. Due to freezes making me force restart haven't tried to mine yet will update.  Thanks

**Comment by Yehti** [comment]
I don't think mine switches. Just opens new Windows for same algos

**Comment by Yehti** [comment]
![Uploading image.png…]()

**Comment by Yehti** [comment]
![Uploading image.png…]()

**Comment by ALQADIRI** [comment]
i wan't ask..
bitcoin production usually how many times per month? there is the payment schedule?

**Comment by Yehti** [comment]
Few times a month

**Comment by Yehti** [comment]
Y won't my pic upload

**Comment by DillonN** [comment]
Is this for the Claymore Zcash miner? It seems there's an issue with it and either new AMD drivers or new Windows updates. Starting in version 12 the same thing happens on my main rig (newest drivers) but not my second (which is still on old drivers). Only workaround I found was to download the older Claymore version and overwrite the claymore equihash folder with it. 

Definitely a problem with the miner itself though and not NHM, since the same thing still happens when you run the miner standalone

**Comment by Yehti** [comment]
Hey sorry for late response I had one of my gpu's overclocked to much.     But with that said I still do crash from time to time but sometimes it take a day or two

**Comment by S74nk0** [comment]
> I had one of my gpu's overclocked to much

OC can be a common reason for OS restarts/BSODs and general incorrect miner behavior.
Closing...

**Comment by ghost** [comment]
Can I reopen this for general solutions when both stock settings, underclock powerlimit settings and across multiple PC's - it hangs after stopping any AMD card when it mines CryptoKnight.. Any idea why?

**Comment by Alexisgarci** [comment]
Im having the same problem. I have 6 1080ti GPUS, z270 pro carbon, i7-7k, 32GB, 2 PSU's 1200W, windows 10 pro, all drives up to date and windows to. Windows freezes when i activate the 6 gpu. I can run 5 gpu's for days but when i turn the 6 onn on nicehash to mine, windows freezes after a while. Anyone knows how to stop this freezes?

**Comment by aalicagan** [comment]
@Alexisgarci  i have same problem. Did you solve it?

**Comment by Alexisgarci** [comment]
yes bro, i did. its running good with no problems for like 2 weeks. read this threat https://github.com/nicehash/NiceHashMiner/issues/1085#issuecomment-362459094
i followed a guide provided by MSi that someone posted there. I followed step by step.
 But first i formatted windows and im on windows 1703(dont update it). The guide is this https://www.msi.com/blog/Mining_Intel_Motherboard_Go_with_MSI_100_200_Series_Motherboard
