### ISSUE TITLE
Nicehash Miner bottom margin disappears after a couple algorithm shifts with multiple GPUs 

### ISSUE THREAD

**Issue by snowcrawl** [nicehash/NiceHashMiner-Archived#611]
I was wondering if there is any possibility of fixing this issue,  which has been ongoing over all the versions I have used, where the bottom margin disappears from NiceHash Miner after a couple of algorithm shifts have taken place, and so have morphed the shape/size of the NiceHash miner display box,  That info seems to drop out after a certain point.  Seems to only affect machines that have 3 or more GPUs connected.   What is missing is the part that lists the Global rate and Bitcoin balance.  In addition, there is also frequently one active mining process missing from the display whenever this display dropout occurs.   If you stop and restart the miners, it will reappear again, until enough algorithm shifts take place to make it disappear again.   Note that the performance is unaffected by this, it is strictly a display issue.

**Comment by nicehashdev** [comment]
Please, try latest pre-release version and report back if you are still having these issues.
