### ISSUE TITLE
Use --remove-disabled by default

### ISSUE THREAD

**Issue by Fredar** [nicehash/NiceHashMiner-Archived#613]
When you run only few cards from whole rig in sgminer, then not included cards are listed as `OFF`.

For some reason this kind of setup produces very unstable mining process + may mix up intensity settings between cards (requires different cards present on rig to happen).

I have discovered that passing `--remove-disabled` flag to sgminer resolves all those issues perfectly.
Please consider using it by default.

**Comment by S74nk0** [comment]
@Fredar Thanks for the suggestion! It is now [added](https://github.com/nicehash/NiceHashMiner/commit/f34a7cb792ef1615858e2a0afe8ce521c6c2af6a).

Closing...
