### ISSUE TITLE
NiceHashMiner.exe crashes immediate

### ISSUE THREAD

**Issue by neoshamangames** [nicehash/NiceHashMiner-Archived#614]
As soon as I execute NiceHashMiner.exe, Windows notifies me "NiceHashMiner has stopped working".  Running as administrator does not help.

I'm running:
Windows 7 Home Premium 64 bit
16GB RAM
Intel Core i7-6700K

**Comment by neoshamangames** [comment]
A little more info:
When I click Debug, it notifies me
"An unhandled exception ('System.TypeInitializationException') occurred in NiceHashMiner.exe"

**Comment by S74nk0** [comment]
@fractalfrenzy please check if this error is present in the new version.

**Comment by neoshamangames** [comment]
I was able to resolve the issue by adding an Exception in Avira antivirus.  It looks like it was blocking the execution.
