### ISSUE TITLE
[ver1.7.5.0] CryptoNight benchmark not start, missing file MSVCP140.dll

### ISSUE THREAD

**Issue by Skymax7** [nicehash/NiceHashMiner-Archived#616]
xmr-stack-cpu.exe need file MSVCP140.dll

**Comment by Timoulis** [comment]
Same here, with 1.7.5.0.
Cpu is i7 980 (soc 1366)
Win 10 Pro 64b

**Comment by S74nk0** [comment]
The download package has been updated. Missing files are included. If the download link is cached clear cache or [install](https://www.microsoft.com/en-us/download/details.aspx?id=48145) x64 version
