### ISSUE TITLE
CPU's not showing up

### ISSUE THREAD

**Issue by brandan-schmitz** [nicehash/NiceHashMiner-Archived#618]
I have two Intel Xeon E5520 CPU's that have worked with this miner in all previous versions. However after updating to 1.7.5.0 they no longer should up and no amount of fiddling with the settings will resolve it.

Specs:
OS: Windows Server 2008 r2 Datacenter
Processors: 2x Intel Xeon E5520
RAM: 16GB DDR3
Drive space: 5TB in RAID, 2.4 still left available.

**Comment by brandan-schmitz** [comment]
I uploaded my logs to pastebin: http://pastebin.com/Uwppd5m9

**Comment by nicehashdev** [comment]
Old CPUs without AES are no longer supported in NHM from version 1.7.5.0.

If you wish to use older CPU, you will have to use older version.

**Comment by BaalMcKloud** [comment]
please add a note to the release notes that this cpu's are no longer supported!?
was wondering too about that..
