### ISSUE TITLE
benchmark crash?

### ISSUE THREAD

**Issue by navarrotarro** [nicehash/NiceHashMiner-Archived#619]
hi!
since the update 1.7.4.4 there are some algorithms that doesnt even seem to start( the card is just idle with low power an usage) and stays there endlessly so i disable them.
the two "stuck" algorithm are:

Daggerhashimoto(ethminer)
Cryptonight(sgminer)

i have an 4gb msi rx 480 and i'm a newbie in mining so if i need to config something i will apreciate some guidance

**Comment by navarrotarro** [comment]
.

**Comment by bittachira** [comment]
i have the same issue

**Comment by vince120** [comment]
Same issue here. If I run sgminer or xmr_stak manually from the bin folder, it's ok, but the benchmark doesn't works on those : 
- Cryptonight XMR_STAK
- NeoScript sgminer
- Cryptonight sgminer
- X11Gost sgminer



2x MSI 7970
intel i7-3970x
win7

I tried to change catalyst version as suggested : no change.

I tried setting non zero values on algorithms in benchmark config files : ok for all except sgminer_CryptoNight it runs with an error. So I had to deactivate it

**Comment by bittachira** [comment]
@vince120 i have problems with DaggerHashimoto (etcminer)
CryptoNight (sgminer)
Pascal (sgminer)

X11Gost sgminer working food for me

if i can provide any info that might help you to solve something tell me , newb here

**Comment by Rezobyte** [comment]
I'm having the same issue, but the algorithms not working for me are:
Equihash (both Claymore and Optiminer are broken)
DaggerHashimoto (both sgminer and ethminer are broken)

Driver: 16.11.5 (Recommended for Fiji R9 Nano)
OS: Windows 10 Pro: Fresh install. Only software on my OS is ASUS AI Suite 3, MSI Afterburner and AMD 16.11.5 driver.
GPU: 4x R9 Fury Nano: Sitting idle at 0MHz because the miner is instructing them to mine on the broken algorithms. listed above. Benchmarks also fail outright when run.

I noticed in the mining window it is throwing a warning about using an improper driver, and then closing itself, but I'm using the recommended non re-live driver 16.11.5. I've tried driver version 16.3.2 and 15.12 with no luck with those either.

**Comment by protossdisaster** [comment]
Having the same issue here, I was able to get Dag to bench once, tried downgrading AMD drivers, I have my own post on GitHub my cpu mines. GPU idles when benchmarking. Whats all the ignoring on AMD hardware. This has been a problem the last 4 updates

**Comment by 9600-** [comment]
Same issues since 1.7.4.4
All AMD deployment.

**Comment by vince120** [comment]
issue still present with v1.7.5.1

(using latest or relive ati driver leads to the same issue)

**Comment by kenshirothefist** [comment]
Unfortunately there is a serious lack of decent open-source development for AMD GPU mining software. We're working hard to include the available software, but unfortunately it is hard to configure/detect optimal/working settings for various generations of AMD GPUs. Therefore we made a cleanup of badly supported miners (especially ethminer is problematic and sgminer fore some cases). The https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre version includes these cleanups and should work for majority of users. If you try the **default** enabled miners with **clean configuration** in **latest 1.7.5.2-pre release** it should work on a wide selection of hardware. Let us know there are still issues for you.

**Comment by vince120** [comment]
I tried the prelease 7.

While doing becnhmark, some algorithms (which were previously working) now put "Terminated" as a result and benchmark is no more stuck. 
General.json
`{
  "ConfigFileVersion": {
    "Major": 1,
    "Minor": 7,
    "Build": 5,
    "Revision": 2,
    "MajorRevision": 0,
    "MinorRevision": 2
  },
  "Language": 0,
  "DisplayCurrency": "EUR",
  "DebugConsole": false,
  "BitcoinAddress": "1AX5HPLZSVnafX39iERrT3rjCDxxDs4maS",
  "WorkerName": "PC",
  "ServiceLocation": 0,
  "AutoStartMining": false,
  "HideMiningWindows": false,
  "MinimizeToTray": false,
  "ForceCPUExtension": 0,
  "SwitchMinSecondsFixed": 90,
  "SwitchMinSecondsDynamic": 30,
  "SwitchMinSecondsAMD": 90,
  "SwitchProfitabilityThreshold": 0.02,
  "MinerAPIQueryInterval": 5,
  "MinerRestartDelayMS": 500,
  "BenchmarkTimeLimits": {
    "CPU": [
      10,
      20,
      60
    ],
    "NVIDIA": [
      10,
      20,
      60
    ],
    "AMD": [
      30,
      180,
      240
    ]
  },
  "DeviceDetection": {
    "DisableDetectionAMD": false,
    "DisableDetectionNVIDIA": true
  },
  "DisableAMDTempControl": true,
  "DisableDefaultOptimizations": false,
  "AutoScaleBTCValues": true,
  "StartMiningWhenIdle": false,
  "MinIdleSeconds": 60,
  "LogToFile": true,
  "LogMaxFileSize": 1048576,
  "ShowDriverVersionWarning": true,
  "DisableWindowsErrorReporting": true,
  "NVIDIAP0State": false,
  "ethminerDefaultBlockHeight": 2000000,
  "EthminerDagGenerationType": 0,
  "ApiBindPortPoolStart": 4000,
  "MinimumProfit": 0.0,
  "IdleWhenNoInternetAccess": true,
  "DownloadInit": true,
  "Use3rdPartyMiners": 2,
  "DownloadInit3rdParty": true,
  "AllowMultipleInstances": true,
  "LastDevicesSettup": [
    {
      "Name": "Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz",
      "Enabled": true,
      "UUID": "GEN-ed95de2f6a507558dc802a104e39b2e2b60168424c04899be2eca0912d5b570c"
    },
    {
      "Name": "AMD Radeon R9 200 / HD 7900 Series",
      "Enabled": true,
      "UUID": "PCI_VEN_1002&DEV_6798_15E7D2AB"
    },
    {
      "Name": "AMD Radeon R9 200 / HD 7900 Series",
      "Enabled": true,
      "UUID": "PCI_VEN_1002&DEV_6798_F2959FF"
    }
  ],
  "hwid": "BFEBFBFF000206D7",
  "agreedWithTOS": 2
}`

CPU benchmark json :
`{
  "DeviceUUID": "GEN-ed95de2f6a507558dc802a104e39b2e2b60168424c04899be2eca0912d5b570c",
  "DeviceName": "Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz",
  "AlgorithmSettings": [
    {
      "Name": "XmrStackCPU_CryptoNight",
      "NiceHashID": 22,
      "MinerBaseType": 10,
      "MinerName": "cryptonight",
      "BenchmarkSpeed": 253.7,
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "LessThreads": 2
    }
  ]
}`

First GPU benchmark json
`{
  "DeviceUUID": "PCI_VEN_1002&DEV_6798_15E7D2AB",
  "DeviceName": "AMD Radeon R9 200 / HD 7900 Series",
  "AlgorithmSettings": [
    {
      "Name": "sgminer_DaggerHashimoto",
      "NiceHashID": 20,
      "MinerBaseType": 3,
      "MinerName": "ethash",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": "",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_Decred",
      "NiceHashID": 21,
      "MinerBaseType": 3,
      "MinerName": "decred",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_Lbry",
      "NiceHashID": 23,
      "MinerBaseType": 3,
      "MinerName": "lbry",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_CryptoNight",
      "NiceHashID": 22,
      "MinerBaseType": 3,
      "MinerName": "cryptonight",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_Pascal",
      "NiceHashID": 25,
      "MinerBaseType": 3,
      "MinerName": "pascal",
      "BenchmarkSpeed": 577500000.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_X11Gost",
      "NiceHashID": 26,
      "MinerBaseType": 3,
      "MinerName": "sibcoin-mod",
      "BenchmarkSpeed": 55600.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "ClaymoreAMD_CryptoNight",
      "NiceHashID": 22,
      "MinerBaseType": 7,
      "MinerName": "cryptonight",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": " -a 0 -wd 1 -nofee 0 -li 0 -h 0 -cclock 0 -mclock 0 -powlim 0 -cvddc 0 -mvddc 0   -tt 1 -tstop 0 -fanmax 100 -fanmin 0",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "ClaymoreAMD_Equihash",
      "NiceHashID": 24,
      "MinerBaseType": 7,
      "MinerName": "equihash",
      "BenchmarkSpeed": 219.123333333333,
      "ExtraLaunchParameters": " -a 0 -asm 1 -i 6 -wd 1 -nofee 0 -li 0 -cclock 0 -mclock 0 -powlim 0 -cvddc 0 -mvddc 0   -tt 1 -ttli 85 -tstop 0 -fanmax 100 -fanmin 0",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "ClaymoreAMD_DaggerHashimoto",
      "NiceHashID": 20,
      "MinerBaseType": 7,
      "MinerName": "",
      "BenchmarkSpeed": 13045890.0,
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "OptiminerAMD_Equihash",
      "NiceHashID": 24,
      "MinerBaseType": 8,
      "MinerName": "equihash",
      "BenchmarkSpeed": 248.233,
      "ExtraLaunchParameters": "  --intensity 0  ",
      "Enabled": true,
      "LessThreads": 0
    }
  ]
}`

Second GPU benchmark json :
`{
  "DeviceUUID": "PCI_VEN_1002&DEV_6798_F2959FF",
  "DeviceName": "AMD Radeon R9 200 / HD 7900 Series",
  "AlgorithmSettings": [
    {
      "Name": "sgminer_DaggerHashimoto",
      "NiceHashID": 20,
      "MinerBaseType": 3,
      "MinerName": "ethash",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": "",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_Decred",
      "NiceHashID": 21,
      "MinerBaseType": 3,
      "MinerName": "decred",
      "BenchmarkSpeed": 11000000.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_Lbry",
      "NiceHashID": 23,
      "MinerBaseType": 3,
      "MinerName": "lbry",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_CryptoNight",
      "NiceHashID": 22,
      "MinerBaseType": 3,
      "MinerName": "cryptonight",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_Pascal",
      "NiceHashID": 25,
      "MinerBaseType": 3,
      "MinerName": "pascal",
      "BenchmarkSpeed": 577500000.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "sgminer_X11Gost",
      "NiceHashID": 26,
      "MinerBaseType": 3,
      "MinerName": "sibcoin-mod",
      "BenchmarkSpeed": 2700000.0,
      "ExtraLaunchParameters": " --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --intensity d --xintensity -1 --rawintensity -1 --thread-concurrency -1 --worksize -1 --gpu-threads 1 --lookup-gap -1   --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "ClaymoreAMD_CryptoNight",
      "NiceHashID": 22,
      "MinerBaseType": 7,
      "MinerName": "cryptonight",
      "BenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": " -a 0 -wd 1 -nofee 0 -li 0 -h 0 -cclock 0 -mclock 0 -powlim 0 -cvddc 0 -mvddc 0   -tt 1 -tstop 0 -fanmax 100 -fanmin 0",
      "Enabled": false,
      "LessThreads": 0
    },
    {
      "Name": "ClaymoreAMD_Equihash",
      "NiceHashID": 24,
      "MinerBaseType": 7,
      "MinerName": "equihash",
      "BenchmarkSpeed": 219.123333333333,
      "ExtraLaunchParameters": " -a 0 -asm 1 -i 6 -wd 1 -nofee 0 -li 0 -cclock 0 -mclock 0 -powlim 0 -cvddc 0 -mvddc 0   -tt 1 -ttli 85 -tstop 0 -fanmax 100 -fanmin 0",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "ClaymoreAMD_DaggerHashimoto",
      "NiceHashID": 20,
      "MinerBaseType": 7,
      "MinerName": "",
      "BenchmarkSpeed": 13123440.0,
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "LessThreads": 0
    },
    {
      "Name": "OptiminerAMD_Equihash",
      "NiceHashID": 24,
      "MinerBaseType": 8,
      "MinerName": "equihash",
      "BenchmarkSpeed": 201.228,
      "ExtraLaunchParameters": "  --intensity 0  ",
      "Enabled": true,
      "LessThreads": 0
    }
  ]
}`

PS : you can note that decred worked for only one GPU (which are same reference, same vendor)

If you need other détails (or other tests) let me know.

Thanks

**Comment by kenshirothefist** [comment]
I see these "--gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu"

Please use latest pre-release (was updated) and check the "Disable AMD Temperature Control" under Settings and try to benchmark again the failed benchmarks. If some benchmark is still failing, try Precise benchmark instead for the failed algorithms.

**Comment by vince120** [comment]
It's better, there's only DaggerHashimoto (sgminer) and Crypto Night (sgminer) that fails.

While testing in precise mode, the message is still "Failed - try precise"

Thanks

**Comment by kenshirothefist** [comment]
It seems that sgminer-gm is problematic on your system. This is why we also include Claymore miner so that you have a choice. Unfortunately various miners do behave differently on different systems and it is impossible to provide a completely universal solution. But we're also working on new more robust miners, developed by NiceHash which will hopefully solve issues like these. Until then please try to use only those algorithm-miner combinations that works for you.
