### ISSUE TITLE
ethminer.exe don't starts

### ISSUE THREAD

**Issue by dobcrypto** [nicehash/NiceHashMiner-Archived#62]
![ouxywp1 1](https://cloud.githubusercontent.com/assets/16653151/14137421/6b97bc10-f670-11e5-95b5-ad7616fc84f3.png)

**Comment by theLosers106** [comment]
I will need more information than that.. what OS and GPU are you using?

**Comment by dobcrypto** [comment]
@theLosers106 
OS - Win 7 x64
GPU - GeForce GT 240
I can manually run "geth" if it help.
Or it's course my card "down"?

**Comment by theLosers106** [comment]
GT 240 should not have ethereum enabled on NiceHashMiner.. I'm puzzled.. are you running it manually or through NiceHashMiner?

**Comment by dobcrypto** [comment]
@theLosers106 
Through NiceHashMiner of course and see screen upper, what "ethminer.exe don't start"
I had asked: "ethminer.exe don't starts"
Why? The point is a "weak" card GT 240?

**Comment by theLosers106** [comment]
NiceHashMiner should not even try to run ethminer.exe.. could you screenshot the benchmark window and scroll down to the appropriate part and post it here.. thanks

**Comment by dobcrypto** [comment]
I had download and unpack NiceHashMiner_v1.3.0.1
Run NiceHashMiner.exe and see 2 windows: from issue and NiceHashMiner.
NiceHashMiner works fine, but why does the window of the problem?
![c67q8lo 1](https://cloud.githubusercontent.com/assets/16653151/14149998/909c1756-f6af-11e5-8f65-6e735d4acd40.png)

**Comment by theLosers106** [comment]
Could you try copying msvcr120.dll file from the bin directory into the ethereum directory and see if that fixes your problem..

**Comment by Kipasse** [comment]
I have the same problem when I start nicehashminer. (Etherminer.exe à cessé de fonctionner = don't work" ) I have two R9 280x and windows 7-64.

**Comment by Kipasse** [comment]
Copying msvcr120.dll file from the bin directory into the ethereum directory doesn't fixes the problem.

**Comment by ghost** [comment]
Disable the Detection for Graficcards you dont have. It worked for me after i disabled the detection for nvidia cards because i have amd.

**Comment by Kipasse** [comment]
Hum how do that ?

**Comment by theLosers106** [comment]
I have been able to reproduce this error.. will be fixed in the next release.. for now.. to those users without nVidia5.X GPUs installed, please disable it in the settings.. change it from false to true..

![image](https://cloud.githubusercontent.com/assets/15833762/14213084/a0f0fcba-f868-11e5-9ec1-9548a5ad6329.png)

**Comment by Kipasse** [comment]
Under button Benchmark in nicehashminer app, the button setting ?

**Comment by theLosers106** [comment]
Yup.. the button settings.. make sure to only change that one setting..

**Comment by Kipasse** [comment]
GREAT!!! Thank you very much.

**Comment by dobcrypto** [comment]
@theLosers106 
Thank you.
