### ISSUE TITLE
stratum connection failed when trying to start mining

### ISSUE THREAD

**Issue by srikarjosyam** [nicehash/NiceHashMiner-Archived#620]

**Comment by S74nk0** [comment]
@srikarjosyam please be more specific about your issue... What HW what miner,... issues with vague descriptions will be closed immediately

**Comment by srikarjosyam** [comment]
i am using lenovo z51-70 laptop with amd graphics card and when i am trying to connect to wifi and start mining on my hardware it is showing stratum connection failed

**Comment by S74nk0** [comment]
This looks like a problem on the networking side. Maybe your system time is out of date or you are having issues with your ISP.

This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.

**Comment by mygreeneggsandham** [comment]
I was unable to use ccminer, sig-miner, nicehash or any of the dual miner features from claymore. Heck, I could only mine ethereum on claymore. I tired every setting in my firewall, the routers firewall and forwarding ports left and right. Nothing worked except using a VPN. It seems my useless ISP is blocking all the relevant ports. Using a VPN I can now mine everything. In case you wonder, I am using PIA (Private Internet Access)
