### ISSUE TITLE
1.7.5.0 XMR CPU Crash

### ISSUE THREAD

**Issue by Eyedol-X** [nicehash/NiceHashMiner-Archived#621]
Crashes immediately upon benchmarking

![image](https://cloud.githubusercontent.com/assets/22627805/22934055/362f6d96-f293-11e6-933b-5224ba60d273.png)

**Comment by S74nk0** [comment]
@Eyedol-X the CPU model should be running without a problem. How many threads are set? Can you send the log?

**Comment by grisserg** [comment]
i7-6700
g4400
i5-3350

**Comment by bpvarsity** [comment]
I get this error as well when doing the benchmark. 
![image](https://cloud.githubusercontent.com/assets/2837098/22935043/cd860f62-f296-11e6-9e83-f1858b4d3797.png)

**Comment by bpvarsity** [comment]
See my log in the link below
https://www.mycodebin.com/?26c6cd157f285633#Zb2WApBWPapFFWY1uk5RAs3ALCP5qT2K6zzO96FQcH0=

**Comment by Headhunter1231994** [comment]
I've got the same error. These are my specs if needed

Windows 10
NVDIA ASUS GTX 1070
24 GB RAM 1600 MHZ
AMD FX-8350
Gigabyte 990x Mobo

**Comment by grisserg** [comment]
[2017-02-14 21:38:05] [INFO] [MiningSession] Current device profits:
	Profits for GEN-daf3dc1b4544290bb82a2ed3805e5dccdcb13df67643dbc6c09e71cbba9a0bea (CPU#1 Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz):
		PROFIT = 0.000189328800	(SPEED = 150		| NHSMA = 1262.192)	[XmrStackCPU_CryptoNight]
		MOST PROFITABLE ALGO: XmrStackCPU_CryptoNight, PROFIT: 0.000189328800


[2017-02-14 21:38:05] [INFO] [MiningSession] Current Global profit: 0.19177493 USD/Day
[2017-02-14 21:38:05] [INFO] [MiningSession] Current Global profit: IS PROFITABLE MinProfit mine always regardless of profit
[2017-02-14 21:38:05] [INFO] [XmrStackCPUMiner-MINER_ID(3)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
[2017-02-14 21:38:06] [INFO] [XmrStackCPUMiner-MINER_ID(3)-DEVICE_IDs(0)] Starting miner [pid(13896)|bin(bin\xmr-stak-cpu\xmr-stak-cpu.exe)] config.txt
[2017-02-14 21:38:06] [INFO] [XmrStackCPUMiner-MINER_ID(3)-DEVICE_IDs(0)] [pid(13896)|bin(bin\xmr-stak-cpu\xmr-stak-cpu.exe)] Starting cooldown checker
[2017-02-14 21:38:06] [INFO] [XmrStackCPUMiner-MINER_ID(3)-DEVICE_IDs(0)] [pid(13896)|bin(bin\xmr-stak-cpu\xmr-stak-cpu.exe)] Miner_Exited Will restart in 5000 ms
[2017-02-14 21:38:07] [INFO] [XmrStackCPUMiner-MINER_ID(3)-DEVICE_IDs(0)] [pid(13896)|bin(bin\xmr-stak-cpu\xmr-stak-cpu.exe)] GetAPIData reason: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:4001
[2017-02-14 21:38:07] [INFO] [XmrStackCPUMiner-MINER_ID(3)-DEVICE_IDs(0)] [pid(13896)|bin(bin\xmr-stak-cpu\xmr-stak-cpu.exe)] summary is null
[2017-02-14 21:38:07] [INFO] [XmrStackCPUMiner-MINER_ID(3)-DEVICE_IDs(0)] GetSummary returned null..

**Comment by Eyedol-X** [comment]
Same issue as above on another rig with a i7-4770K CPU

I'm running with default configuration(s) I haven't manually set any threads. I will try to manually set threads as a workaround.

**Comment by giosal** [comment]
benchmark just fails with no error whatsoever.
ASUS N550JK laptop with Intel Core i7-4700HQ 4x2.4GHz (8 threads up to 3.2 GHz boost) with Windows 10 x64
**UPDATE**
laptop becomes unresponsive several times for couple of seconds during benchmark.
after benchamrk it says "none" in hashrate field
**UPDATE 2**
same applies for my Desktop PC with:
ASUS Sabertooth 990FX R2.0
AMD FX-8150 8x3.6 GHz (up to 4.0 GHz boost)
Windows 10 x64
**UPDATE 3**
launching miner separately works perfectly

**Comment by leshiy-gr** [comment]
I've got the same error (Crashes immediately upon benchmarking, cpu, xmr).
Win7 x64, CPU Intel i5-3570K

**Comment by CreamyG31337** [comment]
crashes on Intel Xeon E5 v2, I assume this should be supported because it's Ivy Bridge and CPU-Z shows support for AES instructions. 
Also crashes on Intel Core i7 2720QM Sandy Bridge with AES.
Works fine on my AMD 8350 and i7-4702HQ
i7-3517U without AES support doesn't show up and doesn't try to run, as expected.

**Comment by Junior88** [comment]
crashing on Intel E5-2620v1

**Comment by zette** [comment]
For me not mining on AMD Opterons 4332 and  Intel Xeon E3 1220 v2. Both CPUs with AES and up. 

**Upgraded system dlls to match instruction on xmr-stak-cpu github, because the bundled crashed miner just upon start with 0xc000007b.**

Bug already filled with xmr-stak-cpu: https://github.com/fireice-uk/xmr-stak-cpu/issues/13

PS: on both Opteron and Xeon platform only half of cores is detected and added to miner config file!!!

**Comment by Blackwing215** [comment]
win10 x64 i5 6500 - just doesn't start mining (benchmark without result, but says "ok")

**Comment by blorbo** [comment]
Have\had similar issues to the ones reported here, though managed to get it working by setting the miner settings manually in the NiceHashMiner\bin\xmr-stak-cpu\config.txt setting the file to write protected, needs to be set to protected so that NHM(NiceHashMiner) can't rewrite the file with default settings; and entering a benchmark number manually in the NHM settings since the NHM requires it for it to start mining.
This won't solve the benchmarking issues but it will allow NHM to run the miner without issues.

**Comment by zette** [comment]
I've been able to get past `MEMORY INIT ERROR: Obtaning SeLockMemoryPrivilege failed` and `MEMORY ALLOC FAILED: VirtualAlloc failed.` by adding the 'Lock pages' right to Administrator user AND running manually the xmr-stak-cpu miner as Administrator. 

It is still not running with the NiceHash GUI, and what is more important **all results are rejected**:
```Top 10 best results found:
|  0 |                0 |  1 |                0 |
|  2 |                0 |  3 |                0 |
|  4 |                0 |  5 |                0 |
|  6 |                0 |  7 |                0 |
|  8 |                0 |  9 |                0 |

Error details:
| Count | Error text                       | Last seen           |
|    19 | Invalid nonce; is miner not comp | 2017-02-14 20:08:52 |
```

**Comment by blorbo** [comment]
@zette confirm that you got "nicehash_nonce": true

**Comment by zette** [comment]
Yes, see my config below:
```

  "cpu_thread_num": 12,
  "cpu_threads_conf": [
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 0
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 1
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 2
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 3
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 4
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 5
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 6
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 7
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 8
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 9
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 10
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 11
    }
  ],
  "use_slow_memory": "warn",
  "nicehash_nonce": true,
  "pool_address": "cryptonight.eu.nicehash.com:3355",
  "wallet_address": "here_goes_wallet_generated_by_nicehash",
  "pool_password": "x",
  "call_timeout": 10,
  "retry_time": 10,
  "verbose_level": 5,
  "h_print_time": 60,
  "httpd_port": 4001,
  "prefer_ipv4": true
```

**Comment by zette** [comment]
Now it automagically started to mine without errors.

**Comment by Headhunter1231994** [comment]
What did you do to fix it? Still does not work over here...



On Tue, Feb 14, 2017 at 8:31 PM +0100, "zet te" <notifications@github.com<mailto:notifications@github.com>> wrote:


Now it automagically started to mine without errors.

**Comment by zette** [comment]
Not a thing. Just restarted worker process.

**Comment by Headhunter1231994** [comment]
Weird just wait for a patch Then

Outlook voor Android<https://aka.ms/ghei36> downloaden



On Tue, Feb 14, 2017 at 9:17 PM +0100, "zet te" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not a thing. Just restarted worker process.

**Comment by giosal** [comment]
I would like to also note that new CPU miner makes PC hang a lot, it's much slower, even with less threads 1; also, it makes GPU mining on AMD R9 290 much slower, around 5% of max capacity
In my opinion it would be great to give the choice between new miner and old one (cpuminer)

**Comment by giosal** [comment]
**UPDATE**
Did work on Intel Xeon CPU (Haswell, no TSX)
Both benchmark and mining work.
But it shows MEMORY ALLOC FAILED despite the fact that the Lock Memory policies are set and both NHM and star miner are run as administrator
**UPDATE 2**
MEMORY ALLOC FAILED problem solved by adding user and group "Everyone" to lock memory policies and restarting PC

**Comment by fireice-uk** [comment]
Hi all

0xc000007b -> this error is caused by the lack of visual studio libc dlls - see this link https://github.com/fireice-uk/xmr-stak-cpu/releases

MEMORY ALLOC FAILED can be caused by memory fragmentation (Windows is very bad at that) - you need to reboot if you configured permissions correctly

**Comment by giosal** [comment]
@fireice-uk thx for confirming. as I said, the error which was initially reported in this issue can be fixed by downloading and installing Visual Studio 2015 Redistributable.
MEMORY ALLOC FAILED is fixed specifically by adding your username, Administrator and group Everyone to Lock Policies

**Comment by fireice-uk** [comment]
@zette proximal cause for your problem might be a large number of cores - this really squeezes the nonce space given that we are limited to 3 bytes
If you manage to narrow it down more, please feel free to open a ticket on my repo, please make sure you can reproduce the issue while starting the miner manually.

**Comment by CreamyG31337** [comment]
I dunno why but adding my user, group everyone & rebooting is not enough to let it lock memory pages in win10. Everything was running under my account, which is an administrator. But then I ran NHM as administrator and it works fine (after adding administrator to the policy too). Setting compatibility settings to do this automatically is a good solution for me.

**Comment by fireice-uk** [comment]
On Windows it isn't enough for a user to have admin rights, you need to pass the UAC prompt to actually have them.

**Comment by bpvarsity** [comment]
@fireice-uk Even with clicking yes on the UAC prompt or disabling UAC all together does not fix the crash/issue.

**Comment by fireice-uk** [comment]
@bpvarsity please confirm that you followed the steps in the readme.

**Comment by bpvarsity** [comment]
@fireice-uk of course I have. Doesn't make any difference on either of my windows pc's. Benchmark still fails for XMR.

**Comment by fireice-uk** [comment]
@bpvarsity  what did you set SeLockMemoryPrivilege to? Can you post the output of a manually ran miner?

**Comment by bpvarsity** [comment]
I reinstalled Visual Basic and rebooted. Seems to have fixed my crash.

**Comment by fireice-uk** [comment]
@bpvarsity that would suggest some kind of problem inside nicehash - the miner is written in c++ not basic.

**Comment by zoro1** [comment]
This new XMR CPU miner is awfull. A user should not have to dig into policies in order to mine properly!
I am using the old CPU cryptonight algo inside 1.7.4.5. 
Very bad choice nicehash!

**Comment by giosal** [comment]
@zoro1 i already asked @nicehashdev to return the choice of miner.
the new miner is about 10-20% faster depending on the system, but it needs a lot of configuration...

**Comment by nicehashdev** [comment]
Fixed in latests version.
