### ISSUE TITLE
XMR crash with Nicehash version 1.7.5.0

### ISSUE THREAD

**Issue by Headhunter1231994** [nicehash/NiceHashMiner-Archived#622]
Here are my specs:

Windows 10
NVDIA ASUS GTX 1070
24 GB RAM 1600 MHZ
AMD FX-8350
Gigabyte 990x Mobo

When benchmarking I get this error for XMR 
![nicehash error](https://cloud.githubusercontent.com/assets/25772604/22934610/da2d51ba-f2cf-11e6-9b24-662eed6db048.PNG)

Any ideas?

**Comment by bpvarsity** [comment]
duplicate issue. See #621

**Comment by Junior88** [comment]
same issue here. 
Win 10
GTX 1060 
16GB RAM
E5-2620v1

**Comment by S74nk0** [comment]
duplicate (https://github.com/nicehash/NiceHashMiner/issues/621)
