### ISSUE TITLE
SM6.x neoscrypt removed in 1.7.5.0, updated ccminer available

### ISSUE THREAD

**Issue by jsmcconn** [nicehash/NiceHashMiner-Archived#623]
The ccminer binary available here has updated neoscrypt for pascal GPUs:

http://cryptomining-blog.com/8117-windows-binary-of-the-ccminer-1-7-6-r10-fork-with-fixed-neoscrypt-performance-on-pascal/

**Comment by S74nk0** [comment]
@jsmcconn We won't be adding this miner in the next release. But we will be adding an improved NVIDIA neoscrypt in one of the future releases.
