### ISSUE TITLE
X11-Gost ccminer infinite restarts

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner-Archived#624]
Benchmark completed successfully, but miner never starts mining, just infinitely restarts
ASUS GeForce GTX680 2GB

**Comment by giosal** [comment]
Issue was caused by new XMR CPU miner it seems, without it, this miner works perfectly,
so should be merged with issue #621

**Comment by S74nk0** [comment]
[Pre-Release2](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.2-pre/NiceHashMiner_v1.7.5.2_PreRelease_2.zip) has all XMR issues resolved.
