### ISSUE TITLE
Dagger not showing on Web

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#625]
Using NHM 1.7.4.5 with MSI RX480 4GB

![dagger](https://cloud.githubusercontent.com/assets/24593637/22939691/9eb6a106-f2f0-11e6-9404-cbdf491c0423.png)

**Comment by realhagie** [comment]
Found the same problem with 1.7.4.5 (1.7.5.0 crashes in banchmark)

If I enter the same command line as in the debug window the statistics appear in the web.

regards

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/678). 
Closing...
