### ISSUE TITLE
X11Gost Parameters

### ISSUE THREAD

**Issue by Kimax89** [nicehash/NiceHashMiner-Archived#626]
I dont think that the parameters for X11Gost is getting through properly.

For instance, my intensity is at 16 for both my R9 280X and my RX 480, but when the miner starts, the intensity has changed.

6 on my R9 280X and 15 on my RX 480

When i change the intensity inside the miner, i get way better results.

**Comment by S74nk0** [comment]
@Kimax89 from the logs it will be clear what parameters are being passed. Post logs so we can see what is going on.

**Comment by Kimax89** [comment]
For some reasson, this is no longer a problem in the 1.7.5.1
