### ISSUE TITLE
1.7.5 Crashing after 30 sec

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#628]
Windows 10
AMD 17.1.2 (Non WHQL drivers just make a constant system reset)
2 x Nitro+ 480 4g
4 x Asus 470 4g
MB: Asus z87 pro V

I can mine equihash only no problem. How ever when i mine it simultaneously with pascal (480s mine pascal) i can hear my fans spinning up temperatures on 2 of the 470s go up to 75, fan speed @ 1700 and the system imminently restarts it self...What can i do? Log attached
[log.txt](https://github.com/nicehash/NiceHashMiner/files/775221/log.txt)

**Comment by Johann1982** [comment]
I had to disable Pascal on my AMD rig also. I suspect there is a bug. You can also try using version 16.11.5 as that is the recommended AMD driver.
What size power supply do you use? Those 6x cards will draw a lot of power. Equihash uses the least amount of power.

**Comment by undefy** [comment]
Well i rearranged my power supplies. i have an xstrike 1100 watt and deepcool 750 watt all gold rated. Stuck the 2 480 on deepcool. That solved the problem for a while.

**Comment by kenshirothefist** [comment]
You must make sure that you have **checked** the option "Disable AMD Temperature Control" under **Settings**. Also, make sure you use some 3rd party software like **MSI Afterburner** to set a fixed fan speed (at least 80%, or even 90% if you have inadequate cooling).
