### ISSUE TITLE
NiceHash Miner v1.7.5.0  unable to find my cpu 

### ISSUE THREAD

**Issue by azizhamad04** [nicehash/NiceHashMiner-Archived#630]
NiceHash Miner v1.7.5.0  unable to find my cpu

**Comment by giosal** [comment]
details ,please, as in model of cpu

**Comment by azizhamad04** [comment]
CPU: Intel(R) Pentium(R) Dual  CPU  E2200  @ 2.20GHz

**Comment by giosal** [comment]
[http://ark.intel.com/products/33925/Intel-Pentium-Processor-E2200-1M-Cache-2_20-GHz-800-MHz-FSB](url)

> Intel® AES New Instructions 
> No

It doesn't support AES-NI, hence with this version you won't be able to mine on it.
See release notes:
[https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.0](url)

> **UPDATE!!! Please note that CPUs without AES-NI extension are no longer supported.**

**Comment by giosal** [comment]
I already posted to give the choice of miner for CPU in order to use old one.
Meanwhile, if mining also on GPU I'd suggest you disable CPU in NHM and laucnh cpuminer separately from bin folder of previous version of NHM

**Comment by nicehashdev** [comment]
This CPU not supported. Closing.

**Comment by Marcos2388** [comment]
Hello, I have a simple question, why does not my cpu appear when it's time to start mining? I use the latest version and also the older one, could you help me?
