### ISSUE TITLE
1.7.5.0 multi-CPU XMR

### ISSUE THREAD

**Issue by fuzzfuzz** [nicehash/NiceHashMiner-Archived#632]
hi guys,
hats off to you for constantly improving mining! great fun for us all.
One issue with new 1.7.5.0 and XMR miner is that it doesn't affine to multi-CPU systems. If I run it from NHM, two CPUs are detected, two miners start, but both mine at half speed.
As an example, I have a Xeon E5640 Westmere * 2 system, 12M cache each. If I run 6 threads I crunch at about 190H/s on one CPU. If I run 6 threads and select 2nd CPU as well both drop to 90H/s and task manager shows similar CPU usage. ~40%.
I haven't tried fiddling with configs or anything but from reading XMR config.txt file it seems maybe only affinity to individual core is supported? i.e. hyperthreading...

Thanks for reading! :)

**Comment by CreamyG31337** [comment]
well, do try fiddling with the configs. on my 8 core cpu it's defaulted to 4 less threads. you can change it in the algo settings.

**Comment by fuzzfuzz** [comment]
yes, and I have done that as the Westmere has 12M of cache, so less threads on both is set to 2, for 6 cores crunching.
That is not the issue. The issue seems to be that both copies of running XMR miner are bound to CPU 0, not CPU 0 CPU 1.

**Comment by CreamyG31337** [comment]
oh, yeah i can confirm this issue now on my xeon box. I get 50% CPU usage and the same hash rate if I enable or disable the 2nd CPU in the GUI. It's actually a virtual 12-core single CPU VMWare instance, not sure why NHM thinks it's 2 CPUs anyways. It's only allocating 6 threads now.

**Comment by CreamyG31337** [comment]
if you want you can just make the config.txt readonly, double the threads and stuff and it will run fine until they patch this. working for me, at least.

**Comment by nightmaker** [comment]
Firstly, kudos to the new miner which is slightly faster than the previous!

I am also confirming that there is a problem with multi-CPU. I have 2 x Xeon X5675 (6 cores, 12 threads each) in my rig. NHM detects both CPU (which is good). When mining with 6 threads with CPU0 only, I manage to get 220-240H/s. However when I enable both CPU0 and CPU1 with 6 threads each, the hashrate will be halved for each CPU. Each CPU0 and CPU1 will get only around 100-120H/s.

I managed to get a temporary workaround of this problem. While running NHM with 2 CPU, I have to manually Set Affinity to each xmr-stak-cpu.exe process from Task Manager (on Processes tab). One xmr-stak-cpu.exe to CPU0 (Node 0) until CPU11 (Node 0), the other one xmr-stak-cpu.exe to CPU 0 (Node 1) until CPU11 (Node 1). After configuring this, both CPU's hashrate will come up to the higher number (200-240H/s) each.

This confirms that when running multiple CPU on NHM 1.7.5, NHM will only asssign all threads to CPU0.

**Comment by Headhunter1231994** [comment]
Can someone explain to me in noobie language how to get my speed back up? With the new xmr miner I am only getting 120/150 h/s while with the old miner I had 200/240 h/s I use a AMD FX-8350

**Comment by nightmaker** [comment]
how about configuring higher Less Thread so that it will utilize lesser
cores? How will that affects?

**Comment by giosal** [comment]
The miner is using only one CPU on multi-CPU systems,
I have 2 CPUs, each with 32 cores. It uses only first CPU and not the second.
Logically, NHM doesn't pass number of CPU correctly to miner

**Comment by Headhunter1231994** [comment]
So it's just the way it is then? Or will it be fixed in the future?



On Wed, Feb 15, 2017 at 11:04 PM +0100, "giosal" <notifications@github.com<mailto:notifications@github.com>> wrote:


The miner is using only one CPU on multi-CPU systems,
I have 2 CPUs, each with 32 cores. It uses only first CPU and not the second.
Logically, NHM doesn't pass number of CPU correctly to miner

**Comment by CreamyG31337** [comment]
headhunter, you don't even have 2 cpus. just go fix the number of threads in the settings. put it to 0 or 1, not 4. 
![image](https://cloud.githubusercontent.com/assets/11222932/22998327/78d9e0f8-f393-11e6-9c63-9da5e8c9880d.png)

**Comment by fuzzfuzz** [comment]
Hi guys,
looks like 1.7.5.1 has made this particular issue worse.
Now the miner performs affinity still to single CPU but affines to non-hyperthreaded cores. In my example, I have 2 Westmere E5640 CPUs, which have 8 threads each (2 sockets * 4 cores * hyperthreaded) for total of 16 threads.
In 1.7.5.0, the miner was configured with less threads=2 as the E5640 has 12M cache, and crunched with 6 threads. The issue was that miner tried to set two running instance of 6 threads to the one CPU.
In 1.7.5.1, the miner seems to still treat both CPU as one, but also affines to non-hyperthreaded cores, meaning that the lessthreads=2 now has the effect of miner only mining with 3 threads out of 8, instead of 6. Confused? :) I know I am... it's really hard to explain and I cannot post screenshots at the moment.
In any event, I will go back to 1.7.5.0 for now as Nightmaker's workaround does work - Once miner starts and launches both miners to CPU 0, you can force second copy of it to CPU 1 and full speed then ensues.
I would be really interested to see how others with hyperthreaded CPUs work - I don't have an i7 to test with, just Xeons. :D

**Comment by giosal** [comment]
I concurr, I have Intel Core i7-4700HQ with 4 cores and 8 threads ands setting less threads to 1 leads to miner using only 3 threads.
it seems it's affines to physical cores and not threads on Hyperthreading enabled CPUs.
and setting less threads to 0 leads to using only 4 threads.
```
[2017-02-19 03:14:30] : Starting single thread, affinity: 0.
[2017-02-19 03:14:30] : Starting single thread, affinity: 2.
[2017-02-19 03:14:30] : Starting single thread, affinity: 4.
[2017-02-19 03:14:30] : Starting single thread, affinity: 6.
```
this is output of miner when using less threads 0
and this is with only ONE physical CPU

**Comment by S74nk0** [comment]
This will be fixed with the upcoming release. Keep open until new release.
The default optimizations have been also changed so it will be best to repeat the benchmark to work with new settings

**Comment by S74nk0** [comment]
Try the [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre). Report if this is fixed.

**Comment by S74nk0** [comment]
[Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre) and the next official release will include a fix. Closing ...
