### ISSUE TITLE
1.7.5 error with CPU that support AES-NI

### ISSUE THREAD

**Issue by Sammael** [nicehash/NiceHashMiner-Archived#633]
All of this CPUs support AES-NI
windows server 2008 r2 x64
![1](https://cloud.githubusercontent.com/assets/6249562/22967326/1338c4c4-f377-11e6-943a-8d5328c98155.png)
windows server 2008 r2 x64
![2](https://cloud.githubusercontent.com/assets/6249562/22967355/316358ce-f377-11e6-94ee-77d5142f8228.png)
windows 10 x64
![3](https://cloud.githubusercontent.com/assets/6249562/22967395/53511a02-f377-11e6-8c91-48e7d21da354.png)

**Comment by giosal** [comment]
Install Microsoft Visual Studio 2015 Redistributable, both 32 and 64 bit versions

**Comment by Sammael** [comment]
it hasn't solved a problem

**Comment by giosal** [comment]
Try reinstalling DirectX Redist package.
Also, try running NHM as Administrator

**Comment by Sammael** [comment]
"Try reinstalling DirectX Redist package." - seriously? ))) What else you will advise? Maybe I need to update the driver for CPU? Does anybody have the latest driver for I5?

**Comment by giosal** [comment]
Seriously :-)
After doing some research that's what I stumbled upon. They recommend you reinstall Visual Studio Redist, DirectX redist and launch as admin

**Comment by Sammael** [comment]
No, it's not right, I'm just going to use the old version of NHM

**Comment by fuzzfuzz** [comment]
the 7b error is definitely missing Visual C++ (not Visual Studio) 2015 redistributable 64-bit.

**Comment by Sammael** [comment]
probably a required dll files are in Visual C++ and Visual Studio, because I install Visual Studio and this solved the problem 7b. But main problem is that NHM 1.7.5.0 not see CPU...

**Comment by nightmaker** [comment]
I solved this issue with these steps:
1) Install Visual C++ Redistributable for Visual Studio 2015 from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145).
2) Enable Lock Pages in Memory. See instructions [here](https://msdn.microsoft.com/en-gb/library/ms190730.aspx).
3) Reboot.

If problem persist, please check if your CPU support AES instruction or not. If not, you may need to revert to previous version of NHM.

**Comment by Sammael** [comment]
No, it didn't help. Yes, my CPU's support AES-NI

**Comment by nicehashdev** [comment]
This error will be fixed in next version we are about to release.

**Comment by pifagor2** [comment]
Same problem with 3570K. Have to use old NHM version :)
