### ISSUE TITLE
1.7.5.0 Cryptonight won't bench.

### ISSUE THREAD

**Issue by DarkTrollCoin** [nicehash/NiceHashMiner-Archived#634]
Cryptonight (XmrStakCpu) won't bench on a i-5 6600K @ 4.4 Ghz.
Benchmark launches and finish with no error and no results.

I tried reseting Cpu clocks to defaut but it won't bench either.

Here is the log about it : 

[2017-02-14 15:46:11] [INFO] [XmrStackCPUMiner-MINER_ID(0)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
[2017-02-14 15:46:11] [INFO] [BENCHMARK] Benchmark starts
[2017-02-14 15:46:11] [INFO] [XmrStackCPUMiner-MINER_ID(0)-DEVICE_IDs(0)] Starting benchmark: benchmark_mode config.txt
[2017-02-14 15:46:11] [INFO] [XmrStackCPUMiner-MINER_ID(0)-DEVICE_IDs(0)] Using miner: bin\xmr-stak-cpu\xmr-stak-cpu.exe
[2017-02-14 15:47:11] [INFO] [BENCHMARK] Final Speed: 0.000 H/s 
[2017-02-14 15:47:11] [INFO] [BENCHMARK] Benchmark ends

**Comment by ghost** [comment]
FX-8350 will NOT benchmark.

**Comment by ghost** [comment]
i5-4690K will NOT benchmark.
BTW, on the shortcut to launch NHM I selected Advanced/Run as Administrator.

**Comment by Iamzelok** [comment]
i guess out of the log that i have to create a benchmark_mode config.txt i'll give a try...

**Comment by Sammael** [comment]
same problem with i5-3470, i5-4460, i5-4570
https://github.com/nicehash/NiceHashMiner/issues/633

**Comment by nightmaker** [comment]
I solved this issue with these steps:
1) Install Visual C++ Redistributable for Visual Studio 2015 from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145).
2) Enable Lock Pages in Memory. See instructions [here](https://msdn.microsoft.com/en-gb/library/ms190730.aspx).
3) Reboot.

**Comment by DarkTrollCoin** [comment]
i already have a newer version of Visual C++ Redistributable for Visual Studio 2015 installed (14.0.24215.0)
i have activated Locked pages in memory since first version of EQM in NHM.

**Comment by nicehashdev** [comment]
Fixed in latests version.

**Comment by DarkTrollCoin** [comment]
still not fixed with latest

**Comment by pifagor2** [comment]
Same problem with 3570K. Have to use old NHM version :)

**Comment by Sammael** [comment]
no, not fixed ((
