### ISSUE TITLE
xmr-stak-cpu +AMD Cryptonight (Claymore)

### ISSUE THREAD

**Issue by grisserg** [nicehash/NiceHashMiner-Archived#636]
AMD  R480  Cryptonight (Claymore) =790 h/s
I run xmr-stak-cpu and R480 goes to 0 h/s
I close the program and all recovered... R480  Cryptonight (Claymore) =790 h/s

**Comment by giosal** [comment]
+1
same applies to all GPUs
I have two systems:
CPU + NVIDIA GeForce GTX680 + AMD Radeon R9 290x
CPU + NVIDIA GeForce GTX850M
on both systems with xmr-stak-cpu miner on (only if launched via NHM interface) all GPUs work at about 0-5% of capacity
Though if launched separately from bat file, it works ok

**Comment by nicehashdev** [comment]
"Though if launched separately from bat file, it works ok"

Are you sure you launch with exactly same extra launch params?

What if you let some threads free (not load CPU 100%?)

**Comment by giosal** [comment]
@nicehashdev on the first system with two GPUs - with less threads 1 or 2 it's same story (with 8 MB L3 cache)
on second system it did help (with 6 MB L3 cache)
both systems have 8 thread CPU

**Comment by S74nk0** [comment]
The issue is probably caused due to XMR incorrect settup by NHM. Try the [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre). Report if this is fixed.
