### ISSUE TITLE
1.7.5.0 1070 no CryptoNight Algo

### ISSUE THREAD

**Issue by frazier345** [nicehash/NiceHashMiner-Archived#637]
I have 5 750ti and 1 1070 on a rig. And the 1070 is missing CryptoNight (CCminer) on the benchmark screen, I tried to see if I could add it but I couldn't figure out where in the instructions to change it.

**Comment by S74nk0** [comment]
@frazier345 it will be re-introduced with a more stable miner. 
[Here](https://github.com/nicehash/NiceHashMiner/commit/188505538cc517b3230699b40aad1e870ab7ad33#diff-b80b912346495625d8c1384f2d0ea0c0R233) is the **if** block when removed it will have **CryptoNight** support.
