### ISSUE TITLE
1.7.5.0 doesn't detect NVIDIA Tesla K80

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner-Archived#638]
see title
Only shows CPUs
Driver: 376.33
CUDA toolkit: 8.0

**Comment by giosal** [comment]
now it gets stuck on detecting AMD devices, though there is none...

**Comment by keztheminer** [comment]
i'm sure this will be fixed soon its an nvidia issue , quick devs run  and fix for them

**Comment by giosal** [comment]
when launched separately, ccminers are running perfectly

**Comment by nicehashdev** [comment]
NiceHashMiner does not officially support non-desktop video cards.
