### ISSUE TITLE
Low hasrate new XMR miner

### ISSUE THREAD

**Issue by Headhunter1231994** [nicehash/NiceHashMiner-Archived#639]
Hi,

I've got issues with the new XMR miner (Nicehash version 1.7.5.0) at one point it reaches 200 kh/s and after a while drops to 120. With 1.7.4.5 It stays steady around 200/260 kh/ s any ideas? I use a AMD FX-8350

**Comment by giosal** [comment]
Hi

Go to settings and click on your CPU, then Cryptonight and in the field Less Threads (to the right) put 0

**Comment by TheXev** [comment]
Yeah, that threads setting is very odd.  When I set it to 3 (like I would in XMR's config.txt), it only uses one thread.  Settings to 2 uses 3 threads (which on my i5-6600k, is the correct setting). O_o

**Comment by Headhunter1231994** [comment]
Thanks! That helped a lot. It now stays within the 200 range. It can't reach 220 h/s though. Any other setting I can fine tune? Thanks for the help so far!



On Wed, Feb 15, 2017 at 11:56 PM +0100, "giosal" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

Go to settings and click on your CPU, then Cryptonight and in the field Less Threads (to the right) put 0
