### ISSUE TITLE
EWBF's CUDA Zcash miner - Adding?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#640]

**Comment by nicehashdev** [comment]
There is no reason to add miner that is no faster than ours plus having additional fee, which means you would be actually earning less than with EQM.

Besides, it has been prooved that EWBF copied all ideas out of EQM.

**Comment by Chugumoto** [comment]
but on my 1080ti EWBF 0.3.3b 5-10% faster than EQM or excavator... that even with a 2% commission is more profitable

**Comment by GTANAdam** [comment]
You might wanna take a look at https://github.com/GTANAdam/NiceHashMiner/releases/tag/1.7.5.13-pre
It adds EWBF miner support
Hope that helps a lot of you now.

**Comment by msbarnum** [comment]
GTANAdam, how does one configure that?  I would like to try it out as ewbf bumps me up to 533 from 470...
