### ISSUE TITLE
Averaged speeds are causing less profitable combinations to be chosen

### ISSUE THREAD

**Issue by DillonN** [nicehash/NiceHashMiner-Archived#641]
Not sure exactly the purpose of the average speeds system that was activated in commit 09c61ee93d9458f30f8deaa7966208adb38daa1b, but it seems to be causing NHM to select less profitable mining combos when two identical GPUs are used.

Both my 290Xs come up with the same name, but one (thermal reasons) gets much less performance in power hungry algos. So one can get 30MH/s in eth but the other only 24. However this averager sets both of them as getting 27MH/s, and as a result it will only activate miners when the overall average is most profitable. This is detrimental because the slower GPU can mine equihash at practically full speeds, and usually the most profitable choice would be eq on one and eth on the other, but this is never realized.

This is easily fixed by changing the AveragerGroup dictionary keys to device UUID instead of name (so they are separated), but as I don't know what Averager is meant to do in the first place I'm not sure if this breaks anything else.

**Comment by S74nk0** [comment]
@DillonN the average is calculated to increase stability. There were many reports when same GPUs were running different algorithms/miners and this has caused problems (driver hangs, OS freeze, restarts,...). It is true that in your case this will degrade profitability (you can workaround by disabling eth for the slower GPU), but the main and only reason for averaging speeds is that the performance differences aren't that big (like in your case, an exception), and having a more stable miner was more desirable than a potentially unstable and breaking miner where one could earn 0.00000001 BTC/Day more on avarage, with a greater chance of freezing the OS. Now in the case of two GPUs it may not brake as often or at all like with a 6-GPU setup, so to workaround this you can disable ethminer with the slower GPU and it will mine **equihash**.

I hope this helps. 
Closing issue...

**Comment by DillonN** [comment]
Ah ok, that makes sense then. Thanks for letting me know what it's for, I'll do the workaround
