### ISSUE TITLE
CPU performance tanked after update

### ISSUE THREAD

**Issue by mavericknoob** [nicehash/NiceHashMiner-Archived#644]
Updated to 1.7.5.0 from 1.7.4.5 and lost ~100 Hashes per second for CPU hashing.
CPU is AMD FX-8350, LOCKED PAGES is and has been enabled in OS.
1.7.4.5
![1 7 4 5](https://cloud.githubusercontent.com/assets/20135196/23027283/a5d8e664-f418-11e6-9c03-c7f068bdca85.jpg)

1.7.5.0
![1 7 5 0](https://cloud.githubusercontent.com/assets/20135196/23027308/b8dbee8c-f418-11e6-8693-6ceeee21b699.jpg)

**Comment by keztheminer** [comment]
no 1 here cares but the amd lot , you're on amd so it  will never be sorted or solved . sorry the truth hurts but nicehash is not amd friendly no more every update makes it worse

**Comment by Headhunter1231994** [comment]
It's simple, click on settings device/algorithm. select your processor click on the algorithm then look at the right side and change lessthreads to 0 or 1
![help](https://cloud.githubusercontent.com/assets/25772604/23028003/5bdb3f78-f466-11e6-9403-09253ec49818.PNG)

**Comment by mavericknoob** [comment]
Thank you, Headhunter1231994. I'm now seeing better performance than before the update.
![1 7 5 0_1](https://cloud.githubusercontent.com/assets/20135196/23028834/5bc9e7b2-f41d-11e6-94e8-de241f057a1c.jpg)

**Comment by Headhunter1231994** [comment]
which setting do you use? I've got the same processor mine is just 200 h/s

**Comment by mavericknoob** [comment]
Lessthreads 1, and the CPU is running at 4.6 Ghz. BTW, looks like I was wrong about locked pages, I'd had it set up for admins, and was not working, until I started running Nicehash as Admin.
![1 7 5 0_2](https://cloud.githubusercontent.com/assets/20135196/23030007/3e61a26a-f421-11e6-8823-733d90d2b2a6.jpg)
![cpu-z](https://cloud.githubusercontent.com/assets/20135196/23030098/941d3ce6-f421-11e6-9017-0bf15cb37701.jpg)
