### ISSUE TITLE
CPU wont work ? :(

### ISSUE THREAD

**Issue by LeVeloute** [nicehash/NiceHashMiner-Archived#645]
Hi ! 
My CPU is : i7 6700HQ @2.60GHz
When i start benchmark, he do the benchmark, and after, i can't start the mining, he ask me to select a device ( i select my CPU, click start again ) and he ask me to do the benchmark again :( And its an infinity loop :(
How to fix it ? Thx :) I use the version of Nice Hash v1.7.5.0
Sorry for my bad English :)

**Comment by Sammael** [comment]
https://github.com/nicehash/NiceHashMiner/issues/633
how to fix? wait for new version or use older

**Comment by LeVeloute** [comment]
Okay thx u :) Where can i download older version ?

**Comment by Sammael** [comment]
https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.5

**Comment by nightmaker** [comment]
I solved this issue with these steps:
1) Install Visual C++ Redistributable for Visual Studio 2015 from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145).
2) Enable Lock Pages in Memory. See instructions [here](https://msdn.microsoft.com/en-gb/library/ms190730.aspx).
3) Reboot.

**Comment by nicehashdev** [comment]
Fixed in latests version.
