### ISSUE TITLE
p0 state needs administrator permission

### ISSUE THREAD

**Issue by CreamyG31337** [nicehash/NiceHashMiner-Archived#646]
can you not add something to detect if the nvidiasetp0state.exe is going to create a UAC dialog, just skip running it? I can't enable this option because when my computer restarts due to updates or a crash, it logs into a non-admin miner account and resumes mining, but then the UAC dialog prevents any mining. 

If I leave the set p0 state option disabled, can I run nvidiasetp0state.exe as a startup item instead? Does it need some parameters passed? It exits too quickly for me to see how it was launched.

**Comment by nicehashdev** [comment]
Set p0 state without administrator privileges does NOT work. Administrator privileges are needed.

**Comment by CreamyG31337** [comment]
i know but please answer the question - can i run nvidiasetp0state.exe as a startup item, does it need any parameters?
why not detect the UAC authentication and terminate or skip it?

**Comment by nicehashdev** [comment]
UAC cannot be terminated or skipped.

Perhaps try to add task in scheduler and make it run as SYSTEM at system startup.
