### ISSUE TITLE
Lower CPU rate

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#647]
I get 6 to 8 cents less per hour with 1.7.5.1 vs 1.7.5.0

**Comment by xadonxander** [comment]
Set less threads to 0 and it corrected the problem.

**Comment by Mare76** [comment]
Hi my i7-4790K has had around 230 H/s or higher, with 1.7.5.0 now it gets 153 H/s.
I copied the config file (xmr-stak-cpu) from previous version but  as soon as I start NHM it change it back so I copied it again and made it read only and now I get >230 H/s with new version.

**Comment by xadonxander** [comment]
Try changing the less threads to 0 in the settings menu.

**Comment by Mare76** [comment]
yes, you can do it like that too :)

**Comment by xadonxander** [comment]
Well that way it doesn't revert to the old setting.

**Comment by S74nk0** [comment]
[pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre) and the new upcoming release will have this fixed. Do a rebenchmark of CPU XMR miner as the settings have been changed.

Closing...
