### ISSUE TITLE
i install microsoft c ++ 2015 redistrubaable and enable lock memory but  i cnt see my cpu 

### ISSUE THREAD

**Issue by almoharebh** [nicehash/NiceHashMiner-Archived#648]
i install microsoft c ++ 2015 redistrubaable and enable lock memory but  i cnt see my cpu .
I run sqlserver.exe but not work .
what sqlserver.exe and how can I enable it

**Comment by nicehashdev** [comment]
Without you telling us what kind of CPU you use, we cannot know whether it supports AES-NI.

**Comment by DannyDK2** [comment]
I cant use the cpu miner aswell, also get the mem alloc failed. I have a Ryzen cpu and an Asus x370 crosshair extreme motherboard. Is there something in bios i need to change/enable for it to work?

**Comment by almoharebh** [comment]
can i mine on vps
