### ISSUE TITLE
XMRStakCpu Tip

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#650]
Bold this Link: **You have to be logged into Windows as Administrator in order for this feature to work.**

**Comment by S74nk0** [comment]
https://msdn.microsoft.com/en-gb/library/ms190730.aspx

This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
