### ISSUE TITLE
XFX RX 470 Dagger sgminer issue 1.7.5.1

### ISSUE THREAD

**Issue by Treebeardz** [nicehash/NiceHashMiner-Archived#653]
I can't seem to complete a benchmark of "DaggerHashimito (sgminer)" with the latest version it will start but never complete. 

Using version 1.7.5.0 I have no issues running the benchmark for both Dagger sgminer / ethminer .

I am wondering why my performance is so much worse then what is listed in the profitability calculator for the RX 470. I currently get about 19 MH/s with Dagger(ethminer) and 16 MH/s with (Dagger)sgminer when running 1.7.5.0. The profitably calculator estimates 25 MH/s a significant improvement over what I am currently getting. 

My specs
Windows 7 64Bit
XFX RX 470 4GB
Driver NON-ReLive AMD driver 16.11.5

Any advise on improving performance would be helpful as well.

**Comment by Pizzaguy1234** [comment]
Same exact thing W10 XFX 480

**Comment by Treebeardz** [comment]
Found out the profitability calculator is estimating a modded vbios RX 470 and RX 480. A stock RX 480 gets about ~25MH/s where as a modded vbios with strapped memory timing will get about 30MH/s same with the 470 about a 5MH/s improvement. 

The sgminer issue seems to be an issue going back all they way to the 280X series my guess is it will see a fix soon.
