### ISSUE TITLE
XmrStackCPU Miner Performance cut in half in 1.7.5.1

### ISSUE THREAD

**Issue by mavericknoob** [nicehash/NiceHashMiner-Archived#654]
With the move from 1.7.5.0 to 1.7.5.1 XmrStackCPU miner performance on AMD FX-8350 was cut in half.  Less threads is still set to 1. 
I've found the problem in bin\xmr-stak-cpu\config.txt, the miner is only being set to use half the treads available. It is being set to use treads 0, 2, and 4 in 1.7.5.1. In 1.7.5.0 it will use treads 0, 1, 2, 3, 4, 5, 6. 
Note replacing the config.txt, in 1.7.5.1 with the config.txt from 1.7.5.0 makes no difference.

**Comment by giosal** [comment]
same problem here.
on Intel Core i7-4700HQ with 4 cores and 8 threads it's using only threads 0, 2, 4 and 6
same on AMD FX-8150 with 4 cores and 8 threads.
on Intel Xeon E5-2686v4 with 4 cores and 4 threads it's working properly, using threads 0, 1, 2 and 3
so seem only to happen only on CPUs with Hyperthreading and when launching via NHM.
if you edit config.txt and launch from bin folder this miner separately it works properly, but if you launch it again via NHM, NHM reedits config.txt file again.

**Comment by Mare76** [comment]
Hi
When replace config.txt set it as read only

**Comment by mavericknoob** [comment]
@Mare76 ok, I'll try that. But this is still a bug/problem in the code.

**Comment by Mare76** [comment]
Yes I know but it is the only solution that worked for me

**Comment by mavericknoob** [comment]
@Mare76 that did the trick. Thanks. Too bad this is an active Bug, and now NHM does not report hash rate for CPU when also mining with GPU.

**Comment by mavericknoob** [comment]
Ok, looks like it is hit or miss if NHM show CPU hash rate, when also GPU mining... Was not showing for Pascal, but stopped it and started Lyra2REv2 and it is now showing CPU hash rate... Whatever is the case, 1.7.5.1 seems to me to be more bugy

**Comment by xadonxander** [comment]
Have you tried setting the less threads in the settings menu to 0? It worked for me and I did not have to configure the config file. It also shows the cpu hash rate for me.

**Comment by mavericknoob** [comment]
No I've not set less threads to 0, because I want a thread available for my mouse

**Comment by xadonxander** [comment]
I have it set to 0 and it doesn't affect my mouse and the computer is very
usable. I guess you could try playing with the settings and see the
outcome. I have a i7- 6700 mining with all threads, 2 980ti's and a Radeon
7950 in the rig and still use it to watch YouTube, play music and surf. I
only need to stop mining if I am gaming.

**Comment by mavericknoob** [comment]
@xadonxander good for you that you don't need a spare thread. It still does not solve the problem; if and when testing 1.7.5.1 with less threads set to 0, NHM still only uses half the treads available. NHM, will only use 4 of the 8 threads, cutting hash rate down to ~200 H/s from ~400H/s.

**Comment by giosal** [comment]
@mavericknoob same here. but only on CPUs with hyperthreading (i.e., 4 cores / 8 threads).
but it actually started on version 1.7.5.0 after change of CPU cryptonight miner to xmr-stak

**Comment by mavericknoob** [comment]
@giosal The big hit for me came in 1.7.5.1. I had some issues at first in 1.7.5.0, untill I figured out what I was doing wrong. See https://github.com/nicehash/NiceHashMiner/issues/644

**Comment by xadonxander** [comment]
If you know how hyperthreading works and the physical cores are being 100% loaded the virtual cores do not help at all and could actually hurt performance. Cores 0,2,4,6 are physical cores and 1,3,5,7 are virtual cores.  I manually changed the config file to include the virtual cores and the performance dropped.  In my case using the all 8 threads drops the hash rate from 176.3H/s to 145.5H/s and it kills Equihash performance.  Using 7 and then 6 threads still yielded the same results with cryptonight hash rate but did keep equihash running full speed. Even though windows task manager may show utilization at 50% of your processor you are still using 100% if all the physical cores are maxed out. I did set mine to use all physical cores by updating the use less cores to 0. If you would like to leave 1 core for you to use set it to 1. Keep in mind if you set it to 0 there will still be 4 virtual cores available for your mouse and everyday tasks. If there is any other performance issue I think it would be in the coding of the XMR-STAK-CPU.EXE file. If a previous release worked better for you try replacing the one in the bin folder with that release.

**Comment by mavericknoob** [comment]
@xadonxander ok, since you're so smart. Tell me which has the highest hash rate.
3 threads
![3 cores](https://cloud.githubusercontent.com/assets/20135196/23265235/e69d4818-f998-11e6-8e86-8ee4ef96ea56.jpg)

4 threads
![4 cores](https://cloud.githubusercontent.com/assets/20135196/23265247/eff246fc-f998-11e6-91fb-cc196286b427.jpg)

or 7 threads
![7 cores](https://cloud.githubusercontent.com/assets/20135196/23265255/f551190c-f998-11e6-9b49-a47e522d1ef2.jpg)

Edited to change wording from "cores" to "threads"

**Comment by mavericknoob** [comment]
Here is 7 threads in 1.7.5.1
![7 cores 1 7 5 1](https://cloud.githubusercontent.com/assets/20135196/23265896/0b08259a-f99b-11e6-8f01-42fc29439cf8.jpg)

**Comment by xadonxander** [comment]
Why do you feel the need to be such a dick to people who are trying to help you? Like I said my i7 works that way I don't have an AMD processor to test. I know the hyperthreading works differently in AMD processors. While it may not help you the information I provided may help someone else with Intel processors. Glad it works for you!

**Comment by mavericknoob** [comment]
@xadonxander B/c I want to get the problem fixed and everyone keeps telling me, that I don't know what I'm talking about, and I'm sick of it.

**Comment by giosal** [comment]
@mavericknoob how did you get it to use all threads? I have AMD FX-8150 and I think it will make quite a differrence as well

**Comment by mavericknoob** [comment]
@giosal  **In 1.7.5.0 I did what is discussed here** https://github.com/nicehash/NiceHashMiner/issues/644
**But in 1.7.5.1 I had to I edited config.txt found in \NiceHashMiner_v1.7.5.1\bin\xmr-stak-cpu\ replacing**
"cpu_thread_num": 3,
  "cpu_threads_conf": [
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 0
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 2
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 4
    }
**with the code from 1.7.5.0's config.txt**
"cpu_thread_num": 7,
  "cpu_threads_conf": [
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 0
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 1
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 2
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 3
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 4
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 5
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 6
    }
**and then set the file's properties to read only.**

**Comment by giosal** [comment]
@S74nk0 ok, after update to 1.7.5.2 it sees all threads (but doesn't affine to any of them, guess that was the problem?), also it doesn't reduce performance of GPU miners.
will test tomorrow some more and report back, but so far so good

**Comment by S74nk0** [comment]
@giosal That was causing issues (affine to thread). NHM wasn't setting the miner config correctly that is why many users were having issues. https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre should have this issue fixed.

Closing...

**Comment by mavericknoob** [comment]
Thanks, @giosal & @S74nk0 , I'll start testing 1.7.5.2-pre shortly
