### ISSUE TITLE
Can't benchmark GPU Terminated?

### ISSUE THREAD

**Issue by eneraltec** [nicehash/NiceHashMiner-Archived#656]
Im using sapphire nitro 4gb
![terminated](https://cloud.githubusercontent.com/assets/25885056/23104999/c4827284-f6f1-11e6-9742-1e630c1b5797.png)

**Comment by Talhabestaz** [comment]
I have the same problem. It never ends

**Comment by giosal** [comment]
might be realted to issue #672 
have you tried launching mining?

**Comment by Talhabestaz** [comment]
nicehash is supposed to work with r9 280x right? It stops in Benchmark step 3/8 and when i start mining only one GPU works. I have 5 * R9 280x

**Comment by keztheminer** [comment]
Nvidiahash miner (was nicehash miner)is changing name without realising

**Comment by kenshirothefist** [comment]
This was resolved with the latest (pre) release 1.7.5.2
