### ISSUE TITLE
my miner cant read my cpu or gpu 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [nicehash/NiceHashMiner-Archived#657]
my miner cant read my cpu or gpu  after the update

**Comment by S74nk0** [comment]
@zezo357 did you close the previous NHM instance? Was NHM mining at the time (were there any standalone miners running)? Does a reboot make HW detection working again? What CPU(s) and GPU(s) are you using?

**Comment by abdelaziz-mahdy** [comment]
i restarted the computer and same problem 
geforce9500 gt and cpu is pentium dual core cpu e5300 2.60ghz

**Comment by nicehashdev** [comment]
Your video card is too old to be supported by NHM. 

Also, your CPU does not have AES-NI thus it is not supported by NHM.
