### ISSUE TITLE
1.7.5.1. CryptoNight --launch ignored

### ISSUE THREAD

**Issue by blue-yu** [nicehash/NiceHashMiner-Archived#658]
Again --launch is ignored in settings, and also in internals. No matter what I do it is always 8x20

**Comment by adpv0205** [comment]
alguien que hable español

**Comment by S74nk0** [comment]
@blue-yu The parser settings have been reverted ([commit](https://github.com/nicehash/NiceHashMiner/commit/2ed1ffc8f5100cab3086d8967c7b95e9f28f9e90#diff-796b2617ddca7bd6432282880d297e42R354)) as it breaks other miners. Until the parser module is fixed I can help you with the internals workaround. 
[MinerOptionPackage_ccminer_CryptoNight_launch_no_ignore.zip](https://github.com/nicehash/NiceHashMiner/files/786883/MinerOptionPackage_ccminer_CryptoNight_launch_no_ignore.zip)
this file when unzipped to **internals** folder will accept any **value** for the **"-l"/"--launch="** parameter. The **"Default": "",** value is empty and it will ignore only the empty field (It is a little confusing that the default is ignored, but it is a workaround to make the parser compatible with some miners) So copying this over will help. If it still doesn't work **reopen** the issue and we'll find a solution.

@adpv0205 This is an international forum, the best/fastest way to get issues resolved related to **NiceHash Miner** is to speak English as most of us will understand it.

**Comment by blue-yu** [comment]
It's working. Thanks once again...
