### ISSUE TITLE
alguien que hable español ?

### ISSUE THREAD

**Issue by adpv0205** [nicehash/NiceHashMiner-Archived#659]

**Comment by TVilaboa** [comment]
Hola! Que pregunta tenes?

**Comment by adpv0205** [comment]
una buenas . tengo una rx 470 y a la hora de hacer el bermank no lo hace en todos los algorismo que sales porque ?

**Comment by S74nk0** [comment]
@adpv0205 please open issues related only to **NiceHash Miner**. Please try your best to use English.
Closing issue...
