### ISSUE TITLE
DIFFERENT AMD 2XX CARDS MINE ETH SEPERATE DESKTOPS BUT NOT ON SAME. PR

### ISSUE THREAD

**Issue by PhoenixAdageyudi** [nicehash/NiceHashMiner-Archived#66]
Two different amd 2XX cards mined beautifully by themselves on different desktops but on same board i suddenly get <10% what should be combined hash rate.. 

mining with 295x was great 55mh then added in a 270x usually 13mh BOOM 7mh TOTAL even after 12 hrs letting it go no matter what i do  they wont work together.. 

[Another Similar issue was put forth over a month ago and has not been resolved.   . 
](https://github.com/nicehash/NiceHashMiner/issues/33). 

1 Month later I have this issue and am very frustrated 

WHY BOTHER EVEN DETECTING OTHER CARDS AT ALL IF THEY WONT WORK THIS IS PRETTY VITAL TO NICEHASH'S WAY OF GENERATING REVENUE.

**Comment by Kekkonshiki** [comment]
@iwasphoenix try first manually start it for test and then directly update it from site
https://github.com/nicehash/NiceHashMiner/issues/45#issuecomment-200251315
maybe it's not a problem of NHM

**Comment by kenshirothefist** [comment]
Mixing different cards can produce unexpected results. In general different cards works fine, since we are testing NHM with various mixed setups, even with setups with mixed AMD and NVIDIA cards. The idea or running separate mining processes for different GPUs is not bad, but it also requires more main RAM memory (especially in Ethereum case). We will consider this upgrade as an optional setting in a future release.

**Comment by PhoenixAdageyudi** [comment]
please do more than consider it as your company will generate a significant increase in fees if people can run more hardware without issue.  

thats a very big motivator i cant understand how this has gone unaddressed. 
The cost of new RND spent to its solution would more than return on its investment for the profit Nicehash generates.     

Regardless of other priorities to attend to this is, by a wide margin, under appreciated revenue not being generated.

**Comment by PhoenixAdageyudi** [comment]
what if i tried AMD crossfire on both the 270x auind. the 295x ?     

@SiegHeil appologies but is there a walkthrough for thiis i have never been able to use beanch masters they consfuse me. how would i upgrade the etherminer used by the NH applicarion?  .   

i have never set up the ethereum miner by itself and have only mjned eth via NH as in would it be easier to set up mining for eth with their miner and just put in the NH pool into it?  

just trying to finally get this resolved  

Thank for you for your help

**Comment by theLosers106** [comment]
Hi,

This is an old issue but I would like to know it the newer ethminer works better now?

Thanks.
