### ISSUE TITLE
Virtual Memory Warning in 1.7.5.1

### ISSUE THREAD

**Issue by magnoman** [nicehash/NiceHashMiner-Archived#663]
With release 1.7.5.1 one of my rigs has started giving me a Virtual Memory Warning when I start Nicehash.  I have all my rigs set to load up NiceHash automatically but now that this warning pops up it has to be manually acknowledged before the miner will start mining.  I'm using 1.7.5.0 on that rig until I can fix the issue.  Any ideas?  I did try a clean NiceHash install and I've tried to manually increase the size of the virtual memory but it doesn't seem to help any.  The warning pops up when NiceHash is loading and finding the CUDA devices etc.  This rig is running Windows 10 Pro-64 bit , 256GB SSD, 8GB Ram, Pentium and 6 Geforce GTX 1070 w 378.66 drivers.  I have about this same setup in my other rigs running 1060s but they aren't having this issue.  Let me know if anyone has any ideas or if you've encountered this yourself.

![virtualmemorywarning](https://cloud.githubusercontent.com/assets/25410005/23146193/a6499142-f7a2-11e6-9254-c8257dfead27.png)

**Comment by Kimax89** [comment]
As Claymore recommend:

> For multi-GPU systems, set Virtual Memory size in Windows at least 16 GB

**Comment by magnoman** [comment]
Thank you for the suggestion.  I set it at 17000 MB to 24000 MB and restarted but I'm still getting the warning.
![virtualmemorywarning2](https://cloud.githubusercontent.com/assets/25410005/23146491/47fe49ea-f7a5-11e6-9260-a9aa8b747684.png)

**Comment by fefsf** [comment]
Set the min and max at at least 24GB, dont let windows adjust it.

**Comment by magnoman** [comment]
Awesome!  That did the trick.  I set it at 32GB/32GB and no more warning.  Case closed.  Thanks!
