### ISSUE TITLE
Claymore ZCash miner 12.1

### ISSUE THREAD

**Issue by Kimax89** [nicehash/NiceHashMiner-Archived#664]
Just a kindly reminder that Claymore has released 12.1 and the one your using is 12.0

**Comment by BARUCHER777** [comment]
Please add also a miner --- Claymore's Dual ethereum miner 8 - Pascal coin

**Comment by S74nk0** [comment]
@Kimax89 Thanks for the reminder, the download package has been [updated](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.1). A re download will have V12.1 included. Of course just replacing the old miner in **bin_3rdparty\claymore_zcash** folder with the new version will also work. Thanks again for the reminder.

@BARUCHER777 Claymore's Dual ethereum miner 8 will probably land in one of the new versions.
