### ISSUE TITLE
AMD Card Issue All algos

### ISSUE THREAD

**Issue by semisane** [nicehash/NiceHashMiner-Archived#666]
2 of 4 of my identical RX480 8GB always mine at half hash rate.
This happens with all algos except Dagger

4x RX480 8GB
Win 10
16.11.5
NHM 1.7.5.x
![pascal](https://cloud.githubusercontent.com/assets/18557237/23147400/7d92dede-f793-11e6-90f4-0fafaa6730f2.JPG)

**Comment by Johann1982** [comment]
What mainboard and cpu do you have? Could be a lane issue...
Was it always like that or only after the last upgrade?

**Comment by semisane** [comment]
Biostar TB85
Celeron G1840

It has always been like this.

**Comment by kenshirothefist** [comment]
Since this is a sgminer-gm issue and not directly related to NiceHash Miner, we welcome you to discuss these kind of issues here: https://github.com/nicehash/sgminer-gm/issues.
