### ISSUE TITLE
PC Reboots when mining anything else than Lyra2rev2.

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#668]
Hi
I had to disable all other algo's because it causes a reboot after a while. I am running 2x GTX1070 8GB cards with win10, latest NVidia drivers.
I was able to mine most algo's about 2 builds back. Now I just get system restarts. 
All algo's bench without problems.

**Comment by Johann1982** [comment]
When mining with a single card it works fine. Only when running both that it reboots.

**Comment by fefsf** [comment]
What does windows event viewer state is the reason for the system restarts?

**Comment by Johann1982** [comment]
My event viewer is not active. I have managed to get other algos working except for X11 Ghost. Seems it was a power issue. Had to connect a 2nd psu to mainboard and risers. Now pascal, equihash (Slightly buggy, nicehash will freeze if I do anything else), decred and lyra2rev2 works well. Not sure why X11 Ghost still causes system reboot. Funny enough, everything worked fine before the last 2 updates. Not sure if the new algos draws more power?

**Comment by Johann1982** [comment]
Maybe I have to add another 4GB ram to my system for X11. Currently running 4GB DDR3 1600Mhz, G4400 CPU, 160GB HDD, Windows 10 SL, 2x GTX 1070 8GB with 700W Huntkey PSU.

**Comment by Johann1982** [comment]
Ok, have tested all algos. Only X11 Ghost (Alexis) that causes my pc to reboot as soon as it starts mining.

**Comment by fefsf** [comment]
4GB of ram is pretty low for X11GOST. Try increasing your virtual memory to 16GB (min and max size). You are probably rebooting due to low memory.  I had to increase mine to over 24GB on my 6 rig system.

**Comment by Johann1982** [comment]
Have tried that already. Virtual mem is set to 40GB min 50GB max. It is just weird the way the pc reboots when doing X11. It is immediate. Will try adding another 4GB DDR3 tomorrow and see if that helps.
@S74nk0 Do you perhaps have any input? Maybe bug in code? I can upload logs if you need them?

**Comment by nicehashdev** [comment]
ccminer_x11gost is experimental miner, that is why it is disabled by default. It may cause issues like you have experienced already. Use at your own risk. Since ccminer is not our code, there are no plans to fix this issue.

But we have plans to integrate x11gost into our own excavator miner which is based on stability.
