### ISSUE TITLE
Last Sp version Faster + Need decred support

### ISSUE THREAD

**Issue by mendoza1468** [nicehash/NiceHashMiner-Archived#67]
Hi, just to say that the last SP version is 5 to 10% faster than previous version, so it will be great for your next update.

And it should be great to have decred support too. 
Last Decred version tpruvot
http://cryptomining-blog.com/7679-updated-ccminer-1-7-6-fork-by-tpruvot-with-improved-decred-support/

 Thanks to all the developper you doin a great job. Last Nicehash miner work well. For those who wanna upgrade the last SP mod in nicehash : https://github.com/sp-hash/ccminer/releases/

Old Version 
![1](https://cloud.githubusercontent.com/assets/16471209/14237373/ebf15406-f9f0-11e5-8111-08e9e6398031.JPG)

New Version
![2](https://cloud.githubusercontent.com/assets/16471209/14237372/e6718d16-f9f0-11e5-8a36-76ccbd0ac663.JPG)

**Comment by theLosers106** [comment]
The new miners will be included in the next release of NiceHashMiner. Thanks for the suggestion (:

**Comment by theLosers106** [comment]
Will be closing this issue as it has been resolved in NiceHashMiner v1.4.0.0 release..
