### ISSUE TITLE
Nicehash locks and does not mine

### ISSUE THREAD

**Issue by nandopais** [nicehash/NiceHashMiner-Archived#670]
I'm getting these messages, what should I do to work?

unable to get nicehash profitability data. if you are connected to internet, try again later

nicehash miner cannot start mining. make sure you have at least one enabled that has at least one enabled and benchmarkerd algorithm

I'm having trouble starting work
1x r9 290x
2x r9 380
3x rx 470
1x r9 265x

**Comment by Johann1982** [comment]
Please supply hardware info, O/S and driver versions. Also, list any anti-virus software

**Comment by nandopais** [comment]
Cpu intel i5 750 2.67ghz
6gb memory
Windows 7 ultimate 64bits

gpus com crismon Updated 16.11.5 
I do not have any antivirus on the machine
Only windows firewall
thanks for listening

**Comment by Johann1982** [comment]
Ok, did you check under benchmark if all selected algorithms have been benchmarked? If you can, upload a screenshot of your nicehash miner main screen.

**Comment by Johann1982** [comment]
You might want to upgrade to windows 10 if you are using more than 4 cards per mainboard.

**Comment by undefy** [comment]
This issue has been raised before. Check that your IPv6 is disabled.

**Comment by kenshirothefist** [comment]
NiceHash Miner is periodically communicating with our web service to get profitability data, etc. You must make sure that you have a stable Internet connection. Also, you have to make sure that your firewalls/anti-virus/anti-trojan software is not blocking communication with *.nicehash.com.
