### ISSUE TITLE
ccminer problems

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#671]
As far as I can tell, all the ccminer algos draw way more power than the normal nicehash algos. I found that it roughly draws double the amount of power. Does anyone else have similar experience?
I would suggest that unless you have double the size of psu normally needed, do not run any ccminer algos.

**Comment by S74nk0** [comment]
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
