### ISSUE TITLE
NeoScrypt not avaible for NVIDIA GTX 1060

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#673]
Miner version 1.7.5.1 is not working algorithm neoscrypt graphics card Nvidia 1060 this algorithm generally not available for mining ...
P.S Driver version 21.21.13.7653 (29.12.2016)

**Comment by S74nk0** [comment]
NeoScrypt is disabled for SM6.x architectures (current miner is not stable for SM6.x architectures). We will be adding this back in one of the future releases with a new miner.
