### ISSUE TITLE
Equihash AMD restart loop

### ISSUE THREAD

**Issue by Rezobyte** [nicehash/NiceHashMiner-Archived#677]
After latest payout. Version 1.7.5.1 Equihash (both Optiminer and Clamored) no longer works on my AMD R9 Nano (Fiji) cards. The miners connect, query 2 of my cards for work, and then quits, restarts, and repeats this process indefinitely.
I matched this stoppage with the exact time of payout, the miner quit mining at the same time. My nVidia (1070) Cards are unaffected and are mining just fine.
Reinstalled driver 15.2, as well as reloaded nicehash and all benchmarks, but no luck.

**Comment by Rezobyte** [comment]
Switching from San Jose to Amsterdam allowed mining to work again on my AMD cards. I guess there's an issue with the San Jose connection.

**Comment by S74nk0** [comment]
@Rezobyte this was probably just a temporary issue with that service location. Reopen this issue if it is still failing with **USA - San Jose**.
