### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by OAXP** [nicehash/NiceHashMiner-Archived#680]
Please, Can I now how to setup my Rx 480 GPU and my Fx 8350 CPU for more money. Because I just get 0.20 $/day with the two devices.

**Comment by S74nk0** [comment]
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.
