### ISSUE TITLE
XmrStackCPU won't bench on 1.7.5.1

### ISSUE THREAD

**Issue by OAXP** [nicehash/NiceHashMiner-Archived#681]
When it says : All benchmark finished. The CryptoNight algorithm Speed is none and the BTC/Day is N/A. How can I bench my fx 8350

**Comment by alawadhi2012** [comment]
solution here , follow it , it will rum then reboot 

https://msdn.microsoft.com/en-gb/library/ms190730.aspx

**Comment by OAXP** [comment]
Thank, I'll try now

**Comment by OAXP** [comment]
Don't work.

**Comment by alawadhi2012** [comment]
last step you put your login name , 
my server login name is Administrator after that click on check then restart your computer then try

**Comment by OAXP** [comment]
It does not work and it desactive my GPU so I disable the locked pages.

**Comment by DarkTrollCoin** [comment]
i guess you have a non US system.
It's because the decimal separator you use is not "." parsing of bench results are not going through because of decimal separators being different.
it will be fixed in the next version. (there's a pre release so you can test but i'm not sure if the commit is in)

**Comment by S74nk0** [comment]
Use [Pre-Release2](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.2-pre/NiceHashMiner_v1.7.5.2_PreRelease_2.zip)
