### ISSUE TITLE
Benchmarked Algorithms 

### ISSUE THREAD

**Issue by 192uijo** [nicehash/NiceHashMiner-Archived#683]
After having setting up my new miner and installing Nicehash, I benchmarked Dagger, Equi, and Cryptonight. I did the benchmark for the ones that had Claymore miner in the parentheses (they also had the same rates). The rest were left unbenchmarked.

I started mining and it shows up with a message saying that some are not benchmarked, continue mining? I just skipped it and started mining. It's mining like normal, I'm not seeing any problems. Will there be any problems or disadvantages without the same ones except using the default miner?

GPU: R9 290X

**Comment by S74nk0** [comment]
@192uijo There shouldn't be any problems if you continue. That prompt is just to note the user that not all algorithms have been bench-marked, miners/algorithms that have speed 0 will just be ignored and it will use only miners/algorithms that have a speed greater than 0. 
Update: 
As for what miner to use it really depends on the drivers, GPU, etc. Case by case
