### ISSUE TITLE
XmrStackCPU crashes when sets more threads

### ISSUE THREAD

**Issue by KexyBiscuit** [nicehash/NiceHashMiner-Archived#684]
I have a dual E5-2670 server, running Windows Server 2016. I add an VM on Hyper-V, give it 32 threads(Hyper-Threading enabled), run NHM. It gives me ~600 H/s with the old cpuminer. Cool.

Each CPU has 20 MB SmartCache L3, so in theory 10 threads on each should give the best performance. The old cpuminer runs more, but it has a good speed. Now, XmrStackCPU runs only 16 threads, and assign them all to CPU 0, CPU 1 is idle. This gives me only ~150 H/s, the same as E3-1231 v3, 1/4 of cpuminer on the same VM.

The same problem with my desktop, but I fixed it with the solution in #654. However, use more threads causes crash on E5-2670 and i5-4590.

**Comment by nicehashdev** [comment]
We are aware of the issue and will be fixed in next release.

**Comment by memphis83** [comment]
I have the same issue #688

**Comment by S74nk0** [comment]
Try the [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre). Report if this is fixed.

**Comment by S74nk0** [comment]
[Duplicate](https://github.com/nicehash/NiceHashMiner/issues/654) closing issue
