### ISSUE TITLE
Please add miner from EWBF's for NVIDIA VIDEOCARD`S

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#686]
Please be so kind as to add a miner from --- EWBF's CUDA Zcash miner(Version 0.3.0b)
For graphics cards from Nvidia 1060 are more productive than your miner! 290-305 SOL`s

**Comment by nicehashdev** [comment]
Hello!

EWBF's miner has same speed as our EQM (just set higher memory clock and you will get 300+ too).

Besides, EWBFs has also 2.5% devfee which makes it less profitable to mine on NiceHash - EQM has 0% extra fee.

It was also prooven that EWBF has copied all ideas out of EQM (that is why it is not faster than EQM).

**Comment by GTANAdam** [comment]
You might wanna take a look at https://github.com/GTANAdam/NiceHashMiner/releases/tag/1.7.5.13-pre
It adds EWBF miner support
Hope that helps now.
