### ISSUE TITLE
[BUG] AMD GPU not showing (NHM parsing error)

### ISSUE THREAD

**Issue by GeneGulanesJr** [nicehash/NiceHashMiner-Archived#687]
My amd rx 460 sapphire 2gb does not show on device list.
Tried with latest version of amd relive and non relive (16.11.5)
Any help would be appreciated.
Currently running NHM 1.7.5.1

![sssss](https://cloud.githubusercontent.com/assets/26081692/23396143/24a203f0-fdcd-11e6-94c9-0ae98ce96aba.png)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/806003/log.txt)

**Comment by S74nk0** [comment]
@MPGH5574 It seems this is a parsing error with NHM. Is OS locale setting set to English? If not what is the locale? I believe that Operating System language is causing a parsing error and hence this is not being shown. I can post a patched version that might fix this so we can resolve this for the future.

**Comment by GeneGulanesJr** [comment]
@S74nk0 OS locale is set on English already by default. I would also like to try the patched version if you could post it.
![ssss](https://cloud.githubusercontent.com/assets/26081692/23487811/80a92b2c-ff23-11e6-8a18-6813e4566e28.png)

**Comment by S74nk0** [comment]
@MPGH5574 try replacing **AMDOpenCLDeviceDetection.exe** with this [one](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/AMDOpenCLDeviceDetection_NHR.zip) inside the NHM folder. Report if this works

**Comment by GeneGulanesJr** [comment]
@S74nk0 Thats it now shows my GPU. Thanks for the help
![ssss](https://cloud.githubusercontent.com/assets/26081692/23532666/93651c7a-ffe7-11e6-8e58-04a6cce904e4.png)

**Comment by S74nk0** [comment]
@MPGH5574 thanks for the feedback. We'll change this in the upcoming release.
Closing...
