### ISSUE TITLE
XmrStackCPU Dual CPU Both miners on one CPU Preformance to 2x 25% (50%)

### ISSUE THREAD

**Issue by memphis83** [nicehash/NiceHashMiner-Archived#688]
I have a Dual Xeon E5-2620-v4 both are visible in the NiceHash Miner.
But Nicehash starting the XmrStackCPU Miner twice on one CPU.

**Comment by giosal** [comment]
take a look at #654

**Comment by memphis83** [comment]
Does not apply to me, i have 2 physical CPU's
NHM starts 2 miners but bind them on one CPU.

**Comment by memphis83** [comment]
![1](https://cloud.githubusercontent.com/assets/22313662/23399576/faacf022-fda0-11e6-9dfd-161233e02a0b.jpg)
![2](https://cloud.githubusercontent.com/assets/22313662/23399574/faac9424-fda0-11e6-8c92-7132b322656c.jpg)
![3](https://cloud.githubusercontent.com/assets/22313662/23399575/faac9f3c-fda0-11e6-9005-11cc0bb47e30.jpg)

**Comment by S74nk0** [comment]
Try the [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre). Report if this is fixed.

**Comment by xadonxander** [comment]
I tried the prerelease and it gets 10-15% less h/s on the cpuminer than in 1.7.5.1 even after changing the the config file. intel i7 processor

**Comment by memphis83** [comment]
Seems to be working ...
![4](https://cloud.githubusercontent.com/assets/22313662/23449629/badb34a6-fe57-11e6-974e-92ba4d9a4f24.jpg)

**Comment by S74nk0** [comment]
Thanks guys for the feedback! This issue is a [duplicate](https://github.com/nicehash/NiceHashMiner/issues/632). Will close this now
