### ISSUE TITLE
Unble to get Claymore to benchmark with R9 Furty

### ISSUE THREAD

**Issue by shaggyboiler** [nicehash/NiceHashMiner-Archived#689]
Running nicehash 1.7.5.1.  AMD drivers 17.2.1 

Benchmark will not run for any of the ClaymoreAMD. It just says none.  Everything else will benchmark.
My R9 290 and 270 work just fine with claymoreamd mining cryptonight.

**Comment by BARUCHER777** [comment]
Personally at me data on the same video card everything works fine!
Driver Version: ---- (16.150.2211.0 --- 21.03.2016)

**Comment by shaggyboiler** [comment]
Switched to the 16.1 drivers and still get none on speed during benchmark on all Claymore

**Comment by S74nk0** [comment]
@shaggyboiler try setting **-asm 0** in the extra launch parameters for Equihash. If none of the Claymore miners work for you check that the miner files aren't missing (if they are you should get a warning at NHM startup)

**Comment by BARUCHER777** [comment]
I have all the normal working specifically with cards 390 and 290 but on the Fury's speed dropped significantly unfortunately ....

**Comment by shaggyboiler** [comment]
@S74nk0 Tried the -asm 0.  that worked for Equihash. Should I do same for Crypto

**Comment by S74nk0** [comment]
@shaggyboiler For **Claymore CryptoNight** there is a different flag and that is **-a [0,1,2,3,4]**, try setting this to **-a 0** or **-a 4**, 0 is automatic, 4 should be the fastest but it might not work.

**Comment by shaggyboiler** [comment]
@S74nk0 the -a 0 or -a 4 didn't work for CryptoNight, but at least I've getting decent numbers out of Equihash now.

**Comment by S74nk0** [comment]
@shaggyboiler You should try using **Catalyst 15.12** as it is the recommended driver version for Claymore's miners. Mining should be more stable and faster with **Catalyst 15.12**. For further help regarding Claymore's miners please refer to https://bitcointalk.org/index.php?topic=638915.0. 

Closing issue as it is not relevant to NiceHash Miner itself. For any new issues regarding NiceHash Miner open a new issue.
