### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by bnmnb** [nicehash/NiceHashMiner-Archived#69]
Balance issues, it seem like it had added two times more than expected from the webpage has shown which the payable numbers it maybe. Thank you.

After it has been updated to the latest version v1.3.0.2 "quote".
[NiceHashMiner_upgrade_to_v1.3.0.2.zip](https://github.com/nicehash/NiceHashMiner/files/202454/NiceHashMiner_upgrade_to_v1.3.0.2.zip)

.

**Comment by theLosers106** [comment]
Please download the latest (https://github.com/nicehash/NiceHashMiner/releases/tag/1.3.0.3) NiceHashMiner as that should fix the problem. Report back if that works..

Thanks.

**Comment by bnmnb** [comment]
Pop up window shows the latest version not protected in some forms, but clicked run anyway and it works. The balance shows closely to the value as the webpage.

Thank you.

**Comment by theLosers106** [comment]
Ok no problem (: .. you might need to refresh the web and quickly check both as the balance can go quite fast if you have fast miner.. anyways.. will be closing this now..
