### ISSUE TITLE
С nicehash miner на В1.7.5.2 

### ISSUE THREAD

**Issue by gennadiv** [nicehash/NiceHashMiner-Archived#691]
skips DaggerHashimoto

**Comment by S74nk0** [comment]
@gennadiv sgminer-gm or ClaymoreDual or both?

**Comment by gennadiv** [comment]
with missed the beginning of both versions - then I reinstalled and the pass was sgminer -then I launched sgminer passed then both passed - but sgminer is disabled by default - and the question I have and ClaymoreDual  both currencies why not Mein?

**Comment by S74nk0** [comment]
**sgminer-gm** will be enabled by default and **ClaymoreDual** will be the alternative (one can enable disable any miner as they want depending what works best for their setup)

**Regarding ClaymoreDual mining:**
Dual Mining DaggerHashimoto + [Pascal/Decred/...] will not be available **(at least not officially)** in the future pre-release / release. We can make [additional parameters](https://github.com/nicehash/NiceHashMiner/commit/38e3aaae218be9132a2466ca66b3f9f69387419b#diff-3ca7e2b0e91004f0f16ab9b71693cceeR218) that you can enter in ExtraLaunch Parameters parsable, so one can enable this **manually**. Try using [latest pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre) version.

Closing...
