### ISSUE TITLE
Can't benckmark Equihash

### ISSUE THREAD

**Issue by jimdi** [nicehash/NiceHashMiner-Archived#692]
Can't benchmark Equihash, but all tests passed
![77c4b17e84](https://cloud.githubusercontent.com/assets/2002983/23447008/9dfb5dae-fe69-11e6-8e39-44facadaec24.png)

if i force check this algorithm them i see many errors and can't stop mining, only terminate process
![bc0c7b1845](https://cloud.githubusercontent.com/assets/2002983/23447028/cf6199c6-fe69-11e6-8224-6c493ea6a091.png)

**Comment by S74nk0** [comment]
Disable **Equihash**. Older GPUs aren't fully supported and there aren't any plans to support them in the future.

**Comment by jimdi** [comment]
ok, but can you fix continuous error messages? it appear sometimes if benchmark failed for one or more algorithms

**Comment by S74nk0** [comment]
@jimdi I thought that was just a rendering issue. I'll check what could be causing this. Maybe the logs can help, if you can upload them here.

**Comment by jimdi** [comment]
[logs.zip](https://github.com/nicehash/NiceHashMiner/files/810284/logs.zip)
