### ISSUE TITLE
Testing prerlase

### ISSUE THREAD

**Issue by nickdf** [nicehash/NiceHashMiner-Archived#694]
Hi Here are logs. All benchmarks are passed

you can contact me on skype nikola.atanasovski

[log.txt](https://github.com/nicehash/NiceHashMiner/files/810431/log.txt)

**Comment by nickdf** [comment]
But I have problems with this
![screenshot](https://cloud.githubusercontent.com/assets/25613597/23456960/ebede0a2-fe75-11e6-8d4f-ab95471a9352.JPG)

**Comment by nickdf** [comment]
I have I7-4790K 16Gb ram and enable 18Gb swap file on ssd.

**Comment by nickdf** [comment]
Also I have Radeon (TM) RX 470 Graphics with 8Gb ram and in log file is detected as 4Gb

**Comment by fefsf** [comment]
Increase your swap file to 32GB

**Comment by nickdf** [comment]
I set to 40Gb but i get same error message

![scrscho](https://cloud.githubusercontent.com/assets/25613597/23502296/9b7f4b66-ff37-11e6-8b0d-0d0d3f8cd455.JPG)

**Comment by nickdf** [comment]
Ive canget to 1000Gb but still not working

![c](https://cloud.githubusercontent.com/assets/25613597/23502741/2a4f1578-ff39-11e6-850b-5d4e2b3adcd8.JPG)

**Comment by felixbrucker** [comment]
this is no error, it only shows that you did not enable hugepages support in windows

**Comment by nickdf** [comment]
Then how can I fix this error


![untitled-1](https://cloud.githubusercontent.com/assets/25613597/23512054/98ef404a-ff5f-11e6-82c8-63925674e0e7.jpg)

**Comment by nicehashdev** [comment]
Doesn't look like an issue. Your CPU is simply very slow so it takes a lot of time to find a share.
