### ISSUE TITLE
Nicehash miner statistics page displaying Bitcoin value as $600

### ISSUE THREAD

**Issue by snowcrawl** [nicehash/NiceHashMiner-Archived#696]
I noticed that the statistics page is displaying the incorrect value of bitcoin.  Looks like half of what the actual price is.   It is probably just a temporary glitch as the value of bitcoin has risen higher than previously.

**Comment by giosal** [comment]
Same here, it is a glitch here

**Comment by snowcrawl** [comment]
It has happened in the past, on a previous occasion when the price of bitcoin was rising fast.

**Comment by giosal** [comment]
seems fixed...
