### ISSUE TITLE
where does the profit?

### ISSUE THREAD

**Issue by sergej-shkuruk** [nicehash/NiceHashMiner-Archived#698]
<a href="http://uploads.ru/XDs1I.jpg"><img src="http://sh.uploads.ru/t/XDs1I.jpg" border="0" /></a>
<a href="http://uploads.ru/XtQ3v.jpg"><img src="http://se.uploads.ru/t/XtQ3v.jpg" border="0" /></a>
<a href="http://uploads.ru/2PU1D.jpg"><img src="http://sh.uploads.ru/t/2PU1D.jpg" border="0" /></a>
the wallet shows that the score of 0. Maini your program. She writes that the means. Photo skins attached.
кошелёк показывает что на счёт 0. Майню  вашей программой. Она пишет что средства есть. Фото скинов прилагаю.

**Comment by kenshirothefist** [comment]
Since this is service-related, please write your issue via email to NiceHash Russian Support <support-ru@nicehash.com>
