### ISSUE TITLE
NVIDIA SLI issues

### ISSUE THREAD

**Issue by wallace1981** [nicehash/NiceHashMiner-Archived#699]
I do have two GTX 1070 cards in SLI.
With quite random frequency, when NHM decides to switch from one miner to another (like from Equihash to Lyra), after it stopped current miner and started new one, i'm having this issue. After few notifications from Windows (in Action Center) system hangs (mouse, keyboard, screen -- all frozen). In few mins comes blue screen with dpc_watchdog_violation and system restarts itself.

I do have i7-7700 CPU on Z270 chipset with 16GB RAM running Windows 10 Pro.

When running only one of the miners (like only Equihash) it works perfectly fine. If I assign different algos per card, it is also fine. The problem comes only when it is switching from one to another OR when Im manually stopping and starting mining.

Example of message I have from windows:
Application eqm.exe has been blocked from accessing Graphics hardware.

**Comment by kenshirothefist** [comment]
Can you try temporary **disable (and disconnect)** SLI and see if it works?

**Comment by wallace1981** [comment]
I did that. It seems issue gone (at least for this many time it never happened again).
Is there anything you can fix in software itself or I can do on my end to keep SLI enabled (since this PC used for games as well) and NOT have this issue while mining?
Thanks.

**Comment by Junior88** [comment]
You can try using the Nvidia control panel and disabling SLI in there while you are mining and re-enable for when you are playing games.

**Comment by wallace1981** [comment]
Well I can do that, but it's kinda inconvenient, some time when disabling/enabling SLI it just hangs and then I have to reboot. If I will add all executables of miners to NVidia 3D settings page in CtlPnl and will disable SLI for them -- will it make difference or not?

**Comment by fefsf** [comment]
This is way i abandoned my idea of SLI GTX 1080s :)

**Comment by nicehashdev** [comment]
We tested this issue and it did not happen on our system with 2x 1070 in SLI. Maybe you have some issues with your system? Also, system hang when enabling/disabling SLI is not normal. We suggest you to do clean reinstall of your Windows and drivers.

**Comment by HennethAnnun** [comment]
I am having similar issue here. I use 3 x GTX 1070. No SLI. System is only for mining. Windows 10 Enterprise, freshly installed. Once every couple of days I encounter no multiminer running, and notifications from Windows (in Action Center) stating: "Application has been blocked from accessing Graphics hardware.". Usually some 9 notifications are displayed.

I run latest multiminer.

There is a BUG, but not with SLI.

**Comment by albertaholdingsgroup** [comment]
I'm have same issue with 2 ASUS strax 1080 a. In sli

**Comment by demetrios-koziris** [comment]
Also experiencing this issue with 2 1070. Happens anywhere from every 3 to 6 hours. Will try disabling sli to see if that makes a difference

**Comment by jimwatkins** [comment]
Same for me, 2x1070s. Just did a clean install and very little other software yet. Seems like it might only be the ccminer so your experience could vary by what's profitable atm. I will disable SLI as I barely need it for most games anyway but hope it can be addressed.

**Comment by stefan2606** [comment]
Exactly the same thing here!! My system: Intel 6800k, Asus Strix x99, 16gb Corsair Vengeance, 2x Asus Gtx 1070, Corsair 760 Platinum PSU

**Comment by stefan2606** [comment]
Why is this issue closed? How to fix this?
Put off the SLI cable? Disable in Nvidia control panel?

**Comment by gjaegy** [comment]
Same here, with 2 x 970.. When SLI is enabled in NVidia CP, a freeze occurs after some time (10 minutes). When disabled, no freezer as expected.

**Comment by corygehr** [comment]
Same issue with 2x 1080 Ti cards.
