### ISSUE TITLE
Ethminer alway mine on all card's

### ISSUE THREAD

**Issue by Fossius** [nicehash/NiceHashMiner-Archived#70]
I chose one videocard <a href="http://jpegshare.net/" target="_blank" title="JpegShare.net - бесплатный хостинг картинок"><img src="http://jpegshare.net/images/2f/32/2f32bbbfaeb44c09d743ef0d1be8731a.jpg"/></a>
, but Ethminer mine on all card's. I have to set  in  settings: "--opencl-device 1"

**Comment by theLosers106** [comment]
Please read the FAQ (https://github.com/nicehash/NiceHashMiner#troubleshooting) .. Will be fixed in the next version of NiceHashMiner..

**Comment by theLosers106** [comment]
Will be closing this issue as it has been resolved in NiceHashMiner v1.4.0.0 release..
