### ISSUE TITLE
Increasing and decreasing payment in GUI

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner-Archived#701]
NHM is showing payment 1.23 USD and after few mins it is 1.15 USD. Why is that ?

**Comment by fefsf** [comment]
Because the profitability flucuations continously

**Comment by nerdatwork** [comment]
But the amount should not decrease since the shares are already submitted and accepted. Am I wrong ?

**Comment by nicehashdev** [comment]
Your balance will only decrease when you get payment.

Profitability of cards and devices may constantly change up and down. This is normal.

Also, you should monitor BTC values and not USD - if BTC price in USD is reduced, so is your balance in USD.
