### ISSUE TITLE
Computer crashes after clicking start.

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashMiner-Archived#702]
As soon as I click start in nicehash the monitor goes black and computer stops responding. 

EDIT: i7-6700, 2x 980ti, 1x Radeon 7950. No overclocking
Seems to be an issue with certain algo's on the 980ti's turned all but Equihash off and still crashes. ran two instances of nicehash and have 1x 980ti active in each and it operates stably. 

[log.txt](https://github.com/nicehash/NiceHashMiner/files/819090/log.txt)

**Comment by nicehashdev** [comment]
Try without AMD card in your system. If it still crashes, try without NVIDIA cards.

**Comment by xadonxander** [comment]
Still crashes without AMD card. I use the 980ti's for gaming so if I need to remove them I will just stop using nicehash.

**Comment by xadonxander** [comment]
1.7.5.0 seems to run fine without crashing with all cards installed.

**Comment by xadonxander** [comment]
After turning on sli for the 980ti's it is working in 1.7.5.2 PR 7. I had to deactivate it in previous versions due to stability issues and now it is required.
