### ISSUE TITLE
Nvidia drivers are "out of date" after i updated them 

### ISSUE THREAD

**Issue by anonminer123123** [nicehash/NiceHashMiner-Archived#703]
when i launch the program it will tell me my nvidia drivers are on 364.xx or something like that. So naturally i went through and updated all drivers relevant for this program (my only nvidia GPU, its recognizing my intel CPU fine).

so what do? I've updated everything but on program start up it says im not on version 372.54 for my nvidia drivers, it still says im on 364.xx, which im not because ive updated them and they say theyre fully updated.

this is a laptop that im working on, so im just testing the power of this before i get into mining more. The driver is a Nvidia GEFORCE 720M.

Thanks for your help

**Comment by Timoulis** [comment]
Did you do a clean install, or update the drivers. At time to time it is good to make a clean installation of the drivers.

**Comment by S74nk0** [comment]
@anonminer123123 Do you have **nvidia-smi** installed (under program files in path `\\NVIDIA Corporation\\NVSMI\\nvidia-smi.exe`)? Are you able to mine any algorithm?

**Comment by kenshirothefist** [comment]
The latest official drivers for NVIDIA 720M are of version 378.66. If you still see this warning after updating the driver please uninstall all your Nvidia drivers and make a clean install of latest official driver from **http://www.nvidia.com**.
