### ISSUE TITLE
Rejected (other) CPU mining 

### ISSUE THREAD

**Issue by raigtriv** [nicehash/NiceHashMiner-Archived#704]
If I try mining with xmr-stak-cpu full speed - Rejected (other). Please tell me how can I resolve this problem or what it can be connected? When I use the NiceHashMiner all is well. But I need to use xmr-stak-cpu.

**Comment by kenshirothefist** [comment]
xmr-stak-cpu is **already integrated** into NiceHash Miner - download latest release. If you would like to run in manually you have to use our fork: https://github.com/nicehash/xmr-stak-cpu
