### ISSUE TITLE
Nvidia MSI GTX 1070 with x11gost miner - NHM 1.7.5.1

### ISSUE THREAD

**Issue by Skymax7** [nicehash/NiceHashMiner-Archived#710]
sometimes happen this...

![x11gost](https://cloud.githubusercontent.com/assets/25384176/23701231/487dc8ca-03f6-11e7-9c9c-c68c4c2f88a0.jpg)

**Comment by nicehashdev** [comment]
ccminer_x11gost is unstable miner thus disabled by default. You risk stability of your PC if you decide to use it. There is nothing we can do about it, this ccminer is developed by alexis.
