### ISSUE TITLE
RX 480 DaggerHashimoto Problem

### ISSUE THREAD

**Issue by YasinUsa** [nicehash/NiceHashMiner-Archived#711]
I can benchmark and mine with DaggerHashimoto but when i look to my online stats i can see my rx480 without speed. Hashrate is always null. The dos window shows me hashrate right.

I can mine with genoil ethminer to nice hash without problem, but the nicehash app cant mine to nicehash.

Can somebody help ?

**Comment by S74nk0** [comment]
@YasinUsa what version of genoil ethminer are you using with success with Nice Hash (what parameters are you passing)?

**Comment by YasinUsa** [comment]
@S74nk0

ethminer-0.9.41-genoil-1.1.9

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_ALLOC_PERCENT 100

ethminer.exe --opencl --opencl-platform 1 -SP 2 -G -S daggerhashimoto.eu.nicehash.com:3353 -O Bitcoinadress.RX4808GB 

ethminer.exe -SP 2 -G -S daggerhashimoto.eu.nicehash.com:3353 -O Bitcoinadress.RX4808GB 

Both are working well, with opencl and without opencl.

**Comment by kenshirothefist** [comment]
@YasinUsa which version of NHM are you using and which DaggerHashimoto miners do you have enabled under "Benchmark"?

**Comment by YasinUsa** [comment]
@kenshirothefist

NiceHash Miner v1.7.5.1 
DaggerHashimoto(ethminer) 21.433 MH/s

I have 4 different operating systems on 4 different machines with RX480, always with the same result.

**Comment by kenshirothefist** [comment]
Please try the latest version of this pre-release: https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre

We removed ethminer from NHM due to the fact that it is having issues with various AMD drivers/cards combinations. Most stable/profitable is Claymore Ehereum miner, therefore you're welcome to try it - it is included in the aforementioned pre-release.

**Comment by YasinUsa** [comment]
@kenshirothefist

Great Work thanks for help, problem solved.

 DaggerHashimoto works fine with better performans 24.933 MH/s

There is another problem but its no matter, cant see worker name in online stats with DaggerHashimoto

![workers](https://cloud.githubusercontent.com/assets/20423685/23749133/60a2865a-04cf-11e7-98f3-f4fb8057cded.PNG)

**Comment by kenshirothefist** [comment]
@YasinUsa if you use the latest pre-release https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.2-pre/NiceHashMiner_v1.7.5.2_PreRelease_9.zip then also the empty worker name bug should be fixed.

**Comment by platinum4** [comment]
This probably looks closable.

**Comment by sabaruddin** [comment]
Dear Developer, We are unable to benchmark using Sgminer(DaggerHashimoto), please include back ethminer(Dagger Hasimoto)

**Comment by platinum4** [comment]
Benchmarks work fine on PreRelease_6 just download that and run the benchmarks then copy the numbers over to the new one.  You should be using ClaymoreAMD for ETH anyway.

**Comment by kenshirothefist** [comment]
This issue has been fully resolved in latest Pre-Release with new Claymore Dual miner which now properly implements benchmark.
