### ISSUE TITLE
1.7.5.1 does not work with a benchmark, for the neoscrypt algorithm, Does not work for some video cards

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#712]
The version of NiceHash Miner v1.7.5.1 does not work with a benchmark, for the neoscrypt algorithm for the following video cards: GEFORCE 1060, Radeon Fury, and Radeon R9 390, please fix these problems!

**Comment by kenshirothefist** [comment]
Neoscrypt will be only added as experimental for NVIDIA 6.x devices (GTX 10xx) since it is unstable in some cases. Neoscrypt for AMD is completely disabled due to lack of stable AMD neoscrypt miner.
