### ISSUE TITLE
Web portal not reporting correct speeds 

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner-Archived#713]
Hello , iv been watching and the web portal most of the time doesnt show correct speeds on the gpus  , because of that incorrect amounts of coins are reaching my account , this is a very big deal , please check whats wrong because it might be happening to a lot of ppl

here is the image 

![untitled](https://cloud.githubusercontent.com/assets/9946471/23788684/8ee3326c-056f-11e7-94aa-dd1affde914e.jpg)

**Comment by nicehashdev** [comment]
All pools can only report speed according to accepted shares and do not know the "real hasing power" of your machine. Over longer period of time, statistics kicks in and you get average speed that is very near to your actual speed.

This is not an issue and not related to NHM. Closing.
