### ISSUE TITLE
The version of NiceHash Miner v1.7.5.3 not all algorims run to worked benchmark

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#714]
The version of NiceHash Miner v1.7.5.1 does not work with a benchmark, for the SGMINER (DaggerHashiMoto and CryptoNight + LBRY) not run  algorithm for the following videocards: ---  Radeon Fury, and Radeon R9 390, please fix these problems!

**Comment by Rezobyte** [comment]
What driver version are you using? When was the last time the driver was installed? I had to fully reinstall my 15.12 driver to get benchmarks to work on my R9 Fury Nano cards on 1.7.5.x
After that, mine worked fine. I had the same issue with those same crypto's as well.

**Comment by BARUCHER777** [comment]
@Rezobyte
I`am use Driver ver 16.3.2 in the Win 10\64 bit!

**Comment by kenshirothefist** [comment]
This is fixed in latest Pre-Release.
