### ISSUE TITLE
Equihash miner from Claymore`s 12.2&12.3 Not true benchmark results (Miner version 1.7.5.3)

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#717]
Not true benchmark results for the Claymore Miner for graphic cards RADEON FURY & RADEON R9 390
Very poor performance benchmark test results, erroneous data understating the performance of at least 15-20%....

**Comment by S74nk0** [comment]
@BARUCHER777 Please try the latest [pre-release-03](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.4-pre/NiceHashMiner_v1.7.5.4_PreRelease_03.zip) this should be resolved. Also refer to [this](https://github.com/nicehash/NiceHashMiner/issues/715#issuecomment-287022181) as this seems to be related.

Closing issue...
