### ISSUE TITLE
xmr-stak-cpu will not run

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#718]
xmr-stak-cpu will not run and benchmark. Error says there's no msvcp120.dll try installing software again. I have msvcp120.dll all over my PC and I copied it into the C:\NiceHashMiner_v1.7.5.3\bin\xmr-stak-cpu folder and restarting but it still failed. This has been the case for several NH versions so there is no CPU mining possible.

**Comment by leshiy-gr** [comment]
I have same problem, but error - msvcp140.dll missed. I found this dll and copy it to xmr-stak-cpu folder, have another error ...7b. What needed it to normal work??? And where I can safe download it to install?

**Comment by S74nk0** [comment]
@thaistar @leshiy-gr with the clean install of NHM after the downloads there is a prompt to install **vc_redist.x64.exe** it is located under **bin\\vc_redist.x64.exe** (the file was download from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145)).

**Comment by leshiy-gr** [comment]
S74nk0, I just install update, and have no prompt. Thanks, I install now bin\vc_redist.x64.exe and all ok. Now testing new version

**Comment by leshiy-gr** [comment]
Now xmr-stak-cpu work. But at start, in xmr-stak-cpu window, I have error "Memory init error: Obtained SelockMemoryPrivelege failed"
And "Memory alloc failed: VirtualAlloc failed"

**Comment by S74nk0** [comment]
@leshiy-gr Here is the [Wiki](https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining) for CPU mining.

Closing as issue seems to be related to missing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)
