### ISSUE TITLE
i didint get paid

### ISSUE THREAD

**Issue by alawadhi2012** [nicehash/NiceHashMiner-Archived#719]
dear sire 

i have 4 wallets 3 ofthem ok get paid but the 4th one nothing come please cheack for me

**Comment by nicehashdev** [comment]
If you have questions regarding service NiceHash, write email to support@nicehash.com

Not related to NiceHash Miner software. Closing.

**Comment by alawadhi2012** [comment]
its ok now they fix it 

thanks
