### ISSUE TITLE
Single R9 390x outputs more then rig with 6 x R9 380

### ISSUE THREAD

**Issue by ethimology** [nicehash/NiceHashMiner-Archived#72]
I tried setting the miner on the rig to work with 3, 6 and 12 threads, but it always crashes/hangs (X11).
It works only with default 2 (and 1) threads setting, but with only ~3.1MHs per card, totaling ~18MHs.

390x outputs ~15-16Mhs using sgminer 5.1 by default, so expected output from 380s should be at least around 10MHs per card. However, NiceHash Miner on the rig deploy  sgminer 5.3, so maybe that causes lower hashing power?

All the cards are correctly recognized by NiceHash Miner 1.3.0.3.
Please assist on this matter, thanks!
TT

**Comment by theLosers106** [comment]
R9 380 is a Tonga card and there's no optimized miner for it while R9 390X is a Hawaii card and there's an optimized miner for it.. that is why the speed is slower on R9 380..

**Comment by ethimology** [comment]
Ah, I hoped that there are some settings that may make them work. :)
Nevertheless, thanks a lot for such prompt answer, much appeciated!
TT

**Comment by theLosers106** [comment]
I'll be closing this issue now.. (:
