### ISSUE TITLE
New Claymore_Dual keeps restarting

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner-Archived#720]
Hello , just upgrade to new nice hash  1.7.5.3,  on my biggest machine that has 6x 480 8gb , claymore dual keeps restarting itself , tried to revert to 1.7.5.1  and it works fine with 1.7.5.1 , and it only happens on this machine that has a lot of grafics cards , the others with only 2 , works fine .... maybe a bug with a lot of gpus , can u help me , can i see logs of claymore any ware ???

**Comment by CAVACO-PT** [comment]
iv set like you said  in the notes 

-dual=Pascal  
GPU_FORCE_64BIT_PTR 0 
GPU_MAX_HEAP_SIZE 100 
GPU_USE_SYNC_OBJECTS 1 
GPU_MAX_ALLOC_PERCENT 100 
GPU_SINGLE_ALLOC_PERCENT 100


and in windows virtual memory to 16000 MB

**Comment by MACE-Zer0** [comment]
Found the log file doesnt show any thing

**Comment by CAVACO-PT** [comment]
Bug also happens with dual mining turned off

**Comment by S74nk0** [comment]
@MACE-Zer0 Try troubleshooting it like so:
  - Try mining with individual GPUs and see if one of them causes restarts (faulty GPU)
  - Try increasing grouped GPUs one by one and (mine with 2, 3,...) and see with how many does it work or restarts. 

Most likely one GPU is causing problems here. 

`tried to revert to 1.7.5.1 and it works fine with 1.7.5.1` 

this is with **ethminer**?

**Comment by CAVACO-PT** [comment]
@S74nk0 its with Ethminer that doesnt give any problem , 

im trying now what u recomended , with only 3 gpus , and then if its good enable one by one ... will let u know !!!

**Comment by CAVACO-PT** [comment]
@S74nk0 just so i check if im doing something wrong , where do u set environment variables, ??? in the alogithm in extra launch parameters , or in another place ??? iv set in the extra launch parameters 

-dual=Pascal    -GPU_FORCE_64BIT_PTR 0  -GPU_MAX_HEAP_SIZE 100  -GPU_USE_SYNC_OBJECTS 1  -GPU_MAX_ALLOC_PERCENT 100  GPU_SINGLE_ALLOC_PERCENT 100

But the gpus in claymore dont seem to be mining at 100 %

**Comment by S74nk0** [comment]
@MACE-Zer0 extra launch parameters are meant only for miner parameters. Environment variables are set at NHM startup (and are hard-coded). But as there are different miners that have different Environment variables requirements or recommendations I think that the current hard-coded approach could be causing issues as they don't apply to the miner recommended Environment variables (for example like the ClaymoreDual GPU_FORCE_64BIT_PTR should be 0 but it is set to 1).

Try this [PreRelease](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.4-pre/NiceHashMiner_v1.7.5.4_PreRelease_01a.zip) it sets  GPU_FORCE_64BIT_PTR to 0 (this is just a quick-fix for the feedback for ClaymoreDual issue).

I'll add the option to set Environment variables for specific miners in the future (Pre)Release(_02) so these issues can be resolved easily.

Please give feedback when you can.

**Comment by S74nk0** [comment]
@MACE-Zer0 I have updated the Pre-Release version ([v02](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.4-pre/NiceHashMiner_v1.7.5.4_PreRelease_02.zip)) that handles these settings correctly and can be changed by the user ([Wiki](https://github.com/nicehash/NiceHashMiner/wiki/Setting-Environment-Variables-for-specific-miners))

**Comment by CAVACO-PT** [comment]
@S74nk0  thanks a lot , going to try it .. will tell the outcome in a few min

**Comment by CAVACO-PT** [comment]
@S74nk0 Veryyyyy big diference now .. it works good , no restart on claymore dual , the gpus are mining at 100% , and there are no big ups and downs in speed like there were without the variables , seems fixed , thanks a lot @S74nk0
