### ISSUE TITLE
No devices showing up on my hash miner

### ISSUE THREAD

**Issue by jephillips21** [nicehash/NiceHashMiner-Archived#721]
I have 2 laptops that I have tried using the Nice Hash Miner, but neither shows a device in the miner.  Help??

**Comment by S74nk0** [comment]
@jephillips21 Your HW might not be supported. What CPUs/GPUs are in the laptops?

**Comment by luminustau** [comment]
I'm having the same issue. Version: 1.7.5.3. CPU: Intel Core 2 Duo E8400.

**Comment by nicehashdev** [comment]
Intel Core 2 Duo E8400 is too old CPU, it does not support AES-NI.

If your hardware is too old, you cannot run NiceHash Miner.

**Comment by Rickyen** [comment]
me too. my laptop procescors i-3 and vga nvidia 720m
