### ISSUE TITLE
1.7.5.3 slow GTX 1070 mining issue

### ISSUE THREAD

**Issue by Rezobyte** [nicehash/NiceHashMiner-Archived#722]
When using the new v. 1.7.5.3 (installed last night), my GTX 1070 cards mine Equihash at less than 1/2 speed, 174 sol/s instead of ~400 sol/s. Clean install, no config folder import. The benchmark (precise) output the correct speed of ~400 sol/s, but actual mining is cut roughly in half.

Switching back to 1.7.5.1 shows speeds of ~400 sol/s. Installed latest nVidia GameReady drivers as a test: no change in speed for either nicehash version. Web profitability also shows accepted mining speed is less than 1/2 it's normal rate.

**Comment by Rezobyte** [comment]
After leaving the rig running overnight, the speed hasn't changed; still stuck at roughly 1/2 speed.

**Comment by Rezobyte** [comment]
Founders Edition 1070 (PNY) GPU utilization in MSI Afterburner indicates %100, but temperatures are low, ~45c instead of the ~66c I usually see at %100 load.

**Comment by nicehashdev** [comment]
Show log. Try running EQM manually and see what speed you get.

**Comment by kenshirothefist** [comment]
The same version of EQM is used on all 1.7.5.x versions, therefore this can not be an issue with NiceHash Miner, but rather a miss-usage of either EQM settings or NiceHash Miner settings. What we suggest you is to do a **clean** download of [latest NiceHas Miner](https://github.com/nicehash/NiceHashMiner/releases), make a clean start (don't copy and old configs/settings) and see if it solves your issues (it should). If you still have issues try running EQM manually from ..\bin\eqm\start+restart_script.bat and see if it shows you the correct speed. Also for debugging purposes make sure to not overclock your GPU and have a clean install of latest drivers.
