### ISSUE TITLE
1.7.5.3 no algorithm neoscrypt for GTX1070 

### ISSUE THREAD

**Issue by HolodN** [nicehash/NiceHashMiner-Archived#723]
In most recent versions of the program there is no algorithm neoscrypt for GTX 1070

**Comment by BARUCHER777** [comment]
I`am used ver 1/7/4/3 In this version, this algorithm works, and is present!

**Comment by HolodN** [comment]
but 1.7.4.3 no algorithm X11GOST.

**Comment by nicehashdev** [comment]
Neoscrypt was mostly causing issues and crashes and is very rarely most profitable algorithm thus we decided to remove it.

**Comment by HolodN** [comment]
Neoscrypt is most profitable and stable algorhitm with true miner!!!
