### ISSUE TITLE
 [ERROR] No connection could be made because the target machine actively refused it 127.0.0.1:4002

### ISSUE THREAD

**Issue by TheFalconsNest** [nicehash/NiceHashMiner-Archived#724]
Running Windows 8.1 Pro
Just put in a second Nvidia 1080 in SLI
Drivers okay, temp ok, Nicehash v1.7.5.3 upgrade installed today.

Nicehash runs for a while then screen goes black and will not come back from what I thought was sleep.
Set power to never sleep but still crashes on it's own
Tried to run as admin while writing to Github and before I could submit new issue it crashed on me.
Cold boot brings machine back fine but have to restart Nicehash
I wondered about the SLI is there a diagnostic program?  Windows seems to think it is operational. Temp is okay it has been working on one GPU for a week.  Today added a second.  The second GPU is recognized just fine and Nicehash runs, for a while.

I started poking around in the logs and found a reference to port? 4002 
I don't see Nicehash in the  firewall so it is not like something I can 'allow' Do I have to open the router like I did when trying solo mining?

Any suggestions are welcome.  I am tired of rebooting this machine and have considered taking out the SLI and going back to single GPU and v1.7.5.1 but the current version works on the machine upstairs.  Let me check.  Yup purring like a kitten.  Single Nvidia 980 SC Ti GPU.

I wonder if the twins here allow hashing that I have not seen before. This is the command line in the log
Starting miner [pid(5320)|bin(bin\eqm\eqm.exe)]   -t 0  -cd 0 0 1 1   -a 4002 -l eu -u ..myQR.. -w Eddy2
So what is eqm.exe and the -a 4002 option?

Any ideas?  Thank you.

[2017-03-13 22:15:59] **[INFO] [ERROR] No connection could be made because the target machine actively refused it 127.0.0.1:4002**
[2017-03-13 22:16:01] [INFO] [eqm-MINER_ID(2)-DEVICE_IDs(0,1)] [pid(5320)|bin(bin\eqm\eqm.exe)] Cooling UP, cool time is 10000 ms
[2017-03-13 22:16:05] [INFO] [ERROR] No connection could be made because the target machine actively refused it 127.0.0.1:4002 
...

**Comment by nicehashdev** [comment]
We do not suggest running SLI for mining. Due to badly coded miners (ccminers), mining in SLI will eventually lead to problems. Just disable SLI when you mine and reenable when you need it for gaming. Until all ccminer miners are replaced with our excavator or until NVIDIA fixes stability of their drivers, nothing we can do about it.

**Comment by TheFalconsNest** [comment]
Okay.  I turned the monitor off and it ran overnight.  Though I think the performance is jumping up and down.  I presume that I should get into the NVidia setup and disable SLI.  Will this allow me to run on two GPU's?  I am fine with that.  I will give it a try.

Any idea what the issue was?  -a 4002 parameter.  Was I on the right track?  What are ccminers?  I will try to do some research.  What is an excavator? Can I get one and replace the ccminer, it sort of sounds like the difference between pick and shovel and D10 dozer (heavy equipment).  I apologize for being a noob I am a first time miner.  I do appreciate the reply.  Reliability is a plus for both of us.

Since you are on the line can you tell me where to find the report by worker?  I am suppose to get a bitmain antminer s9 (that will be fun to hook up) so It would be nice to do some comparisons between miners.  Nicehash, so far has been really easy to setup and run.  Many thanks.

**Comment by TheFalconsNest** [comment]
Hello Again,
Thank you for pointing me in the right direction and kick in the pants.  http://cryptomining-blog.com/tag/ccminer/ discusses the open source ccminer.  

I brought everything down and disabled the SLI and started NiceHash.  It seems to recognize the GPU's just fine.  I don't know about the performance but they seem to be operational.  Time will tell if this has solved the issue of refusing 4002.  Research indicated this was network related some TCP/IP handshake idk.

If you have a hint about multi miner report I would appreciate it.  I have looked on FAQ and the summary page.  Maybe it is not what I think it is.  I am hoping for performance statistics by machine/worker.  
Thanks again.
