### ISSUE TITLE
1.7.5.3 no algorithm neoscrypt for GTX1070. Return the algorithm please!!!

### ISSUE THREAD

**Issue by HolodN** [nicehash/NiceHashMiner-Archived#726]
Neoscrypt is most profitable and stable algorhitm with true miner by KlausT!!!

**Comment by fefsf** [comment]
Run it manually then

**Comment by HolodN** [comment]
fefs,  i can either run the miner manually, but better if it will be started automatically by the program.

**Comment by S74nk0** [comment]
It will be [returned](https://github.com/nicehash/NiceHashMiner/releases) here is pre-release [download link](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.4-pre/NiceHashMiner_v1.7.5.4_PreRelease_03.zip)

**Comment by kenshirothefist** [comment]
Neoscrypt will be only added as experimental for NVIDIA 6.x devices (GTX 10xx) since it is unstable in some cases.

**Comment by HolodN** [comment]
Ok, thx!!!
