### ISSUE TITLE
stratum_subscribe timed out on CCMiner

### ISSUE THREAD

**Issue by p1r473** [nicehash/NiceHashMiner-Archived#728]
Hey,
Been using NiceHash for a long time now and its always worked great.
The last 2 weeks, I can't mine on Lyra2REv2 or Lbry (my 2 most profitable) due to the error:

![image](https://cloud.githubusercontent.com/assets/9235633/23981029/1057b796-09da-11e7-9a70-24661d7323d8.png)
![image](https://cloud.githubusercontent.com/assets/9235633/23981119/9b54f9da-09da-11e7-8e99-0b0a1432ba36.png)

Others work. Using the much less profitable Equihash till its fixed...

**Comment by kenshirothefist** [comment]
It seems that you have issues connecting to this location. Please see this [FAQ](https://www.nicehash.com/index.jsp?p=faq#faqs13). If you still have issues please email support@nicehash.com since this is a more general issue for you, not directly related to NiceHash Miner software.
