### ISSUE TITLE
[FEATURE REQUEST] in benchmark, add Rate in mBTC/Day and $/Day

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner-Archived#73]
In Benchmark window it would be nice to see two more columns:
Rate mBTC/Day  and Rate in $/Day for each algorithm

Of course rate needs to be updated with current Exchange rate
either with a button "update rate"  or automatically
(maybe everytime benchmark window is opened?)

This would give a better comparison to the unexperienced user
how much an algorithm is better than another
(because not everybody can guess it from the MH/s column)

**Comment by theLosers106** [comment]
This will be considered in the future releases of NiceHashMiner.. Thanks for the suggestion.. Seems like a valid reason in my opinion..

**Comment by S74nk0** [comment]
Hi @apprehensivemom. This feature has been added in our current BETA and will be available in future releases. I will close this issue.
