### ISSUE TITLE
SgMiner not all algo bench test passed! (AMD Radeon Fury)

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#730]
On the videocard AMD radeon fury (Drv vers 16.3.2) not all algoritm`s run benchmark test///passed!

**Comment by BARUCHER777** [comment]
[https://yadi.sk/i/YlYY0WJx3FzbAp](url)

**Comment by kenshirothefist** [comment]
Do as it tells you - select **Precise** in the "Benchmark Type". Now you have selected **Quick** which can be very inaccurate. If it fails once, try multiple times - the issue is with **sgminer** which is a big tricky, but it works if you're insistent enough.
