### ISSUE TITLE
1.7.5.5 missing .dll

### ISSUE THREAD

**Issue by Timoulis** [nicehash/NiceHashMiner-Archived#731]
After installing 1.7.5.5 i have the message that msvcp140.dll is missing, so my 2 xeons don't work any more.
Only my vga.

Solutions?

**Comment by S74nk0** [comment]
@Timoulis there should be an automatic prompt to install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145). If this wasn't prompt you can install it from the previous link or run **vc_redist.x64.exe** it is located under **bin\\vc_redist.x64.exe**.

Closing...

**Comment by Timoulis** [comment]
Yes that did the trick.

Thank you my friend
