### ISSUE TITLE
2 copies of ccminer_nanashi get launched when mining on a single card

### ISSUE THREAD

**Issue by Kingdud** [nicehash/NiceHashMiner-Archived#732]
I updated to 1.7.5.5 today and since the update Lyra2Rev2 has been spawning 2 copies of ccminer_nanashi instead of just 1. I get no performance benefit from this, and my client only realizes half the profitability of the algorithm because of it. I do, however, see the correct (overall) hash rate reflected on the website. This *may* not be a bug, but it's certainly a strange change that wasn't mentioned in the patch notes. I am using a GTX 1080 to mine, if that matters.

**Comment by Kingdud** [comment]
I retract half my issue. I *do* actually see about a 10-20% performance gain from two miners instead of one. Also, when I push 'stop', CCminer_nanashi continues to mine, and restarts if I kill the process, even though I am not idle and have pushed the 'stop' button.

**Comment by kenshirothefist** [comment]
Go to Settings / Advanced. Set "Miner Start Delay" to **2000** and "Switch Minimum Fixed" to **900**. Then Save settings, close NiceHash Miner and reboot your PC. Try starting NHM once again (to make sure that Lyra2REv2 will be started, enable only Lyra2REv2 under Benchmark / Algorithms).

**Comment by Kingdud** [comment]
Good call. Increasing Miner Restart Delay (there is no Miner Start Delay) to 2000 from 500 (the default, I think; I don't remember changing it) fixed the issue.
