### ISSUE TITLE
Question re Claymore Dual mining on GeForce GTX 1070

### ISSUE THREAD

**Issue by magnoman** [nicehash/NiceHashMiner-Archived#733]
The latest version of Claymore supports dual mining on the GeForce GTX 1070 (I've tested it stand-alone and it works great) but that miner isn't showing up as on option in my NHM 1.7.5.5.  I do have the enable 3rd party miners checked in the settings.  Is there any way to enable Claymore Dual mining for NVIDIA cards in NHM or are you only supporting AMD at this time?

**Comment by kenshirothefist** [comment]
No, we will not support Claymore for NVIDIA, because we're developing [our own NVIDIA miner](https://bitcointalk.org/index.php?topic=1777827.0), which will also support dual (multi) algorithm mining.

**Comment by wcchye** [comment]
NHM 1.7.5.13 still no dual mining for Nvidia 1070? what happen?

**Comment by wcchye** [comment]
NHM 1.7.5.13 still no Claymore miner for Nvidia 1070 also? Why?
