### ISSUE TITLE
Optiminer doesn't work with amd 7950

### ISSUE THREAD

**Issue by Fossius** [nicehash/NiceHashMiner-Archived#734]
Optiminer immediately close after launch. But in 1.7.5.3 nicehash miner work fine.

**Comment by S74nk0** [comment]
@Fossius nothing has been changed from v1.7.5.3 to v1.7.5.5 regarding Optiminer. Do you have the same settings in both versions?

**Comment by Fossius** [comment]
same settings in both versions, even with "clear install" problems are

**Comment by S74nk0** [comment]
@Fossius Optiminer can be flagged by Windows Defender or some other AV. Is NHMv1.7.5.5 folder white-listed?

**Comment by Fossius** [comment]
[log.zip](https://github.com/nicehash/NiceHashMiner/files/850469/log.zip)


Have no any AV, Windows Defender is off. win7x64

**Comment by Fossius** [comment]
I think the problem is in 

> Environment variable GPU_FORCE_64BIT_PTR set to 0

**Comment by S74nk0** [comment]
@Fossius clear the System Environment variable for your os user. Open **\\configs\\MinerSystemVariables.json** and check **GPU_FORCE_64BIT_PTR** for **"bin_3rdparty\\optiminer_zcash_win\\Optiminer.exe"** this should be set to 1. NHM v1.7.5.3 and v1.7.5.5 have the same OptiminerZcash version and all OptiminerZcash logic is the same. Try clearing System Environment Variable check **\\configs\\MinerSystemVariables.json** settings for Optiminer that **GPU_FORCE_64BIT_PTR** is set to **1**, try running it. 

With the provided logs it seems that one GPU finishes benchmark fine while the other does not due to **GPU_FORCE_64BIT_PTR=1** but I think this is a false positive since this is set.

**Comment by Fossius** [comment]
The problem is in code 100%
Have just tried NiceHashMiner_v1.7.5.4_PreRelease_01 - work, and NiceHashMiner_v1.7.5.4_PreRelease_01a where is declared: "> Environment variable GPU_FORCE_64BIT_PTR set to 0" - doesn't work

**Comment by S74nk0** [comment]
@Fossius v1.7.5.4_PreRelease_01 and NiceHashMiner_v1.7.5.4_PreRelease_01a set the Environment Variables for the system user (Globaly).  v1.7.5.5 sets it for the running process. Your issue cannot be reproduced on testing rigs. GPU_FORCE_64BIT_PTR is set to 1 for Optiminer. I am not sure what can be causing the issue in your case, this change [resolved a bug](https://github.com/nicehash/NiceHashMiner/issues/720#issuecomment-286903016) and I am not able to reproduce your issue.

You can try the following:
  - solution 01:
    - delete **\\configs\\MinerSystemVariables.json** file (this will create the a new default file after new start)
    - start NHM and test Optiminer (**"GPU_FORCE_64BIT_PTR": "1"** will be set to 1)

  - solution 02:
    - download [set_GPU_USE_SYNC_OBJECTS_1.zip](https://github.com/nicehash/NiceHashMiner/files/851191/set_GPU_USE_SYNC_OBJECTS_1.zip) unzip it and run it this will set **"GPU_FORCE_64BIT_PTR": "1"** for your user
    - download [MinerSystemVariables.zip](https://github.com/nicehash/NiceHashMiner/files/851181/MinerSystemVariables.zip) unzip it and copy over **\\configs\\MinerSystemVariables.json** this config doesn't have Optiminer settings and will use the global setting.

Report back which solution works. Try them in order.

**Comment by Fossius** [comment]
unfortunately solutions doesn't help
but fact is:  v1.7.5.4_PreRelease_01 - work fine, v1.7.5.4_PreRelease_01a and higher - doesn't work

**Comment by kenshirothefist** [comment]
We tested Optiminer in various scenarios, but since Optiminer is not optimized for Windows, it simply does not work on all systems. If it does not work for you no matter what you set, then we simply suggest you to **enable Claymore Equihash** miner instead of Optiminer.

**Comment by S74nk0** [comment]
[Related](https://github.com/nicehash/NiceHashMiner/issues/739)
