### ISSUE TITLE
Start mining when computer locked

### ISSUE THREAD

**Issue by justsomedudeonthenet** [nicehash/NiceHashMiner-Archived#736]
If NiceHash is set to start mining when idle, it would be nice if it started immediately when the computer is locked.

I have a fairly long minimum idle delay, so it doesn't kick in when I'm watching a movie or something.

But when I lock my computer that's a pretty clear sign that it isn't being used, and the miner can start immediately.

**Comment by kenshirothefist** [comment]
This is a very custom feature and we won't be implementing it. You can schedule tasks like this in the Task Scheduler (Event triggered).
