### ISSUE TITLE
GTX 1070 and dual miner

### ISSUE THREAD

**Issue by gorilza** [nicehash/NiceHashMiner-Archived#737]
ETH on GTX1070 start with ethminer and not test speed( and run with) claymore dual eth.

**Comment by kenshirothefist** [comment]
First of all, make sure you are **NOT OVERCLOCKING**. Secondly, what exactly do you mean by Claymore Dual Eth? Claymore Dual Eth is **NOT** supported for NVIDIA in NiceHash Miner. Please explain your issues in more details.

**Comment by Teo99** [comment]
Claymore dual works fine from command line, either with single mining (ethereum) or with dual mining (ethereum + decred).
But it isn't listed in Nicehash Miner, as available miner.

**Comment by kenshirothefist** [comment]
We do not support Claymore Dual miner for NVIDIA and we are not planning to. We are developing our own [multi algorithm miner called excavator](https://bitcointalk.org/index.php?topic=1777827.0) which will support dual/multiple algorithm mining in the future.
