### ISSUE TITLE
NiceHashMiner.exe not opening

### ISSUE THREAD

**Issue by iSpec** [nicehash/NiceHashMiner-Archived#738]
Upon extracting the zip file and clicking the .exe file for NiceHash miner version 1.7.5.5, an error window pops up and says "Windows cannot access the specified device, path, or file. You may not have appropriate permissions to open the item." I am attempting to open the .exe on an administrator account, and I have tried to run the exe as admin, but to avail.
![screenshot_5](https://cloud.githubusercontent.com/assets/19579963/24074946/dad5e532-0be8-11e7-8575-5a48543c2e64.png)

**Comment by fefsf** [comment]
make sure you right click each of the .exe files and goto properties and check the unblock option at the bottom

**Comment by kenshirothefist** [comment]
Also make sure that antivirus/antitrojan/defender/firewall is not blocking NiceHash Miner. You should put the whole "NiceHash Miner" folder as an exception (skip checks) in antivirus/antitrojan/defender/firewall. This is because some antivirus/antitrojan/defender/firewall detects "NiceHash Miner" as false-positive while it is of course completely virus-free (if downloaded from this GitHub official Releases page).

**Comment by systemx** [comment]
I am also not able to launch NHM from 1.7.5.3 up to 1.7.5.6 PreRel 1a.

1.7.3.3 launches for me however.

**Comment by S74nk0** [comment]
@iSpec @systemx What is the full path (ex: **C:\\some\\path\\...**) where NHM is located?

**Comment by iSpec** [comment]
The path for NHM is C:\Users\(Me)\Desktop\NiceHashMiner_v1.7.5.5\NiceHashMiner.exe

**Comment by iSpec** [comment]
NHM was working for me a few days ago on v1.7.5.1, but recently it just decided to give me that error again. I tried updated, but nothing changed.

**Comment by systemx** [comment]
Mine's at C:\Users\systemx\Desktop\miners\NiceHashMiner_v1.7.5.6_PreRelease_01a

**Comment by S74nk0** [comment]
@systemx @iSpec The previous versions were on the same path and were working? Can you please provide information from the Event Viewer?

**Comment by systemx** [comment]
Yes, my previous NHM versions have always been in C:\Users\systemx\Desktop\miners\,

Event Viewer produces something.

**Event ID 1023**
.NET Runtime version 2.0.50727.8000 - Fatal Execution Engine Error (5AB9037A) (80131506)

**Event ID 1000**
Faulting application name: NiceHashMiner.exe, version: 1.7.5.7, time stamp: 0x58d5255d
Faulting module name: mscorwks.dll, version: 2.0.50727.8000, time stamp: 0x526720fc
Exception code: 0xc0000005
Fault offset: 0x00001a10
Faulting process id: 0x%9
Faulting application start time: 0x%10
Faulting application path: %11
Faulting module path: %12
Report Id: %13
Faulting package full name: %14
Faulting package-relative application ID: %15

**Event ID 1001**
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: NiceHashMiner.exe
P2: 1.7.5.7
P3: 58d5255d
P4: mscorwks.dll
P5: 2.0.50727.8000
P6: 526720fc
P7: c0000005
P8: 00001a10
P9: 
P10: 

Attached files:

These files may be available here:
C:\Users\systemx\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_NiceHashMiner.ex_f4415ca8e383aceefeaadd64a145dcddf67d447_00000000_320ae486

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2b176a38-1240-11e7-829a-50e549ea4cec
Report Status: 4100
Hashed bucket: 

**App crash report**
Version=1
EventType=APPCRASH
EventTime=131350188478271220
ReportType=2
Consent=1
ReportIdentifier=2b176a38-1240-11e7-829a-50e549ea4cec
WOW64=1
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=NiceHashMiner.exe
Sig[1].Name=Application Version
Sig[1].Value=1.7.5.7
Sig[2].Name=Application Timestamp
Sig[2].Value=58d5255d
Sig[3].Name=Fault Module Name
Sig[3].Value=mscorwks.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=2.0.50727.8000
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=526720fc
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=00001a10
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
UI[2]=C:\Users\systemx\Desktop\miners\NiceHashMiner_v1.7.5.7\NiceHashMiner.exe
LoadedModule[0]=C:\Users\systemx\Desktop\miners\NiceHashMiner_v1.7.5.7\NiceHashMiner.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\SYSTEM32\KERNEL32.dll
LoadedModule[4]=C:\Windows\SYSTEM32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\SYSTEM32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\SYSTEM32\msvcrt.dll
LoadedModule[7]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[8]=C:\Windows\SYSTEM32\RPCRT4.dll
LoadedModule[9]=C:\Windows\SYSTEM32\SspiCli.dll
LoadedModule[10]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[11]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\Windows\SYSTEM32\SHLWAPI.dll
LoadedModule[14]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[15]=C:\Windows\SYSTEM32\USER32.dll
LoadedModule[16]=C:\Windows\SYSTEM32\GDI32.dll
LoadedModule[17]=C:\Windows\system32\IMM32.DLL
LoadedModule[18]=C:\Windows\SYSTEM32\MSCTF.dll
LoadedModule[19]=C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorwks.dll
LoadedModule[20]=C:\Windows\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.8428_none_d08a11e2442dc25d\MSVCR80.dll
LoadedModule[21]=C:\Windows\SYSTEM32\shell32.dll
LoadedModule[22]=C:\Windows\SYSTEM32\SHCORE.dll
LoadedModule[23]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[24]=C:\Windows\assembly\NativeImages_v2.0.50727_32\mscorlib\3de119146ed0e59408f896aa69cdfc42\mscorlib.ni.dll
LoadedModule[25]=C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorsec.dll
LoadedModule[26]=C:\Windows\SYSTEM32\WINTRUST.dll
LoadedModule[27]=C:\Windows\SYSTEM32\CRYPT32.dll
LoadedModule[28]=C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.9600.17810_none_7c5b6194aa0716f1\COMCTL32.dll
LoadedModule[29]=C:\Windows\SYSTEM32\MSASN1.dll
LoadedModule[30]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[31]=C:\Windows\system32\rsaenh.dll
LoadedModule[32]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[33]=C:\Windows\SYSTEM32\imagehlp.dll
LoadedModule[34]=C:\Windows\SYSTEM32\ncrypt.dll
LoadedModule[35]=C:\Windows\SYSTEM32\NTASN1.dll
LoadedModule[36]=C:\Windows\SYSTEM32\gpapi.dll
LoadedModule[37]=C:\Windows\SYSTEM32\cryptnet.dll
LoadedModule[38]=C:\Windows\SYSTEM32\WLDAP32.dll
LoadedModule[39]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[40]=C:\Windows\SYSTEM32\NSI.dll
LoadedModule[41]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[42]=C:\Windows\SYSTEM32\ole32.dll
LoadedModule[43]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[44]=C:\Windows\system32\uxtheme.dll
LoadedModule[45]=C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorjit.dll
LoadedModule[46]=C:\Windows\assembly\NativeImages_v2.0.50727_32\System\20af51394609c937507288c2b1cf2c8c\System.ni.dll
LoadedModule[47]=C:\Users\systemx\Desktop\miners\NiceHashMiner_v1.7.5.7\Newtonsoft.Json.dll
LoadedModule[48]=C:\Windows\assembly\NativeImages_v2.0.50727_32\System.Drawing\d76ae95d56d39a59f727f5518ac8e396\System.Drawing.ni.dll
LoadedModule[49]=C:\Windows\assembly\NativeImages_v2.0.50727_32\System.Windows.Forms\a673aacf407b499981342bb709cce917\System.Windows.Forms.ni.dll
LoadedModule[50]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[51]=C:\Windows\assembly\NativeImages_v2.0.50727_32\System.Management\9f0fe59d471b42a6bbfe4ed1ca78aaa3\System.Management.ni.dll
LoadedModule[52]=C:\Windows\SYSTEM32\clbcatq.dll
LoadedModule[53]=C:\Windows\system32\wbem\wmiutils.dll
LoadedModule[54]=C:\Windows\SYSTEM32\OLEAUT32.dll
LoadedModule[55]=C:\Windows\SYSTEM32\wbemcomn.dll
LoadedModule[56]=C:\Windows\SYSTEM32\WS2_32.dll
LoadedModule[57]=C:\Windows\system32\wbem\wbemprox.dll
LoadedModule[58]=C:\Windows\Microsoft.NET\Framework\v2.0.50727\wminet_utils.dll
LoadedModule[59]=C:\Windows\system32\wbem\wbemsvc.dll
LoadedModule[60]=C:\Windows\system32\wbem\fastprox.dll
LoadedModule[61]=C:\Windows\assembly\NativeImages_v2.0.50727_32\System.Xml\672138dc2f47a077f59ef14290a6973e\System.Xml.ni.dll
LoadedModule[62]=C:\Windows\assembly\NativeImages_v2.0.50727_32\System.Data\5eedd7ea1972a47f490dc3949879e473\System.Data.ni.dll
LoadedModule[63]=C:\Windows\assembly\GAC_32\System.Data\2.0.0.0__b77a5c561934e089\System.Data.dll
FriendlyEventName=APPCRASH
ConsentKey=APPCRASH
AppName=NiceHashMiner
AppPath=C:\Users\systemx\Desktop\miners\NiceHashMiner_v1.7.5.7\NiceHashMiner.exe
ReportDescription=Stopped working
ApplicationIdentity=00000000000000000000000000000000

**Comment by systemx** [comment]
I fired up a VM and loaded Win 8.1 Pro (identical to my current workstation). NHM 1.7.5.7 loads fine after the OS asked me to download and install .NET 2.0 and 3.5 to launch the app. This leads me to believe that my current framework may have some issues. I am going to disable both the .NET 2.0/3.5 feature and have it reinstalled to see if it resolves the issue.

**Comment by sadgb** [comment]
same issue, same system log entries.

**Comment by S74nk0** [comment]
@systemx Did .NET 2.0 3.5 re-installation fixed this issue?

@sadgb What is your Windows version? Do you have the latest updates and .NET 2.0-3.5 run-time installed?

**Comment by sadgb** [comment]
i am trying to reinstall right now.  It is windows 10, not sure about latest updates

**Comment by sadgb** [comment]
Funny one - i can't reinstall .net because of strange 0x800f081f error. Also, i am unable to insert install disk to my rig, so i will try to fix it and write about results after

**Comment by kenshirothefist** [comment]
Seems like bad Windows Install or .NET install issue - will be fixed by reinstalling. Closing now.

**Comment by systemx** [comment]
Sorry for the delayed response. I just re-installed the .NET framework and as expected from the VM's observation, 1.7.5.7 loads perfectly. Thanks for the support!
