### ISSUE TITLE
Ati 7850 and nicehash 1.7.5.5

### ISSUE THREAD

**Issue by dadoremix** [nicehash/NiceHashMiner-Archived#739]
hi
I upgrade to 1.7.5.5 from 1.7.5.3
Stop working optiminier_zcash_win .. on 1.7.5.3 still working
cmd windows come and gone in 1-2 sec.. so i cant read what is wrong
but i see, he run to  Connecting to equihash.eu.nicehash.com:3357. and gone
so i disable these, and run via equihash claymoreAND.. or go back to 1.7.5.3

also some time is not working cryptonight SGMINER .. cant run benchmark..

**Comment by kenshirothefist** [comment]
Go to Settings / Advanced. Set "Miner Start Delay" to 2000 and "Switch Minimum Fixed" to 900. Then Save settings, close NiceHash Miner and reboot your PC. Try starting NHM once again (to make sure that Lyra2REv2 will be started, enable only Lyra2REv2 under Benchmark / Algorithms).

**Comment by dadoremix** [comment]
nope.. not working
some problem is with exe of nicehash 1.7.5.5 .. 3 is working fine
i try only copy exe file to another folder
build 1.7.5.5. dont work with optiminer_zcash_win .. at me

**Comment by S74nk0** [comment]
@dadoremix Are you running NiceHash Miner as Administrator or a user with Administrator privileges?

**Comment by dadoremix** [comment]
As admin acc
Try also with run as admin

I can provide teamviwer for closer look

19.03.2017., u 13:13, Stanko Krstić <notifications@github.com> napisao:

**Comment by S74nk0** [comment]
@dadoremix Try running it as a **"normal" (a user that doesn't have Admin access)** user and report back if it works. I suspect here might be the problem. Also you can try setting **GPU_USE_SYNC_OBJECTS 1** in the **Environment variables** but set this for the whole **system** and try running it as Administrator. 

Please report back if running as normal user works and also if setting **GPU_USE_SYNC_OBJECTS 1** for the **System** works when running as **Administrator**

**Comment by S74nk0** [comment]
@dadoremix After trying the steps provided in the previous comment try also [this](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.6-pre/NiceHashMiner_v1.7.5.6_PreRelease_01a.zip) and report back if it works.

**Comment by dadoremix** [comment]
I do not know in which file I have entered GPU_USE_SYNC_OBJECTS 1
where is "Environment variables" ?

here is log for problem..
http://pastebin.com/2pHucv4T

first i run with claymore zcah.. then i disable to force optiminer

@S74nk0 i try your file.. 1.7.5.6 pre release.. working again for zcash optiminer
but benchmark dont work .. i try to reset and run benchmark..

**Comment by mustafahp53** [comment]
i am also getting problem in starting mining.when i start mining it says that some dll. files is missing and you have to reinstall the program.

**Comment by S74nk0** [comment]
@dadoremix which benchmark doesn't work?

@mustafahp53 Open a new issue and give as much information as possible (vague descriptions will be closed)

**Comment by dadoremix** [comment]
<a href="http://www.oldschool-samp.com/slike/?v=inkedscree.jpg"><img src="http://www.oldschool-samp.com/slike/thumbs/inkedscree.jpg" border="0"></a>
nicehash 1.7.5.6 beta01a
try optiminer_zcash benchmark.. not working.. 
only if i write manual speed
also dont work from older version cryptonight sgminer

**Comment by dadoremix** [comment]
<a href='https://postimg.org/image/wrtovdndt/' target='_blank'><img src='https://s8.postimg.org/wrtovdndt/Screenshot_2017_03_21_18_34_15.png' border='0' alt='postimage'/></a>
benchmark not working for 2 miners

**Comment by kenshirothefist** [comment]
Have you tried running "Precise" benchmark on these two?

**Comment by dadoremix** [comment]
yes yes
try quick, standard and precise
not working bench.. so i write manualy something and voila.. runing

proff
<a href="https://ibb.co/diC7gF"><img src="https://thumb.ibb.co/diC7gF/Screenshot_2017_03_21_23_28_35.png" alt="Screenshot_2017_03_21_23_28_35" border="0"></a>

**Comment by S74nk0** [comment]
@dadoremix Please do the following:
  - delete the logs folder
  - reproduce the steps that cause the benchmark issue
  - zip the logs folder and post it here

Did this benchmark issue happen with previous versions?

**Comment by dadoremix** [comment]
http://www.megafileupload.com/1qgaf/logs.zip


yes.. benchmark was problem with 1.7.5.3 ?

**Comment by S74nk0** [comment]
@dadoremix please upload the **logs.zip** file directly to GitHub.

**Comment by dadoremix** [comment]
sorry, but dont know how

i select zip file.. and recive message..  
We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by kenshirothefist** [comment]
@dadoremix Please send the ZIP package with logs to email: support@nicehash.com. Just write the same subject as the subject of this GitHub Issue. Thanks!

**Comment by dadoremix** [comment]
ok i send
but you just can use upper link..

**Comment by S74nk0** [comment]
@dadoremix I have checked your mail. Optiminer/Zcash is reporting that **GPU_USE_SYNC_OBJECTS 1** is not set. This variable is set in [v1.7.5.7](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.7) for the system and individually per miner. It seems that this setting isn't working correctly when running as Administrator. Copy this [MinerSystemVariables.zip](https://github.com/nicehash/NiceHashMiner/files/889796/MinerSystemVariables.zip) to **configs** (unzipped of course), this will not set any environment variables per miner (here could be the issue when running as Administrator). The log for **sgminer** CryptoNight is emtpy, I suspect that the miner closes immediately after starting (it is unclear why from the logs).

**Comment by kenshirothefist** [comment]
@dadoremix So are you sure that you're running v1.7.5.7? If not, make sure you run this latest version. Please report back if you're still facing the original issues.

**Comment by dadoremix** [comment]
benchmark works with files from last post.. S74nk0 has posted
for optiminier_zcash_win

cryptonight sgminer not woking

**Comment by kenshirothefist** [comment]
@dadoremix Unfortunately cryptonight sgminer is known to cause issues in particular combinations of gpus/drivers. In this case we suggest you to use the other available cryptonight option (claymore). Since other issues seems to be resolved I'm now closing this issue.
