### ISSUE TITLE
Ethminer not appearing (R9 390)

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#740]
On the benchmark page, Ethminer / ethereum is missing from the list of algorithms - i've double checked and ethminer.exe is present in /bin - what could be wrong?

**Comment by S74nk0** [comment]
@kingblah ethminer is removed due to stability issues (submitting stales in certain cases). This change is present from [v1.7.5.3](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.3).

Closing...
