### ISSUE TITLE
Excavator equihash not working on GTX850M

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner-Archived#741]
Benchmark fails.
Manual start with included script also fails - see [https://drive.google.com/file/d/0B2arX3raSawBcmo4NEV2R2RERHM/view?usp=sharing](url)
Works with pascal though

**Comment by nicehashdev** [comment]
There is a bug in excavator for SM5.0 devices on equihash. We are aware of this. For now, you can solve this with setting mode '-c1 1' or wait for next prerelease.
