### ISSUE TITLE
Pre-release 1.7.5.6 PreRelease_01a excavator caused driver crash on 750 ti's for Equihash.

### ISSUE THREAD

**Issue by frazier345** [nicehash/NiceHashMiner-Archived#742]
I have three rigs one with 1 1070 and 5 750 ti and 2 with 1 or 2 750 ti.  During Benchmarking on Equihash on the one system it did full crash of the driver and did not benchmark Equihash or Pascal.  The other two terminated the benchmarks for Equihash for the 750 ti's however it did benchmark on the 1070.  (I didn't see crash notices on those computers.)  

System info
Windows 8.1 Pro
Driver 376.33 on 2 and 378.49 on third.

**Comment by nicehashdev** [comment]
There is a bug in excavator for SM5.0 devices on equihash. We are aware of this. For now, you can solve this with setting mode '-c1 1' or wait for next prerelease.

**Comment by frazier345** [comment]
Next Prerelease 1b still terminates the benchmark even with -c1 1 in the extra launch parameters for 750 ti.

**Comment by S74nk0** [comment]
@frazier345 The issue you are having is fixed in [NiceHashMiner_v1.7.5.6_PreRelease_02](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.6-pre/NiceHashMiner_v1.7.5.6_PreRelease_02.zip). If this doesn't work for you reopen this issue.
