### ISSUE TITLE
Windows 10 64 bit still gives me a setup error.

### ISSUE THREAD

**Issue by Kerwin123** [nicehash/NiceHashMiner-Archived#744]
Error message: Windows 10 cannot access specified device, path, or file. You may not have the appropriate permission to access them. 
I tried closing all AV and Anti-malware programs. No luck.
Tried to change the user privileges under safe mode. No luck.
Close window firewall. No luck.
Use of whitelist. No luck. 
GPU computing: 6.1
GPU: Up-to-date 
No TPM module 
C++ and other firmware is up-to-date
What can I do to solve this access denial issue?

**Comment by Kerwin123** [comment]
Note: I tried the previous two old versions no luck.
Beta is still no luck.
The bin solution doesn't work either.

**Comment by semisane** [comment]
Out of curiosity have you tried running it as admin? 

Is this a new issue or has NHM worked prior to this?

The error message you're receiving is a generic one from Windows basically saying that you don't have the appropriate user rights to run the file. Is this computer part of a domain?

Here's a link to MS:
https://support.microsoft.com/en-us/help/2669244/-windows-cannot-access-the-specified-device,-path,-or-file-error-when-you-try-to-install,-update-or-start-a-program-or-file

**Comment by Kerwin123** [comment]
No, it is not part of the domain. 
I tried to run it as admin, but same error.
I was trying to set up NHM, and it is my first time installing it.

**Comment by semisane** [comment]
Can you take a screenshot of the error, as well as the permissions associated with NHM?

What AV are you using?

**Comment by kenshirothefist** [comment]
@Kerwin123 Can you please give us some feedback? Most probably it's your Antivirus/Defender blocking your NiceHash Miner. Try to exclude the path/folder where NiceHash Miner is installed from in your Antivirus/Defender settings.
