### ISSUE TITLE
Windows 10 x64 GTX1070 lot of zeroes in excavator miner.

### ISSUE THREAD

**Issue by HolodN** [nicehash/NiceHashMiner-Archived#745]
Excavator miner prints a lot of zeros in the command window after the words "Efficiency", but the miner is running. GTX1070, Windows 10 x64 v. 1607, Nvidia Driver 375.70

**Comment by HolodN** [comment]
![noname](https://cloud.githubusercontent.com/assets/26391137/24151903/1a96ef6c-0e5b-11e7-893c-e5266c0af91c.png)

**Comment by nicehashdev** [comment]
Install latest NVIDIA drivers or copy nvml.dll from your driver folder into excavator folder.
