### ISSUE TITLE
Github Releases Page - bins.zip old

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner-Archived#746]
On the releases page under 1.7.5.5
https://github.com/nicehash/NiceHashMiner/releases

It mentions to click here for the bins if the miner doesnt download them

The url is old as it shows 1_7_5_2 instead of 1_7_5_5
https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/bin_1_7_5_2.zip

The 3rd party tool shows 1_7_5_4 instead of 1_7_5_5
https://github.com/nicehash/NiceHashMiner/releases/download/1.7.0.0-dev/bin_3rdparty_1_7_5_4.zip

**Comment by S74nk0** [comment]
@computeronix  this is ok. The release version and the binary download zip versions don't always match. 
[Here](https://github.com/nicehash/NiceHashMiner/blob/92a3893519da5d3a2d24498e6d24a885daee2064/NiceHashMiner/Utils/MinersDownloadManager.cs) are the download links for v1.7.5.5 (same links).

Closing issue...

**Comment by billmcilhargey** [comment]
Perfect thanks!!
