### ISSUE TITLE
Lyra2Rev2 algorithm switching unreliable.

### ISSUE THREAD

**Issue by Kingdud** [nicehash/NiceHashMiner-Archived#747]
Since 1.7.5.3 I've noticed switching to Lyra2Rev2 from any algorithm can be unstable. Specifically, Lyra2Rev2 (ccminer_nanashi) may fail to launch. The problem is not the miner/system though. Closing nicehashminer and re-lanching the program clears whatever error state and allows mining to continue. Rebooting the PC/graphics card resets are not required. The error message you see trying to launch Lyra2Rev2 once this issue occurs is "Unable to find any CUDA devices" or something similar to that (the miner reports this, then exits). 

Attempting to launch the miner through the command line reveals the same issue. Once Nicehashminer is restarted, however, both the CLI and nicehashminer 'start' method allow for mining. 

I have no idea how to go about troubleshooting this problem. My system is an i7 6700k with a GTX 1080. Nothing (save the actual miner) is running on the GPU; I am using the integrated graphics card to render the desktop while nicehash mines in the background. In Windows I have the monitors from the GPU 'disconnected' through the Customize Desktop screen, they aren't even rendering a blank desktop.

**Comment by Kingdud** [comment]
![err1](https://cloud.githubusercontent.com/assets/20249763/24197045/6bf4eeba-0ed6-11e7-9e6c-44dec83f2471.PNG)
![err2](https://cloud.githubusercontent.com/assets/20249763/24197044/6bf4f6a8-0ed6-11e7-9914-6d4da75b4f39.PNG)

Note the time difference. All I did was close and restart Nicehashminer (the actual application, not the GPU mining app) and the problem went away. How do I debug this?

**Comment by Kingdud** [comment]
Whatever causes this issue, the 'fix' that clears it is applied during startup of nicehashminer.exe. I'm trying to see what operation(s) happen only during startup. Specifically: the issue where ccminer_nanashi reports "unable to query" happens even when nicehashminer.exe is closed, and persists until nicehashminer.exe has started up again. When I have the issue happen again I'll try to determine if the issue is cleared before or after device detection takes place.

**Comment by kenshirothefist** [comment]
@Kingdud This really seems to be a specific issue to your environment. Please do the following:

- make sure to reboot your computer/rig and only start NiceHash Miner (no other apps) before you do testing/benchmarking
- make sure you are **not** overclocking

If you still hit on this issue there is no other way for you but to disable Lyra2REv2 algorithm for your device because this seems to be a specific ccminer-nanashi miner issue for your environment.
