### ISSUE TITLE
NHM 1.7.5.5 GPU excavator (Pascal) shows ridiculous hashrate

### ISSUE THREAD

**Issue by nightmaker** [nicehash/NiceHashMiner-Archived#748]
I am using NVIDIA Quadro 6000 (old card).

NHM detects automatically to mine Pascal with excavator. However the hashrate value is ridiculous. The value will gradually goes down until about 88 GH/s (still ridiculous). And actually it is not mining at all (checked with NH statistic, no Pascal submission at all).

How I really wish I can get 1 BTC/day... LOL

![exca](https://cloud.githubusercontent.com/assets/23731947/24187065/435aa504-0f16-11e7-890b-4d9aa4139aad.PNG)

**Comment by S74nk0** [comment]
Your GPU is not supported. This has been fixed in the [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.6-pre) in **v1.7.5.5** disable Pascal **manually** (**Excavator** is supported only SM5.x+ GPUs ).

Closing issue...
