### ISSUE TITLE
NVIDIA GTX 680 & 770 Equihas terminates

### ISSUE THREAD

**Issue by Sifontes** [nicehash/NiceHashMiner-Archived#752]
Not benchmarking GTX 680 and 770 on equihash. Any suggestions.

**Comment by fefsf** [comment]
Did you try the prerelease 02?

**Comment by Sifontes** [comment]
Have not! Will wait for official release

**Comment by S74nk0** [comment]
@Sifontes nheqminer is used for these GPUs (SM.x.y < SM 5.0). This issue is known and there aren't any plans to fix compatibility for these cards. GPUs [will be filtered](https://github.com/nicehash/NiceHashMiner/commit/f1f0f619e7c852778966bfd20d5c15e3d0cd57e2).

Closing...
