### ISSUE TITLE
Claymore ZEC Miner is on 12.4 now

### ISSUE THREAD

**Issue by platinum4** [nicehash/NiceHashMiner-Archived#754]
Works OK if I drag and drop it in place of 12.3 on 1.7.5.6.pr.02

https://mega.nz/#F!P0ZjFDjC!Cmb-ZRqlbAnNrajRtp4zvA

**Comment by S74nk0** [comment]
@platinum4 Thanks for the heads up. The download package is updated to include v12.4

Closing...
