### ISSUE TITLE
Ethereum mining a lot less than the predicted mBTC/Day

### ISSUE THREAD

**Issue by NogaAllTK** [nicehash/NiceHashMiner-Archived#756]
Hi Im using Radeon Pro Duo and Nicehas tells me that Im mining 54mhs/s but when I click to check my stats online it ony registers 20 or so. All the other algorithms are fine. Is there a way to solve this?

**Comment by S74nk0** [comment]
@NogaAllTK Ethereum needs a while to be averaged (up to 30minutes)

**Comment by NogaAllTK** [comment]
I left for 4 hours and it didn't go up. Went to work then came back and saw the history.

**Comment by kenshirothefist** [comment]
@NogaAllTK Which DaggerHashimoto miner do you have enabled in the Bechmark options? Claymore or sgminer? If one is not working for you correctly, try the other one.

**Comment by NogaAllTK** [comment]
It's working and it says I'm mining an amount but in fact I'm receiving half of it.

**Comment by kenshirothefist** [comment]
@NogaAllTK What "is working"? Can you please clarify? As said in previous comment please report which DaggerHashimoto miner do you have enabled in the Bechmark options? Claymore or sgminer?

**Comment by nerdatwork** [comment]
I too want to convey the same issue. My main issue is 15% to 20% rejected shares for second coin in Claymore's dual mining. Which results in lesser mbtc mount than predicted. I monitored exactly 24 hours. Also where can I enter other claymore options like -mvddc or -cvddc ?

**Comment by kenshirothefist** [comment]
@nerdatwork please see here: https://github.com/nicehash/NiceHashMiner/wiki/Enable-ClaymoreDual-with-Decred-Lbry-Pascal This is completely unrelated issue.

@NogaAllTK can you please provide some feedback (see my last comment).

**Comment by NogaAllTK** [comment]
Sorry for the delay on the feedback I got so much work these days it's driving me crazy. I tested with all daggerhashimoto miners, what happens is, I get way less mbtc per day than i was supposed to be getting. My card can mine 54mhs or so, and it says it is mining this ammoount on nicehash app, but when i click check my stats online it says it's only getting 20mhs or so.

**Comment by yetanotherjson** [comment]
Sometimes i find that the view view on nicehash is not always accurate, check the hashrate on the console view (command prompt view) and see the values there.

Basic check - check to make sure your videocard is not overheating and underclocking itself, try older drivers as the maybe the newest ones is having issues,if you also mining with your CPU, try mining GPU without mining with CPU.  Good luck.
