### ISSUE TITLE
Dual Mining Decred

### ISSUE THREAD

**Issue by Joshwaa2010** [nicehash/NiceHashMiner-Archived#760]
I tried to switch from Pascal to Decred in dual mining but all the Decred shares get rejected. Had to go back to Pascal.  4 RX 480 not overclocked. Running NiceHash Miner v1.7.5.7

**Comment by kenshirothefist** [comment]
Dual mining with Decred is not fully supported yet. See here: https://github.com/nicehash/NiceHashMiner/wiki/Enable-ClaymoreDual-with-Decred-Lbry-Pascal
