### ISSUE TITLE
Doesn't detect R7 370?

### ISSUE THREAD

**Issue by sapphonie** [nicehash/NiceHashMiner-Archived#761]
My R7 370 has openCL support, no idea why it won't detect it.

**Comment by kenshirothefist** [comment]
Please zip the \logs folder and attach it here.

**Comment by sapphonie** [comment]
https://thesqrtminus1.com/files/misc/logs.7z

**Comment by sapphonie** [comment]
bump? if you need a different link I can provide one

**Comment by kenshirothefist** [comment]
@TheSqrtMinus1 Please make sure to install appropriate AMD drivers version: see here: https://github.com/nicehash/NiceHashMiner/wiki/AMD-drivers-version-information
