### ISSUE TITLE
No CPU detection

### ISSUE THREAD

**Issue by MostUnclean626** [nicehash/NiceHashMiner-Archived#762]
When I open up NiceHash the program doesn't detect my CPU or GPU.  I believe the GPU problem is because its to old but the CPU I can't figure out.  The CPU is an AMD Athlon II X4 635 Processor 2.90GHz.  Can someone tell me a way to fix this or provide a web site for required CPU specs?
Thanks

**Comment by kenshirothefist** [comment]
The CPU has to support **AES / Advanced Encryption Standard instructions** feature, but your CPU doesn't support it. See also https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining.
