### ISSUE TITLE
NEOSCRYPT Please returned this algo for Amd VIDEO

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#763]
This algorithm worked quite well on video cards from AMD, but only in version 1.7.4.4 and 1.7.4.3 after installing Microsoft Visual C ++ 2005-2008-2010-2012-2013-2017 Redistributable Package Hybrid x86 & x64 (December 25, 2016) everything is fine Worked and there were no glitches at all, please return this algorithm! Be so kind, deign to respect and pity over the users of your super-duper mega atstskogo multiminer!)))

**Comment by kenshirothefist** [comment]
neoscrypt miner is unfortunately unstable and unmaintained, therefore we can not include it into NHM. We might include it later if a newer miner will be available.
