### ISSUE TITLE
Wrong predicted rate on quadro card

### ISSUE THREAD

**Issue by Calle1756** [nicehash/NiceHashMiner-Archived#765]
I've set a cad-machine to mine with nicehash, but I dont't receive the predicted mining rate. The prediction for the quadro-computer is twice the amount that my duo 1080 computer mines. I am guessing there's a bug or wrong computation in the predictionfunction? This is a fairly old computer with a quadro 600 for CAD.

![capture](https://cloud.githubusercontent.com/assets/26736830/24398324/5e01c1de-13a9-11e7-85a3-3e36f3712355.PNG)

**Comment by S74nk0** [comment]
@Calle1756 Are you using the latest NHM version? Pascal shouldn't be available for this GPU in the latest version

**Comment by nicehashdev** [comment]
NHM officially only supports desktop gaming video cards.
