### ISSUE TITLE
DCR keep being rejected.

### ISSUE THREAD

**Issue by hinata9276** [nicehash/NiceHashMiner-Archived#766]
Hi, recently my RX470 rigs failed to mine DCR. Using Claymore Dual Miner, both V7.4 and newest v8.1 won't work. The log file keep displaying weak DCR shares.
21:15:16:470	198c	DCR: weak share, skip
21:15:18:970	1990	DCR: weak share, skip
21:15:19:329	1988	DCR: weak share, skip
21:15:19:876	1994	DCR: weak share, skip

Only rejected by Nicehase server, Suprnova server works fine.

**Comment by kenshirothefist** [comment]
Decred mining with Claymore is experimental only. See here: https://github.com/nicehash/NiceHashMiner/wiki/Enable-ClaymoreDual-with-Decred-Lbry-Pascal
