### ISSUE TITLE
No profit with  the GTX 660?

### ISSUE THREAD

**Issue by Headhunter1231994** [nicehash/NiceHashMiner-Archived#767]
Now, I don't know whether I could post it here, but am I correct that there is no way of getting any profit with the GTX 660? Prevouiosly I mined DaggerHashimotto, but that's not possible anymore.

Just a simple question. If the answer is there is no profit, I can shut down that machine.

Thank you for your time!

**Comment by S74nk0** [comment]
@Headhunter1231994 There are many factors that determine profitability, BTC price, Alt-coin prices, hash-rate, electricity cost,... If you determined that this GPU/rig  is **not profitable for you** anymore then best to shut it down.

Closing issue as it is not related to NiceHash Miner code...
