### ISSUE TITLE
Remote monitoring blocked?

### ISSUE THREAD

**Issue by jddebug** [nicehash/NiceHashMiner-Archived#768]
I have used http://awesomeminer.com/ for years to monitor my rigs. It seems that Nicehash Miner is using something like -mport 127.0.0.1:3333 to control claymore zcash miner instead of -mport 3333. As a result awesome miner will no longer work. Please allow the option for remote monitoring or I will not be able to use the nicehash miner. I have a large farm and not being able to see the status of each rig is a real problem.

**Comment by jddebug** [comment]
It appears the problem for me is located here:

 NiceHashMiner/NiceHashMiner/Miners/Equihash/ClaymoreZcashMiner.cs 

I need the option to remove the 127.0.0.1 which will allow me to monitor the miners on my LAN.

**Comment by nicehashdev** [comment]
NiceHash Miner uses multiple miners and switches between most profitable algorithm. There is no unified API protocol between these. NHM also randomly binds local port so you cannot know ahead which one will get bound.

The feature you are asking may be available in the future in linux version of NHM to control NHM directly via API.

We have no plans to change current behaviour. Binding to non-local host triggers Windows Firewall window which looks suspicious to many users.

If you still need this feature, you can change source of NHM and compile your own version.
