### ISSUE TITLE
Automatic updates solution

### ISSUE THREAD

**Issue by judge2020** [nicehash/NiceHashMiner-Archived#769]
Currently updating is not optimal for every user, they might skip some, maybe important, updates due to either not knowing how to use Github releases or just not wanting to stop mining. 

Possible solutions:

 - [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) - automatic updates on startup, generates an automatic installer without UAC dialogs, only requires static files either on GitHub or a server. 
 - OneClick deployment - requires static web server files
 - [octopus](https://octopus.com/) - requires static web server files

**Comment by nicehashdev** [comment]
We already have automatic updater ready in NHM2.0.

**Comment by judge2020** [comment]
👍
