### ISSUE TITLE
StartMiningWhenIdle not working as intended

### ISSUE THREAD

**Issue by swagkiller69** [nicehash/NiceHashMiner-Archived#77]
When you select StartMiningWhenIdle to true, after the set amount of time it starts mining, and when you return, it stops, which is great for the times i forget to launch my miner. But when this option is true you cant manually start mining because it thinks you're not idle and kills the miners instantly. Can't this setting be ignored if the mining was started manually? Or is this working as originally intended

**Comment by kenshirothefist** [comment]
Yes, this is working as designed. When you're taking manual actions, your PC is not idling, therefore this conflicts with the StartMiningWhenIdle setting. You can only use either StartMiningWhenIdle or full manual, but not both.

**Comment by swagkiller69** [comment]
What confused me is "start mining when idle" is the name of the setting,
maybe it'd be better off written as "only mine when idle"
