### ISSUE TITLE
Nvidia Glitch 970

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#772]
Win 10
Biostar 85
1 stick ram 8gb
2x xstrike 1100watts PSU

3 x Asus strix 970
2 x 1060 (Asus + gigabyte) 
1 x Asus strix 960

All powered USB raisers

NHM 1.7.5.7

When i try to bench mark 960, 1060, no problem BUT when i get to 970 it gets stuck at excavator. I can see that there is BTC/DAY but it just keeps going forever until i press stop only then the speed value shows up. If i try to resume benchmark everything freezes. If i close the miner after pressing the stop button and start it up again i cannot see any GPUs in the main NHM window and takes awhile to load, stuck at "quering CUDA devices". Also if i close  NHM, CUDA process is still running in the backround and i cant close it.

![screenshot 1](https://cloud.githubusercontent.com/assets/19608698/24563158/4fc97f02-1602-11e7-9708-0bee63e6c6a0.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19608698/24563159/4fca501c-1602-11e7-86d7-437b1d3067a6.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19608698/24563137/4210f264-1602-11e7-915e-31da531ddaaa.png)

The only way to do it is reboot and it freezes if i try to do that. So i hold down the on/off button for forced shut down. The 1060 which is connected to the 16 lane starts spinning at full throttle until i hit the on off button again and the system boots up normally.

So the only way to bench mark all the algos for below LBRY for 970s is to 
1. wait for a BTC/DAY to show up.
2. Stop the benchmark
3. close nhm
4.Force  Shutdown
5. Boot up, Start benchmarking the next algo go back to step 1.

This way i manged to benchmark all algos! WTF?! I there something wrong?

After doing the benchmarks in this crazy way i can start mining,it works until it tries to switch out to excavator or nanashi. Then it just keeps opening up nanashi windows allover the place. Is there a way to fix this?

![screenshot 6](https://cloud.githubusercontent.com/assets/19608698/24563186/66755de8-1602-11e7-96a9-5ee673a7ae17.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/19608698/24563185/6675134c-1602-11e7-94ec-50d1302f7e57.png)

[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/886539/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/886538/log.txt)

Images and LOG is attached

**Comment by nicehashdev** [comment]
Can you post benchmark logs as well?

**Comment by undefy** [comment]
Sure are these the ones?
[logs.zip](https://github.com/nicehash/NiceHashMiner/files/887428/logs.zip)

**Comment by S74nk0** [comment]
@undefy Can you please upload the logs after mining with this file [NiceHashMiner_log_fix.zip](https://github.com/nicehash/NiceHashMiner/files/889904/NiceHashMiner_log_fix.zip). It will produce better logs and will be easier to analyze the problem.

**Comment by nicehashdev** [comment]
Since author did not provide any more information we requested, we are closing this.
