### ISSUE TITLE
Excavator Hangs

### ISSUE THREAD

**Issue by Sifontes** [nicehash/NiceHashMiner-Archived#773]
Miner works fine, maybe for a day, or 2. But in numerous occasions, Ive noticed the excavator "hangs" as an infinite loop trying to start but doesnt start. Any suggestions

**Comment by nicehashdev** [comment]
We need some more. Your card(s)? You have anything overclocked? Post your log file. You can also enable logging in excavator - so we can see why it is closing down.

**Comment by nicehashdev** [comment]
When you provide more information as requested, we will reopen this issue.
