### ISSUE TITLE
Excavator blocked from accessing graphics hardware

### ISSUE THREAD

**Issue by digableinc** [nicehash/NiceHashMiner-Archived#774]
AMD Ryzen 1800X
16GB GSKILL DDR4 Ram
2x MSI GTX 1080 Gaming 8GB
Windows 10 Pro 64-bit

Mines for various amounts of time before getting these errors and ultimately bluescreens with BAD_POOL_CALL. Originally thought it was the Eset Nod32 doing it because CCMiner was the first one doing this, so I started disabling it. Ended up switching to the KlausT fork, but the Excavator hang/reboot issue persists.

[photo apr 01 2 00 09 pm](https://cloud.githubusercontent.com/assets/24709779/24581190/e71f6c80-16e4-11e7-957b-79097418e75d.jpg)

**Comment by nicehashdev** [comment]
You can try following:
- increase virtual memory
- increasing switch delay in settings of NHM
- update drivers or if you have latests version, roll down
- disable certain algorithm(s) and see which one is most likely causing the issues

**Comment by fefsf** [comment]
disable any OC and see what happens

**Comment by digableinc** [comment]
No overclocking going on, both cards are running the way they came out of the box. I upped the virtual memory to 16,384, Window was managing it and had only 2 gigs and some change going. I've disabled all algorithms that use excavator and it hasn't failed yet. Might try renabling them now that I've adjusted the virtual memory.

**Comment by nicehashdev** [comment]
Has this issue been resolved?

**Comment by digableinc** [comment]
No, the issue persists. I will be able to look into it more tomorrow. Even removing excavator algorithms hasn't solved it. BSOD and reboots are random between 30 minutes and four hours. This is one out of four other machines with various mixtures of NVIDIA and AMD gpus having this issue. All others are running Eset Nod32 and not having any problems.

**Comment by nicehashdev** [comment]
If you are running a mixture of AMD and NVIDIA cards in same system, we recommend you to remove all AMD cards for a test and see what happens then. It has been known that there can be issues on some systems when running mixture of cards.

Also, don't stop with excavator - excavator is the least possible candidate for causing troubles, but rather start disabling ccminers. For example, ccminer_x11gost by Alexis is very unstable miner and is causing issues for majority, thats why we have it disabled by default.

**Comment by digableinc** [comment]
The setup with the AMD/NVIDIA mixture is running without issue. The one with the problems is running a pair of matched GTX1080s. Ccminer was the one that I noticed started the problems. I moved to the fork released by KlausT and it stopped hanging the system. Excavator (as shown in the screen grab) is the one that is now continuously hanging the system at random intervals.

**Comment by nicehashdev** [comment]
Did you increase switch delay?

**Comment by digableinc** [comment]
No, I didn't increase the switch delay - everything is running as it comes from NiceHash. 

However, I increased the virtual memory to 32GB and disabled SLI. I know there is nothing to be gained with SLI, but i also use this system for VR dev. I've also reenabled all of the algorithms to see if SLI had anything to do with the issue. So far its been going for a little over three hours without issue. I'll update in a few hours.

**Comment by digableinc** [comment]
It would appear that having SLI enabled was causing the issue. All algorithms are enabled, Nod32 enabled, everything is running smooth without issue.

**Comment by nicehashdev** [comment]
It is possible that it would work with SLI enabled if you increase switch delay. If you don't mind checking that... Thanks.

**Comment by Schnazzy** [comment]
I'm running two GTX 1080's in SLI and am running into this issue as well.  I came across this post while googling.  Which setting is the "switch delay" setting?  I see a couple options in the settings which could  be it, but I'm not sure which one is the right one, or if it's even exposed in the GUI.  Could you provide a tad more detail on which setting needs to be adjusted for SLI configurations, and recommend a value to set it to?  Thanks!

**Comment by AndrewDonelson** [comment]
Issue still persists with 8 GPU EVGA GTX 1080ti cards, latest drivers, no overclock. Weird thing is it does not do it on my 8 GPU MSi 1080ti rigs. they are rock solid. Could it be vendor firmware?

**Comment by Icarus-Incognito** [comment]
Issue is present for me also 4 EVGA GTX 1080ti cards latest drivers, no overclock.

**Comment by BillSavastano-LeaguePals** [comment]
I'm having this issue without SLI bridge, and with SLI disabled.  I have already increased my VM to 60GB.
