### ISSUE TITLE
AMD Ryzen

### ISSUE THREAD

**Issue by gg4life** [nicehash/NiceHashMiner-Archived#775]
on v1.7.5.1 my ryzen 1700 processor would be doing .47 cents a day and only use 29~40% cpu power.
on v1.7.5.7 my ryzen 1700 processor would be doing .27 cents a day and use 100% cpu power. I have tried to extract the bin into the folder and it doesnt do much. Can anyone please explain why?:

**Comment by kenshirothefist** [comment]
@gg4life the same cpu miner (xmr-stak) is used in both 1.7.5.1 and 1.7.5.7, therefore results should be the same. Compare the config_0.txt files on both versions under nicehashminer\bin\xmr-stak folder

**Comment by kenshirothefist** [comment]
@gg4life did you see my last comment. Did you check the config, is it now working as expected for you?

**Comment by gg4life** [comment]
I will take photo and send you tonight
kenshirothefist <notifications@github.com>于2017年4月6日 周四下午4:17写道：

**Comment by gg4life** [comment]
​
 New 1.7.5.7 Miner.jpg
<https://drive.google.com/file/d/0B-UtsGgJS2oiblVEWC02SFVXem8/view?usp=drive_web>
​​
 Old 1.7.5.1 Miner.jpg
<https://drive.google.com/file/d/0B-UtsGgJS2oiR1NVTTY1RlBHSDQ/view?usp=drive_web>
​​
 Old NiceHashMiner_v1.7.5.1.rar
<https://drive.google.com/file/d/0B-UtsGgJS2oib2xkZzBWamltek0/view?usp=drive_web>
​​
 NiceHashMiner_v1.7.5.7.rar
<https://drive.google.com/file/d/0B-UtsGgJS2oicExiNHJOVWJpckU/view?usp=drive_web>
​

**Comment by gg4life** [comment]
As you can tell the 1.7.5.7 does a lot lower on cpu mining while using max
cpu speed. While on 1.7.5.1 it uses way lesser and makes more. What I am
also trying to figure out is why am I getting the message that MEMORY ALLOC
FAILED: VIRTUALALLOC FAILED. I never got this message when I was using my
old APU system before I upgraded to this.

**Comment by gg4life** [comment]
From the looks of this article it looks like it can do that much at 4.0 ghz. I am currently clocked at 3.9 on mine. Please someone help me.

https://www.nicehash.com/?p=news&id=148

**Comment by gg4life** [comment]
Please see my specs

http://valid.x86.fr/et7vbs

**Comment by S74nk0** [comment]
@gg4life Download the [pre-release-v1.7.5.8_PreRelease_02](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.8-pre/NiceHashMiner_v1.7.5.8_PreRelease_02.zip). Go to settings and paste **enable_ht=true** to **Extra Launch Parameters**. Here is a picture:
![ht_mode](https://cloud.githubusercontent.com/assets/1517233/24861028/8259b1ce-1df7-11e7-8813-3ad604d3c1e7.PNG)

Save the settings and do a benchmark. Please report back your benchmark speed. Also make sure you aren't running any applications that are CPU intensive when bench marking to get the best benchmark results.

**Comment by gg4life** [comment]
[image: Inline image 1]

I have tested it and its still not using all cores. Please see below. I am
not sure whats wrong. My CPU is at 3.8ghz.
If According to the profit calc I should be getting at least 40+ cents
cause I am not far off from the 1700x overclocked to 4.0ghz which gets
60cents. I am not sure what i went wrong.



[image: Inline image 2]

**Comment by kenshirothefist** [comment]
@gg4life Please read carefully this wiki: https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining. To reach full speed you need to take special care on topics 2. and 5. from the aforementioned wiki.

**Comment by gg4life** [comment]
I am not sure how this works. Could you please walk me over?

**Comment by ArtAnts1986** [comment]
Hi guys, I have the same problem.
There are 2 PCs:
1. 1500Х 4/8 works without the parameter "enable_ht = true" and produces ~450h/s (LessT = 0 )
2. 1700 8/16 works with the parameter "enable_ht = true" and produces ~550h/s (LessT = 0 ), but the load is only 50%, and without the parameter HT produces only 190h/s

I think the problem is in the xmr-stak-cpu miner which can not use 16 threads.
Fix it please if possible, I would like to use all power.

**Comment by kenshirothefist** [comment]
@ArtAnts1986 This is expected behavior, please read carefully this wiki: https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining.

Also, your speeds are in the range of expected speed for your CPUs, check here: https://www.nicehash.com/index.jsp?p=calc
