### ISSUE TITLE
Device Not there ...help

### ISSUE THREAD

**Issue by Bosskiller1711** [nicehash/NiceHashMiner-Archived#776]
I dont can see on nicehash any device of my Laptop.
They dont see my gpu or cpu

pls help
![screenshot 14](https://cloud.githubusercontent.com/assets/20838566/24590765/621e9c9e-17f3-11e7-9f1f-8b3764b348b8.png)

**Comment by nicehashdev** [comment]
This means that your laptop is too old. It does not have CPU or GPU that could be used for mining by NiceHash Miner.
