### ISSUE TITLE
McAfee Flagging Artemis!9D4A541BD271 Trogran in latest release

### ISSUE THREAD

**Issue by sparcusa** [nicehash/NiceHashMiner-Archived#778]
Can you please supply a MD5 Hash with the releases.

Thanks,

**Comment by S74nk0** [comment]
Check the check-sums in the [release notes](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.7). 
AV is probably flagging the miner files that NiceHash Miner downloads. This is a false positive because a lot of miners get bundled with malware and get flagged as well.

Closing issue...
