### ISSUE TITLE
benchmarks terminated 

### ISSUE THREAD

**Issue by lisath** [nicehash/NiceHashMiner-Archived#78]
my benchmarks keep getting terminated on my R9 fury

**Comment by theLosers106** [comment]
First of all.. Which algorithm(s) are you getting terminated? Could you try and run the sgminer manually by running runme.bat in the sgminer-5-3-0-general folder..

**Comment by lolwut548** [comment]
I have the same issue since 1.3

X11 keeps dying on me, and here's the log of sgminer-5-3-0

> [13:25:30] Thread 1 set pool = 0 (x11.eu.nicehash.com)
> [13:25:30] Init GPU thread 1 GPU 0 virtual GPU 0
> [13:25:30] CL Platform vendor: Advanced Micro Devices, Inc.
> [13:25:30] CL Platform name: AMD Accelerated Parallel Processing
> [13:25:30] CL Platform version: OpenCL 2.0 AMD-APP (2004.6)
> [13:25:30] Platform devices: 1
> [13:25:30]  0   Fiji
> [13:25:30] List of devices:
> [13:25:30]  0   Fiji
> [13:25:30] Selected 0: Fiji
> [13:25:30] Preferred vector width reported 1
> [13:25:30] Max work group size reported 256
> [13:25:30] Maximum work size for this GPU (0) is 256.
> [13:25:30] Your GPU (#0) has 64 compute units, and all AMD cards in the 7 series or newer (GCN cards)       have 64 shaders per compute unit - this means it has 4096 shaders.
> [13:25:30] Max mem alloc size is 4026531840
> [13:25:30] Using source file darkcoin-mod.cl
> [13:25:30] GPU 0: selecting lookup gap of 2
> [13:25:30] GPU 0: selecting thread concurrency of 30656
> [13:25:30] Setting worksize to 64
> [13:25:30] Using binary file darkcoin-modFijigw64l4ku0.bin
> [13:25:30] No binary found, generating from source
> [13:25:30] Building binary darkcoin-modFijigw64l4ku0.bin
> [13:25:30] Trying to open /usr/x86_64-w64-mingw32/bin/darkcoin-mod.cl...
> [13:25:30] Trying to open ./darkcoin-mod.cl...
> [13:25:30] Trying to open ./kernel/darkcoin-mod.cl...
> [13:25:30] Using ./kernel/darkcoin-mod.cl
> [13:25:30] CompilerOptions: -I "." -I "./kernel" -I "." -D WORKSIZE=64 -I "/usr/x86_64-w64-mingw32/bin" -D SPH_COMPACT_BLAKE_64=0 -D SPH_LUFFA_PARALLEL=0 -D SPH_KECCAK_UNROLL=0 
> [13:25:30] Error -11: Building Program (clBuildProgram)
> [13:25:30] C:\Users\CHARL_~1\AppData\Local\Temp\OCL6504T8.cl:90:10: fatal error: 'blake.cl' file not found
> #include "blake.cl"
>          ^
> error: Clang front-end compilation failed!
> Frontend phase failed compilation.
> Error: Compiling CL to IR

 blake.cl is present in the kernel subfolder

**Comment by kenshirothefist** [comment]
Which AMD driver version are you using?

**Comment by lolwut548** [comment]
the latest crimson 16.4.1, package 16.15.2211.1001-160403a-301124E which include Opencl 2.0.6.0

**Comment by kenshirothefist** [comment]
OK. Now, there are a couple of things to try.
1. Try to replace all files in the "bin\sgminer-5-3-0-general" folder (delete existing files) with files from folder "bin\sgminer-5-2-1-general" which can be found in this release: https://github.com/nicehash/NiceHashMiner/releases/tag/1.2.3.2 Then re-run the benchmark, just make sure to un-check all of the Blake\* algos (since 1.2x does not have Blake\* algos support). Report what happens.
2. If you can - uninstall the driver completely (see https://github.com/nicehash/NiceHashMiner#troubleshooting) and install 15.7.1. Then try to run with latest 1.3x version and report what happens.

Thanks for the feedback!

**Comment by lolwut548** [comment]
Thanks for the quick answers
So I tried to swap sgminer-5-2-1 from 1.2.3.2 with sgminer-5-3-0 from 1.3.0.3.
I still end up with the same issues, it only successfully benchmarks keccak.
It keeps throwing compiling errors, saying that either blake.cl, luffa.cl or blake256.cl are not found.

I'm not so keen on rolling back to catalyst, I'm playing on that computer...

EDIT: it actually looks that even 1.2.x is pushing those errors.
So the culprits could be me upgrading to win10 or the latest crimson drivers.

**Comment by kenshirothefist** [comment]
Can you also try this: copy all files from "bin\sgminer-5-3-0-general\kernel" into "bin\sgminer-5-3-0-general\" folder (so files from "kernel" subfolder goes directly to bin\sgminer-5-3-0-general). Re-run and see what happens.

**Comment by lolwut548** [comment]
Solved !
I tried copying all the files from the kernel subfolder into the root folder like you said, that didn't work. But then I thought your idea of injecting the files was good, so I tried pushing them into c:\users[_your_username_here_]\appdata\local\temp\ and that did the trick. sgminer is running again like it should!
Thank you for your help

**Comment by kenshirothefist** [comment]
Thank you for you workaround! We added this workaround in the Troubleshooting section. Thanks again!
