### ISSUE TITLE
Excavator mining intensity less than 1 thread

### ISSUE THREAD

**Issue by Lexomatico** [nicehash/NiceHashMiner-Archived#781]
Hi everyone,
i recently tweaked all the miners to work with less intensity for daytime usage while playing games and such. Is it possible to throttle excavator to mine with less intensity other than putting it to only 1 thread? 1 thread unfortunately isn't low enough.

**Comment by nicehashdev** [comment]
No, due to the specifics of equihash algorithm, you cannot set equihash of excavator to anything else but to certain number of threads.
