### ISSUE TITLE
Earned income balance is not working wrong BTC value of 600

### ISSUE THREAD

**Issue by sil2222** [nicehash/NiceHashMiner-Archived#784]
Nice hash miner shows ive earned 20.03 usd ,but the web page shows me only earning 10.17 every time i check it goes lower also it shows current value of BTC as 600.00 ? I checked coinbase and value is currently $1193.57
![nicehash_-_2017-04-08_05 32 09](https://cloud.githubusercontent.com/assets/27058629/24827795/b8f3885c-1c1e-11e7-8682-1ba41f932e7c.png)

**Comment by nicehashdev** [comment]
This is issue not related to NiceHash Miner but website www.nicehash.com. In future, send reports of these issues to info@nicehash.com and avoid opening issues here.
