### ISSUE TITLE
router configuration?

### ISSUE THREAD

**Issue by Bedoy78** [nicehash/NiceHashMiner-Archived#785]
hi, 

I am unable to use nicehasminer currently. I always get the error message stratum_subscribe timed out.

for testing I deactivated my windows firewall: no progress.
Then I put my router in DMZ mode. The hashing worked!

however, I am not able to configure properly my router for port forwarding. do you have recommendation on configuration?

regards,

**Comment by nicehashdev** [comment]
We got several reports that some integrated protections of routers are blocking stratum protocols. You may want to take a look into this and disable only that.

**Comment by Bedoy78** [comment]
Do you have the recommendation on which setting to tweak?  I enabled port forwarding 3333:3359, I was able to go a bit further, but the tool get disconnected

**Comment by nicehashdev** [comment]
This is not an issue of port forwarding as theres no port you need to bind on your machine for NiceHash Miner to properly work. All the ports that are bound are only on local host for API readings.

What we believe it may be happening with some routers is that they block certain type of traffic - they analyse protocol and when stratum is detected, connection is terminated. Where you can disable that in settings of your router, I don't know. If you can't find it, I suggest you to contact manufacturer of your router and ask them.
