### ISSUE TITLE
ASUS gtx1080ti problem

### ISSUE THREAD

**Issue by money3239789** [nicehash/NiceHashMiner-Archived#786]
ASUS gtx1080ti problem
I use version V.1.7.5.7
Zcash mining, the computer will be blue screen, and re-boot
Ask for help
 

NO Overclock
 
     

I used the old version v.1.7.5.4 no problem
Use v.1.7.5.7. Immediately blue screen,

     
I currently choose DaggerHashimoto
no problem
The computer will not reboot

**Comment by nicehashdev** [comment]
You have already opened same issue. Please, refrain from opening multiple issues with same topic.
