### ISSUE TITLE
2nd R9 280x card will not mine x11, Lyra2REv2, quark, or qubit.  terminates immediately 

### ISSUE THREAD

**Issue by computerchuck** [nicehash/NiceHashMiner-Archived#79]
This is a Win10pro, H170 chipset, i3-6100 CPU computer.   Running NHM 1.3.0.3.  Now with 2ea R9 280x cards (identical 280x cards - vendor, manf date, firmware).  Current driver ver: 16.150.2211.0.  Started with 15.7.

This PC has been mining great for about a month with a single 280x.   I've just added an .   Tried new install, new precise benchmarks, I think I've narrowed the problem down a bit.  
The original GPU (never removed, in PCIe v3 x16 slot - called GPU device:1 in debug) when individually selected (check box in the NMH window), it no longer will mine x11.  It immediately shutdown as soon as it starts.  This is from the debug screen:

[7:07:10 PM] [AMD_OpenCL] Starting miner:  --gpu-platform 0 -k quarkcoin --url=stratum+tcp://quark.usa.nicehash.com:3345 --userpass=17xyWrRK6xPqttQ6CfEenmvrYnWMYL2ryQ.SB2:x --api-listen --api-port=4050  --keccak-unroll 0 --hamsi-expand-big 4 --nfactor 10 --xintensity 1024 --thread-concurrency    0 --worksize  64 --gpu-threads 1 --device 1 --gpu-fan 30-95 --temp-cutoff 95 --temp-overheat 90 --temp-target 75 --auto-fan --auto-gpu
[7:07:11 PM] [AMD_OpenCL] Shutting down miner

The sgminier window opens in a flash and closes just as quickly.    

When I deselect the original 280x card from NHM window, and select the other (newly installed) GPU (in PCIe v3 x4 slot - called GPU:0 in debug), it runs perfectly.  

So, now the newly installed card works fine, but the original card doesn't.  The benchmark terminates  on most algos except ether and even that one benchmarks significantly lower than normal.  16 MH/s vs the normal 20.5 MH/s.

Please help.

with best regards,
Chuck

**Comment by rezonjov** [comment]
Did you try uninstalling the drivers with DDU (Display Driver Uninstaller)? And reinstall the drivers again?

**Comment by computerchuck** [comment]
I haven't.  I'll give it a try and go back to 15.7 or 15.201.

**Comment by computerchuck** [comment]
I've used the driver uninstall utility (thank you rezonjov) and started from scratch.   Seems AMD no longer lists the 15.7 or 15.201 driver now.  They only have Crimson listed for download.   Used windows update to get it to 15.201.   Rebooted.  Did a fresh install of NHMiner 1.4.0.1  Did a quick benchmark of just x11, then ran mining for a few minutes.  It worked perfectly, both cards no problem.   Then went back, did a benchmark on most other algos and started receiving 'termination' on all other algos except ethereum.   Now it bombs out exactly as before on x11 when both cards are selected.   Everything mentioned above in the original write up came back.   Tried running precise benchmarks several times, they all (except eth) fail immediately.   The only thing I have left to try is the latest Crimson drivers.    Since it bombed before, it probably will not succeed.  Will post my findings.

**Comment by computerchuck** [comment]
Tried Crimson drivers 16.150.2211.1001.  Same effect.  Cannot mine any of the coins mentioned in the title.   Eth really doesnt mine either.  Occasionally it will mine a little after many retries and failures.  It may effectively be mining nothing.   

So, bottom line, I cannot mine with two R9 280x cards in a Win 10 machine with H170 chipset, no matter the driver.

I can take these cards and mine with them separately (1ea GPU per computer) and I've got these to work perfectly in three different computers, for more than 48 hours straight.
1.) Win7, using Z77 chipset, .  
2.) Win10, using z170 chipset
3.) Win10 using h170 chipset.  

Just cannot run two 280x cards together.   Bummer!!

Good luck out there.

**Comment by computerchuck** [comment]
Finally figured out the problem.  YEA!!!!

RDP.   When you rdp instead of using the console, the miner thinks there is only one monitor and one video card to use.  So, you have to launch everything from the computer itself, or use something like TeamViewer.   DANG.  This was a tough find.   

So, if anyone else should run into this issue, this is the fix.  Don't use rdp.

**Comment by theLosers106** [comment]
Please read the README on the front page (https://github.com/nicehash/NiceHashMiner#-how-to-getrun-it) .. this is a known limitation of sgminer..
