### ISSUE TITLE
Excavator.exe problem

### ISSUE THREAD

**Issue by Headhunter1231994** [nicehash/NiceHashMiner-Archived#790]
Hi,

With the latest release of the miner I have the issue that Excavator.exe keeps restarting itself. As in, opening running for 10 seconds to a couple of minutes, an then closes and restarts again. What could be the problem here? I mean if a different algorithm is more profitibale, it switches that's logical, but since it keeps restarting the same thing, it doesn't make sense to me.

**Comment by nicehashdev** [comment]
Cards? OC? Drivers? OS? Card temperatures?

**Comment by Headhunter1231994** [comment]
GTX 1070, ver 381.65  OC=Yes (Check attachment for settings.) 
![settings](https://cloud.githubusercontent.com/assets/25772604/24917423/6f748976-1edd-11e7-969f-30c2e38493c7.PNG)
  Temps between 78C and 81C OS Windows 10 build 15063.13

I should add that I did not have this issue in previous versions of the miner.

**Comment by nicehashdev** [comment]
Reduce your OC (especially core) for a bit. And it wouldn't hurt to reduce your temps as well. Pascals don't like so high temperatures (try to keep them sub 60 for optimal mining performance).

**Comment by banthing** [comment]
Thank you very much I apologize to you with a machine I do not have 32
notebooks do not do it.I'm hacked BTC I have been hacked by BTC twice,
and I'm very tired of investing.Now I'm running out of capital, and I
keep trying to keep it small, but I can not.

2560-04-13 17:26 GMT+07:00, nicehashdev <notifications@github.com>:

**Comment by Headhunter1231994** [comment]
After reducing my clock speeds it runs much better, thanks!

________________________________
