### ISSUE TITLE
Third-party miners not listed?

### ISSUE THREAD

**Issue by brian000** [nicehash/NiceHashMiner-Archived#791]
For some reason, even though the `Use3rdPartyMiners` option is set to `2` in my General.json, none of the third-party miners show up in my devices/algorithms list.  They get downloaded, but simply aren't an option to select for either benchmarking or mining.

I'm running the latest version (1.7.5.9) of NHM on a brand new W10 machine.  At the moment all I have is a GTX 1050Ti, but have some RX470s on the way.

Any suggestions?

**Comment by S74nk0** [comment]
@brian000 Are the algorithms visible in the benchamrks.json file for RX470? Post the zipped configs folder here to see and also a screenshot where the algorithms are missing.

**Comment by S74nk0** [comment]
@brian000 Also try a clean install.

**Comment by nicehashdev** [comment]
There are no third party miners for NVIDIA cards, only for AMD.
