### ISSUE TITLE
Failing Benchmark

### ISSUE THREAD

**Issue by sachadechef** [nicehash/NiceHashMiner-Archived#794]
First i had the issue with the dll files. Now i have all dll files but i receive the following error message:
![image](https://cloud.githubusercontent.com/assets/17064329/24950531/a0c7ce9a-1f71-11e7-9b98-0e7831607e63.png)

Can anyone help me.

Thanks

**Comment by nicehashdev** [comment]
Please, use latest NHM version.

**Comment by sachadechef** [comment]
I have same issue with latest version

**Comment by nicehashdev** [comment]
How did you fix issue with missing dlls? Did you download missing files from some websites on internet? We do not recommend doing that - these files may be unsafe to use.

**Comment by sachadechef** [comment]
i made Windows update

**Comment by sachadechef** [comment]
in my server are only cpus, is there any way to pass benchmark,without doing it, because i cant mine without benchmark ...

**Comment by S74nk0** [comment]
@sachadechef install [Visual C++ Redistributable for Visual Studio 2015 ](https://www.microsoft.com/en-us/download/details.aspx?id=48145), the needed file is also under **bin\vc_redist.x64.exe**. Report back if this is fixed after installing the dependencies. P.S. install the x86 as well.

**Comment by sachadechef** [comment]
Installation of Visual C++ failed

**Comment by S74nk0** [comment]
@sachadechef please zip the logs and configs folder and upload it here or send it to stanko@nicehash.com.

**Comment by sachadechef** [comment]
![image](https://cloud.githubusercontent.com/assets/17064329/24956295/4b7a7508-1f87-11e7-9c1c-9a6e3dea77e9.png)
[logfile.zip](https://github.com/nicehash/NiceHashMiner/files/916374/logfile.zip)

**Comment by sachadechef** [comment]
i think this issue is comming because i use win srv and not win client...

what do you think? do you know this issue?

thanks for helping

**Comment by sachadechef** [comment]
solved issue 
https://dotblogs.com.tw/dog0416/2016/09/05/152344

**Comment by nicehashdev** [comment]
So, never use some dlls from unknown sources and make sure your vcredist installs successfully. Issue resolved.
