### ISSUE TITLE
Windows cannot access the specified device

### ISSUE THREAD

**Issue by bustapaladin** [nicehash/NiceHashMiner-Archived#797]
I was able to run the previous version just fine that being NiceHashMiner_v1.7.5.7

https://gyazo.com/390f0e4b99495ae16d0851f76b35b9cf
![image](https://cloud.githubusercontent.com/assets/19695825/24971378/0e100d00-1fb8-11e7-85ee-63d5af52b4a1.png)

Not able to run NiceHashMiner_v1.7.5.9

**Comment by nicehashdev** [comment]
Do you have antivirus enabled? If yes, whitelist all files in NHM folder.
