### ISSUE TITLE
ethereum config file overwritten each time NHminer is run 

### ISSUE THREAD

**Issue by MartinCzechowski** [nicehash/NiceHashMiner-Archived#80]
im trying to change the block refresh to something higher than 100ms in the ethereum config.json.

i make the changes and save.

when i run NHminer, the changes have no effect.

if i check the config file, the setting is back at 100ms.

**Comment by theLosers106** [comment]
This is a planned update to include the ability to change the settings for the proxy from NiceHashMiner itself.. If it is urgent I could make a temporary fix for you..

**Comment by MartinCzechowski** [comment]
thanks for the reply :D 

i figured out a way to change the values without them being reset; editing the config.json while NHminer is running, then manually closing the terminal windows and waiting for them to get restarted.

this has not however solved my issue. 

still no income / reported hashing when trying to mine ethereum.

ethminer starts
![1](https://cloud.githubusercontent.com/assets/18451690/14572473/0238329a-031d-11e6-8b85-8bab76a2f3bb.jpg)

does this indefinitely
![2](https://cloud.githubusercontent.com/assets/18451690/14572494/1c77cdfa-031d-11e6-86f3-c05d3afe381c.jpg)

ether proxy does this, keeps finding new blocks. every 10-20 seconds.
![3](https://cloud.githubusercontent.com/assets/18451690/14572511/34705990-031d-11e6-9c2d-1fc762705ce8.jpg)

NHminer looks like this the whole time
![4](https://cloud.githubusercontent.com/assets/18451690/14572532/5922a324-031d-11e6-9b73-b6c760023b7c.jpg)

**Comment by MartinCzechowski** [comment]
SOLVED

just installed version 1.4.0.1. everything works great :D
