### ISSUE TITLE
Changing GPU intensity?

### ISSUE THREAD

**Issue by David-Lor** [nicehash/NiceHashMiner-Archived#805]
I'd like to know if it's possible to reduce the GPU intensity when mining with this NiceHashMiner. Sometimes the mining makes the computer a bit laggy, and I'd like to mine just when "not-playing" on the PC.

The GPU is a Nvidia GTX970.

Thanks.

**Comment by S74nk0** [comment]
@EnforcerZhukov yes. Check the [Wiki - ExtraLaunchParameters](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters).

**Comment by David-Lor** [comment]
Thanks, but I'm not sure what option I should use. Tried xintensity, worksize and gputhreads with any difference on GPU usage, nor Sol/s I get. Below, "NVIDIA excavator (Equihash and Pascal)" is listed, and that's what I'm currently using. Three options are shown, -c1, -c2, -ct, but the wiki tells nothing about what each option does. Anyway, tried them and there's no difference.

**Comment by ejaedesign** [comment]
Is this possible on the new 2.0 alpha? I didn't see any parameters in the JSON config file.
