### ISSUE TITLE
Only 1 Algorithm?

### ISSUE THREAD

**Issue by bsjelin** [nicehash/NiceHashMiner-Archived#808]
Hello!

I just recently installed and did the benchmarking however I only seem to be able to benchmark or use cryptonight? It's the only option available on the list.

Do we download different algorithms elsewhere and upload them like plugins?

**Comment by bsjelin** [comment]
It looks like I'm able to mine other algorithms but they don't show in the benchmark section.

**Comment by sapphonie** [comment]
also getting this error

**Comment by platinum4** [comment]
This sounds like you are using a Kepler Titan

**Comment by bsjelin** [comment]
No it's happening with a couple different stations with different gpu's and cpu's.

**Comment by bsjelin** [comment]
Wait! I figured out my issue. The algorithms only show if you click on the gpu in the device list above. By default it only shows algorithms under cpu even though both devices are checked.

**Comment by S74nk0** [comment]
Closing issue... issue related to non-intuitive GUI (will be fixed in one of the future releases)

**Comment by foudreclair** [comment]
I have the same problem with my GTX 1080. I have only the algorithm : CryptoNigth
Why ?

**Comment by jaggedsoft** [comment]
I have 2x GeForce 670 and also only CryptoNight is showing
EDIT: Second try it showed more. I think you just need to click the GPU, or ctrl+click each one to show combined
![image](https://cloud.githubusercontent.com/assets/4283360/26651842/d555535a-4602-11e7-9e09-09b1c955eb68.png)

**Comment by panki989** [comment]
Hi,
I'm only seeing cpu algo but not the gpu algo in version v1.8.1.4.
Please look into this .
![image](https://user-images.githubusercontent.com/20380358/31852105-a944144c-b68f-11e7-9b49-fe43916eae1f.png)

**Comment by microtechies** [comment]
If you click on the gpu on the screen you will see the gpu algo all there
