### ISSUE TITLE
Connection problems, only one working algorithm.

### ISSUE THREAD

**Issue by steinhammer** [nicehash/NiceHashMiner-Archived#810]
Just about the only thing working is Equihash, daggerHashimoto works sometimes on backup. The rest just won´t connect to your servers. This started yesterday.
had version 1.7.5.7 yesterday, now 1.7.5.9 and still not working, exept equihash....

**Comment by S74nk0** [comment]
Please write to support@nicehash.com about your problem. Tell them what is your IP and BTC address. Your IP might be blocked.

Closing issue not related to NHM program
