### ISSUE TITLE
Hide Mining Windows

### ISSUE THREAD

**Issue by bsjelin** [nicehash/NiceHashMiner-Archived#812]
Noticed that xmr-stak-cpu does not hide when this option is selected in the settings.

The other 3rd party apps seem to work ok with this function.

**Comment by S74nk0** [comment]
@bsjelin this is expected behavior. This is an exception for **eqm**, **excavator** and **xmr-stak-cpu** miners. These miners are started minimized when Hide Mining Windows is enabled. This will not be changed.

Closing isssue
