### ISSUE TITLE
GPU: too many resources requested for launch

### ISSUE THREAD

**Issue by boneus** [nicehash/NiceHashMiner-Archived#816]
Hello.

Yesterday I was mining on my notebook
Dell XPS
Intel Core i7-2720QM @ 2.20Ghz
NVIDIA GeForce GT 555M

I'm using NiceHash Miner 1.7.5.9. 
For CPU: xmp-stak-cpu
For GPU: ccminer

Everything was fine. But today I'm getting "too many resources requested for launch" on GPU miner. Can't understand what's wrong.

**Comment by S74nk0** [comment]
This sounds like an issue related to intensity. Lower your intensity for the specific miner (probably ccminer.) and algorithm that is giving you this message (**"too many resources requested for launch"**).  Read the [wiki](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#nvidia-ccminers) on how to achieve this.
Closing issue...

**Comment by boneus** [comment]
It's weird, today the problem went away. But thank you for the tip, I'll try next time
