### ISSUE TITLE
New V1.7.5.10 less profitable with same hashrates?

### ISSUE THREAD

**Issue by yearight** [nicehash/NiceHashMiner-Archived#818]
For both CPU(xmr-stak-cpu) and GPU(claymore_dual) (eth only, apparently decred has no pool specified) its lower. 
Ver.9 = $4.33 
Ver.10 = $3.20

OOOps, never mind, my mistake....back to normal when I choose the proper currency.

**Comment by S74nk0** [comment]
User mistake.
Closing issue...
