### ISSUE TITLE
i am still using 1.3.0

### ISSUE THREAD

**Issue by keztheminer** [nicehash/NiceHashMiner-Archived#82]
I thought you may have fixed this by now but i have been unable to use any new version since 1.3.0.0 , i keep getting this as error

AppData\Local\Temp\OCL4468T10.cl:90:10: fatal error: 'blake.cl' file not found
# include "blake.cl"

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

Even the newest version i have this issue

**Comment by keztheminer** [comment]
Just to note the new version is giving me same error as above :(

**Comment by theLosers106** [comment]
What driver version are you using?

**Comment by keztheminer** [comment]
16.4.1 , running fine on 1.3.0.0 but since the etherum added has not worked on newer versions

**Comment by theLosers106** [comment]
so sgminer-5-2-1-general works right but not the sgminer-5-3-0-general?

**Comment by keztheminer** [comment]
The version i seem to be running is 5.1-0 optimized sgminer on nicehash v 1.3.0.0
Now i just checked the version 1.4.0.1 And all is working fine  also running the same sgminer 5-1-0 optimized

**Comment by keztheminer** [comment]
For some reason with my apu enabled in bios it loads sgminer 5-3 and when disabled its using 5-1 , so with the apu on, nicehash don't work for me as it loads sg miner 5-3

**Comment by theLosers106** [comment]
Yes that's what it kinda should work.. the APU is seen as an incompatible GPU for the 5-1 so it will default back to 5-3..

**Comment by keztheminer** [comment]
So it seems to be the other way round for me , I am so confused as tried 1-3-0 and it loaded sgminer 5-3 with no issues mining fine , but then when I opened 1.4.0.1 it also loaded sgiminer 5-3 and i have same error as my first post this is with apu enabled for both  .

**Comment by theLosers106** [comment]
Issue is resolved in the latest version..
