### ISSUE TITLE
Only 1 algorith.

### ISSUE THREAD

**Issue by nisargshh** [nicehash/NiceHashMiner-Archived#820]
I only see 1 algorith when I click on benchmark, tried selecting cpu and gpu, nothing works.

**Comment by Joshwaa2010** [comment]
What GPU and CPU is in your rig?

**Comment by nisargshh** [comment]
GPU is old = Nvidia GT 610
CPU is also pretty old = AMD FX 8350

**Comment by Joshwaa2010** [comment]
That would be why.  The new miner will not work on your cpu and with the gpu being low in memory it will not do many algorithms either.

**Comment by S74nk0** [comment]
Issue opened due to old unsupported hardware.
Closing issue...
