### ISSUE TITLE
reject reason: share above target

### ISSUE THREAD

**Issue by poirat** [nicehash/NiceHashMiner-Archived#821]
the program keeps putting my gtx 1080 and 750ti to work on decred and no matter how long it runs It  keeps telling me reject reason: share above target if anyone has any info on how to fix this I'd greatly appreciate it

**Comment by MrZacks** [comment]
for the past two days i have had similar issues just like you with my gtx 730.

**Comment by nicehashdev** [comment]
You have to update your NHM to the latest version.
