### ISSUE TITLE
Nvidia Dual mining

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner-Archived#822]
Hello this is more a questions . because havent found the options , 

Can nvidia dual mine with escavator ??? what are the options to set ... is it like claymore and add -dual= in nicehash ???

can someone tell me how to enable dual mining in nvidia thanks

**Comment by fefsf** [comment]
No, no support for NVIDIA dual mining

**Comment by N8Thrasher** [comment]
Try this for Dual Eth+Pascal

EthDcrMiner64.exe -di 0 -esm 3 -mport 0 -allpools 1 -dcoin pasc -epool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 -ewal 39rZQqMBLymQsoNBixqMzvxdjksvcPyRQ8.yey -epsw x -dpool stratum+tcp://pascal.eu.nicehash.com:3358 -dwal 39rZQqMBLymQsoNBixqMzvxdjksvcPyRQ8.yey -dpsw x

**Comment by N8Thrasher** [comment]
for Decred just remove the "-dcoin pasc" and change "-dpool stratum+tcp://decred.eu.nicehash.com:3354"
for Lbry just change "-dcoin lbc" and pool to "-dpool stratum+tcp://lbry.eu.nicehash.com:3356"

**Comment by CAVACO-PT** [comment]
for amd cards ... with dualclaymore im using dual without any problem.... for nvidia escavator i dont know the what to add ... @N8Thrasher  u are talking about amd right ??

**Comment by N8Thrasher** [comment]
NVIDIA.
im using two GTX 780 Ti

**Comment by S74nk0** [comment]
Currently there is no NVIDIA dual mining option in NHM or excavator. This will probably be available in the future. 
Closing ...
