### ISSUE TITLE
Handle Excavator extra params

### ISSUE THREAD

**Issue by boltzj** [nicehash/NiceHashMiner-Archived#823]
As introduced on bitcointalk.org, excavator is embedded a lot of feature to achieve the best results:

`-ca,` `-ca -ca`, or `-ca -ca -ca` for managing number of thread per devices
`-os`, `-or` and `-od` for overclocking
and many more...

But when looking at [ExtraLaunchParameters.cs](https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Miners/Parsing/ExtraLaunchParameters.cs#L175), there is nothing to manage those options:
```
            new MinerOptionPackage(
                MinerType.excavator,
                new List<MinerOption>() {
                    // parameters differ according to algorithm
                    new MinerOption("parameter1", "-c1", "-c1", "0", MinerOptionFlagType.MultiParam, " "),
                    new MinerOption("parameter2", "-c2", "-c2", "0", MinerOptionFlagType.MultiParam, " "),
                    // Overclocking not supported from NHM
                    //new MinerOption("Overclocking_os", "-os", "-os", "", MinerOptionFlagType.MultiParam, " "),
                    //new MinerOption("Overclocking_od", "-od", "-od", "2", MinerOptionFlagType.MultiParam, " "),
                },
                new List<MinerOption>()
            ),
```

**Comment by nicehashdev** [comment]
We are aware of extra functionalities of excavator, but current design of NiceHash Miner does not benefit from using them and would only cause extra confusion or instability.

You will have to wait for NHM2.
