### ISSUE TITLE
How is the amount paid for each valid share calculated?

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#825]
I understand that the website give units in btc rate/hashrate/day. Nicehash pays per valid share and the going rate is constantly changing. So, before hashing begins does it accept the going rate and then use the hash power and time to calculate payment?
Thank you for your consideration.

**Comment by JeanPrendnote** [comment]
Go read the FAQ

**Comment by nicehashdev** [comment]
NHM is periodically checking rate via API and adjust algorithms so it is always mining what is most profitable according to rates online and benchmarked speed.

**Comment by ghost** [comment]
I understand how the program chooses what to mine. I am curious how the nicehash service tracks this as I am trying to build a program that can track each individual workers revenue. Thank you.

**Comment by nicehashdev** [comment]
NiceHash is paying miners according to orders placed by our buyers of hashing power. There is nothing that can be predicted - it is a mass of buyers that can either push the price up or down.

**Comment by ghost** [comment]
Is there a way for the miners to see the order that they are filling. To my knowledge there is no way to track each individual workers per btc address. This is very important for me. I was trying to figure out if it could be done locally on the miner's machine but it seems that NiceHash manages all of that. Would it be possible for you guys' to add that to the api area?

**Comment by nicehashdev** [comment]
No, you cannot know which order you are filling. And there is no need to know. All miners are paid the same rate, which is based on weighted average price of all orders.

**Comment by ghost** [comment]
Okay that's a good thing. So, as long as I keep track of the accepted hashrate and the time spent hashing, I should be able to use the orders.get request to accurately calculate the payout for each share?

**Comment by nicehashdev** [comment]
No, you should call SMA - you are paid what SMA says not what order list shows. You will not be able to determine payout out of order list.

**Comment by ghost** [comment]
Do you guys' update the SMA on a fixed time? Also, just to clarify, I should keep track of the time between the accepted shares correct?

**Comment by ghost** [comment]
So the process should go, get current sma, start logging time, and then when accepted, use the returned hash rate to calculate payout and of course subtract the 3%?

**Comment by nicehashdev** [comment]
The questions you are asking are not related to NiceHash Miner. You can view NiceHash Miner source on this github page and see how it is done.

If you have any further questions, you can ask on bitcointalk thread.
