### ISSUE TITLE
NiceHash don't show the expected earnings 

### ISSUE THREAD

**Issue by shorya95** [nicehash/NiceHashMiner-Archived#826]
It always remains 0.00USD/DAY, used to work like charm. tried reinstalling the program as well but still having the same problem. 
Any solution guys ??
![capture](https://cloud.githubusercontent.com/assets/13226372/25501787/caf5c1c6-2b48-11e7-8c30-8dbcc0e4bf9b.PNG)

**Comment by shorya95** [comment]
even the mBTC went from 5 to 0$

**Comment by nicehashdev** [comment]
This is just a visual issue. It looks like you are unable to get API for BTC to USD conversion.

Remember: always check profitability stats online - that is what actually matters and not what NHM is showing you.
