### ISSUE TITLE
When ever I try and use the nice hash no devises come up

### ISSUE THREAD

**Issue by carmelldancing** [nicehash/NiceHashMiner-Archived#827]
Idk how this is

**Comment by S74nk0** [comment]
@carmelldancing please describe you machine. If there are no devices it might be that your hardware is too old

**Comment by carmelldancing** [comment]
@S74nk0 Name:  Intel(R) Xeon(R) CPU W3565 @ 3.20GHz
Manufacturer:  Intel
Speed:  3.2 GHz
Category:  Server
Generation:  8th
Brand:  Xeon 3000
Cores:  4
And i think its a hp z400 from 2010

**Comment by S74nk0** [comment]
This CPU lacks **Intel® AES New Instructions**. This is the reason no hardware is being shown.
Closing issue...
