### ISSUE TITLE
100% Decred Shares rejected

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#829]
![rejected](https://cloud.githubusercontent.com/assets/24593637/25522518/e8a56320-2c0b-11e7-94da-1b770956c3e0.PNG)

**Comment by S74nk0** [comment]
@N8Thrasher did you update to latest [NHM](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.10)?

**Comment by S74nk0** [comment]
@N8Thrasher if you are using latest [NHM](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.10) with updated Decred miners you shouldn't be getting 100% rejects. Please reply when you can.

**Comment by N8Thrasher** [comment]
using 1.7.5.9

ok ill try the new one. thanks
