### ISSUE TITLE
1.4 ignoring skip True/False flags.

### ISSUE THREAD

**Issue by AngryOverlord** [nicehash/NiceHashMiner-Archived#83]
I currently have x11 set to skip and every time I start mining with NHminer it automatically starts mining x11.

**Comment by theLosers106** [comment]
Have you benchmark other algos yet? If not, NiceHashMiner would automatically choose the first one which is X11

**Comment by AngryOverlord** [comment]
I've tried to, the etherium one waited ~40 minutes before cancelling and lost all progress because I had to kill the NHMiner process.

**Comment by AngryOverlord** [comment]
After manually updating the values from 1.3.0.1 it works. Thanks.

**Comment by theLosers106** [comment]
May I know what CPU, GPU(s) and how much RAM you have in your system?
