### ISSUE TITLE
How to add pool settings for when there is no orders on nicehash

### ISSUE THREAD

**Issue by microtechies** [nicehash/NiceHashMiner-Archived#830]
I have tried to search everywhere and asked on Facebook and twitter can someone help me to add my own pool settings to nicehash if there is no orders or low value orders

**Comment by nicehashdev** [comment]
You cannot add other pools. NHM is designed only to work on NiceHash. If there are no orders for certain algorithm, NHM would never choose that algorithm, because payrate would be 0.
