### ISSUE TITLE
Nicehash eth dual mining not working

### ISSUE THREAD

**Issue by squeezy** [nicehash/NiceHashMiner-Archived#831]
I have tried below params in extra launch param but it doesn't work.

> -dual=Decred
> -dual=Lbry
> -dual=Pascal

https://github.com/nicehash/NiceHashMiner/wiki/Enable-ClaymoreDual-with-Decred-Lbry-Pascal

NHM still execute an Ethminer, not EthDcrMiner64.exe like it should be.
Also, in the algorithm lists, there is no dagger which will execute "EthDcrMiner64", it still says "ethminer".

I have tried on NiceHashMiner 1.7.5.8, 1.7.5.9 and 1.7.5.10 with the latest Claymore miner.

System : 

> Win 10
> GTX1060  
> driver version 381.65

> Win 10
> GTX1070
> driver version 381.89

> Win 10
> GTX1080TI
> driver version 381.89

http://imgur.com/a/qXeco

**Comment by nicehashdev** [comment]
No dual mining for NVIDIA in NHM yet.

**Comment by virtakar** [comment]
It is available now with version 1.7.5.13, you need to benchmark the algorithms and it will dual-mine for you.
