### ISSUE TITLE
No Device Found!!

### ISSUE THREAD

**Issue by GovetaXV** [nicehash/NiceHashMiner-Archived#832]
My System is new with a moderate GPU and CPU yet nicehash does not show any devices

**Comment by GovetaXV** [comment]
Also If I buy any external miner, will it work??

**Comment by nicehashdev** [comment]
If no devices are recognized by NHM, then you either have hardware that we do not support or you did not install your drivers.

NHM does not support any external miners, only CPUs and GPUs.
