### ISSUE TITLE
Why nicehash is downloading this dll at each launch?

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#839]
at **each launch**, NiceHash is downloading and overwriting the file "nvml.dll" ; what's the point to download **the same file** over and over?

1.7.5.10

**Comment by nicehashdev** [comment]
Are you sure it is downloading it? To my knowledge, it is copying it from your Program Files where you installed NVIDIA drivers.

**Comment by ghost** [comment]
Ho ok, i understand now; thanks.
