### ISSUE TITLE
Significantly lower performance on new vesion and question about dual-mining

### ISSUE THREAD

**Issue by poordude** [nicehash/NiceHashMiner-Archived#840]
While using new version of nicehash (1.7.5.10) on 7950
I get only **117-118** sols/s  that's on claymore z-cash amd miner 12.4

But on claymore z-cash amd miner 11.1 beta (was shipped with nicehash 1.7.4.5)
I'm getting **215-224** sols/s !! Such huuuge gap in performance is strange.

Also maybe i'm blind... but I just can't find "algorithm" in settings that will start "EthDcrMiner64.exe" (for  eth+ decred) mining in 1.7.5.10 version. I really can't find it. Can somebody help with that ?

**Comment by poordude** [comment]
Windows 8.1 and 16.11.4 drivers
gpu clock is only 900

**Comment by yearight** [comment]
EthDCrMiner64 is Daggerhashimoto I believe. Select it only and no others to run it only. Nicehash is choosing Zcash as most profitable for you.

As for claymore Zcash, I dunno....but perhaps choose Optiminer instead, if you can, it could be more profitable anyways.

**Comment by poordude** [comment]
Thanks for response!
Honestly I found on some forums ... and tried bat file that works with claymore_dual (that is installed with nicehash).... sadly profit is lower than on just "claymore z-cash". Probably cause my gpu is old =( and not polaris.

Also I tried "Optiminer" (gets around 160-170).... sadly its still lower than "old claymore z-cash amd miner 11.1 beta". I really have no idea why that beta version that was included with old nicehash is so special and gives me much more performance.

**Comment by yearight** [comment]
Copy and paste the old Claymore into the new versions folder is another option I think. Or just use the old version of nicehash....earnings are more important than version numbers.

All versions earn me the same anyways, but I'm an update to the latest version kind of guy.
I'm guessing Claymore is concentrating on newer videos cards, like you say.

I also think the Dag file for Eth mining is approaching 2 gigs, so if your card is only 2 gigs that may play a part.

I know there is a difference in what the app states as hashrates and earnings and what is on the website when you click check my stats. They say the website is the accurate one. Not for me.
For me, I pay most attention to what the app says I've earned so far (in the bottom right corner)...that is the correct one for me as it is the same as the payouts I get. The website stats are all over the place.

FYI: my 2 r9 380s are earning me about 5.50 CAD a day. Hashrates on Zcash are around 190 each, Eth is around 19.5 per card.

**Comment by poordude** [comment]
maybe you too should try that old version of claymore zcash miner that was shipped with nicehash 1.7.4.5 too ...cause 380 theoretically has more "tflops"... but slower memory bandwith.
or maybe not.... probably not... cause you get more money now.
cause now i get 1.5usd/day ....  203 sols/s  (while playing wow "vanilla" on same card).

**Comment by Joshwaa2010** [comment]
Look under settings and see what command line options you have for equihash for your gpu.  You can change some options to get a better hash rate.  I think it is asm 1 try asm 0 and see if it gives you more hashes.

**Comment by yearight** [comment]
Thanks for the tip. I just tried changing asm to 0 and it was worse actually.
203 sols while playing a game....seriously?....don't think I could play a game. My cards are maxed out mining....100% gpu utilization. Well... i guess my cpu mining wouldn't help either....8 cores all at 100%.
Daggerhashimoto is earning quit a bit more so I unchecked everything but that, I seen it switch to Zcash even though it was less profitable.

**Comment by S74nk0** [comment]
@poordude  This is not really related to NHM but rather to ClaymoreZec miner. You can copy over the old version over the new one if the old version gives better performance or just use the older NHM version, but this might not work if there are unsupported extra launch parameters present (**-asm** flag), so make sure to delete those in settings or in the internals folder (edit **MinerOptionPackage_ClaymoreZcash.json** more on [Wiki](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#how-to-add-missing-miner-flag)). Also using the older NHM version that gives better performance is an easier option. 
Closing issue as it is not related to NiceHash Miner program.
