### ISSUE TITLE
Balance Confirmation

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner-Archived#845]
Hello, i would like to confirm something, when i quit Nicehashminer to let my computer relax a bit, i noticed my balance was XX.XX and then when i launched Nicehashminer again after 30 minute or so, i noticed that my balance was less by at least 26 cents or so, why is this?   or is this normal? or does it not always happen?
Many thanks

**Comment by nicehashdev** [comment]
Your balance is kept in Bitcoins. Exchange rate of Bitcoins may change therefore your balance in fiat value may change. Keep in mind that you are paid in Bitcoins and displayed balance in fiat is there just for informative purposes and nothing more.

**Comment by imrecsoka** [comment]
Oh okay thanks, i only saw this now.
I didnt understand why my message was no longer on the github issues.
I am new to all of this, and i am getting old, and trying to survive this difficult life we are living where everything is so dam expensive from petrol to food to whatever! i hope i can keep up and learn.
Thanks for developing this application. I really  wish i knew about mining sooner, i feel like i have really lost out.
