### ISSUE TITLE
Stupid question

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner-Archived#846]
I was mining and closed Nicehashminer after noticing my balance in USD value.
I then re-opened my Nicehashminer shortly after and i saw that my balance was less  26 cents roughly.
I am just wondering if this happens for a reason or is this a false positive , i have never noticed it before, usually my balance is the same from the last exit and start of the application.

Thanks in advance to  Nicehash Dev Team.

**Comment by nicehashdev** [comment]
Your question has already been answered here: https://github.com/nicehash/NiceHashMiner/issues/845
