### ISSUE TITLE
Can not detect my CPU

### ISSUE THREAD

**Issue by lamfuture** [nicehash/NiceHashMiner-Archived#847]
Hi,
When using NiceHash 1.7.5.10, it can not detect Intel CPU E5-2687 (two GPUs can detect and run for miners). Although I run NiceHash with "run as administrator".
Thanks for your help.

**Comment by Timoulis** [comment]
My 2X E5-2630 v2 works perfect with latest version, if i can help someone to solve your problem.

**Comment by BaalMcKloud** [comment]
https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining

**Comment by lamfuture** [comment]
Thanks for your information. I need to click "ENABLE"  AES / AES-NI in **Bios** to see CPU detection in NiceHash

**Comment by redboxstudio** [comment]
> My 2X E5-2630 v2 works perfect with latest version, if i can help someone to solve your problem.

My   2X E5-2630 v2 do not pass the benchmark, in the logs speed 0 and the benchmark end.
How fix it?
