### ISSUE TITLE
Does NiceHash support NVIDIA Pascal architecture (Quadro series)

### ISSUE THREAD

**Issue by lamfuture** [nicehash/NiceHashMiner-Archived#849]
Quick question: Does NiceHash support NVIDIA Pascal architecture (Quadro or Tesla series)? Thank you.

**Comment by nicehashdev** [comment]
NiceHash officially supports only **desktop** graphic video cards - GeForce GTX; this means following cards:

NVIDIA TITAN Xp
NVIDIA TITAN X
GeForce GTX 1080 Ti
GeForce GTX 1080
GeForce GTX 1070
GeForce GTX 1060
GeForce GTX 1050
GeForce GTX TITAN X
GeForce GTX 980 Ti
GeForce GTX 980
GeForce GTX 970
GeForce GTX 960
GeForce GTX 950

Older cards may or may not work. Support for older cards is deprecated and we do not work on any improvements or compatibility issues for older cards. Also, professional cards (Quadro or Tesla) may or may not work. Again, we do not deal with that.
