### ISSUE TITLE
GPU #0: too many resources requested for Launch

### ISSUE THREAD

**Issue by mhosni22** [nicehash/NiceHashMiner-Archived#850]
Hi,
I suddenly get the following error
""GPU #0: too many resources requested for Launch"
"Stratum difficulty set to 256<1.00000>"
I user nichhash mining software using Nvidia Quadro 600, it was working find and just start give me this error,

can any one help me becouse I am new in mining and help me to solve this error.

Thanks

**Comment by calonjuragan** [comment]
Help  to miner get earn bitcoin free..   donasi   btc    


1JPkjyFWEzGBtgUreDao6qBbFLDVjSzvaC

**Comment by S74nk0** [comment]
**Nvidia Quadro 600** is SM 2.1 this is the lowest supported CUDA architecture. With new miner updates not all algorithms may work correctly on SM 2.1 cards and SM 2.1 will be depreciated in the near future. You can however try lowering the intensity value for the particular algorithm (look at [ccminer wiki](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#nvidia-ccminers)) this can help but with no guarantee.
Closing issue...
