### ISSUE TITLE
How does the nicehash workout which algorithm are profitable? and does this change as the day go's on.

### ISSUE THREAD

**Issue by ceejayone** [nicehash/NiceHashMiner-Archived#851]
Like is one algorithm better at 10am and another at 8pm. As I am using your software and it keeps trying to mining bitcoin which drop my daily income down as mining anything but bitcoin is more profitable. Can you help or just explain whats happening! Does power or heat play a part?

**Comment by S74nk0** [comment]
This depends on a couple of factors mainly on BTC to USD price, altcoin prices and hashing power (this depends on hardware)... on the main site there are [prices](https://www.nicehash.com/) for buyers and sellers. Please write your questions to info@nicehash.com. Open issues if there are related to NiceHash Miner program itself here on GitHub.
Closing issue...
