### ISSUE TITLE
It can not switch from Equihash to Daggerhashimoto automatically. Using RX480 card

### ISSUE THREAD

**Issue by JerryC564** [nicehash/NiceHashMiner-Archived#852]
It can not switch from Equihash(ClaymoreAMD) to Daggerhashimoto(ClaymoreAMD) even there is a higher earning. However, in contrast it can switch to Equihash(ClaymoreAMD) from Daggerhashimoto. Any advice?

**Comment by S74nk0** [comment]
@jerrychen007 Please explain this issue more in detail and/or provide the log files. I suspect that it is a coincidence that it isn't switching because of the **SwitchProfitabilityThreshold** setting

**Comment by S74nk0** [comment]
@jerrychen007 this is most likely related to a [BUG](https://github.com/nicehash/NiceHashMiner/issues/779) (resolved in this [commit](https://github.com/nicehash/NiceHashMiner/commit/6ee043491388dc3f32e824a69b0640058cc363c1)) that was present at the time of writing. Use the [current latest version](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.12) that has this issue resolved.
Closing ...
