### ISSUE TITLE
AMD driver question

### ISSUE THREAD

**Issue by Timoulis** [nicehash/NiceHashMiner-Archived#854]
As from 2016 I use the 16.11.3 version driver for my 2 RX 470. It is an old driver and I am thinking to install the latest driver. 
Anyone knows if I will have problems with newer version?

Tim

**Comment by JerryC564** [comment]
I am using 17.4.4 with my RX480, it works perfectly. Don't install the Crimson ReLive software and everything will be all right

**Comment by Timoulis** [comment]
I install the 17.5.1.
No problems until now.

Thank you my friend.
