### ISSUE TITLE
When using a VPN I cannot mine

### ISSUE THREAD

**Issue by deckador** [nicehash/NiceHashMiner-Archived#855]
I'm very new to all this, so please try to ignore my primitive terminology. When I click start on the NiceHash  Miner software, it opens up two cmd windows, and each, every minute or so, prints new text: "cannot connect" (not exactly those words, but along those lines). However, when I turn off my VPN, which I know was working fine for everything else but this program, mining works fine. I connect almost immediately. 
Should I contact my VPN provider for help, or is it more likely it's the NiceHash Miner's issue?

**Comment by Crypto-Lord** [comment]
You basically answered your question. Don't use a VPN while mining.

**Comment by nicehashdev** [comment]
Make sure that your VPN provider allows any kind of TCP traffic and not just HTTP(s).

Another thing to make sure is settings of your OS - you need to configure your VPN connection to route all internet traffic through VPN.
