### ISSUE TITLE
nicehashminer.exe keeps disappearing, fs , i dontknow why?

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner-Archived#858]
hi, so i noticed that for some reason my nicehashminer.exe keeps disappearing.
I do not have any anti virus installed and i do not have windows defender on or whatever.
Windows 7 64 bit. I was using nicehasminer fine.
The only thin i have installed was something called Awesomeminer which i deleted because i dont know how the hell to use it. I have run superantispyware; adwcleaner; and junk removal tool
Not sure what the hell is going on , every time i check after sometime the exe is missing.
any advise ?

**Comment by nicehashdev** [comment]
Maybe awesomeminer installed malware on your PC that is constantly trying to get rid of competition - us? ^^

Do a clean Windows reinstall and see what happens then.

**Comment by imrecsoka** [comment]
yah maybe cause i can hear my hard drive going ape shit, it is going mad.
what the hell why do these guys do this now they are probably scanning my entire hard drive , i wish i an find the process and kill it, damit this is crap

**Comment by imrecsoka** [comment]
I think i will do a clean re-install on my second drive partition which is my D drive which does also have data.
I wish i can format but i cant because i have so much data to move and save somewhere im thin on space.
Do you have a basic rule of thumb on what to install when installing windows 7 again?
For RX470 graphics card and basic hardware.
I would assume install windows 7  x64 and then let updates install which which will probably take forever since i do not have a quick internet line , its very unstable.
Or can i skip updates? I need to install SP1 for windows 7  at least , surely? and maybe Python and Widows Powershell?
Then MS Visual Runtime Libraries 2013 x32 and x64?
AMD driver 16.11.11 (beta) unless you can recommend me a better version?
not sure if there is a particular order of installing drivers?
Yeh anyways, IF IT WAS , then AwesomeMiner really screwed up my time here it takes forever to recover this when i can be mining instead. I have a really old hard drive 160GB SATA1.... but my D drive is a newer SATA drive at least so that should be better.

**Comment by imrecsoka** [comment]
Something is really wrong here , my nicehashminer.exe keeps disappearing
I have disabled windows defender the service and i have also got no anti-virus installed.
I dont know what to do now, i have never had this before and i have just clean reinstalled windows.
How can i track the exe and see what deletes it, this is so anoying.

**Comment by imrecsoka** [comment]
Superantipyware seems to have been the culprit although i was closing it still.
Now i am going to see Chelsea become champions :)

**Comment by MadWolf94** [comment]
ok so i added it to windows firewall and allowed it thought Seems to be ok now worth a try [http://prntscr.com/h0dhwn](url)
