### ISSUE TITLE
Did not received the money in my wallet (second time)

### ISSUE THREAD

**Issue by Hbkdavid** [nicehash/NiceHashMiner-Archived#859]
SO i started 2 weeks ago the first payment was right but the second today is not right i didnt received anything in my wallet .. is this normal?

**Comment by imrecsoka** [comment]
Not sure, the scheduled date for payment should be the date you see the money in your wallet.
Are you using offline wallet like me? 130 odd GB of Bitcoin core blockchain its crazy .
I have to Synch it every day else it will take forever to update when i leave it long without synching.

**Comment by S74nk0** [comment]
@Hbkdavid Please write to support@nicehash.com about this issue. Write your BTC address and give as much detail as possible regarding this problem.
Closing issue as it is not related to NHM program or source code.
