### ISSUE TITLE
nice hash will not mine.

### ISSUE THREAD

**Issue by maveric296** [nicehash/NiceHashMiner-Archived#862]

**Comment by imrecsoka** [comment]
Kindly elaborate please.
You have your NiceHashMiner open : check?
Miners downloaded : check?
Benchmarks have been run : check?

**Comment by S74nk0** [comment]
@maveric296 Please provide more information about your issue, what CPUs, GPUs are on the system, log files generated in the NHM folder. How and when does the issue occur so we can reproduce it? 
Reopen this issue with detailed information.
Will close it now as the description is too vague.
