### ISSUE TITLE
Problem with algorithm

### ISSUE THREAD

**Issue by allessi10** [nicehash/NiceHashMiner-Archived#864]
Cpu: Intel core i76700 @3.4ghz
Gpu: Nvidia Gtx 1080

Im having a problem with the algorithms. It only shows the CryptoNight when i am in the benchmark section. My friend says that it should be alot more miners/benchmark things, im barely earning any money either. Would love some help with this!

**Comment by nicehashdev** [comment]
Have you installed latest NVIDIA drivers?

**Comment by S74nk0** [comment]
@allessi10 Please post a screenshot of the benchmarks Form. What does happen when you click on the **Nvidia Gtx 1080** device in devices list?

**Comment by allessi10** [comment]
Sorry, i got it!
