### ISSUE TITLE
NHM doesnt switch to most profitable algo

### ISSUE THREAD

**Issue by fefsf** [nicehash/NiceHashMiner-Archived#865]
Ive noticed this happen a few times on my rigs. ive noticed sometimes NHM will be stuck on one algorithm and not change even though its mining an algorithm that isnt the most profitable. For example, one of my rigs was ''stuck' on LBRY making ~17 bucks a day but when i click stop and start they started doing EQM making well over 23/day. This happened on all three of my machines, when i clicked stop and start they all switched back to EQM but otherwise could have continued mining the same less profitable algorithm. And yes the miners were well outside the switch time in settings

**Comment by S74nk0** [comment]
@fefsf This bug has been located and fixed. Please check this [comment](https://github.com/nicehash/NiceHashMiner/issues/779#issuecomment-300782497) for more information. Until there is a new official release you can use the [pre-release](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.11-pre/NiceHashMiner_v1.7.5.11_PreRelease_01.zip).

Closing...
