### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by allessi10** [nicehash/NiceHashMiner-Archived#867]
When i am mining equihash everything is fine, but when i mine pascal or Lyra2REv2 my computer get small freezes almost every second. Would love some help on this issue!

**Comment by mono-ped** [comment]
I never had an issue with l2r2, but my system lagged with pascal on v1.7.5.10

It seems fine when using v1.7.5.11_PreRelease_01

Perhaps it's nothing to do with versions, maybe it's an issue when using an non-dedicated mining rig. When i noticed lag-free pascal mining i wasn't working on the machine in question.

**Comment by nicehashdev** [comment]
You need to use extra launch parameters and adjust intensities for each card/algorithm to make lagless mining: https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters
