### ISSUE TITLE
Can I add missing Algo?

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#868]
I can run ccminer_cryptonight  on my GTX 460 on a command prompt but on NHM 1.7.5.10, I can only run Decred while Lbry is not supported.
![capture](https://cloud.githubusercontent.com/assets/24593637/26002069/1be19976-3737-11e7-9148-531af84702ea.PNG)

Also Claymore_Dual, I can run it on a separate command window but it's not available on NHM.
![capture](https://cloud.githubusercontent.com/assets/24593637/26002596/d387a6b4-3738-11e7-8807-5d7534b88d63.PNG)

**Comment by nicehashdev** [comment]
We do not work on support for such old cards. We do not test them and there may be big issues with older cards. If old cards are working, fine, if not, we have no plans fixing that.

If you still want to use old hardware with NHM, but something doesn't work correctly, feel free to modify source of NHM to suits your needs.
