### ISSUE TITLE
help my pliz 

### ISSUE THREAD

**Issue by mouaoued** [nicehash/NiceHashMiner-Archived#870]
NiceHash Miner has detected change of hardware ID .

**Comment by nicehashdev** [comment]
Just click OK and continue with usage, nothing wrong with that.

**Comment by JesusTheHun** [comment]
I'm still curious to know how to disable it. I've created a usb install with all software needed on it, so I can copy it for all my rigs and it's annoying, I've tried to remove some bench log or entries in the config directory, without success. Can you provide some hints please

**Comment by nicehashdev** [comment]
Sorry, this is just one of the security technique to prevent Botnet miners.

**Comment by cpshoemake** [comment]
Delete the General.json file in the configs folder. This will reset the settings and the message will disappear. Benchmarks are not affected.
