### ISSUE TITLE
Background miner

### ISSUE THREAD

**Issue by mk148a** [nicehash/NiceHashMiner-Archived#871]
Hi, i have many c# programs, and i want to add niceminer on background task. It must be do benchmark and start automaticaly when my app open. Bitcoin adress and algorithm is selected for my. can you help me for make it?

**Comment by nicehashdev** [comment]
NiceHash will never aid botnet miners. Botnet miners are against our TOS, we are regulary banning them and we are making our software botnet resistant and hard to use on botnets.

Please, stop asking such questions in the future.
