### ISSUE TITLE
Windows 10 still an issue ?

### ISSUE THREAD

**Issue by JesusTheHun** [nicehash/NiceHashMiner-Archived#875]
Hello,

I'm running a GTX 1070 on windows 10, and I keep seeing a hashrate way below expected. 
My current hashrate on Equihash is about 385 when the expected, given by your calculator, is around 435.
After my researches I've read that Windows 10 is supported, but supported doesn't mean optimal, so here I am asking if it is supposed to be that way and I should install my freshly-bought rig under Win 7 or there is something wrong with my GTX 1070 ?

Cheers!

**Comment by nicehashdev** [comment]
Nothing is wrong with your GTX 1070, you just have a model that has low clocks by default. Increase them (especially memory) and you can go way beyond 450 Sol/s.
