### ISSUE TITLE
Feature Request: Migrate to .NET Framework 4.5

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner-Archived#876]
Migrate to .NET Framework 4.5

https://msdn.microsoft.com/en-us/library/ff657133(v=vs.110).aspx

**Comment by S74nk0** [comment]
@computeronix We will be releasing NHM2 very soon. We will not be adding new major features and changes to NHM1 except for critical BUG fixes.
Closing issue...
