### ISSUE TITLE
Worker Name Invalid

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner-Archived#878]
Worker name invalid appears on start if the worker name is invalid

The GUI should prevent you form putting in the invalid name.

For example if I put in an 8+ character name (sunsundays) it lets me.  Then when i close and reopen the miner it says invalid worker name.

In the text box for the worker name set the length to 7 characters and then do a validation check on the requirements too and this will prevent this use case from occuring

**Comment by S74nk0** [comment]
@computeronix We will be releasing NHM2 very soon. We will not be adding new major features and changes to NHM1 except for critical BUG fixes.
Closing issue...
