### ISSUE TITLE
NiceHashMiner_v1.7.5.12 Internet connection drops on ether

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#883]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/1005197/log.txt)
win 10
amd asus 470 x 4, nitro x 2
8 gb ram
1000 watt + 1100 watt power supply

The bench mark went great BUT once i try start mining eth it goes as far as "remote connection port 4000" and then starts cycling in lost connection. At the same time i cannot browse anything. Once i stop the NHM the internet comes back.... What could be the problem?

**Comment by ChriscomIT** [comment]
Something is redirecting nicehash traffic to your own host IP so the nicehash address can't be resolved. Do you run an antivirus or network security solution which might be interfering or altering the host file? There similar symptoms with Asus routers that feature Trend Micro security engine.

**Comment by undefy** [comment]
Well the thing is i was mining fine before and this came up recently =( I have no problem mining Dagger on gtx cards. Also zec is mining fine on the AMDs.

I do not have any AV and disabled windows firewall. i used tp link tl-wn821N up to now with no issues. But since the start of the week this problem occurred. I tried a wired (RJ45) connection through my totolink 300 router. A bit better but connection keeps getting lost and about 95% rejection rate.

Any ideas? Should i try tunneling or will this have no affect?

**Comment by undefy** [comment]
I am going to close this. The problem was that i updated the realtek lan driver! Had to reinstall windows as it would not load because of it (tried removing and reinstalling it in safe mode = didn't help) disabled driver update and every thing is running smoothly!

**Comment by undefy** [comment]
just noticed that i am getting 50% rejection rate =( not sure if this to do with nicehash being down for maintenance....

**Comment by undefy** [comment]
Everything seems to be working fine now.

**Comment by juanjux** [comment]
I have an Asus AC68U router and I couldn't connect or subscribe until I disabled "Vulnerability Protection"  (under AIProtection) that uses that Tren Micro Virtual Partch thing.
