### ISSUE TITLE
Eset quarantine   xmr-stak-cpu.exe as a Trojan 

### ISSUE THREAD

**Issue by ganeshthevar** [nicehash/NiceHashMiner-Archived#887]
![image](https://cloud.githubusercontent.com/assets/20280944/26191883/453bfe34-3bcd-11e7-92eb-c6690f5ab91d.png)

**Comment by CAVACO-PT** [comment]
yes having same issue ...

**Comment by fefsf** [comment]
exempt NHM from scans

**Comment by ganeshthevar** [comment]
Thanks @fefsf   

@MACE-Zer0   

![image](https://user-images.githubusercontent.com/20280944/30032042-6705c326-91b1-11e7-8bef-f7697b128455.png)
