### ISSUE TITLE
ESET Reporting NICE HASH ...

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner-Archived#890]
HEllo , my miners are stoping to work because a lot of files are getting reported by eset av ... and it moves them to quarantine ... tried to add it do non scan by still doing it....

**Comment by nerdatwork** [comment]
ESET in my humble opinion sucks. Try Avast

**Comment by undefy** [comment]
OR go Chinese for total 360

P.S. Eset is a but of a downer alright
