### ISSUE TITLE
NHM Website error?

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner-Archived#891]
![nice](https://cloud.githubusercontent.com/assets/24593637/26256752/a25931be-3cc6-11e7-9abf-81f1b0650689.PNG)

**Comment by undefy** [comment]
Guess their server was overloaded with requests so the implemented a waiting que.

**Comment by Johann1982** [comment]
This is really irritating. Even if I wait the 59 seconds, it won't let me in. I have to refresh 50 times before it goes through.

**Comment by Timoulis** [comment]
I have the same issue with you.
This occurs only with firefox. Try chrome and will open.

**Comment by weespin** [comment]
IP based quota.
NiceHash already know about this issue, they're working with new api rn.

**Comment by nicehashdev** [comment]
Use reddit, facebook or twitter to discuss this.

Not related to NHM issues. Closing.
