### ISSUE TITLE
Nicehash payout moved?

### ISSUE THREAD

**Issue by aakashmurthy** [nicehash/NiceHashMiner-Archived#892]
Hi I'm sorry but I don't know where to put this, so I'm putting this here. Before the nice hash my miner page told me that I would get paid out today, but it now says that I'm going to get paid out on the 9th of June. Help.

**Comment by nicehashdev** [comment]
https://www.nicehash.com/index.jsp?p=news&id=159

Not related to NHM issues. Closing.
