### ISSUE TITLE
Stratum Proxy Disconnected

### ISSUE THREAD

**Issue by bigdaddyjsb** [nicehash/NiceHashMiner-Archived#898]
Hi,

I installed the latest version of Nicehash, and I am trying to mine on my Nvidia GPU's however,  I cannot connect to any crypto type.  Every single one gives me the same Stratum Disco error.  Why would my IP be banned?  I am currently from 99.248.129.101

What else can I do???

Thanks - Jason
![2017-05-22_15-32-51](https://cloud.githubusercontent.com/assets/16542063/26325198/f67d1bf4-3f03-11e7-916a-1c7aea479eb8.png)

**Comment by nicehashdev** [comment]
I would suggest you to check your router/firewall.

Make sure there are no security rules that affects stratum protocol.
