### ISSUE TITLE
Mining with Nice Hash not putting money into Coinbase wallet help

### ISSUE THREAD

**Issue by nschainblatt** [nicehash/NiceHashMiner-Archived#899]
Copied and pasted bitcoin address into nice hash miner and ran it, about an hour, later had like 5 cents and it didn't put it in my coin base. Am I doing something wrong, please help.

**Comment by gordesky1** [comment]
i also noticing this...  Im new too mining so maybe it just takes awhile to update?    

even on nicehash wallet it shows 
Confirmed BTC balance
0.00000000
Pending BTC balance
0.00000000

is that even normal? even tho in the program it self shows 43cents..

**Comment by fefsf** [comment]
Please read this about payment schedule. 

https://www.nicehash.com/?p=news&id=159

**Comment by S74nk0** [comment]
Not related to NHM1 code. Closing
