### ISSUE TITLE
Automatic software update

### ISSUE THREAD

**Issue by raoulh** [nicehash/NiceHashMiner-Archived#906]
Hi,

I'm using Nicehash miner on different machine, and it's a pain to manually update all of them when you release an update. I need to go on all machine, copy the config, download the new zip, start it, wait for all the miners zip files to finish to download (that could take time...) and finally start to mine again! That tasks could highly be automated!

I know you are working on Nicehash 2. It would be great to see an automatic update feature. Or at least something that does the download in background, prepare everything, and once a I go to the machine just click a button to replace the version and to start benchmark(if needed) and mining. That would be an awesome missing feature of the current software.

Thanks

**Comment by giosal** [comment]
I completely agree.
In my case, I'm using a lot of VMs to mine, so it's kind of difficult to update NHM on dozens of machines...

**Comment by dadoremix** [comment]
yep.. 
update only files what need
So it can be saved on the server traffic / bandwidth

**Comment by S74nk0** [comment]
@all This feature is partly implemented in NHM2 (Alpha). Of course the goal is to have a plug and play approach with automatic updates and miner file updates (updates only needed miners) and auto new benchmarks (for updated miners). This will be available in NHM2. 
I suggest ti open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report. 

Closing...
