### ISSUE TITLE
NiceHash Miner 2.0 Questions

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner-Archived#908]
Hello , fist of all thanks for sending me the link ... i have a question  in the new miner 2.0 ... to add in the claymore dual  , dual mining i have to edit the config files for each gpu and put this ??

{
			"Name": "ClaymoreAMD_Equihash",
			"NiceHashID": 24,
			"MinerBaseType": 4,
			"MinerName": "equihash",
			"BenchmarkSpeed": 0,
			"ExtraLaunchParameters": "-dual=Pascal",  ?????
			"Enabled": true,
			"AlgorithmStringID": "ClaymoreAMD_Equihash",
			"MinerBinaryHashID": ""

2nd question where are the Miner System variables , are they addded already or u still going to add them later on ???
 
in the old one u had a MinerSystemVariables.json with this 👍 

bin\\sgminer-5-6-0-general\\sgminer.exe": {
    "GPU_MAX_ALLOC_PERCENT": "100",
    "GPU_USE_SYNC_OBJECTS": "1",
    "GPU_SINGLE_ALLOC_PERCENT": "100",
    "GPU_MAX_HEAP_SIZE": "100",
    "GPU_FORCE_64BIT_PTR": "1"
  },
  "bin\\sgminer-gm\\sgminer.exe": {
    "GPU_MAX_ALLOC_PERCENT": "100",
    "GPU_USE_SYNC_OBJECTS": "1",
    "GPU_SINGLE_ALLOC_PERCENT": "100",
    "GPU_MAX_HEAP_SIZE": "100",
    "GPU_FORCE_64BIT_PTR": "1"
  },
  "bin_3rdparty\\claymore_cryptonight\\NsGpuCNMiner.exe": {
    "GPU_MAX_ALLOC_PERCENT": "100",
    "GPU_USE_SYNC_OBJECTS": "1",
    "GPU_SINGLE_ALLOC_PERCENT": "100",
    "GPU_MAX_HEAP_SIZE": "100",
    "GPU_FORCE_64BIT_PTR": "1"
  },
  "bin_3rdparty\\claymore_zcash\\ZecMiner64.exe": {
    "GPU_MAX_ALLOC_PERCENT": "100",
    "GPU_USE_SYNC_OBJECTS": "1",
    "GPU_SINGLE_ALLOC_PERCENT": "100",
    "GPU_MAX_HEAP_SIZE": "100",
    "GPU_FORCE_64BIT_PTR": "1"
  },
  "bin_3rdparty\\optiminer_zcash_win\\Optiminer.exe": {
    "GPU_MAX_ALLOC_PERCENT": "100",
    "GPU_USE_SYNC_OBJECTS": "1",
    "GPU_SINGLE_ALLOC_PERCENT": "100",
    "GPU_MAX_HEAP_SIZE": "100",
    "GPU_FORCE_64BIT_PTR": "1"
  },
  "bin_3rdparty\\claymore_dual\\EthDcrMiner64.exe": {
    "GPU_MAX_ALLOC_PERCENT": "100",
    "GPU_USE_SYNC_OBJECTS": "1",
    "GPU_SINGLE_ALLOC_PERCENT": "100",
    "GPU_MAX_HEAP_SIZE": "100",
    "GPU_FORCE_64BIT_PTR": "0"
  }
}

**Comment by alex-milanovic** [comment]
I didn't get the link, is it only a few people getting it?

**Comment by S74nk0** [comment]
@MACE-Zer0 please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
