### ISSUE TITLE
NHM 2.0.0.3 Alpha won't complete benchmarking

### ISSUE THREAD

**Issue by MNewman** [nicehash/NiceHashMiner-Archived#909]
Fresh install of NHM, appears to complete benchmarking successfully, generates benchmark json files, but then continues to ask to benchmark every time without ever actually mining.

Last few lines of the log.txt:

{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK] ---\n  - \"-a\"\n  - \"equihash\"\n  - \"-b\"\n  - \"20\"\n  - \"-cd\"\n  - \"1\"\n  - \"1\"\n","time":"2017-05-24T15:09:44.709Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK] Benchmark starts","time":"2017-05-24T15:09:44.709Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK excavator-MINER_ID(33)-DEVICE_IDs(1)] Using miner: C:\\Users\\redacted_user_name\\AppData\\Roaming\\nhm2\\bin\\excavator\\excavator.exe","time":"2017-05-24T15:09:49.212Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK] C:\\Users\\redacted_user_name\\AppData\\Roaming\\nhm2\\bin\\excavator\\","time":"2017-05-24T15:09:49.212Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK excavator-MINER_ID(33)-DEVICE_IDs(1)] We have failed Error: spawn C:\\Users\\redacted_user_name\\AppData\\Roaming\\nhm2\\bin\\excavator\\excavator.exe ENOENT","time":"2017-05-24T15:09:49.214Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK] child process exited with code -4058","time":"2017-05-24T15:09:49.214Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK] Benchmark for Pascal: 0","time":"2017-05-24T15:09:49.214Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK] ---\n  - \"-a\"\n  - \"pascal\"\n  - \"-b\"\n  - \"20\"\n  - \"-cd\"\n  - \"1\"\n","time":"2017-05-24T15:09:50.223Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BENCHMARK] Benchmark starts","time":"2017-05-24T15:09:50.223Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[NICEHASH] SMA get","time":"2017-05-24T15:10:38.044Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[NICEHASH] workerName= obs","time":"2017-05-24T15:10:38.046Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetAlgorithmRates => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=simplemultialgo.info\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:10:38.145Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetAlgorithmRates => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=simplemultialgo.info\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:10:40.275Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetAlgorithmRates => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=simplemultialgo.info\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:10:42.408Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetAlgorithmRates => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=simplemultialgo.info\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:10:44.484Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetAlgorithmRates => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=simplemultialgo.info\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:10:46.602Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[SMA_Promise_ResolveCallback] promise stream has returned Optin.NONE","time":"2017-05-24T15:10:48.603Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[InternetCheckerController] HAS Intenret connection","time":"2017-05-24T15:11:05.995Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[NICEHASH] Balance get","time":"2017-05-24T15:11:43.038Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[NICEHASH] workerName=obs  &&  btcAddr=redacted_wallet_address","time":"2017-05-24T15:11:43.040Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetBalance => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=stats.provider&addr=redacted_wallet_address\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"redacted_wallet_address.obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:11:43.130Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetBalance => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=stats.provider&addr=redacted_wallet_address\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"redacted_wallet_address.obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:11:45.257Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[GetHttpJsonRequestBase] {\n \"MainErrorMsg\": \"GetHttpJsonRequest<T> RequestError: Error: unable to verify the first certificate\",\n \"CalledFromFunction\": \"GetBalance => GetNiceHashAPIDataTemplate<T>\",\n \"url\": \"https://api.nicehash.com/api?method=stats.provider&addr=redacted_wallet_address\",\n \"option\": {\n  \"timeout\": 20000,\n  \"headers\": {\n   \"NHM-OS\": \"WINDOWS\",\n   \"User-Agent\": \"NiceHashMiner/2.0.0.3\",\n   \"NiceHash-Worker-ID\": \"redacted_wallet_address.obs\",\n   \"NHM-Active-Miners-Group\": \"IDLE\"\n  }\n }\n}","time":"2017-05-24T15:11:47.393Z","v":0}
{"name":"NHM","hostname":"redactedhostname","pid":16884,"level":30,"msg":"[BalanceCheckHandler] promise stream has returned Optin.NONE","time":"2017-05-24T15:11:49.395Z","v":0}

**Comment by S74nk0** [comment]
@MNewman please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.

**Comment by S74nk0** [comment]
@MNewman  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
