### ISSUE TITLE
[feature request] allow 'sgminer' to mine when switching windows user on same PC

### ISSUE THREAD

**Issue by computerchuck** [nicehash/NiceHashMiner-Archived#91]
It seems all algos that use sgminer.exe will hang if you switch user accounts on the same computer.

*Note: no problem with ethereum mining when switching user accounts. 

Scenario:  You login to Windows as Admin1, launch NiceHash Miner, start mining.   You click start, switch user, then you login as Admin2.   If you 'switch account' back to Admin1, you'll notice that your sgminer.exe windows are hung and are not progressing.   You have to hit 'stop' on the NHM, then start.  it then begins to mine correctly again, until you 'swtich user' to another WIndows session.  

So, I'm hoping there could be a way to improve NHM to allow mining under another running windows login on the same computer.  

Thanks for all your help and suggestions.

with best regards,
Chuck

**Comment by theLosers106** [comment]
Would the latest version's feature to hide the NiceHashMiner to tray do the trick for you instead of switching users?

**Comment by computerchuck** [comment]
Not really.

**Comment by nicehashdev** [comment]
This is the issue of sgminer application which we only "borrowed" in NHM. Contact sgminer developers regarding this issue.
