### ISSUE TITLE
nh 2.0.0.3 - nvidiasetp0state?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#910]
I'm running windows 10 with 1x 1080 and 1x 980 ti.  Should I turn this on and if so, where is the option.  I edited the config file from false to true and ran the app as admin.  Any thoughts?

**Comment by S74nk0** [comment]
If you ran it as admin then it is executed after startup it will not ask for permissions. If running it as a normal user you should be getting a dialog for admin privs.
Closing...
