### ISSUE TITLE
Nice HashMiner 2.0 CryptoNight (XxnrStackCPU) BenchMark not working

### ISSUE THREAD

**Issue by Hannibaldz** [nicehash/NiceHashMiner-Archived#912]
when BenchMark CryptoNight (XxnrStackCPU) will stay Needs Benchmark and not Start mining cpu

**Comment by S74nk0** [comment]
@Hannibaldz please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.

**Comment by S74nk0** [comment]
@Hannibaldz  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
