### ISSUE TITLE
NiceHashMiner v2 not taking into account CPU accepted speed

### ISSUE THREAD

**Issue by virtakar** [nicehash/NiceHashMiner-Archived#915]
CPU is mining correctly, results are accepted by the pool and it appears in the website, but a speed of 0 is displayed in the application. When a result is accepted the value bumps to the accepted speed then instantly goes back to 0, forcing xmr-stak-cpu to restart when declared not profitable enough.
![nicehash_com_screen_capture](https://cloud.githubusercontent.com/assets/17980657/26416008/ba0e1ff8-40b4-11e7-9e02-7eb20bb351fc.png)
![nicehash_screen_capture](https://cloud.githubusercontent.com/assets/17980657/26416009/ba1377a0-40b4-11e7-94ac-ac36ce1dc394.png)

**Comment by S74nk0** [comment]
@virtakar  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
