### ISSUE TITLE
Alpha 2 Doesn't acknowledge CPUs that 1.7 did ??

### ISSUE THREAD

**Issue by microtechies** [nicehash/NiceHashMiner-Archived#916]
Is this a known issue or do i need to do something to the config file ?

**Comment by microtechies** [comment]
I must state some CPUs I have many machines

**Comment by S74nk0** [comment]
@microtechies  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
