### ISSUE TITLE
NHM 2 alpha benchmarking crash in sgminer

### ISSUE THREAD

**Issue by logiclrd** [nicehash/NiceHashMiner-Archived#918]
On my Radeon 7970, the benchmarking for NHM 2 crashes in the middle of the sgminer benchmarking. The crash itself is obviously sgminer's fault, but in the older NHM, I was able to specify the style of benchmarking, and while it, too, had a crash in the default benchmarking of sgminer, the longer "Precise" benchmark completed without issues. With Alpha 2, it appears I no longer have the option to specify the type of benchmark, and the default type done does crash.

I also don't know whether there is anything NHM could be doing differently to work around the crash in the first place.

(As an aside, does this count as an entry into the draw for 0.25 BTC ?)

**Comment by S74nk0** [comment]
@logiclrd  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.

**Comment by logiclrd** [comment]
Ah, my mistake -- done. :-)
