### ISSUE TITLE
Nicehash Miner V2.0.0.3 Alpha does not mine after benchmarks

### ISSUE THREAD

**Issue by Opc9** [nicehash/NiceHashMiner-Archived#921]
The name of my PC is i7-975 after NHM V2 completes the benchmarking and when I click start miner
it says.

Windows cannot find 'C:\Users\i7'

Seems if there is a - sign in your windows username the miner will not work after the benchmarks run.

**Comment by S74nk0** [comment]
@Opc9  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
