### ISSUE TITLE
NHM 2 Alpha Key Shortcuts don't work

### ISSUE THREAD

**Issue by DeeJayBro** [nicehash/NiceHashMiner-Archived#923]
I am on WIndows 10 and I don't know if this is on purpose, but i cannot use Shortcuts for example I cannot close menus with the Esc-Key or accept something with The Enter-Key.

**Comment by S74nk0** [comment]
@DeeJayBro  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
