### ISSUE TITLE
Allow custom installation path or zip format for NHM2 windows installer

### ISSUE THREAD

**Issue by De-Occultist** [nicehash/NiceHashMiner-Archived#924]
The NHM2 windows installer should allow user to specify their own installation directory instead of installing it to %userprofile%\AppData\Local\Programs\nhm2 .
Since most AV will detect the miners as trojans, a custom installation directory would allow users to install to a directory excluded from AV auto protection.

A zip package release like before would also be a good option for power users and convinience.

Thanks.

**Comment by S74nk0** [comment]
@De-Occultist  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
