### ISSUE TITLE
NiceHash Miner v1.7.5.12 not registering speed

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#926]
win 10
6 x 6gb gtx 1060
Biostar bt 85
RAM 8gb
Power 2100 watts dell server PSU

Logs and pictures areatteched.

I set it up last night no OC, left it running for the night @ around 20 USD per day. After about 8 hours of mining all i got was 13 cents =( For some reason the speeds are not registering. 

Also it after the excavator window shows up it takes awhile to start up. What can i do? 

I tried switching servers from Amsterdam to china but the speed does not show up at all!
[log.txt](https://github.com/nicehash/NiceHashMiner/files/1028418/log.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/1028419/log.1.txt)
![screenshot 1](https://cloud.githubusercontent.com/assets/19608698/26442968/773c6202-40eb-11e7-8523-1d25f68d5006.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19608698/26442967/773a2fdc-40eb-11e7-9c36-1fb77511ade4.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19608698/26442969/773de212-40eb-11e7-8210-72399a6e16b8.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/19608698/26442966/77399a04-40eb-11e7-9fae-12fa3c1e4ac5.png)

**Comment by undefy** [comment]
Fixed it! NHM does not work with the latest nvidia drivers!!! Had to roll back to previous version.

**Comment by TGM** [comment]
What version?

**Comment by undefy** [comment]
Had to reopen. I have problem with ether, connection just drops and it goes into reconnect loop. Zec is better but i get 15% reject rate from time to time.

My other rig , 3 970s ,2 1060 3gb and 1 1060 6gb do not exoerince this.

Does not work on nvidea 388. 385 is ok
