### ISSUE TITLE
Stop mining when switch to DaggerHashimot  on v2.0.0.3 alpha and v1 both

### ISSUE THREAD

**Issue by arrmor** [nicehash/NiceHashMiner-Archived#927]
Hi there!
Miner stops mining process when switch to DaggerHashimot!!! It start to happens from yesterday when u release v2.0.0.3A.
I have this issue both on v2 and v1 nicehash miner.

![2017-05-25 6](https://cloud.githubusercontent.com/assets/28950108/26447473/5627d46e-4151-11e7-975e-9247d2b019ca.png)
![2017-05-25](https://cloud.githubusercontent.com/assets/28950108/26447485/6772d6c4-4151-11e7-9e1b-9d12c8d1d24a.png)

It happens to me every hour now and i loosing my money((

**Comment by S74nk0** [comment]
@MrHump  please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
