### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by FoxyBit** [nicehash/NiceHashMiner-Archived#932]
I have been using this version since yesterday and I've noticed that whether I am using just GPU, or CPU and GPU the program will slowly increase it's memory usage up to the maximum available. Upon stopping mining, the memory size stays the same.

I'm not sure what information you require but I've attached my log file for the last 'run'.
[log_reference.txt](https://github.com/nicehash/NiceHashMiner/files/1029348/log_reference.txt)

**Comment by S74nk0** [comment]
@FoxyBit Yes there is a memory leak in the version of the provided log file. Check this [issue](https://github.com/nicehash/NiceHashMiner2/issues/18). For all future **NiceHashMiner2** issues please open them in the [NiceHashMiner2 repo](https://github.com/nicehash/NiceHashMiner2). Thanks for the report. Closing issue as it is not related to **NiceHashMiner1**
