### ISSUE TITLE
Power for PCIE Risers

### ISSUE THREAD

**Issue by Claybro31** [nicehash/NiceHashMiner-Archived#936]
I see that PCIE risers come with a 6pin to sata. What would I even plug the sata into? A sata to 6pin adapter? Why couldn't I just use a 6pin to 6pin for each PCIE riser instead of plugging the sata into a daisy chain adapter and back to the power supply. Can I use these pictured below for each PCIE riser?
![7125apvp9sl _sl1500_ jpg 63724ba6598687b5937bfa2b7d908aeb](https://cloud.githubusercontent.com/assets/28884242/26478281/04c55ef0-4180-11e7-8147-5e41903f177b.jpg)

**Comment by arrmor** [comment]
Why you open an issue in nicehash miner topic and telling us about risers?)))

**Comment by semisane** [comment]
This is not NHM topic but these worked well for me:

http://amzn.to/2qrBJ7p

One was bad but they sent a free replacement overnight.

**Comment by Claybro31** [comment]
Thank you for your responses. Closed.
