### ISSUE TITLE
Throttle when not idle?

### ISSUE THREAD

**Issue by rayzorben** [nicehash/NiceHashMiner-Archived#940]
Right now the idle feature works well, but it stops completely. I don't mind it using say 50% of my GPU when I am using the computer. If it runs at 100% I can barely use excel or watch a video. 

If I wanted to play a game, I would stop it manually.

Any possibility of introducing throttling when the computer is in use vs stopping completely?

**Comment by S74nk0** [comment]
@rayzorben Yes this will probably be added in NHM2 in one of the future stable releases... 
I would suggest to open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
