### ISSUE TITLE
Miner destroyed???

### ISSUE THREAD

**Issue by arrmor** [nicehash/NiceHashMiner-Archived#941]
Hi there!
Last 2 days having troubles with both v1 and v2. This one happened to me few minutes ago.
![2017-05-26 3](https://cloud.githubusercontent.com/assets/28950108/26505282/d7d102d8-4250-11e7-9ca1-659b1a23392f.png)
 What is that? Why miner stops and idle to much? And what i need to do to fix it?
TY!
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/1032564/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/1032565/log.txt)

**Comment by arrmor** [comment]
It is on v1.7.5.12 btw.

**Comment by arrmor** [comment]
any troubleshooting advises?
PLS!! Because of that issue 1-1.5h a day my rig is not working((

**Comment by arrmor** [comment]
Guys! i don't need to cooling up i need work)
Help PLS!
![2017-05-28](https://cloud.githubusercontent.com/assets/28950108/26531480/947a2aa2-43f2-11e7-8623-268c23d4836d.png)

**Comment by S74nk0** [comment]
@MrHump the restarts happen when the API port reads aren't available (miner freeze, 0 speed reports), it restarts the miner so it doesn't go in limbo and not mine at all. ethminer DAG creation takes some time after new starts or new jobs this can add up. You can increase in the switch minimum time in advanced settings this will reduce switch times and can increase stability (but reduce most profitable algorithm switch). Looking at the logs everything seems to be in order.

Closing issue

**Comment by arrmor** [comment]
TY, will try it
