### ISSUE TITLE
Miner do not see and use 6th GPU

### ISSUE THREAD

**Issue by arrmor** [nicehash/NiceHashMiner-Archived#946]
Hi there!
![2017-05-27 2](https://cloud.githubusercontent.com/assets/28950108/26524203/41f50bf8-4334-11e7-9b8c-f3b344c200fe.png)

v1.7.5.12 do not see my 6th gpu, but afterburner and device manager does((

**Comment by tmslacker** [comment]
reinstall the driver with express and don't reboot! Then relaunch the miner!

**Comment by arrmor** [comment]
only after restart miner start to use all gpu's...
TY for advice
