### ISSUE TITLE
Equihash bench not working GTX780Ti W10 64 bits

### ISSUE THREAD

**Issue by briferz** [nicehash/NiceHashMiner-Archived#947]
Today I installed the latest Nicehash client for windows.
All other algos run without problems (except maybe the hashimoto one, which runs very low due to the W10/Nvidia drivers issue)

The software just tells me that the benchmark failed to run. I have both W10 and the graphics driver updated. What else can I say? I have 16 GB of RAM.

Thanks for your support.

**Comment by nerdatwork** [comment]
Try older Nicehash miner version.

**Comment by briferz** [comment]
Yeah, I just found info regarding this issue. It looks like the CUDA Compute capability of my GPU (3.5) is not supported by the Equihash miner. It's such a shame, because the gpu isn't that old.

Thanks!
