### ISSUE TITLE
Nice hash miner v2.0.0.4 not displaying estimated daily earnings

### ISSUE THREAD

**Issue by sil2222** [nicehash/NiceHashMiner-Archived#949]
Just updated to new release miner v2.0.0.4 miner is no longer displaying daily estimated earnings it shows 0.00 usd

**Comment by Squall-Leonhart** [comment]
it will show them after some time.

**Comment by S74nk0** [comment]
@sil2222 please open this issue on [NiceHashMiner2 page](https://github.com/nicehash/NiceHashMiner2). We will address it there. Thanks for the report.
