### ISSUE TITLE
Stop mining bellow user-defined payout threshold

### ISSUE THREAD

**Issue by PauloOF** [nicehash/NiceHashMiner-Archived#95]
I would like to have a pay-out threshold (for example BTC/GH/Day, BTC/day or $/day) allowing NiceHashMiner to stop bellow that and resume above. The general idea is to avoid eventual no positive revenue vs energy costs for any of the selected algorithms at the benchmark under Auto-Switching feature.

Is this possible using the parameters described in the "Fine tuning with custom speed factors and daily costs" section?

**Comment by theLosers106** [comment]
This feature is added in the latest NiceHashMiner v1.5.0.0
