### ISSUE TITLE
XMR-Stack-cpu config0 getting overridden by Nicehash software

### ISSUE THREAD

**Issue by MunsuDC** [nicehash/NiceHashMiner-Archived#950]
So I've noticed that simply launching the .exe miner from bin\xmr-stak-cpu gets me correct (as specified in manually edited config.txt) affinities and reasonable hash rate (500+) on my Ryzen 7. But launching the Nicehash app overrides the config_0 file with some rubbish about 12 non-affined threads and this gets me down to, like, 280 H/s. 
Could you look into this? For now, I've set up the external miner with wallet strings from config0. 
One other observation is that changes to notls policy in config prevent the miner from starting; needless to say that doesn't happen with direct launch.
AFAIK many people struggle with the same issue.

Also, it would be nice if you posted settings or configs in articles like that one with 1700X testing where you boast 510 H/s.

![screenshot 2017-05-29 03 31 27](https://cloud.githubusercontent.com/assets/5533353/26533284/87df25a4-441f-11e7-8cac-5e0c348085b6.png)

**Comment by 008** [comment]
"Also, it would be nice if you posted settings or configs in articles like that one with 1700X testing where you boast 510 H/s."
+1 (but 610 not 510)

**Comment by 008** [comment]
make "Read only" config_0.txt file with Mouse R Click
tested!

**Comment by MunsuDC** [comment]
> make "Read only" config_0.txt file with Mouse R Click

Yeah this solves it, thanks!
The only problem now is that the miner seems to not register the profitability. It still is registered in web interface though.

**Comment by phenom77** [comment]
Hi all,

i think i found a better sollution for your issue.
I also run through this and used the workaround to set config_0.txt to read only.
After a few days of mining the nicehashminer GUI gets frozen and did not show hashpower from xmrstackcpu worker.

So i searched the web to get more info about how xmrstackcpu is working and i found another workaround.
To get it working leave the config_0 as it was created by NH or remove read only flag.
Just edit /config/benchmark_GEN-* and change the folowing entries:

      "ExtraLaunchParameters": "enable_ht=true"
      "LessThreads": 8

Keep in mind to set "LessThreads" matching your cpu thread count.
The result is it runs with threads matching real core and set affinity to 0,2,4,6.....

![image](https://user-images.githubusercontent.com/32238775/30782007-ef3e37f0-a129-11e7-8cfe-7500c0a9a09a.png)
