### ISSUE TITLE
r9 280x benchmark issue

### ISSUE THREAD

**Issue by tesh5581** [nicehash/NiceHashMiner-Archived#955]
Doesn't show the benchmark list. I've run the benchmark time and time again and it just displays this

![capture](https://cloud.githubusercontent.com/assets/16067339/26591707/1986184c-4591-11e7-8ee4-fd3262b2a1ff.PNG)

I've downloaded it and reverted to the previous driver and I'm now on the latest driver 17.3.1. 

Is there a fix to this?

Thanks!

**Comment by jakubmi9** [comment]
Stupid question: Did you click on the name of yoru GPU on the list above? If not, try doing that.

**Comment by tesh5581** [comment]
@jakubmi9 Yes I've did. I've used precise and standard benchmarking when choosing my card and sadly it doesn't show all of em' except for the one in the screenshot.

Thankfully I'm able to still mine but I'm not able to choose specific algorithms I'd like to mine. Equihash for my 280x's are much more profitable then the others but it mines majority of the time, dagger hash. 

I've gone through the issues section over here and apparently this issue has been mentioned way back since last year. 

Do hope there's a fix for it that I've just not found.

**Comment by jgoggan** [comment]
Anyone update on this?  I'm using NiceHash on AMD for the first time (been running it on a 1080 rig for a while now with no problems).  I have a rig with an R9 280X, an R9 280, and an HD 7970 (which is essentially a 280X) -- and I'm getting this exact same behavior.  It shows ONLY the CryptoNight algorithm in the list.  Benchmark runs (and goes through 42 steps!), but it never shows any algorithm other than CryptoNight.

So -- just curious if there were any updates to this issue?  Note that I'm running the latest release of NiceHashMiner Legacy (1.8.1.3 Pre-release 1).
