### ISSUE TITLE
Can't set to mine blake256r8vnl

### ISSUE THREAD

**Issue by ordnarf** [nicehash/NiceHashMiner-Archived#96]
Hello, i have read that nicehash miner support blake256r8vnl, but i can't set it to mine with it

**Comment by theLosers106** [comment]
Could you explain more? What did you do to "set" it to mine blake256r8vnl? NiceHashMiner will automatically choose to mine which ever algo that is the most profitable for you specific GPU(s). Please ensure that you have benchmarked first before running it.

**Comment by nicehashdev** [comment]
No response... closing.
