### ISSUE TITLE
750Ti Ethereum not mining

### ISSUE THREAD

**Issue by Jam0r85** [nicehash/NiceHashMiner-Archived#97]
I've got a 3 card 750Ti rig which runs everything fine apart from ethereum.

I've run the benchmark and no issues. Start mining and the proxy window shows up, the mining window pops open and I get what appears to be mining but Nicehash window shows that the card's are mining nothing.

**Comment by Singman33** [comment]
It's a parameter problem. For some of my 750 Ti cards, I should tweak them before, finding the right command line and adding that parameter to JSON file under "ExtraLaunchParameters".

**Comment by Jam0r85** [comment]
Any ideas on where to start for this? I'm used to X11 and Quark, etc but not Ethereum lol

**Comment by Singman33** [comment]
https://bitcointalk.org/index.php?topic=1368785.0

**Comment by theLosers106** [comment]
Is this issue resolved now? If not you should try to follow this -> https://github.com/nicehash/NiceHashMiner/issues/87#issuecomment-212713258

**Comment by ghost** [comment]
I am having a similar issue. Even benchmarking does not work for ethereum. I inserted the extra parameters in that link into the Nvidia 5.x with no luck.

**Comment by theLosers106** [comment]
@BurntOrange Are you using a 750ti too? You should try to use smaller numbers until it works..

**Comment by ghost** [comment]
I have 3 gtx750tis. I did try those numbers and ethminer.exe keeps crashing.

**Comment by theLosers106** [comment]
@BurntOrange yeahh.. I am not sure what numbers will work with 750ti but you should keep reducing the number and eventually it should work

**Comment by ghost** [comment]
@theLosers106  Which numbers do I reduce?

**Comment by ghost** [comment]
@theLosers106   The other part that is confusing me is they mention NVIDIA 3.X for a gtx750ti but the 750 runs 5.X

**Comment by theLosers106** [comment]
@BurntOrange 750ti is NVIDIA5.X .. I was just referring to the config part.. you should put it under NVIDIA5.X 's ExtraLaunchParameter .. the numbers you should reduce are cuda-grid-size and cuda-block-size

**Comment by ghost** [comment]
@theLosers106 I get to the benchmarking step on ethereum and the ethminer.exe continues to crash and also crash my nvidia drivers. Not sure what to do.

**Comment by theLosers106** [comment]
I would suggest you to disable ethereum for the 750ti as it is really inefficient to mine especially on Windows.

**Comment by nicehashdev** [comment]
750Ti cannot be used for mining Daggerhashimoto. You should disable it prior benchmarking.
