### ISSUE TITLE
So many algorithms are missing.

### ISSUE THREAD

**Issue by Frowny** [nicehash/NiceHashMiner-Archived#972]
![default](https://cloud.githubusercontent.com/assets/2028361/26775779/dace79c4-49ef-11e7-91d3-7b2a9065b27e.png)
5 seems like such a tiny amount. Shouldn’t they get filtered after the benchmark and not before?

**Comment by S74nk0** [comment]
@Frowny NVIDIA GPUs SM 5.0+ are and will be supported in the future. There will not be any focus for older GPUs. These algorithms are available at the moment for SM 3.0.
Closing issue...
