### ISSUE TITLE
Won't launch with newest Windows Update to Windows 10 Version 1703

### ISSUE THREAD

**Issue by shellbunner** [nicehash/NiceHashMiner-Archived#977]
Did the most recent Windows Update, and once I launch NiceHash v2.0.0.5 excavator opens and closes nonstop and very rapidly. It opens and closes a few times a second, and the only change to my system is the newest Windows Update to Windows Version 1703.

**Comment by nicehashdev** [comment]
https://github.com/nicehash/excavator/issues/1

**Comment by Squall-Leonhart** [comment]
display drivers MUST be clean installed following a major windows version upgrade, the upgrade breaks the installation.

**Comment by shellbunner** [comment]
Works great after a clean driver install. Thanks!
