### ISSUE TITLE
2nd Card not found, ethermine too slow

### ISSUE THREAD

**Issue by klis8** [nicehash/NiceHashMiner-Archived#978]
Hello, 
i have been running nicehash in my old pc and now on a new rig with mobo asus prime z270-a and 2 gigabyte 1060(that were working ok on the old pc) nicehash does not seem to be able to find the 2nd one.
also when running dagger/hashimoto i get a 2,3MHz speed only!!
i am running the newest drivers and version of nicehash and i have tried also with old ones.
attached are the logs i am getting.
can you please help me?

[debug_all_out.txt](https://github.com/nicehash/NiceHashMiner/files/1054985/debug_all_out.txt)
[debug_all_out_AMD.txt](https://github.com/nicehash/NiceHashMiner/files/1054984/debug_all_out_AMD.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/1054986/log.txt)

**Comment by Stephen-Randall** [comment]
If you are running Windows 10, you need to use Driver version 347.52 in order to fix the speed issue with Ethermine. Unfortunately the Nicehash miner does not support the CUDA version in that driver.

**Comment by Squall-Leonhart** [comment]
that driver doesn't support a gtx 1060 anyway.

**Comment by Stephen-Randall** [comment]
@Klismine Do you have the same issue in v1.7.5.13?

Looking at the Log it is showing both devices, and showing profit calculations for them.

I am not familiar enough yet with the UI to determine if Similar hardware is grouped in the UI that might be causing some confusion.

**According to the log, you are showing profit of GPU 0 + GPU 1 combined.** 



[2017-06-05 23:54:19] [INFO] [MiningSession] Current device profits:
	Profits for GPU-e531e169-e3c7-04a3-d0ba-8950738ec894 (GPU#1 Gigabyte GeForce GTX 1060 3GB):
		PROFIT = 0.001096547374	(SPEED = 223.3812685		| NHSMA = 4908.86)	[excavator_Equihash]
		MOST PROFITABLE ALGO: excavator_Equihash, PROFIT: 0.001096547374
	Profits for GPU-6b98c925-6fbc-a649-1b9f-f06a2853654e (GPU#2 Gigabyte GeForce GTX 1060 3GB):
		PROFIT = 0.001096547374	(SPEED = 223.3812685		| NHSMA = 4908.86)	[excavator_Equihash]
		MOST PROFITABLE ALGO: excavator_Equihash, PROFIT: 0.001096547374
[2017-06-05 23:54:19] [INFO] [MiningSession] PrevStateProfit 0, CurrentProfit 0.00219309474737782

**Comment by klis8** [comment]
Yeah I had managed to get them recognized for a little while, but running only on excavator. 
After trying a lot of thing i finally formatted the new rig and installed a newest version of windows 10. And everything worked as expected, finally. I still do not know what was the issue but i will further investigate and if i find anything i will inform you.
Thank you all for your comments.
