### ISSUE TITLE
Ati Hd 4830 512Mb mining problem

### ISSUE THREAD

**Issue by Anonymous3556** [nicehash/NiceHashMiner-Archived#99]
Hello Nice hash team.
I'm having problems with the graphic card HD 4830, I know it's not profitable but I am mining for fun.
So the problem is that I can only mine the following algorithms, keccak, blake256r8, blake256r8vnl, the others i can´t mine.
When I do benchmark in the others algorithms, the sgminer stops working and the benchmark stops also.
Also I have done the following ..... c: \ Users [your_username_here] \ AppData \ Local \ Temp] folder and Then re-run the benchmark for the algorithms are terminated during benchmark, it did not work.
I have windows 8.1 x64 full updated, I am using AMD Catalyst 13.1 software driver (this driver software has been made to Windows 8, but had to install because ati no longer does suport for this graphic card).
Many congratulations,this software work beautifully in my NVidea 930m.
Thank you and sorry for my english

**Comment by theLosers106** [comment]
Have you tried the latest version? It should fix that problem..

**Comment by Anonymous3556** [comment]
yes I've tried but not fix the problem, when i trie to run benchmark, this message apears (sgminer stops working)

**Comment by theLosers106** [comment]
Hey, I think it is the driver version or the kernel code as I can't get some of the algos to work on my old GPU too..
