### ISSUE TITLE
ERROR: 'Insufficient system resources to complete the requested service'

### ISSUE THREAD

**Issue by tigercamefortea** [nicehash/NiceHashMiner-Archived#994]
Hello,

I am trying to get NiceHash Miner working for the first time.

I am running Windows 10 with a EVGA GTX 1070 & 16GB of DDR4 Ram.

Everything else I download installs and runs with no issue but NiceHash Miner gives me the error:

'Insufficient system resources to complete the requested service'

Then it deletes the NiceHash file from where I just unzipped it too meaning I have to unzip it again each time I have tried something different inn troubleshooting.

I have since tried this on another new computer and EXACTLY the same thing happens.

Am I missing something really obvious here because I cannot seem to find any answers for this particular problem online?

Any help or suggestions for this to get working would be greatly appreciated.

Best Regards,
Tiger

**Comment by Timoulis** [comment]
Try to deactivate antivirus.
If all go fine with the antivirus deactivated, then make an exeption at it.

**Comment by tigercamefortea** [comment]
Thank you for help that has fixed this issue
