### ISSUE TITLE
Miner windows are not hidden

### ISSUE THREAD

**Issue by HyperCriSiS** [nicehash/NiceHashMiner-Archived#996]
Hi,
the mining windows are never hidden they are only minimized.
Is this a known issue?
Windows 10 64 Bit

Thanks and regards,
Hyper

**Comment by dadoremix** [comment]
yep
i use also 1.7.5.13
in options set.. hide miners
but xmr-stak-cpu.exe is still here

**Comment by S74nk0** [comment]
@HyperCriSiS @dadoremix some miners are started minimized and not hidden to make users aware that something is going on since people have been integrating NHM into botnets. We will not change this and will only make them more visible to reduce botnet abuse.

Closing...

**Comment by Codingale** [comment]
Not really a fix you know.. 

[RBTray](http://rbtray.sourceforge.net/) lets you hide almost any window to the tray. C# can also be used to completely hide a window in about 15 lines of code.
