### ISSUE TITLE
unable to launch fully 

### ISSUE THREAD

**Issue by Flickton** [nicehash/NiceHashMiner-Archived#999]
I get a error thrown once upon opening the next after the TOS has been accepted.
error 1
![capture1](https://user-images.githubusercontent.com/9166482/27001086-4d9721ac-4d8f-11e7-9692-08bf78b57b49.PNG)

error 2
![capture2](https://user-images.githubusercontent.com/9166482/27001118-adb57106-4d8f-11e7-9c55-b8e4378e4203.PNG)
details

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Root element is missing. (C:\Windows\Microsoft.NET\Framework\v2.0.50727\Config\machine.config) ---> System.Xml.XmlException: Root element is missing.
>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
>    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
>    at System.Xml.XmlTextReaderImpl.Read()
>    at System.Xml.XmlTextReader.Read()
>    at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
>    at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
>    --- End of inner exception stack trace ---
>    at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
>    at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
>    at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
>    at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
>    --- End of inner exception stack trace ---
>    at System.Configuration.ConfigurationManager.PrepareConfigSystem()
>    at System.Configuration.ConfigurationManager.GetSection(String sectionName)
>    at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
>    at System.Net.Configuration.WebRequestModulesSectionInternal.GetSection()
>    at System.Net.WebRequest.get_PrefixList()
>    at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
>    at System.Net.WebRequest.Create(String requestUriString)
>    at NiceHashMiner.Helpers.WebRequestTestGoogle()
>    at NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e)
>    at System.Windows.Forms.Timer.OnTick(EventArgs e)
>    at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8784 (WinRel.050727-8700)
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
> ----------------------------------------
> NiceHashMiner
>     Assembly Version: 1.7.5.13
>     Win32 Version: 1.7.5.13
>     CodeBase: file:///D:/Side%20install/NiceHashMiner_v1.7.5.13/NiceHashMiner.exe
> ----------------------------------------
> System
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8793 (WinRelRS2.050727-8700)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 7.0.0.0
>     Win32 Version: 7.0.1.18622
>     CodeBase: file:///D:/Side%20install/NiceHashMiner_v1.7.5.13/Newtonsoft.Json.DLL
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8784 (WinRel.050727-8700)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8784 (WinRel.050727-8700)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Management
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8794 (WinRelRS2.050727-8700)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8784 (WinRel.050727-8700)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8784 (WinRel.050727-8700)
>     CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> log4net
>     Assembly Version: 1.2.15.0
>     Win32 Version: 1.2.15.0
>     CodeBase: file:///D:/Side%20install/NiceHashMiner_v1.7.5.13/log4net.DLL
> ----------------------------------------
> System.Configuration
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8784 (WinRel.050727-8700)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> MessageBoxManager
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///D:/Side%20install/NiceHashMiner_v1.7.5.13/MessageBoxManager.DLL
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 

Then it just hangs here 
![capture3](https://user-images.githubusercontent.com/9166482/27001129-ec1e9936-4d8f-11e7-94b1-fcd374967820.PNG)

Thanks

**Comment by dadoremix** [comment]
did you try reinstall net framework.. 
2/3/4 ?

**Comment by Flickton** [comment]
yes just now, 
same results, but i just realized there was a window saying a internet connection is required, popped up after a undetermined amount of time...the pc is connected without a doubt
error 3
![capture4](https://user-images.githubusercontent.com/9166482/27006054-4ed266ac-4df9-11e7-8355-aea6405da0a4.PNG)

**Comment by dadoremix** [comment]
then is main server offline

try now.. 
at my side working
but nicehash time to time have server offline 10-15 min
you can see messages on FB pages of nicehash

**Comment by Flickton** [comment]
deleted and reinstalled .net in a different way than before and now everything is working

**Comment by sirwyatt** [comment]
Mind sharing how you reinstalled .net? Are you Windows 10? I'm having the same issue.

**Comment by Flickton** [comment]
Fully removed via windows features then reinstall via Microsoft link...sorry for quick and dirty...on mobile away from mining pc
